### ISSUE TITLE
Subnormal instead of denormal

### ISSUE THREAD

**Issue by jfbastien** [cplusplus/draft#1017]
As a follow-up to #1009: IEEE-754 2008 uses "subnormal" instead of "denormal". Since C++ refers to the 2008 version, we should use the same naming.

See its section 2.1.51 for the definition. See 2.1.15 for "denormalized number: See: subnormal number."

**Comment by jensmaurer** [comment]
Is there a copy of IEEE-754 2008 available somewhere so that I can verify the claims?

**Comment by jfbastien** [comment]
@jensmaurer http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=4610935

**Comment by jfbastien** [comment]
It's probably worth having an index entry for "denormal" still, which refers to subnormal. I'm not sure what to do about the traits though!

**Comment by sigfpe** [comment]
The trait has been like that for 20+ years, nobody really reported being
confused.  Any change now is more likely to introduce confusion and harm
for no real benefit.

**Comment by jfbastien** [comment]
@sigfpe any new trait needs to be in a paper and isn't editorial. The wording of the standard, however, should be editorially updated to reflect the new reference to the 2008 version of IEEE-754.
