### ISSUE TITLE
 [fpos.operations] Unclear assertions in requirements table

### ISSUE THREAD

**Issue by jlaire** [cplusplus/draft#1031]
The first row in "Table 108 — Position type requirements" contains expression `P(i)` in the first column and assertion `p == P(i)` in the last column. It is not clear what `p` refers to, since it is not used in the expression. Perhaps it is a typo and the assertion should be `i == P(i)`.

The expression `streamsize(o)` has a corresponding assertion `streamsize(O(sz)) == sz`. The meaning of this is also unclear, since `sz` does not appear in the expression.

**Comment by jensmaurer** [comment]
Regarding the first row: I have no clue what the editorial fix here should be. "p" is just any value of type P, so "p == P(i)" seems totally misguided. I'm asking for an LWG issue.

Regarding the conversions in the last row of the table: sz is introduced in the paragraph before the table: "sz refers to a value of type streamsize". So, these rows tell you that conversion from streamsize to streamoff, then back to streamsize is value-preserving for all possible values of type "streamsize".

**Comment by jensmaurer** [comment]
http://cplusplus.github.io/LWG/lwg-active.html#2832

**Comment by jensmaurer** [comment]
See #2134 for the wholesale cleanup here.
