### ISSUE TITLE
[tables] Formatting of "Effects:", "pre:" and "post:"

### ISSUE THREAD

**Issue by jlaire** [cplusplus/draft#1032]
Tables listing requirements on expressions, for example "Table 86 — Associative container requirements", have a column that may specify effects, pre-conditions and post-conditions. The "*Effects:*" is capitalized and in italics, but "pre:" and "post:" are not. The tables would look nicer if "pre:" and "post:" were formatted the same way as "*Effects:*" is.

I have just noticed that "Table 29 — Allocator requirements" uses "Effect:" without italics, "*pre:*" with italics  and "post:" without italics.

**Comment by tkoeppe** [comment]
It would be even better to not have tables at all and come up with a more sensible way of presenting requirements.

**Comment by jlaire** [comment]
Duplicate of https://github.com/cplusplus/draft/issues/792
