### ISSUE TITLE
monotonic_buffer_resource: initial_size vs buffer_size

### ISSUE THREAD

**Issue by yurikhan** [cplusplus/draft#1055]
In [memory.resource.monotonic.buffer.ctor], ¶4:

> Sets […] `next_buffer_size` to `initial_size` (but not less than 1) […]

However, the name `initial_size` is not in scope at that point. Was `buffer_size` intended?

**Comment by tkoeppe** [comment]
@AlisdairM: This looks like your kettle of fish.

**Comment by timsong-cpp** [comment]
See https://github.com/cplusplus/fundamentals-ts/pull/66
