### ISSUE TITLE
Inconsistent formatting of "public" and "inline" in sentences

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#106]
There are a bunch of inconsistencies around whether to `\tcode` `public` and `inline`, e.g. in "public inline member function" throughout the standards text.

**Comment by jensmaurer** [comment]
As far as I understand, the rule is to use \tcode{} when referring to syntax appearing in a program, and normal text when we refer to an attribute of a function. For example, a function can be inline even if it's not declared with the `inline` keyword (e.g. defined in-class). And `public` (the keyword) isn't even part of the function declaration.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: We agree that we use \tcode when referring to syntax, and otherwise not. We should add that to the style guide on the wiki.

**Comment by jensmaurer** [comment]
Wiki page was updated.
