### ISSUE TITLE
Tildes in index entries

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#1064]
We use two distinct styles for multiword index entries, both pervasively:

* `\indextext{hello world}`
* `\indextext{hello~world}`

What is the purpose of the tilde? Does it have any special meaning in the index, or is it just a non-breaking space? In the latter case, why are we doing that? There seems to be no value in trying to force a particular (probably poor) line breaking decision on the already constrained index.

What's turning this question from a mere curiosity into a serious issue is that if you *mix* the two styles for the purportedly same entry term, you get two separate index entries, and moreover, the tilde collates differently from the space, producing a surprising index order.

Unless there's a good reason against it, I would recommend killing all those tildes.

**Comment by cpplearner** [comment]
dup/general case of #664

**Comment by tkoeppe** [comment]
Yeah, we can keep both issues; #664 to fix existing double-indexing problems, and this one to decide on a single style.

**Comment by jensmaurer** [comment]
See also #398.

**Comment by zygoloid** [comment]
I'm not aware of any reason for these tildes, and I'd be surprised if they're fixing a line-breaking issue in the index rather than causing one. Can you try stripping them (say, with `sed`) and see if there are any visual differences? If not, let's get rid of them all. (If there are differences, we'll need to understand why.)

**Comment by tkoeppe** [comment]
@jensmaurer: You are good with `sed`, right?

**Comment by tkoeppe** [comment]
Perfect, thanks! This even saves a page, thanks to deduplicating index entries.

**Comment by jensmaurer** [comment]
Augmented "style guidelines" wiki page accordingly.

**Comment by tkoeppe** [comment]
Thanked!
