### ISSUE TITLE
[class.union]/3 note contradicts normative wording

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1073]
See https://groups.google.com/a/isocpp.org/d/msg/std-discussion/4BWeZosWYiY/5LKz98-dBQAJ

We should weaken the note, for instance by changing "must" to "should typically" and "will" to "will usually".

**Comment by JABelloc** [comment]
@jensmaurer 
In reference to [your commit](https://github.com/jensmaurer/draft/commit/b124e3d095e255acafc16abb07d5fe74f5e7ec31), I believe the added sentence "Absent default member initializers" is necessary only for the non-trivial default constructor.  That is, the additional condition imposed by the alluded sentence should not affect the other two constructors, the assignment operators and the destructor, mentioned in [class.union]/3.

**Comment by jensmaurer** [comment]
@JABelloc: Right. However, I think the note is now correct post-my patch, although it's not completely describing the situation. But then, it's a note, not a normative statement. I don't think I should repeat all the complexity of the real rule in this note, which is just trying to say "you can have non-trivial data members in a union, but if you do, you need to do the legwork yourself".
