### ISSUE TITLE
[lib] When to use 'shall' in library clauses?

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1086]
In the core clauses, we strive to be consistent to use "shall" for requirements on user programs that require a diagnostic when violated. Requirements on the implementation are described in regular present-tense prose. (We sometimes use "shall" in phrases like "the implementation shall ...", in which case no ambiguity arises.)

In the library clauses, the rules are less clear and should be clarified. In particular, since most library requirements on programs cause undefined behavior, rather than an ill-formed program, when violated.

At the very least, for a "Requires" clause, the use of "shall" for runtime preconditions seems redundant.

Whatever we come up with, we should spell out the rules explicitly in the respective introduction sections.

Generalized from #417.

**Comment by jwakely** [comment]
My P0411 proposal is an attempt to stop using Requires for runtime preconditions, so that violations of "shall" requirements in a Requires requires a diagnostic. I have also volunteered to write another huge proposal making the use of "shall" in the library clauses consistent with how it's used in the core clauses.

**Comment by jensmaurer** [comment]
I agree with the idea to separate runtime preconditions from compile-time diagnosable rules.
If we're in a section clearly labeled as "Preconditions", I find the use of "shall" not really necessary. Sentences with "is" simply read better. I understand that the "Requires" section will have diagnosable conditions, so consistency with core would suggest to continue to use "shall" there.
Further, I'd like to point out that switching "shall" to "is" in clauses marked as [runtime] "Preconditions" by LWG is probably editorial and would save another huge paper.

**Comment by jensmaurer** [comment]
See also [P0788](http://wg21.linjk/p0788).

**Comment by jensmaurer** [comment]
Marshall's "mandating" papers have addressed this issue, and clearly separate diagnosable requirements and runtime preconditions into different descriptive elements.
