### ISSUE TITLE
[lib] Inconsistent style in \complexity

### ISSUE THREAD

**Issue by jlaire** [cplusplus/draft#1088]
Wording of complexity requirements is inconsistent in a couple of ways.

### Noun-phrase or sentence?

"Exactly N applications of `f`."
vs.
"Applies `f` exactly N times.`"
vs.
"It takes approximately N comparisons."

The first form seems to be the most common.

### Time or space complexity, or both?

It is not always made explicit whether the requirement is referring to time or space complexity, or both.

"Linear time." vs. "Linear."
"Constant time." vs. "Constant."

17.5.1.4 says that the *Complexity:* element specifies "the time and/or space complexity of the function", so being explicit about this would be good.

### N log N vs. N log(N)

This is minor, but `N \log(N)`, `N \log N` and `N \log{N}` are all used.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Use parens for log only when the argument is long and could be ambiguous, e.g. log(N+1). "It takes" is cringe-worthy. 

"Exactly N applications" and related phrases are all ok, no need to harmonize.

Time or space complexity is LWG territory.

**Comment by jensmaurer** [comment]
The remaining question "Time or space complexity, or both?" was sent to LWG.

**Comment by jensmaurer** [comment]
[LWG issue 2949](http://cplusplus.github.io/LWG/lwg-active.html#2949)
