### ISSUE TITLE
== operator vs operator == (and similar cases)

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#109]
Throughout the core clauses, especially in [expr], we are inconsistent in how we refer to operators. Pick a style and run with it.

Examples:

[expr.add]:

> The additive operators `+` and `-`

[expr.add]:

> ... the binary `+` operator ...

[expr.eq]:

> The `==` (equal to) and the `!=` (not equal to) operators

[expr.log.and]:

> The `&&` operator groups left-to-right.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: More consistency doesn't seem to help comprehension of the standard. No harmonization required.
