### ISSUE TITLE
Meaning of "program-defined"

### ISSUE THREAD

**Issue by jlaire** [cplusplus/draft#1090]
There are 4 instances of the term "program-defined" in the standard. Does it have the same meaning as "user-defined"?

**Comment by jensmaurer** [comment]
Yes, please replace with "user-defined".

**Comment by jlaire** [comment]
I just noticed that there are two instances of "program-supplied" and four of "user-supplied", should these be replaced as well?

**Comment by jensmaurer** [comment]
program-supplied to user-defined: yes, please
user-supplied to user-defined: Not when we're talking about a value ("user-defined value" sounds wrong), but only when we're talking about types.

**Comment by jensmaurer** [comment]
See http://cplusplus.github.io/LWG/lwg-active.html#2139
