### ISSUE TITLE
[lib] Referring to \requires, \effects and others

### ISSUE THREAD

**Issue by jlaire** [cplusplus/draft#1091]
Function descriptions can contain elements introduced with \requires, \effects, \sync, etc., and in some places the standard text refers to these elements. It does this in several different ways.

- 17.5.1.4p4 uses the same macros that are used to define these elements when mentioning them. This is a bit ugly because it includes the colon.

- A couple of places use `\synopsis{Effects}` or `\synopsis{Throws}`, which looks very wrong because it's bold.

- There's at least one instance of ` ``Requires''`.

- There's at least one instance of `\emph{Returns}`.

Visually, I like \emph the most, since it's rendered the same way as the definitions, but without the colon.

There are also many different nouns used when talking about these: at least element, paragraph, section, clause and subclause. I wonder whether clause and subclause are correct.

I can create a pull request making these consistent if someone decides which form to use. I think either the macros themselves (already used in many places, but come with the colon) or \emph would be best. I can leave the nouns as-is or replace uses of clause/subclause with element or section.

**Comment by tkoeppe** [comment]
I'm fine with keeping the colon. We do the same when we explain how "[*Note:*]" and "[*Example:*]" are typeset.

**Comment by jlaire** [comment]
Thanks, I'll go with that.
