### ISSUE TITLE
Run-on paragraph in [dcl.spec.auto]/7

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#111]
In the C++14 CD, there is a sequence of three paragraphs, the second and third of which are not numbered, like this:

> When a variable declared using a placeholder type is initialized, [...] Let `T` be the declared type of the variable or return type of the function.
> If the placeholder is the `auto` _type-specifier_, [...]
> If the placeholder is the `decltype(auto)` _type-specifier_, [...]

It is tempting to just add paragraph numbers to the second and third paragraphs, but these are really not self-contained. The second and third ones depend on the definitions in the first.

Clean this up editorially.

**Comment by jensmaurer** [comment]
I can no longer find this issue in the current Working Draft.
