### ISSUE TITLE
Use teletype font for T throughout [variant]

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1115]
Within [variant] we use `$T_i$` to denote the i'th template argument. This should probably be \tcode{T}$_i$ throughout.

**Comment by tkoeppe** [comment]
Another option is `$\mathtt{T}_i$`, in case you find yourself in the middle of more math.

**Comment by jensmaurer** [comment]
I'd like to point out that the "tuple" wording has the same issue.
