### ISSUE TITLE
Style of "equivalent to"

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#1119]
In the library, we have a term of art "equivalent to" to specify effects. What we don't have is a consistent way of formatting it. Currently observed forms:

1. Equivalent to: [codeblock]
1. Equivalent to: `statement;`
1. Equivalent to: `expression;`
1. Equivalent to `expression`.
1. Equivalent to `statement;` where foo is bar.

I think we should definitely have the colon after "to", and we should probably have both a codeblock and an inline form.

**Comment by jwakely** [comment]
This was discussed earlier this year I think we agreed that the third form is wrong (we shouldn't use a semi-colon after an expression, only after a statement) but that we do want all three of codeblock/statement/expression.

**Comment by jensmaurer** [comment]
It seems we're using "Equivalent to `expression`." quite a lot, and only use a colon if a statement or codeblock follows.

**Comment by tkoeppe** [comment]
Maybe we can settle on these forms:

### Codeblock

-?- *Effects:* Equivalent to:

    statement;

where we may optionally explain things used in the block.

### Inline statement

-?- *Effects:* Equivalent to: `statement;`

### Inline expression

-?- *Effects:* Equivalent to `expression`.

-?- *Effects:* Equivalent to `f(n)`, where `n` is a value.

**Comment by jensmaurer** [comment]
Sounds minimally-invasive vs. the status quo.

**Comment by jwakely** [comment]
See also #694

**Comment by jensmaurer** [comment]
@tkoeppe: Given Richard's explanation in #694, is there still some open issue? Note that the third of your forms above is a statement-expression, i.e. a valid statement.

**Comment by tkoeppe** [comment]
OK, I think the detail that was missing from #694 is how to deal with continuing sentences, e.g. when something needs a retrospective definition. My concrete proposal here is to place a comma after an inline statement and never use an inline expression.

**Comment by jensmaurer** [comment]
Do you have specific examples?

**Comment by tkoeppe** [comment]
@jensmaurer: I realise that's a valid statement, but the idea is to partially specialize on such patterns and prefer "inline `expression`.".

**Comment by tkoeppe** [comment]
@jensmaurer: E.g. 20.7.2.4/1. I would add a comma there.

**Comment by tkoeppe** [comment]
Some "equivalent to" statements are also just poorly constructed. E.g. 21.3.1.6.2, compare p6 vs p17.

**Comment by tkoeppe** [comment]
@jensmaurer: Please leave this bug open until we have at least updated the style wiki.

**Comment by jensmaurer** [comment]
One aspect that wasn't discussed yet is "Equivalent to: `return expression;`" vs. "Equivalent to `expression`." It seems we could get by with the latter, but we usually do "return `expression`" if expression has a type other than void.

**Comment by zygoloid** [comment]
If I recall correctly, we chose to use "Equivalent to: `return expression;`" in cases where a return value is produced, to make the connection between the expression and the value clearer.

See https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines#writing-effects-in-a-function-description for the existing description of the rules here.

**Comment by jensmaurer** [comment]
@tkoeppe: That covers it, right?

**Comment by tkoeppe** [comment]
@jensmaurer: The wiki is still missing information on how to continue with trailing definitions after the code, and maybe it should include a disambiguation rule for "equivalent to function-call" that I mentioned above.

**Comment by jensmaurer** [comment]
I've updated the wiki.
