### ISSUE TITLE
[re.regex.const] missing multiline from LWG2503

### ISSUE THREAD

**Issue by cubbimew** [cplusplus/draft#1129]
LWG2503 added `multiline` to `std::regex_constants` (bf6a98d), but did not add it to  `std::basic_regex`, which contains clones of all other syntax options (`[re.regex.const]` with synopsis in `[re.regex]/3`)

Does it still qualify as editorial? The text in `[re.regex.const]` says "The static constant members are provided as synonyms for the constants declared in namespace regex_constants.", but pedantically speaking it doesn't say "all constants defined" and so is not a contradiction.

**Comment by jensmaurer** [comment]
Personally, I believe the intent is clear, thus adding "multiline" to [re.regex.const] seems editorial to me.
