### ISSUE TITLE
Missing definition of "direct-non-list-initialization"

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1130]
The specification of `optional` uses various forms of "direct-non-list-initialization", which is defined in [[general.defns.direct-non-list-init]](https://rawgit.com/cplusplus/fundamentals-ts/v2/fundamentals-ts.html#general.defns.direct-non-list-init) in the Fundamentals TS, but that definition wasn't added to the IS working paper for the merge.

**Comment by zygoloid** [comment]
Looks like we could instead just remove the (unnecessary) new term. Example:

> If `rhs` contains a value, initializes the contained value as if direct-non-list-initializing an object
of type `T` with the expression `*rhs`.

could be rewritten as

> If `rhs` contains a value, initializes the contained value with the initializer `(*rhs)`.

This is shorter, simpler, and doesn't require inventing a new term for something that the core language can already express. We should first run this past LWG to make sure (a) they're OK with this, and (b) they change their habits (and the fundamentals TS) to apply the same pattern going forward.

**Comment by AlisdairM** [comment]
This is https://cplusplus.github.io/LWG/lwg-defects.html#2872 and should be applied to the DIS at Kona.

**Comment by jwakely** [comment]
It's a shame we'll continue our bad habits now.

**Comment by zygoloid** [comment]
Term has been added to library definitions.
