### ISSUE TITLE
Format indexed variables with code and maths properly

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#1139]
We still have a number of "indexed" variables, like `Ti` or `TiD`, that should be formatted with the variable name in code and the index in maths, either `\tcode{T}$_i$` or `$\mathtt{T}_i$` or `$\mcode{T}_i$` provided someone adds an `\mcode` macro, or `$\text{\tcode{T}}_i$`.

Please also look out for concrete indexes like `$T_0$` etc.

**Comment by tkoeppe** [comment]
48efdfe014549e6d116ce12ca427f7df0e0f8c70 contributed to this, but there's more work left to be done in [tuple.tuple].

**Comment by jensmaurer** [comment]
Waiting for #1142 to be applied to avoid merge conflicts.

**Comment by tkoeppe** [comment]
c2144122667f95b65859887012c8bfed4b795225 also contributed to this.

**Comment by jensmaurer** [comment]
@tkoeppe: Do you have a suggestion how to format `TiD = decay_t<Ti>` ? My guess would be `T_i^D = decay_t<T_i>`, but maybe you've got another idea.

**Comment by tkoeppe** [comment]
@jensmaurer: How about `TD_i = decay_t<T_i>`? It's very unusual to have the index in the middle.

**Comment by zygoloid** [comment]
Any further problems can be addressed by point issues; having an omnibus issue is no longer valuable.
