### ISSUE TITLE
Comments in code example in footnotes should be italic like elsewhere

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1152]

**Comment by jensmaurer** [comment]
This is 13.3.3.1p10.

My opinion: Move the footnote into a regular note and rephrase it substantially. The normative sentence after the footnote should also become part of the note. (It's redundant here.)

**Comment by Eelis** [comment]
Spotted another one: http://eel.is/c++draft/over.match.best#footnote-133

**Comment by jensmaurer** [comment]
@Eelis: This is exactly the one this issue is talking about, and it's fixed by my proposed patch.

**Comment by jensmaurer** [comment]
Fixed by #1232.

**Comment by tkoeppe** [comment]
(The problem with footnotes is that the listings environments don't work in them, so you don't get any of the magic features like text-front comments. Best to avoid footnotes that require commented code!)
