### ISSUE TITLE
BaseCharacteristic, unlike all other technical terms we define, is in CamelCase

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1154]
"BaseCharacteristic" should be simply "base characteristic". Using camel case for a plain English term is bizarre.

**Comment by tkoeppe** [comment]
Given that this came up in recent motions, let's reopen this just to verify that the DIS doesn't contain any new occurrences of the case camel.

**Comment by jensmaurer** [comment]
$ grep BaseChar *.tex | wc -l
0
