### ISSUE TITLE
[expr.prim.lambda] p 6, 7 obnoxiously long

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#1155]
Paragraphs 6 and 7 of [expr.prim.lambda] are very long. P 7 contains 2 notes and 3 examples!

Could we please rewrite those to become multiple paragraphs? Consider having long examples be paragraphs on their own.

@jensmaurer, @zygoloid, any takers?

**Comment by zygoloid** [comment]
Hmm, while we're here, it might be good to add some subsections to [expr.prim.lambda]; that subclause is a sprawling mess that's grown without any cleanup. Perhaps something like:

 * Closure types [expr.prim.lambda.closure]: paragraphs 4 (everything except the specification of the type of a *lambda-expression*), 6, 7, 8, 21, 22, 23
 * Captures [expr.prim.lambda.capture]: paragraphs 9-20, 24, 25, 26

... with the remaining text left in [expr.prim.lambda] itself. I'd also like a better description of closure types, perhaps first enumerating the different kinds of members that a closure type has and then describing those members and their properties.
