### ISSUE TITLE
[re.regex]/3 regex_constants presentation

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1163]
Each constant takes up two lines. That's ugly.

We could squeeze each on a single line (with comfortable padding) if we used the flag_type alias for regex_constants::syntax_option_type.

Opinions?

**Comment by tkoeppe** [comment]
I like the idea of compressing the presentation, which is needlessly noisy at the moment.

@jwakely, @AlisdairM, do you think that would be in line with existing practice?

**Comment by AlisdairM** [comment]
makes sense to me too, but only if applied consistently through the clause, rather than cherry picking the list of constants in the class definition - we don't want to use two ways of saying the same thing.

**Comment by jwakely** [comment]
Using `flag_type` might be the least noisy form.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Apply flag_type to synopsis. Remove [re.regex.const]. Call out in the editor's report.
