### ISSUE TITLE
[basic.scope.class] CWG 2331: is redundant

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#1169]
The first four paragraphs of [basic.scope.class] (3.3.7) are somewhat reduntant. As @zygoloid noted:

* The normative paragraphs are 4 and 2.
* Paragraph 1 is subsumed by p4.
* Paragraph 3 follows from existing rules for name hiding.

We felt that this was too much to reword editorially though and would like CWG guidance. We could produce a pull request and let CWG decide whether the change is editorial, and if not the proposed wording could be moved into a Core issue.

**Comment by jensmaurer** [comment]
Did someone e-mail Mike Miller already?

**Comment by tkoeppe** [comment]
@jensmaurer: Not yet. Could you perhaps? Will you be in the upcoming teleconference?

**Comment by jensmaurer** [comment]
Sent e-mail to Mike Miller.

Yes, I will join the teleconference next Monday.

**Comment by jensmaurer** [comment]
see [http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2331](CWG 2331)

**Comment by zygoloid** [comment]
Closing now we are tracking this as a core issue.
