### ISSUE TITLE
"possibly const" vs "possibly \tcode{const}" vs "possibly \keyword{const}"

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#117]
"possibly const" appears five times in the current draft. "possibly \tcode{const}" appears ten times. Clean this up, make a rule for it.

Update added by @burblebee on 11/15/22:
We've since added several more of the above variations as well as the addition of  "possibly \keyword{const}".

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Similar to inline / public. Thus, we should generally not use "possibly \tcode{const}".

**Comment by zygoloid** [comment]
See also issue 106.

**Comment by jensmaurer** [comment]
Postponing until #1497 was applied to avoid editing conflicts.

**Comment by burblebee** [comment]
> Editorial meeting consensus: Similar to inline / public. Thus, we should generally not use "possibly \tcode{const}".

To clarify, all occurrences should become `possibly const`, correct?

**Comment by JohelEGP** [comment]
See https://github.com/cplusplus/draft/pull/4405#discussion_r535507929 with regards to `\keyword`. @tkoeppe, can `\keyword` be rationalized on the wiki?

**Comment by tkoeppe** [comment]
I think the original decision to say "possibly const" (without markup) is uncontested; shall we just execute that?

**Comment by sdutoit** [comment]
> I think the original decision to say "possibly const" (without markup) is uncontested; shall we just execute that?

Yes please, after these 9+ years! :)

**Comment by tkoeppe** [comment]
@sdutoit Why did you leave? :-)

**Comment by tkoeppe** [comment]
@burblebee What do you think needs a decision here? Don't we already have several decisions above?

**Comment by burblebee** [comment]
> I think the original decision to say "possibly const" (without markup) is uncontested; shall we just execute that?

Sure! Sorry this resolution wasn't clear to me, but
"we should generally not use possibly \tcode{const}."
doesn't say what we *should* do, so thank you for the clarification! There is now the added complexity with \keyword{const}, but I feel the "just say possibly const" resolution works there to.

**Comment by jwakely** [comment]
Arguably we should just say "type `X` or `const X`" instead of "type (possibly const) X".

Not using keyword markup for "possibly const" does look a bit odd when we have:

> an lvalue of type (possibly const) `X` or an rvalue of type `const X`,

Based on the decision above, one "const" is is code font and one isn't.

**Comment by tkoeppe** [comment]
@jwakely That one case you pointed out could indeed be rewritten a little to avoid this awkwardness.
