### ISSUE TITLE
Inconsistent noexcept

### ISSUE THREAD

**Issue by W-E-Brown** [cplusplus/draft#1171]
The declarations in [pointer.traits.functions] have inconsistent noexcept specifications: they are inconsistent with each other, and one of them is inconsistent with the relevant part of the synopsis shown above (following [pointer.traits]/1).

**Comment by zygoloid** [comment]
I don't immediately see the problem. It looks to me like the general version is not `noexcept` (in both sections), and the pointer specialization is `noexcept` (in both sections). Given that the former calls arbitrary user code (`Ptr::pointer_to(r)`) and the latter only calls a known-non-throwing function (`addressof(r)`), I suspect this is already presented as LWG intended.

**Comment by W-E-Brown** [comment]
Sorry; I must have misread the synopsis.  Closing.
