### ISSUE TITLE
"T* p" vs. "T *p"

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#118]
The library is inconsistent about the placement of the ptr-operator, sometimes even within the same class, e.g. [util.smartptr.shared] has

```
template<class Y> explicit shared_ptr(Y* p);
template<class Y, class D> shared_ptr(Y* p, D d);
[...]
template<class Y> shared_ptr(const shared_ptr<Y>& r, T *p) noexcept;
```

It would be better to be consistent. A couple of quick searches indicate the more common placement is on the left with the type (which is the correct style IMHO ;-)

**Comment by tkoeppe** [comment]
Agreed, and I think we're getting better at this.

Do you have a query that let's us track whether this issue is complete?

**Comment by oblitum** [comment]
If any of this start to be adopted, I hope at last it doesn't slip into the language core, as [@zygoloid suggested](https://github.com/cplusplus/draft/issues/430#issuecomment-70932522).

**Comment by jensmaurer** [comment]
Issue #166 claims this was fixed for pointer declarators. At least the particular example shown above is fixed.
