### ISSUE TITLE
[diff] Capitalization of headings

### ISSUE THREAD

**Issue by jlaire** [cplusplus/draft#1200]
Most clause headings mentioned in Annex C are not capitalized. For example:

**`C.2.11 Clause 20: general utilities library   [diff.cpp03.utilities]`**
**`C.3.7  Clause 27: input/output library [diff.cpp11.input.output]`**

But some of them are.

**`C.2.16 Clause 27: Input/output library [diff.cpp03.input.output]`**
**`C.4.9  Clause 20: General utilities library [diff.cpp14.utilities]`**

I think they should be all capitalized to match the style in the actual clause headings.

**Comment by tkoeppe** [comment]
Headings are generally set in sentence case, and our sentence style does not generally capitalize after a colon. So the right solution is to fix the inappropriate capitalization. I'll handle this.
