### ISSUE TITLE
The ValueType parameter of std::any_cast is confusingly named

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1202]
```
template<class ValueType>
  ValueType any_cast(const any& operand);
template<class ValueType>
  ValueType any_cast(any& operand);
template<class ValueType>
  ValueType any_cast(any&& operand);
```

This template parameter is confusing, because it's really the return type of the function, _not_ the type of the contained value in the `any` (as shown by the fact the requirements say it must be a reference, or copy constructible). When the parameter is a reference the functions return by reference, not by value, and `ValueType` is not the type of the value in the `any`. The parameter can be `const` but the value in the `any` is not a const-qualified type.

Elsewhere in the library "value type" is used for containers, iterators, and allocators, and must be an object type, not a reference type.

I suggest renaming this to make it clearer that it can be a reference, and is not the type of the value in the `any`.  `Result` or `ResultType` might be better. Or just `Type` or `T`.

For the `any_cast` overloads taking pointers the `ValueType` parameter is OK, as in that case it does refer to the type of the value in the `any`.

**Comment by timsong-cpp** [comment]
`any`'s member functions (ctor, `=`, `emplace`) have similar problems. The actual type of the value being stored is the decayed type, not actually `ValueType`, despite the name.

The pointer variant of `any_cast` also has issues - `ValueType` can be cv-qualified (the comparison is by `typeid` which drops cv-qualification), but the value being stored is not.

**Comment by jensmaurer** [comment]
I'm preparing a patch that replaces ValueType with T and uses VT where the description seems to hint we're dealing with the actual ValueType.

**Comment by jwakely** [comment]
That sounds good to me - thanks.
