### ISSUE TITLE
"; otherwise" vs ". Otherwise" vs ". Otherwise,"

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#122]
When specifying else-cases in paragraph text, a common idiom in the draft is to write

> If .... then <something>. Otherwise <something else>

or

> If .... then <something>; otherwise <something else>

The full sentence end vs semicolon is one inconsistency. Another is whether a comma follows the "otherwise". Existing usage in the draft is mixed between all four combinations.

**Comment by jensmaurer** [comment]
I think the style varies with complexity, among other things. I'm not sure enforcing the consistency is helpful here.
Richard?

**Comment by jensmaurer** [comment]
Editorial meeting consensus: No need to enforce the style.
