### ISSUE TITLE
[sf.math] parenthesized "of the first/second kind"?

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1250]
We're inconsistent here.

For example, [sf.cmath.cyl_bessel_j] has parenthesis in the heading and no parenthesis in the running text. The synopsis follows the spelling in the heading.

**Comment by tkoeppe** [comment]
ISO-80000-2 never parenthesizes anything. We should definitely never parenthesize "of the {first,second} kind", and also never "incomplete".

You could argue that "complete" may be parenthesized, because it's implied, but we may as well also keep it unparenthesized.
