### ISSUE TITLE
[cstdint.syn] should list the macros it defines

### ISSUE THREAD

**Issue by cubbimew** [cplusplus/draft#1276]
All other C header synopses, such as `[cfloat.syn]` just above, now list every macro they define on its own line, but `[cstdint.syn]` instead describes them in prose using unique pattern-matching language.  Should it be made as explicit as the other C header synopses?

**Comment by jensmaurer** [comment]
See also pull request #843.

**Comment by jensmaurer** [comment]
Duplicate of #843.
