### ISSUE TITLE
More pre:'s and post:'s in library specification

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1281]
*pre:* and/or *post:* are also used in:

- Table 28, NullablePointer requirements (in [nullablepointer.requirements])
- Table 31, Allocator requirements (in [allocator.requirements])
- Table 54, Character traits requirements (in [char.traits.require])
- Tables in [iterator.requirements]
- Table 104, Random number engine requirements (in [rand.req.eng])
- Table 105, Random number distribution requirements (in [rand.req.dist])
- Table 112, Position type requirements (in [fpos.operations])

**Comment by timsong-cpp** [comment]
There are also some hand-written `Effect:` in Table 31 instead of `\effects`, and many `yields:` in table 54 instead of `\returns`.

**Comment by jensmaurer** [comment]
Thanks for the list. Pull request #1273 only addressed the [containers] section.
