### ISSUE TITLE
[char.traits.specializations] Inconsistent punctuation in stable names of subsections

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1293]
This section has 4 subsections:

* [char.traits.specializations.char]
* [char.traits.specializations.char16_t]
* [char.traits.specializations.char32_t] ← note the underscore
* [char.traits.specializations.wchar.t] ← note the period

**Comment by jensmaurer** [comment]
These are stable names, so we shouldn't change the spelling lightly.

Also, the "specializations" part in the stable name could benefit from some abbreviation, for the benefit of indexes etc.

**Comment by tkoeppe** [comment]
I'm not sure if there's a) any way to "resolve" this issue, and b) any problem that needs to be solved here.

**Comment by Eelis** [comment]
Well, I guess the obvious way to resolve this is to change "wchar.t" to "wchar_t". But if the theory is that such a punctuation fix would tremendously inconvenience people when they read the existing stable name somewhere and try to look it up, then by all means close this ticket (because while I find that thoroughly unconvincing, I'm not interested in arguing that point).

**Comment by tkoeppe** [comment]
I'm still unconvinced that there is a problem here that needs to be solved. Stable names are called stable because we *don't* generally change them, so I'd like to see a much more convincing analysis spelled out why you think this is needed. Feel free to reopen if you have one.
