### ISSUE TITLE
Decide on \defn{thing}{s} vs \defnx{things}{thing}

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1295]
There are currently two styles in use for definitions that occur in plural form in the text but have a singular index entry:

* \defn{thing}{s}
* \defnx{things}{thing}

The difference is that the former does not italicize the 's'.

Occurrences of style A:

    classes.tex:1737:member. A union-like class \tcode{X} has a set of \defn{variant member}{s}.
    containers.tex:2104:grouped into \defn{equivalent-key group}{s} such that all elements of each
    expressions.tex:4862:\defn{constant expression}{s}. \begin{note} Constant expressions can be evaluated
    intro.tex:905:The \defn{immediate subexpression}{s} of an expression \tcode{e} are
    iterators.tex:105:called \defn{mutable iterator}{s}. Nonmutable iterators are referred to
    iterators.tex:106:as \defn{constant iterator}{s}.
    special.tex:828:Such functions are called \defn{conversion function}{s}.

Occurrences of style B:

    basic.tex:2194:A \defn{program} consists of one or more \defnx{translation units}{translation unit}
    basic.tex:3609:\defnx{scalar types}{scalar type}. Scalar types,
    basic.tex:3707:There are five \defnx{standard signed integer types}{standard signed integer type} :
    basic.tex:3720:\defnx{extended signed integer types}{extended signed integer type}.
    basic.tex:3723:\defnx{signed integer types}{signed integer type}.
    basic.tex:3760:collectively called \defnx{unsigned integer types}{unsigned integer type}. The range of non-negative
    basic.tex:3768:are collectively called the \defnx{standard integer types}{standard integer type}, and the extended
    basic.tex:3771:\defnx{extended integer types}{extended integer type}.
    basic.tex:3912:\defnx{references}{reference} to objects or functions of a given
    expressions.tex:126:In some contexts, \defnx{unevaluated operands}{unevaluated operand}
    expressions.tex:1343:are collectively called \defnx{unary folds}{unary fold}.
    intro.tex:569:Objects can contain other objects, called \defnx{subobjects}{subobject}.
    intro.tex:1489:are \defnx{lock-free executions}{lock-free execution}.
    iostreams.tex:10147:\defnx{encoded character types}{encoded character type}.
    lex.tex:32:\defnx{source files}{source file} in this International

**Comment by jensmaurer** [comment]
Yeah, I think italicizing the "s" in the definition is a good idea.
(In contrast, we don't italicize the "s" when referring to the plural of a grammar term.)
