### ISSUE TITLE
[util.smartptr.enab]/8 and P0033R1

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1299]
Currently [[util.smartptr.enab]/8](https://timsong-cpp.github.io/cppwp/n4618/util.smartptr.enab#8) depicts:

> *Postconditions:* `r.get() == this`.

This is a vestige from pre-[P0033R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0033r1.html) days, when it was paragraph 9 in e.g., [N4567](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4567.pdf); it references a nonexistent variable `r`.

I'd normally file an LWG issue for this, but it looks like that P0033R1's wording actually does seem to say this should be removed, because it says "*Replace paragraphs 7, 8 and 9*" (and this was paragraph 9 in N4567, as noted). The subsequent diff didn't include the paragraph, though. 

Pinging @jwakely (since it's his paper).

**Comment by jensmaurer** [comment]
Well, P0033R1 didn't show the Postcondition with strikeout.

Anyway, there's no "r" in sight here, and the prose edit instructions in P0033R1 seem clear enough to me.

**Comment by jwakely** [comment]
Yes, that was meant to be struck out, I guess I missed it from the paper. Thanks for fixing it.
