### ISSUE TITLE
Code font in "return statement"

### ISSUE THREAD

**Issue by alexanderkscott** [cplusplus/draft#1305]
I count 14 instances of "return statement" and 23 instances of "`return` statement". The is also some variation in "if statement", "switch statement" and maybe others.

**Comment by jensmaurer** [comment]
We're even inconsistent in [stmt.return] where we define the meaning: p1 has `return`, p2 has plain return.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Use code font for these statement variations.
