### ISSUE TITLE
Consider using more "Descriptive variable definitions" tables for requirements

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1309]
Compare:
* http://eel.is/c++draft/allocator.requirements#tab:allocator.req.var
* http://eel.is/c++draft/associative.reqmts.general#8

The former is nice and clean, while the latter is almost impossible to read.

**Comment by jensmaurer** [comment]
Except that the intro text for the variable table isn't stellar:
> Table [tab:desc.var.def] describes the types manipulated through allocators. 
The table also shows non-type variables.

**Comment by jensmaurer** [comment]
That would be a rather large change, since most of the introductory sections for the requirements tables are affected.

**Comment by Eelis** [comment]
A third alternative layout is to use a list, as in [[rand.req.dist]#3](http://eel.is/c++draft/rand.req.dist#3).

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Re-layout the introductory sections as lists.

**Comment by Eelis** [comment]
Ah, I see that the hard-to-read paragraph I originally cited (http://eel.is/c++draft/associative.reqmts.general#8) has now been fixed, sweet!

I also see that the "big" label was applied to this ticket. Are there any remaining hard-to-read paragraphs introducing variables?

**Comment by jensmaurer** [comment]
Fixed by #4499
