### ISSUE TITLE
Decide as what kind of entity to annotate "derived-declarator-type-list"

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1310]
Places where it is a \grammarterm:

    declarators.tex:954:``\grammarterm{derived-declarator-type-list}
    declarators.tex:1258:``\grammarterm{derived-declarator-type-list}
    declarators.tex:1265:``\grammarterm{derived-declarator-type-list}
    declarators.tex:1296:``\grammarterm{derived-declarator-type-list} \tcode{T}'',
    declarators.tex:1303:``\grammarterm{derived-declarator-type-list}

Places where it is a \nonterminal:

    declarators.tex:535:is ``\nonterminal{derived-declarator-type-list}
    declarators.tex:539:is ``\nonterminal{derived-declarator-type-list cv-qualifier-seq} pointer to
    declarators.tex:650:is ``\nonterminal{derived-declarator-type-list}
    declarators.tex:654:is ``\nonterminal{derived-declarator-type-list} reference to
    declarators.tex:847:is ``\nonterminal{derived-declarator-type-list}
    declarators.tex:851:is ``\nonterminal{derived-declarator-type-list cv-qualifier-seq} pointer to member of class
    declarators.tex:987:is ``\nonterminal{derived-declarator-type-list} array of
    declarators.tex:997:is ``\nonterminal{derived-declarator-type-list} array of unknown bound of
    declarators.tex:1000:The type ``\nonterminal{derived-declarator-type-list} array of
    declarators.tex:1004:``\nonterminal{derived-declarator-type-list} array of unknown bound of

Possibly it should be neither? :)

**Comment by jensmaurer** [comment]
Oh, \nonterminal is actually misused all over the place. We should use \grammarterm or \cv or \cvqual or ... See #1312.

Similar to derived-declarator-type-list, we also have parameter-type-list as a term of art that just happens to be spelled with hyphens. However, in the case of the derived-declarator-type-list, this is used more like a \placeholder.

@tkoeppe: Ok to use \placeholder here for now?
