### ISSUE TITLE
Replace \nonterminal with \grammarterm or \cv or \cvqual or ...

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1312]
... and remove the macro afterwards, taking care of the use(s) in macros.tex itself.

\nonterminal in running text should be \grammarterm these days.

**Comment by Eelis** [comment]
Is it possible that this ticket was inappropriately auto-closed by @tkoeppe's commit? We do still have a bunch of \nonterminal uses left in the document. (Most of them are addressed by #1315.)

**Comment by tkoeppe** [comment]
Yes, if you say "fixes" in the commit message, GitHub closes the referenced issue. @jensmaurer: Double-check if this issue is still relevant and reopen?

**Comment by jensmaurer** [comment]
The remaining appearances of \nonterminal are:

- \nonterminal{derived-declarator-type-list} addressed by #1315 (@tkoeppe: Please have a look and apply.)
- \nonterminal inside grammar snippets; this seems a fine use
- \nonterminal{nested-name-specifier} in [dcl.mptr] p1, which might be an oversight that we want to double-check after #1315 went in.
