### ISSUE TITLE
wrongly added {}

### ISSUE THREAD

**Issue by lynnboy** [cplusplus/draft#1320]
[stmt.stmt/2](https://github.com/cplusplus/draft/blob/master/source/statements.tex#L36):
there is a redundant `{}` in `\grammarterm{}{condition}{s}`.
Also in `\grammarterm{}{declarator}`.
Also in stmt.stmt/3-5.
Also in stmt.select/1, for `\grammarterm{}{statement}`.

I don't know whether these are intended (to temporarily disable the `\grammarterm` macro) or by mistakes.

In stmt.select/1, the statement before [Example, are the `selection-statement` and `compound-statement` need to be marked by `\grammarterm`?

**Comment by jensmaurer** [comment]
Apparently, those are mistakes. We do want to mark grammar non-terminals in running text with \grammarterm.
