### ISSUE TITLE
Issues of ending indeces.

### ISSUE THREAD

**Issue by lynnboy** [cplusplus/draft#1325]
These ending indeces may be put at wrong place:

* [func.bind](https://github.com/cplusplus/draft/blob/master/source/utilities.tex#L14161)
* [stmt.select](https://github.com/cplusplus/draft/blob/master/source/statements.tex#L397)
* [stmt.iter](https://github.com/cplusplus/draft/blob/master/source/statements.tex#L679)
* [class.init](https://github.com/cplusplus/draft/blob/master/source/special.tex#L2069)
* [over.match.funcs](https://github.com/cplusplus/draft/blob/master/source/overloading.tex#L1375)
* [lex.name](https://github.com/cplusplus/draft/blob/master/source/lex.tex#L645)
* [expr.prim](https://github.com/cplusplus/draft/blob/master/source/expressions.tex#L1309)
* [basic.types](https://github.com/cplusplus/draft/blob/master/source/basic.tex#L4144)
* [dcl.spec](https://github.com/cplusplus/draft/blob/master/source/declarations.tex#L1652)

Missing ending index for [expr.spec](https://github.com/cplusplus/draft/blob/master/source/exceptions.tex#L686).

**Comment by jwakely** [comment]
It's unclear where the range_close should go for:

`\indextext{overloading!argument lists|(}`

Should that page range include the new [over.match.class.deduct] sub-clause, which is part of [over.match.funcs]?

**Comment by jwakely** [comment]
And should [dcl.type.auto.deduct] and [dcl.type.class.deduct] be included in the range for [dcl.spec] started with `\indextext{specifier|(}` ?

**Comment by jwakely** [comment]
> Missing ending index for expr.spec.

There is no such subclause, is this a typo?

I do see these unbalanced index page ranges:

````
numerics.tex:\indextext{\idxhdr{cstdarg}|)}%
numerics.tex:\indextext{\idxhdr{random}|(}%
````

**Comment by jwakely** [comment]
I've fixed most of these, there are a couple more in pull request #1328 where I'm unsure if I moved them to the right place.

**Comment by zygoloid** [comment]
I think it makes more sense for the "specifier" index item to include up to the end of [dcl.type.class.deduct] than to end before [dcl.type.auto.deduct]. Likewise, "overloading!argument lists" should probably extend to include [over.match.class.deduct], since it does (indirectly) specify how to form the argument list for such an overload resolution.

**Comment by jwakely** [comment]
Done.
