### ISSUE TITLE
Typo in [basic.scope.namespace]/3

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#134]
From Andrew Tomazos: 
> - Names with global namespace scope are said to be global name 
> 
> Either 
> 
> + A name with global namespace scope is said to be a global name 
> 
> or 
> 
> + Names with global namespace scope are said to be global names

**Comment by AlisdairM** [comment]
Apparently the first option was chosen, and has been applied in the current draft.  This issue can be safely closed.
