### ISSUE TITLE
10.2p12 wrong example.

### ISSUE THREAD

**Issue by introom** [cplusplus/draft#1343]
It says:
    int B1::* mpB1 = &D::i;     // Unambiguous
    int D::* mpD = &D::i;       // Ambiguous conversion

Which is wrong.

**Comment by jwakely** [comment]
Yes, both are ambiguous. @jensmaurer or @zygoloid what is this meant to say?

**Comment by jensmaurer** [comment]
As discussed on the core reflector starting at http://lists.isocpp.org/core/2017/01/1441.php, the example is correct: There is only one B1::i member, and that is unambiguously found by the algorithm described in this section.

See also CWG 39 / N1626.
