### ISSUE TITLE
Inconsistent italicization of \nontermdef's colon in bnf and bnfkeywordtab envs

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1351]
Compare:
- [hexadecimal-digit](https://github.com/cplusplus/draft/blob/master/source/lex.tex#L897), defined with a bnf environment:
![hexdigit](http://eel.is/hexdigit.png)
- [preprocessing-op-or-punc](https://github.com/cplusplus/draft/blob/master/source/lex.tex#L794), defined with a bnfkeywordtab environment:
![ppoporpunc](http://eel.is/ppoporpunc.png)

**Comment by tkoeppe** [comment]
I have a long standing rant about not italicising colons. It not only affects grammar, but also Note: and Example: introducers. One day we'll get to it.

**Comment by jensmaurer** [comment]
@tkoeppe: Do I interpret this correctly that you want the colons to be italics in these cases?

**Comment by tkoeppe** [comment]
@jensmaurer: No, heaven forbid! The point is that punctuation should never be italicizable. Italics are *letters*, but it really doesn't make sense to inclined commas, periods, colons, or even brackets. Italic brackets are an unfortunate outcome of digital typography (where the layman's idea of "italics" is to just shear the shapes a bit) gone wild. Good fonts keep the punctuators straight even in the italics.

I want to style notes and examples as `[\textit{Note}:` and `--- \textit{end note}]`. And we should find a similar way to make the colon after grammar productions appear straight. It's even more obvious why that's the right thing to do in that context: the colon isn't part of the production!

**Comment by jensmaurer** [comment]
@tkoeppe: Thanks. Does Richard agree with this direction?

**Comment by jensmaurer** [comment]
Ah, it seems the colon after _preprocessing-op-or-punc_, while upright, is actually \ttfamily, which is also not what we want.

**Comment by tkoeppe** [comment]
@jensmaurer: No, we never reached a conclusion on that. It's one of my big plans for C++20.

**Comment by tkoeppe** [comment]
Fixed by ffb9408d01061c336807333bf2cd2743acb8df14. Thanks for providing the solution!
