### ISSUE TITLE
[any.class]/3 Rephrase example

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1360]
[[any.class]/3](http://eel.is/c++draft/any.class#3) reads:

> Implementations should avoid the use of dynamically allocated memory for a small contained object. [ Example: where the object constructed is holding only an int.  — end example ] Such small-object optimization shall only be applied to types T for which is_­nothrow_­move_­constructible_­v<T> is true.

Grammar-wise the phrasing of the example is not ideal.

**Comment by jwakely** [comment]
Yes, although "small-object optimization" is a known term outside the standard, it's ungrammatical here and not defined as a formal term. How about ...

> Implementations should avoid the use of dynamically allocated memory for a small contained object. [ Example: Where the object constructed is holding only an `int` it could be stored in an internal buffer, not in separately-allocated memory.  — end example ] Any such small-object optimization shall only be applied to types `T` for which `is_nothrow_­move_­constructible_­v` is `true`.

**Comment by tkoeppe** [comment]
Maybe put "small-object optimization" in quotation marks?

**Comment by jensmaurer** [comment]
In normative text? No thanks.
