### ISSUE TITLE
"pointer to member" vs "pointer-to-member"

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1369]
Pick one.

e.g. just in overloading.tex:

````
overloading.tex:a pointer to member, or \tcode{std::nullptr_t}
overloading.tex:pointer-to-member-function type.
overloading.tex:pointer to member function type.
overloading.tex:function name is required to have the form of a pointer to member as
overloading.tex:                                // pointer to member
overloading.tex:For every pointer to member type \tcode{\placeholder{T}} or type \tcode{std::nullptr_t} there
overloading.tex:is an enumeration or pointer to member type,
overloading.tex:is a pointer, pointer-to-member, or scoped enumeration type, there exist candidate operator
````

**Comment by jensmaurer** [comment]
You're confused. It's hyphenated when it's an adjective (or part of one), as in "pointer-to-member-function type", and it's not hyphenated when it's a noun, e.g. "the form of a pointer to member". This is standard English grammar, as far as I know.

[](http://www.grammarbook.com/punctuation/hyphens.asp)

"We have a one-year-old child." vs. "My child is one year old."

**Comment by jwakely** [comment]
I don't think we're following that rule though.

What's the difference between "when matching a pointer-to-member-function type" and "match targets of pointer to member function type" two paragraphs later?

**Comment by jwakely** [comment]
And "For every pointer to member type T"

OK, I shouldn't have said "Pick one." but it doesn't look consistent and/or correct in all cases.

**Comment by jensmaurer** [comment]
Agreed. This one should be hyphenated, for example:

overloading.tex:pointer to member function type.

**Comment by jensmaurer** [comment]
Editorial committee consensus: Do not hyphenate pointer-to-object or pointer-to-function (they are pointers). Define pointer-to-member as a term of art (adjective only; fix noun uses). Also consider canonical type strings.
