### ISSUE TITLE
[expr.cond]/4.3 simplification

### ISSUE THREAD

**Issue by cubbimew** [cplusplus/draft#1373]
Should the simplification from https://groups.google.com/a/isocpp.org/forum/#!topic/std-discussion/hFSv84WY14o (which pointed out awhile ago that [expr.cond]/4.3.1 is redundant) be applied to [expr.cond]/4.3 as an editorial? That wall of text could use any simplification it can get.

**Comment by zygoloid** [comment]
Closing; we don't need to have both this and #1374 open. A pull request is as good as a (non-PR) issue for this.
