### ISSUE TITLE
Style references to numbered lines in example code consistently

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1375]
The following two fragments are from [except.ctor]/2 and [temp.class.order]/2, respectively:

![coderefs](http://eel.is/coderefs.png)

Note how the `#1`/`#2` are in body font in the first, and in code font in the second.

(Also, the `A`/`B`/`C`/`D`in the second fragment should probably not be in code font.)

**Comment by jensmaurer** [comment]
We don't do #1 -style references very often, it seems, but where we have them, \tcode is the exception. We usually just have body font #1 references.

That suggests point-fixes for the few issues discovered above as opposed to broad harmonization.
