### ISSUE TITLE
[cpp.pragma.op] Take into account encoding-prefixes other than 'L'

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1388]
[[cpp.pragma.op]](http://eel.is/c++draft/cpp.pragma.op) says:

    The string literal is destringized by deleting the L prefix, if present, [...]

This sounds left over from the days where L was the only encoding-prefix. I would expect that these days, the intent is to also delete other encoding-prefixes, and possibly even handle raw string literals. So I think cwg might want to take a look.

**Comment by jensmaurer** [comment]
I've asked for a core issue to fix this.

Subject: 16.9 [cpp.pragma.op] refers to "L" prefix only
Date: Thu, 19 Jan 2017 15:20:37 +0100
To: William M. (Mike) Miller <william.m.miller@gmail.com>


16.9 [cpp.pragma.op] first paragraph:

"The string literal is destringized by deleting the L prefix, if present, ..."

We nowadays have a lot more string literal prefixes to delete.

For comparison, C11 says:

"The string literal is destringized by deleting any encoding prefix, ..."

C++ should follow. (This is also editorial issue #1388.)

**Comment by cpplearner** [comment]
This is [CWG 897](http://wg21.link/cwg897).

**Comment by Eelis** [comment]
Wow, known since 2009 already!

**Comment by jensmaurer** [comment]
Closing this editorial issue, since it's handled by CWG.
