### ISSUE TITLE
Use "this document" instead of "this International Standard"

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1389]
Version 7.0 of the [ISO/IEC Directives Part 2](http://www.iec.ch/members_experts/refdocs/iec/isoiecdir-2%7Bed7.0%7Den.pdf) (section 10.6) introduces "this document" as the new and improved way for documents to refer to themselves, replacing the wearisome "this International Standard".

Going over occurrences of "this International Standard" in the document, it seems to me that almost all of them would be improved by the replacement, but there are some cases where the change results in dubious phrasing. For example, [diff.cpp03.containers]:

> Valid C++ 2003 code that relies on these functions returning void [..] will fail to compile with this International Standard.

**Comment by jensmaurer** [comment]
The sampling I did is less clear. There are four categories:

- Replace "International Standard" with "document" where we're administratively referring to the document as a body of text, e.g. [intro.scope] (last reference) and [intro.defs].
- Strike "this International Standard", because we're by default not reaching outside of the standard, e.g. [reentrancy].
- Leave as-is, because we're contrasting with a different version of C++, e.g. [diff].
- Leave as-is, because we're contrasting with C, e.g. C headers in clauses 17-30.

Most of the 150 appearances are in the latter two categories.

**Comment by jensmaurer** [comment]
@zygoloid, your opinion?

**Comment by tkoeppe** [comment]
What is the worst case if we just stick with the status quo?

**Comment by timsong-cpp** [comment]
Probably not much. The C++ standard systematically ignores the Directives' prohibition on "hanging paragraphs" (§22.3.3), for instance.

**Comment by Eelis** [comment]
@timsong-cpp Interesting, can you give an example?

**Comment by timsong-cpp** [comment]
@Eelis [basic]/1-9, for instance. (Their definition of "hanging paragraph" is really weird. You pretty much have to look at the example in the Directives to see what they mean - basically any paragraph in a non-leaf subclause is "hanging".)

**Comment by Eelis** [comment]
Ahh, I see, thanks! So that convention lets you say "3.4" to refer to paragraph 4 of section 3 without having to worry about there possibly also being a subsection 3.4 (because the convention prevents such ambiguity). I would say the justification for ignoring that rule is that C++ has a tradition of only using periods for subsections, and using "3p4" or "3/4" or "3#4" to refer to paragraph 4 of section 3.

I think it's probably best to only ignore rules when we have a concrete justification like that.

**Comment by timsong-cpp** [comment]
@Eelis Paragraphs are supposed to be unnumbered (§6.1, Table 1 - so yet another place where we ignore the Directives systematically). The rule is intended to, say, avoid writing a reference to (the entire) Clause 5 [expr] when we really mean to only reference something in the front matter (like the note in [dcl.decomp]/1).

**Comment by Eelis** [comment]
Wow, now I wonder how other ISO standards cope with not having paragraph numbers. They're so useful!

**Comment by jensmaurer** [comment]
@timsong-cpp: Yes, paragraphs are supposed to be unnumbered --- and our in-standard cross-references don't mention paragraph numbers. So just ignore the random black dots in the margins of the C++ standard, and you're good.

Regarding "hanging paragraphs": I think I agree with the rationale in the ISO directives here, and the example in [dcl.decomp]p1 (and similar like it) are indeed disconcernting. My opinion is that those "hanging paragraphs" should only have introductory material without normative impact (maybe in a note for consistency), and everything else should go into a leaf subsection. This way, there is never a need to refer to the material in the hanging paragraph in normative references. Most of the core language sections are fairly bad offenders in that regard, and need rework.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Address the first two categories (Jan 19 comment), conservatively. Leave third and fourth alone.

**Comment by jensmaurer** [comment]
Remaining open issue:
- Strike "this International Standard", because we're by default not reaching outside of the standard, e.g. [reentrancy].

**Comment by jensmaurer** [comment]
Addressed by #1647.
