### ISSUE TITLE
Format index entries that redirect to multiple other index entries consistently

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1391]
There are currently three conventions in use for index entries that redirect to multiple other index entries:
- repeated "see":
![a](http://eel.is/see-a.png)
- semicolon delimiters:
![b](http://eel.is/see-b.png)
- comma delimiters:
![c](http://eel.is/see-c.png)

**Comment by Eelis** [comment]
I can provide a patch, but ideally we would first establish whether the inconsistency is deemed problematic, and then what the preferred convention is.

**Comment by jensmaurer** [comment]
Well, commas obviously don't work.

**Comment by jensmaurer** [comment]
Editorial consensus: The first style is the TeX automatic default. Check why that is; a semicolon before each "see" would be appreciated. Otherwise, live with it. Fix second and third styles.

**Comment by Eelis** [comment]
#1501 fixed the second and third styles. I can't find a nice way to make "see"s semicolon-delimited, nor do I feel strongly about it, so feel free to close this issue as fixed. :)
