### ISSUE TITLE
[optional.observe] Redundant remarks?

### ISSUE THREAD

**Issue by lynnboy** [cplusplus/draft#1394]
[optional.observe/4,8,12,14], these "Remarks" paragraph saying "this functions shall be constexpr functions", but they already declared as constexpr functions. Are these paragraphs redundant?

**Comment by cpplearner** [comment]
[LWG 2829](http://wg21.link/lwg2829), [LWG 2833](http://wg21.link/lwg2833)

**Comment by jwakely** [comment]
They're not redundant, because they're trying to say "this function shall be usable in a constant expression" but they're phrased incorrectly. Removing them would be wrong though.
