### ISSUE TITLE
Term "functor" is used but never defined

### ISSUE THREAD

**Issue by grisumbras** [cplusplus/draft#1403]
Section 20.14 mentions the term "functor" several times but it is never defined. It should either be changed to "function object" as in all other places, or defined (probably as an alternative name to function objects, codifying a popular convention).

**Comment by jwakely** [comment]
I only see two mentions of it, both in non-normative text (a subclause title, and a reference to that subclause in a comment). It doesn't need to be defined to be referred to in that way.

**Comment by jwakely** [comment]
In fact if we _did_ define it, it would be unused in any normative text, and so the definition should be removed again.

**Comment by grisumbras** [comment]
But wouldn't it be confusing for the reader to see this term there? I can send a PR to change those lines to refer to "function objects".

**Comment by tkoeppe** [comment]
Closing this, since we are going to remove `default_order`.
