### ISSUE TITLE
[expr.delete] Missing tilde in index entry?

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1417]
[expressions.tex#L3644](https://github.com/cplusplus/draft/blob/master/source/expressions.tex#L3644) produces:

![pic](http://eel.is/operator.png)

**Comment by tkoeppe** [comment]
Can you please describe the perceived problem here?

**Comment by jwakely** [comment]
"operator , _see_ `delete`" is certainly odd ... why is there a space after "operator"? Which operator is it talking about?

**Comment by jwakely** [comment]
As an aside, the text that contains the index entry ([expr.delete] p8) should probably refer to `operator delete` not `operator delete()`, and `operator delete[]` not `operator delete[]()`.

**Comment by Eelis** [comment]
Yeah, @jwakely's concerns about the index entry are the ones I had in mind. :)

**Comment by jwakely** [comment]
I don't think it's supposed to say "operator~" though, because the unary complement operator has nothing to do with deallocation functions. That character appears in a destructor, but it's not the `~` operator.

**Comment by jensmaurer** [comment]
Maybe the strange "operator space" index entry came into being during my "remove tilde from index entries" operation. In any case, operator~ has nothing to do with delete, so I'm removing the index entry.
