### ISSUE TITLE
[enum.copy_options] Poor wording for requirement on elements set in copy_options

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1422]
[enum.copy_options] says:

> Calling a library function with more than a single constant for an option group results in undefined behavior. 

I don't like how this is phrased. Firstly, which library? Does it apply to _any_ function in the standard library, e.g. `std::move`?

Secondly, I'd prefer if it used the term of art "is set" for bitmask elements set in a bitmask object.

This doesn't exactly roll off the tongue, but I think it's more precise:

"A value of type `copy_options` that is passed to a function described in subclause 27.10 shall have at most one element set from each option group."

**Comment by timsong-cpp** [comment]
There are only two functions taking `copy_options`: `copy` and `copy_file`. Both of them have a similarly poorly phrased *Requires*: clause restating this requirement:

> *Requires*: At most one constant from each option group ([enum.copy_options]) is present in `options`.

I'd suggest dropping the offending sentence entirely from [enum.copy_options] or turning it into a non-normative note, and rewording the two *Requires* clauses to use the correct terms of art ("element" and "is set").

**Comment by jensmaurer** [comment]
@timsong-cpp: Sounds like a good idea.
