### ISSUE TITLE
Indexing issues in [containers]

### ISSUE THREAD

**Issue by lynnboy** [cplusplus/draft#1425]
1. There are many member declarations that are not indexed using `\indexlibrarymember` but simply `\indexlibrary`.
2. Only the requirement tables in [unord.req] are indexed for member names, while other requirement tables are not indexed for member names at all.

**Comment by tkoeppe** [comment]
@AlisdairM: Would you mind taking a look?

**Comment by AlisdairM** [comment]
I'll add this to my list of things to do before Kona, thanks.

**Comment by jensmaurer** [comment]
@AlisdairM: There's another Kona coming up in 2019; maybe that would be a good time?

**Comment by AlisdairM** [comment]
I'll see what I can do :)

**Comment by AlisdairM** [comment]
I did not get to this for C++20 :(. Still time for someone else to find a solution?

**Comment by jensmaurer** [comment]
The first item (insufficient use of `\indexlibrarymember`) was addressed by commit 90623064407c1775dc5d13cb71a1e43fe23137de.

The second item (indexing of members described in container requirements) is addressed by pull request #4454.
