### ISSUE TITLE
[ostreambuf.iter.ops] not divided into subsections as [istreambuf.iter.ops]

### ISSUE THREAD

**Issue by lynnboy** [cplusplus/draft#1429]
there are several [istreambuf.iterator::op...] sections under [istreambuf.iterator],
but there is only a combined [ostreambuf.iter.ops] section under [ostreambuf.iterator].
This is inconsistent.

Consider split it into subsections.

Also: consider change `::` into `.` and `*` into `star` in section labels

**Comment by tkoeppe** [comment]
I don't think we are going to change stable names.

**Comment by lynnboy** [comment]
But we've already made `::` -> `.` for `[string.xxx]`.

**Comment by tkoeppe** [comment]
@lynnboy: Wasn't that for new content post-C++14? Things that were added in this revision can still be changed, indeed.

**Comment by cpplearner** [comment]
The change from `[string::xxx]` to `[string.xxx]` is made in 0b5bcd51.

**Comment by tkoeppe** [comment]
I see. I guess we *do* change stable names then...

**Comment by jensmaurer** [comment]
The stable names are really bad, and those single-paragraph descriptions should never had gotten separate sections to start with.

**Comment by Eelis** [comment]
[[reverse.iter.ops]](http://eel.is/c++draft/reverse.iter.ops) also has many single-paragraph sections for individual operators. So possibly that one could be cleaned up as well.

**Comment by jensmaurer** [comment]
This seems to be a pervasive issue in that area; see [front.insert.iter.ops] and [back.insert.iter.ops]. The [reverse.iter.ops] that you mentioned are more than half a page, though, so some kind of subdivision (e.g. "comparison operators", "arithmetic") might be worthwhile.

In short, all of [predef.iterators] is affected, and we should come up with a common approach for that subsection instead of fixing individual issues.

@zygoloid, what do you think?

**Comment by jensmaurer** [comment]
Editorial committee consensus: Fold mini-sections for operators and rename "::" in stable names.

**Comment by tkoeppe** [comment]
@jensmaurer: Did we mean to close this issue? Didn't you say there were other aspects to it not yet dealt with by pull requests?

**Comment by jensmaurer** [comment]
> In short, all of [predef.iterators] is affected, and we should come up with a common approach for that subsection instead of fixing individual issues.

> Editorial committee consensus: Fold mini-sections for operators and rename "::" in stable names.
