### ISSUE TITLE
Outdated text on signedness of bit-fields

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#145]
[dcl.type.simple]p3 contains a note which claims that:

"It is implementation-defined whether objects of char type and certain bit-fields (9.6) are represented as signed or unsigned quantities. The signed specifier forces char objects and bit-fields to be signed; it is redundant in other contexts."

The bit-field part of this is no longer true. Suggest we remove the mentions of bit-fields here:

"It is implementation-defined whether objects of char type are represented as signed or unsigned quantities. The signed specifier forces char objects to be signed; it is redundant in other contexts."

**Comment by AlisdairM** [comment]
This change is present in the current draft, so this issue can be safely closed.
