### ISSUE TITLE
[expr.dynamic.cast] CWG 2365: Incorrect wording regarding dynamic_cast

### ISSUE THREAD

**Issue by introom** [cplusplus/draft#1453]
In paragraph 4, http://eel.is/c++draft/expr.dynamic.cast#4

If the value of v is a null pointer value in the pointer case, the result is the null pointer value of type T.

And in paragraph6,

Otherwise, v shall be a pointer to or a glvalue of a polymorphic type.

So the *otherwise* means the *v* in p4 doesn't have to be polymorphic.

However, this is not possible because the compiler can only check if "v" is a null pointer at runtime.  If "v" is not a null pointer, and unluckily has no RTTI, then the runtime could do nothing meaningufl, ill-formed?

BTW, Clang and GCC requires the "v" in p4 to be of pointer to polymorphic type.

**Comment by cpplearner** [comment]
Do you mean this:

    struct T1 {};
    struct T2 {};
    T1* p = nullptr;
    dynamic_cast<T2*>(p);

This appears to be valid according to p4, but will not be valid if `p` is not a null pointer.

**Comment by jensmaurer** [comment]
This does not seem to be editorial; the normative wording is nonsensical here. Submitted as a CWG issue: http://lists.isocpp.org/core/2017/02/1733.php .

**Comment by jensmaurer** [comment]
CWG in Jacksonville: treat as a core issue

**Comment by jensmaurer** [comment]
CWG in Jacksonville: To be handled as a core issue.

**Comment by jensmaurer** [comment]
Resolved with commit e81049e5b37fbb38317c3385c3f4742381080cd3.
