### ISSUE TITLE
[dcl.fct.spec] mistakenly used as reference for 'inline'

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1458]
17.5.5.4p1 reads:

> It is unspecified whether any non-member functions in the C++ standard library are defined as inline (7.1.2).

And 17.5.5.5p1 reads:

>  It is unspecified whether any member functions in the C++ standard library are defined as inline (7.1.2).

But 7.1.2 is [dcl.fct.spec] "Function specifiers", which only talks about "virtual" and "explicit", not about "inline", which isn't a function-specifier.

**Comment by cpplearner** [comment]
9.2.1p1:
> A member function may be defined (8.4) in its class definition, in which case it is an _inline_ member
function (7.1.2)

9.2.1p3:
> [ Note: There can be at most one definition of a non-inline member function in a program. There may be more than one inline member function definition in a program. See 3.2 and 7.1.2. — end note ]

And 7.1.6[dcl.inline]p2 (!):
> An implementation is not required to perform this inline substitution at the point of call; however, even if this inline substitution is omitted, the other rules for inline functions defined by 7.1.2 shall still be respected.
