### ISSUE TITLE
HTML version

### ISSUE THREAD

**Issue by lazy-bug** [cplusplus/draft#147]
Hi Guys,
   Thanks for all the hard work on maintaining this. Is there a chance of adding html output support. I did some work a while ago which is available in https://github.com/ramneek-handa/draft. It uses htlatex to output html but requires some tweaking.

I am tex handicap and had to beg, borrow and steal code to get it to compile and now i am not able to maintain it. 

Thanks.

**Comment by zygoloid** [comment]
See eel.is/c++draft
