### ISSUE TITLE
example in [dcl.attr.nodiscard]p3 is insufficiently clear

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1470]
Reported by Mike:

> In particular, the line that reads
>
>      void f() { foo(); } // reference type, warning not encouraged
>
> isn't clear enough why the warning is not encouraged. In fact, it's because the `nodiscard` attribute is on the class type referred to, not the function `foo()`, and the return type is not (cannot be) declared `nodiscard`. I'd suggest, if you agree, an editorial change to something like
>
>      void f() { foo(); } // warning not encouraged: not a nodiscard call, because
>                          // neither the (reference) return type nor the function is
>                          // declared nodiscard
>
> would clarify the intent.

This seems like an improvement to me.

**Comment by jensmaurer** [comment]
Here you are.
