### ISSUE TITLE
`Index style file basic.gst not found.`

### ISSUE THREAD

**Issue by ckaran** [cplusplus/draft#1472]
I keep having the following error when I execute `latexmk -pdf source.tex`:

```
=== Creating rule for 'cusdep glo gls xrefindex'
Latexmk: Summary of warnings:
  Latex failed to resolve 6260 reference(s)
Latexmk: applying rule 'cusdep glo gls xrefindex'...
Rule 'cusdep glo gls xrefindex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'xrefindex.glo'
   Non-existent destination files:
      'xrefindex.gls'
------------
Run number 1 of rule 'cusdep glo gls xrefindex'
------------
For rule 'cusdep glo gls xrefindex', running '&do_cusdep( makeglo2gls )' ...
Index style file basic.gst not found.
Usage: makeindex [-ilqrcgLT] [-s sty] [-o ind] [-t log] [-p num] [idx0 idx1 ...]
Rule 'cusdep glo gls xrefindex', function 'makeglo2gls'
   failed with return code = 256
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  cusdep glo gls xrefindex: Command for 'cusdep glo gls xrefindex' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
~/Documents/Information, Papers, and Books/ISO:IEC 14882 - C++ standard/draft
```

I've used `git bisect` to track this down to commit 46343660afd101e218aa7ec77a7bc6ba618894b0 as being the first bad commit.  Is anyone else seeing this problem as well?  Version info:

```
Cems-Mac-Pro:draft crossbar$ latexmk --version
Latexmk, John Collins, 19 Jan. 2017. Version 4.52c

Cems-Mac-Pro:draft crossbar$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016)
kpathsea version 6.2.2
Copyright 2016 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.21; using libpng 1.6.21
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.04
Cems-Mac-Pro:draft crossbar$ 
```

**Comment by jensmaurer** [comment]
There is no file "source.tex" in my directory tree. I invoke

> latexmk -pdf std

and everything works.

**Comment by ckaran** [comment]
My apologies, you're right that I typed the bug report in wrong; I typed it after a very long time using `git bisect` to find the problem, and had gotten tired.  Here is a better explanation:

Try the following from your cloned root directory (the directory that contains your `.git` directory).

```
git pull
git clean -xdf
cd source 
latexmk -pdf std.tex 
```

You should end up with the same error that I'm having.  To find the first failure I did the following:

```
git pull
git bisect start
# The following is the first commit in the repository.
git bisect good d8fb8cf16dd05f711d33b3749a757d69068e45ef
git clean -xdf
pushd source 
latexmk -pdf std.tex 
popd
# Check the output and mark it good or bad as needed.
git clean -xdf
pushd source 
latexmk -pdf std.tex 
popd
# Check the output and mark it good or bad as needed.
...
```

I kept doing that until I found the first build that failed for me.  Note that `latexmk -cd source -pdf` does **not** work.  Only the commands above cause the failure.  That said, `latexmk -cd source -pdf` still seems to have errors, it just doesn't report them correctly.

**Comment by jwakely** [comment]
I still can't reproduce this, even after:

````
git clean -xdf
cd source 
latexmk -pdf std.tex 
````

**Comment by tkoeppe** [comment]
I'm also baffled by this issue. Hundreds of people have been building the document for months.

**Comment by ckaran** [comment]
OK, it looks like this is a problem with my machine.  I just asked one of my coworkers who has a similar model of machine, and he has no problems.  I have virtualbox installed, and since everything works under Ubuntu on that, I can just rebuild within virtualbox.  So I guess closing this issue is fine.  I guess its time to wipe this machine completely, and reinstall everything from scratch.
