### ISSUE TITLE
Consistently use \mathit for italic 'cv' (or not)

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1474]
Places that use \mathit:

    conversions.tex:291:\item For every $i > 0$, if \tcode{const} is in $\mathit{cv}_i^1$ then \tcode{const} is in $\mathit{cv}_i^2$, and similarly for \tcode{volatile}.
    conversions.tex:293:\item If the $\mathit{cv}_i^1$ and $\mathit{cv}_i^2$ are different,
    conversions.tex:294:then \tcode{const} is in every $\mathit{cv}_k^2$ for $0 < k < i$.
    templates.tex:6555:$\mathit{cv}_{1,0}$ ``pointer to $\ldots$'' $\mathit{cv}_{1,n-1}$ ``pointer to''
    templates.tex:6556:$\mathit{cv}_{1,n}$ \tcode{T1}
    templates.tex:6562:$\mathit{cv}_{2,0}$ ``pointer to $\ldots$'' $\mathit{cv}_{2,n-1}$ ``pointer to''
    templates.tex:6563:$\mathit{cv}_{2,n}$ \tcode{T2},

Places that don't:

    expressions.tex:259:for every $i > 0$, $cv^3_i$ is the union of
    expressions.tex:260:$cv^1_i$ and $cv^2_i$;
    expressions.tex:263:if the resulting $cv^3_i$ is different from
    expressions.tex:264:$cv^1_i$ or $cv^2_i$, then
    expressions.tex:265:\tcode{const} is added to every $cv^3_k$ for $0 < k < i$.
    expressions.tex:2622:$cv_0^2$ $P_0^2$ $cv_1^2$ $P_1^2$ $\cdots$ $cv_{n-1}^2$ $P_{n-1}^2$ $cv_n^2$ $\mathtt{U}_2$,
    expressions.tex:2628:$cv_0^2$ $P_0^1$ $cv_1^2$ $P_1^1$ $\cdots$ $cv_{n-1}^2$ $P_{n-1}^1$ $cv_n^2$ $\mathtt{U}_1$.
    conversions.tex:246:$cv_i$ and $P_i$
    conversions.tex:249:``$cv_0$ $P_0$ $cv_1$ $P_1$ $\cdots$ $cv_{n-1}$ $P_{n-1}$ $cv_n$ \tcode{U}'' for $n > 0$,
    conversions.tex:252:each $cv_i$ is a set of cv-qualifiers~(\ref{basic.type.qualifier}), and
    conversions.tex:259:the cv-qualifiers $cv_{i+1}$ on the element type are also taken as
    conversions.tex:260:the cv-qualifiers $cv_i$ of the array.
    conversions.tex:268:$cv_1, cv_2, \dotsc, cv_n$, is called the
    conversions.tex:285:where~$cv_i^j$ denotes the cv-qualifiers in the cv-qualification signature of $\tcode{T}_j$:%
    utilities.tex:2062:      \tcode{is_constructible_v<$\tcode{A}_{ik}$, $cv_i\;\tcode{A}_{ik}$\&> == true}, otherwise
    utilities.tex:2063:\item \tcode{is_constructible_v<$\tcode{A}_{ik}$, $cv_i\;\tcode{A}_{ik}$\&\&> == true}.

**Comment by jensmaurer** [comment]
We should use \cv{} and \cvqual{cv1} macros and nothing else.

**Comment by tkoeppe** [comment]
@jensmaurer: Don't we already have an open issue for this?

**Comment by jensmaurer** [comment]
@tkoeppe: I fixed most \cv things a few months ago, but apparently missed the ones in math context.
