### ISSUE TITLE
[expr] Built-in operators shouldn't "return" things

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1476]
[expr.new]/1:

> If the entity is a non-array object, the *new-expression* returns a pointer to the object created. If it is an array, the *new-expression* returns a pointer to the initial element of the array.

[expr.log.or]/1:

> It returns `true` if either of its operands is `true`, and `false` otherwise.

 [expr.ass]/1:

> All require a modifiable lvalue as their left operand and return an lvalue referring to the left operand.

**Comment by jensmaurer** [comment]
Editorial committee: "The result is ..."
