### ISSUE TITLE
Missing cross-references to INVOKE in Clause 20

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1480]
We have a couple of things in Clause 20 which refer to _`INVOKE`_ which is not defined until 20.14.3:

- 20.7.7 [variant.visit]
- 20.5.3.5 [tuple.apply]

They should probably have cross-references to the definition of _`INVOKE`_. 

The only other references to _`INVOKE`_ outside its own sub-clause are in the requirements tables for type traits `is_callable`, `is_nothrow_callable` and `result_of`.

**Comment by AlisdairM** [comment]
INVOKE is also used in packaged_task without a cross-reference.  All other uses I found in clause 30 had a cross-reference though.
