### ISSUE TITLE
[stmt.while] Equivalence given for "while (T t = x)" should also cover "while (T t{...})"?

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1485]
6.5.1/2 states:

> A while statement of the form ``while (T t = x) statement``    is equivalent to [...]

These days a declaration condition can also have the form ``T t{...}``. Presumably the equivalence is also intended to apply when the condition has that form. In that case, I suppose this might meet the criterion for an editorial issue:

> Problems with the presentation of the specification, which, when fixed, would not alter the (intended) meaning of the specification.

But I'm not sure :)

**Comment by jensmaurer** [comment]
This looks like a core issue to me.

**Comment by jensmaurer** [comment]
http://lists.isocpp.org/core/2017/02/1827.php

**Comment by Eelis** [comment]
@jensmaurer Is the issue perhaps on one of the public issue lists by now?

**Comment by jensmaurer** [comment]
The existing "of the form `T t = x`" text also has the problem that "of the form" doesn't fit if T is a function type, i.e. the _declarator-id_ is somewhere nested.
