### ISSUE TITLE
Review rev7 of ISO Directives, Part 2 for changes

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1499]
Section numbers below refer to [ISO/IEC Directives, Part2](http://www.iec.ch/members_experts/refdocs/iec/isoiecdir-2%7Bed7.0%7Den.pdfl)

- 12 Foreword (mandatory; not numbered) missing (fixed text to be supplied by ISO Central Secretariat, then some specific text about SC22 and a high-level changelog)
- 13 Introduction (optional unless patent rights have been identified; not numbered) missing
- 14 Scope (mandatory) present; might need a wording rebrush
- 15 Normative references (mandatory) intro text differs (15.5.1)
- 16 Terms and definitions (mandatory) intro text differs; missing references to ISO and IEC dictionaries (16.5.2)

**Comment by jensmaurer** [comment]
Richard, we should discuss how to proceed here.

**Comment by zygoloid** [comment]
The foreword is (or was, for C++14) added by the secretariat after we produced the document.

I've replaced "International Standard" by "document" in our Scope. Otherwise, it still looks good to my eyes.
I've also updated the intro text for "Normative references" and "Terms and definitions".
