### ISSUE TITLE
Change "name space" to "namespace"?

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#1500]
On a few very rare occasions (including one index entry) we say "name space" rather than "namespace". It seems like we should fix all those by removing the space (white, not name).

**Comment by cpplearner** [comment]
[stmt.label]

> Labels have their own name space and do not interfere with other identifiers.

The use of "name space" is confusing, but it would be wrong if the whitespace were removed. 

The C standard defines the term "name space".

**Comment by W-E-Brown** [comment]
> On Mar 2, 2017, at 12:05 AM, S. B. Tam <notifications@github.com> wrote:
> 
> [stmt.label]
> 
> Labels have their own name space and do not interfere with other identifiers.
> 
> The use of "name space" is confusing, but it would be wrong if the whitespace were removed.
> 
> The C standard defines the term "name space".

"namespace" (a single word) is a C++ term for a specific kind of entity.

"name space" (two words) is a technical term of art in computing: it is akin to the C++ term "declarative region"; examples of name spaces include blocks, classes, and namespaces.

IMO, the two are not at all interchangeable.

**Comment by tkoeppe** [comment]
OK, that makes sense, thanks.
