### ISSUE TITLE
Change stable names for Filesystem subclause

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1502]
I would like to change:

[enum.copy_options] -> [fs.enum.copy.opts]
[enum.directory_options] -> [fs.enum.dir.opts]
[enum.file_type] -> [fs.enum.file.type]
[enum.perms] -> [fs.enum.perms]
[directory_iterator.\*] -> [fs.dir.itr.\*]

Any objections? Any other candidates?

As an aside, it's a shame that most [class.xxx] tags are for core wording relating to classes, except for a small handful of library types, [class.gslice], [class.slice], [class.directory_entry], [class.rec.dir.itr], [class.directory_iterator], [class.file_status], [class.filesystem_status], [class.path]. slice and gslice have been there since C++11 (before then they were [lib.class.*]) but all the others are new in C++17 and could be changed now.

**Comment by jensmaurer** [comment]
Emphatically agreed.

**Comment by jensmaurer** [comment]
I would actually prefer to have all stable filesystem labels to start with "fs".

**Comment by zygoloid** [comment]
Can we close this now #1506 is merged, or is there more to do here?

**Comment by jwakely** [comment]
It's done
