### ISSUE TITLE
editorial fixups post-P0270R3

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1505]
Assuming P0270R3 is applied, the following editorial changes are requested by CWG:

 * remove comma after "signal-safe" in [csignal.syn]p3
 * add a subclause for these non-synopsis description elements; update added xrefs to point at it
 * "`dynamic_cast` invocation" should be "`dynamic_cast` expression"
 * "try-block or function-try-block" is missing italics

**Comment by jensmaurer** [comment]
"dynamic_cast invocation" should be "dynamic_cast expression"

should have been addressed by Hans in the latest update.

**Comment by jensmaurer** [comment]
All four items above have already been addressed; see [support.signal].
