### ISSUE TITLE
remove space after INVOKE (please complete before applying p0604r0)

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#1510]
In email from Daniel Krugler:

Dear editors of the working draft!

I would like to ask whether the following editorial improvement could
be realized, when (In case of acceptance),

http://wiki.edg.com/pub/Wg21kona2017/StrawPolls/p0604r0.html

would be transferred into the working draft:

I noticed in the past, that in the pdf output of the working draft, a
font change between italics and non-italics (such as in
"<i>INVOKE</i>(" between '<i>INVOKE</i>' and '(') there often seems to
be an additional space character introduced. This makes is hard to
search reliably for the character sequence 'INVOKE(', for example.
Now, for this sequence there is not often a use-case. But P0604R0
introduces a new "overload" of INVOKE, INVOKE\<something\>. When my
paper was discussed, people were concerned that this overload will be
hard to search in the working draft when looking for 'INVOKE<'. And
given the above problem, I tend to agree. Therefore I would like to
ask, whether it would be possible for your and hopefully lead to a
more reliable search success, when you editors could rewrite the
currently term in partial html

<i>INVOKE</i>&lt;R&gt;  (in html: \<i\>INVOKE\<\/i\>\&lt;R\&gt;)

into the alternative partial html form

<i>INVOKE&lt;</i>R<i>&gt;</i> (in html: \<i\>INVOKE\&lt;\<\/i\>R\<i\>\&gt;\<\/i\>)

?

This change wouldn't change the semantic meaning, because neither
INVOKE nor INVOKE<R> are C++ language constructs but plain symbolic
definitions and in fact it would presumably slightly improve the
clarity that this is just such a construction when it would be spelled
as

<i>INVOKE&lt;</i>R<i>&gt;</i>  (in html: \<i\>INVOKE\&lt;\<\/i\>R\<i\>\&gt;\<\/i\>)

I should say that it is just my guess that this rewrite would also
solve the font-change-additional-space character problem, but maybe
you can give a better explanation for this artifact.

Thanks very much,

- Daniel

**Comment by tkoeppe** [comment]
It's the __dunder story all over again :-) I recommend a healthy dose of
reversing the italic correction.

**Comment by tkoeppe** [comment]
The problem also appears with *`DECAY_COPY*`. Maybe we should use `\placeholdernc` for all shouty pseudo-functions.

**Comment by zygoloid** [comment]
Yes, using \placeholdernc when the next character is punctuation seems to be an improvement. (I think itcorr is supposed to take care of that itself, but perhaps the font change is preventing that from firing?)

**Comment by jwakely** [comment]
I don't like the appearance of `INVOKE<R>` when the angle brackets are in italics, this is the output of `\tcode{\textit{INVOKE}<R>(f, t1, t2, ..., tN)}`

![display1](https://cloud.githubusercontent.com/assets/1254480/23733332/4e05c26e-0470-11e7-9db9-1e9fcb12a030.png)

This is the output of `\tcode{\placeholdernc{INVOKE}<R>(f, t1, t2, ..., tN)}`

![display1](https://cloud.githubusercontent.com/assets/1254480/23733424/b95038ec-0470-11e7-8cb6-908f51a4c56c.png)

And this is `\tcode{\placeholdernc{INVOKE<}R\placeholdernc{>}(f, t1, t2, ..., tN)}`

![display1](https://cloud.githubusercontent.com/assets/1254480/23733454/ecb4ce3c-0470-11e7-902d-ac097eff35a2.png)

I think the second one looks best, and searching for it works perfectly in Okular (which isn't true when `\placeholdernc` is not used).

**Comment by jwakely** [comment]
I haven't changed the presentation of any INVOKEs in the branch for P0604R0, https://github.com/cplusplus/draft/tree/motions-2017-03-lwg-13

But I will create a pull request to change them all to use `\placeholdernc` after it's merged.

**Comment by tkoeppe** [comment]
Second form, absolutely. When in doubt I recall Bringhurst's advice that it doesn't actually make sense to italicise punctuators, which usually results in the superior presentation.

**Comment by Dani-Hub** [comment]
2017-03-09 3:36 GMT+01:00 Jonathan Wakely <notifications@github.com>:

> I don't like the appearance of INVOKE<R> when the angle brackets are in
> italics, this is the output of \tcode{\textit{INVOKE}<R>(f, t1, t2, ...,
> tN)}
>
> [image: display1]
> <https://cloud.githubusercontent.com/assets/1254480/23733332/4e05c26e-0470-11e7-9db9-1e9fcb12a030.png>
>
> This is the output of \tcode{\placeholdernc{INVOKE}<R>(f, t1, t2, ...,
> tN)}
>
> [image: display1]
> <https://cloud.githubusercontent.com/assets/1254480/23733424/b95038ec-0470-11e7-8cb6-908f51a4c56c.png>
>
> And this is \tcode{\placeholdernc{INVOKE<}R\placeholdernc{>}(f, t1, t2,
> ..., tN)}
>
> [image: display1]
> <https://cloud.githubusercontent.com/assets/1254480/23733454/ecb4ce3c-0470-11e7-902d-ac097eff35a2.png>
>
> I think the second one looks best, and searching for it works perfectly in
> Okular (which isn't true when \placeholdernc is not used).
>
I'm also in favour for the second form. The reason why I made the
alternative suggestion was under the assumption that otherwise there exists
no solution for the font-change-space problem.

Thanks,

- Daniel

------------------------------
