### ISSUE TITLE
Move <numeric> to the algorithms clause

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#1511]
Especially with the addition of parallel algorithms, it is clear that the <numeric> header has more in common, and more shared wording, with the algorithms clause than the numerics clause.  For C++20, it would be good to move the header and relevant wording into clause 28 (Algorithms Library), and rename clause 29 from Numerics Library to Numerical Types Library.

**Comment by cubbimew** [comment]
+1 cppreference has always listed numeric algorithms on its [algorithms page](http://en.cppreference.com/w/cpp/algorithm)

**Comment by W-E-Brown** [comment]
<Adding SG6 chair Lawrence Crowl>

> On Mar 4, 2017, at 6:15 AM, Alisdair Meredith <notifications@github.com> wrote:
> Especially with the addition of parallel algorithms, it is clear that the header has more in common, and more shared wording, with the algorithms clause than the numerics clause. For C++20, it would be good to move the header and relevant wording into clause 28 (Algorithms Library), and rename clause 29 from Numerics Library to Numerical Types Library.
> 
Let's please be sure to consult with at least SG6 when we're ready to consider such renaming.

**Comment by W-E-Brown** [comment]
On 3/4/17, W Brown <webrown.cpp@gmail.com> wrote:
> <Adding SG6 chair Lawrence Crowl>
>
> On Mar 4, 2017, Alisdair Meredith <notifications@github.com> wrote:
>> Especially with the addition of parallel algorithms, it is clear that
>> the header has more in common, and more shared wording, with the
>> algorithms clause than the numerics clause. For C++20, it would be
>> good to move the header and relevant wording into clause 28
>> (Algorithms Library), and rename clause 29 from Numerics Library to
>> Numerical Types Library.
>
> Let's please be sure to consult with at least SG6 when we're ready to
> consider such renaming.

I agree with a separate clause for number types.  There are many clauses
that seems to me to be bags of stuff.  I would like to see some of them
split, but I'll leave that to folks more directly involved.

-- 
Lawrence Crowl

**Comment by zygoloid** [comment]
We like the direction suggested: move <numeric> to the Algorithms clause, and rename the Numerics clause to something that better describes its contents. LWG feedback is requested on this direction and on what Clause 29 should be named after the move.

**Comment by jensmaurer** [comment]
[P1076R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1076r0.html) presents the planned sectioning changes and asks for feedback from LWG and CWG. See also #1919.

**Comment by jensmaurer** [comment]
Fixed with #2243.
