### ISSUE TITLE
Class templates in Clause 33 are not indented

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1516]
For example:
````
namespace std {
  template <class R>
  class future {
````

This applies to all the lock types, `promise`, `future` and `packaged_task`. I'll fix it after motions-2017-03-lwg-17 is merged in, because that adds a new lock type (which is not indented, for local consistency).

**Comment by jwakely** [comment]
Instead of indenting the entire class bodies by an additional two spaces we could take the approach used by `reference_wrapper` 

````
namespace std {
  template <class R> class future {
````

**Comment by tkoeppe** [comment]
@jwakely: I'm not sure. That doesn't generallze well, and we can't do that for every class template. So perhaps we shouldn't do it for any. There's no problem with indenting that body by another two spaces.

**Comment by jensmaurer** [comment]
Uh, it's nowhere indented, it seems: [ios.overview], [vector.overview]. Do you have an example of your desired indentation?

**Comment by tkoeppe** [comment]
@jensmaurer: I thought we had already come to a decision on this in a different issue somewhere; check the wiki? [re.traits] would be an example of the style I believe I was referring to, although I think we ultimately decided against that and in favour of the style given in the OP here (in case where we do break the line).

**Comment by jensmaurer** [comment]
Follow-on discussions in #1576, partly overridden by #1754.
