### ISSUE TITLE
[lib] Inconsistent phrasing for "Shall not participate ..."

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1518]
Most SFINAE constraints in the library are specified via:

> Shall not participate in overload resolution unless [positive condition]

There is a small minority that use:

> Shall not participate in overload resolution if [negative condition]

In other words, most are phrased as a condition for "enable if" but some are phrased as a condition for "disable if". It would be better to be consistent.

**Comment by jensmaurer** [comment]
I think the "unless positive condition" reads better, unless we get an actual English negative in the "positive condition".

**Comment by zygoloid** [comment]
LWG is working on a new element to convey this information replacing these magic words.

**Comment by jensmaurer** [comment]
P0788R3 was approved in Rapperswil; see #2132.

**Comment by jensmaurer** [comment]
This is being handled by the "Mandates" series of papers.
