### ISSUE TITLE
operator~ in index uses ugly ~

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1521]
The index entry for `operator~` uses an ugly wide `~` rather than the code font `~` we use elsewhere.

**Comment by jensmaurer** [comment]
Hm... Is that new stuff? I can't find the quoted index entry. And the entry at the start of the index for ~operator uses:

`\indextext{~@\tcode{\tilde}|see{operator, ones' complement}}%`

**Comment by jensmaurer** [comment]
Sorry, looking again now, I can't find an index entry for "operator ~" at all.
