### ISSUE TITLE
Capitalization in [path.generic] grammar 

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1526]
Should the non grammarterm-text in the grammar be all lowercase, rather than complete sentences with capital letters and periods? That's what we do for things like "each non-white-space character that cannot be one of the above" in [lex.pptoken]

**Comment by jensmaurer** [comment]
Sounds like a good idea to me.

**Comment by jensmaurer** [comment]
This was fixed by @zygoloid's recent [fs.path.generic] grammar refactoring.
