### ISSUE TITLE
P0492R2 makes dot and dot-dot no longer grammarterms

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1527]
Following the changes to the generic path grammar ([path.generic]) the special filenames _dot_ and _dot-dot_ are no longer grammar terms, but are simply defined terms in [fs.def.filename]. (In terms of the grammar they are covered by the _filename_ production.)

Throughout the clause we use `\grammarterm{dot}` and `\grammarterm{dot-dot}` to give them a special appearance. Should we use `\term` instead? Should they only be italicized on their first definition? (IMHO that would make the specification unclear, even though it's consistent with how we present other defined terms).

**Comment by zygoloid** [comment]
Why do we need these terms at all? Instead of

> If the last filename is *dot-dot*, remove any [...]

we could say

> If the last *filename* is `..`, remove any [...]

I think that's what we'd do in the core wording in a case where we care about the particular spelling of a terminal.

**Comment by jensmaurer** [comment]
@zygoloid: Well, in [expr.ref], we sometimes put "(dot)" after `.` because it's so easy to confuse the operator with prose-level punctuation. And [expr.comma] only talks about "comma operator", never spelling `,` in prose text. Using "dot-dot" (as a \grammarterm) seems less susceptible to confusion.

**Comment by burblebee** [comment]
I also like the abstraction _dot_ and _dot-dot_ provide, in case some other OS had a similar grammar but used different tokens.

**Comment by jwakely** [comment]
> in case some other OS had a similar grammar but used different tokens.

They are pathnames in the generic pathname format, which is platform-agnostic. An OS can use different things for the same concepts (or have no way to represent them at all), but a pathname in the generic format still has to recognise `.` and `..` with the established meaning.

**Comment by jwakely** [comment]
So maybe we should just introduce them with `\term` and stop italicising them after the first definition.

**Comment by jensmaurer** [comment]
@jwakely: Fine with me.
