### ISSUE TITLE
[unique.ptr.single.ctor] Sloppy wording after application of LWG 2905

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1530]
After LWG 2905 (part of Kona 2017 LWG motion 20) is applied, we will have something along the lines of 

> If `D` is an lvalue reference type `A&`, then the signatures are:
>
>     unique_ptr(pointer p, A& d) noexcept;
>     unique_ptr(pointer p, A&& d) = delete;

The use of _signature_ is incorrect, as whether a function is defined as deleted or not is not part of the signature. See [defns.signature.member].

The paragraph dealing with the case where `D` is `const A&` will also have the same problem.

**Comment by jwakely** [comment]
In LWG 2905 I pointed out that we could replace the _see below_ stuff with the real signatures:

````
unique_ptr(pointer p, const D& d) noexcept;
unique_ptr(pointer p, remove_reference_t<D>&& d) noexcept;
````

Then we could simply say:

> The second constructor is defined as deleted if `is_reference_v<D>` is `true`"

**Comment by timsong-cpp** [comment]
Yes, that would fix it. In any event, p11 (the `const A&` case) seems redundant; it's just p10 (`A&`) with `A` being a `const`-qualified type.

**Comment by jwakely** [comment]
Yes, it's a curious piece of wording :-)

It dates from the very early days of rvalue references and move semantics, so seems to be acting as a tutorial for how the constructors work.

**Comment by jensmaurer** [comment]
@zygoloid, how much of this are you comfortable with addressing editorially?

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Use of the word "signature" is definitely wrong. Delete p11 editorially. Replace "signature" with something else editorially. Replacing the "see below" with the real declarations is fine. Use English "if D is a reference type, the second constructor is defined as deleted."
