### ISSUE TITLE
[fs.definitions] needs overhaul

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1534]
[fs.definitions] thoroughly fails to follow the rules for a "Terms and definitions" clause in an ISO standard. The definitions are an inconsistent mix of half-sentences (with a trailing period but a leading lowercase word) and full sentences, or in some cases multiple sentences and even multiple paragraphs with nested lists.

Each definition should be rewritten to conform to this rule from the ISO directives: "The definition shall be written in such a form that it can replace the term in its context. It shall not start with an article ("the", "a") nor end with a full stop."

We should also merge these definitions into [definitions]. (Merging [intro.defs] and [definitions] is also probably required for ISO directive conformance, but I'd prefer to investigate whether it would be feasible to  address that issue by splitting the standard into two Parts instead.)

**Comment by jwakely** [comment]
It may be that many of these should not be in Terms & Definitions at all, but just introduced in prose with `\term`.

**Comment by jensmaurer** [comment]
This seems to be fixed with the last-minute editorial changes or C++17.
