### ISSUE TITLE
[intro] contains subclauses that belong in [basic]

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1539]
[intro] contains subclauses that belong in [basic].

This has been made more obvious by the ISO-mandated extraction of clauses 1-3. We have the broad and not-particularly-technical introductory sections "Implementation compliance", "Structure of this International Standard", "Syntax notation", and "Acknowledgments". But jammed in between we have "The C++ memory model", "The C++ object model", "Program execution", and "Multi-threaded execution and data races", which belong in [basic].

... except that paragraphs 1-5 and 8 of [intro.execution] should perhaps stay in [intro], perhaps as an "Abstract machine" subclause of [intro.compliance].

Perhaps:

 * Insert a clause "Memory and objects" at the current location of [basic.stc], with subclauses [intro.memory], [intro.object], [basic.life], [basic.stc], [basic.align]
 * Insert a "Program execution" into [basic], maybe at the end, with subclauses [intro.execution] (renamed "Sequential execution"), [intro.multithread], [basic.start]

**Comment by jensmaurer** [comment]
In general, I agree, but I'd suggest that the new "Memory and objects" subclause be inserted at the front (before [basic.def]). Once you live with the fact that there are "objects" (created by forward references to various places), [intro.execution] and [intro.multithread] are fairly self-sufficient.

Further, while we're rearranging [basic], it seems we should first introduce a program [basic.link] before discussing [basic.def.odr]. Performing such a move would also nicely group all subsections dealing with names ([basic.def], [basic.scope], [basic.lookup]).

While we're at it, introducing a subsection "Expression properties" under [expr] would also offer a new home for [basic.lval].

**Comment by jensmaurer** [comment]
Editorial meeting consensus: do the "Perhaps" part first, then reconsider.

**Comment by jensmaurer** [comment]
See also #1771 and #1730 and #574.
