### ISSUE TITLE
Add mapping from removed section labels to new location of content in xrefs

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1547]
In the xrefs section, we should list all the C++14 section labels that no longer exist in C++17, along with an indication of where the content is now.

**Comment by tkoeppe** [comment]
Sounds good. We could start by extracting the labels now and from the C++14 FDIS to get a list of candidates.

**Comment by zygoloid** [comment]
After we branch, I'd like for us to maintain a "differences from C++17" list in xrefs incrementally. Might also be good to have a "differences from post-C++17 drafts" section that we remove for C++20 DIS.
