### ISSUE TITLE
[input.output] Invalid use of injected-class-name of dependent base

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1551]
[ifstream.cons] says "initializing the base class with `basic_istream(&sb)`" but as that's a dependent base we need to spell its name out in full: `basic_istream<char, traits>(&sb)`.

This occurs in paragraphs 1 and 2, and [ofstream.cons] 1 & 2, and [fstream.cons] 1 & 2.

**Comment by jwakely** [comment]
Or we could just say "initializing the base class with `&sb`"

**Comment by jensmaurer** [comment]
Now that we have class template deduction, `basic_istream(&sb)` might actually work, deducing the charT and traits template parameters from the parameter.

**Comment by jensmaurer** [comment]
[istringstream.cons] p1+2 and friends has the same issue, btw.

**Comment by jensmaurer** [comment]
I would actually opt towards spelling out the name of the base class in full. I find that a bit more readable than just "initializing with `&sb`".
