### ISSUE TITLE
"opt" should not be italicised

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#1556]
I think the "opt" modifier we subscribe to grammar items should not be set in italics, since it is not itself a piece of grammar.

I would probably set it like a named math function, i.e. `\operatorname{opt}`.

![image](https://cloud.githubusercontent.com/assets/6378233/24077282/5a0f3922-0bec-11e7-9d1f-d555d8e912cb.png)

**Comment by jensmaurer** [comment]
No objection from me, but that's probably not C++17 material.

**Comment by tkoeppe** [comment]
Sure. We should probably pick this up when we look at the xspace business.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Leave italics.
