### ISSUE TITLE
In Mac Preview, searching for "func.wrap.func.con" finds only the cross reference

### ISSUE THREAD

**Issue by jyasskin** [cplusplus/draft#1557]
It doesn't find 23.14.13.2.1 itself. Quoting the search does find both. However, searching for "func.not_fn" finds both with or without the quotes.

**Comment by jwakely** [comment]
Weird, I don't see any difference in the source between that and any other titles.

**Comment by jyasskin** [comment]
And this is weird: once I've searched for it with quotes, searching without quotes finds both. So I'll call this a bug in Mac Preview. Sorry for the noise here.
