### ISSUE TITLE
Don't abuse \xref

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#1561]
The `\xref` "see also" annotation is only meant for references to The Other Standard, not for simple cross-references within our own document. Such cross-references should simply say "See also" in ordinary text.

I have not yet surveyed the entire text for occurrences of this problem, but I fixed it in [library] and it's still rampant in [language.support].

**Comment by tkoeppe** [comment]
The remaining cases all seem to be in support.tex.

What makes this issue non-trivial is that some use cases look like

> `\xref` Local section A (x.y), Another local section (z.w), and ISO C 8.1.

We could split this into two paragraphs:

> `\pnum`
> See also Local section A (x.y) and Another local section (z.w).
>
> `\xref` ISO C 8.1.

But that would result in two consecutive "See also" paragraphs, slightly differently styled.

Suggestions?

**Comment by jensmaurer** [comment]
Looking at [support.types.layout] as an example, I think we should make sure that the running text already has all mentioned internal cross-references; then we can just drop them from \xref.
For this particular case, the text talking about "size of an object" should have the cross-reference to sizeof, for example.

**Comment by tkoeppe** [comment]
Yes, that sounds like the right solution - move the local references to better places and then keep the `\xref` for the C reference.
