### ISSUE TITLE
"method" as synonym for "class member function"

### ISSUE THREAD

**Issue by Axel-Naumann** [cplusplus/draft#1573]
I stumbled across mentions of "method" as a synonym for "class member
function" or "class member function template"

- [mem.poly.allocator.mem]/8
[ Note: This method and the construct methods that follow are overloads
for piecewise construction of pairs(20.4.2). —endnote]

- [string.view.iterators]/2
For a basic_string_view str, any operation that invalidates a pointer in
the range [str.data(),
str.data() + str.size()) invalidates pointers, iterators, and references
returned from str’s methods.

I suppose those should be replaced by "class member function" or "class
member function" as appropriate?

I believe that's editorial.

Cheers, Axel.

**Comment by jensmaurer** [comment]
Here you are.

**Comment by Axel-Naumann** [comment]
Thank you, Jens!
