### ISSUE TITLE
[alg.equal] Wrong wording (by copy/paste?)

### ISSUE THREAD

**Issue by lynnboy** [cplusplus/draft#1578]
At [[alg.equal]/3.2](https://github.com/cplusplus/draft/blob/master/source/algorithms.tex#L2115), the case should be "For the overloads with `ExecutionPolicy`," the "*no*" should be removed.

**Comment by tkoeppe** [comment]
The wording was added here:

https://github.com/cplusplus/draft/commit/151449b1fa1128a507f8d82d21a55a6dde13c4cb#diff-55a2410a80cb8710b07b579048668170R2104

@AlisdairM: Could you please check and advise?

**Comment by tkoeppe** [comment]
@zygoloid: This looks like a misapplication of [P0467r2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0467r2.html).
