### ISSUE TITLE
[any.cons] Replace 'contained object' by 'contained value' in Kona motion edits

### ISSUE THREAD

**Issue by lynnboy** [cplusplus/draft#1580]
(Edited by @jensmaurer)

#1401 harmonized [any] to use 'contained value', but Kona motion edits re-introduced 'contained object', which should be changed to 'contained value'.

**Comment by tkoeppe** [comment]
@lynnboy: Could you please post self-contained issue bodies? The issue title is not really meant for consumption on the details page; the title's purpose is to identify the issue in the list.
