### ISSUE TITLE
Second sentence of 1.10p6 is redundant

### ISSUE THREAD

**Issue by hboehm** [cplusplus/draft#159]
Please delete 

"If A and B are modifications of an atomic object M and A happens before (as defined below) B, then A shall precede B in the modification order of M, which is defined below. [ Note: This states that the modification orders must respect the “happens before” relationship. —end note ]"

from 1.10p6 [intro.multithread].  The normative sentence is redundant with 1.10p15.  There seems to be a concensus among SG1 commentators that it's not worth preserving the note, which seems a bit shallow.  It could also be added to p15 or integrated into p19.

**Comment by jensmaurer** [comment]
This is now 1.10.1 [intro.races] p4 and p13.
