### ISSUE TITLE
[charconv] Elementary string conversions wording nits

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1594]
A few places in [utility.to.chars] and [utility.from.chars] say "minus sign". Should that just be `'-'` instead?  We don't mean the Unicode U+2212 character, for example, and we don't have to worry about wide character versions of `'-'` here, it's just `'-'`.

[utility.to.chars] p5 says "the range 10..35 (inclusive)" and "`a..z`", is that syntax clear enough? Would "the range [10,35]" be better for the former?

**Comment by jensmaurer** [comment]
@jwakely: And what about the latter, then?

**Comment by jwakely** [comment]
Maybe, if that's clear. If everyone else is happy with the ".." notation then that's OK, but I don't think it's something we use or define anywhere else. Is it defined or used in some other ISO standard?

**Comment by jensmaurer** [comment]
Editorial meeting consensus: First change is good. Second change: don't do, it's good enough and the alternatives are worse.
