### ISSUE TITLE
[expr]/12 optional conversion

### ISSUE THREAD

**Issue by BRevzin** [cplusplus/draft#1597]
The wording currently reads:

> If the expression is a prvalue after this optional conversion, the temporary materialization conversion is applied.

"this optional conversion" refers to the lvalue-to-rvalue conversion. Optional isn't a good word here, since the conversion itself is mandatory - just only conditionally applied. Maybe "If this conversion is applied and the resulting expression is a prvalue, the temporary materialization conversion is applied"? Or something along those lines.

**Comment by timsong-cpp** [comment]
The proposed rewording is incorrect. Materialization applies to all discarded prvalues, whether the prvalue is because the expression started off as a prvalue or because the lvalue-to-rvalue conversion was applied by the previous sentence to a volatile-qualified glvalue.

**Comment by BRevzin** [comment]
"If the expression was a prvalue, or becomes a prvalue after applying the lvalue-to-rvalue conversion, the temporary materialization conversion is applied." ?  "The temporary materialization conversion is applied if, after applying the lvalue-to-rvalue conversion if necessary, the expression is a prvalue."? "after conditionally applying the lvalue-to-rvalue conversion"?
