### ISSUE TITLE
No synopsis for <strstream>

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1603]
The deprecated header `<strstream>` does not appear to have a synopsis.

**Comment by jensmaurer** [comment]
I can't find one in C++03, either.

Is it really editorial to come up with a synopsis?

**Comment by tkoeppe** [comment]
@jensmaurer: That wouldn't be the first time. P0175 came up with a ton of synopses editorially, although we did run it by LWG.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Yes, we're providing a <strstream> synopsis, even though it's in Annex D.

**Comment by jwakely** [comment]
The entire synopsis is just:

    namespace std {
      class strstreambuf;
      class istrstream;
      class ostrstream;
      class strstream;
    }

Also, the preamble says " The header <strstream> defines **three** types" but it also defines the streambuf type.
