### ISSUE TITLE
fs.op.canonical still defined in terms of absolute(p, base)

### ISSUE THREAD

**Issue by cubbimew** [cplusplus/draft#1620]
[fs.op.canonical](https://github.com/cplusplus/draft/blob/master/source/iostreams.tex#L13796-L13799) says it is equivalent to "absolute(p, base).", but absolute no longer takes a base argument as of p0492r2

More likely to be editorial, absolute still has a base argument in the synopsis of [fs.filesystem.syn], though it doesn't have it in [fs.op.absolute]

**Comment by jwakely** [comment]
This seems non-editorial.

**Comment by jwakely** [comment]
The synopsis part is though, p0492 said "_Change [fs.op.absolute] and **update the synopsis in [fs.filesystem.syn] accordingly**_:" but I failed to do that.

**Comment by jwakely** [comment]
The synopsis is fixed by ae6271c88727c3fabe7dd8258f8687b369d83d6d

**Comment by cubbimew** [comment]
all right, I'll send the non-editorial bit to lwg.

**Comment by cubbimew** [comment]
This is now [LWG 2956](http://cplusplus.github.io/LWG/lwg-active.html#2956)
