### ISSUE TITLE
[filesystem_error.members] what() function to use non-existant function native_string() 

### ISSUE THREAD

**Issue by BoPersson** [cplusplus/draft#1629]
The description fo the what() function says:

"Returns: A string containing runtime_error::what(). The exact format is unspecified. Implementations
are encouraged but not required to include path1.native_string() if not empty, path2.native_-
string() if not empty, and system_error::what() strings in the returned string."

The native_string() should likely be just string().

**Comment by jwakely** [comment]
More likely `native()`

**Comment by BoPersson** [comment]
native() returns wstring on Windows, so cannot be used in an exception what-message.

**Comment by jwakely** [comment]
Good point. My implementation uses `string()` but then there's no difference for POSIX. Boost also uses `string()`.

**Comment by jensmaurer** [comment]
Is this editorial? The fix seems normative.

**Comment by jwakely** [comment]
It's being dealt with as an LWG issue.

**Comment by jwakely** [comment]
Although it's arguably not normative, since `native_string()` doesn't exist, so the current wording is inconsistent, and it's only encouragement anyway.

**Comment by jwakely** [comment]
http://cplusplus.github.io/LWG/lwg-active.html#2965
