### ISSUE TITLE
[fs.dir.entry.obs] directory_entry members to call non-existent functions

### ISSUE THREAD

**Issue by BoPersson** [cplusplus/draft#1630]
The description for directory_entry::exists(error_code& ec) requires it to call 

(std::filesystem::) exists(this->status(), ec)

but there is no such function. Probably intended to be a call to filesystem::exists(this->status(ec));

Most member functions in this subclause seem to have the same issue.

**Comment by jwakely** [comment]
Introduced by 221d52ef0d9a3a0c7449be5dee586eda365998db but http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0317r1.html is correct, so it's an editorial mistake applying the paper.
