### ISSUE TITLE
[fs.filesystem.syn] only lists old absolute function

### ISSUE THREAD

**Issue by BoPersson** [cplusplus/draft#1631]
The synopsis [fs.filesystem.syn] contains one signature

path absolute(const path& p, const path& base = current_path());

while the definition in [fs.op.absolute] contains two different overloads

path absolute(const path& p);
path absolute(conts path& p, error_code& ec);

**Comment by jwakely** [comment]
Already fixed with ae6271c88727c3fabe7dd8258f8687b369d83d6d
