### ISSUE TITLE
[fs.op.canonical] uses non-existent absolute(p, base);

### ISSUE THREAD

**Issue by BoPersson** [cplusplus/draft#1632]
The description for canonical says:

Returns: A path that refers to the same file system object as absolute(p, base).

However, there is no function matching that signature.

**Comment by jwakely** [comment]
That's not an editorial problem so shouldn't be reported here.

It's already in the issues list as http://wg21.link/lwg2956

**Comment by jwakely** [comment]
Also #1620 (where it was originally reported before being moved to the issues list).
