### ISSUE TITLE
Building pdf is not working

### ISSUE THREAD

**Issue by fro0m** [cplusplus/draft#1634]
Following the instructions
Running `latexmk -pdf std` from source dir does not do anything
and running `make rebuild` returns
```
pdflatex std | grep -v "^Overfull"
Makefile:27: recipe for target 'rebuild' failed
make: *** [rebuild] Error 1
```

**Comment by fro0m** [comment]
environment kubuntu 16.10 x64

**Comment by jensmaurer** [comment]
Are you really sure you're in the "source" subdirectory when you run `latexmk -pdf std` ?

There should be 45 .tex files in the source/ directory.

Is "latexmk" and the latex suite installed on your box (you likely need to install it separately with your package manager)?

Other than that, "rm -rf" and start over; your local copy of the github repository seems broken.

**Comment by jwakely** [comment]
Yes, this works fine here. I don't think there's a problem with the content of the repo, only your copy of it.

**Comment by fro0m** [comment]
I reinstaled Latex packages. It works now.
