### ISSUE TITLE
[lex.string] p5 examples involving non-trigraphs

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1635]
Two of the examples explain that trigraphs are not interpreted inside raw string literals. The examples are correct as-written, but might be considered misleading after the (global) removal of trigraphs. Maybe add a cross-reference to [diff.cpp14.lex] and/or a bit of explanatory text?

**Comment by zygoloid** [comment]
I excised these two examples, and added a new example to retain some motivation for the feature's existence.
