### ISSUE TITLE
[facet.num.put.virtuals]/1 Bad grammar

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1638]
Paragraph 1 [ends with](https://github.com/cplusplus/draft/blob/master/source/locales.tex#L2846):

> In the following description, a local variable initialized with: locale loc = str.getloc();

Doesn't sound right.

**Comment by jensmaurer** [comment]
The description that follows continues to use `str.getloc()` in a number of places, and uses `loc` only three times. Go figure.
