### ISSUE TITLE
[cfenv.syn] some FE_ macros may not be defined

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1639]
(from std-discussion)

The synopsis shows the FE_ macros as always defined, although C specifies that some are only defined if the corresponding feature is available on the platform.

**Comment by jensmaurer** [comment]
This seems LWG matter.

**Comment by tkoeppe** [comment]
Fixed by b9c5272c78fb312883cb548219b7fd2cb44280c7.
