### ISSUE TITLE
[over.call] wording makes little sense

### ISSUE THREAD

**Issue by BRevzin** [cplusplus/draft#1642]
This is a purely editorial issue. The wording currently reads:

> Thus, a call `x(arg1,...)` is interpreted as `x.operator()(arg1, ...)` for a class object `x` of type `T` if `T​::​operator()(T1, T2, T3)` exists and if the operator is selected as the best match function by the overload resolution mechanism ([over.match.best]).

What does it mean for `T::operator()(T1, T2, T3)` to exist? What are `T1`, `T2`, and `T3`? The idea here, I think, is to clarify that `operator()` is called if it exists, as opposed to some function pointer conversion that could happen and be a better match... I can't propose a better wording since I'm not entirely sure what the wording is currently intended to convey.

**Comment by jensmaurer** [comment]
Editorial meeting: Drop "Thus". Drop (T1,T2,T3). Instead of "args1...", use "expression-list/opt" (grammar). Move "A call" to a new paragraph. Also in 12.6.5 and 12.6.6. Use a fairly large hammer, possibly excising "x" as well.
