### ISSUE TITLE
Spurious remove_all_extents<T> in is_destructible definition

### ISSUE THREAD

**Issue by Dani-Hub** [cplusplus/draft#1644]
In Table 42 — "Type property predicates" for

```
template <class T>
struct is_destructible;
```

the relevant text in the Condition column is:

Either `T` is a reference
type, or `T` is a complete
object type for which the
expression
`declval<U&>().~U()` is
well-formed when treated
as an unevaluated operand
(Clause 8), where `U` is
`remove_all_extents<T>`.

The end of the sentence should refer to

`remove_all_extents_t<T>`

instead of

`remove_all_extents<T>`.

For the record: This was correctly using `remove_all_extents<T>::type` in

http://cplusplus.github.io/LWG/lwg-defects.html#2049

**Comment by timsong-cpp** [comment]
Introduced by 7997487.
