### ISSUE TITLE
[atomics.syn] missed edit for atomic_exchange signature in P558R1

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1647]
In

```
template<class T>
  T atomic_exchange(volatile atomic<T>*, T) noexcept;
```

the second "T" should actually be `typename atomic<T>::value_type` to avoid deduction for that parameter. The neighbor overload (without volatile) has it correct. This is a bug in P558R1.

**Comment by jensmaurer** [comment]
Can we fix that editorially?

**Comment by jensmaurer** [comment]
This should be handled as an LWG issue.

**Comment by jensmaurer** [comment]
This is LWG 2988.

**Comment by CaseyCarter** [comment]
LWG 2988 has been applied to the WP; I believe this issue is resolved.
