### ISSUE TITLE
[strings] Use "Equivalent to" where appropriate

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#165]
From an email by Jeffrey Yasskin:

Many functions in the strings clause use formulations like:

[string.cons]/15:

> Effects: Same as basic_string(il.begin(), il.end(), a).

[string.capacity]/15:

> Effects: Behaves as if the function calls:
>            erase(begin(), end());

[string::insert]/27:

> Effects: insert(p, il.begin(), il.end()).
> Returns: [what the above insert() call returns]

instead of the "Equivalent to" wording defined in
[structure.specifications]/4. These should all be changed to
"Equivalent to" for consistency and conciseness.

**Comment by burblebee** [comment]
This needs to be opened as an LWG issue.  I've asked for an issue to be opened for this throughout the spec, but I don't know it's number yet.

**Comment by jensmaurer** [comment]
LWG issue https://cplusplus.github.io/LWG/lwg-defects.html#2679

**Comment by jensmaurer** [comment]
I've asked for another LWG issue, explicitly listing the places that need fixing.

**Comment by jensmaurer** [comment]
[LWG 2841](https://cplusplus.github.io/LWG/lwg-active.html#2841)
