### ISSUE TITLE
Wrong comment in [intro.execution]/12's example

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#1650]
[[intro.execution]/12](http://eel.is/c++draft/intro.execution#12):

> A _full-expression_ is
>
> ... 
> 
> [ _Example_:
> 
> ```
>     struct S {
>           S(int i): I(i) { } // full-expression is initialization of I
>           int& v() { return I; }
>          ~S() noexcept(false) { }
>     private:
>          int I;
>     };
>     S s1(1); // full-expression is call of S::S(int)
>     void f() {
>           S s2 = 2;      // full-expression is call of S::S(int)
>           if (S(3).v())        // full-expression includes lvalue-to-rvalue and
>                                // int to bool conversions, performed before
>                                // temporary is deleted at end of full-expression
>           { }
>           bool b = noexcept(S());       // exception specification of destructor of S
>                                         // considered for noexcept
>                                          // full-expression is destruction of s2 at end of block
>     }
>     struct B {
>           B(S = S(0));
>     };
>     B b[2] = { B(), B() };     // full-expression is the entire initialization
>                                // including the destruction of temporaries
> ``` 
> —_end example_ ]

The comment

>   // full-expression includes lvalue-to-rvalue and

above, should be replaced by

>  // full-expression includes the temporary-materialization and

Note that the prvalue `S(3)` is subjected to a temporary-materialzation convertion to an xvalue. The dot(.) class member operator requires a glvalue as a postfix expression. See [[expr.ref]/2](http://eel.is/c++draft/expr.ref#2).

**Comment by cpplearner** [comment]
AFAIK `S(3).v()` in its own is an lvalue of type `int`. It is then converted to an rvalue, and then converted to `bool`.

The comment probably does not contain what you expect it to say, but I personally don't think it is factually wrong.

Just my two cents.

**Comment by cpplearner** [comment]
As far as I know, conversion from "lvalue of type `int`" to "rvalue of type `bool`" is a [standard conversion sequence](http://eel.is/c++draft/conv#def:standard_conversion_sequence) that consists of an lvalue-to-rvalue conversion ([\[conv.lval\]](http://eel.is/c++draft/conv.lval)) and a boolean conversion ([\[conv.bool\]](http://eel.is/c++draft/conv.bool)). The comment "int to bool conversion" is just a detailed way of describing the latter (the boolean conversion).

**Comment by jabelloc** [comment]
You are right. The boolean conversion expects a prvalue and so, an lvalue-to-rvalue conversion is required before that. But again, the temporary materialization conversion is also required because of [expr.ref]/2. Thanks for the feedback.

**Comment by zygoloid** [comment]
The comment is correct as written. The point of the example is to demonstrate that certain constructs occur before the temporary is destroyed; saying that the creation of the temporary is one of those things seems unnecessary to me.

**Comment by MDPModelChecker** [comment]
Why does this paragraph state that for this construct: "S s1(1)" "full-expression is call of S::S(int)"? Shouldn't be the full expression the entire construct itself (because it is an init-declarator)? It would make sense if the comment said: "full-expression contains call of S::S(int)". Am I not understanding something correctly?
