### ISSUE TITLE
Why does [basic.scope.class]/2 must be NDR?

### ISSUE THREAD

**Issue by AlexanderMace** [cplusplus/draft#1652]
[[basic.scope.class]/2](http://eel.is/c++draft/basic.scope.class#2):

> A name N used in a class S shall refer to the same declaration in its context and when re-evaluated in the completed scope of S. No diagnostic is required for a violation of this rule.

I don't see the need for the NDR. As far as I can tell, it is very easy for any compiler to detect the anomaly indicated by the first part of the sentence above.

**Comment by tkoeppe** [comment]
This issues list is for *editorial* issues only. If you would like to discuss the normative content of the standard, please visit isocpp.org, try the [std-discussion](https://groups.google.com/a/isocpp.org/forum/#!forum/std-discussion) mailing list, or get in touch with the committee in ways described there.
