### ISSUE TITLE
Globally replace unqualified uses of "concept"

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/draft#1659]
P0734R0 will presumably define "concept" as a term-of-art. The C++ working draft makes use of that term for its meaning in English. Other words should be chosen; perhaps a concept in the IS is sometimes a great notion.

**Comment by jensmaurer** [comment]
- notion
- abstraction
- idea
- theory

**Comment by faisalv** [comment]
And maybe we can rename clause 6 to Basics (as opposed to Basic Notions) or my slight preference would be for Foundations or something such, since basic can readily imply simple - and odr-use, linkage, lifetime and storage aren't always that ....

**Comment by jensmaurer** [comment]
Editorial meeting consensus: "Basic Concepts" -> "Basics"
