### ISSUE TITLE
[util.smartptr.shared] should not duplicate non-member functions in class synopsis

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1662]
They are already covered in [memory.syn].

**Comment by tkoeppe** [comment]
A fair number of declarations are duplicated, e.g. all the `make_unique`s. I'm not convinced that's a bad thing. @zygoloid, any opinions?

**Comment by tkoeppe** [comment]
We do this elsewhere, too, e.g. [vector] repeats the relational operators from [vector.syn].

**Comment by tkoeppe** [comment]
I believe this is resolved by 1c43bc8685335048cd30042a712c0b40ff7f890a, at least as much as we're comfortable with. I think `swap` is still repeated, but we do that everywhere.
