### ISSUE TITLE
runtime vs run-time

### ISSUE THREAD

**Issue by faisalv** [cplusplus/draft#167]
is there a good reason for using both spellings in the standard? might be nicer to stick to one ...

**Comment by burblebee** [comment]
Which one do you prefer?

**Comment by tkoeppe** [comment]
Good point, both look equally popular in body text (with only a handful of uses each). @zygoloid, @jwakely, any opinions?

**Comment by zygoloid** [comment]
Run-time is antiquated. Let's consistently use runtime for all uses. (But I question whether these uses are really appropriate, because they suggest a separation between translation and execution that is not required...)

**Comment by faisalv** [comment]
FWIW - I just want to second richard's questioning of the separation between translation and execution - since I remember a thread during which several of the core folks argued viguorously that the standard maintains no distinction between compile-time and run-time execution (at the expense of clarity in specifying the real connotations behind constant expressions in my opinion - but I have sympathy for their arguments)

**Comment by jensmaurer** [comment]
@faisalv: This is an editorial issue to harmonize the spelling of "runtime". This has been addressed. I think any questions about talking about "runtime" in the first place should be directed to CWG or LWG with specific examples.

**Comment by faisalv** [comment]
@jensmaurer thanks - i'm aware this is an editorial issue - just cared enough to document seconding Richard's raising the question on this thread - will leave it to those who argued so ardently against the distinction to approach the WGs.
