### ISSUE TITLE
[class.temporary]p6: "should" in note

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1674]
Bullet 6.11 says:

> A temporary bound to a reference in a *new-initializer* (8.3.4) persists until the completion of the *full-expression* containing the *new-initializer*. [*Example*:
> ```
> struct S { int mi; const std::pair<int,int>& mp; };
> S a { 1, {2,3} };
> S* p = new S{ 1, {2,3} }; // Creates dangling reference
> ```
> — *end example* ] [ *Note*: This may introduce a dangling reference, and implementations should issue a warning in such a case. — *end note* ]

Even if this note were sound advice (it is not in all cases: such a warning may have false positives if the allocation is consumed before the full-expression ends), providing normative encouragement via "should" in a note is verboten (ISO Directives, part 2, 7th ed, 24.5).

**Comment by tkoeppe** [comment]
Demote to footnote?

**Comment by hubert-reinterpretcast** [comment]
Footnotes are similarly restricted (ISO Directives, part 2, 7th ed., 26.5).
