### ISSUE TITLE
Editorial: difference between "well defined" and "well-defined"?

### ISSUE THREAD

**Issue by mclow** [cplusplus/draft#1675]
The standard uses 'well defined' in 7 different places.
It uses "well-defined" (with a hyphen) in 64 places.

A quick look at the seven suggests that most of them could be replaced with 'well-defined', increasing the consistency of the standard.

**Comment by dhouck** [comment]
According to #1587, it’s supposed to be hyphenated when it’s an adjective. The grammar is slightly different in the cases without a hyphen.

**Comment by mclow** [comment]
If the difference is intentional, then this can be closed as NAD.  I just want to make searching the standard easier ;-)

**Comment by tkoeppe** [comment]
The [style guide](https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines#hyphens-miscellanea) says that "well-defined" is the way to spell the adjective. The new cases of "well defined" seem to have come in via recent motions; I assume LWG reviewed those before we added the style guide entry.

**Comment by jensmaurer** [comment]
See also #1618.

**Comment by jensmaurer** [comment]
Uh, sorry, #1618 is about well-formed, this issue is about well-defined.
