### ISSUE TITLE
[class.derived] has confusing cross-reference for inheriting constructors

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1681]
[class.derived] p2 says:

> Constructors of a base class can also be inherited as described in 10.3.3.

But 10.3.3 is only about the syntax, it says nothing much about inheriting constructors. Could we also have a cross-reference to 15.6.3 [class.inhctor.init], even if only in a note?
> Constructors of a base class can also be inherited as described in 10.3.3. _[Note:_ But don't look there, you're probably trying to find 15.6.3 instead. _--end note]_

**Comment by jensmaurer** [comment]
Richard objects; see #1687.
