### ISSUE TITLE
[over.over]/p4 what "set of selected functions"?

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#1691]
After the addition of concepts, we have the wording "All functions with associated constraints that are not satisfied (17.4.2) are eliminated from the set of selected functions.", but there's no mention of a "set of selected functions" up to this point.

From comments to branch at https://github.com/cplusplus/draft/commit/18b788bde093045d34dff93e2b80d7b7a8aedc76:

burblebee:
> what "set of selected functions"? up to this point, we've only discussed if/whether a function is selected - there is no set. At least the previous text (although still problematic) started with "If more than one function is selected" so that one could extrapolate that the set must be from the selected functions.
> 
> The whole section could use some work for that matter. For example, where did "the overload set" in p1 come from? And in the next sentence, "A function
> template name is considered to name a set of overloaded functions in such contexts." - did we really mean to restrict this to function templates? And, if not in one of these "certain contexts" where a function is "resolved", the name doesn't name a set of overloaded functions?

zygoloid:
> The start of p1 says: "A use of an overloaded function name without arguments is resolved in certain contexts to a function, a pointer to function or a pointer to member function for a specific function from the overload set."
> 
> So this set is the set of functions associated with the "use of an overloaded function name".
> 
> I agree this subsection would benefit from rework, but I don't think this particular change materially affects the clarity in this regard. Please provide a separate editorial issue or pull request if you feel strongly about improving this wording.

I don't feel that the "overload set" mentioned in p1 is sufficient.  I would like to see this "reworked".  Even giving the overload set a name (S?) and referring to it would be a huge improvement and clarify things significantly.

**Comment by zygoloid** [comment]
p2 says:

> If the name is a function template, template argument deduction is done (17.9.2.2), and if the argument deduction succeeds, [...]

... which completely fails to account for the case where the name resolves to an overload set containing a function template and other things (more functions / function templates).

**Comment by jensmaurer** [comment]
The specific issue mentioned in the title can be resolved by replacing "set of selected functions" by "set of overloaded functions". We talk about the latter all over [over.over].

**Comment by jensmaurer** [comment]
Should we move this into a core issue, due to the larger changes, or should I try again?

**Comment by zygoloid** [comment]
Too large and involved to tackle editorially, and the wording needs normative changes => to be converted to core issue.

**Comment by jensmaurer** [comment]
The wording in [over.over] was improved in [P1972R0](https://wg21.link/p1972r0), see commits 7fc7106e4d94e9cf8daf99cb8da5cf0c287097ea and b369c9229f9b3223c967ab00ccb1e54eafec6a7a.
