### ISSUE TITLE
[util.smartptr.shared.create]: Broken declaration by "\placeholder{}" macro

### ISSUE THREAD

**Issue by Dani-Hub** [cplusplus/draft#1696]
[util.smartptr.shared.create] before p2 shows a broken `make_shared` and `allocate_shared` prototype declaration presumably due to an incomplete `\placeholder{}` expansion. ~~In addition, the variadic template parameter name `Args` is missing~~ (I just checked p0674r1 and found that the omitted parameter seemed to be intended):

```
template<class T, ...>
shared_ptr<T> make_shared(\placeholder{args});
template<class T, class A, ...>
shared_ptr<T> allocate_shared(const A& a, \placeholder{args});
```

**Comment by tkoeppe** [comment]
Thanks for reporting! Fixed by a35fb3e2db1f76777bd1d509456fb10beed6ce0e.
