### ISSUE TITLE
[temp.constr.order]/p2 wrong definition for subsume

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#1699]
The spec places the definition of subsume in [temp.constr.order]/p2, but as I read it, subsume is defined in [temp.constr.order]/p1, with the qualification "as described below" to specify what must hold true in order to satisfy this definition.  Can we turn these two paragraphs into a proper definition for subsume?

From my correspondence with Richard:

me:
This ([temp.constr.order]/p1) is the definition of subsume, not below. Below describes how to determine if P implies Q, as referenced here with "as described below". Please move definition here.

Richard:
I don't think I agree. We never define what "implies" means; this is just a warm-up sentence telling you informally what we're going to precisely define below. The definition below is the formal definition of "subsumes".

me:
As I read it, the "implies" part is defined "as described below", so it all works.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Delete first 1.5 paragraphs of [temp.constr.order]. "Then, P subsumes Q..." stays (drop "Then"). Split footnote into two (for DNF and CNF) and attach to mentions in definition of "subsumes".
