### ISSUE TITLE
[diff.cpp14.library] missing Annex C note for new C++17 headers

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1700]
[diff.cpp03.library] has a note for new headers added in C++11, and [diff.cpp11.library] has a note for the one new header added in C++14. We do not appear to have a similar note for the headers added in C++17 `<any>`, `<optional>`, `<variant>`, `<filesystem>`, `<execution>`, `<memory_resource>`, maybe `<charconv>` (or should that be handled as C++20)?

**Comment by zygoloid** [comment]
If you put together a pull request for this, I would take it as an editorial change to C++17.

**Comment by tkoeppe** [comment]
@timsong-cpp: Ping, the ship is leaving...

**Comment by zygoloid** [comment]
Merged to c++17 in 
commit 450d9fc2ceb74cc394e76273e79c5d9b6e4fd66a.
