### ISSUE TITLE
Minor styles inconsistency in single-line comments

### ISSUE THREAD

**Issue by FrankHB** [cplusplus/draft#1709]
Result of searching "// hash" shows...

```
[vector.syn]
// hash support
[unord.map.overview]
// hash policy:
[unord.set.overview]
// hash policy:
[unord.multimap.overview]
// hash policy
[unord.multiset.overview]
// hash policy:
[thread.thread.id]
// Hash support
```

Well, there are at least 2 problems.

- Which case of letter should be used after `//`?
- When to use trailing colon in a single-line comment?

Not sure if there has been already some rules about styles in comments, esp. in synopses. (Nonetheless, the examples above seem to be unintended.)

**Comment by tkoeppe** [comment]
I think we agreed we usually want:

    // \ref{...}, hash support

Additional punctuation was deemed unnecessary, as was capitalization.
