### ISSUE TITLE
[C++17 DIS comment 001] remove [intro.refs] bullet 1.4

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1713]

**Comment by tkoeppe** [comment]
This seems unfortunate; I suppose what really should happen is that p2 should mention that the relevant library clauses are to be understood together with the corrigenda.

**Comment by zygoloid** [comment]
ISO's comment says: "Normative references list doesn't need to list corrigenda or amendments – these are assumed to be part of the main document."

Unclear if "doesn't need to" really means "shall not", or whether we have discretion here. Possibly we could refer to the corrigenda in a note in p2?

**Comment by tkoeppe** [comment]
No, in that case we should delete the entry as requested. Presumably this is to avoid mandatory recursive document purchases.

Well, I guess we could put the TC into our new Bibliography and go with the note :-)

**Comment by zygoloid** [comment]
https://github.com/cplusplus/draft/pull/1743 is ready for review

**Comment by zygoloid** [comment]
Done. Resolution: ACCEPTED
