### ISSUE TITLE
[C++17 DIS comment 006] [temp.over.link]p8: change comments to lowercase

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1718]

**Comment by jensmaurer** [comment]
We usually use lowercase in situations like that, so I'd suggest ACCEPT.

**Comment by zygoloid** [comment]
Agreed. PR #1745 ready for review.

**Comment by zygoloid** [comment]
Merged, and merged to master as 577968dc. Resolution: ACCEPTED
