### ISSUE TITLE
[C++17 DIS comment 007] [support.start.term]p13 restore xref to C 7.22.4.5

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1719]
This is unclear: C 7.22.4.5 says that it's implementation-defined whether standard file buffers are flushed. Did this change between C99 and C11? Perhaps we should delete the note instead?

**Comment by tkoeppe** [comment]
I haven't traced the change back yet, but it seems that the original reference was inappropriate there (7.22.4.5 is `_Exit`, not `quick_exit`); a "see also" cannot appear in that place, and we already have the reference to 7.22.4 right below that covers the entire set of exit functions.

**Comment by tkoeppe** [comment]
I deleted the reference in faba9f732c1c74e03c5a05764da1d7481ea94d94, mostly because a "see also" isn't allowed there, and I figured that the reference was not helpful.

**Comment by tkoeppe** [comment]
Suggested response: REJECT, explanation: The cross-reference was incorrect and not helpful, and a cross-reference may not appear inline anyway. A better reference to 7.22.4 as a whole is provided (in the correct form) in the very next paragraph.

**Comment by jensmaurer** [comment]
@tkoeppe: Agreed.

**Comment by zygoloid** [comment]
I think this misses the point.

Here's the rest of the note to which the xref was attached:

> [ Note: The standard file buffers are not flushed. — end note ]

But `quick_exit` calls `_Exit(status)`, which per p2 "has the semantics specified in the C standard library"; in C11 7.22.4.5, we find: "Whether open streams with unwritten buffered data are flushed, open streams are closed, or temporary files are removed is implementation-defined."

So the xref to C's spec for `_Exit` *was* appropriate, but the problem is that the note is simply wrong.

Suggested response: ACCEPTED WITH MODIFICATION. The note containing the cross-reference was not justified by the normative wording and has been removed.

**Comment by tkoeppe** [comment]
@zygoloid: I see, makes sense.

**Comment by zygoloid** [comment]
Note removed in 73b06fa1 on c++17 and 132326619d234a2b62819fd3a2cba6d9c654be23 on master. Resolution: ACCEPTED WITH MODIFICATION, per above.
