### ISSUE TITLE
Define non-trivial operations

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#172]
Mike Miller on std-core:

> I would expect by normal English rules that a "non-trivial operation" is simply an operation that isn't specifically defined to be trivial in clause 12 or section 3.9.  However, perhaps the wording of 20.11.4.3 should be revised to say explicitly "an operation other than those defined as trivial in 3.9 or Clause 12" just to be extra clear that that is the intention.

**Comment by jensmaurer** [comment]
20.11.4.3 no longer exists in the standard, and I can't find the word "non-trivial" anywhere near that section.

**Comment by timsong-cpp** [comment]
https://listarchives.isocpp.org/cgi-bin/wg21/message?wg=lib&msg=34451

This is talking about the `is_trivially_*` traits.
