### ISSUE TITLE
[C++17 DIS comment 010] [any_cons]p2, `in_place<T>` should say `in_place_type<T>`

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1721]

**Comment by tkoeppe** [comment]
We also don't seem to have any library index entries for those in-place types.

**Comment by tkoeppe** [comment]
Commit in master: 2c634465cbd94fd0738171623b5b924a0fc8d60c

**Comment by zygoloid** [comment]
Looks good to me. Resolution: ACCEPTED.

**Comment by zygoloid** [comment]
Commit in master got rebased to 1a4e554f910cdd1df3d2d8a62c2270dd1219eddc. Merged to c++17 branch as 94e64d093835bc827c536e85629cd9fcc89cf026.
