### ISSUE TITLE
[C++17 DIS comment 012] [algorithms.parallel.user]p1 Repeated period at end of paragraph..

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1724]

**Comment by tkoeppe** [comment]
Commit on master: https://github.com/cplusplus/draft/commit/da100dc8319f9b4bd468918264f3902980dfaaea

**Comment by zygoloid** [comment]
Looks good. Resolution: ACCEPTED.

**Comment by zygoloid** [comment]
Commit on master rebased as 788b07ba87458c35228ecbdccb2e9dfac37eebf8. Merged to c++17 branch as
