### ISSUE TITLE
[C++17 DIS comment 013] [alg.equal]p3 "For the overloads with no ExecutionPolicy" repeated twice

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1725]
This is already fixed in master; double-check that it's already fixed on c++17 branch.

**Comment by tkoeppe** [comment]
Confirmed, fixed by cd2cc5c4709f4b8295d71d9fed92f3f2b2393f77.

**Comment by zygoloid** [comment]
Resolution: ACCEPTED.
