### ISSUE TITLE
[C++17 DIS comment 016] Add Foreword

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1728]

**Comment by jensmaurer** [comment]
Suggestion: ACCEPT and do as they wish. (I thought they PDF-collated the Foreword in former times.)

**Comment by zygoloid** [comment]
They added the Foreword themselves for C++14, but in a way I was unhappy with; I ended up re-adding it myself. The relevant patches to apply are in the C++ Editors shared folder on google drive. (Let me know if you don't have access.)

**Comment by zygoloid** [comment]
#1746 is ready to merge.

**Comment by jensmaurer** [comment]
#1746 was closed, so presumably the secretariat told you to use their words, not yours?

**Comment by zygoloid** [comment]
I'm still waiting to find out what the correct words are. It looks like a list of changes since C++ 2014 is likely required, but it's not yet clear.

**Comment by tkoeppe** [comment]
How could one come by such a list at a moment's notice...

**Comment by jensmaurer** [comment]
@tkoeppe: http://wiki.edg.com/pub/Wg21albuquerque/SG10/sd-6.html#recs.cpp17 is probably a good start.

**Comment by cpplearner** [comment]
Or [p0636](http://wg21.link/p0636).

**Comment by zygoloid** [comment]
Fixed in 699115454d84d9ba549a50b9b2f1d6b78c887cc5.
