### ISSUE TITLE
[C++17 DIS comment 018] Hanging paragraphs

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1730]
Perhaps we should see how hard ISO pushes for this one. It's probably not too hard to script up the addition of a bunch of "General" headings if we need to, but I would worry that such a heading would be inappropriate in many cases.

**Comment by jensmaurer** [comment]
Agreed: Fixing these for real (e.g. clause [expr]) means more work than adding a bunch of trivial subsection headings. Postpone to C++20.

**Comment by zygoloid** [comment]
Response: REJECTED. We will consider this change for the next revision of the document, but adding meaningful headings for these paragraphs would require significant reorganization of the text and potentially updating of cross-references, which introduces too much risk for this stage of the standardization process.

**Comment by zygoloid** [comment]
Leaving this open for consideration post-C++17 IS.

**Comment by jensmaurer** [comment]
See also #574 and #1771.

**Comment by zygoloid** [comment]
We have addressed a lot of issues here for C++20, but there's more work to do. Retargeting at C++23.
