### ISSUE TITLE
[C++17 DIS comment 020] Use of "this International Standard"

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1732]
Suggestion: reject. We have already changed the places where "this document" does not create an ambiguity or confusion.

**Comment by tkoeppe** [comment]
Agreed.

**Comment by zygoloid** [comment]
Looks like there are still a lot of "this International Standard"s left that would be better as "this document". Proposal: use "this document" when referring to the body of text, "this International Standard" when referring to the IS in comparison to other revisions of the C++ standard or in reference to the standardization process (eg, "reserved for use by future versions of this International Standard" or "C++ 2003 did it some other way, but in this International Standard, we...").

To review: https://github.com/cplusplus/draft/pull/1748

**Comment by zygoloid** [comment]
That would make this ACCEPTED WITH MODIFICATION. "This International Standard" has been replaced by "this document" when referring to the body of text, but has been left as-is when referring to the IS in comparison to other revisions of the C++ standard, as changing those instances to "this document" would create confusion and ambiguity.

**Comment by zygoloid** [comment]
Merged, and submitted as 6218c216 in master. I think we may have reached a new low with this one, in going with a resolution that literally no-one is happy with. But hopefully ISO will not complain.
