### ISSUE TITLE
[C++17 DIS comment 021] Review all 'must's and fix as appropriate

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1733]

**Comment by jensmaurer** [comment]
Let me suggest REJECT for C++17 due to the size of the task and the induced wording churn. We should target this for C++20 with priority, though.

**Comment by tkoeppe** [comment]
I thought @hubert-reinterpretcast said this comment only applies to a small number of instances that were newly introduces between the DIS and our c++17 branch? Maybe this isn't so hard to fix then.

**Comment by hubert-reinterpretcast** [comment]
I did not make any statements with regards to this comment on the DIS ballot. In any case, the comment is on the DIS ballot, so it definitely was meant to refer to the instances that are present in the DIS.

**Comment by jensmaurer** [comment]
@tkoeppe: You seem to be confused. This is an ISO Central Secretariat comment, talking about "throughout the document".

**Comment by tkoeppe** [comment]
OK, never mind me then.

**Comment by zygoloid** [comment]
Pull request #1747 converts a few of these.

Suggested response: ACCEPTED WITH MODIFICATION. The majority of uses of "must" are either indicating logical necessity, or (when in non-normative wording) the consequence of requirements specified elsewhere in the document. Other occurrences of "must" have been corrected.
