### ISSUE TITLE
[C++17 DIS comment 023] [support.runtime] Remove index entry for __bool_true_false_are_defined

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1735]

**Comment by tkoeppe** [comment]
Agreed. `<cstdbool>` was moved to Annex D by means of Clark, and a stray index remained behind.

**Comment by zygoloid** [comment]
Proposed response: ACCEPTED

**Comment by tkoeppe** [comment]
Commit in master: https://github.com/cplusplus/draft/commit/65a7cf53d790de7e7cb91ff2b717e07cce6d70a2

**Comment by zygoloid** [comment]
Merged to c++17 as 7f0685f930bcfc9a48dc32e3eeead02ef0c8cfc7.
