### ISSUE TITLE
Wrong example of unspecified behavior in [intro.abstract]/3

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1742]
> Certain other aspects and operations of the abstract machine are described in this International Standard as unspecified (for example, evaluation of expressions in a *new-initializer* if the allocation function fails to allocate memory ([expr.new])). 

The example is no longer correct after [P0145](https://wg21.link/P0145).

**Comment by jensmaurer** [comment]
CWG 1583 changed the example to the current wording. Since it was previously updated by a core issue, I guess we shouldn't do it editorially this time. I've sent e-mail to the core reflector:
http://lists.isocpp.org/core/2017/09/2930.php

**Comment by timsong-cpp** [comment]
It looks like it would be correct to revert to the previous example, since function argument evaluations are now indeterminately sequenced, which is a form of unspecified behavior ("either A is sequenced before B or B is sequenced before A, but it is unspecified which") :)
