### ISSUE TITLE
[thread.condition.condvarany]/9 is incorrect

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1755]
> [ Note: If any of the wait functions exits via an exception, it is unspecified whether the `Lock` is held. One can use a Lock type that allows to query that, such as the unique_­lock wrapper. — end note ]

This is not correct after [LWG 2135](https://cplusplus.github.io/LWG/lwg-defects.html#2135) specified that `terminate()` is called if the function fails to meet the postcondition (the lock is held by the calling thread).

**Comment by jensmaurer** [comment]
Let's remove that note, then.
