### ISSUE TITLE
[meta.trans.other] Consider referencing p2 from the aligned_storage and aligned_union rows in Table 50

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1757]
In this case, we have a single-line normative paragraph, buried between a non-normative note and two lengthy paragraphs dealing with `common_type`, that adds a requirement to `aligned_{storage,union}`, without any hint in Table 50 that the specification of those templates in the table is incomplete. This seems suboptimal.

I'd suggest adding a cross reference in the table (make it "Note X"?). Or perhaps it'd be simpler to just add the sentence to the two rows it applies to?

**Comment by jensmaurer** [comment]
It's not clear to me that "It is implementation-defined whether any extended alignment is supported (6.11)." applies to aligned_union at all. There is no way to pass a "size_t Align" to aligned_union, and the normative statement is immediately after the example about aligned_storage. For "aligned_union", the phrasing should be "It is implementation-defined whether a type with an extended alignment is supported."

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Turn p2 sentence into a note with xref to 6.11 (where the general normative statement resides), applying to both aligned_storage and aligned_union. Also add both places to impldef index (same entry).

**Comment by jwakely** [comment]
I agree that p2 isn't clearly attached to anything, and can't apply to `aligned_union` as written.

**Comment by jensmaurer** [comment]
See [LWG 3016](https://cplusplus.github.io/LWG/issue3016).
