### ISSUE TITLE
[expr.prim.lambda.capture]p11 description of capture-by-reference of references is out of place

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1785]
[expr.prim.lambda.capture]p11 describes capture-by-reference of references. But p11 is actually giving details of capture by copy. Capture by reference is not even *introduced* until p12.

The capture-by-reference-of-reference wording and its note and example should be moved to a new p13.

**Comment by jensmaurer** [comment]
Part of the example needs to move, too.
