### ISSUE TITLE
[temp] p1 what is a family of classes?  and can they claim dependents? ;) 

### ISSUE THREAD

**Issue by faisalv** [cplusplus/draft#1787]
Why not eschew the non-technical term 'family' and deviate from the ARM in favor of something more descriptive along the lines of:
A template defines a pattern (borrowing from [temp.variadic]) for generating/instantiating an unbounded set of related classes ... etc.

not better?

**Comment by jensmaurer** [comment]
We should be aware that we're talking about a warm-up introductory sentence that just happens not to be in a note. I'd like to get a consensus on the general approach here first (see #1771) before addressing specific issues.

As a side note, I dislike "unbounded": There are templates that can only be instantiated with a single type (think `static_assert(is_same_v<T, int>)`). Also, "related": what's the relationship between two classes instantiated from the same template? These are distinct classes, after all.

So, something like "A template defines a pattern for a set of classes, functions, or variables, an alias for a set of types, or a concept." sounds workable.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Disrupting this wording in the proposed way is no match for the conceivable fall-out. No consensus for a change.
