### ISSUE TITLE
[bitmask.types] Potential undefined behavior in operator~

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#1788]
Wording relative to n4700.

[bitmask.types] specifies that a bitmask type's `operator~` can be written as
```C++
constexpr bitmask operator~(bitmask X){
  return static_cast<bitmask>(~static_cast<int_type>(X));
}
```
for
```C++
// For exposition only.
// int_type is an integral type capable of representing all values of the bitmask type.
enum bitmask : int_type {
  V 0 = 1 << 0, V 1 = 1 << 1, V 2 = 1 << 2, V 3 = 1 << 3, .....
};
```

The suggested `operator~` results in undefined behavior if `sizeof(int_type) < sizeof(int)` because `static_cast<int_type>(X)` has to be promoted to `int` before evaluating `~`, and the outter `static_cast<bitmask>` would result in undefined behavior because its operand is not within the range of the enumeration values as explained in [expr.static.cast]/10.

My suggested solution is wrapping the `~` and its operand in `static_cast<int_type>` as follows:
```C++
constexpr bitmask operator~(bitmask X){
  return static_cast<bitmask>(static_cast<int_type>(~static_cast<int_type>(X)));
}
```

Greetings,
Johel

**Comment by jensmaurer** [comment]
@zygoloid , is this editorial?

**Comment by tkoeppe** [comment]
This is basically the same issue that I reported about `std::byte` operations. I would hope that I mentioned this case in that issue, too, but I'm not sure now.

And it's definitely not editorial.

**Comment by jensmaurer** [comment]
@tkoeppe : Which LWG issue number?

**Comment by tkoeppe** [comment]
@jensmaurer: [LWG 2950](https://wg21.link/lwg2950). It looks like it's not mentioned there, though I'm sure I've brought both `byte` and *`bitmask`* up somewhere, perhaps on the reflector.

**Comment by tkoeppe** [comment]
@jensmaurer: See "std::byte operations are hard to use correctly" on the lib reflector.

**Comment by johelegp** [comment]
Even though it's part of the normative text, I had assumed that it was an editorial issue because what the text does is offer a suggestion on how to write a bitmask type. After all, it uses _can_ instead of _shall_ in the introductory line ([bitmask.types/2](http://eel.is/c++draft/bitmask.types#2)). So does the previous paragraph. If it actually meant that we can only choose among those (enumerated type, integer type, or `bitset`), and further, if it's an enumerated type it must be implemented as shown below, then `enum class` bitmask types are not contemplated.

Should I submit a defect report based on the OP?

**Comment by timsong-cpp** [comment]
[bitmask.types] is part of [description], which is labeled informative.

Also, the resolution of Core issue 2338 in P0818R0 should obviate the problem.

**Comment by tkoeppe** [comment]
Ah, *that's* where I had mentioned this problem.

**Comment by johelegp** [comment]
Ah, I lost sight of the big picture.

> Also, the resolution of Core issue 2338 in [P0818R0](https://wg21.link/P0818R0) should obviate the problem.

Does CWG has a more actively updated issues repository like LWG does? I can't find one.
