### ISSUE TITLE
rationalize library header name indexing

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1807]
Right now, we index library headers something like this:

```
\indextext{\idxhdr{<blah>}}%
\indexlibrary{\idxhdr{<blah>>}}%
```

We should provide a dedicated macro for this (perhaps `\indexhdr{blah}`). Once that's done, we should consider removing these from the index of library names, since they're not library names in the normal sense. (Maybe a separate 1-page index of library headers would be useful, though.)

**Comment by jensmaurer** [comment]
Now moving all library headers from the "index of library names" into a new index. Headers stay in the main index.
