### ISSUE TITLE
fix bnf / bnftab / bnfkeywordtab mess

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1821]
We currently have mutliple "bnf" environments:

* `bnf` is used for most normal grammar snippets. It does not support `\>` for indenting wrapped continuation lines.
* `bnftab` is used for some grammar snippets. Upside: it supports `\>` for indenting continuation lines. Downside: it does not automatically indent the body of a grammar definition. Each line must be prefixed with `\>`.
* `bnfkeywordtab` is used for "keyword" lists in the grammar. Actually, it's only used for lists of operators (one in [lex], one in [over]), since our lists of keywords are in tables not in the grammar at all.

You would think that we would use `bnftab` when we need to wrap a line, and `bnf` otherwise. But actually, we use `bnftab` for the grammar in [lex] (some of which is wrapped) and for non-grammar snippets such as the rewrite rules in [stmt], and we use `bnf` for the rest of the grammar, including cases that need line wraps (where the wrapping is constructed manually using `\hspace*`).

This is a mess. We should make `\>` work in `bnf` environments, and remove `bnftab`. We should also consider renaming `bnfkeywordtab` since it's not actually used for keywords (the only difference between it and `bnftab` is that text is by default in teletype rather than in italics).

**Comment by jensmaurer** [comment]
There's also `ncsimplebnf` for "of the form" grammar quotes. Those should probably stay as-is.

**Comment by tkoeppe** [comment]
@jensmaurer: That's the "**n**on-**c**opying" version that doesn't get extracted into the grammar summary.

**Comment by jensmaurer** [comment]
@tkoeppe: Sure, but why do we sometimes use `ncsimplebnf` and sometimes `ncbnftab` for quoted grammar snippets?

**Comment by jensmaurer** [comment]
Ok, I have a bnf environment where \> works to indent at the beginning of a line (for wrapped continuations). However, [cpp] also contains \> inside a bnftab for tabbing within a grammar production (see _control-line_). In general, enumerations (= automatic indent) and tabbing don't mix well.
@zygoloid: Are we keeping the aligned presentation of the grammar productions in [cpp], or are they considered an oddity that can go?

**Comment by jensmaurer** [comment]
It seems the "tabto" package does what I want, even inside enumerations; see https://tex.stackexchange.com/questions/15628/ . Before I go there (and introduce yet another package dependency), @zygoloid should advise whether we want to keep the aligned grammar presentation in [cpp]. If yes, I'll go for the extra package; if no, I'll remove `\>` in the middle of a grammar production in [cpp].

**Comment by zygoloid** [comment]
Here's what [cpp] looks like without the `bnftab`:

<img width="356" alt="screen shot 2018-03-17 at 8 43 58 pm" src="https://user-images.githubusercontent.com/232783/37561392-01fcfb0a-2a24-11e8-906d-0ca78bc1a6fa.png">

That seems fine to me. Other opinions solicited (@tkoeppe?)

**Comment by jensmaurer** [comment]
@tkoeppe: What's your opinion?

**Comment by tkoeppe** [comment]
Is [cpp] the only instance where we have additional alignment apart from the first one? If so, I think that can go. I'd be happy to lose the entire set of macros related to tabbing. It might be nice to see the impact of such a change on [lex], where we mix the two kinds of grammar environments.

**Comment by tkoeppe** [comment]
It looks like we can replace `ncbnftab` environments with `ncsimplebnf` environments in several cases.

**Comment by tkoeppe** [comment]
In [stmt] we use bnftab environments to indent and then exdent again. The plain "bnf" environment can't do that, since it indents all lines but the first, and simplebnf doesn't come with any indentation tools at all (I think).

**Comment by tkoeppe** [comment]
...but I can trivially provide such an indentation aid :-)

**Comment by tkoeppe** [comment]
I got rid of all bnftabs except the ones in [cpp]. We just need to decide whether we're OK with dropping the alignment.

**Comment by tkoeppe** [comment]
Removed raw `\hspace`s  in 6b700d63929a1d8bffd37d174e065b2e6afcb487.

**Comment by tkoeppe** [comment]
No more uses of `bnfkeywordtab` as of 15412326fc0df176b4ef4481fcd0e4a3978c7b86 and parent.

**Comment by tkoeppe** [comment]
I sidestepped the discussion around [cpp] by aligning the grammar with spaces (rather than tabbing) in 7f84786ce51d5ba3c91e4fce1c7b5db835ef7136.

**Comment by tkoeppe** [comment]
Fixed by e964cd7491419a3628d9ee8bf0fb49d9f64883f9.
