### ISSUE TITLE
[dcl.enum] Duplicate sentences about redeclarations

### ISSUE THREAD

**Issue by BRevzin** [cplusplus/draft#1826]
[\[dcl.enum\]/4](http://eel.is/c++draft/dcl.enum#4.sentence-1):

> If the enum-key is followed by a nested-name-specifier, the enum-specifier shall refer to an enumeration that was previously declared directly in the class or namespace to which the nested-name-specifier refers (i.e., neither inherited nor introduced by a using-declaration), and the enum-specifier shall appear in a namespace enclosing the previous declaration.

Is mostly repeated in [\[dcl.enum\]/12](http://eel.is/c++draft/dcl.enum#12.sentence-1):

> If an enum-head contains a nested-name-specifier, the enum-specifier shall refer to an enumeration that was previously declared directly in the class or namespace to which the nested-name-specifier refers, or in an element of the inline namespace set ([namespace.def]) of that namespace (i.e., not merely inherited or introduced by a using-declaration), and the enum-specifier shall appear in a namespace enclosing the previous declaration.

One of these was probably intended to replace the other. I don't know which.

**Comment by jensmaurer** [comment]
I don't know what happened here, but it seems p12 should go, except that the "inline namespace set" must be integrated into p4.

**Comment by cpplearner** [comment]
[dcl.enum]/12 was added by CWG 2156.
