### ISSUE TITLE
Does [basic.life] have the wrong cross-reference?

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1841]
> Otherwise, such a pointer refers to allocated storage (6.6.4.4.2), 

>  Otherwise, such a glvalue refers to allocated storage (6.6.4.4.2),

This links to [basic.stc.dynamic.deallocation] which only mentions "storage" once, in "the deallocation function shall deallocate the storage referenced by the pointer".

Is it supposed to be [basic.stc.dynamic.**allocation**] instead, which has lots to say about "allocated storage"?

This bad cross-reference was copied by [N3916](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3916.pdf#page=16) (see the note to the editor on page 16) and so appears in three more places.

**Comment by jensmaurer** [comment]
Agreed.
