### ISSUE TITLE
GB-6: [category.ctype] Formatting of exposition-only members

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#185]
N3733 GB-6 says:

> 17.5.2.3 [objects.within.classes] defines the use of "exposition only" in the library:
> The declarations for such member objects and the definitions of related member types are followed by a comment that ends with exposition only,
> 22.4.1 [category.ctype] has members which are preceded (not followed) by a comment ending "exposition only".
> and 28.12.1 [re.regiter] and 28.12.2 [re.tokiter]

It goes on to propose:

> Reformat to follow 17.25.2.3

**Comment by jensmaurer** [comment]
22.4.1 has been fixed with an explicit comment. I can't find exposition-only values in [re.regiter] or [re.tokiter].

**Comment by jwakely** [comment]
The problems in [re.regiter] and [re.tokiter] were fixed by f4fb66c58df078366beb9823c1ef3e8cf7877574
