### ISSUE TITLE
Consider removing [facets.examples]

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1852]
In #781, @jensmaurer expressed serious doubts that [[facets.examples]](http://eel.is/c++draft/facets.examples) should exist in the standard. I have such doubts as well. Anyone else?

(In addition, the remaining \pnums in examples are an annoyance for cxxdraft-htmlgen.)

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Remove [facets.examples] entirely.
