### ISSUE TITLE
missing xrefdelta updates for recent reorganization work

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1854]
Some of the recent reorganizational changes (particularly removing excessive subclause structure) has missed the corresponding changes to xrefdelta indicating where the wording has gone.

**Comment by jensmaurer** [comment]
@zygoloid: Do you have specific pointers?
Both the [array] and [util.smartptr] modifications have their xrefdelta entries, as do my proposed reverse_iterator changes.

**Comment by tkoeppe** [comment]
I don't know the answer, but an easy way to find out is to compare the xref data file from before and after and see if anything went away.

**Comment by jensmaurer** [comment]
The list of all labels can be produced using:
`sed '/glossaryentry/s/^\\glossaryentry{\([^@]*\)@.*$/\1/' xrefindex.glo  | sort`

Doing this on the "c++17" branch yields (for future reference):
[glo-17.txt.gz](https://github.com/cplusplus/draft/files/1511838/glo-17.txt.gz)

Comparing against HEAD shows a single missed update, which is the deprecation of [util.smartptr.shared.atomic].
