### ISSUE TITLE
basic_string_view begins_with has an incorrect reference implementation

### ISSUE THREAD

**Issue by cscrimge** [cplusplus/draft#1870]
```
constexpr bool starts_with(basic_string_view x) const noexcept;
    Effects: Equivalent to: return compare(0, npos, x) == 0;
```

`compare(0, npos, x)` should be: `compare(0, x.size(), x)`

Otherwise `"Hello World"sv.starts_with("Hello"sv)` would return `false`.

**Comment by jwakely** [comment]
This is not an [editorial issue](https://github.com/cplusplus/draft/wiki/How-to-tell-if-an-issue-is-editorial), so needs to be [submitted as a defect report](https://cplusplus.github.io/LWG/lwg-active.html#submit_issue).

I'm pretty sure @mclow already noticed this problem, and might have opened an issue already.

**Comment by mclow** [comment]
I have written up the issue, but haven't added to the issues list. That will happen by Monday. 

BTW, your proposed resolution is incorrect, because in the case `"Hello"sv.starts_with("Hello World"sv)` you would have undefined behavior.

**Comment by cscrimge** [comment]
You are right. I was assuming that `substr(0, n)` would clamp to `size()`, which is true for `basic_string` but not `basic_string_view`.

So the proposed resolution should be `return (size() >= x.size()) && (compare(0, x.size(), x) == 0)`.

**Comment by mclow** [comment]
Which is exactly the proposed resolution in my LWG issue, and in my patch for libc++: https://reviews.llvm.org/D40586

**Comment by mclow** [comment]
https://cplusplus.github.io/LWG/issue3040
