### ISSUE TITLE
[string.cons] Editorial change for caption on table 56

### ISSUE THREAD

**Issue by mclow** [cplusplus/draft#1875]
LWG closed issue [3033](https://wg21.link/LWG3033) as "NAD editorial", with a suggestion that changing the caption on the table would be both editorial and sufficient.

The current caption is "`basic_string(const basic_string&)` effects"

My first suggestion is: "`basic_string(const basic_string&)` and `basic_string(const basic_string&&)` effects", but I'm not going to insist on that.

The discussion occurred on the -lib reflector in the thread titled "Issue 3033: basic_string move ctor is underspecified"

**Comment by tkoeppe** [comment]
Can I make a counter-proposal to just remove the tables outright and replace them with standard *Postconditions* elements? @zygoloid, would you support that?

**Comment by tkoeppe** [comment]
Proposal:

![image](https://user-images.githubusercontent.com/6378233/33529615-270162fc-d86b-11e7-8dd7-8370292e46b2.png)

**Comment by jensmaurer** [comment]
Those constructor postcondition tables are odd, and telling the reader the state of three data members doesn't seem overly obtuse to warrant separate tables.

**Comment by tkoeppe** [comment]
I believe at some point in the past there was *one* table that was shared between two `\itemdesc`s. However, I merged those two separate items into one a few months ago, and now we have literally one table per item. So I think the time has come for those tables to pass on to a better place.
