### ISSUE TITLE
[everywhere] Remove paragraph breaks in the middle of sentences

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#1899]
For example, consider this sentence that spans multiple paragraphs: https://github.com/cplusplus/draft/blob/master/source/basic.tex#L631

The reason I care about this is that cxxdraft-htmlgen supports linking to individual sentences (which has proved to be a popular feature), but it can't do this properly for sentences that span multiple paragraphs.

So to get links like http://eel.is/c++draft/basic.scope.declarative#2.sentence-1 to correctly select the whole sentence, I currently use a [sloppy incomplete patch](https://github.com/Eelis/draft/commit/5842bfa4399f786c731ab4cd69cb007ce56e262e) that removes tons of these inappropriate paragraph breaks. I could clean that patch up, make it more complete, and submit it, if this issue is deemed worthy of fixing.

I vaguely recall that @tkoeppe was already planning something along these lines a while ago, but I can't find an existing ticket.

**Comment by tkoeppe** [comment]
Well, my goal was to make it possible to remove those breaks, but to actually make edits to remove the breaks would be a lot of work, and there are edge cases where the additional break improves line breaking, weirdly. (Though perhaps this has changed with @jensmaurer's improved widow/club code.)

I'd certainly entertain patches that do nothing but break removal and cause no visual diffs.

**Comment by jensmaurer** [comment]
Just to clarify, the issue is the empty line for cases like the following:
```
In
(empty)
\begin{codeblock}
int j = 24;
[...]
```
Because from a LaTeX perspective, there is no difference with and without the empty line (a codeblock is a vertical environment, so the previous LaTeX paragraph ends anyway).

There might actually be an argument for source code readability to keep the empty line.
@zygoloid , any opinion here?

**Comment by tkoeppe** [comment]
As a long-term user of LaTeX, it's precisely the readability aspect that makes me want to *get rid* of the double line breaks. Double line breaks read as "paragraph break", so they're very confusing.

**Comment by Eelis** [comment]
I noticed that removing an empty line between text and a codeblock changes the layout of the text. For example, removing [this empty line](https://github.com/cplusplus/draft/blob/616405fb021f33841280407e95a7a44e1183a719/source/lex.tex#L1858) results in the following change:

![diff](https://user-images.githubusercontent.com/22357/35414384-9c2a6ad4-0222-11e8-9cd3-57cb2b71978a.png)

(If you don't see it, look at the right side.)

Since empty lines like these are currently used erratically around codeblocks, this means the layout in the PDF is currently inconsistent. So fixing this issue will entail visual diffs (fixing the inconsistencies).

**Comment by Eelis** [comment]
Enough inappropriate paragraphs have been fixed to satisfy me. :) Closing.
