### ISSUE TITLE
[temp.local]/3 Wrong example?

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1900]
```c++
template<class T, template<class> class U = T::template Base> struct Third { };
Third<Base<int> > t;                    // OK: default argument uses injected-class-name as a template
```
With `T::template Base`, lookup for `Base` in the scope of `T` aka `Base<int>` finds the injected-class-name, and this lookup does not ignore function names, so per [CWG 1310](https://wg21.link/CWG1310) it should be considered to name the constructor of `Base`, making the code ill-formed.

If this analysis is correct, perhaps the example can be changed to
```c++
template<class T, template<class> class U = T::template Base> struct Third { };
Third<Derived<int> > t;                    // OK: default argument uses injected-class-name as a template
Third<Base<int> > t;                       // Error: injected-class-name in default argument names the constructor of Base ([class.qual])
```

**Comment by jensmaurer** [comment]
MSVC rejects. ICC with different error messages. clang accepts with a warning.
Problem is `T::template Base` is a constructor name, even with intervening "template".
Editorial meeting consensus: Replace "Base" with "Derived", don't add a second line.
