### ISSUE TITLE
[over.match.ctor] Initialization by "()" neither is copy-initialization nor direct-initialization. 

### ISSUE THREAD

**Issue by RealLitb** [cplusplus/draft#1911]
Over.match.ctor says 

"When objects of class type are direct-initialized, copy-initialized from an expression of the same or a derived class type ([dcl.init]), or default-initialized, overload resolution selects the constructor. For direct-initialization or default-initialization that is not in the context of copy-initialization, the candidate functions are all the constructors of the class of the object being initialized. For copy-initialization, the candidate functions are all the converting constructors of that class. "

The last sentence should consider the remaining default initialization cases aswell that happened in the context of copy(-list)-initializatizion. Suggested edit:

"For copy-initialization and the remaining default-initialization cases, the candidate functions are all the converting constructors of that class."

Note that initialization by "()" is not copy-initializaton (neither is it direct initialization), so this change is normatively relevant. However, I think the current intent is sufficiently clear so this could be handled editorially.

**Comment by cpplearner** [comment]
>initialization by "()"

(When) is it not covered by [\[dcl.init\]/16](http://eel.is/c++draft/dcl.init#16)?

> The initialization that occurs in the forms
>
>     T x(a);
>     T x{a};
>
> as well as in new expressions, static_­cast expressions, functional notation type conversions, mem-initializers, and the braced-init-list form of a condition is called _direct-initialization_.

**Comment by RealLitb** [comment]
Because "(a)" is different from "()". That's how I read it, even though I wish it was clearer. 

But, if it was covered by that, then "For direct-initialization or default-initialization that is not in the context of copy-initialization ..." could be simplified to "For direct-initialization ..." straight away. And we could always use explicit constructors in the context of copy-list-initializations. Which seems... odd and against the intentions.

**Comment by cpplearner** [comment]
I mean, can the initializer "()" appear outside of new expressions, functional notation type conversions, or mem-initializers?

**Comment by RealLitb** [comment]
"T x()" can happen if a variadic template instantiates it from "T x(args...);". It also appears in this context:

   struct T { explicit T() { } };
   T t = {};

Here, we are told by list-initialization clauses, to value-initialize "t". And that means to default-initialize "t". And that means to consider over.match.ctor with an initializer "()". This initializer doesn't appear in code, but merely needed for the conditional verbiage in over.match.ctor. 

Ok, now that you mention new-expressions, functional notation type conversions etc, I can see why it's deeply confusing. Yes, I agree, I think in some cases "()" is considered direct initialization, and in other cases, like my above examples, it is not.

**Comment by timsong-cpp** [comment]
And we use \grammarterm for "the _initializer_ `()`" in the description of default-initialization, but `()` doesn't match the _initializer_ production at all.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: First issue, fixed by "For copy-initialization (including default initialization in the context of copy-initialization), the candidate functions are all the converting constructors of that class."
11.6p16 morph to bulleted list; fix "of the form" declaration-lookalikes to instead inspect grammar non-terminals.
