### ISSUE TITLE
[conv,class] Clause reorganization in core sections

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1919]
Following up on #1771, here's a specific suggestion at reorganization:

- Move [conv] as a subclause into [expr], immediately before [expr.arith.conv].
- Move [class.derived], [class.access], and [special] as subclauses into [class]: [class.access] as a subclause of [class.mem]; the rest immediately nested into [class].
- After the above, move [class.init] immediately nested into [class]. Same for [class.temporary]. Neither have anything to do with "special member functions" per se.
- (avoid hanging paragraphs:) Rename [class.name] to "Class declarations" and move [class]p1-3,5,11 there, at the top. Introduce [class.prop] "Class properties" and move [class]p4,6-10 there.

**Comment by jensmaurer** [comment]
@tkoeppe, @zygoloid: opinions?

**Comment by jensmaurer** [comment]
Editorial meeting consensus: First change agreed. Second change: ctors/dtors/conversions etc. talk about members and go to [class.mem]. Initializations, construction/destruction go into [class]. [class.temporary] goes to [basic] (same level as full-expression). Copying/moving and comparisons under [class]. Leave front matter of "special member functions" without subclauses, under [class.mem].
Maybe separate conversion functions (how to declare) from the "conversions" section.
Consider merging declarations and declarators. Move up [namespace.udecl] under "declarations".

**Comment by jensmaurer** [comment]
[time] should be a top-level clause "Time and date library".

**Comment by tkoeppe** [comment]
What about filesystem? If [time] qualifies, probably [fs] does too.

**Comment by jensmaurer** [comment]
@tkoeppe: [filesystems] is 46 pages. That would be a candidate, but it does also fit under [input.output].
Whereas [utilities] became a dump-everything-here location.

I think we should strive to keep the number of (sub)section reasonable at every level of the hierarchy. The top level is already large, at 33 clauses, but the suggestions above (reducing the core language footprint) will gain us 4 or 5 clauses.
And I would actually consider putting [re] under [strings], both talk about strings (in the sense of character sequences and the operations performed on them).

Napkin math: 1500 pages / 20 top-level clauses = 75 pages per top-level clause.
40 pages is way below that and needs reasoning why it's at the top level.

**Comment by jensmaurer** [comment]
Additional ideas with some support: Move [re] under [strings], move [localization] under [input.output].

**Comment by AlisdairM** [comment]
For C++17, there was tentative agreement to move [numeric.ops] under [algorithm], after we had published the final standard (i.e., make the change for C++20).  I had been trying to put together a PR for such a change after the post-meeting mailing, but this seems to be the right place to have that conversation too.

**Comment by AlisdairM** [comment]
Indeed, this was issue https://github.com/cplusplus/draft/issues/1511

**Comment by jensmaurer** [comment]
[P1076R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1076r0.html) presents the planned sectioning changes and asks for feedback from LWG and CWG.

**Comment by jensmaurer** [comment]
Most recent update of P1076 is at [D1076R1](http://wiki.edg.com/pub/Wg21rapperswil2018/Documents/d1076r1.html).
