### ISSUE TITLE
std::hash<> could have a clearer index entry

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#192]
Given that there are many specializations of std::hash<>, the index should clearly point to [unord.hash] for the general description.

**Comment by tkoeppe** [comment]
@AlisdairM: Could you please check if this is still a problem?

**Comment by jensmaurer** [comment]
The index entry for the library name "hash" now points to the right place.

In order to address the other concern, I'll add a "synopsis" subsection for <functional> and add a cross-reference to it.
