### ISSUE TITLE
[using.linkage] Fix reference to section of C standard in footnote

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#194]
From LWG Issue 2281:

Edit footnote 182, 17.6.2.3 [using.linkage] as indicated:

> The only reliable way to declare an object or function signature from the Standard C library is by including the header that declares it, notwithstanding the latitude granted in <del>7.1.7</del><ins>7.1.4</ins> of the C Standard.

**Comment by AlisdairM** [comment]
The current draft has the suggested 7.1.4 cross-reference, so this issue can be safely closed.
