### ISSUE TITLE
[ios.base] has too many variables called "index"

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#1955]
The synopsis shows an exposition-only static data member called `index` but the same name is used for the parameters of `iword`, `pword`, `register_callback`, and redundantly in the `event_callback` alias declaration.

Then [ios.base.locales] uses `index`, presumably not referring to the static data member. [ios.base.storage] uses it to refer to the static data member in the definition of `xalloc`. The definitions of `iword` and `pword` use `idx`, which is inconsistent with the synopsis, but avoids confusion. [ios.base.callback] uses `index` as a function parameter again, and finally [ios.base.cons] uses it, again not referring to the static data member.

**Comment by jwakely** [comment]
The uses of `index` in [ios.base.locales] and [ios.base.cons] refer to a function parameter _of a completely different function_, even though that name isn't in scope there, and the static data member `index` is in scope. How lovely.

**Comment by timsong-cpp** [comment]
I'd read those uses as declaration of a "local variable" a la 
`for(auto [fn, index] : registered-pairs) { ... }`. Who knew that C++98 had structured bindings? :)
