### ISSUE TITLE
[intro.refs] add normative reference on ISO 8601

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#1971]
ISO 8601 is cited normatively from the <chrono> calendar extensions. We should add a matching normative reference.

**Comment by tkoeppe** [comment]
@hubert-reinterpretcast: Another standard for users to buy if they want transitive closure.

**Comment by jensmaurer** [comment]
@tkoeppe: For just 138 CHF: https://www.iso.org/standard/40874.html
(This is just 33 pages. C++17 has 1605 pages, yet costs only 198 CHF: https://www.iso.org/standard/68564.html . Apparently, C++ has much less net worth than date/time representations.)

**Comment by hubert-reinterpretcast** [comment]
@tkoeppe: I think it is the same amount of normative reference as is already present for `strftime`.
