### ISSUE TITLE
[namespace.udecl]p16 references nonexistent "implicit this parameter"

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#1975]
> In particular, the implicit `this` parameter shall be treated as if it were a pointer to the derived class rather than to the base class.

The name is "implicit object parameter", not "implicit `this` parameter", and it's a reference, not a pointer. See [over.match.funcs]p4. There also appears to be some normative duplication and contradiction between these two paragraphs as [namespace.udecl]p16 contains no exception for conversion functions.

**Comment by jensmaurer** [comment]
We should turn the entire paragraph into a note; there's nothing said here that isn't also said elsewhere.
