### ISSUE TITLE
reverse_iterator synopsis includes associated functions in two places

### ISSUE THREAD

**Issue by jyasskin** [cplusplus/draft#199]
[reverse.iterator] includes a set of comparison and arithmetic operators below the definition of class reverse_iterator, but that list was already below the class declaration in [iterator.synopsis]. I don't know where the list should be, but I don't think it should be twice.

**Comment by jensmaurer** [comment]
Jeffrey, I'm closing this with the provided explanation. Please re-open if you feel otherwise.
