### ISSUE TITLE
Rename [cmp.syn] to [compare.syn]

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1991]
along the reasoning in #1958.

**Comment by W-E-Brown** [comment]
> On Mar 27, 2018, at 4:21 AM, Jens Maurer <notifications@github.com> wrote:
> 
> along the reasoning in #1958.

Sorry, but I respectfully disagree with that reasoning, both in this specific case and in general.

If a clause has a stable tag of the form [X], it seems entirely reasonable to me that each of its subclauses have a stable tag of the form [X.Y].  

I am therefore not in favor of making even well-intentioned changes to this scheme.  Instead, I would favor going the other way:  finding any stable tags that do not adhere to the described scheme and making them conform to it.

But I also am sympathetic to the widely-held view that stable tags should be, well, stable unless there are truly compelling reasons for a change.  Let's please not touch tags without significant need.

**Comment by jensmaurer** [comment]
@W-E-Brown, thanks for your comment. I have added references to the respective pull requests #1960 and #1993.

**Comment by jensmaurer** [comment]
I'd like to point out that [cmp.syn] in particular was added as late as November 2017, so I view the "stable" argument carrying less weight.

**Comment by tkoeppe** [comment]
@W-E-Brown: The problem with this "nesting" approach is that it's brittle and unmaintainable. We have moved sections and synopses around in the past, or introduced "ill-fitting" headers like `<cstddef>`, and nesting can sometimes not be achieved or maintained. So I'd hesitate to demand that.

By contrast, *header-name*.syn seems to be reasonably easy to understand and maintain, and it's trivially as stable as the header name itself.

**Comment by zygoloid** [comment]
We are not going to rename existing stable labels to conform to the [header-name.syn] pattern, but [cmp.syn] is brand-new, so renaming that one is much lower-cost, and we're going to do that.

**Comment by jensmaurer** [comment]
See #1958 for more explanation.
