### ISSUE TITLE
[stmt.while] no rewrite rule for non-variable condition case

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2008]
In [stmt.while], we say:

> A `while` statement whose *condition* is an initialized declaration of some variable `t` is equivalent to
> ```
> label:
> {
>   condition ;
>   if (t) {
>     statement
>     goto label;
>   }
> }
> ```

But fail to give any rewrite rule for the other kind of `while` statement. The result is both redundant and underspecified.

We could replace this with:

> A `while` statement is equivalent to
> ```
> label:
> if (condition) {
>   statement
>   goto label;
> }
> ```

... and make the wording simpler, less redundant, and more complete.

(Open question: is it useful to retain the braces around the outside of the if-statement in order to make it obvious that an `else` cannot bind to a `while`?)

**Comment by tkoeppe** [comment]
Yes on both counts -- the simplification seems obvious in retrospect, and keeping the "else" part clear is valuable (especially given the notorious absence of a "while-else" construct in C++).
