### ISSUE TITLE
unify capitalization of node_handle and INSERT_RETURN_TYPE

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2014]
We render the placeholder type *`INSERT_RETURN_TYPE`* in uppercase italics but render the placeholder type *`node_handle`* in lowercase italics. Likewise, we render the exposition-only name *`signal-handler`* in lowercase italics but *`INVOKE`* in uppercase italics.

We should establish a convention here, and if there is a reason for the difference in capitalization, it should be documented somewhere.

**Comment by jensmaurer** [comment]
Why is _node_handle_ a large-scale placeholder anyway? All other type requirements are phrased as tables (ok, also sub-optimal) instead of showing a pseudo class synopsis.

**Comment by tkoeppe** [comment]
In my understanding, "node_handle" is an exposition-only class, but it's still an actual class, hence class name capitalization. By contrast, the capital-italics *`INSERT_RETURN_TYPE`* is a placeholder for something that we fill in later (like *`EXPLICIT`*).

So it's exposition-only vs placeholders. I think that's not too bad.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Use lowercase italics teletype with hyphens, not underscores, for exposition-only types (cf. signal-handler) to clarify they are not standard-blessed names. (This is unclear for node_handle.) Apply this convention to all exposition-only types where a C++-level definition is shown in the standard such as INSERT_RETURN_TYPE or CALL_WRAPPER.

**Comment by zygoloid** [comment]
Retain all-uppercase italic teletype for INVOKE and GENERALIZED_NONCOMMUTATIVE_SUM, which are sort-of macros at the standard level, and don't directly represent source constructs.

**Comment by jwakely** [comment]
`node_handle` is definitely not a standard-blessed name, so using _`node-handle`_ for that makes sense.
