### ISSUE TITLE
[numarray] Wildly inconsistent formatting for valarray helpers

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#2023]
There are a number of apparently unnecessary inconsistencies between [template.slice.array.overview], [template.gslice.array.overview], [template.mask.array.overview], and [template.indirect.array.overview].

[template.slice.array.overview] p1 says:

>  The `slice_array` template is a helper template used by the `slice` subscript operator

    slice_array<T> valarray<T>::operator[](slice);

And [template.gslice.array.overview] p1 says:

> This template is a helper template used by the `slice` subscript operator
 
    gslice_array<T> valarray<T>::operator[](const gslice&);

Either the latter should say "`gslice` subscript operator" or the word `slice` should not be in code font (which would be consistent with "mask subscript operator" and "indirect subscript operator" in  [template.mask.array.overview] and  [template.indirect.array.overview] respectively).

Also [template.slice.array.overview] p1 says "The `slice_array` template is a helper template" but the other three helpers say "This template is a helper template". Presumably they could be consistent.

The "It has reference semantics ..." wording is part of p1 in [template.slice.array.overview] but is a separate paragraph p2 in the other three places.

The explanation of the effects ("the expression ... has the effect of ...") is an _Example:_ in [template.slice.array.overview], its own paragraph in [template.gslice.array.overview], and part of p2 in [template.mask.array.overview] and [template.indirect.array.overview].

**Comment by jwakely** [comment]
Some of those paragraphs were also incorrectly indented, but I've fixed that in c9e60abd503039d881f2d56eb0d10ed4cd555566

**Comment by GabrielDosReis** [comment]
> This template is a helper template used by the `slice` subscript operator

It should be `gslice`.

**Comment by jwakely** [comment]
Thanks!

**Comment by jensmaurer** [comment]
So, we're actually repairing valarray wording? Shocking.

**Comment by jwakely** [comment]
Does anybody except me care about the other inconsistencies?

Also [template.slice.array.overview] p1 says "The slice_array template is a helper template" but the other three helpers say "This template is a helper template". Presumably they could be consistent.

The "It has reference semantics ..." wording is part of p1 in [template.slice.array.overview] but is a separate paragraph p2 in the other three places.

The explanation of the effects ("the expression ... has the effect of ...") is an Example: in [template.slice.array.overview], its own paragraph in [template.gslice.array.overview], and part of p2 in [template.mask.array.overview] and [template.indirect.array.overview].

**Comment by jwakely** [comment]
I can send a pull request if we agree which presentation to use.

**Comment by jensmaurer** [comment]
@jwakely: "The "It has reference semantics ..." wording is part of p1 in [template.slice.array.overview] but is a separate paragraph p2 in the other three places." This has been addressed in the patch; it's p2 as well, now.

"The explanation of the effects ("the expression ... has the effect of ...") is an Example: in [template.slice.array.overview]," Addressing this would mean adding normative wording to an underspecified facility -> LWG issue, I'd say.

I agree with merging p3 in [template.gslice.array.overview] with its preceding paragraph for consistency.
