### ISSUE TITLE
Add names for the mutex requirements

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#203]
In particular, `Mutex`, `TimedMutex`, `SharedMutex`. There was a request that we don't, in fact, name the basic requirement `Mutex` so that it is easier to search for.

See also #202.

**Comment by jensmaurer** [comment]
See #202. The mutex requirements are now referenced using the obvious prose names. There's no obvious non-confusing alternative for "mutex requirements", so I left it at that. Specific suggestions welcome.
