### ISSUE TITLE
Mixed use of \ldots and \dotsc

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2032]
Those seem to be used in approximately the same context of comma-separated lists, so we should find out what the differences are and harmonize on one.
Also update the style guide.

**Comment by tkoeppe** [comment]
Please research first each macro's purpose. I believe that the \dotsX macros are for math mode, whereas \ldots works in text mode. The horizontal spacing is different in the different modes, so both macros may be appropriate in their respective contexts.

**Comment by tkoeppe** [comment]
OK - looks like we can use either, then. That said, I like keeping `\dotsc` in math mode because it's nice and self-documenting (but maybe that's just because I used to typeset a lot of maths). I'd be happy to use Ams-dots in math mode and "raw" dots in text mode.
