### ISSUE TITLE
The Note in [over.oper]/1 requires a change

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#2038]
[[over.oper]/1](http://eel.is/c++draft/over.oper#1)

[ Note: The **last two** operators are function call (8.5.1.2) and subscripting (8.5.1.1). The operators new[],
delete[], (), and [] are formed from more than one token. —end note ]

The words **last two** above are obviously wrong.

**Comment by jensmaurer** [comment]
I think this sentence in the note can go entirely; it's well enough covered by [over.call] and [over.sub].
