### ISSUE TITLE
[dcl.array]/8 does not take into account array xvalues

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#2049]
http://eel.is/c++draft/dcl.array#8.sentence-1 says:
> Except where it has been declared for a class ([over.sub]), the subscript operator [] is interpreted in such a way that E1[E2] is identical to *((E1)+(E2)) ([expr.sub]).

Well, currently E1[E2] is not always identical to *((E1)+(E2)) valuecategorywise.

Also, can we call subscripting commutative (eel.is/c++draft/dcl.array#8.sentence-3), if in E1[E2], [The expression E1 is sequenced before the expression E2.](http://eel.is/c++draft/expr.sub#1.sentence-6)?

**Comment by jensmaurer** [comment]
... and sequencing-wise.

**Comment by languagelawyer** [comment]
> ... and sequencing-wise.
I have edited the message 2 seconds before this...
