### ISSUE TITLE
Weird special characters

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#205]
N3690 2.3 [lex.charset]/1 has a good caret but a bad tilde. The offending LaTeX is:
_ { } [ ] # ( ) < > % : ; . ? \* + - / ^ & | @$\sim$@ ! = , @\textbackslash@ " '
so all occurrences of @$\sim$@ should be inspected.

2.13 [lex.operators] has a bad caret but a good tilde. The offending LaTeX is:
>\+ >\- >\* >/ >\% >^{} >& >| >\tilde\br
PDF search indicates that there are 25 occurrences of this.

20.10.7 [bitwise.operations]/5 has a bad tilde. The offending LaTeX is:
\tcode{operator()} returns \tcode{~{}x}.
This appears elsewhere (e.g. /9).

**Comment by jensmaurer** [comment]
This seems to be fixed.

**Comment by StephanTLavavej** [comment]
I confirm that [lex.charset] and [bitwise.operations] are fixed.

However, [lex.operators] is unfixed. The `^` and `^=` have weird carets. By weird/bad, I meant "doesn't copy into a plain text editor normally" (at least on Windows). Please consider reactivating this.

**Comment by tkoeppe** [comment]
I think you need to replace

    \^

with

    \char`\^

However, since this appears in a few more places than the one listing mentioned here, we should probably create a macro for this and apply that consistently.

**Comment by jwakely** [comment]
FWIW the "bad" one is U+02C6 rather than U+005E

**Comment by tkoeppe** [comment]
Let's reopen this for now so we don't forget. Patches welcome.

**Comment by StephanTLavavej** [comment]
Thank you! As someone whose job is copy-pasting from the Standard, I really appreciate this fix.

**Comment by tkoeppe** [comment]
No problem, thanks for calling out the problem! And thanks to Jens for implementing the solution!
