### ISSUE TITLE
[expr.ref]/2 

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#2051]
[[expr.ref]/2](http://eel.is/c++draft/expr.ref#2) 

> For the first option (dot) the first expression shall be a glvalue having class type.   **. . .**

We should replace the "glvalue having class type" above by "glvalue or prvalue having class type", otherwise the snippet below would be invalid.

```
struct A{ int a; };
int&& r = A().a;
```

**Comment by tkoeppe** [comment]
No, prvalues aren't materialized objects. We really do want a glvalue here, and that will necessitate materialization [conv.rval].

**Comment by jabelloc** [comment]
> No, prvalues aren't materialized objects. We really do want a glvalue here, and that will necessitate materialization [conv.rval].

That doesn't make any sense to me
