### ISSUE TITLE
[over.match.copy]: "return lvalues or xvalues" makes me uncomfortable

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#2053]
**UPD**:  [over.match.copy] and [over.match.conv]

The sections [over.match.copy] and [over.match.conv] have statements like: "Conversion functions that return “reference to X” return lvalues or xvalues ..."

[diff.expr]/4 is also broken: "C++ is an object-oriented language, placing relatively more emphasis on lvalues. For example, functions may return lvalues."

"return _value category_" sounds illiterate for me.

Proposed wording:

```
The result of calling a
conversion function that returns ``reference to
\tcode{X}''
is
lvalue or xvalue, depending on the type of reference, of type
\tcode{X}
and is therefore considered to yield
\tcode{X}
for this
process of selecting candidate functions.
```

**Comment by zygoloid** [comment]
"Result" is defined as the value/object returned by the function call, so I don't think that's quite right. We want to say that the call expression is an lvalue or xvalue. Maybe:

> A call to a conversion function returning "reference to `X`" is a glvalue of type `X`, and such a conversion function is therefore considered to yield `X` for this process of selecting candidate functions.

?

**Comment by languagelawyer** [comment]
> "Result" is defined as the value/object returned by the function call, so I don't think that's quite right.

Then the note [basic.lval]/4 needs editorial fix? It says "An expression is an xvalue if it is: the result of calling a function, whether implicitly or explicitly, whose return type is an rvalue reference to object type"

There already exists PR about [basic.lval]/4 — #2045 — so the fix for "xvalue is ... the result of calling a function" could be added into it?

**Comment by languagelawyer** [comment]
[diff.expr]/4 is also broken: "C++ is an object-oriented language, placing relatively more emphasis on lvalues For example, functions may return lvalues."

**Comment by tkoeppe** [comment]
I'm inclined to call this NAD. I have no problem with "returning an xvalue"; in fact, that's how I usually say it myself when the distinctions matter.

To me, this fits as follows: as a general statement that I think sounds meaningful to most programmers, regardless of language, "a function returns a value" is a useful shorthand for "the result of evaluating a function call expression is a value". Now all we're doing is extending this schema to be specific about the category of that value.
