### ISSUE TITLE
[atomics.types.operations] misuses "underlying type"

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#2057]
The note in [atomics.types.operations] p23 says "if the underlying type has ..." but this is not the same meaning of "underlying type" used elsewhere ([basic.fundamental] and [dcl.enum]).

[atomics.types.generic] uses the phrase "the template argument for `T`", and the nested type `value_type` is also defined. Either would be better than "the underlying type", but I think the note would be improved by referring to "object representation of the type", possibly even making use of `std::has_unique_object_representations`.

**Comment by jfbastien** [comment]
`std::has_unique_object_representations` is probably the wrong choice given the behavior that's expected for floating-point types. The intent is to discuss the type stored in lieu of `T`, because SG1 believes that `atomic<T>` doesn't contain a `T`.

**Comment by jensmaurer** [comment]
This is a note, so we don't have to be super-precise. I just used "object representation" instead of "underlying type", which is sufficiently vague about how the T's are actually stored.
