### ISSUE TITLE
Follow "semantic line breaks" in the LaTeX sources

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#2064]
See http://sembr.org/ and http://rhodesmill.org/brandon/2012/one-sentence-per-line/

The following example makes it hard to grep for "pointer types" in the source, because of an arbitrary line break that would have been better placed before "pointer":

````
Arithmetic types\iref{basic.fundamental}, enumeration types, pointer
types, pointer-to-member types\iref{basic.compound},
````

Reformatting everything would be a huge amount of churn and make `git blame` less convenient, but it would be good to start following this style when making other editing changes.

**Comment by jwakely** [comment]
This one's even worse because we have a line break in the middle of a `\defn`:

````
Cv-unqualified scalar types, trivially copyable class types\iref{class}, arrays of
such types, and cv-qualified versions of these
types are collectively called \defn{trivially
copyable types}.
````

This means to search for all occurrences of "trivially copyable types" you need to search in the generated PDF rather than the sources.

**Comment by tkoeppe** [comment]
I wouldn't be opposed to that being changed :-)

**Comment by jensmaurer** [comment]
We should decide whether "semantic line breaks" should become an editorial guideline.
Pros: see above
Cons: We can no longer press "M-q" (reformat paragraph to fit window size) in emacs to auto-reformat overlong lines. (Not that I do that frequently, because it likely adds no-op diffs to a change.)

**Comment by jensmaurer** [comment]
Editorial meeting consensus: This is already the convention; we simply need to document this policy.

**Comment by jensmaurer** [comment]
Added a sentence to the "Source code formatting" section of our "Specification Style Guidelines".

**Comment by jwakely** [comment]
Thanks! Should we close this now then?

**Comment by jensmaurer** [comment]
Since we're probably not doing fixes for violations unless we're editing in the vicinity, let's close this issue.
