### ISSUE TITLE
Overuse and misuse of \techterm in [rand]

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#2072]
Terms are defined using `\techterm` and then also referred to using it e.g. [rand.req.urng] uses it for _uniform random bit generator_ in paragraphs 1 and 2. These terms are not indexed, because they're introduced with `\techterm` not `\defn`.

We also have terms that don't need defining here, like `\techterm{signed}` and `\techterm{unsigned}`.

**Comment by jensmaurer** [comment]
We should consider whether there is space for non-indexed, yet italics `\techterm`s that are only valid locally, or whether we should strive for indexed `\defn` terms in all cases.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: As a rule of thumb, if a term is local to a subclause, do not make it italics and do not index it, i.e. delete any \techterm or \term decoration. Anything with a larger scope should get an index entry. Net result: \techterm has been excised from the standard.

**Comment by tkoeppe** [comment]
See also 76545fa54e33861c73789f070774257a9689723f.

**Comment by jensmaurer** [comment]
$ grep techterm *.tex
(empty)
