### ISSUE TITLE
Probably wrong complexity of std::includes

### ISSUE THREAD

**Issue by pisarik** [cplusplus/draft#2082]
I started from the [question at stackoverflow](https://stackoverflow.com/questions/50514694/complexity-of-algorithm-stdincludes-in-c).

[Here](https://github.com/cplusplus/draft/blob/6242d7291cf379a63ec5d4cb65af0d6c2c2273ec/source/algorithms.tex#L4612) stated that algorithm `std::includes` has complexity at most `2 * ((last1 - first1) + (last2 - first2)) - 1` comparisons.

But it seems the algorithm has complexity at most `2 * (last1 - first1)` comparisons. Probably this mistake arose from complexity of operations `std::union` and `std::intersection`.

It would be cool to see a nice answer at stackoverflow on it.

**Comment by timsong-cpp** [comment]
This is not an editorial issue; it needs to go to LWG.

**Comment by pisarik** [comment]
Should I create an issue here issues.isocpp.org ?

**Comment by zygoloid** [comment]
I believe this issue is incorrect. Remember that either range can contain duplicate elements. Consider:

```
int haystack[] = {1};
int needles[] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
includes(begin(haystack), end(haystack), begin(needles), end(needles));
```

Clearly we cannot give a complexity bound better than `last2 - first2` comparisons.

**Comment by timsong-cpp** [comment]
See http://lists.isocpp.org/lib/2018/05/7092.php; `includes` is actually checking for subsequence-ness. Once you exhaust `haystack` there's no point going through the rest of `needles`.

**Comment by zygoloid** [comment]
The complexity requirements are consistent with the current description, and should be fixed if/when the description is fixed to actually describe what the algorithm is "supposed' to do. Seems like LWG is already on the case. I'll reply to that lib thread to request that the complexity be revisited when the spec is fixed.
