### ISSUE TITLE
Wrong specification of `basic_string_view::starts_with(basic_string_view)`

### ISSUE THREAD

**Issue by lhmouse** [cplusplus/draft#2087]
https://github.com/cplusplus/draft/blob/61b6c21f218e3cbb9d15426975f1a26d8b72a7fe/source/strings.tex#L5451

The current specification, which is equivalent to 
```c++
return compare(x) == 0;
```
, compares the entire `basic_string_view` with `x`.

As its name suggests, the expected implementation is 
```c++
return compare(0, x.size(), x) == 0;
```

**Comment by zygoloid** [comment]
I agree, but this is not editorial. Can you email lwgchair@gmail.com and ask to have an issue opened?

**Comment by cpplearner** [comment]
This is a duplicate of #1870 and [LWG 3040](https://cplusplus.github.io/LWG/issue3040)

**Comment by jensmaurer** [comment]
(The current proposed resolution for LWG 3040 seems technically incorrect; I've sent an e-mail to the -lib reflector.)
