### ISSUE TITLE
"lvalue-reference" and "rvalue-reference" should not be hyphenated

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#209]
In N3690, there are 7 occurrences of "lvalue-reference" and 2 occurrences of "rvalue-reference" (in 20.9.1.2 [unique.ptr.single]/1, 20.9.1.2.1 [unique.ptr.single.ctor]/10-12, and 20.10.2 [func.require]/4).  They aren't hyphenated in the rest of the Standard.

**Comment by cpplearner** [comment]
Solved by 5599ece.

**Comment by jwakely** [comment]
Yes, dup of #446
