### ISSUE TITLE
[intro.refs]/1 Plurality correction

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2090]
[[intro.refs]/1](https://wg21.link/intro.refs#1) says (emphasis mine):
>The following documents are referred to in the text in such a way that some or all of their content **constitutes** requirements of this document.

Since it talks about a plurality of content here, it should read constitute.

**Comment by jensmaurer** [comment]
ISO directives part 2, 8th edition, subclause 15.5.2 require ("shall be introduced by the following wording") this intro text:

> The following documents are referred to in the text in such a way that some or all of their content constitutes requirements of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.

So, we can't change the text. (Plus, "content" is singular here, so it seems the grammar is actually correct; "their" just means the (single) content has multiple owners.)

**Comment by jwakely** [comment]
The grammar is correct. The referenced documents' content _is_ relevant to C++, and their content constitutes requirements of the C++ standard.
