### ISSUE TITLE
[util.smartptr.shared.assign] assign from auto_ptr&& is in the wrong paragraph

### ISSUE THREAD

**Issue by BoPersson** [cplusplus/draft#211]
shared_ptr assignment has two groups of assignments, assignment from lvalue (paragraphs 1-3) and assignment from rvalue (paragraphs 4-5). 

operator=(auto_ptr<Y>&&) is shown in the first group, but the Effects clause is not valid for that operator. It belongs in the second group of operators.

**Comment by jwakely** [comment]
`auto_ptr` has been removed from the draft, so this issue is no longer relevant (except for the missing period, which I'll fix now).
