### ISSUE TITLE
Harmonize index entries for list items

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#2110]
I've found the following 3 styles in use:

1. \indextext on the line *before* the \item ([example](https://github.com/cplusplus/draft/blob/b821b0174d64429c075aa6a6d88c2e36705eccf1/source/preprocessor.tex#L1363))
2. \indextext on the *same* line as the \item ([example](https://github.com/cplusplus/draft/blob/b821b0174d64429c075aa6a6d88c2e36705eccf1/source/basic.tex#L2376))
3. \indextext on the line *after* the \item ([example](https://github.com/cplusplus/draft/blob/b821b0174d64429c075aa6a6d88c2e36705eccf1/source/special.tex#L1936))

One thing style 3 has going for it is that it is consistent with the [existing style rule](https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines#source-code-formatting) for index entries for paragraphs (which are to be placed on separate lines after the \pnum).

I'd be happy to submit a patch once a style is chosen. I guess the style guidelines could be updated to show an index entry for a list item, too.

**Comment by jensmaurer** [comment]
Editorial meeting: Put \indextext etc. markers after \item, on a separate line. This is consistent with \pnum: \indextext also goes after \pnum. Mind the % at the end of the line for LaTeX reasons.
