### ISSUE TITLE
[2018-06 LWG Motion 19] P0769R2 Add shift to <algorithm>

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2136]

**Comment by timsong-cpp** [comment]
This one needs some fixes:

- `shift_left`'s _Returns:_ uses the expression `first + (last - first) - n`, this should be reparenthesized to `first +(last - first - n)` or `first + ((last - first) - n)`. There's no library wording defining `a - n` for forward iterators.
- We don't have a CamelCased `BidirectionalIterator` requirements, so `shift_right`'s "the `BidirectionalIterator` requirements" (in both the _Requires_ and _Effects_ paragraphs) should be "the requirements of a bidirectional iterator", with a cross-reference to [bidirectional.iterators].

**Comment by AlisdairM** [comment]
We use iterator arithmetic, even for forward iterators, where the semantics are clear.  Every so often there are attempts to clean it up, but if precision comes at the cost of too much clarity, the shorthand usually wins.
