### ISSUE TITLE
[2018-06 LWG Motion 24] P0019R8 Atomic ref

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2141]

**Comment by jensmaurer** [comment]
"The __cpp_lib_atomic_ref feature test macro should be added."

**Comment by jfbastien** [comment]
Did we ever resolve if D1123r0 could be applied editorially, or whether it'll require extra approval in San Diego? It might be useful to go through CWG, and maybe wait for #2105 resolution.

**Comment by tkoeppe** [comment]
Since D1123 is not editorial, but normative, I would very much like such a document to be reviewed by CWG.

**Comment by AlisdairM** [comment]
Consensus was that D1123r0 went beyond editorial guidance, so needs a separate review (and likely updates) for San Diego.

**Comment by jensmaurer** [comment]
This paper claims "For signed integer types, arithmetic is defined to use two’s complement representation. There are no undefined results." but atomic_ref operates on an existing object of type T. What if that type T has sign-magnitude representation and the operation happens to produce INT_MIN in two's complement, which is not representable as a sign-magnitude number?

**Comment by jensmaurer** [comment]
"The __cpp_lib_atomic_ref feature test macro should be added."

**Comment by jfbastien** [comment]
> This paper claims "For signed integer types, arithmetic is defined to use two’s complement representation. There are no undefined results." but atomic_ref operates on an existing object of type T. What if that type T has sign-magnitude representation and the operation happens to produce INT_MIN in two's complement, which is not representable as a sign-magnitude number?

p0907 was forwarded to CWG and should get into the draft soon. Maybe open an issue and we can close as NAD if p0907 makes it through?
