### ISSUE TITLE
 [vector.cons]/1 should say noexcept

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#2178]
N4750 26.3.11.2 [vector.cons]/1 defines:

`explicit vector(const Allocator&);`

But 26.3.11.1 [vector.overview] declared:

`explicit vector(const Allocator&) noexcept;`

**Comment by liuziangexit** [comment]
I thought that only move constructors need noexcept...

**Comment by jensmaurer** [comment]
This change added noexcept in the synopsis:

commit 6e3b46f1d8e1c4ca4d580d9e4f7d5abd5316120b
Author: Richard Smith <richard@metafoo.co.uk>
Date:   Mon Nov 10 17:23:30 2014 -0800

    N4258 Cleaning‐up noexcept in the Library
    
    [unord.set.overview], [unord.multiset.overview]: Replace meaningless
    "Container_move_assign" with the intended "Pred".

I believe the intent of that paper was clear: make the named std::vector constructor noexcept, so fixing this seems editorial to me.

**Comment by jensmaurer** [comment]
(I notice that the partial specialization for vector<bool, Allocator> does not have the various noexcept fixes in the constructors.)
