### ISSUE TITLE
[class.copy.assign]/7.4 CWG 1499: misses the unsuccessful overload resolution case

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#2179]
[[class.copy.assign]/7](http://eel.is/c++draft/class.copy.assign#7) says:
> A defaulted copy/move assignment operator for class X is defined as deleted if X has:
> …
> [(7.4)](http://eel.is/c++draft/class.copy.assign#7.4) —  a direct non-static data member of class type M (or array thereof) or a direct base class M that cannot be copied/moved because overload resolution, as applied to find M's corresponding assignment operator, results in an ambiguity or a function that is deleted or inaccessible from the defaulted assignment operator.

For the code
```
struct M {};

struct X {
    const M m{};
};
```
(I assume) the intent is that the implicit copy assignment operator for `X` shall be deleted. But:
1. `M`'s assignment operator is accessible and not deleted. "inaccessible" ­— is about access control, right?
2. Overload resolution is not ambiguous, because the set of viable functions chosen by [over.match.viable] is empty: there is no implicit conversion from `const M` implied object argument to `M&` implicit object parameter of `M`'s implicitly-declared copy assignment operator.
And [If the set of candidate functions is empty, overload resolution is unsuccessful.](http://eel.is/c++draft/over.match#footnote-128)
unsuccessful ≠ ambiguous. There is no ambiguity when there is nothing to select from.

Should only this paragraph be fixed or the fix for [over.match] is also required to say explicitly that unsuccessful overload resolution means ill-formed program (or vice versa), I don't know.

**Comment by jensmaurer** [comment]
We usually just say "overload resolution fails" when we mean any of the failure cases, including not having a viable function to start with.

**Comment by jensmaurer** [comment]
Editorial meeting: Not editorial (has normative impact).

**Comment by languagelawyer** [comment]
@jensmaurer isn't this https://wg21.link/cwg1499?

**Comment by jensmaurer** [comment]
[CWG 1499](https://wg21.link/cwg1499)

**Comment by frederick-vs-ja** [comment]
I think this is mute now, and CWG1499 is resolved by the resolution of CWG1353.
