### ISSUE TITLE
[dcl.init.ref]/5 misuses "underlying type" for references

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#2180]
There was issue #391 about 'underlying type' for a reference used in [over.match], fixed by #1013. But this misusage of 'underlying type' is still exists in "this document", in the definition of [bind directly](http://eel.is/c++draft/dcl.init.ref#def:bind_directly) :
> In all cases except the last (i.e., implicitly converting the initializer expression to the underlying type of the reference), the reference is said to bind directly to the initializer expression.

---

I've searched with the https://github.com/cplusplus/draft/search?q=%22underlying+type%22 request. This looks like the last place where 'underlying type' is mentioned in a context not related to enumerations or `wchar_t`/`char{16,32}_t`.

**Comment by jensmaurer** [comment]
There is also #2057.

**Comment by languagelawyer** [comment]
> There is also #2057.

Well, you are right. I meant that this is the last place which was not reported yet. I know about #2057, the title of this issue was inspired by it.
