### ISSUE TITLE
Typo in Rapperswil CWG motion 14

### ISSUE THREAD

**Issue by Dani-Hub** [cplusplus/draft#2192]
I noticed a typo in p0542r5,

http://wiki.edg.com/pub/Wg21rapperswil2018/StrawPolls/p0542r5.html

The first edit for

"Modify clause 6.4.1 [basic.lookup.unqual], p. 7:"

has a "contact condition" instead of a "contract condition"

**Comment by jensmaurer** [comment]
Please check pull request #2151; I can't find "contact" in there.
