### ISSUE TITLE
add subclause structure to [dcl.attr.contract]

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2197]
[dcl.attr.contract] would benefit from some subclause structure. I'd suggest:

----

# Contract attributes [dcl.attr.contract]
## Overview [dcl.attr.contract.over]

 * Is there a better name for this?

p1 - p4 (grammar and introduction to the three attributes)

p12: Merge into p4; move the "A contract condition may be applied to the function type of a function declaration." from p6 into both p2 and p3, changing "A contract condition" to "The attribute". Change "An assertion" to "The attribute" in the p12 wording likewise.

p5, p13 (general properties of contract predicates)

## Contract conditions [dcl.attr.contract.cond]

p6 - p11

p14

## Checking contracts [dcl.attr.contract.check]

p15

p16: Convert to a note.

p17 - p21

----

This should give three sections of little over a page of text each, each of which describes a fairly coherent piece of the feature.

**Comment by jensmaurer** [comment]
I've called the "overview" section "syntax". We still have the "is checked" wording in the other sections, but I agree the substructure is an improvement.
