### ISSUE TITLE
[time.duration.io] Requires: element should be a Remarks:

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2208]
Everything in http://eel.is/c++draft/time.duration.io#1 can be detected at compile time, so it seems to be a misuse that should new be clear that should use a _Remarks:_ element coupled with the _shall not participate in overload resolution_ wording. Do you think this can be done editorially?

A better solution would be to permit all integral types. I assume this element exists to prevent a `duration` with a `char`-like `Rep` from being printed as a character. Such a change would probably require a paper and not a DR.

**Comment by jwakely** [comment]
This is definitely no editorial.

**Comment by johelegp** [comment]
Thank you. I'll submit a DR.
