### ISSUE TITLE
[time] Inconsistent ordering of elements of description

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2209]
Throughout [time], the ordering of _Remarks:_ (mostly), _Throws:_ and probably some other elements is inconsistent with their ordering in the rest of the library, which follow the order as described in https://wg21.link/structure.specifications#3. There are also local inconsistencies in the ordering.

**Comment by jensmaurer** [comment]
As far as I can see (from sampling the first few occurrences of "Remarks"), it's inconsistently ordered in exactly those cases where it talks about participation in overload resolution. This will be replaced by a \constraints item in the near future, I'd guess, which is sorted correctly near the top.
