### ISSUE TITLE
"Returns:" should be followed by an English sentence

### ISSUE THREAD

**Issue by lichray** [cplusplus/draft#223]
There are several different practices in the standard:
1. Returns: `expr`
2. Returns: `expr`.
3. Returns: `expr;`
4. Returns: `expr;`.
5. Returns: English sentence.
6. Returns: `expr;` english sentence.

Suggestion:

Regard an expression as an English sentence, thus, keep 2 and 5, replace 1,3,4 with 2, replace 6 with "Returns: `expr`, english sentence.".

**Comment by tkoeppe** [comment]
I'm pretty sure this is a duplicate. @jensmaurer: Do you recall us discussing this not too long ago?

**Comment by jwakely** [comment]
See #694 and #1119
