### ISSUE TITLE
Proposal: Pull all macros into a custom documentclass

### ISSUE THREAD

**Issue by godbyk** [cplusplus/draft#2256]
I propose consolidating much of the preamble of `std.tex` and the contents of the `layouts.tex`, `styles.tex`, `macros.tex`, and `tables.tex` files (and perhaps a few others) into a new `std.cls` document class.

This would make it easier for proposals to reuse the same macros and format as the standard and streamline integration of accepted proposals into the standard.

I'm happy to do the work on this if it sounds like a good idea.

Thoughts?

**Comment by zygoloid** [comment]
Baseline assumption:
 * proposals aren't going to be written in .tex; as @tkoeppe points out, it's easier to maintain small proposals in HTML
 * TSes are going to start by forking the standard sources, and don't care whether we use a document class or individual macro and style definitions

So the people who'd be benefitting from this would largely be the people maintaining the draft itself. @godbyk, what advantages are there to us of converting from .tex files to a document class? How does that affect the maintenance of our macros and style rules?

**Comment by godbyk** [comment]
@zygoloid The primary advantage is just in the organization. All the formatting/style code then lives in a single file instead of being scattered across half a dozen files. It also helps us separate content from presentation.

I did some initial work consolidating the files and code into a [`std.cls`](https://github.com/godbyk/draft/blob/documentclass/source/std.cls) document class. Doing this cleans up the [`std.tex`](https://github.com/godbyk/draft/blob/documentclass/source/std.tex) file considerably. It also pulls out a lot of previously hidden variables and places them up front in `std.tex` so they're easier to update (e.g., document numbers, editor info).

(Note that the `std.cls` file is a bit messy right now as I essentially just moved large swaths of code into it. This isn't a final product, just an exploratory experiment.)

**Comment by jensmaurer** [comment]
Editorial meeting:
- Some people have a lot of experience with LaTeX, others have less so.
- The real work is abstracting away the differences between the IS and the TSes (cover page, title etc)
- Add instructions to wiki how to add an ISO-conforming cover page (also for TS). But that changes rather often.
- Clean up std.tex.
- Total maintenance cost goes up with .cls file; consider the cover sheet. Maintenance in .cls file is much harder due to lots of special formatting.
-> Thanks for sharing. We say "no" to this.
