### ISSUE TITLE
Names from namespace std::pmr need to be qualified LWG 2818

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#2269]
[contents] says:

>  Whenever a name `x` defined in the standard library is mentioned, the name `x` is assumed to be fully qualified as `::std::x`, unless explicitly described otherwise.

Names in subclause [mem.res] are in the nested namespace `std::pmr` so names like `get_default_resource()` need to be qualified, otherwise [contents] means that it refers to `::std::get_default_resource()` (which doesn't exist).

Maybe at the start of a subclause like [mem.res] we need to say that for the rest of the subclause names are fully qualified as either `::std::x` _or_ `std::pmr::x` as appropriate.

[time] and [filesystem] have similar issues for names in `::std::chrono` and `std::filesystem` respectively. See also #1793.

**Comment by CaseyCarter** [comment]
I noticed this - and went to look at `chrono` and `filesystem` to see what we do there - when I was thinking about the same problem for `std::ranges`. Perhaps we need to change the blanket wording to more generically claim that all names are fully qualified without reference to a specific namespace?

**Comment by jwakely** [comment]
I'm assigned to fix [contents] via [LWG 2818](https://wg21.linki/lwg2818).
