### ISSUE TITLE
note on locations where nodeclspec-function-declarator can appear seems to be incorrect

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2276]
[dcl.dcl]p12 says:

> A *nodeclspec-function-declaration* shall declare a constructor, destructor, or conversion function. [*Footnote*: The “implicit int” rule of C is no longer supported.] [*Note*: A *nodeclspec-function-declaration* can only be used in a *template-declaration* (Clause 12), *explicit-instantiation* (12.8.2), or *explicit-specialization* (12.8.3). — *end note*]

This is wrong in two ways.

1. The footnote is wrong: the "implicit int" rule in C never permitted declarations without any *specifiers-and-qualifiers*, so implicit int has nothing to do with *nodeclspec-function-declaration*s.
2. The note is wrong: a *nodeclspec-function-declaration* can't be used in a *template-declaration*. An out-of-line declaration of a member function must be either a definition, a friend, an explicit instantiation, or an explicit specialization, and a non-defining *template-declaration* is none of those things. (See [class.mfct]p1, which would incidentally benefit from saying something about the friend and explicit instantiation cases, though the friend case is at least mentioned by p6.)

**Comment by jensmaurer** [comment]
[dcl.type] p3 already has a footnote talking about the "implicit int rule". Let's remove the footnote.

@zygoloid, I don't understand the point on the note. I believe there are _template-declaration_s where we can, in fact, use a _nodeclspec-function-declaration_ (admittedly, those are definitions, but _declaration_ is not limited to non-defining declarations, I believe).

**Comment by jensmaurer** [comment]
@zygoloid: I get it now: The grammar for _nodeclspec-function-declaration_ only allows a non-defining declaration.

**Comment by jensmaurer** [comment]
@zygoloid: It seems to me that
```
struct S {
  template<class T> S(T);
};
```
recurses through _member-declaration_ / _template-declaration_ / _declaration_ / _nodeclspec-function-declaration_ and that's where the note applies. [temp] p2 says the _declaration_ must declare a function, which it does, if [dcl.fct] is ever supposed to be applicable to constructors ("returning T"?)

**Comment by zygoloid** [comment]
Ah, yes, OK then. So the note is subtle but correct.
