### ISSUE TITLE
[concepts.equality] modifying and non-modifying expressions

### ISSUE THREAD

**Issue by h0nzZik** [cplusplus/draft#2286]
The section [concepts.equality] uses the term _non-modifying expression_ (e.g. in 17.1.3 and 17.1.6), but such term is never defined.

**Comment by jensmaurer** [comment]
[concepts.equality] p5 seems to define when an expression "is said to modify" an input. That seems close enough to specify what it means for an expression to be "non-modifying" for some input.
Also, section numbers 17.1.3 and 17.1.6 don't exist in the current working draft; could you please give us section labels?

**Comment by h0nzZik** [comment]
Yes, now I see. My mistake. Closing.

(I meant the paragraphs 3 and 6 in [concepts.equality].)
