### ISSUE TITLE
The word "below" in [basic.lookup.argdep]/3 should be replaced by "above". 

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#2287]
The word  "below" should be replace by "above" in [[basic.lookup.argdep]/3](http://eel.is/c++draft/basic.lookup.argdep#3):

> Let X be the lookup set produced by unqualified lookup and let Y be the lookup set produced by argument dependent lookup (defined as follows). If X contains
>     (3.1) a declaration of a class member, or
>     (3.2) a block-scope function declaration that is not a using-declaration, or
>     (3.3) a declaration that is neither a function nor a function template
> then Y is empty. Otherwise Y is the set of declarations found in the namespaces associated with the argument types as described ~~below~~**above**. The set of declarations found by the lookup of the name is the union of X and Y. [ Note: The namespaces and classes associated with the argument types can include namespaces and classes already considered by the ordinary unqualified lookup. — end note ] [ Example:

**Comment by jwakely** [comment]
The set of associated namespaces is defined by paragraph 2, above, but the set of declarations found in the associated namespaces is determined by paragraph 4, below. It's talking about the set of declarations, so "below" is correct.

**Comment by jabelloc** [comment]
That's clear now. Thanks.
