### ISSUE TITLE
[std] Use of undefined term "structure"

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2289]
Subject: [isocpp-edit] Use of term structure instead of class
Date: Tue, 7 Aug 2018 17:43:21 +0900
From: Ryou Ezoe <boostcpp@gmail.com>

I noticed that current latest draft(N4750) still use the term
"structure" instead of "class".

The term "structure" as in defined in C Standard. But it isn't defined
in the C++ standard. C++ use the term "class". But there are some
places still use the term structure to mean class. And context doesn't
relies on C standard at all.

$ 6.6.1 p5

> [ Example: A structure declared as

This structure shall be class.

$ 23.4.5 p1

>The struct piecewise_construct_t is an empty structure type used as...

$ 23.6.4 p1

> The struct nullopt_t is an empty structure type used as ...

$ 23.10.7 p1

> The allocator_arg_t struct is an empty structure type used as ...

These structure shall be class.

$ 23.17.10.4.1 p1

> A sys_info structure can be obtained from

$ 23.17.10.4.1 p2

> Typical conversions from sys_time to local_time will use this structure implicitly, not explicitly.

$ 23.17.10.4.2 p1

> Typical conversions from sys_time to local_time will use this structure implicitly, not explicitly.

These structure shall be class.

Table 121

> no sub-expression matches shall be stored in the supplied match_results structure.

This structure shall be class.

I don't understand how could the wording introduced after C++11 still
use the term structure.

The usage I think it should be retained.

There are three occurrences of "structure" as "POSIX stat structure"
in filesystem.

> On POSIX platforms, this is determined as if by the values of the POSIX stat structure,
> determined as if by the value of the POSIX stat structure member st_size
>  determined as if by the value of the POSIX stat structure member st_mtime

The index has structure. linked to page 214($12 Class).

I think this should be retained too but $12 Class has no mention of
the term structure.

**Comment by jwakely** [comment]
>> no sub-expression matches shall be stored in the supplied match_results structure.

> This structure shall be class.

I think it should be object instead.
