### ISSUE TITLE
[class.temporary]/1: prvalue can't be materialized, it is an expression

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#2305]
> Temporary objects are created
> — when a prvalue is materialized so that it can be used as a glvalue ([conv.rval]),

Suggested fix:
> — when a prvalue is converted to an xvalue ([conv.rval]),

Also, I think the colon should be placed before the list of cases.

**Comment by cpplearner** [comment]
Why an expression can't be materialized?

**Comment by languagelawyer** [comment]
[conv.rval] is titled "Temporary materialization conversion". The only temporaries we have in this document are temporary objects. "temporary expression" is a meaningless combination of words which will be dropped (reported by you, BTW).
[class.temporary]/1 is the only place I've found which says "a prvalue is materialized". All other places say either "a temporary object is materialized" or "the temporary materialization conversion is applied".

**Comment by cpplearner** [comment]
My understanding is that temporaries are the product of materialization, so "a temporary is materialized" and "a prvalue is materialized (to produce a temporary)" both make sense.

**Comment by languagelawyer** [comment]
I agree that there is no absolute argument showing that one can't use such a wording.
But it is used only in one place, other places say "a temporary object is materialized".
