### ISSUE TITLE
[expr.prim.this]/2 alludes to the grammar production `declarator` without necessity

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#2306]
[[expr.prim.this]/2](http://eel.is/c++draft/expr.prim#this-2):

> If a declaration declares a member function or member function template of a class X, the expression this  is a prvalue of type “pointer to cv-qualifier-seq X” between the optional cv-qualifier-seq and the end of the function-definition, member-declarator, or **declarator**.  . . .

A _member-declarator_ is already [defined](http://eel.is/c++draft/class.mem#nt:member-declarator) in terms of a _declarator_. Therefore, the declarator can be eliminated above without loss of generality.

**Comment by cpplearner** [comment]
In `template auto A::f(int t) -> decltype(t + g());`, `A::f(int t) -> decltype(t + g());` is a declarator but not a member-declarator.

**Comment by jensmaurer** [comment]
Right you are.

**Comment by cpplearner** [comment]
(But `declarator` should probably be changed to `init-declarator`, to make `this` valid in a trailing requires-clause.)
