### ISSUE TITLE
[expr.const]/2.11 CWG 2186: "Preceding" is unclear

### ISSUE THREAD

**Issue by xskxzr** [cplusplus/draft#2307]
[expr.const]/2.11:

> An expression e is a core constant expression unless the evaluation of e, following the rules of the abstract machine, would evaluate one of the following expressions:
> - ...
> - an id-expression that refers to a variable or data member of reference type unless the reference has a preceding initialization and either
>   - it is initialized with a constant expression or
>   - its lifetime began within the evaluation of e;

It's unclear what "preceding" means. It may either mean the initialization happens before the evaluation of the id-expression, or mean the initialization occurs before the id-expression **in lexical order**. 

According to this example in [cppreference](https://en.cppreference.com/w/cpp/language/constant_initialization):
```
struct S {
    static const int c;
};
const int d = 10 * S::c; // not a constant expression: S::c has no preceding
                         // initializer, this initialization happens after const
const int S::c = 5;      // constant initialization, guaranteed to happen first
```

It seems "preceding" means the latter, but consider:
```
constexpr int f(const int &i)
{
    return i;
}

constexpr int j = f(0);
```

Here `f(0)` is obviously a constant expression, **but the initialization of `i` does not occur before `return i;` in lexical order**.

I think it makes more sense to say:
- an id-expression that refers to a variable or data member of reference type unless either 
   - the reference has a preceding initialization, initialized with a constant expression or
   - its lifetime began within the evaluation of e;

**Comment by cpplearner** [comment]
I don't think this is editorial, and there is already [CWG 2186](https://wg21.link/cwg2186).

**Comment by frederick-vs-ja** [comment]
This issue is now mute. The first "preceding" in [N4659 [expr.const]](https://timsong-cpp.github.io/cppwp/n4659/expr.const) was removed by [P0595R2](https://wg21.link/p0595r2), and the second was removed by [P2280R4](https://wg21.link/p2280r4).

I believe the meaning is clear enough now, and both this issue and CWG2186 can be closed. @jensmaurer

**Comment by jensmaurer** [comment]
off-topic: "mute" and "moot" are different things...

**Comment by jensmaurer** [comment]
Closed CWG2186.
