### ISSUE TITLE
operator= missing from overview for (some) valarray classes

### ISSUE THREAD

**Issue by mclow** [cplusplus/draft#232]
The classes:
- slice_array (section 26.6.6)
- gslice_array (section 26.6.7)
- mask_array (section 26.6.8)
- indirect_array (section 26.6.9)

all have `void operator=(const valarray<T>&) const;` defined in the section [XXX.assign], but these operators do not appear in the [XXX.overview] section.

**Comment by jensmaurer** [comment]
They're all defined in the .overview sections as of now.
