### ISSUE TITLE
[basic.fundamental] CWG 2185: Missing "and cv-qualified versions of those types" for various type categories

### ISSUE THREAD

**Issue by Rakete1111** [cplusplus/draft#2334]
Every type category in [basic.fundamental] (integrals, narrow character types, floating points, ...) don't mention cv-qualified types. For example [basic.fundamental]p7:
 
> Types `bool`, `char`, `char16_­t`, `char32_­t`, `wchar_­t`, and the signed and unsigned integer types are collectively called *integral* types.

Is `const bool` an integral type? Obviously yes, but this is not mentioned anywhere. Because a lot of type categories are introduced in that section, maybe add a new paragraph that says something like:

> If a type *T* is a X type, where X is one of the types of types mentioned in this section, then `cv-qualifiers T` is also a X type.

**Comment by cpplearner** [comment]
How does it interact with [\[basic.type.qualifier\]/1](https://timsong-cpp.github.io/cppwp/n4659/basic.type.qualifier#def:type,cv-unqualified)?

> A type mentioned in [basic.fundamental] and [basic.compound] is a cv-unqualified type.

**Comment by Rakete1111** [comment]
Oh yeah thanks, looks like a contradiction. Probably better to also change that sentence I think (if there is no better alternative).

Also just noticed that [basic.compound] has some definitions that also suffer from the same issue as [basic.fundamental].

**Comment by jensmaurer** [comment]
This is [CWG 2185](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2185).

**Comment by frederick-vs-ja** [comment]
Should have been fixed by #4693 (https://github.com/cplusplus/draft/pull/4693/commits/4df64b457e02c2d66567f4fc11041b43ce199cd2).
