### ISSUE TITLE
[dcl.init.aggr] Bad phrase "empty initializer list"

### ISSUE THREAD

**Issue by h0nzZik** [cplusplus/draft#2335]
The section [dcl.init.aggr] uses the phrases "empty initializer list" and "empty initializer-list" (paragraphs 5.2, 5.5, 9,  and the footnote in paragraph 9). It may be in another places, too. I believe the phrase is nonsensical, since _initializer-list_ as defined by the grammar in paragraph 1 of [dcl.init] can be never empty. Also, the paragraph 9 of [dcl.init.aggr] talks about
> [...] empty initializer list {} [...]

I guess that it should talk about `braced-init-list`, not about `initializer-list`.

**Comment by jensmaurer** [comment]
I agree this should read "empty braced-init-list", although "initializer list" reads nicer.

**Comment by cpplearner** [comment]
Per [dcl.init.list]/1, an initializer list is a _braced-init-list_ used as an initializer:

> List-initialization is initialization of an object or reference from a _braced-init-list_. Such an initializer is called an initializer list, and the comma-separated *initializer-clause*s of the *initializer-list* or *designated-initializer-clause*s of the *designated-initializer-list* are called the elements of the initializer list. An initializer list may be empty.

**Comment by jensmaurer** [comment]
Good point. So, the phrasing is good as-is; the only remaining issue is whether we anywhere talk about an "empty _initializer-list_", which would not make sense. Ah, the footnote in [dcl.init.aggr] does that, so that is the only place that needs fixing.
