### ISSUE TITLE
[alg.shift] Slight mismatch with accepted proposal wording

### ISSUE THREAD

**Issue by danra** [cplusplus/draft#2337]
The _Returns_ clause 3 under [alg.shift] in P0769R2 says
_Returns:_ `first + (last – first) – n` if `n` is positive...

The matching clause in the latest published Standard draft (n4762) is slightly different:
_Returns:_ `first + (last – first – n)` if `n` is positive...

Was this change done intentionally? If not, can we keep the original ones?

Thanks,
Dan

**Comment by cpplearner** [comment]
I guess the standard wants to avoid substraction between ForwardIterator and number.

**Comment by danra** [comment]
Ah, that makes sense. Thanks!
