### ISSUE TITLE
[class.this] restriction on constructors and destructors has nothing to do with this pointer

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#2347]
[class.this]p4 is the constraint that constructors/destructors do not have cv-qualifiers.  It probably belong better in [class.mfct.non-static] after its p4, that talks about cv-qualifiers on non-static member functions.

p5 talks about ref-qualifiers on non-static member functions, and I don't see anything stating that this does not apply to ctors/dtors.  If that falls out of the grammar, then perhaps this cv-restriction would go the same way, and this paragraph should be demoted to a note?  Otherwise, there may be a CWG issue needs to be opened on ref-qualifiers on constructors?  (Just as likely I missed this restriction in another cross-reference, in which case it would be good to call that out here too.)

**Comment by jensmaurer** [comment]
Both [class.ctor] and [class.dtor] present limited declarator syntax for constructors/destructors, which does not allow for cv-qualifiers or ref-qualifiers.

**Comment by AlisdairM** [comment]
OK, so no concerns with ref-qualfiers, but moving the paragraph into a more appropriate clause still makes sense.
