### ISSUE TITLE
Wonky wording: operators that "admit" other operators?

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#2357]
E.g. in [[cmp.weakord]/1](http://eel.is/c++draft/cmp.weakord#1.sentence-1):
> The `weak_­ordering` type is typically used as the result type of a three-way comparison operator that (a) admits all of the six two-way comparison operators ([expr.rel], [expr.eq]), and (b) does not imply substitutability.

What does it mean for an operator to "admit" another operator? I can't find a definition of it anywhere. Is there maybe a better way to phrase what is intended here? :)

**Comment by jensmaurer** [comment]
Maybe "... that does not imply ... and whose parameter type admits all..."?

**Comment by jensmaurer** [comment]
Editorial meeting: Replace "admits" with "supports". No, makes it worse.
"... for a type that is intended to support ... and for which equality need not imply substitutability."
Also for the other such phrases.
