### ISSUE TITLE
Should the PDF title be different for drafts?

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#2367]
In `std.tex` we have

````
\usepackage[pdftex,
            pdftitle={C++ International Standard},
            pdfsubject={C++ International Standard},
````

Should that be different for drafts and published standards? Drafts and WPs are _not_ the C++ IS.

**Comment by jensmaurer** [comment]
Yes. It would be great to have the actual ISO/IEC 14882:YYYY designation in the title for "released" standard, and something like "Draft ISO C++ Standard" or so otherwise.

**Comment by jensmaurer** [comment]
Editorial meeting: Have a single macro that controls whether a working draft or an IS is produced.

**Comment by Eelis** [comment]
Neat, I'll also use that draft title on eel.is/c++draft then.
