### ISSUE TITLE
What is LIA-1?

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#237]
Footnotes 210-212, 214-217, 219-223, in 18.3.2.4 [numeric.limits.members], refers to "LIA-1". This name is not mentioned anywhere else in the entire standard. Maybe the reference in footnote 205, which mentions "ISO/IEC 10967-1 Language independent arithmetic - Part 1", should say something like "hereafter referred to as LIA-1"?

**Comment by jensmaurer** [comment]
We should also add a normative reference to ISO 60559 (= IEEE 754-2008), referenced in [numeric.limits.members] p56.

**Comment by jensmaurer** [comment]
Asked LWG about opposition re: [intro.refs] extensions: http://lists.isocpp.org/lib/2016/12/1548.php

**Comment by zygoloid** [comment]
Approved by CWG.
