### ISSUE TITLE
[dcl.init] Initialization of non-class types with direct initialization with multiple arguments

### ISSUE THREAD

**Issue by Rakete1111** [cplusplus/draft#2373]
[dcl.init] doesn't seem to say what should happen if in direct initialization there are multiple arguments, i.e.:

```
int a(1, 2);
```

Direct initialization goes through [dcl.init]p17, which for direct initialization of an `int` goes to the last point, which says:

> Otherwise, the initial value of the object being initialized is the (possibly converted) value of the initializer expression. [...]

What's the "initializer expression" for direct initialization? Missing is a limitation of the number of expressions in the *expression-list* and which expression is meant I guess.

**Comment by Rakete1111** [comment]
Seems like [dcl.init.ref] and [dcl.init.string] suffer from the same problem.

**Comment by cpplearner** [comment]
Already specified by [\[dcl.init\]/14](http://eel.is/c++draft/dcl.init#14)?

> If the entity being initialized does not have class type, the expression-list in a parenthesized initializer shall be a single expression.

**Comment by Rakete1111** [comment]
Hey, I missed that! Thanks :)

Would it still make sense to clarify "initializer expression" then?

**Comment by jensmaurer** [comment]
Editorial meeting: This is fine as-is. NAD.
