### ISSUE TITLE
[dcl.init] vague wording for non-class initializer conversions

### ISSUE THREAD

**Issue by Rakete1111** [cplusplus/draft#2374]
[dcl.init]p17:

> Standard conversions ([conv]) will be used, if necessary, to convert the initializer expression to the cv-unqualified version of the destination type; no user-defined conversions are considered.

As @zygoloid said, a sequence of standard conversions can potentially be arbitrarily long (temporary materialization -> lvalue-to-rvalue -> temporary ...).

We need some some rules to clarify and/or limit what standard conversions get used and how.

**Comment by jensmaurer** [comment]
I'm not sure I understand the issue, and even if I did, this doesn't smell editorial to me.

**Comment by Rakete1111** [comment]
The issue here is that it's unclear which conversion get used. It just says "standard conversions will be used, if necessary" which doesn't say anything ("just use standard conversions"). How many? Which one in which order?

Also, technically, because there are no restrictions, we could form a sequence of standard conversions through temp mat -> l-to-r -> temp mat -> ... (just an example).

**Comment by jensmaurer** [comment]
Editorial meeting: "A standard conversion sequence (xref conv) will be used, if necessary, to convert..."
