### ISSUE TITLE
[allocator.uses.construction] Rephrase note on uses-allocator construction

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#2384]
LWG suggested rephrasing the note at the end of [allocator.uses.construction] 

Currently: 

> [Note: An error will result if `uses_allocator_v<T, Alloc>` is true but the specific constructor does not take an allocator. This definition prevents a silent failure to pass the allocator to an element. — end note]

Suggested:

> [Note: This definition prevents a silent failure to pass the allocator to an element of a type for which `uses_allocator_v<T, Alloc>` is true. — end note]

**Comment by jensmaurer** [comment]
[allocator.uses.construction] p5 seems to now have a better phrasing, based on the San Diego papers.
