### ISSUE TITLE
\tcode{min} vs. $\min$

### ISSUE THREAD

**Issue by CaseyCarter** [cplusplus/draft#2385]
The algorithm specifications - and potentially the rest of the library - use both forms for min and max. For example, `\complexity At most \tcode{min(last1 - first1, last2 - first2)} applications...` ([mismatch]) and `\complexity ... \bigoh{\min(\tcode{last1 - first1}, \tcode{last2 - first2})} applications...` ([alg.equal]). To me, it seems we should be using the "mathematical function" form for all cases that aren't actual code.

**Comment by jensmaurer** [comment]
Agreed.
