### ISSUE TITLE
"standard conversion sequence" should say "implicit conversion sequence" in some places

### ISSUE THREAD

**Issue by t3nsor** [cplusplus/draft#2388]
[over.ics.ref]/3

> Except for an implicit object parameter, for which see [over.match.funcs], a standard conversion sequence cannot be formed if it requires binding an lvalue reference other than a reference to a non-volatile const type to an rvalue or binding an rvalue reference to an lvalue other than a function lvalue.

[over.ics.ref]/4

> Other restrictions on binding a reference to a particular argument that are not based on the types of the reference and the argument do not affect the formation of a standard conversion sequence, however.

Aren't these paragraphs intended to apply to both standard and user-defined conversion sequences?

**Comment by CaseyCarter** [comment]
"user-defined conversion sequence" is not a term of art used in the Standard.

**Comment by t3nsor** [comment]
> "user-defined conversion sequence" is not a term of art used in the Standard.

Are you serious?

https://github.com/cplusplus/draft/blob/master/source/overloading.tex#L1975

https://github.com/cplusplus/draft/blob/master/source/overloading.tex#L2186

**Comment by CaseyCarter** [comment]
> Are you serious?

I was in fact serious, and in fact incorrect. I'll go back to the Library now.
