### ISSUE TITLE
harmonize "deduced to" versus "deduced as" in [temp.deduct]

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2390]
We use both "deduced to" and "deduced as" when saying what template argument was deduced for a template parameter. We should pick one and use it consistently. CWG expressed no strong opinion as to which was preferred and suggested using whichever is more common.

**Comment by jensmaurer** [comment]
"deduced to" -> 24 occurrences, but also has "deduced to be ..." fairly often
"deduced as" -> 15 occurrences

In a phrase like "X is deduced to [be] int", I think "deduced as" works better: "X is deduced as int".

**Comment by tkoeppe** [comment]
This is mostly in non-normative examples, right? "Deduced as" sounds more natural to me, too; mild preference for that.
