### ISSUE TITLE
[container.requirements.general] should use dual-range equal()

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#240]
Thanks to N3797 25.2.11 [alg.equal]/2 "If last1 - first1 != last2 - first2, return false.", we can simplify 23.2.1 [container.requirements.general] Table 96 "Container requirements"
from: "distance(a.begin(), a.end()) == distance(b.begin(), b.end()) && equal(a.begin(), a.end(), b.begin())"
to: "equal(a.begin(), a.end(), b.begin(), b.end())"
This will save 4 lines in an obnoxiously tall row. Related issue: #235

**Comment by cpplearner** [comment]
This (as well as issue #235) was also reported as a library issue http://cplusplus.github.io/LWG/lwg-defects.html#2257

**Comment by AlisdairM** [comment]
The LWG issue reference above was adopted for C++14, so this issue should be closed.
