### ISSUE TITLE
[2018-11 CWG Motion 15] P1141R2 Yet another approach for constrained declarations

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2407]
[P1141R2](http://wg21.link/p1141r2)

**Comment by tkoeppe** [comment]
Note the interaction with motion CWG-4 (#2397). We'll need to adjust the wording of that paper after we apply this one.

**Comment by burblebee** [comment]
I'll create the branch for this motion based on the paper as is, then I/someone can add the required changes as a separate edit, OK?  @tkoeppe Can you suggest the needed changes (or just apply them to the branch yourself after I commit)?

**Comment by tkoeppe** [comment]
Right, the fixup should probably appear in a separate commit (but in the same branch).

The point of contention is the grammar production *qualified-concept-name* that we are deleting in this paper, but which is being used by the earlier paper. We need to rephrase the affected sentence.

**Comment by hubert-reinterpretcast** [comment]
`->` _type-constraint_

If the _return-type-requirement_ is of the form `->` _type-constraint_, then the _type-constraint_ applies to `decltype((E))`. The immediately-declared constraint of `decltype((E))` shall be satisfied. [_Note:_ ...]

**Comment by burblebee** [comment]
@hubert-reinterpretcast Your suggested change looks correct, but I'm not sure about the wording, in particular "the type-constraint applies to decltype((E))" - can we find better wording than "applies" here?  Perhaps wording that is closer to the original text?

**Comment by hubert-reinterpretcast** [comment]
In the language of P1141:
> `->` _type-constraint_
> 
> If the _return-type-requirement_ is of the form `->` _type-constraint_, then the contextually-determined type being constrained is `decltype((E))`. The immediately-declared constraint of `decltype((E))` shall be satisfied. [_Note:_ ...]

**Comment by burblebee** [comment]
@hubert-reinterpretcast Much better, thank you!
