### ISSUE TITLE
[2018-11 LWG Motion 11] P1032R1 Misc constexpr bits

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2417]
[P1032R1](http://wg21.link/p1032r1)

**Comment by burblebee** [comment]
@zygoloid I figured we'd use the "Assignees" in the associated PRs to designate the reviewer(s), but since this commit wasn't done thru a PR, how do we know who the official reviewer is?

FWIW, I'll take this one on as the "official" reviewer...

**Comment by burblebee** [comment]
In order to review the changes I want to build the paper from the sources, but commit fda31482 isn't known to my git.  How to build the std from these sources???

**Comment by zygoloid** [comment]
@burblebee It was just pushed to my personal fork of the repository rather than this one. I've pushed it to the right place now.
