### ISSUE TITLE
[2018-11 LWG Motion 13] P0318R1 unwrap_ref_decay and unwrap_reference

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2419]
[P0318R1](http://wg21.link/p0318r1)

**Comment by jwakely** [comment]
N.B. the proposed wording in this paper is missing a semi-colon after the definition of `struct unwrap_ref_decay`.

The description for `unwrap_reference` says:

> The member typedef `type` of `unwrap_reference <T>` shall equal `X&` if `T` equals `reference_wrapper<X>`, `T` otherwise.

This should not say "equals" (see #491 and #2354)

**Comment by jwakely** [comment]
The suggested change to [pairs.spec] is 

> Let `Vi` is `unwrap_ref_decay_t <Ti>` .

That should say "be" not "is"

**Comment by jwakely** [comment]
And the changes to the Concurrency TS were not included in the motion to apply this paper, but the suggested change for the TS is wrong too.

**Comment by zygoloid** [comment]
Tomasz suggests that more instances of the pattern replaced by this paper are being introduced by other papers moved this week. We should do a pass over the draft after merging the motions to check for more places where this should be applied.
