### ISSUE TITLE
[2018-11 LWG Motion 25] P0896R4 The One Ranges Proposal

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2431]
[P0896R4](http://wg21.link/p0896r4)

**Comment by zygoloid** [comment]
From @CaseyCarter:

> The sources are at https://GitHub.com/ericniebler/stl2 in the ironically named ext/merge2std2 directory. I'm available to answer any questions that come up in the process. You'll need to search and replace cxxref and cxxiref with ref and iref, but otherwise the merge shouldn't be too horrific. The most complicated integrations are the algorithms changes, and I think that wording hasn't changed much in the IS since we pulled it in the n4750 era.

**Comment by CaseyCarter** [comment]
New information: I've added a [P0896R4](https://github.com/ericniebler/stl2/tree/P0896R4) tag at the commit from which I generated the document which was moved in plenary to reassure you Editors that you  are accessing the proper sources and not something that's been altered since.

**Comment by CaseyCarter** [comment]
Mateusz Pusz has just pointed out to me that the specification of `incrementable_traits` in [incrementable.traits]/1 includes a partial specialization:
```c++
template<class I>
struct incrementable_traits<const I>
  : incrementable_traits<remove_const_t<I>> { };
```
in which the application of `remove_const_t` is extraneous: when the pattern `const I` matches the template argument, `I` and `remove_const_t<I>` are the same type. Is it possible to correct this editorially to:
```c++
template<class I>
struct incrementable_traits<const I>
  : incrementable_traits<I> { };
```
which has the same normative effect?

The specification of `readable_traits` in [readable.traits] has an identical occurrence.

**Comment by tkoeppe** [comment]
If the original diff is based on some past commit of our repo here, then it should be possible to apply that diff to a branch at that commit and then rebase that branch to the present. There'd probably be some manual work involved when rebasing, but that should hopefully cover the bulk of the work.

**Comment by CaseyCarter** [comment]
> If the original diff is based on some past commit of our repo here

Sadly, that is *not* the case. P0896 was created primarily by copying raw sources from the standard and then modifying them in place. Maybe make a branch here, copy over the sources from the stl2 repo, and revert the portion of the resulting changes that replaces swaths of text with `[...]`?

**Comment by jensmaurer** [comment]
@burblebee: In short, the eventual goal needs to be a pull request based on a reasonably recent commit of our (not the sources') repository. The sources simply help to get there quicker, for example by being able to cut&paste large chunks of LaTeX source with lots of formatting that would otherwise need to be redone.
Yes, this particular motion will be lots of work regardless.

**Comment by zygoloid** [comment]
Problem: the wording here uses syntax that CWG motion 4 removes:
```
concept WeaklyIncrementable =
  // ...
  requires (I i) {
    // ...
    { ++i } -> Same<I>&;   // uh-oh, this isn't valid syntax any more
    // ...
  };
```

I've mailed the lib reflector for advice on how to proceed.
