### ISSUE TITLE
[dcl.type.auto.deduct] Use "immediately-declared constraint of"

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/draft#2477]
https://github.com/cplusplus/draft/blob/65a4bacd2942e0e889bf713fe8db2321ab18fc29/source/declarations.tex#L1894-L1897
This is an instance where the antecedent of "its" is not entirely clear on first reading in relation to "immediately-declared constraint", which is a new term. An immediately-declared constraint is always one "of" a type; therefore, we are talking about the immediately-declared constraint of the type deduced for the placeholder.

Suggested wording:
> For a _placeholder-type-specifier_ with a _type-constraint_, the immediately-declared constraint is that of the type deduced for the placeholder. This constraint shall be satisfied.

**Comment by jensmaurer** [comment]
I'm reading the "immediately-declared constraint" construction in clause 12 as syntactic; we often talk about "type" in the syntax analysis when we also mean "placeholder-type-specifier". So, clause 12 tells us what the immediately-declared constraints of the placeholder-type-specifier are, "its" in the quote above obviously refers to the placeholder, and the normative text says that whatever we deduce for the placeholder has to then satisfy the constraint.

**Comment by hubert-reinterpretcast** [comment]
The _immediately-declared constraint of_ any _type_ uses that _type_ in the _constraint-expression_. Clause 12 defines what the immediately-declared constraint of a type is only when given a type by other wording elsewhere. The proposed wording specifies that in auto-type deduction contexts, the type to plug in is the type deduced for the placeholder. As for [temp.param] p10, it does not talk about the deduced type; the "invented type" is the notional _dependent_ type that is still to be deduced.

**Comment by jensmaurer** [comment]
Regarding [temp.param] p10, the text reads "introduces the immediately-declared constraint of the invented type corresponding to the placeholder." So, we're still talking about what I call the syntactic level: it's the notional type "auto" that gets an immediately-declared constraint.
Back to the original question on [dcl.type.auto.deduct]: I still think the "its" refers to the "invented type" = placeholder (we might want to copy the phrasing from [temp.param] p10), we syntax-parse the rest of the declaration and remember the constraint, and when we get to the instantiation, we check the constraint. There is no specific "deduced type" at the time of parsing, so there can't be any constraints attached to it.

**Comment by hubert-reinterpretcast** [comment]
The definition of an "immediately-declared constraint" does not "give" anything to a type, so nothing "gets an immediately-declared constraint" in [temp.param] p10. The immediately-declared constraint is an expression; the application of the expression is determined by the text elsewhere. The operative word in [temp.param] p10 is "introduces". The [decl.type.auto.deduct] wording applies the _constraint-expression_ by requiring it to be satisfied--it does not redefine the term "immediately-declared constraint".

For me, the difference between the two cases is that the [temp.param] case _does_ attach constraints prior to instantiation (relevant for partial ordering), and the [dcl.type.auto.deduct] case does not.

```cpp
template <typename T> concept C = true;

template <auto x, typename U> struct A { };
template <C T, T x, C U> struct A<x, U> { struct Happy; };
template <C auto x, typename U> struct A<x, U> { };

typename A<0, int>::Happy *p = 0; // okay
```

We only apply the constraint after the deduction in [dcl.type.auto.deduct], so I see not issue with asking for the _constraint-expression_ written in terms of the deduced type. The immediately-declared constraint of a type `T`, is a _constraint-expression_ written in terms of `T`. Saying that `T` is the placeholder type means, to me, that we have an expression written with a placeholder type in the style of `static_cast<auto>(0)`.

**Comment by jensmaurer** [comment]
Editorial meeting:
- phrase is: "The immediately-declared constraint of type-constraint for type..."

**Comment by tkoeppe** [comment]
Example: The defining sentence will become:

> This constraint-expression `E` is called the *immediately-declared constraint* of `Q` for `T`.
