### ISSUE TITLE
Link in [expr.call]/6 is probably wrong. It should be [expr.reinterpret.cast] instead of [dcl.link].

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#2482]
[[expr.call]/6](http://eel.is/c++draft/expr.call#6):

Calling a function through an expression whose function type is different from the function type of the called function's definition results in undefined behavior ([[dcl.link]](http://eel.is/c++draft/dcl.link)).

[[expr.reinterpret.cast]/6](http://eel.is/c++draft/expr.reinterpret.cast#6) :

A function pointer can be explicitly converted to a function pointer of a different type. [ Note: The effect of calling a function through a pointer to a function type ([dcl.fct]) that is not the same as the type used in the definition of the function is undefined. — end note ] Except that converting a prvalue of type “pointer to T1” to the type “pointer to T2” (where T1 and T2 are function types) and back to its original type yields the original pointer value, the result of such a pointer conversion is unspecified. [ Note: See also [conv.ptr] for more details of pointer conversions. — end note ]

**Comment by CaseyCarter** [comment]
Related: is it intended that calling a`noexcept` function through a pointer-to-non-`noexcept`-function results in undefined behavior?

**Comment by jensmaurer** [comment]
@jabelloc, [dcl.linik]p1 says "Two function types with different language linkages are distinct types even if they are otherwise identical." So, the cross-reference points at one possible (and not super-obvious) way how you can screw up.
@CaseyCarter, that seems to be a defect in the wording. I'd suggest to ask for a core issue on the CWG reflector.

**Comment by CaseyCarter** [comment]
> I'd suggest to ask for a core issue on the CWG reflector.

Done. Apologies for injecting obviously-non-editorial questions in the editorial issue tracker. I should know better.

**Comment by cpplearner** [comment]
Per [\[basic.link\]/11](http://eel.is/c++draft/basic.link#11) it's ill-formed NDR to declare the same function with different types. One doesn't even need to invoke

**Comment by jensmaurer** [comment]
Editorial meeting:
- Remove the dcl.link cross-reference.
- expr.reinterpret.cast needs a cross-reference to expr.call at the end of the first note.
