### ISSUE TITLE
[basic.fundamental] boolean note nitpick

### ISSUE THREAD

**Issue by jfbastien** [cplusplus/draft#2483]
Booleans can behave as neither true nor false, but can also behave as both true and false.
Suggested wording here: https://github.com/cplusplus/draft/pull/2438#discussion_r232839704

**Comment by jensmaurer** [comment]
The suggestion is to add "or might cause it to behave as if it is both \tcode{true} and \tcode{false}" to the corresponding footnote.

Opinion: I don't think attempting to inject more precision in a non-normative comment on possible results of undefined behavior is worthwhile. Actually, removing that footnote would be fine, given that the Undefined Behavior dragon is already out of the box here.

**Comment by jfbastien** [comment]
The Undefined Behavior Dragon might or might not be out of the box. It's up to the Dragon to decide whether it'll come out of the box, and whether you'll be allowed to observe it come out of the box.

Agreed we can just remove the note.
