### ISSUE TITLE
[expr.prim.lambda.capture] CWG 2378: Resolve FIXME regarding ellipses in captures

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#2493]
I was looking at ellipses and noticed this FIXME:
https://github.com/cplusplus/draft/blob/f1fabf220edaa8f042e897f2be1712afc406d707/source/expressions.tex#L1910

I'm not quite sure what it's saying, or if there's really something wrong, but if there *is* something wrong, perhaps it's fixable. :)

**Comment by timsong-cpp** [comment]
That's a core issue about how you spell reference init-capture packs.

**Comment by Eelis** [comment]
Oh I see! I guessed it was editorial. Feel free to close in that case.

**Comment by jensmaurer** [comment]
This is [CWG 2378](http://wg21.link/cwg2378)
