### ISSUE TITLE
clean up [algorithms] source code

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2509]
From @jensmaurer in #2501:

> The "algorithms" clause still has a lot of troff-era formatting where we start a new line for each non-prose item, such as \tcode{first}. And we have a lot of these. This makes for very long source code. Suggestion: Between the mailings, have me reformat the source code in a no-visual-changes diff.

**Comment by CaseyCarter** [comment]
Having recently spent a lot of time in [algorithms], +1. The "vertical" layout makes the source less readable, and makes it painful to correlate the source with the rendered text.
