### ISSUE TITLE
formatting for "E" variant marker in [algorithms]

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2511]
@jensmaurer wrote on #2501:

> The algorithms now define a placeholder $E$ to deal with the subvariants of an algorithm (with/without comparator etc.) Very often, this $E$ is an actual C++ expression, so (per our standing rules) should be \tcode{E}. Except for a very few places where we need a parameter and $E(x)$ is used. In the latter cases, \placeholder{E} would be appropriate (similar to the other description meta-functions such as INVOKE). However, using \tcode in one situation and \placeholder in the next seems sub-optimal, too.

**Comment by jensmaurer** [comment]
Editorial meeting:
- Formatting E as math-mode $E$ is correct.
- We should consider replacing \placeholder with math-mode in similar situations.
