### ISSUE TITLE
revise section labels introduced by ranges

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2513]
In particular, [range] should be [ranges] for consistency with the rest of the library. There are probably other opportunities for cleanups here.

**Comment by jensmaurer** [comment]
We consistently have [range.foo.bar] for subclauses. Do you want them renamed to [ranges.foo.bar] as well?

**Comment by zygoloid** [comment]
Use your judgment for the subclause labels. [range.general] should be renamed, but [range.access], [range.primitives], etc seem fine as-is to me. Maybe [range.range] should be [ranges.range].

**Comment by jensmaurer** [comment]
Thanks. Most labels look reasonable, but there are some very long ones that I'd like to shorten. E.g. "iterator" -> "iter" and "operations" -> "op"
