### ISSUE TITLE
consider renaming [*.erasure] to [*.erase]

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2516]
We'd need to move [string.erase] out of the way first.

However, reserving [containername.erase] for a member named erase, and using a different name for the non-member form, seems preferable. Maybe [*.erase.nonmem] for the new ones?

**Comment by jensmaurer** [comment]
[*.erase.nonmem] seems a bit long...

**Comment by jensmaurer** [comment]
Editorial meeting:
- [string.erase] stays as-is.
- Going for [*.string.nonmem] is worse than [*.erasure].
- Net result: Do nothing.
