### ISSUE TITLE
[util.smartptr.hash] at wrong level

### ISSUE THREAD

**Issue by W-E-Brown** [cplusplus/draft#252]
At the moment, [util.smartptr.hash] "Smart pointer hash support" is numbered 20.8.2.6, which means it is a subclause of [util.smartptr] "Shared-ownership pointers".

However, [util.smartptr.hash] speaks to hash support for `unique_ptr` as well as `shared_ptr`.

I recommend that either:
1. [util.smartptr.hash] be repositioned to become, say, 20.8.3, or
2. the section be deleted and its two paragraphs become subclauses of their respective smart pointer sections.

**Comment by zygoloid** [comment]
Decision: remove [util.smartptr] heading and move all of its contents up one level.
