### ISSUE TITLE
Missing template declaration in [array.tuple]

### ISSUE THREAD

**Issue by mclow** [cplusplus/draft#2553]
In [array.tuple] (in N4778 and 4788), we see:
```
template<class T, size_t N>
     struct tuple_size<array<T, N>> : integral_constant<size_t, N> { };

tuple_element<I, array<T, N>>::type
```
I'm thinking that the `tuple_element` bit should look more like this:
```
template<class T, size_t N>
     tuple_element<I, array<T, N>>::type
```

**Comment by jwakely** [comment]
It needs `size_t I` as well.

I think this style of presentation is intentional, not a mistake. That doesn't make it good though.

**Comment by jwakely** [comment]
See [pair.astuple] and [variant.helper] as well.

**Comment by tkoeppe** [comment]
Looks like this has been broken size the first commit.

**Comment by tkoeppe** [comment]
I think we should add the missing template head to all those cases (the variant-values `variant_alternative` and pair's and array's `tuple_element`.

**Comment by jensmaurer** [comment]
But what does it mean? `tuple_element<I, array<T, N>>::type` is not valid C++ either way, if `type` is in fact a typedef: You can't have out-of-line definitions of member typedefs.

**Comment by jensmaurer** [comment]
Duplicate of #2786.
