### ISSUE TITLE
[atomics.types.operations]/20 Awkward "E.g." at start of sentence

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#2555]
Consider the "E.g. " below:
![image](https://user-images.githubusercontent.com/22357/49439174-a2af9e80-f7c0-11e8-8ecb-206be583b4af.png)
Some thoughts:
- The space between "E.g." and "list" seems a bit wide, is it possible LaTeX is generating a sentence-space? Should maybe "\ " be used? (Or maybe even "~", to prevent a line break.)
- In the vast majority of cases, the document actually has a comma after "e.g.". Maybe that's the way to go here, too?
- Starting a sentence with the "e.g." abbreviation could be considered poor style to begin with. Maybe nicer to just say "For example,"

**Comment by tkoeppe** [comment]
It's entirely possible that capital "E.g." isn't recognised as a magic
exception and sentence spacing is applied afterwards. The space should be
escaped like `E.g.\ `.

**Comment by Eelis** [comment]
Ok cool, does that also apply to the space between "P.J." and "Plauger" at https://github.com/cplusplus/draft/blob/1dc0c7d5f6d1ac740bd40b72953a397a8cdca792/source/intro.tex#L638 ?

**Comment by tkoeppe** [comment]
Yes, very much so. Any mid-sentence period is suspect. (I think exceptions
exist for some well-known forms.)

**Comment by Eelis** [comment]
Ok great, thanks! I'll make a patch. This will help cxxdraft-htmlgen's sentence-splitting, too.

**Comment by Eelis** [comment]
Closing, see #2557.
