### ISSUE TITLE
Consider formatting ranges with math brackets

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#2556]
`\Range` and `\range` currently format the whole range, including the brackets and comma, as C++ code:

    \newcommand{\Range}[4]{\tcode{#1#3,\penalty2000{} #4#2}}
    \newcommand{\range}[2]{\Range{[}{)}{#1}{#2}}

But that's kinda weird, because something like `[eback(), gptr())` isn't actually a syntactically well-formed C++ code fragment; only the `eback()` and `gptr()` parts are. So I think it might make more sense to format the brackets (and comma) as math. What do you think?

**Comment by tkoeppe** [comment]
It's a trade-off. Using code font gives the thing a uniform look, and we do actually *define* the meaning of the notation. So it's not outright wrong. It's similar to how we use code font for conceptual placeholders, e.g. `T` when referring to an invented type.

**Comment by Eelis** [comment]
It does make sense, it's just a bit unfortunate for cxxdraft-htmlgen that the same commands/environments are used for C++ code and non-C++ code, because cxxdraft-htmlgen should only highlight C++ code as C++. I currently maintain a [patch](https://github.com/Eelis/draft/commit/1cbc68b204fda614b9368f7c429544dd7dfadadb) that introduces `\noncxxtcode` and changes \Range to

    \newcommand{\Range}[4]{\noncxxtcode{#1}\tcode{#3,\penalty2000{} #4}\noncxxtcode{#2}}

but it's not ideal. :)

**Comment by Eelis** [comment]
Interestingly, there's a bunch of places in numerics.tex that don't use the range macros but instead use

    $\bigl[ ... , ... \bigr)$

[Example](https://github.com/cplusplus/draft/blob/master/source/numerics.tex#L5888)

Probably an oversight, but I'm reluctant to submit a patch to replace these with uses of the range macros, because I love the math brackets more than I hate the inconsistency. ;)

**Comment by jensmaurer** [comment]
Editorial meeting: Try the looks of two center dots as separator, with math brackets. Do not proceed without @tkoeppe's input.

**Comment by Eelis** [comment]
Cool, thanks for the decision! I'd be happy to submit a patch to move away from \tcode for brackets and comma.

The idea of using two center dots as separator surprises me a little bit though, as it doesn't match conventional mathematical interval notation (when combined with round and square brackets to indicate inclusive-ness of the bounds). What would be the motivation for changing from comma to two center dots? :)
