### ISSUE TITLE
struct/class mismatch for `char_traits`

### ISSUE THREAD

**Issue by mclow** [cplusplus/draft#2561]
in [iosfwd.syn], `char_traits` is declared as a class.
```
template<class charT> class char_traits;
template<> class char_traits<char>;
template<> class char_traits<char8_t>;
template<> class char_traits<char16_t>;
template<> class char_traits<char32_t>;
template<> class char_traits<wchar_t>;
```

In [char.traits.require] and [char.traits.specializations], they're defined as structs:
`template<class charT> struct char_traits;`
and
```
template<> struct char_traits<char>;
template<> struct char_traits<char8_t>;
template<> struct char_traits<char16_t>;
template<> struct char_traits<char32_t>;
template<> struct char_traits<wchar_t>;
```

Since everyone implements them as structs, I think that [iosfwd.syn] should be changed.

**Comment by jensmaurer** [comment]
Not that the difference would actually matter.

**Comment by mclow** [comment]
Actually, on at least one compiler (MSVC) it does matter, and clang will warn if you declare something as a `class` and then later define it as a `struct` if you use `-Wmismatched-tags`

**Comment by mclow** [comment]
Thanks for the prompt resolution.
