### ISSUE TITLE
[iterator.concept.readable]/2 parenthesized clarification seems like a note

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2567]
https://github.com/cplusplus/draft/blob/38eb5e5e6209be9fce69e39ff721cd587791788e/source/iterators.tex#L1201-L1204

**Comment by jensmaurer** [comment]
Where is the normative statement that leads to the "indirectly required to be valid" conclusion?

**Comment by johelegp** [comment]
https://github.com/cplusplus/draft/blob/38eb5e5e6209be9fce69e39ff721cd587791788e/source/iterators.tex#L62-L63

There, which is required to be valid in in its definition:
https://github.com/cplusplus/draft/blob/38eb5e5e6209be9fce69e39ff721cd587791788e/source/iterators.tex#L1192

But, didn't using concepts in alias templates actually not constrain the template arguments?
