### ISSUE TITLE
20.7.9.1 [allocator.members] should use addressof()

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#257]
N3797 20.7.9.1 [allocator.members]/2 and /3 say:

Returns: The actual address of the object referenced by x, even in the presence of an overloaded operator&.

It would be less verbose to say:

Returns: std::addressof(x).

**Comment by AlisdairM** [comment]
This is now [depr.default.allocator]p2, which looks like it could otherwise use a little love for formatting of fonts.
