### ISSUE TITLE
[stream.iterators] Requirements mixed with description

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2587]
The descriptions for the istream(buf) iterators have requirements mixed with them, which should go after the class synopsis.

**Comment by johelegp** [comment]
https://wg21.link/P0738 takes care of the editorial changes for `istream_iterator` described here and more. The presentation of `istreambuf_iterator` suffers of similar problems as those outlined in the proposal. For example, the description states: ["If the end of stream is reached \[...], the iterator becomes equal to the end-of-stream iterator value."](http://eel.is/c++draft/istreambuf.iterator#1.sentence-4). But that isn't reflected on the detailed specifications.

**Comment by jensmaurer** [comment]
P0738R2 was applied after Kona.

If you feel there are any issues in this area remaining, please open a new issue.
