### ISSUE TITLE
[range.range] Requirement marked wrongly

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2589]
https://github.com/cplusplus/draft/blob/0155d2046eacb32d60bcc49cebffa34e97b4818c/source/ranges.tex#L691
should be marked with
https://github.com/cplusplus/draft/blob/0155d2046eacb32d60bcc49cebffa34e97b4818c/source/concepts.tex#L58

**Comment by jensmaurer** [comment]
The marking seems correct. p3.3 in the text that follows requires "equality-preserving" when the end result is a forward iterator.

**Comment by johelegp** [comment]
Yeah, I'm aware. I'm just being pedantic because what I believe to be normative text requires marking
https://github.com/cplusplus/draft/blob/0155d2046eacb32d60bcc49cebffa34e97b4818c/source/ranges.tex#L691
with `// not required to be equality-preserving`. p3.3 would then be an additional requirement for when it is required to be equality-preserving, which is the default.

**Comment by johelegp** [comment]
p3.3 indeed adds the additional requirement, but http://eel.is/c++draft/concepts.equality#4 says that all are equality-preserving unless it uses _this_ comment, and doesn't give leeway to waive the requirement some other way as usually done with the phrase "unless stated otherwise".

**Comment by johelegp** [comment]
"sometimes equality-preserving" is true for all expressions "not required to be equality-preserving". Perhaps "conditionally required to be equality-preserving" is a better fit. This seems like LWG material. Should I open an issue?
