### ISSUE TITLE
[ranges] Different uses of "common range"

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2590]
[range.req.general] defines (not in the sense of defining a term, like _swapable_) common range (which [common.iterator] uses, again, not as a term), and the subclause title for [range.refinements] uses it in another sense (and it even defines `CommonRange`!)
https://github.com/cplusplus/draft/blob/a3ab84cc0221e73b2acb870873b3bfffeb35b414/source/iterators.tex#L4551-L4555
https://github.com/cplusplus/draft/blob/a3ab84cc0221e73b2acb870873b3bfffeb35b414/source/ranges.tex#L669-L671
https://github.com/cplusplus/draft/blob/a3ab84cc0221e73b2acb870873b3bfffeb35b414/source/ranges.tex#L898
https://github.com/cplusplus/draft/blob/a3ab84cc0221e73b2acb870873b3bfffeb35b414/source/ranges.tex#L949-L962

**Comment by johelegp** [comment]
So there might be 2 problems here:
- The lack of the definition of "common range", which `CommonRange` represents, and
- the use of "common range" in the title for [range.refinements] with another meaning.

**Comment by johelegp** [comment]
Just to be clear, by definition, models of `ForwardRange` also model `CommonRange`, but [range.refinements] also specifies `OutputRange` and `InputRange`, for which this many not be the case. It's use of "common" is the same as that of [alg.req].
https://github.com/cplusplus/draft/blob/a3ab84cc0221e73b2acb870873b3bfffeb35b414/source/iterators.tex#L2248-L2255

**Comment by jensmaurer** [comment]
I'm seeing the possible confusion potential in the phrasing of the heading "Common range refinements", but I'm not seeing the other issues. For once, CommonRange does not mention "common range" at all. Plus, the meaning of CommonRange seems to be the same as that intended for "common range", i.e. whether the iterator and the end marker are of the same type or of different types.
Alternative suggestion for the heading: "Other range refinements"
(The concepts that precedes this subclause are also range refinements.)

**Comment by johelegp** [comment]
If there's any other issue, it would be the use of "common range" without a centralized definition. All places it's used at define it.

**Comment by jensmaurer** [comment]
Let's fix the heading.
