### ISSUE TITLE
[basic.lookup.classref]p1 CWG 682: Should allow alias-templates followed by '<'

### ISSUE THREAD

**Issue by RealLitb** [cplusplus/draft#2593]
The text currently renders this ill-formed, because "c.U" in the context of the postfix expression doesn't find 'U' as a class-template, but alias template:

```
   struct C { typedef C type; int dummy; };

   template<typename>
   using U = C;

   int main() {
       C c;
       c.U<void>::dummy = 0;
   }
```

GCC and Clang implement the obvious, so I suspect this can be fixed editorially (stealing the wording used for "only-templates-that-yield-types::something" lookup).

**Comment by jensmaurer** [comment]
@RealLitb, Could you please edit your submission so that the angular brackets are visible?

**Comment by jensmaurer** [comment]
Asked CWG whether to proceed editorially here; this feels like a normative change: http://lists.isocpp.org/core/2018/12/5331.php

**Comment by jensmaurer** [comment]
A more involved example with a dependent object expression shows implementation variance. This is not editorial.

**Comment by johelegp** [comment]
> [Accepted as a DR at the July, 2019 meeting.]
