### ISSUE TITLE
[mismatch] LWG 3178: std::mismatch is missing an upper bound

### ISSUE THREAD

**Issue by mclow** [cplusplus/draft#2611]
https://cplusplus.github.io/LWG/issue3178
This was opened by @geoffromer , but @Dani-Hub thought it might be editorial.

**Comment by CaseyCarter** [comment]
FWIW, as the last person to touch [mismatch] I can verify that the PR clarifies the intent of the existing wording.

**Comment by Dani-Hub** [comment]
I will make a note to LWG 3178 regarding these editorial changes.
