### ISSUE TITLE
[iterator.container,range.prim] "range" vs. "container and/or view"

### ISSUE THREAD

**Issue by CaseyCarter** [cplusplus/draft#2614]
Could we editorially merge [iterator.container] into [iterator.range], and likewise merge [range.prim] into [range.access]? I defy anyone to explain to me the difference between "range" and "container and/or view".

Should I simply prepare a PR to do so, and we can decide on the basis of the proposed wording changes whether or not the change needs LWG approval?

**Comment by jensmaurer** [comment]
Both changes sound good to me; please prefix the subclause headings in [range.prim] and [iterator.container] with `ranges::` for consistency with the respective receiving subclause. Feel free to prepare a pull request.
