### ISSUE TITLE
[range.adaptors] Generators bundled together with the adaptors

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2615]
At http://ericniebler.com/2018/12/05/standard-ranges/, right before the "Range Adaptors" section is "Range Generators." [range.adaptors], which is supposed to describe _range adaptors_, also bundles these generators. You'll notice from the description of the `view::X` objects that those for the adaptors are described as denoting range adaptor objects, while those of the generators denote customization point objects. Shouldn't the generators live in their own subclause?

**Comment by jensmaurer** [comment]
Let's formulate this a bit harsher: The intro sentence of [range.adaptors] says "This subclause defines range adaptors, which are utilities that transform a Range into a View with custom behaviors."
This is a lie; the subclause also contains iota_view, single_view, and empty_view, which perform no such transformation.
I would be ok with introducing a new subclause "Range generators" with these, but we should ask around.
@CaseyCarter, any opinion here?

**Comment by CaseyCarter** [comment]
> Wouldn't "View factories" be more descriptive?

I agree that "`View` factories" would be more precise.
