### ISSUE TITLE
[expr.prim.id.dtor] Comment in example reflects lexing misunderstanding

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#2630]
The example in [[expr.prim.id.dtor]/3](http://eel.is/c++draft/expr.prim.id.dtor#3) shows the following line of code:

    0.T::~T(); // error: 0. is a floating-point literal ([lex.fcon])

However, contrary to what the comment suggests, I believe `0.` does not appear as a floating-point literal on this line. I believe that what really appears on this line is the [pp-number](http://eel.is/c++draft/lex.ppnumber#nt:pp-number) token `0.T` (which is not a valid floating literal token).

A very similar case is described in [[lex.pptoken]/4](http://eel.is/c++draft/lex.pptoken#4.sentence-1):
> The program fragment 0xe+foo is parsed as a preprocessing number token (one that is not a valid floating or integer literal token)"

**Comment by jensmaurer** [comment]
It seems this is a floating-point literal "0." with a _ud-suffix_ "T" [lex.ext], which happens not to exist. At least that's what gcc tells me, and it seems a reasonable outcome.

**Comment by Eelis** [comment]
Ah, but if you agree that the `0.T` (with the T) is a user-defined-floating-literal, then you should also agree that it's misleading for the comment to suggest that `0.` (without the T) on the line is a floating-point literal, because in that case it's actually merely a partial token, and only complete tokens are turned into literals.
