### ISSUE TITLE
[iterator.requirements.general] past-the-end/dereferenceable/singular iterators are not defined

### ISSUE THREAD

**Issue by morinmorin** [cplusplus/draft#2632]
Past-the-end/dereferenceable/singular **values** are defined in [iterator.requirements.general] p7, but past-the-end/dereferenceable/singular **iterators** are not defined.
Would it be better to have "iterators having XXXX values are called XXXX"?

Edit: The problem is that these adjectives for iterators are used without definition. For example, 
- [vector.capacity] p11: … as well as the past-the-end iterator.
- [iterator.requirements.general] p11: … `i` is dereferenceable.
- [iterator.requirements.general] p15: … an iterator that may be singular.

**Comment by CaseyCarter** [comment]
I don't see this as problematic: it's conventional with value-semantic object types to refer to objects as having properties when we actually mean that the value of the object has that property. Given:
```c++
int i = 42;
```
I think the statement "`i` is even" clearly conveys the meaning "`i` has the value `42` which is even."

**Comment by morinmorin** [comment]
I thought that defining 

- past-the-end iterators
- dereferenceable iterators
- singular iterators

and putting them in the index may improve the readability of the Standard.

**Comment by CaseyCarter** [comment]
All three terms are defined for iterator values in [[iterator.requirements.general]/7](https://wg21.link/iterator.requirements.general#7), although not properly indexed. Would it suffice to index those terms?

**Comment by morinmorin** [comment]
> Would it suffice to index those terms?

Yes, that works.

- While the term "invalid pointer value" has the two index entries,
  - invalid pointer value
  - value -> invalid pointer
  
  I think it is more useful if the term "xxxx iterator value" has the following index entries
  - xxxx iterator value
  - iterator -> xxxx iterator value (instead of value -> …)

- In the Standard (unlike the SGI doc), singular iterator values are only used in "22.3 Iterator Requirements". Thus, since the term "singular iterator value" does not meet [this](https://github.com/cplusplus/draft/issues/2072#issuecomment-395523704),
  > As a rule of thumb, if a term is local to a subclause, do not make it italics and do not index it
  
  it seems better not to index it.

**Comment by jensmaurer** [comment]
The linked pull request will consistently use "xxxx iterator" in the index, not "xxxx iterator value", following the argument of @CaseyCarter. However, the actual definitions are not changed.
