### ISSUE TITLE
[expr.unary.op]/3: the value of a pointer should be "pointer to", not "address of"

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#2645]
http://eel.is/c++draft/expr.unary.op#3.sentence-4:
> Otherwise, if the type of the expression is T, **the result has type “pointer to T”** and is a prvalue that is **the address of the designated object** ([intro.memory]) or a pointer to the designated function.

1. «The _result_ of a prvalue is the value that the expression stores into its context.» ([basic.lval]). The lvalue can be of type `T`, but denote an object of type `U`, so the type of the result of applying the address-of operator to it will be `pointer to U`, not `pointer to T` (and I'm unsure if we even can talk about the type of the result. The result is "pointer to object", the type of the prvalue is `pointer to T`, but I don't think this makes sense to say that the type of the result is `pointer to U`). `pointer to T` is the type of the prvalue, not its result.
2. the prvalue has the value "pointer to the designated object or function", not "the address of the designated object or a pointer to the designated function."

The note following the sentence above (http://eel.is/c++draft/expr.unary.op#3.note-1) also needs a fix:
> In particular, the address of an object of type “cv T” is “pointer to cv T”

I don't think that addresses have types.

**Comment by jensmaurer** [comment]
I don't follow item 1, but I think item 2 and the note could use some embellishment to properly fit into [basic.compound],.

**Comment by jensmaurer** [comment]
Editorial meeting: Point 1 is wrong; for the rest, my suggestion is good.
