### ISSUE TITLE
revert e58439b (fix to "usable in constant expressions") if not fixed at Kona

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2651]
e58439b is not a complete fix for this issue, and we should let CWG fix it properly. If it's not fixed in the Kona motions, revert e58439b so that the draft text matches the (known-broken) wording as moved at San Diego.

**Comment by hubert-reinterpretcast** [comment]
@jensmaurer, I cannot set the milestone; however, I believe that this is for https://github.com/cplusplus/draft/milestone/14.

**Comment by jensmaurer** [comment]
@hubert-reinterpretcast: Milestone assigned.

**Comment by zygoloid** [comment]
Fixed in 41853024e5e6fcd5feb496f64767d2888d76154f.
