### ISSUE TITLE
The hyperlink [stmt.if] is wrong in [dcl.spec.auto]/3

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#2659]
The hyperlink [stmt.if] in [[dcl.spec.auto]/3](http://eel.is/c++draft/dcl.spec.auto#3) should be replaced by 
[[dcl.type.auto.deduct]](http://eel.is/c++draft/dcl.spec.auto#dcl.type.auto.deduct).

**Comment by tkoeppe** [comment]
Why do you think so?

Isn't the purpose of the link to explain "discarded `return` statement"?

**Comment by jwakely** [comment]
Yes. That paragraph is a brief summary of the rules in [dcl.type.auto.deduct], so doesn't need to link to it. The reference to [stmt.if] is because it defines discarded return statement.
