### ISSUE TITLE
Meaning of "Return Type" not specified in [structure.specifications]

### ISSUE THREAD

**Issue by K-ballo** [cplusplus/draft#266]
The current draft contains 14 occurrences of a `\returntype` clause. That clause is not covered by **17.5.1.4/3** [structure.specifications].

**Comment by jwakely** [comment]
(All occurrences are in Clause 30)

**Comment by jensmaurer** [comment]
Asked lwgchar@gmail.com to open an LWG issue.

**Comment by jensmaurer** [comment]
LWG 2819
http://cplusplus.github.io/LWG/lwg-active.html#2819
