### ISSUE TITLE
[intro.execution] CWG2431: Destruction of a temp. object bound to a reference is not a full-expression?

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#2664]
http://eel.is/c++draft/intro.execution#def:full-expression:
> A *full-expression* is 
> — an invocation of a destructor generated at the end of the lifetime of an object other than a temporary object ([class.temporary]), or

Here is an example
```c++
void foo()
{
    const auto& rk = Klass{};
    Klass k;
    // ...
    // generated invocation `k.~Klass()` is a full-expression
    // generated invocation `rk.~Klass()` is not a full-expression?
}
```
I think it is intended to be a full-expression, so the Standard should say something like
> other than a temporary object **whose lifetime was not extended**

**Comment by jwakely** [comment]
If you have multiple lifetime-extended temporaries, do their destructors produce multiple full-expressions?

```
{
    const auto& rk = Klass{};
    const auto& rk2 = Klass{};
    // ...
}
```

The current wording seems to allow the destructor invocations `rk.~Klass()` and `rk2.~Klass()` to be part of the same full-expression (though it could be clearer whether that is intended, or whether your reading is correct).

**Comment by languagelawyer** [comment]
> If you have multiple lifetime-extended temporaries, do their destructors produce multiple full-expressions?

If I have multiple variables, do their destruction produce multiple full-expressions?

**Comment by jwakely** [comment]
Yes, but the destruction of temporary objects doesn't have to produce multiple full-expressions, so there's no inherent requirement that destruction of objects happens in separate full-expressions.

**Comment by languagelawyer** [comment]
Ok, the difference could be intended, lets wait what others will say.

**Comment by jensmaurer** [comment]
The text is clearly wrong (a lifetime-extended temporaries should be treated as-if it were a non-reference variable), but is the fix editorial?

**Comment by zygoloid** [comment]
Given the ambiguity Jonathan mentioned, I think we should process this as a core issue.

**Comment by languagelawyer** [comment]
[[stmt.jump]/2](http://eel.is/c++draft/stmt.jump#2) orders destructors invocations (TBH, storage duration of lifetime-extended temporary objects is not specified yet ([CWG1634](http://wg21.link/cwg1634))) and [[intro.execution]/11](http://eel.is/c++draft/intro.execution#11) prohibits function executions interleaving.
So, is there any difference between multiple lifetime-extended temporaries destructor invocations being or not being a subexpression of one full-expression?

**Comment by jensmaurer** [comment]
@zygoloid, @jwakely: What would the effective difference be between "one full-expression for destruction of several lifetime-extended temporaries" vs. "one full-expression each"? We can't have temporaries in default arguments for destructors.

**Comment by languagelawyer** [comment]
@jensmaurer the difference would be observable if a destructor throws an exception.

**Comment by jensmaurer** [comment]
@languagelawyer, sorry, maybe it's too early in the morning for me, but could you please be more specific?

**Comment by languagelawyer** [comment]
@jensmaurer if there are several temporary object destructor invocations in one full-expression and one of them throws an exception, it will finish evaluating the rest of the full-expression and could left some destructors not invoced. But if each destructor invocation is a full-expression and one of them thows, the following destructors still would be called during stack unwinding.

**Comment by jensmaurer** [comment]
@languagelawyer: Such behavior would be at odds with [stmt.jump] p2: Even if a destructor throws an exception, you still need to execute the rest of the destructors, now in the context of stack unwinding [except.ctor].

**Comment by languagelawyer** [comment]
@jensmaurer hm, indeed. Then I also don't see a difference.

**Comment by jwakely** [comment]
I'm not aware of any way the difference is observable, so maybe it can be changed editorially (or maybe it doesn't need to change at all). My original comment was just to say that "it is intended to be a full-expression" may need additional justification, as it's not obvious to me whether that really is the intention.

**Comment by languagelawyer** [comment]
Excuse my curiosity, was this submitted to CWG? I don't see a comment like https://github.com/cplusplus/draft/issues/2846#issuecomment-489313227 here.
