### ISSUE TITLE
Can we find a better name for "promoted arithmetic type"?

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#2665]
The term "promoted arithmetic type" is defined by [over.built]p2 to mean "promoted integral types and *all* floating-point types". It seems suboptimal to say that `float` is a "promoted arithmetic type" when it is subject to (floating-point) promotion to `double`.

**Comment by jensmaurer** [comment]
Is this sufficiently editorial? What's the new name?

**Comment by timsong-cpp** [comment]
I don't have a great alternative name right now (or I'd have suggested it). Given that the term appears to be only used four times and all in this subclause, perhaps we can just substitute the definition in those uses and remove the term altogether?

**Comment by jensmaurer** [comment]
Editorial meeting: Not enthusiastic about a change in this area. Go with Tim's expansion suggestion for now.
