### ISSUE TITLE
"Syntactic" circularity between [expr.add]/4 and [expr.sub]/1?

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#2670]
[expr.sub]/1 defines subscripting through pointer arithmetic
> The expression `E1[E2]` is identical (by definition) to `*((E1)+(E2))`

[expr.add]/4, defining pointer arithmetic, uses syntax looking like subscripting
> … if P points to element x[i] of an array object x with n elements,81 the expressions P + J and J + P (where J has the value j) point to the (possibly-hypothetical) element x[i+j]…

Not that `x[i]` necessarily means subscripting expression, but I think it is still better to replace such constructs with plain English wording like
> i-th element of an array object `x`

instead of
> element `x[i]` of an array object `x`

**Comment by jensmaurer** [comment]
Except that we index arrays zero-based, but English does not allow us to talk about the 0-th element.

**Comment by W-E-Brown** [comment]
> On Mar 10, 2019, at 2:56 PM, Jens Maurer <notifications@github.com> wrote:
> 
> ...  English does not allow us to talk about the 0-th element.
> 

Perhaps it does, after all.  According to my Mac's dictionary:

> zeroth |ˈzi(ə)rōTH, ˈzēˌrōTH| 
> adjective
> immediately preceding what is regarded as first in a series.
> ORIGIN late 19th cent.: from zero <x-dictionary:r:m_en_us1307976:com.apple.dictionary.NOAD> + -th1 <x-dictionary:r:m_en_us1298080:com.apple.dictionary.NOAD>.
Please see also https://www.wordnik.com/words/zeroth.

**Comment by jensmaurer** [comment]
Editorial meeting: We're still unhappy with "i-th", at least without further context. Say "array element i of array object x" instead, taking "array element" as a term of art.
