### ISSUE TITLE
[expr.sizeof][expr.alignof][expr.unary.noexcept] What is a constant?

### ISSUE THREAD

**Issue by Rakete1111** [cplusplus/draft#2671]
[expr.sizeof]p6:

> The result of sizeof and sizeof... is a constant of type std::size_­t.

[expr.alignof]p2:

> The result is an integral constant of type std::size_­t.

[expr.unary.noexcept]p2:

> The result of the noexcept operator is a constant of type bool and is a prvalue.

I can't find a definition of constant anywhere. It seems like it is supposed to mean an *integral constant expression*.

Also the first two miss saying what the value category of the result is.

**Comment by languagelawyer** [comment]
Lotsa operators miss requirements for value category of operands and don't specify value category of the resulting expression. It was noticed long time ago https://groups.google.com/a/isocpp.org/d/msg/std-discussion/sjK_KoeD3xo/a55uY-Q4q5kJ

**Comment by jensmaurer** [comment]
Let's fix these three situations as a first step.
