### ISSUE TITLE
Harmonize ", inclusive" and "(inclusive)" spelling

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2672]
CWG in Kona: Both are used. Prefer "(inclusive)". Also address "inclusive" (without punctuation).

**Comment by W-E-Brown** [comment]
> On Feb 18, 2019, at 6:37 PM, Jens Maurer <notifications@github.com> wrote:
> 
> CWG in Kona: Both are used. Prefer "(inclusive)". Also address "inclusive" (without punctuation.
> 

Please reconsider this determination.  Removal of any parenthesized phrase should not affect the meaning of what remains, but removing "(inclusive)" does in these cases materially change the interpretation of what remains.

In any event, this should be an LWG decision, as all the affected wording arises in Library clauses (locales, numerics, strings).
