### ISSUE TITLE
Table names should be present as stable names

### ISSUE THREAD

**Issue by PeterSommerlad** [cplusplus/draft#2674]
The latex sources of the standard have "stable" table identifications as their \label{tablename}. However, in contrast to regular sections, these names are never rendered in the text. This leads to tedious updates of table numbers in any paper referring to any of the tables. It would be great if the table labels would be printed with the standard like the stable names are printed in the header sections.

This would ease the work of the paper authors as well as the editors (i guess).

**Comment by tkoeppe** [comment]
(I feel like this issue has been raised before.)

**Comment by cpplearner** [comment]
#824

**Comment by jensmaurer** [comment]
Editorial meeting:
- Review all table labels.
- Expose label as "tab:blah".

**Comment by jensmaurer** [comment]
This needs substantial work. Almost all labels seem to be overly long or nondescript. Suggested rules:
- If a subclause consists predominantly of a table, use the same label as the subclause label (plus tab: prefix). Example: tab:lex.key, tab:lex.digraph.
- Otherwise, use at least some parts in common with the subclause label. Example: tab:temp.fold.empty.

**Comment by jensmaurer** [comment]
Editorial meeting:
- Second rule: Use cpp17.conceptname.
- Do not make the label bold.
- Separate label from caption text by \quad.
- Separate table number from caption text by \quad or colon (show screenshots of both options). Remove mdash. Try to be consistent with subclause titles.
- Make figure captions the same as table captions, except for before/after placement.
- Check linebreaks in captions.
- Do not repeat the label in continued captions of longtables.

**Comment by jensmaurer** [comment]
Sample 1: separate table number from caption text by colon
![caption-colon](https://user-images.githubusercontent.com/23412755/59137302-74856400-8987-11e9-877c-31c1fb62bd1c.png)

Sample 2: separate table number from caption text by \quad
![caption-quad](https://user-images.githubusercontent.com/23412755/59137347-b1515b00-8987-11e9-85d7-ea44400653c5.png)

**Comment by jensmaurer** [comment]
Sample figure:

![caption-figure](https://user-images.githubusercontent.com/23412755/59151219-a2be7e80-8a2f-11e9-9e71-b249f3a8ed3d.png)

Sample linebreak:

![caption-linebreak](https://user-images.githubusercontent.com/23412755/59151236-f03aeb80-8a2f-11e9-94ab-6c32fef0846e.png)

**Comment by hubert-reinterpretcast** [comment]
My preference is for the colon between the number and the caption.

**Comment by W-E-Brown** [comment]
> On Jun 8, 2019, at 3:07 PM, Hubert Tong <notifications@github.com> wrote:
> 
> My preference is for the colon between the number and the caption.
> 

I, too, prefer the colon.

**Comment by zygoloid** [comment]
(I also prefer the colon.) Thanks Jens!

**Comment by jensmaurer** [comment]
Added a "labels" section to the wiki style guidelines.
