### ISSUE TITLE
Why are the words "that is not a cv-qualifier" mentioned in [class.mem]/12? 

### ISSUE THREAD

**Issue by Ayrosa** [cplusplus/draft#2675]
[[class.mem]/12](http://eel.is/c++draft/class.mem#12):

> The decl-specifier-seq may be omitted in constructor, destructor, and conversion function declarations only; when declaring another kind of member the decl-specifier-seq shall contain a type-specifier **that is not a cv-qualifier**. The member-declarator-list can be omitted only after a class-specifier or an enum-specifier or in a friend declaration. A pure-specifier shall be used only in the declaration of a virtual function that is not a friend declaration.

The code below is accepted by C++ compilers since time immemorial:

```
struct A{
    const int i;
    A():i(1) {}
};
```

**Comment by jwakely** [comment]
It means it must have at least one type-specifier that is not a cv-qualifier. It can **also** have cv-qualifiers.

i.e. `const i;` is not valid, but `const int i;` is valid and `const unsigned long long int;` is valid

**Comment by jwakely** [comment]
In other words, it doesn't say "shall not contain cv-qualifiers".
