### ISSUE TITLE
[2019-02 CWG Motion 9] P0960R3 Allow initializing aggregates from a parenthesized list of values

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2689]
[P0960R3](https://wg21.link/p0960r3)

**Comment by languagelawyer** [comment]
@zygoloid @jensmaurer it is surprising that the wording for [[dcl.init]/(17.5)](http://eel.is/c++draft/dcl.init#17.5) passed as-is. It:
- uses constructs like «i<sup>th</sup> array element»
- counts them from 1 to N, not from 0 to N-1.

Was this an overlook?
