### ISSUE TITLE
[2019-02 LWG Motion 17] P1024R3 Usability Enhancements for std::span

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#2708]
[P1024R3](https://wg21.link/p1024r3)

**Comment by CaseyCarter** [comment]
FYI: this paper has an interaction with P1227R2, which changes the type of `span`'s second template parameter from `ptrdiff_t` to `size_t`. After application of P1227R2, the specializations of `tuple_size` and `tuple_element` that this paper adds will never be matched (which IIRC means they are ill-formed NDR). 

LWG is hoping - @mclow can verify - that we can editorially change the `ptrdiff_t`'s in this paper to `size_t`'s to resolve the conflict.

**Comment by mclow** [comment]
I offered (in plenary) to consult about merge conflicts between P1024 and P1227. I have implemented both in libc++ w/o any compatibility concerns (doing what Casey suggested)
