### ISSUE TITLE
clause [istream.extractors] is named [istream::extractors]

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#271]
Subclause 27.7.2.2.3 [istream::extractors] should be named [istream.extractors].

**Comment by AlisdairM** [comment]
There are 8 library issues reported against this clause that would need to have their section reference updated in synch:  13, 58, 64, 68, 162, 413, 639, 2499.

Of course, only 2499 is still open, but we do not want to break the links for resolved issues either.

**Comment by jwakely** [comment]
There are lots of these in Clause 21 too, e.g. [string::op+=], [string::append] etc.

**Comment by jensmaurer** [comment]
Regarding Clause 21, this is fixed in https://github.com/cplusplus/draft/pull/999 .
