### ISSUE TITLE
[range.iota, range.adaptors] View's synopses missing cross-references to iterator and sentinel members

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2716]
Per https://github.com/cplusplus/draft/pull/2475#issuecomment-466289153, these are bugs.

**Comment by jensmaurer** [comment]
Ah, this maybe points at a larger issue: We have private "struct iterator" and "struct sentinel" for exposition only. Are these names part of the interface, or not? If they're not part of the interface, we should use non-C++ names and \placeholder for them, cf. node-handle. Also, once we do that, we can remove "private".
@CaseyCarter, what's the deal here?

**Comment by CaseyCarter** [comment]
Those names are *not* part of the interface. The library does not `\placeholder` the names of exposition-only variables, types, or functions declared as `private` class members. I'm mildly opposed to such a change: I'm not concerned that users will be confused into thinking they can name things declared `private`, and I think too much variation in typography makes the spec harder to read.

*`node-handle`* and pre-P1252  *`ref-view`* are special cases, in that we need to specify them despite that they are not declared anywhere.

**Comment by jensmaurer** [comment]
@CaseyCarter: Private members are not as invisible as we might want them to be. Consider:
```
class Lib_X {
private:
  int x;
};

// user code starts here
int x;
struct User_T : Lib_X {
  int f() { return x; }   // finds Lib_X::x (ill-formed), not the user-written (and likely intended) ::x.
};
```
So, it's a material part of the classes' interface whether there is a name "iterator" declared in the standard library class (even if private).

**Comment by jwakely** [comment]
But the comment _exposition only_ means they are not part of the specified interface, not even as private members, at least that's what [expos.only.types] is supposed to mean.

**Comment by jwakely** [comment]
Since the implementation won't actually use the names `iterator` and `sentinel`, but rather reserved names like `__sentinel`, the problem Jens describes won't happen. Users won't be referring to any non-members with those reserved names, so it doesn't matter that they are visible and inaccessible.

I don't see any issue here.

**Comment by jensmaurer** [comment]
But for concepts, we mark them with \expos and we make them italics to shy away people from thinking those names mean anything in their programs. Why are we inconsistent for member types?

**Comment by johelegp** [comment]
I think that \placeholder was introduced to emphasize the exposition only nature of names in an accessible scope. Data members being private, \expos should be enough.
