### ISSUE TITLE
Typo? in range.iota_view example

### ISSUE THREAD

**Issue by robert-andrzejuk** [cplusplus/draft#2717]
@CaseyCarter I believe the example in the draft standard might perhaps contain a very minor error.

http://eel.is/c++draft/range.iota#overview-2

Shouldn't the comment be `prints: 1 2 3 4 5 6 7 8 9 10` ?
```
[ Example:

for (int i : iota_view{1, 10})
  cout << i << ' '; // prints: 1 2 3 4 5 6 7 8 9

— end example
 ]
```

**Comment by Rakete1111** [comment]
Why? See eel.is/c++draft/range.iota#overview-2 When the value of the iterator is equal to the upper bound (in this case 10), the iterator is equal to the sentinel and thus the loop stops.

**Comment by CaseyCarter** [comment]
As @Rakete1111 says, the arguments to `view::iota` are treated as a half-open interval `[first, last)`.
