### ISSUE TITLE
Verbiage about compilation errors in the non-immediate context spammed out everywhere

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/draft#272]
We need to centralize the definition of "immediate context" wrt template instantiation so we can eliminate spammy verbiage like the following in the description of `is_assignable`:

> Only the validity of
> the immediate context of
> the assignment expression
> is considered. [ Note: The
> compilation of the
> expression can result in
> side effects such as the
> instantiation of class
> template specializations
> and function template
> specializations, the
> generation of
> implicitly-defined
> functions, and so on. Such
> side effects are not in the
> “immediate context” and
> can result in the program
> being ill-formed. —end
> note ]

In addition to all the current places where "immediate context" is described in the current standard, similar wording can be found in proposals for SFINAE-friendly `iterator_traits`, `common_type`, and `invocation_traits`.

**Comment by jensmaurer** [comment]
General case of #445.

**Comment by jensmaurer** [comment]
This is the subject of [LWG 2290](http://cplusplus.github.io/LWG/lwg-active.html#2290) "Top-level "SFINAE"-based constraints should get a separate definition in Clause 17".
