### ISSUE TITLE
Inconsistent complexities for average/worst

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#2749]
We're inconsitent as to wether we do
`Average case x. Worst case y.`
vs
`Average case x, worst case y.`
when describing complexities in library tables.

In #2718, jensmaurer added:
> I would even vouch for a semicolon here. Yes, please make that a separate editorial issue and put "decision-required" on it.

**Comment by jensmaurer** [comment]
Editorial meeting: Go for comma, lowercase.
