### ISSUE TITLE
add index entries for identifiers with special meaning

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2769]
Add index entries for identifiers with special meaning, both for their entry in Table 4 and for each use of them in the grammar.

We should probably add a dedicated macro for these special non-keyword terminals to automate the second part of this.

**Comment by jensmaurer** [comment]
Shouldn't we index all uses of keywords in the grammar, regardless of whether it is a "real" keyword or a contextual one? It seems nice to be able to find all uses of "class" in our grammar, for example.
