### ISSUE TITLE
reorder subclauses of [expr.unary] to match grammar

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2773]
The subclauses of [expr.unary] should be in the same order as the grammar productions. They aren't. Reorder one or both so that they match. (I'm moving the preincrement operators after unary-operators in the grammar as part of merging the coroutines wording, but the relative order of the final four productions still needs to be fixed.)

**Comment by jensmaurer** [comment]
Waiting for #2770.

**Comment by jensmaurer** [comment]
#2770 is done.

**Comment by jensmaurer** [comment]
I think it makes sense to keep sizeof, alignof, noexcept together; they are "compile-time constant functions". It's a "later add-on" mishap that the detailed description of alignof and noexcept are at the end.
