### ISSUE TITLE
reconsider placeholder formatting in [expr.await]

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2774]
[expr.await] uses placeholders for names of various expressions, types, etc used in its exposition. We should consider whether plain teletype would be a better choice for some of those placeholders (in particular, the ones that simply denote types rather than being syntactic macros for a choice of one of two forms of expression).

**Comment by zygoloid** [comment]
Concretely, we should consider upright teletype for these placeholders: P and Z (types), and e and h (objects). p, a, o, await-ready, await-suspend, and await-resume are all macros for a specific syntactic construct, so italics for those seems appropriate.

**Comment by zygoloid** [comment]
It's not clear what to do with *s* in /5.1, which is "a value". But then we talk about a call "*s*`.resume()`", which doesn't make sense, since you can't make a call on a value. I think *s* should actually be the *await-suspend* expression itself:

> If the *await-suspend* expression has type `std::coroutine_handle<Z>`, the coroutine referred to by that handle is resumed as if by calling *await-suspend*`.resume()`.

Fitting that into the surrounding bullet may require some massaging of the text.

**Comment by zygoloid** [comment]
e and h are nebulous -- e is an lvalue, and h should probably be a prvalue, so they're both syntax-macro-esque.

**Comment by jensmaurer** [comment]
Waiting for #2770.
