### ISSUE TITLE
Reconsider use of 'prime' placeholder variables in code fragments

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#2775]
For example:
https://github.com/cplusplus/draft/blob/79cd78cbc6015fd4074147a83a312b22e93519fa/source/templates.tex#L7518
That 'prime' quote character is awfully close to a regular single quote character. Is there enough value in the 'prime' naming convention for placeholder variables that the possible confusion with regular C++ quote characters is worth it? :)

**Comment by tkoeppe** [comment]
Hm, it looks pretty distinct to me in the rendered output. Primed vs unprimed symbols is a pretty common style for situations like this, so I quite like the way it is... how big a problem is this for you? How many people have been confused by this?

**Comment by Eelis** [comment]
Primed symbols is certainly a common convention for math, but I think we're in an untypical situation, because we're mixing C++ syntax and math syntax. Given that C++ syntax is famously complex, I figured that a style guideline like the following would be uncontroversial:

> Mix C++ syntax and math syntax in code fragments only when absolutely necessary.

But if not, that's ok too. It's not causing me any problems. :)

**Comment by tkoeppe** [comment]
But overload resolution is a uniquely mathsy section of the specification already -- I think the notation is appropriate in its context. Shout if this really upsets anyone, but let's keep it as is otherwise.
