### ISSUE TITLE
Hanging paragraphs in [stmt.return] following the coroutines merge

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#2781]
The coroutines wording added a subsection [stmt.return.coroutine] to [stmt.return], leaving the original text in hanging paragraphs. We should perhaps invent a new subsection for the original material, too. (E.g. "classic return", or "[stmt.return.legacy]" :-) .)

**Comment by jensmaurer** [comment]
What about moving co_return one level up, i.e. not nested inside "return"? It's fairly self-contained.

**Comment by jensmaurer** [comment]
Editorial meeting: Move the co_return clause level up; leave the label as-is.
