### ISSUE TITLE
prevent `template <` from sneaking into the library wording

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2785]
We should fix all the instances of `template <` in library clauses, and consider adding a CI check to prevent more regressions.

**Comment by zygoloid** [comment]
Cleaned up for now; we should still consider a CI check for this to prevent more regressions.

**Comment by jensmaurer** [comment]
The core language parts actually use `template <` quite a lot. So, the first challenge is to find out which LaTeX source files constitute the library part of the standard.

**Comment by jensmaurer** [comment]
The new "check.sh" script will detect `template <` in library clauses; committed in 71086838c8082ab5d426c5cc963357e591355a85.
