### ISSUE TITLE
fix presentation of `tuple_element` specializations

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#2786]
We have a variety of `tuple_element` specializations that use different presentation styles:

 * Some give a definition of the specialization
 * Others don't, and merely specify the `::type` member
 * Some use a *Value:* element for the type, others use a *Type:* element

We should do this properly: the specialization needs a specified definition, and a member typedef should be specified as actually being a type. (The current wording for several of these specializations completely lacks any suggestion that `...::type` is a *typedef-name*, for example.)

**Comment by johelegp** [comment]
#2553, #2476 and https://wg21.link/LWG3166 are related.

**Comment by jensmaurer** [comment]
LWG 3166 is concerned with the undefined "Value:" element. Let's ignore this issue for now (since it's tracked elsewhere), and let's harmonize all `tuple_element` specialization as outline by @zygoloid above.
