### ISSUE TITLE
I find the first comment in the example in [basic.lookup.elab]/3 inaccurate

### ISSUE THREAD

**Issue by Ayrosa** [cplusplus/draft#2802]
The example in [[basic.lookup.elab]/3](http://eel.is/c++draft/basic.lookup.elab#3) starts with the following:

> struct Node {
> &nbsp;&nbsp;&nbsp;&nbsp;struct Node* Next;            // OK: Refers to Node at global scope
> &nbsp;&nbsp;&nbsp;&nbsp;struct Data* Data;            // OK: Declares type Data at global scope and member Data
> };

The first comment above should be replaced by "Refers to the injected class name Node" according to the [previous paragraph](http://eel.is/c++draft/basic.lookup.elab#2) which says:

> If the elaborated-type-specifier has no nested-name-specifier, and unless the elaborated-type-specifier appears in a declaration with the following form:
>
> &nbsp;&nbsp;&nbsp;&nbsp;_class-key_ _attribute-specifier-seq<sub>opt</sub>_ _identifier_ `;`
>
> the identifier is looked up according to [[basic.lookup.unqual]](http://eel.is/c++draft/basic.lookup.unqual) but ignoring any non-type names that have been declared.

Finally, [[basic.lookup.unqual/7](http://eel.is/c++draft/basic.lookup.unqual#7) confirms that the lookup for the name `Node` started in `struct Node * Next;` finds the injected class name `Node`, not the `Node` in global scope.

**Comment by jwakely** [comment]
Aside: should the example in [basic.lookup.elab] p3 be a new paragraph? It seems to be showing the rules of the entire sub-clause, not just those in paragraph 3 that it's attached to.

**Comment by Ayrosa** [comment]
I wouldn't go that far. All the lookups in the example start with _class names_ in _elaborated-type-specifiers_ .

**Comment by jwakely** [comment]
The paragraph talks about "If the elaborated-type-specifier has a nested-name-specifier," and that doesn't apply to everything in the example.

**Comment by Ayrosa** [comment]
Yes, you're right. In that case it makes some sense to move the example to a new paragraph, although I don't feel uncomfortable with the way it's laid out now.
