### ISSUE TITLE
[span.overview] Iterator requirements should be appropriately relocated

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2806]
The normative requirements on the iterator types of `span` [are in](http://eel.is/c++draft/span.overview#2) its description (before its class synopsis). I believe it would be more appropriate that they be relocated in a manner similar to that of [`string_view`'s](http://eel.is/c++draft/string.view.iterators#itemdecl:1).

**Comment by jensmaurer** [comment]
Agreed, and also makes for better index entries.
