### ISSUE TITLE
[iterator.traits] Redundant required expression in cpp17-input-iterator

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2816]
With _`cpp17-iterator`_ requiring
https://github.com/cplusplus/draft/blob/8d238bd4e100495f032e9cca2a8f051797f0888f/source/iterators.tex#L859
isn't _`cpp17-input-iterator`_'s requirement redundant?
https://github.com/cplusplus/draft/blob/8d238bd4e100495f032e9cca2a8f051797f0888f/source/iterators.tex#L869
Whole definitions:
https://github.com/cplusplus/draft/blob/8d238bd4e100495f032e9cca2a8f051797f0888f/source/iterators.tex#L854-L873

**Comment by CaseyCarter** [comment]
> isn't _`cpp17-input-iterator`_'s requirement redundant?

Yes, it is. Good catch.
