### ISSUE TITLE
In [func.wrap.func.con], reference to "Table 17.6.3.5"

### ISSUE THREAD

**Issue by jyasskin** [cplusplus/draft#283]
Should either be Table 28 or Section 17.6.3.5.

**Comment by AlisdairM** [comment]
Searching for all uses of '28' (still the correct table number) and '17.6.3.5' I find exactly zero references to Table 28.  The cross-references to 17.6.3.5 typically contain just the clause-number in brackets, but we could be more consistent in our phrasing when we make the cross-reference.

Existing phrasing includes:
   Alloc shall be an Allocator (17.6.3.5)  [most common, but not dominant]
   Alloc shall meet the requirements for an Allocator (17.6.3.5).
   Allocator shall meet the Allocator requirements (17.6.3.5)
   a type that satisfies the Allocator requirements (17.6.3.5)
   ... conforms to the Allocator requirements (17.6.3.5)
   a type that conforms to the requirements for Allocator (Table 17.6.3.5)   [text of this issue]

**Comment by jensmaurer** [comment]
Allocator support for std::function has been removed, so this is now moot.

(If we want to discuss consistency of the "shall meet X" wording, we should have a new issue that also looks for similar phrases for CopyConstructible etc. This is probably a large task.)
