### ISSUE TITLE
[dcl.ambig.res] Ambiguity resolution for function and object declarations is ambiguous CWG2620

### ISSUE THREAD

**Issue by sdkrystian** [cplusplus/draft#2831]
http://eel.is/c++draft/dcl.decl#dcl.ambig.res-1 (Ambiguity resolution for function/object declaration) states that: 

> In that context, the choice is between a function declaration with [...] and an object declaration with [...].

and 

> Just as for the ambiguities mentioned in [stmt.ambig], the resolution is to consider any construct that could possibly be a declaration a declaration.

Both a function declaration and an object declaration are declarations, so it is unclear which will be chosen.

**Comment by 18** [comment]
In addition to this, this wording does not cover the declaration of a reference being ambiguous with a the declaration of a function returning a reference. 
Ex:
```
int x;
int& y(int(x)); 
```

**Comment by zygoloid** [comment]
I believe the intended interpretation is "the resolution is to consider the longest sequence of tokens that could possibly constitute a *declarator* to form a *declarator*". (In your example, the `(int(x))` could be part of a *declarator*, so the declaration is disambiguated as a function declaration.)

I'd like CWG to look at this, in case my belief above is incorrect :)

**Comment by cpplearner** [comment]
My understanding is that the ambiguity arises because `int(x)` can be treated as a parameter declaration or an initializer, and the "resolution" is to consider it as a parameter declaration.

[dcl.dcl]/10 seems to suggest that anything that's not a _typedef declaration_ or _function declaration_ is a _object declaration_, so it does seem to cover declaration of a reference.

**Comment by 18** [comment]
Both of your interpretations work, but I believe the wording should be changed in order to make it clearer as to what it means.

**Comment by RealLitb** [comment]
> [dcl.dcl]/10 seems to suggest that anything that's not a _typedef declaration_ or _function declaration_ is a _object declaration_, so it does seem to cover declaration of a reference.

I think this is https://github.com/cplusplus/draft/issues/1280
