### ISSUE TITLE
[dcl.stc]/9 allows modification of any member provided any is mutable

### ISSUE THREAD

**Issue by 18** [cplusplus/draft#2837]
> The mutable specifier on a class data member nullifies a const specifier applied to the containing class object

This has the effect of saying that specifying any data member of a class as mutable is result in the object losing it's const qualification, leading to any member being able to be modified. This is obviously not the intended meaning.

**Comment by jensmaurer** [comment]
I think the right fix is to turn [dcl.stc} p9 into a note; this is all said elsewhere.
