### ISSUE TITLE
The sentence highlighted below in [basic.start.static]/2 is indexed to {initialization!runtime}. Is that correct?

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#2844]
[[basic.start.static]/2](http://eel.is/c++draft/basic.start.static#2)

> Constant initialization is performed if a variable or temporary object with static or thread storage duration is initialized by a constant initializer ([expr.const]) for the entity. **If constant initialization is not performed, a variable with static storage duration ([basic.stc.static]) or thread storage duration ([basic.stc.thread]) is zero-initialized ([dcl.init])**. Together, zero-initialization and constant initialization are called static initialization; all other initialization is dynamic initialization. All static initialization strongly happens before ([intro.races]) any dynamic initialization. [ Note: The dynamic initialization of non-local variables is described in [basic.start.dynamic]; that of local static variables is described in [stmt.dcl]. — end note ]

To verify this, see line # 5735 in the [committed pull request](https://github.com/cplusplus/draft/commit/9eccd8d1d2e217e770c761c1f3e82267e9f4c5a5#diff-a7cb4634eeb2e4ce984d41aaa9a70ef4):

5735    **\indextext{initialization!runtime}%**

AFAICT this is basically saying that zero-initialization is somehow related to run-time initialization, which doesn't seem to be correct.

To correct this, simply reverse the content of lines 6067 and 6068 in [basic.tex](https://github.com/cplusplus/draft/blob/master/source/basic.tex).

**Comment by jensmaurer** [comment]
Both constant and zero-initialization can happen at runtime, as long as they happen before "main". So "runtime" is not exactly wrong here, but probably not really appropriate. I've replaced it with "zero-initialization", which already had an entry in the index.
