### ISSUE TITLE
[dcl.ref] Requirement to diagnose invalid binding of references

### ISSUE THREAD

**Issue by meowingtwurtle** [cplusplus/draft#2848]
[dcl.ref]/5 says:
> A reference shall be initialized to refer to a valid object or function.

According to [the specification style guidelines](https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines), this sentence imposes a requirement on implementations to diagnose violations of this rule, as there is no mention of "no diagnostic is required" or "undefined behavior".

It is unreasonable to expect implementations to diagnose all violations of this rule.

This is related to [CWG 453](https://wg21.link/cwg453).

**Comment by jensmaurer** [comment]
This is exactly core issue 453.
