### ISSUE TITLE
Should we change all "source character set" to "basic source character set"?

### ISSUE THREAD

**Issue by xskxzr** [cplusplus/draft#2857]
I have searched over [lex] and found there is no definition for "source character set", but this word is used in many contexts, for example,

[lex.phases]/5:
Each source character set member in a character literal or a string literal, ...

Unlike execution character set, "extended source character set" is useless since any source file character not in the basic source character set is replaced by a universal-character-name. So should we change all "source character set" to "basic source character set", or vice versa？

**Comment by jensmaurer** [comment]
There are special cases where we actually consider characters outside of the basic source character set, for example in raw string literals [lex.pptoken] p3. The conversion to universal-character-names is reverted in that case.

So, in a raw string literal, we could have characters beyond the basic source character set, and those are (also) mapped to the execution character set.

The remaining (small) issue here is the missing definition of "source character set". We could say "set of physical source file characters"; see [lex.phases] p1.1.

**Comment by jensmaurer** [comment]
Editorial meeting: Fix "source character set" -> "basic source character set" where that is the obvious correct fix. Leave other cases to eventual CWG cleanup.

**Comment by jensmaurer** [comment]
The remaining issues are whether _h-char_, _q-char_, and _r-char_ can be letters outside of the basic source character set. It seems to me the answer to the latter is clearly "yes"; the answer to the former two might be "no".
