### ISSUE TITLE
[iterator.synopsis][insert.iterator] Some "iterator_t" should be replaced with "ranges::iterator_t"

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#2859]
In N4810, the specifications for `insert_iterator` and `inserter` refer the name `iterator_t` which belongs to namespace  `std::ranges`.
However, `insert_iterator` and `inserter` are in namespace `std` themselves.
So I think `iterator_t` should be qualified with `ranges::` while introducing `insert_iterator` and `inserter`.

**Comment by jwakely** [comment]
Good catch, thanks. Would you be able to submit a pull request to fix it?
