### ISSUE TITLE
[range.filter.sentinel] filter_view::sentinel's single-parameter constructor seems wrong

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#2880]
[\[range.filter.sentinel\]](http://eel.is/c++draft/range.filter.sentinel):

>     constexpr explicit sentinel(filter_view& parent);
>
> Effects: Initializes `end_` with `ranges::end(parent)`.

1. `ranges::end(parent)` should probably be `ranges::end(parent.base_)`.

2. The design of sentinel's constructor seems to be unnecessarily inconsistent among range adaptors. 
  - `filter_view::sentinel` ([\[range.filter.sentinel\]](http://eel.is/c++draft/range.filter.sentinel#itemdecl:1)) and `join_view::sentinel` ([\[range.join.sentinel\]](http://eel.is/c++draft/range.join.sentinel#itemdecl:1)) have constructors that accept a reference to parent type, and call `ranges::end` inside that constructor. The parents simply pass `*this` as sentinel constructor argument in `end()`.
  - `transform_view::sentinel` ([\[range.transform.sentinel\]](http://eel.is/c++draft/range.transform.sentinel#itemdecl:1)) and `take_view::sentinel` ([\[range.take.sentinel\]](http://eel.is/c++draft/range.take.sentinel#itemdecl:1)) have constructors that accept a `sentinel_t<Base>`, the parents pass `ranges::end(base_)` as sentinel constructor argument in `end()`.

**Comment by jensmaurer** [comment]
"The design of ..." catapults this right out of editorial scope.

@CaseyCarter , do you have an opinion on the first item above?

**Comment by cpplearner** [comment]
Nevermind 2. I think I understand now. The difference is because the iterators of `filter_view` and `join_view` use `ranges::end(parent_->base_)`, which only makes sense when the sentinels hold the same value.

**Comment by CaseyCarter** [comment]
> @CaseyCarter , do you have an opinion on the first item above?

Yes, the spec is completely bogus: either the specified initialization is ill-formed, or the resulting program will overflow its stack recursing between this constructor and `filter_view::end`.

I've submitted a PR with the editorial-ish fix; feel free to assign this issue to me.
