### ISSUE TITLE
Reference Initialization: function lvalue covered by two cases

### ISSUE THREAD

**Issue by h0nzZik** [cplusplus/draft#2882]
The section [dcl.init.ref](http://eel.is/c++draft/dcl.init.ref) of the C++ standard contains rules for initialization of references. However, the case when the initializer is a function lvalue seem to be covered twice: first time implicitly in [[dcl.init.ref]/5.1.1](http://eel.is/c++draft/dcl.init.ref#5.1.1):

> If [...] **the initializer expression
is an lvalue** (but is not a bit-field), and “cv1 T1” is reference-compatible with “cv2 T2”, or [...]

and second time explicitly in [[dcl.init.ref]/5.3.1](http://eel.is/c++draft/dcl.init.ref#5.3.1):
> Otherwise, if the initializer expression is an rvalue (but not a bit-field) **or function lvalue** and “cv1 T1” is reference-compatible with “cv2 T2”, or [...].

~Moreover, the second instance is hidden behind `otherwise`, and so cannot apply to anything.~

is this intentional?

**Comment by cpplearner** [comment]
I think the intent is to permit both

```c++
void f();
decltype(f)& lref = f; // [dcl.init.ref]/(5.1.1)
```

and

```c++
decltype(f)&& rref = f; // [dcl.init.ref]/(5.3.1)
```

Note that `std::move(f)` is also a function lvalue.
