### ISSUE TITLE
[dcl.type.simple]/2 erroneous statement about a type-specifier

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#2909]
[[dcl.type.simple]/2](http://eel.is/c++draft/dcl.type#simple-2):

> A _placeholder-type-specifier_ is a placeholder for a type to be deduced ([dcl.spec.auto]). A _type-specifier_ of the form **typename**<sub>_opt_</sub> _nested-name-specifier_<sub>_opt_</sub> _template-name_ is a placeholder for a deduced class type ([dcl.type.class.deduct]). . . .

AFAICT, there is no way to obtain a [_type-specifier_](http://eel.is/c++draft/dcl.type#nt:type-specifier) with the form specified above.

**Comment by jensmaurer** [comment]
It seems the grammar for _typename-specifier_ is missing an option for
_nested-name-specifier_ _template-name_ to make the `typename` prefix possible.

**Comment by jensmaurer** [comment]
Editorial meeting: The grammar for _typename-specifier_ allows a trailing _identifier_, which does cover _template-name_ as well. We understand "of the form" quotes are re-matching the tokens, so there is no defect.
