### ISSUE TITLE
P0457R2 - links in TOC point to R1

### ISSUE THREAD

**Issue by WimLeflere** [cplusplus/draft#2910]
The links in the table of contents of [P0457R2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0457r2) point to P0457R1.

Not sure if this is the correct place to report the issue.

**Comment by tkoeppe** [comment]
Sorry, that document is entirely unrelated to this project. You can contact the author, but given that the document is published, it cannot really be changed, only have future revisions.
