### ISSUE TITLE
[conv.qual]/5 and footnote 67 are near-identical

### ISSUE THREAD

**Issue by W-E-Brown** [cplusplus/draft#2924]
Do we need both [conv.qual]/5 and footnote 67?

[conv.qual]/5 says:  "[Note: Function types (including those used in pointer to member function types) are never cv-qualified (9.2.3.5). —end note]"

Footnote 67 says:  "Function types (including those used in pointer-to-member-function types) are never cv-qualified; see 9.2.3.5."

(FWIW, I prefer to keep the Note, but with the footnote's "pointer-to-member-function" hyphenation.)

**Comment by jensmaurer** [comment]
Footnote 67 is in [expr.static.cast], thus far away from [conv.qual] p5. I do support turning footnote 67 into a note, though.

**Comment by jensmaurer** [comment]
Editorial meeting: Turn footnote into a note; consistently use hyphenation from the footnote and xref style from the note.
