### ISSUE TITLE
[func.bind] needs de-shalling

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#2930]
[func.bind.isbind]:

>  ~Instantiations~ **Specializations** of the `is_bind_expression` template shall satisfy the _Cpp17UnaryTypeTrait_ requirements (20.15.1). The implementation ~shall provide~ **provides**  a definition that has a base characteristic of `true_type` if `T` is a type returned from `bind`, otherwise it ~shall have~ **has** a base characteristic of `false_type`. 

Similarly in [func.bind.isplace].

The _Returns:_ and _Remarks:_ in [func.bind.bind] shouldn't be using "shall", and neither should [func.bind.place] p1 and p2.

**Comment by jensmaurer** [comment]
I'm not convinced that [func.bind.place] should be de-shalled. After all, users can define their own placeholders (using std::is_placeholder), and presumably those restrictions also apply for user-defined placeholders.
