### ISSUE TITLE
[expr.prim.req]/1 Incorrect reference to [temp.constr.decl]?

### ISSUE THREAD

**Issue by RazvanAM** [cplusplus/draft#2944]
[expr.prim.req]/1

> A nested-requirement can be used to specify additional constraints in terms of local parameters. The constraint-expression shall be satisfied ([temp.constr.decl]) by the substituted template arguments, if any. **Substitution of template arguments into a nested-requirement does not result in substitution into the constraint-expression other than as specified in [temp.constr.decl]**. [...]

I tracked the highlighted sentence to this commit (https://github.com/cplusplus/concepts-ts/commit/52b22de6edac608b72244fe1fdee4188a9c40f11).

Does the highlighted sentence mean that in the case of a _requires expression_ such as:
`requires {
    requires A<T>::val && B<T>::val;
  };`
if `A<T>::val` evaluates to `false` then the template argument that corresponds to `T` is not substituted into `B<T>` (this would be helpful if `B<T>::val` would make the program ill-formed)? If so, then why is the reference to [temp.constr.decl]? I checked the contents of [temp.constr.decl] back when the commit was made, but I still cannot find a reason for the reference to be to that section.

I think a more appropriate reference could be to [temp.constr.op], which states that some constraints may remain unchecked.

Thank you.

**Comment by jensmaurer** [comment]
Referring to [temp.constr.constr] seems to be most appropriate.

**Comment by RazvanAM** [comment]
I re-read the version of "constraints.tex" from when Richard Smith's commit was made (https://github.com/cplusplus/concepts-ts/blob/52b22de6edac608b72244fe1fdee4188a9c40f11/src/constraints.tex). I saw that back then the [temp.constr.decl] section contained the following paragraph: 

> A declaration's associated constraints are satisfied by a set of template
arguments if and only if its normalized associated constraints are satisfied
by those arguments.

This may be the reason why [temp.constr.decl] was referenced (in both sentences of [expr.prim.req]/1). And this may be relevant, as I think that the standard, in its current version, does not state when a _constraint-expression_ is satisfied. It only states when a _constraint_ is satisfied, but a _constraint-expression_ first needs to be normalized in order to become a _constraint_.

**Comment by jensmaurer** [comment]
Well, it's certainly odd to have two cross-references to the same target within the same paragraph.

**Comment by RazvanAM** [comment]
This has been on my mind for a while. I keep trying to figure out why the references would be to [temp.constr.decl] at the time the commit was made. The explanation that I can come up with is that [temp.constr.decl] was the section that made the link between _constraint-expressions_ and _constraints_ (this is because it described what the _associated constraints_ of a declaration are (some of them being derived from _requires-clauses_ made up of  _constraint-expressions_), when the _associated constraints_ of a declaration are _satisfied_ ([expr.prim.req]/1 uses the keyword _satisfied_), and it also described the _normalization_ process). I think other sections were concerned only with _constraints_. @zygoloid, could you please confirm that this is the reasoning behind the initial references? Thank you very much!
