### ISSUE TITLE
[basic.life]/5 was overlooked during CWG2256 resolution?

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#2953]
[basic.life]/5 still says that
> A program may end the lifetime of any object by reusing the storage which the object occupies or by explicitly calling the destructor for an object of a class type with a non-trivial destructor.

even though the requirement about non-triviality of a destructor was removed from [basic.life]/1 during CWG2256 resolution and now it says that
> The lifetime of an object o of type T ends when:
 — if T is a non-class type, the object is destroyed, or 
 — if T is a class type, the destructor call starts, or

**Comment by jensmaurer** [comment]
CWG2051 is still in "drafting"; you're talking about CWG 2256.

**Comment by languagelawyer** [comment]
Oops, yes, I meant CWG2256.

**Comment by languagelawyer** [comment]
> CWG2051 is still in "drafting"

I've thought it was merged in https://github.com/cplusplus/draft/commit/573152d081f7052f4ebe7678d58f94714f2b973b

**Comment by jensmaurer** [comment]
Right, sorry for the confusion. (I was looking at an older core issues list.)
