### ISSUE TITLE
An index of library concepts would be extremely useful

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#2959]
The standard library specification is filling up with concepts, especially "exposition only" concepts, and Cpp17Requirements.  It is often necessary to locate the definition of these concepts to understand the clause you are reading, and there is no easy collected reference to find them.  We could look into the index of library names, but it is not clear that the exposition-only names belong there.

It would be helpful to add a new index for all library concepts, including the exposition-only ones denoted by appearing in italics.  It might also be useful to index the Cpp17Requirements, but most of those are reasonably easy to find today, and with a consistent prefix naming convention, perhaps better served by consistently adding them to the main index (where some, but not all, already reside).

**Comment by AlisdairM** [comment]
Note that any Cpp17Requirements concerns would be separately addressed by the patch I just submitted:
   https://github.com/cplusplus/draft/pull/2961

It would not surprise me that we could do better (comments on patch please!) but the existing indexing infrastructure can largely deal with this case.

**Comment by jensmaurer** [comment]
Editorial meeting: Nice idea. The index should contain Cpp17, exposition-only, and published new-style concepts.
