### ISSUE TITLE
Specifying hidden friends

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#2966]
Considering [P1601](https://wg21.link/P1601 "Recommendations for Specifying “Hidden Friends”"), have you decided whether to add the mentioned blanked wording or _Remarks:_ element to each of the current hidden friends?

**Comment by jensmaurer** [comment]
We have not. @mclow, do you have any guidance for the editors here? Should we attempt to retroactively editorially improve the existing hidden friends as outlined in the paper?

**Comment by jensmaurer** [comment]
Also, we should really avoid adding more boilerplate such as \remarks for every function if we can use blanket wording instead.

**Comment by jensmaurer** [comment]
Duplicate of #3110.
