### ISSUE TITLE
Indexing of ios_base members

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#2970]
The index of library names does not include `Init`, `pword`, `failure` etc.

We have index entries for `ios_base::Init` and `ios_base`!`Init`, but not `Init`!`ios_base`.

I think we want to use `\indexlibrarymember` e.g.

````diff
--- a/source/iostreams.tex
+++ b/source/iostreams.tex
@@ -1109,7 +1109,7 @@ that contains the elements indicated in \tref{ios.seekdir}.
 \rSec4[ios.init]{Class \tcode{ios_base::Init}}
 
 \indexlibrary{\idxcode{ios_base::Init}}%
-\indexlibrary{\idxcode{ios_base}!\idxcode{Init}}%
+\indexlibrarymember{ios_base}{Init}%
 \begin{codeblock}
 namespace std {
   class ios_base::Init {
````

**Comment by jensmaurer** [comment]
This has been addressed globally by commit 90623064407c1775dc5d13cb71a1e43fe23137de.
