### ISSUE TITLE
Which library features appear in the main index is inconsistent

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#2972]
**Most** library components are not in the main index (just the headers), but the random numbers subclause adds several entries:

![indexg](https://user-images.githubusercontent.com/1254480/61367310-3848fb80-a883-11e9-93e7-66c14f1d0a5f.png)
![indexm](https://user-images.githubusercontent.com/1254480/61367317-3bdc8280-a883-11e9-8752-118cdb6253b9.png)

Also every enumerator of the `regex_constants::syntax_option_type` is index, e.g. `awk` and `multiline`.

We should either consistently index **all** library enumerators and classes in the main index, or remove many of the entries that come from  `<random>` and `<regex>`.

The following may be useful, but probably not all the others:

![indexr](https://user-images.githubusercontent.com/1254480/61367379-64647c80-a883-11e9-8085-b4dca7a3b79b.png)

**Comment by jensmaurer** [comment]
Editorial meeting: Avoid listing library names in the main index. We should not have `\tcode` entries from the library in the main index.
