### ISSUE TITLE
[2019-07 LWG Motion 1] P1724R0 C++ Standard Library Issues to be moved in Cologne

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3005]

**Comment by jensmaurer** [comment]
Issue 3185 says: "If P0784 is accepted, then also add constexpr to uninitialized_construct_using_allocator.”  Note that P0784 was accepted, so this change should also be made when applying LWG motion 1.

**Comment by burblebee** [comment]
LWG3196 adds a row to a table that extends over all columns (it's a note at the bottom of the table).  How can I do that in Latex?

**Comment by keryell** [comment]
Are you talking about `\multicolumn` like in https://en.wikibooks.org/wiki/LaTeX/Tables#Rows_spanning_multiple_columns ?

**Comment by jwakely** [comment]
@burblebee I think the note should be after the table, not within it. Please check with @mclow though.

**Comment by burblebee** [comment]
> Are you talking about `\multicolumn` like in https://en.wikibooks.org/wiki/LaTeX/Tables#Rows_spanning_multiple_columns ?

@keryell Thanks for this tip - it worked!
@jwakely I'll put the note in the table since that's how it appears in the paper, unless I hear otherwise from @mclow.

**Comment by CaseyCarter** [comment]
> @burblebee I think the note should be after the table, not within it. Please check with @mclow though.

IIRC the intent is that the note is within the table, just as is the case for [tab:cpp17.moveconstructible] and [tab:cpp17.moveassignable] (from which one could presumably steal the LaTeX).

**Comment by mclow** [comment]
I agree with @CaseyCarter - the note should be in the table, as it is shown in [3196](https://cplusplus.github.io/LWG/issue3196)
