### ISSUE TITLE
[2019-07 LWG Motion 12] P1614R2 The Mothership has Landed

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3016]

**Comment by jensmaurer** [comment]
@Dani-Hub notes:

The newly added [cmp.concept] says:

> "partially-ordered-with<T, U> is satisfied only if:" [bullet list of semantic requirements]

The usage of "satisfied" is inappropriate here and should be

> "T and U model partially-ordered-with<T, U> only if:" [bullet list of semantic requirements]

**Comment by jensmaurer** [comment]
From P1452R2 On the non-uniform semantics of return-type-requirements:

"[If] P1614, “The Mothership Has Landed: Adding <=> to the Library”), replace said production with -> ConvertibleTo<Type> where Type is the type named by the trailing-return-type:"

**Comment by Dani-Hub** [comment]
I couldn't find the resolution expressed in the second comment of this issue referring to [cmp.concept]'s notion of "partially-ordered-with<T, U> is satisfied only if:". Could you please help me understanding the decided resolution?

**Comment by johelegp** [comment]
It is here:
https://github.com/cplusplus/draft/blob/4060676e3989167a4e83c08ae0550509b574f1db/source/support.tex#L4737-L4738
The resolution was to fix the wording to follow the convention.

**Comment by Dani-Hub** [comment]
Thanks for the pointer - looks good!
