### ISSUE TITLE
[2019-07 LWG Motion 14] P0408R7 Efficient Access to basic_stringbuf ’s Buffer

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3018]

**Comment by jensmaurer** [comment]
see email from @zygoloid on lib reflector (duplicate constructor)

**Comment by jensmaurer** [comment]
Note that LaTeX sources were supplied (see the attachment on the StrawPolls page)

**Comment by burblebee** [comment]
> see email from @zygoloid on lib reflector (duplicate constructor)

I'm not on the lib reflector - can someone please paste the relevant bits here?

**Comment by jwakely** [comment]
`basic_stringbuf(const basic_string<charT, traits, SAlloc>& s, const Allocator& a)` is specified twice. The two are identical apart from whitespace, so just pick one to be applied to the draft, and ignore the other one.
