### ISSUE TITLE
[2019-07 LWG Motion 23] P1035R7 Input Range Adaptors

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3027]

**Comment by CaseyCarter** [comment]
#3015 renames the namespace `std::ranges::view` to `std::ranges::views`. The declarations added by this proposal to `std::ranges::view` should instead be added to `std::ranges::views` for consistency.

**Comment by jensmaurer** [comment]
Asked @CaseyCarter for LaTeX source code to facilitate the integration of the new views.

**Comment by jensmaurer** [comment]
LaTeX source obtained, pull request submitted.

**Comment by zygoloid** [comment]
@jensmaurer I'm out of time for today. Can you try to rebase this onto master? It's going to be an annoying one; git's default merge algorithm is getting very confused by the similar-but-different `sentinel` classes, and applying edits in the wrong places. :(

**Comment by zygoloid** [comment]
Never mind, I managed to find some time and got it rebased. (`-X patience` for the win...)
