### ISSUE TITLE
Missing edits for CWG908

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#303]
The edits for CWG908 are missing from the standard, and appear to have been removed unintentionally. The edits were present in N3035, but gone in N3090. The application of N3044 appears to be the culprit: the proposed wording there did not take into account that the wording it was modifying was also changed by a core issue that had just been voted into the standard.

The edit marks in N3090 do not show the change, and the editors report in N3091 don't mention it, so I suspect it was unintended, and should be restored editorially. (The wording has no normative impact anyway, since the preceding sentence gives a more general rule of which this is a special case.)

**Comment by burblebee** [comment]
Fixed in 5e3b57dc2b3b8862b47c61aea114611a178ede90
