### ISSUE TITLE
Example LaTeX on style wiki does not demonstrate good semantic line breaking

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#3054]
The [Source code formatting](https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines#source-code-formatting) section states:
> Use semantic line breaks in LaTeX source code: http://sembr.org/ 

sembr.org states (rule 4):

> A semantic line break MUST occur after a sentence, as punctuated by a period (.), exclamation mark (!), or question mark (?).

But the LaTeX example on the wiki page shows:

    Lorem ipsum first sentence here, defining a
    \defn{thing}\indextext{alternate entry}. When
    needed,\footnote{mind the spacing} add

**Comment by jensmaurer** [comment]
Fixed.
