### ISSUE TITLE
Inconsistent use of "in this section" vs "in this sub-clause"

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#307]
"In this section" is far more common, but we have the following mentions of sub-clauses:

[expr.const]
[meta.unary]
[meta.unary.prop.query]
[meta.rel]
[meta.trans]
[meta.numerics]
[rand.eng]
[futures.state]

**Comment by jensmaurer** [comment]
"in this section" - 32
"in this subclause" - 38

ISO seems to prefer "in this subclause"
Richard?

**Comment by zygoloid** [comment]
In an ISO standard, the correct term is "subclause".

**Comment by jensmaurer** [comment]
Editorial meeting: The term is "sub-clause" without hyphen.
