### ISSUE TITLE
"terminate is called" inconsistency

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#3079]
Clause [except] consistently says "the function `std::terminate` is called".

[support.start.term] says "the function `std::terminate` shall be called" (which is an incorrect use of "shall", and redundant `std`-qualification).

[terminate.handler] says "The type of a _handler function_ to be called by `std::terminate()` when terminating exception processing" (redundant qualification, completely bogus to use `()` when referring to a function by name, rather than describing a function call expression).

[execpol.seq], [execpol.par], [execpol.parunseq], and [execpol.unseq] say "`terminate()` shall be called" (incorrect "shall", unclear if it's trying to name the function or show a call expression, but arguably either is correct).

[stopsource] and [stopcallback.constr] (added by P0660R10, #3072) say "`terminate()` is called".

[thread.thread.constr] and [thread.jthread.constr] (the latter added by P0660R10 #3072) say "`terminate` shall be called" (incorrect "shall").

[thread.thread.destr] and [thread.thread.assign] say "calls `terminate()`".

[thread.condition.condvar] says "`terminate()` shall be called" many times (incorrect "shall").

This is a mess.

**Comment by jensmaurer** [comment]
See #2150.

**Comment by jensmaurer** [comment]
Editorial meeting: Use "call" for function call expressions; use "invoke" for abstract-machine-level discussion of control flow passing to another function. Also in [basic].
For this particular issue, "the function std::terminate is invoked" (no parens).

**Comment by languagelawyer** [comment]
> Editorial meeting: Use "call" for function call expressions; use "invoke" for abstract-machine-level discussion of control flow passing to another function.

This resolves [CWG2166](https://wg21.cmeerw.net/cwg/issue2166)

**Comment by jensmaurer** [comment]
@languagelawyer , CWG2166 has the title 'Unclear meaning of “undefined constexpr function” '. I fail to see a connection to call vs. invoke.

**Comment by languagelawyer** [comment]
@jensmaurer CWG2166 asks: undefined when? At the time of parsing ("call") or when really evaluated (invoked)? Are mutually-recursive `constexpr` functions allowed?

The resolution of editorial meeting answers: when really evaluated (invoked), the standard says _«expr is a const. expr unless it would evaluate ... an **invocation** of an undefined `constexpr` function»_. Mutually-recursive `constexpr` functions are allowed, bc a function can be undefined when is called, but defined when invoked.
