### ISSUE TITLE
Index footers say "Cross references"

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#308]
Looks like we're not setting new footer text when we transition from Annex F into the Indexes, and the footer text gets carried over.

**Comment by jwakely** [comment]
It's a bit of a hack, but adding this at the top of `back.tex` (i.e. before the indices start) gets rid of it:

    \renewcommand{\leftmark}{}

**Comment by jensmaurer** [comment]
Index pages currently say "Index" in the footer.

**Comment by tkoeppe** [comment]
I recall vaguely Doing Something at some point that addressed this.

**Comment by jwakely** [comment]
@tkoeppe you fixed it with 0bc04c584447d510d4d9a58553689cd405894fa2
