### ISSUE TITLE
kebab-case all the exposition only ranges types

### ISSUE THREAD

**Issue by cjdb** [cplusplus/draft#3097]
LWG asked for the exposition-only types in namespace ranges to universally be changed to _kebab-case_ in Cologne, so that it's easier to tell which types are public-facing, and which are exposition-only.

I've volunteered to make that change, but it's a good idea to make an issue to track it.

**Comment by jensmaurer** [comment]
@cjdb, The merge of the motions is now complete, except for the concepts renaming. Now is a good time to make the change and send a pull request.

**Comment by jensmaurer** [comment]
@cjdb, any updates here?

**Comment by cjdb** [comment]
Sorry, I haven't made time for this (but really should). Do you want a single commit, one commit per name change (but as a single PR), or many PRs?

**Comment by jensmaurer** [comment]
A single commit sounds fine for me.
