### ISSUE TITLE
Index of library names is inconsistent

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#310]
Some library names are keyed off of the class, and then have sub-entries for members.
Some are keyed off the member, and have sub-entries for the classes with that member.
Some names are listed both ways, some names are listed neither way.

Sometimes constructors are listed as

  bad_exception
      bad_exception, 1234

Sometimes constructors are listed as

  basic_filebuf
      constructor, 1234

We should pick rules for what goes in this index, and follow them.

**Comment by AlisdairM** [comment]
This is addressed by https://github.com/cplusplus/draft/pull/740

**Comment by jwakely** [comment]
#740 was merged
