### ISSUE TITLE
What are "Boolean contexts"?

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#3112]
In #3015, I ask:
>  In concepts.tex, we have this wording:
>      "The \libconcept{boolean} concept specifies the requirements on a type that is usable in Boolean contexts."
>   What are "Boolean contexts"?

and Casey replies:
> "Boolean context" is meaningless fluff which unfortunately can easily be conflated with "contextual conversion to bool". "...specifies the requirements on types of expressions used as predicates in other library concepts." would not be great, but is at least meaningful and won't lead readers astray.

We should fix this.

**Comment by jensmaurer** [comment]
Editorial teleconference: "usable in Boolean contexts" -> "usable as a truth value".
