### ISSUE TITLE
[class.copy.elision] Is the first example contradictory?

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#3117]
(In N4820) The first example says that
```
struct A {
  void *p;
  constexpr A(): p(this) {}
};

constexpr A g() {
  A a;
  return a;
}

constexpr A a;          // well-formed, a.p points to a
constexpr A b = g();    // well-formed, b.p points to b
```
However, if my understanding is correct, as copy elision (NRVO) is forbidden in constant initialization since CWG 2278, `b.p` shall point to the local variable `a` in `g` whose lifetime has ended.

**Comment by jensmaurer** [comment]
Editorial teleconference: Agreed, this is an error in second line of the example. Also change name of local variable "a" to avoid duplication of name.
