### ISSUE TITLE
Update [diff.cpp17.library] to match new headers since C++17

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#3122]
At least `<format>` is missing from this list; check for others too once we've merged all the motions.

**Comment by jwakely** [comment]
`<stop_token> <semaphore> <latch> <barrier>`

**Comment by zygoloid** [comment]
Turns out we're also missing <coroutine> from the list of headers. I have a patch.

**Comment by zygoloid** [comment]
(`<charconv>` and `<source_location>` are missing too.)

**Comment by CaseyCarter** [comment]
`<charconv>` is a C++17 header.

**Comment by jensmaurer** [comment]
I'll update the pull request.

**Comment by jensmaurer** [comment]
`<coroutine>` is already present in Annex C, but it's missing from [tab:headers.cpp].
