### ISSUE TITLE
Inconsistent Latex coding style used in clauses of \itemdescrs

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#3128]
We're inconsistent in the Latex coding style used for clauses of \itemdescrs.  Some clauses use 2 space indentation for the text (similar to \items), some place the text on the same line as \<clause_macro>, some place the \<clause_macro> and text on the same line as \pnum, etc..  Our [guidelines](https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines?) don't specify how they should be formatted.

Can we come up with some guidelines, document them, and do a global whitespace change to fix the old formatting style so that we can follow the guidelines when applying edits?

**Comment by jensmaurer** [comment]
`\pnum` should always be alone on a line, and we're pretty consistent about it.
The question is whether there should be text following `\effects`, for example, or whether that text should be on a new line. I'm not eager to have indentation here, btw.

**Comment by jensmaurer** [comment]
Editorial teleconference: Agreed with @jensmaurer's suggestions. Do not integrate \pnum with \markers to be able to find a paragraph by counting \pnum.
