### ISSUE TITLE
[diff] Inconsistent LaTeX source code style

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#3129]
We're inconsistent in the Latex coding style used for clauses in [diff.iso].  Some place the text on the same line as the <clause_macro>, others don't.  Our [guidelines](https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines?) don't specify how they should be formatted. I'd like to see us format them similarly to \items, where a single line is used if the text is short, and 2-space indentation is used for clauses which span multiple lines.

Can we come up with some guidelines, document them, and do a global whitespace change to fix the old formatting style so that we can follow the guidelines when applying edits?

**Comment by jensmaurer** [comment]
[diff.iso] is just "C++ and ISO C"; did you mean that, or did you mean all of [diff]?

**Comment by jensmaurer** [comment]
Editorial teleconference: We should absolutely document the policy.
Also consider ease of finding the source of a change. Probably made easier by current github "blame" view. Current approach mixes whitespace changes with semantic changes, which is worse than having a separate and early whitespace change.

**Comment by jensmaurer** [comment]
Editorial teleconference: \pnum should be on a line by itself.

**Comment by jensmaurer** [comment]
Editorial teleconference: Happier about global rules if/when we enforce them.

**Comment by jensmaurer** [comment]
Editorial teleconference: Newlines around "\rationale" etc. macros in diff.iso. Drop empty lines around "codeblock". Thus, no blank lines except to separate differences.
