### ISSUE TITLE
consistently use hyphens instead of underscores as word separators in placeholders

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#3130]
We decided that we want to use hyphens instead of underscores to separate words in placeholders (eg, *`node-handle`*), to further emphasize these components are not *identifier*s, but have not consistently applied this across the wording. For example, in 20.15.7.6, we have * `COMMON_REF`* and *`COND_RES`*.

This change should be applied everywhere.

**Comment by jensmaurer** [comment]
I've tried to apply this consistently, but apparently have missed a few spots. Except for the examples you gave, are there any other occurrences you could enumerate?
