### ISSUE TITLE
In Latex sources, do columns start counting at 0 or 1?

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#3131]
Our coding style [guidelines](https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines?) say that the starting columns for comments in examples should be multiples of 4, but starting from where?  If we start counting at 1, the examples' comments in [diff.cpp17.dcl.dcl] start on column 25, suggesting that at least those comments start counting from 0, while other comments (including the ones I've edits) assume we start counting at 1.  Which is correct?  Example from compatibility.tex:
```
  void f() {}           // ill-formed; previously well-formed
0         1         2
0123456780912345678091234 does the above comment start on column 24?
1234567809123456780912345 or on column 25?
```
FWIW, the comments in the guideline's own Latex example text start on column 48 when counting from 1, suggesting that whoever wrote the guidelines was thinking they should start at 1:
`\begin{note}                                   %% own lines if possible
`

The guidelines should be fixed to specify, and the examples fixed to adhere to them.

**Comment by johelegp** [comment]
The example is correct. The first/zeroth column is a multiple of 4.

**Comment by tkoeppe** [comment]
Maybe a better way to say this is that "the number of spaces preceding a comment should be a multiple of four".

**Comment by johelegp** [comment]
Most comments aren't preceded by spaces only. We also can't say just characters, as that'd be ambiguous between source characters (LaTeX) and rendered characters (using `\placeholder` requires readjusting). What actually matters is that the number of characters preceding a rendered comment is a multiple of four.

**Comment by tkoeppe** [comment]
Yes, sorry, that's what I meant. (And indeed, if you have macros in the source, you need to know how many characters they expand to, which is something I try to document as part of the macro in cases that come up a lot, like `\commentellip`.)

**Comment by jensmaurer** [comment]
Editorial teleconference: @tkoeppe's is the right rule.
