### ISSUE TITLE
[atomics.wait] Add an index for "eligible to be unblocked" under "atomic"

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#3132]
The wording for P1135R6 in #3093 added a definition for "eligible to be unblocked" in [atomics.wait].  Please add an index for this so it can be found under "atomic waiting operation".

Does it also make sense to move the index entries for "atomic waiting operation" and "atomic notifying operation" under "atomic operation" or "atomic!operation"?

**Comment by jensmaurer** [comment]
We don't yet have "atomic!anything", but it seems to make sense to group the 5 or so index entries relating to memory model "atomic" there. (Atomic constraints are different, and should not be so grouped.)
