### ISSUE TITLE
[ranges] Merge range adaptor specs into overview paragraphs

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#3134]
Merge range adaptor/range adaptor object specs into overview paragraphs, similarly to how this was done in [range.split.adaptor] in #3106.

**Comment by johelegp** [comment]
Context at https://github.com/cplusplus/draft/pull/3106#discussion_r309441151:
> Aside: I've been trying to eradicate the archaic "introductions are semi-normative" belief when it pops up in LWG.
> 
> This text changed between R6 and R7 because (1) LWG was unhappy that the example uses `view::elements` so far from any description thereof, and (2) LWG dislikes the single-paragraph subclauses used to specify the range adaptor objects in general. We decided to merge the range adaptor object spec into this overview paragraph, and there was encouragement to editorially change the other range adaptor / range adaptor object specifications similarly.
