### ISSUE TITLE
fix use of "for some" throughout [ranges]

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#3136]
In [ranges] (and possibly elsewhere in range-related wording) we find utterances such as:

> Within this clause, for some integer-like type X (23.3.4.4), make-unsigned-like-t(X) denotes make_unsigned_t<X> if X is an integer type;

and

> For some subexpressions E and F, the expression view::take_while(E, F) is expression-equivalent to take_while_view{E, F}.

These are uniformly wrong; they mean "for any" or "for given" (∀) not "for some" (∃).

**Comment by CaseyCarter** [comment]
We discussed this in LWG Cologne: I was instructed to file an editorial issue to omit the "some" in all of these cases. (Notably this contradicts the guidance LWG gave me in Batavia and/or San Diego to add the "some"s.)

I'll prepare a PR for this.
