### ISSUE TITLE
Confusing wording in CWG2300 regarding definitions and token sequences

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#3155]
CWG2300 appended wording to the first bullet of [basic.def.odr]p12.1 so it now reads:

> Given such an entity named D defined in more than one translation unit, then
>     - each definition of D shall consist of the same sequence of tokens, for which the definition of a closure type is considered to consist of the sequence of tokens of the corresponding /lambda-expression/; and

What are we saying here?  Can this be clarified editorially?

**Comment by jensmaurer** [comment]
Editorial teleconference: replace "for which" -> "where".

**Comment by zygoloid** [comment]
> each definition of *D* shall be formed from the same sequence of tokens, where:
>  * a definition produced by a declaration is formed from the sequence of tokens in its declaration, and
>  * a definition of a closure type is formed from the sequence of tokens in its *lambda-expression*; and
