### ISSUE TITLE
What is "the initialization full-expression" ??

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#3156]
CWG2366 introduced the term "initialization full-expression" but never defined it.  What exactly are we talking about here?  The spec never actually defines what an initialization is or what it consists of from a grammar stand-point either, so no clues there.

We've used the following related wording elsewhere:
* the full-expression of the initialization
* the part of the full-expression that performs the initialization
* any full-expression in its /initializer/

If we can't come up with a definition editorially, can we reword the text to use one of the forms above so that we're not introducing a new term?

**Comment by jensmaurer** [comment]
Editorial teleconference: First bullet would work.
