### ISSUE TITLE
[thread.jthread.class] suggests the thread joins itself

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#3157]
As I said at https://github.com/cplusplus/draft/pull/3072#pullrequestreview-266507401 I think this wording is unclear and inaccurate:

> The functionality is the same as for class `thread` (32.4.2) with the additional ability to request that the thread stops and then joins the started thread.

The threads referred to as "the thread" and "the started thread" are actually the same thread, so this says "the ability to request that the thread stops and then joins itself" which is not what the class does.

I suggest:

> The functionality is the same as for class `thread` (32.4.2) with the additional abilities to provide a `stop_token` (32.3) to the new thread of execution, make stop requests, and automatically join.

**Comment by jensmaurer** [comment]
Sounds good.
