### ISSUE TITLE
[support.srcloc] It's underspecified whether copy/move functions of source_location are constexpr or not

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#3170]
Since the actual data members of `std::source_location` are not precisely specified, leaving these special member functions (copy/move constructor and copy/move assignment operator) implicitly declared might be insufficient to make them usable in constant evaluation.

I think it might be better to specify them as `constexpr`, either in the synopsis or in [source_location.syn]/3.

**Comment by frederick-vs-ja** [comment]
Or can we just specify that `std::source_location` is a trivially copyable type?
An implementation of `std::experimental::source_location` by [gcc libstdc++](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/experimental/source_location) (which is the only implementation I can find) is already trivially copyable.

**Comment by jensmaurer** [comment]
Sounds like a LWG issue to me.

**Comment by jensmaurer** [comment]
Submitted to lwgchair.

**Comment by jensmaurer** [comment]
According to www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1208r6.pdf, it is intentionally unspecified (by absence) whether these functions are trivially copyable. We could assume the same applies to "constexpr".
