### ISSUE TITLE
[over.match.funcs, ...?] Consider shunning single-item lists

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#3176]
For example:
- https://github.com/cplusplus/draft/blob/173905005c2c419548418239518db72bfda9dd9a/source/overloading.tex#L1381
- https://github.com/cplusplus/draft/blob/173905005c2c419548418239518db72bfda9dd9a/source/overloading.tex#L1431

These look pretty weird. I think a "let's avoid single-item lists" rule would probably make sense for the Specification Style Guidelines wiki page. :)

**Comment by jwakely** [comment]
I think this is to mirror the presentation in [over.match.copy] which has a very similar "the candidate functions are selected as follows:" sentence followed by a two-bullet list. Using similar formats for those three paragraphs is nice, although I agree that a one-bullet list is ugly now that we number the bullets.

**Comment by jensmaurer** [comment]
Editorial teleconference: No general prohibition against single-item bulleted lists. Review individual bulleted lists that are objectionable. [over.match.conv] and [over.match.conv] are fine.

[over.match.funcs] p5: fix by removing "an additional rule applies" and remove bullet.
