### ISSUE TITLE
[memory.syn] LWG 3303: ExecutionPolicy overloads of destroy/destroy_n shoudn't be constexpr

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#3181]
It would be better to be consistent with other algorithms.

**Comment by jensmaurer** [comment]
Submitted to lwgchair.

**Comment by zygoloid** [comment]
(For future reference, these functions were added by [P0784R7](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0784r7.html), which specifies that they are `constexpr`.)

**Comment by Dani-Hub** [comment]
A corresponding LWG issue has been created: [LWG 3303](https://cplusplus.github.io/LWG/issue3303)

**Comment by AlisdairM** [comment]
Resolved by P2051R0 in Prague
