### ISSUE TITLE
\placeholer{} adds a space

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#319]
In e-mail from Richard:
Dawn: - \placeholder{} appends a space after its contents, which prevents it from being used inside other macros.  For example, "\tcode{is_reference<\placeholder{R}>::value}" turns into "is_reference<R >::value".  How to fix/workaround?  Should I remove space from macro and add extra space after all uses of \placeholder{} in spec where a space is desired?

Richard: Yes, please fix the macro. It shouldn't be adding a trailing space.

**Comment by tkoeppe** [comment]
@burblebee, @zygoloid: Do you want to go ahead with changing `}\placeholder{X}\tcode{` into `\placeholder{X}`? I think that's the right course of action, though Issue #326 discusses an alternative.

**Comment by burblebee** [comment]
On Fri, Dec 11, 2015 at 02:21:50AM -0800, Thomas Köppe wrote:
> @burblebee, @zygoloid: Do you want to go ahead with changing `}\placeholder{X}\tcode{` into `\placeholder{X}`? I think that's the right course of action, though Issue #326 discusses an alternative.

Fine with me.  Thanks for doing this!

**Comment by burblebee** [comment]
Can we close this now?  The fix to the \placeholder macro was merged was it not?

**Comment by burblebee** [comment]
Fixed in the following master commits.

Fix for placeholder macro:
* ddf0f80b00e084c5ae245a1c0577dcec356cd30e -
Uses applied to text:
* eb6d427e325f4ddb19280da10ebb387ba8498575
* 9ae00ff477891539b51275e81bd3437c416ee0d3
* 4926f71c3749dacf3a6ee3b6d34cfc110e66c48b
* 776c1fe21ad8725a8d1e4ca66baa0d8565feb62d
* 63305182f3c7efba1dbcaf35d1799e2fc95611b4
