### ISSUE TITLE
[cpp.import] Import directive is deleted at the end of translation phase 4

### ISSUE THREAD

**Issue by RazvanAM** [cplusplus/draft#3201]
[P1703](http://open-std.org/JTC1/SC22/WG21/docs/papers/2019/p1703r1.html) states that a line starting with the `import` preprocessing token is a preprocessing directive.

Such a line is processed first by the preprocessor (in translation phase 4, in order to import macro definitions) and it should also be processed in translation phase 7 (in order to import declarations). However, because such a line is a preprocessing directive, it is removed at the end of translation phase 4.

Is there something that I am overlooking?

Thank you.

**Comment by RazvanAM** [comment]
I think one of the purposes of [[cpp.import] p.2](http://eel.is/c++draft/cpp.import#2) is to say that the import directive is entirely replaced by the same tokens, except for the mentioned changes (e.g. `import` token replaced by the `import-keyword` token).

**Comment by jensmaurer** [comment]
Editorial teleconference: This area is in flux and likely to change next time.

**Comment by jensmaurer** [comment]
There are now clarifying notes in cpp.module:

> The module and export (if it exists) preprocessing tokens are replaced by the module-keyword and export-
keyword preprocessing tokens respectively.
> [Note 2 : This makes the line no longer a directive so it is not removed at the end of phase 4. — end note]

and in cpp.import:

> In all three forms of pp-import, the import and export (if it exists) preprocessing tokens are replaced by the
import-keyword and export-keyword preprocessing tokens respectively.
> [Note 1 : This makes the line no longer a directive so it is not removed at the end of phase 4. — end note]
