### ISSUE TITLE
Improve cv-combination note

### ISSUE THREAD

**Issue by opensdh** [cplusplus/draft#3205]
The note in [conv.qual]/3,

> [_Note_: Given similar types `T1` and `T2`, this construction ensures that both can be converted to the cv-combined type of `T1` and `T2`. — _end note_]

is close to being vacuous: A can be converted to B precisely when cvc(A,B)=B, so saying that T1 can be converted to cvc(T1,T2) is saying that cvc(T1,cvc(T1,T2))=cvc(T1,T2).  It seems obvious that an operation like cv-combination should be **idempotent** in this sense (here, the unary function cvc(T1,&middot;)); it is also reasonable that it should be **symmetric** (the reference to P<sub>i</sub><sup>1</sup> at the end of /3.2 damages that, but only in cases that are irrelevant anyway).  If any note is needed, it is one that reassures the reader that those two properties hold (in all the cases that matter).

**Comment by jensmaurer** [comment]
The whole point of notes is being vacuous and stating the sort-of obvious.

**Comment by jensmaurer** [comment]
Editorial teleconference: If we want any note here at all, the note is saying the right thing for the programmer. No motivation for a change.
