### ISSUE TITLE
grammar terms are indistinguishable from defined terms

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#323]
This issues was raised by Gaby - that you can't tell definitions from grammar terms, because both are _italics_.  Maybe use **_bold italics**_ for one of those - like the definition?

**Comment by jensmaurer** [comment]
This depends on #701.

**Comment by tkoeppe** [comment]
Sans-serif (whether slanted or upright) wouldn't be a terrible solution. Maybe we could test-drive that change and see how we feel about it. Sample boards welcome.

**Comment by jensmaurer** [comment]
Now that #701 is addressed, we can make progress here. A sample for [class] is attached. Note p5, where we have all the different typefaces in one sentence.

![class](https://user-images.githubusercontent.com/23412755/33505613-5e6ada0a-d6ec-11e7-9408-23a60f708534.png)

**Comment by jwakely** [comment]
I like it.

**Comment by zygoloid** [comment]
Just playing with `\tcolorbox`:

![screenshot from 2017-12-01 14 45 28](https://user-images.githubusercontent.com/232783/33506840-5bf18292-d6a6-11e7-96b3-58511f733f3f.png)

**Comment by jensmaurer** [comment]
Well... I just had a look at the \tcolorbox manual, and the table of contents looks ... wow.

I think the fundamental question here is whether we want to leave the realm of traditional black-on-white printer-style typesetting or not. (Maybe ISO Central Secretariat has an opinion, too.) If the former, we should (for example) consider boxing all the examples and notes, as well as the grammar snippets and the itemdecls.

At the current state of black-on-white, boxing the \grammarterms (and nothing else) seems misguided to me, and hurts my eyes: "Here is a large blue boxed \grammarterm. Better pay attention. We will throw it right in your face. But we didn't bother to box the grammar definitions, sorry about that."

**Comment by tkoeppe** [comment]
I think the typographical principle of minimal distinction applies here: if we're changing the typeface, then we don't also need to make it italic. Try just upright sans-serif for the grammar terms, I bet that looks good, too.

**Comment by jensmaurer** [comment]
Here you are:

![class](https://user-images.githubusercontent.com/23412755/33508153-8a188ae0-d6f0-11e7-9433-caa182c9b4cb.png)

**Comment by tkoeppe** [comment]
(Could you perhaps make slightly higher-resolution screenshots?)

**Comment by jensmaurer** [comment]
Here you are:

![class](https://user-images.githubusercontent.com/23412755/33508274-bd7edb88-d6f9-11e7-9b70-2e70bc67e940.png)

**Comment by zygoloid** [comment]
I'm afraid I don't like it as much as the slanted form. The transition between typefaces looks really jarring, almost as if the grammar names and extracts are screenshots of some other document. (I'm not sure why I don't get the same impression from the slanted form.) And conversely, the transition in typeface between the end of a grammar term and a following "s" is not distinctive enough to give a clear transition between the grammar term and the suffix.

**Comment by tkoeppe** [comment]
Yes, I agree that the distinction is ultimately too subtle to be effective.

**Comment by godbyk** [comment]
You might try small caps (\textsc or \scshape). It's less jarring than changing typefaces and is obviously different than plain italics.

**Comment by tkoeppe** [comment]
@godbyk: I like that idea! Not only does it allow us to not introduce a new typeface, but it also plays more nicely with the start of sentences. Though that said, I'm now wondering whether we shouldn't use small-caps for *definitions* and retain the familiar italics for grammar terms!

**Comment by godbyk** [comment]
Note, though, that it is still difficult to distinguish between a `\textsc{s}` and a regular `s`.

**Comment by jensmaurer** [comment]
For completeness, here's a version with \textsc:

![class](https://user-images.githubusercontent.com/23412755/33513169-826968c6-d73d-11e7-9a32-de4a3f74aa58.png)

**Comment by tkoeppe** [comment]
@jensmaurer: What about the other way round, use small caps for definitions?

**Comment by jensmaurer** [comment]
@tkoeppe: We have not progressed far enough with #329 to make this an imminent option, but here you are:
![class](https://user-images.githubusercontent.com/23412755/33519998-89089d4e-d7b2-11e7-86bf-3c5d5cdb0489.png)

**Comment by tkoeppe** [comment]
@jensmaurer: I don't think any font change is imminent at this point :-)

I do quite like small caps for definitions. I'm not all that fond of small caps for grammar terms. Grammar terms get repeated, and I quite like our existing italics. Definitions appear only once, so I can get behind using small caps there -- there's a fair bit of typographic tradition for that, too.

**Comment by zygoloid** [comment]
How does the small-caps-for-definitions look for "contextually converted to `bool`" and other terms with embedded `\texttt`? (We may want to entirely move away from code font in defined terms, but if we can find a formatting for definitions that permits it without too much ugliness, that might be a point in its favour.)

**Comment by jensmaurer** [comment]
I'd like to point out that we already use \textsc for NTBS and similar acronyms in [library] (both definition and use employ `\textsc`).

@zygoloid: Ugh, turns out [conv] is lagging behind on `\term` -> `\defn` adjustments; see #1880. Here you are, anyway:
![class](https://user-images.githubusercontent.com/23412755/33674461-f12f8cde-daaf-11e7-8b30-078da9a6f9e3.png)

**Comment by zygoloid** [comment]
We also tried bold for definitions, which doesn't really work because the weight of the bold font is too close to that of teletype.

My preference currently is small-caps for definitions. We should also stop using small-caps for NTBS, except in the definition of it. (Note that using small-caps for NTBS means that search for "NTBS" in some PDF viewers doesn't find it! This switches from a bug into a feature when used for defined terms.)

**Comment by tkoeppe** [comment]
Editorial meeting consensus: we explored several options, and even though we *could* pursue any one of them (with small caps definitions being the most popular), there's a big cost of upsetting the status quo and the familiarity of the many users of the standard. The issue is ultimately not all that pressing. Several other language specifications use a similar style to ours, and it's good enough. In many cases, grammar terms have peculiar spelling (e.g. hyphens) that makes them quite obvious, and so we consider the status quo good enough for the time being.

**Comment by jensmaurer** [comment]
New motivation presented in #3197.

**Comment by tkoeppe** [comment]
@jensmaurer  Ping https://github.com/cplusplus/draft/issues/323#issuecomment-348643129?

**Comment by jensmaurer** [comment]
\definecolor{light-gray}{gray}{0.2}
\newcommand{\GrammarStylex}[1]{{\sffamily\itshape\textcolor{light-gray}{#1}}}

looks reasonable, except for the absence of italics correction (visible for trailing "s"). Keep standard black for BNF blocks.
