### ISSUE TITLE
[range.elements.overview] LWG 3302: range adaptor objects `keys` and `values` are unspecified

### ISSUE THREAD

**Issue by morinmorin** [cplusplus/draft#3231]
They are listed in [ranges.syn], but not specified in [range.elements.overview]. Most probably `keys` would work as `elements<0>` and `values` would work as `elements<1>`. But neither N4830 nor [P1035R7](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1035r7.pdf) has such specification. I'm not sure if this issue can be resolved editorially.

Additionally, there are no index entries for `keys_view` and `values_view`.

**Comment by jensmaurer** [comment]
That sounds non-editorial.

**Comment by morinmorin** [comment]
If you want me to submit an LWG issue, I'll take care of it.

**Comment by jensmaurer** [comment]
That would be nice. Missing descriptions are not editorial.
(Missing index entries are, though.)

**Comment by morinmorin** [comment]
OK, I'll do that today. Thanks for the help!

**Comment by CaseyCarter** [comment]
Poor Chris revised P1035 no less than 16 times in Cologne. IIRC we wanted to specify `keys` and `values` directly in the synopsis simply as names for `elements<0>` and `elements<1>`. It looks like we made it half way there by striking [range.keys.adaptor] and [range.values.adaptor] - which specified `views::keys` and `views::values` - but failed to make the corresponding changes to the synopsis.

@morinmorin, if I may suggest a proposed resolution for your issue, I believe our intent was:
> Change [ranges.syn] as follows:
> ```diff
>  template<class R>
>    using keys_view = elements_view<all_view<R>, 0>;
>  template<class R>
>    using values_view = elements_view<all_view<R>, 1>;
>  
>  namespace views {
>    template<size_t N>
>      inline constexpr unspecified elements = unspecified;
>-  inline constexpr unspecified keys = unspecified;
>-  inline constexpr unspecified values = unspecified;
>+  inline constexpr auto keys = elements<0>;
>+  inline constexpr auto values = elements<1>;
>  }
> ```

**Comment by cjdb** [comment]
LGTM

**Comment by morinmorin** [comment]
@CaseyCarter, thanks for the suggestion. I should have asked you for the help before sending the issue to LWG.

I'll soon resend a modified one that replaces the old PR
```diff
 -3- `keys_view` is an alias for `elements_view<all_view<R>, 0>`…
 
+-?- The name `views::keys` denotes a range adaptor object (24.7.1). 
+For some subexpression `E`, the expression `views::keys(E)` is 
+expression-equivalent to `elements_view<all_view<decltype((E))>, 0>{E}`.
 
 -4- `values_view` is an alias for `elements_view<all_view<R>, 1>`…
 
+-?- The name `views::values` denotes a range adaptor object (24.7.1). 
+For some subexpression `E`, the expression `views::values(E)` is 
+expression-equivalent to `elements_view<all_view<decltype((E))>, 1>{E}`.
```
with the suggested PR.

**Comment by jensmaurer** [comment]
@morinmorin, do you have an LWG issue number for tracking?

**Comment by morinmorin** [comment]
@jensmaurer, I don't have an issue number yet. I'll post the number here, when I receive it. (I submitted another issue a day before submitting this to LWG, and that one got the number 3301 earlier today.)

**Comment by Dani-Hub** [comment]
A corresponding LWG issue has been created now: [LWG 3302](https://cplusplus.github.io/LWG/issue3302).

**Comment by johelegp** [comment]
> Status: WP
