### ISSUE TITLE
[ranges] Range adaptor/factory objects not indexed

### ISSUE THREAD

**Issue by morinmorin** [cplusplus/draft#3232]
Range adaptor objects (`filter`, `transform`, ...) and factory objects (`iota`, ...) are not indexed.

**Comment by jensmaurer** [comment]
#3233 has landed.

**Comment by morinmorin** [comment]
It looks like #3280 adds index entries for range adaptors (`filter_view`, `transform_view`, …) but not for range adaptor objects (`filter`, `transform`, …) or range factory objects (`iota`, …).

BTW, do we add index entries for `keys_view` and `values_view` from [ranges.sys]? (While they also appear at [range.elements.overview], `keys` and `values` would only appear at [ranges.sys].)

**Comment by morinmorin** [comment]
@jensmaurer, if you could guide me what macro to use for indexing range adaptor objects (and range factory objects), I'll make a PR.

Thanks.

**Comment by jensmaurer** [comment]
I'd really like to fix this while addressing #3134, otherwise there will be a lot of editing conflicts.

**Comment by morinmorin** [comment]
Sure, no hurry :)
I missed that issue. Thanks for pointing it out.
