### ISSUE TITLE
[over.match.viable] footnote is incorrect

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#3235]
[\[over.match.viable\]](eel.is/c++draft/over.match.viable#2.3.sentence-1):

> A candidate function having more than *m* parameters is viable only if the *(m+1)*<sup>st</sup> parameter has a default argument ([dcl.fct.default]).<sup>124</sup>

and [footnote 124](http://eel.is/c++draft/over.match.viable#footnote-124) says:

> According to [dcl.fct.default], parameters following the *(m+1)*<sup>st</sup> parameter must also have default arguments.

However, according to [\[dcl.fct.default\]](http://eel.is/c++draft/dcl.fct.default#4.sentence-4), subsequent parameters do not need to have default arguments if they were expanded from a parameter pack.

```c++
template<class ... T> struct C {
  void f(int n = 0, T...);
};
C<int> c;                       // OK, instantiates declaration void C​::​f(int n = 0, int)
```

**Comment by cpplearner** [comment]
The relevant wording in [dcl.fct.default] was introduced by [CWG 2233](https://wg21.link/cwg2233).

**Comment by jensmaurer** [comment]
This seems to be a "should have CWG eyes" editorial issue.

**Comment by jensmaurer** [comment]
Registered at http://wiki.edg.com/bin/view/Wg21belfast/CoreWorkingGroup , uploaded to http://wiki.edg.com/pub/Wg21belfast/CoreWorkingGroup/ed-3235.html .

**Comment by jensmaurer** [comment]
CWG teleconference: This is a normative change and will be handled by a CWG issue.

**Comment by cpplearner** [comment]
Fixed by [CWG 2442](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1968r0.html#2442) (commit fd20a44f095fdfbb578f6a2a4f7269997be80b17).
