### ISSUE TITLE
[locale] Example calls time_put::put with ios_base::iostate& but there is no such overload

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [cplusplus/draft#3238]
[\[locale\] paragraph 3](http://wg21.link/locale#3) is this example: https://github.com/cplusplus/draft/blob/e287e8227303672b78e01c44020087e644411d4e/source/locales.tex#L180-L203

In the `put(s, s, s.fill(), err, &tmbuf, 'x')` call, the fourth argument seems intended to be reference to `ios_base::iostate err`. However, in both `put` member functions in [\[locale.time.put.members\]](http://wg21.link/locale.time.put.members), the fourth parameter is `const tm* t`:
https://github.com/cplusplus/draft/blob/e287e8227303672b78e01c44020087e644411d4e/source/locales.tex#L3977-L3980

I suppose the definition and uses of `ios_base::iostate err` should be deleted from the example, and the code should instead call `ostreambuf_­iterator<charT, traits>::failed()`, like in [\[ostream.inserters.arithmetic\]](http://wg21.link/ostream.inserters.arithmetic).

If I understand correctly, the example is non-normative text, making this an [editorial issue](https://github.com/cplusplus/draft/wiki/How-to-tell-if-an-issue-is-editorial).

**Comment by jensmaurer** [comment]
Please have a look at the pull request. Does this fix look correct?

**Comment by KalleOlaviNiemitalo** [comment]
As I commented in <https://github.com/cplusplus/draft/pull/3242#pullrequestreview-292707384>, the change looks OK.

**Comment by zygoloid** [comment]
There's no such thing as `ios_base::iostate::goodbit` either :) I guess no-one ever tried compiling this example.
