### ISSUE TITLE
Mis-application of a bit of p1463r1

### ISSUE THREAD

**Issue by mclow** [cplusplus/draft#3257]
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1463r1.pdf

in [list.ops]/25, it adds the text "get_allocator() == x.get_allocator is true."
and removes the text "The behavior is undefined if get_allocator() != x.get_allocator"

When this paper was applied in commit 019baa941945c1c8529fcaa0288ed5e98944f7a4, the second text was removed (correctly), but the text that was added was "get_allocator() != x.get_allocator is true."   ('!=' instead of '==')

**Comment by tkoeppe** [comment]
I can take this one. We also don't seem to have the edit `, and`, do you also want that (re-)instated?

**Comment by mclow** [comment]
I like the `, and`, but if that doesn't match the rest of the standard, I can live w/o it.
On the other hand, [forwardlist.ops]/22 does have the "and".

**Comment by tkoeppe** [comment]
I agree. It's awkward to start a sentence with a symbol. I'll reinstate both.
