### ISSUE TITLE
Upper-case vs Lower-case for expressions

### ISSUE THREAD

**Issue by BRevzin** [cplusplus/draft#3271]
Throughout the language part of the standard, arbitrary expressions are introduced in lower-case, .e.g:

> The set of _potential results_ of an expression `e` is defined as follows: 

And arbitrary types are introduced in upper-case, e.g.:

> A class type `T` must be complete if:

Both of those are from [basic.def.odr], but it's consistent throughout the language section. 

<hr />

Much of the new library wording from Ranges breaks this convention by introducing expression in upper-case in all the definitions of the CPOs. For instance, from [range.access.begin]:

> The expression `ranges​::​​begin(E)` for some subexpression `E` is expression-equivalent to: 

Is there a particular reason why the Ranges wording uses capital letters for expressions instead of lower-case?

**Comment by jensmaurer** [comment]
[algorithms] uses "Let $E$ ..." (using E as a meta-variable for an expression) pervasively.

@CaseyCarter, any opinion here?

**Comment by CaseyCarter** [comment]
IIRC [algorithms] inconsistently used both `\tcode{E}` and `$E$` as expression placeholders before applying P0896. We chose to use the former as precedent for the placeholder in the CPO specifications. The change to use `$E$` consistently throughout [algorithms] happened in San Diego when I was integrating all of the range algorithm specifications into the `std` flavors.

I have a mild preference for `$E$` - whose slanted font makes it "clearly" a meta-syntactic variable - over `e` - which is itself valid syntax for a C++ expression - as a placeholder, but I'll agree that any consistent style would be an improvement over what's in the working draft right now.

**Comment by jensmaurer** [comment]
The general idea for `\tcode` vs. (e.g.) math formatting is that the former could be valid source code, given the right environment, whereas the latter is used for meta-variables in other situations, such as "atomic operations" or similar. So, using `$E$` in the [algorithms] section for stuff that looks like valid code snippets is questionable. However, using lowercase "e" for the CPO specification (in harmony with the core language section) might make sense.

**Comment by jensmaurer** [comment]
Editorial meeting:
- Do we want a consistent capitalization convention for the core language part, for types vs. expressions.
- Do we want to apply this to the library part as well?
- What should the convention be?

**Comment by tkoeppe** [comment]
![image](https://user-images.githubusercontent.com/6378233/68156400-aa814100-ff43-11e9-9052-47f9dfbbbbbc.png)

**Comment by jensmaurer** [comment]
Editorial meeting: Use math variables for everything, including types. `\placeholder` remains for exposition-only names and forming parts of an identifier. Range-based for: explain range/begin/end as exposition-only identifiers. Use $T$ primarily, possibly with index for types. Additionally, use $U$, $V$ for types unrelated to $T$. Use $E$ for expressions, possibly with subscript.

**Comment by jensmaurer** [comment]
See also #326, #3139.
