### ISSUE TITLE
[dcl.fct] parameter-type-list should be non-hyphenated, and inconsistent use

### ISSUE THREAD

**Issue by 18** [cplusplus/draft#3281]
The definition [parameter-type-list](http://eel.is/c++draft/dcl.fct#def:parameter-type-list) is not a grammatical production, but by being hyphenated it is very similar to the naming scheme for grammatical productions. We should consider changing it to *parameter type list* to avoid confusion.

Additionally, [[intro.defs]](http://eel.is/c++draft/intro.defs) references "parameter type list" rather than the defined "parameter-type-list" on four occasions. Depending on what course of action is chosen for the above issue, it should be updated accordingly.

**Comment by jensmaurer** [comment]
We have intentionally used a hyphenated term here, similar to odr-use. Grammar non-terminals are always in italics, so the confusion potential seems minimal.
I'll fix [intro.defs].
