### ISSUE TITLE
[basic.def.odr] Variable templates are not excepted from ODR

### ISSUE THREAD

**Issue by aaronpuchert** [cplusplus/draft#3289]
[[basic.def.odr]/12](http://eel.is/c++draft/basic.def.odr#12) mentions inline functions, inline variables and function templates, but no variable templates. I think this is an oversight. For example, [n4424](http://open-std.org/JTC1/SC22/WG21/docs/papers/2015/n4424.pdf) says in the introduction: "inline functions can be defined in multiple translation units (and must be defined in all translation units in which they are odr­-used), but all such definitions must be the same. The same is true (through a different mechanism) for functions and variables instantiated from templates."

**Comment by zygoloid** [comment]
I've requested that Mike open a core issue for this.

**Comment by zygoloid** [comment]
Filed as [CWG2433](http://wg21.link/cwg2433).

**Comment by aaronpuchert** [comment]
Thanks!
