### ISSUE TITLE
[duration.cast, time.point.cast] Better subclause names

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#3298]
These subclauses are named after the entities they originally described, `duration_cast` and `time_point_cast`. Since C++17, they also describe `floor`, `ceil` and `round` entities, so better subclause names are in order. Perhaps also consider folding the single-entity subclause [time.duration.alg] "Algorithms" holding `abs` into [duration.cast].

**Comment by jwakely** [comment]
Does the benefit of renaming these outweigh the cost though?

**Comment by johelegp** [comment]
I wonder. I couldn't think of any reasonable suggestion. I noticed this when I couldn't find the rounding functions in the table on contents.

**Comment by johelegp** [comment]
The best I could think of was moving the rounding functions to their own subclause, but that'd create more single-item subclauses, which are discouraged.

**Comment by jwakely** [comment]
Use the index or the search function in your favourite pdf reader.

**Comment by jensmaurer** [comment]
I agree the heading "duration_cast" is misleading if this has more similar functions. Something like "Conversions" sounds plausible.
