### ISSUE TITLE
inconsistent formatting for "underlying type"

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#330]
"underlying type" is defined in basic.tex 3.9.1 [basic.fundamental] p5, is used throughout the spec, yet is formatted as a \term{} only in declarations.tex 7.2 [dcl.enum] p9.

**Comment by jensmaurer** [comment]
I'd like to point out that "underlying type" in 3.9.1 refers to the base type for wchar_t, char16_t, and char32_t, whereas "underlying type" in 7.2p9 talks about the underlying type of an enumeration.  These two definitions, strictly speaking, have nothing to do with each other.

Am I understanding correctly that this editorial issue strives to add italics to the introduction of the term "underlying type" for enumerations in 7.2p5 "Each enumeration also has an underlying
type." ?
