### ISSUE TITLE
make-unsigned-like and make-unsigned-like-t are too similar

### ISSUE THREAD

**Issue by CaseyCarter** [cplusplus/draft#3300]
[ranges.syn]/1 defines an exposition only function _`make-unsigned-like`_ and an exposition-only metafunction _`make-unsigned-like-t`_. These two names are hard to distinguish, doubly so with an argument list:

>  _`make-unsigned-like(meow)`_ vs. _`make-unsigned-like-t(woof)`_. 

It would help somewhat if _`make-unsigned-like-t`_ were treated as an exposition-only alias template:

>  _`make-unsigned-like(meow)`_ vs. _`make-unsigned-like-t<woof>`_ 

but ideally the names themselves should be more distinct as well. [@jwakely suggests](https://github.com/cplusplus/draft/pull/3299/files/ad046bfccbb3d34dac34ba73ab5645fd73ba614b#r335210466) renaming _`make-unsigned-like`_ to _`as-unsigned-like`_ or _`to-unsigned-like`_, which preserves the intended similarity between _`make-unsigned-like-t`_ and `make_unsigned_t`.

(As discussed in https://github.com/cplusplus/draft/pull/3299#discussion_r335187689).

**Comment by jensmaurer** [comment]
Editorial meeting: When we have exposition-only foo and foo-t, their relationship should be the same as any other bar and bar_t. That's not the case here. Rename "make-unsigned-like" to "to-unsigned-like".
