### ISSUE TITLE
[basic.fundamental]p4 misquotes C

### ISSUE THREAD

**Issue by AaronBallman** [cplusplus/draft#3310]
The note in [basic.fundamental]p4 (http://eel.is/c++draft/basic.fundamental#4.sentence-5) is incorrect if it's relying on the C standard to provide that guarantee. The C standard states that padding bits *can* cause trap representations. See C17 footnote 53:

> Some combinations of padding bits might generate trap representations, for example, if one padding bit is a parity bit. Regardless, no arithmetic operation on valid values can generate a trap representation other than as part of an exceptional condition such as an overﬂow, and this cannot occur with unsigned types. All other combinations of padding bits are alternative object representations of the value specified by the value bits.

**Comment by zygoloid** [comment]
The C++ specification generally does not rely on the C core language specification. (The C standard library is incorporated by reference, but the C++ core language specification is standalone.) The purpose of this reference to C is to point out the intentional difference between the two languages. This should be clarified if it's causing confusion.

**Comment by AaronBallman** [comment]
I think it is a bit confusing -- it reads a bit like "padding bits cannot have traps, see C for rationale". Maybe it could be clarified with:
```
[ Note: Padding bits have unspecified value, but do not cause traps. See also <ins><xref>Annex C</xfref> and </ins>ISO C 6.2.6.2. — end note ]
```
and add a compatibility entry to Annex C.1 since this is a difference in behaviors between the two languages?

**Comment by oss-assist** [comment]
@AaronBallman 

Please note that [eel.is](https://eel.is) or any other similar website is not an authentic place to reference a piece of the draft specification from; please refer to a section of the draft spec using its own addressing format, like the way you see in most [issues](https://github.com/cplusplus/draft/issues).

**Comment by jwakely** [comment]
He did, he said [basic.fundamental]p4.

**Comment by jensmaurer** [comment]
@AaronBallman, Annex C.1 lists situations where a valid C program may change semantics or be ill-formed when compiled as C++. The situation here is not such a case, since we are changing from trap (undefined behavior) to well-defined behavior.

**Comment by jensmaurer** [comment]
We currently say
> [Note: Padding bits have unspecified value, but do not cause traps. See also ISO C 6.2.6.2. -- end note]
Should we instead say "In contrast, see ISO C 6.2.6.2." ?

**Comment by AaronBallman** [comment]
> @AaronBallman, Annex C.1 lists situations where a valid C program may change semantics or be ill-formed when compiled as C++. The situation here is not such a case, since we are changing from trap (undefined behavior) to well-defined behavior.

Okay, that's a fair point.

> Should we instead say "In contrast, see ISO C 6.2.6.2." ?

That would clarify it for me, yes.
