### ISSUE TITLE
List initialization clause appears to exclude form with equals sign

### ISSUE THREAD

**Issue by jacobsa** [cplusplus/draft#332]
[dcl.init]/17 in N3936 says the following:

> If the initializer is a (non-parenthesized) braced-init-list, the
> object or reference is list-initialized (8.5.4).

According to the grammar in [dcl.init]/1, that should certainly cover this
case:

```
T f{17};
```

I infer that this is also supposed to cover the generally equivalent case:

```
T f = {17};
```

However, according to the grammar the initializer in this case is not a
braced-init-list but rather an equals sign followed by a braced-init-list
(there is no category for this that excludes an assignment-expression).

Am I correct in thinking that the latter syntax is supposed to be covered by
the quoted clause? If so, perhaps the wording should be made more precise.

**Comment by jensmaurer** [comment]
We seem to be inconsistent in our use of "initializer" in this paragraph.

**Comment by jacobsa** [comment]
Thanks!
