### ISSUE TITLE
Weird sentence in [ostream]

### ISSUE THREAD

**Issue by gennaroprota** [cplusplus/draft#3333]
Quoting from [ostream]:

  "If one of these called functions throws an exception, then unless
  explicitly noted otherwise the output function sets badbit in error
  state. If badbit is on in exceptions(), the output function rethrows
  the exception without completing its actions, otherwise it does not
  throw anything and treat as an error. "

"and treat as an error" seems wrong; should it be "and treat*s* *it* as
an error"? If that is the case, I'd say that it adds nothing useful and
should be removed.

**Comment by cubbimew** [comment]
FWIW, similar passage in [istream] ends in a more sensible "otherwise it does not throw anything and proceeds as if the called function had returned a failure indication."

**Comment by jensmaurer** [comment]
Editorial meeting: Assign to @jwakely.

**Comment by jwakely** [comment]
The wording seems very similar to Issues 27-406 and 27-504 in [N0827](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/1996/N0827.pdf). I don't know when or why the wording in [istream] and [ostream] diverged.

I think we should improve "set `badbit` in error state" in both places.

It seems like an improvement to make both places say "proceeds as if the called function had returned a failure indication."
