### ISSUE TITLE
[lib] Review organization of standard library clauses

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3349]
From NB US 325 (C++20 CD) cplusplus/nbballot#321: 

> The contents of the header &lt;bit> relate to inspecting and manipulating memory patterns directly, rather than numeric operations. It better belongs under clause 20, general utilities.
>
> Proposed change:
Move 26.5 [bit] to a new subsection under class 20 [utilities]

Other concerns: pair, tuple, variant, optional, any, bitset should be extracted into their own top-level clause "Utility types" or similar (48 pages).
[rand] is unrelated to real-number calculations and thus should not be under [numerics].

**Comment by jensmaurer** [comment]
See also #3388.

**Comment by jensmaurer** [comment]
Ideas from Belfastt:
- Put [atomics] under [threads] (it fits the theme rather well).
- Maybe put all of locale, regex. std::format under I/O-ishj (because locale-using)

**Comment by ben-craig** [comment]
The editors might want to spend some spare brain cycles on editorial strategies for dealing with the combination of standard library headers and standard library modules, particularly if something like P0581 goes through.

**Comment by jensmaurer** [comment]
@ben-craig , thanks for the heads-up. From a cursory look at P0581, it appears we should get away with a small amount of added text for these std modules, so we might get away with a subclause in the lib intro part, or with a short mention whenever we show a header synopsis.

**Comment by jensmaurer** [comment]
Copied the remaining items to #5315
