### ISSUE TITLE
[any.cons]p5 Strike otherwise to form a valid term

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#3362]
"Valid but ~~otherwise~~ unspecified state" is a defined term. If the "otherwise" is intentional, I suggest rewording this so that it doesn't read almost like the defined term, or adding a clarifying note explaining how it differs from the defined term.

**Comment by jensmaurer** [comment]
Actually, the entire sentence can go due to [lib.types.movedfrom].
