### ISSUE TITLE
Provide a summary reference to where the 'Normative references' were mentioned inside the specification

### ISSUE THREAD

**Issue by oss-assist** [cplusplus/draft#3364]
In the section <a href="https://timsong-cpp.github.io/cppwp/#intro.refs">intro.refs</a>, the C++ specification mentions references to certain external specifications and standards.

Better to provide a summary of all the sections inside the C++ specification where those documents where mentioned, either right in the <a href="https://timsong-cpp.github.io/cppwp/#intro.refs">intro.refs</a> section or at the end of the document in a seperate reference.

**Comment by jensmaurer** [comment]
The ISO Directives have vested interest in the structure of [intro.refs]. Just adding some cross-references in every bullet (the easiest fix) might not be liked.

**Comment by jensmaurer** [comment]
Editorial meeting: ISO mandates the structure of this section; we can't just add cross-references there. And we've run out of output files.
