### ISSUE TITLE
Make usage of memory_order enumeration values consistent

### ISSUE THREAD

**Issue by mclow** [cplusplus/draft#3365]
In clause 31, there is mixed usage of the scoped and unscoped names for the `memory_order` enumerations.

For example: `memory_order::acq_rel` and `memory_order_acq_rel`.
Make them consistent.  Preference (from Richard and Jens) for the first form.

**Comment by mclow** [comment]
I will provide a pull-request after the Belfast meeting.

**Comment by AlisdairM** [comment]
https://github.com/cplusplus/draft/pull/3832

**Comment by jensmaurer** [comment]
... with some add-on fixes in #3864.
