### ISSUE TITLE
Make sure that the text can be searched regardless of hyphenation

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#3367]
Anecdotally, hyphenation prevents hyphenated words from being found in full-text search in some PDF readers. We should investigate how we can make full-text search work reliably, at least in _some_ reader.

**Comment by jensmaurer** [comment]
This sounds like a research project that needs a champion.

**Comment by jensmaurer** [comment]
https://tex.stackexchange.com/questions/43033/make-hyphenated-words-in-pdf-searchable

**Comment by jwakely** [comment]
Works for me:

![Screenshot_20191125_093728](https://user-images.githubusercontent.com/1254480/69529051-66dc8e80-0f67-11ea-8bc7-d4d4bdb73364.png)

This is KDE's Okular. Get a better reader :stuck_out_tongue_winking_eye:

**Comment by tkoeppe** [comment]
That's also what I suggested to Lawrence, and he was happy to be given a recommendation of a tool that would work, rather then necessarily requiring changes in the source code.

**Comment by jensmaurer** [comment]
Editorial meeting: Nothing to do here, unless a specific recommendation for a LaTeX-level change comes along.

**Comment by johelegp** [comment]
I find that https://timsong-cpp.github.io/cppwp/full works great on Firefox.
