### ISSUE TITLE
[feature] Add an option to browse the documentation as HTML pages on a local server

### ISSUE THREAD

**Issue by oss-assist** [cplusplus/draft#3374]

**Comment by jwakely** [comment]
This seems out of scope. The point of these sources are to build a PDF for the C++ working draft, for the use of the committee. The sources are public to allow (and encourage) editorial fixes from the community.

Providing additional services for the community is not what we're trying to do here. There are already third-party sites hosting HTML versions, you can use those (and their tools for converting to HTML).

**Comment by tkoeppe** [comment]
This seems out of scope. The principal purpose of this repository is to serve as a editorial tool for the project editors. The repository does not contain "documentation" (but rather sources for the working drafts), and we do not necessarily want to maintain a set of tools external to the editorial project work.

Regularly updated working draft N-papers are available in the public committee mailings.

**Comment by oss-assist** [comment]
@tkoeppe @jwakely 
I know those third-party services, but if you make a simple tool that would make the draft HTML-browseable, you'll bring such a utility to a broader audience.

Your perception that this repository is only for the internal consumption of the C++ commitee is wrong.
If I make the whole thing and do the pr, would you merge it?

**Comment by jwakely** [comment]
It's not a perception, it's a fact. Others might find utility in it, but that's not its main purpose.
