### ISSUE TITLE
[stmt.return]/2 example doesn't have an explanation

### ISSUE THREAD

**Issue by LadyNina** [cplusplus/draft#3379]
in [stmt.return]/2 we have the following example

    std::pair<std::string,int> f(const char* p, int x) { return {p,x}; }

It's not all that clear what this example is meant to demonstrate. Can we add some sort of an explanation?

**Comment by tkoeppe** [comment]
It looks like the example refers to the following parts of the preceding note: "can involve invocation of a constructor" and "if its type differs".

Maybe a comment like `// invokes the constructor std::string::string` would improve the example?

**Comment by jensmaurer** [comment]
Editorial meeting: Example does not seem to be useful. Strike it.
