### ISSUE TITLE
[dcl.pre] paragraphs are in a strange order

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#338]
First we have "the simple-declaration <blah> is divided into three parts".
Then a digression on attribute-declarations and scopes.
Then back to simple-declarations again.
Then a digression on static_assert-declarations and empty-declarations.
Then, with no introduction or explanation, some words about init-declarators, and about decl-specifier-seq's. That's clearly supposed to be related to the prior stuff about simple-declarations, but we're too far away for that to be a reasonable implied context.
Oh, then a lie: "Syntactic components beyond those found in the general form of declaration are added to a function declaration to make a function-definition." This means to say "beyond those found in the general form of a simple-declaration"; a function-definition is one of the possibilities in the general form of "declaration".
And then back to decl-specifier-seq's again.

This is a mess and should be fixed.

Related: we should check which of these simple-declaration rules should also apply to function-definitions and member-declarations, and suggest to core that any discrepancies be fixed.

**Comment by opensdh** [comment]
Before this is closed (and thus vanished): has anyone done the check in the last sentence of the issue description?
