### ISSUE TITLE
Restructure [utilities]

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3388]
Ideas from Belfast editorial session:

- Utility types: pair, tuple, variant, optional, any, bitset
- Memory management: memory, smart Pointers, memory resource, scoped_allocator-adaptor,
- Compile-time programming: type_traits, ratio

**Comment by jensmaurer** [comment]
Move [format] to [strings], since it's essentially a fancy string constructor.

**Comment by jensmaurer** [comment]
Move [stacktrace] to [diagnostics].

**Comment by jensmaurer** [comment]
keep Utility types: pair, tuple, variant, optional, any, bitset under  [utilities], but create a new grouping subclause called "data types".

**Comment by JohelEGP** [comment]
Isn't "[charconv] Primitive numeric conversions" a good fit for Clause 26 "Numerics library"? I always searched there for it, at first.

**Comment by jwakely** [comment]
Should [intseq] "Compile-time integer sequences" be a subclause of [utility] "Utility components" rather than a sibling?

**Comment by jensmaurer** [comment]
Addressed with  #5124
