### ISSUE TITLE
[allocator.adaptor] is in the wrong place

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#341]
[Reported by email]

The section [allocator.adaptor] seems in the wrong place; it would fit better next to the "default allocator" [default.allocator].

**Comment by AlisdairM** [comment]
This is what https://github.com/cplusplus/draft/pull/683 is intended to address.  We cannot go any closer without invading another header, which I would prefer to avoid.

**Comment by jwakely** [comment]
I merged #683
