### ISSUE TITLE
[2019-11 LWG Motion 15] P1862R1 Ranges adaptors for non-copyable iterators

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3417]
http://wiki.edg.com/pub/Wg21belfast/StrawPolls/p1862r1.pdf

These five papers (together) resolve NB comments US272 and DE288

**Comment by burblebee** [comment]
What "five papers"?  Only one paper is referenced to be applied.  @CaseyCarter, can you help explain?

**Comment by zygoloid** [comment]
This is referring to LWG motions 11 - 15.
