### ISSUE TITLE
IEC 559 does not name a standard

### ISSUE THREAD

**Issue by potswa** [cplusplus/draft#343]
[numeric.limits.members] §18.3.2.4/56 and its footnote mention IEC 559, but the reference number of the standard is (and has always been) 60559. Attempts to search for "IEC 559" may be fraught with difficulty because the latest edition is "ISO/IEC/IEEE 60559 ed1.0 (2011-06)". A number of IEC standards end with 559. The IEC webstore still does not find the document for a simple "IEC 60559" query, but requires the whole prefix with all three bodies. Changing that prefix is apparently what sent them back to ed1.0, after the publication of "P-IEC 60559 ed2.0 (1989-01)." That made it a completely different document — what a mess.

So, it would be nice if [numeric.limits.members] and the footnote named the standard document exactly as "ISO/IEC/IEEE 60559". Also, it might deserve a mention in [intro.refs] §1.2, perhaps including the edition and date.

**Comment by jensmaurer** [comment]
ISO/IEC/IEEE 60559:2011 is available on www.iso.org.
