### ISSUE TITLE
Injected-class-names: members or not?

### ISSUE THREAD

**Issue by 18** [cplusplus/draft#3440]
[[class.pre] p2](http://eel.is/c++draft/class#pre-2.sentence-3) says:
> For purposes of access checking, the injected-class-name is treated as if it were a public member name.

[[class.member.lookup] p3](http://eel.is/c++draft/class.member.lookup#3.sentence-2) says:
> [...] type declarations (including injected-class-names) are replaced by the types they designate.

Here, it is incorrectly assumed that an injected-class-name is a member, which it is not. Specifying that an injected-class-name is a nested type would resolve this.

A better definition would be something along the lines of:
> A nested type denoting the class-name is declared as a public member; this is known as the injected-class-name.

**Comment by jensmaurer** [comment]
[basic.lookup] p3 says

> The injected-class-name of a class (Clause 11) is also considered to be a member of that class for the purposes of name hiding and lookup.

So, member lookup is supposed to find it. I'm not seeing a problem here.
