### ISSUE TITLE
[format.arg] Declaration mismatch

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#3461]
An exposition-only constructor of `basic_format_arg` is declared as

https://github.com/cplusplus/draft/blob/6deb1811d9c96ad0efe52ee18140b7998b16ba1b/source/utilities.tex#L21583-L21584

in the class template definition, but `const` is missing in the description:

https://github.com/cplusplus/draft/blob/6deb1811d9c96ad0efe52ee18140b7998b16ba1b/source/utilities.tex#L21739

**Comment by jensmaurer** [comment]
Given the definition of "value", it seems sufficiently obvious that the description is missing the "const" to fix this editorially.

**Comment by cpplearner** [comment]
Sorry, it seems that this constructor makes more sense without `const`. This constructor should be selected when the argument is of type `void*`. But if the parameter is `const T*` then `template<class T> basic_format_arg(const T&)` is a better match.

Can we revert #3465 and make it a LWG issue?

**Comment by jensmaurer** [comment]
What we did editorially is making the synopsis identical to the function definition. Sorry that this seemingly went the wrong way.

Please feel free to have an LWG issue created, but reverting the editorial fix would re-introduce the inconsistency, which seems to make the situation worse.
