### ISSUE TITLE
[lib] Use \exposconcept and \libconcept where applicable

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3494]
Inspect \tcode{\placeholder{...}} situations and other mentions of concept names that should use \exposconcept or \libconcept.

This is fuel for the already-existing index of concept names.

**Comment by zygoloid** [comment]
Once we get a fully-concept-constrained standard library, we will have a *lot* of mentions of common concepts. Is indexing all of them useful?

Example: there are 95 mentions of is_constructible* in the standard library. Most of them will likely become constraints at some point. Is it useful to have 95 index entries for the `constructible_from` concept?

**Comment by jensmaurer** [comment]
If not, what are the rules when to index concept uses (the concept definition is obvious, of course)?

**Comment by jensmaurer** [comment]
Sample of concepts index after #3496 
![concepts](https://user-images.githubusercontent.com/23412755/69503631-f65c5000-0f1b-11ea-90aa-4e1090010098.png)

**Comment by jensmaurer** [comment]
Editorial meeting: LWG chair says the big index is desirable. Let's go for it.
