### ISSUE TITLE
Prefix names of std lib concepts with "std::" in the core clauses

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3495]
The core clauses mention library concepts in some examples.

It is our habit to prefix names from the standard library with `std::` if they appear in the core language clauses, to highlight their provenance.

I'd like to have a nod that we'll be doing the same for concept names from the standard library.

**Comment by zygoloid** [comment]
Can you provide some examples?

**Comment by jensmaurer** [comment]
Good: [over.match.class.deduct] p6
```
template<std::integral W> using B = A<W>;
```

Bad: [expr.prim.req] p3
```
template<typename T>
   concept R = requires (T i) {
      typename T::type;
      {*i} -> convertible_to<const typename T::type&>;
   };
````

**Comment by jensmaurer** [comment]
Editorial meeting: Agreed, add std:: prefixes.
