### ISSUE TITLE
[language.support] Stable label not right-aligned

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#3520]
This is probably the only occurrence of such an effect. Is it okay as is, or should it be fixed? Below is a manually adjusted image for comparison.
![1575265209](https://user-images.githubusercontent.com/21071787/69933365-d214ec00-14a4-11ea-9c9b-7f089205b54c.png)
![1575265209-2](https://user-images.githubusercontent.com/21071787/69933455-320b9280-14a5-11ea-8ef4-918c44f93b87.png)

**Comment by jensmaurer** [comment]
This is because the clause title plus the label is longer than one line.

The easiest fix is probably to rename [language.support] to [support], in harmony with the contained subclauses.

**Comment by jensmaurer** [comment]
Editorial meeting: Go with Jens' suggestion.
