### ISSUE TITLE
[std] Multiple notes and examples within the same subclause shall be numbered

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#3522]
So says the ISO Directives, Part 2:
https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor328
https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor342

**Comment by jwakely** [comment]
The purpose of that is to be able to refer to a note unambiguously. In theory we achieve that by numbering our paragraphs, although that means the notes don't have consecutive numbers starting from one. In practice I think we have a few places where we put two notes in a single paragraph.

**Comment by jwakely** [comment]
Also, ISO have never asked us to change this when we submit a new IS or TS.

**Comment by jensmaurer** [comment]
Even with that change, we're still not satisfying the all-caps presentation of the note and example introducers that the ISO Directives desire.
It would probably be a relatively small change to add subclause-local sequential numbers to notes and examples, if we so desire.

**Comment by johelegp** [comment]
> Even with that change, we're still not satisfying the all-caps presentation of the note and example introducers that the ISO Directives desire.

I think it's fine, given https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor003:
> The ISO/IEC Directives, Part 2 does not specify the typography and layout of documents, which are determined by the house style of the publishing organization. Presentation is outside of the scope of the ISO/IEC Directives, Part 2.

@jwakely Perhaps that means that it's fine as is. With wg21.link, you can reference specific notes within a paragraph. And in text, too (e.g. the second note in [xxx]p2).

**Comment by jensmaurer** [comment]
Editorial meeting: We believe our notes and examples are well-numbered. ISO CS will advise if they disagree.
