### ISSUE TITLE
Inconsistent terminology and spelling regarding start, startup, and start-up

### ISSUE THREAD

**Issue by ben-craig** [cplusplus/draft#3530]
In n4842, I count two non-index instances of the spelling "start-up" (and one in the index).
I count four non-index instances of the spelling "startup" (and one in the index)
The sequence of letters "start" show up more than 100 hundred times, but many of those are referring to things that don't involve the beginning of program execution.
The heading [support.start.term] uses the terms "Start and termination".  [basic.pre.1] mentions "starting and terminating a program".  

The WD should pick one term and use it consistently.

**Comment by jensmaurer** [comment]
Editorial: "start" is a point, whereas "startup" is a process. Be consistent. "at program startup" etc. should be "at program start" -> "At the start of the program". No hyphen.
