### ISSUE TITLE
[span.cons] thinks that to_address() can throw, but it can't

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#3534]
N4842 22.7.3.2 [span.cons]/6 and /9 say: "*Throws:* When and what `to_address(first)` throws."

But 20.10.2 [memory.syn] and 20.10.4 [pointer.conversion] require both overloads of `to_address()` to be `noexcept`:

```
template<class T> constexpr T* to_address(T* p) noexcept;
template<class Ptr> auto to_address(const Ptr& p) noexcept;
```

Therefore, [span.cons]/6 and [span.cons]/9 should be removed editorially.

**Comment by CaseyCarter** [comment]
[span.cons]/9 fails to account for the fact that `last - first` can potentially throw. We should probably file an LWG issue to handle all of this.

**Comment by CaseyCarter** [comment]
This is now [LWG 3358](https://wg21.link/lwg3358).

**Comment by jensmaurer** [comment]
Looks like we can editorially replace the utterings about to_address with "Throws: Nothing.", but of course the "last-first" issue needs to be addressed non-editorially.

**Comment by burblebee** [comment]
The changes applied in PR #3546 conflict with those approved in LWG3358.  I assume LWG3358 is what we really want here?

**Comment by jwakely** [comment]
The changes applied here fix the editorial issue that "_Throws:_ [thing that cannot throw]" should be "_Throws:_ Nothing.". LWG 3358 addresses the normative defect that `last - first` should be considered. So they do conflict, but both changes are correct :slightly_smiling_face:

The LWG 3358 changes supersede this editorial change and are what we want.

**Comment by CaseyCarter** [comment]
+1 to Jonathan's comments, and apologies for not rebasing the wording of LWG 3358 onto the result of the editorial change to avoid this confusion in the first place.
