### ISSUE TITLE
Missing paragraph number for Preconditions element [span.cons] p7/8

### ISSUE THREAD

**Issue by Dani-Hub** [cplusplus/draft#3540]
[span.cons] before p8 has a Preconditions element without own paragraph number:

>7 Constraints: Let U be remove_reference_t<iter_reference_t<It>>.
>(7.1) — is_convertible_v<U(*)[], element_type(*)[]> is true. [Note: The intent is to allow only
>qualification conversions of the iterator reference type to element_type. —end note]
>(7.2) — It satisfies contiguous_iterator.
>(7.3) — End satisfies sized_sentinel_for<It>.
>(7.4) — is_convertible_v<End, size_t> is false.
>Preconditions:
>(7.5) — If extent is not equal to dynamic_extent, then last - first is equal to extent.
>(7.6) — [first, last) is a valid range.
>(7.7) — It models contiguous_iterator.
>(7.8) — End models sized_sentinel_for<It>.

The Preconditions element should get a separate paragraph number (8), similarly the current bullets (7.5)-(7.8) need to be incremented accordingly

**Comment by jwakely** [comment]
Thanks!
