### ISSUE TITLE
Inconsistent indexing of Cpp17 requirements

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#3547]
Some are scattered, others, not indexed:

---
![1576291046](https://user-images.githubusercontent.com/21071787/70842376-47fc4a00-1df9-11ea-822f-a3932b5f04ed.png)
---
![1576291052](https://user-images.githubusercontent.com/21071787/70842377-47fc4a00-1df9-11ea-8c7c-f6ef5bc667fb.png)
---
![1576291069](https://user-images.githubusercontent.com/21071787/70842378-47fc4a00-1df9-11ea-91b4-067b08749a6d.png)
---
![1576291078](https://user-images.githubusercontent.com/21071787/70842379-47fc4a00-1df9-11ea-8429-bec53f046f5f.png)
---

**Comment by jensmaurer** [comment]
Yes, this is a mess.

`\oldconceptdefn` is just broken; it does not generate italics index entries.
The concepts under "requirements" are manually added using `\indextext{...\idxoldconcept...}`. This needs a serious cleanup, but we should first decide what we want. I think putting them on the top level of the index is probably where people are most likely to look. But the space under "requirements" is also tempting.
