### ISSUE TITLE
[string.view.synop][span.syn] Declaration for primary template and namespace of enable_safe_range

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#3552]
In N4842, the primary template of `std::ranges::enable_safe_range` is not declared in synopses of `<string_view>` and `<span>`, and current namespace of partial specializations might be wrong.

**Comment by CaseyCarter** [comment]
> the primary template of `std::ranges::enable_safe_range` is not declared in synopses of `<string_view>` and `<span>`

We cannot define a template in multiple headers, and there are no non-defining declarations of variable templates in C++. I suppose we could put the primary template in an exposition-only header included by all of `<span>`, `<string_view>`, and `<ranges>`, but it seems like overkill to me. I'm perfectly happy to depict the specializations in individual headers and leave it to "implementor magic" to make that valid.

> current namespace of partial specializations might be wrong

I believe I fixed this in #3551.
