### ISSUE TITLE
Header synopses for sequence containers don't have their own sections

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#356]
All the other headers defining containers get an `rSec2` or `rSec3` for their synopsis, but the synopses for `<array>`, `<deque>`, `<forward_list>`, `<list>` and `<vector>` are all lumped together in [sequences.general] and so don't appear in the TOC sidebar in PDF readers, and aren't cross referenced in [xref].

**Comment by jensmaurer** [comment]
There are separate sections nowadays.
