### ISSUE TITLE
[range.adaptors] Base vs base-t

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#3561]
P1035 "Input range adaptors" used `base_t` (in `elements_view` and `take_while_view`) where the other views used `Base`. Which way to go?

**Comment by jensmaurer** [comment]
Asked LWG which way to go: http://lists.isocpp.org/lib/2019/12/14918.php

**Comment by jensmaurer** [comment]
Editorial meeting: It's like a template parameter. Use "Base" (italics).
