### ISSUE TITLE
[range.range] Misleading description of safe_range

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#3564]
From http://eel.is/c++draft/range.range#itemdecl:2:
> ```C++
> template<class T>
>  concept safe_­range =
>    range<T> &&
>      (is_lvalue_reference_v<T> || enable_safe_range<remove_cvref_t<T>>);
> ```
> Given an expression E such that decltype((E)) is T, T models safe_­range only if the validity of iterators obtained from the object denoted by E is not tied to the lifetime of that object.
>
> [ Note: Since the validity of iterators is not tied to the lifetime of an object whose type models safe_­range, a function can accept arguments of such a type by value and return iterators obtained from it without danger of dangling. — end note ]

Given `std::vector<int> x{1, 2, 3};`, if `E` is `x`, its type `std::vector<int>&` models `safe_range`, but the validity of the iterators obtained from the object it denotes are tied to its lifetime.

**Comment by johelegp** [comment]
This is actually normative. As such, `std::vector<int>&` can't model `safe_range` because the iterators of `x` are tied to the lifetime of the object it denotes. The intention is to actually allow such a case, given its use throughout [[range.subrange]](http://wg21.link/range.subrange) and in [[range.dangling]#2](http://eel.is/c++draft/range.dangling#2).

**Comment by CaseyCarter** [comment]
Ugh, this is a train wreck. Please file an LWG issue?

**Comment by johelegp** [comment]
Sure. Will post the issue number here when it is issued.

**Comment by johelegp** [comment]
This is now http://wg21.link/LWG3361.
