### ISSUE TITLE
[view.interface] Inconsistencies in the draft

### ISSUE THREAD

**Issue by miscco** [cplusplus/draft#3577]
In the first [paragraph](https://eel.is/c++draft/view.interface#1) there seem to be some inconsistencies in the current draft.

The `data()` methods are depicted as follows:
```cpp
    constexpr auto data() requires contiguous_iterator<iterator_t<D>> {
      return to_address(ranges::begin(derived()));
    }
    constexpr auto data() const
      requires range<const D> && contiguous_iterator<iterator_t<const D>> {
        return to_address(ranges::begin(derived()));
   }
```
Note that the non-const member function is missing the `range<D>` requirement

The `operator[]` member functions are the only ones written in the "old" template style
```cpp
    template<random_access_range R = D>
      constexpr decltype(auto) operator[](range_difference_t<R> n) {
        return ranges::begin(derived())[n];
      }
    template<random_access_range R = const D>
      constexpr decltype(auto) operator[](range_difference_t<R> n) const {
        return ranges::begin(derived())[n];
      }
```

They should be written with a `requires` clause similar to all other methods.
```cpp
    constexpr decltype(auto) operator[](range_difference_t<D> n) 
      requires random_access_range<D> {
        return ranges::begin(derived())[n];
    }

    constexpr decltype(auto) operator[](range_difference_t<const D> n) const
      requires random_access_range<const D> {
        return ranges::begin(derived())[n];
    }
```

Finally, the implicit conversion opterator seems to be missing a requirement too.
```cpp
    constexpr bool empty() requires forward_range<D> {
      return ranges::begin(derived()) == ranges::end(derived());
    }
    constexpr bool empty() const requires forward_range<const D> {
      return ranges::begin(derived()) == ranges::end(derived());
    }

    constexpr explicit operator bool()
      requires requires { ranges::empty(derived()); } {
        return !ranges::empty(derived());
      }
    constexpr explicit operator bool() const
      requires requires { ranges::empty(derived()); } {
        return !ranges::empty(derived());
      }
```
Note that the conversion operator defers back to `ranges::empty()`. While I believe that it is implied in `ranges::empty()` it would improve readability/consistency to require `forward_range<D>`/`forward_range<const D>`.

**Comment by jensmaurer** [comment]
Unless you can show that a WG21-approved paper was misapplied by the editors, all of your concerns seem to be non-editorial. Note that requires-clauses contribute to partial ordering, which might be detectable once user-supplied overloads end up in an overload set.
@CaseyCarter , could you please forward to LWG?

**Comment by miscco** [comment]
Life is hard, from conversation with @CaseyCarter :

`data()` has no requirement on `range<Derived>` as that is implicit in the requirements of [Derived](https://eel.is/c++draft/view.interface#2) as `view<Derived>` implies `range<Derived>`. So this is technically correct, although I would question whether it is good practise to omit the -tautological- requirement only at that single place.

`operator()` must not be restricted on `forward_range` as a user might write a custom container that does not fulfill the `forward_range` requirement. Moreover, if I understand CRTP correctly even for the `forward_range` case `view_interface::empty()` would be hidden if there is a `Derived::empty()` and correctly selected by `ranges::empty()`

`operator[]` is worse. As `Derived` might be an incomplete type `range_difference_t<Derived>` might not compile. By using the indirection `template<random_access_range R = Derived>` the `operator[]` is only ever synthesized once it is used and `Derived` is complete.
