### ISSUE TITLE
[basic.scope.pdecl]/1 Example is outdated

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#3578]
From https://stackoverflow.com/questions/59442521/use-of-variable-in-own-initializer  
After [the resolution](https://github.com/cplusplus/draft/commit/f3a6b2e671efdee5bacb74a5ea01d4bfb1900d3e) of CWG2256¹ changed the rules of an object lifetime start, `unsigned char x = x;` no longer initializes `x` with its own indeterminate value as the Example in [basic.scope.pdecl]/1 says, but triggers undefined behavior, because the initializer accesses the object whose lifetime has not started yet (because variable initialization hasn't completed).

---
1) Which, if ignore references, kinda mixes variables with objects…

**Comment by jensmaurer** [comment]
So, the definition of "vacuous initialization" has changed, and that means "unsigned char x = x" no longer has vacuous initialization, thus the glvalue "x" is used to access an object whose lifetime has not yet begun, which is undefined behavior. That doesn't seem to be editorial at all to me.
