### ISSUE TITLE
[expr.rel] Simplify pointer comparison wording

### ISSUE THREAD

**Issue by 18** [cplusplus/draft#3590]
[[expr.rel] p4 sub 3](http://eel.is/c++draft/expr.rel#4.3) says:
> Otherwise, neither pointer is required to compare greater than the other.

This should just outright say that the result is unspecified.

**Comment by jensmaurer** [comment]
This bulleted list defines a partial order; "unspecified" would be a category error in that realm. We make specific C++ comparison operators have unspecified result in the next paragraph if the partial order says "no ordering defined here".
