### ISSUE TITLE
[range.prim.size] When is ranges::size ill-formed?

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#3597]
http://wg21.link/LWG3264 suggests that `ranges::size` should be ill-formed when the corresponding `disable_sized_range` is `true` for the non-array case. If its PR is to be correct, the current wording ladder should nest the next-to-last item in the sublist.

**Comment by johelegp** [comment]
Otherwise, `ranges::size` is never ill-formed on a `range`, as when `disable_sized_range` is `true`, it'll simply return _`make-unsigned-like`_`(ranges​::​end(E) - ranges​::​begin(E))`, and so you can never opt-out of `sized_range`.

**Comment by jensmaurer** [comment]
This sounds like a change with normative impact, and thus needs to go to LWG. Please submit an issue.

**Comment by johelegp** [comment]
Hopefully @CaseyCarter can clarify in LWG3264.

**Comment by johelegp** [comment]
> Please submit an issue.

Done. Waiting for its number.

**Comment by johelegp** [comment]
This is handled by https://wg21.link/LWG3368.

**Comment by johelegp** [comment]
LWG3368 merged: https://github.com/cplusplus/draft/pull/3752.
