### ISSUE TITLE
[expr.ref]/(6.3.2) function type spelling doesn't match [dcl.fct]/1

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#3607]
[[expr.ref]/(6.3.2)](http://eel.is/c++draft/expr.ref#6.3.2) says:
> Otherwise, if `E1.E2` refers to a non-static member function and the type of `E2` is “function of parameter-type-list _cv_ ref-qualifier<sub>opt</sub> returning `T`”… The type of `E1.E2` is “function of parameter-type-list _cv_ returning `T`”.

However, this doesn't match how function types are spelled in [[dcl.fct]/1](http://eel.is/c++draft/dcl.fct#1):
> … the type of the declarator-id in `D` is “derived-declarator-type-list noexcept<sub>opt</sub> function of (parameter-declaration-clause) cv-qualifier-seq<sub>opt</sub> ref-qualifier<sub>opt</sub> returning `T`” …

[expr.ref]/(6.3.2):
* uses _cv_ instead of _cv-qualifier-seq<sub>opt</sub>_
* uses "parameter-type-list" instead of "(_parameter-declaration-clause_)"
* misses `noexcept`_<sub>opt</sub>_

---

Also, why _ref-qualifier_<sub>opt</sub> of`E2`'s type is missing in the type of `E1.E2`?

**Comment by jensmaurer** [comment]
I agree with most of the suggestions, but the "parameter-type-list" actually better captures the processing that occurs between the parameter-declaration-clause and the resulting types. (Thus, [dcl.fct] should be fixed.)

**Comment by languagelawyer** [comment]
Is it actually necessary to repeat the full function type spelling, instead of just saying 
> if `E1.E2` refers to a non-static member function and the type of `E2` is `FT`…

**Comment by jensmaurer** [comment]
I'm actually wondering about something else: Do we have to include "cv" and "ref-qualifiers" in the resulting type for E1.E2? After all, those things only matter in checking the relationship of E1 and E2, but once that has been cleared, they're irrelevant for further processing. The relevant overload resolution section talks about "the non-static member function", so don't actually refer to "E1.E2" which is a funny prvalue invented for recursive parsing mechanics but not much else.
