### ISSUE TITLE
[range.join.iterator] Rename ref-is-glvalue to account for rvalues

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#3610]
We want to join rvalues (see https://github.com/ericniebler/stl2/issues/598#issuecomment-545207308), so the name of _`ref-is-glvalue`_ is deceptive. I suggest renaming it to _`deref-is-ref`_.

**Comment by CaseyCarter** [comment]
The variable is true if and only if `*i` is a glvalue for a value `i` of type `iterator_t<Base>`, i.e., it's true if that iterator type's "reference type" is a reference type. (It's unfortunate that iterators have an associated type "reference type" which reuses the name of a category of core language types, doubly so given that the "reference type" of an iterator is often but not always a reference type, but that ship sailed decades ago.)

While I don't care much about the (exposition-only) name of the variable, I don't find _`deref-is-ref`_ to be a substantial improvement over _`ref-is-glvalue`_. To avoid confusion - different people will interpret our cryptic abbreviations differently - I think we should pick either a short and meaningless name like _`potato`_ or a long and descriptive name like _`has_true_reference_type`_ or _`result_of_dereference_is_glvalue`_.

**Comment by johelegp** [comment]
> The variable is true if and only if `*i` is a glvalue for a value `i` of type `iterator_t<Base>`

It is because that is not true that I opened this issue. `*i` could be an rvalue and the variable would be `true` because it uses `is_reference_v` and not `is_lvalue_reference_v`.

If https://github.com/ericniebler/stl2/issues/641 was picked up, this exposition-only variable would be replaced with `safe_range`. In case it isn't, _`deref-is-ref`_ is not deceptive even if it still uses the overloaded reference term. `has_true_reference_type` seems like an improvement.

**Comment by CaseyCarter** [comment]
> > The variable is true if and only if `*i` is a glvalue for a value `i` of type `iterator_t<Base>`
> 
> It is because that is not true that I opened this issue. `*i` could be an rvalue and the variable would be `true` because it uses `is_reference_v` and not `is_lvalue_reference_v`.

A glvalue is either an lvalue or an xvalue. `*i` is an lvalue iff `is_lvalue_reference_v<decltype(*i)>` is `true`. `*i` is an xvalue iff `is_rvalue_reference_v<decltype(*i)>` is `true`. `*i` is a glvalue iff `is_reference_v<decltype(*i)>` is `true`, so the initializer of _`ref-is-glvalue`_ uses `is_reference_v`.

**Comment by johelegp** [comment]
You are right. Thank you. Unfortunately, I had already opened an LWG issue for this a while ago rather that choosing this lower barrier venue, as I prefer.
