### ISSUE TITLE
[locale.codecvt] Unicode is not a character encoding

### ISSUE THREAD

**Issue by cor3ntin** [cplusplus/draft#3611]
https://github.com/cplusplus/draft/blob/3974bc16a91e0be3b741d3ebbc2eea563c5873c8/source/locales.tex#L1837-L1841

This makes little sense,  Unicode being a character set rather than an encoding.
The wording probably meant UTF-8 or UTF-16

**Comment by jensmaurer** [comment]
But the text sounds like "wide character encoding" is considered different from "multibyte characters". So, we should probably talk about UTF-32 and EUC.
