### ISSUE TITLE
[temp.dep.type] Simplify the meaning of "template argument list of the primary template"

### ISSUE THREAD

**Issue by sdkrystian** [cplusplus/draft#3635]
[[temp.dep.type] p2](http://eel.is/c++draft/temp.dep.type#2) says:
> The template argument list of a primary template is a template argument list in which the _nth_ template argument has the value of the _nth_ template parameter of the class template.

This can be written in a much more simple and "correct" manner, since the following paragraph outlines when an equivalent parameter can be used, and what such a parameter is. Something along the lines of:

> The template argument list of a primary template is a template argument list in which the _nth_ template argument is the name of the _nth_ template parameter of the class template.

**Comment by jensmaurer** [comment]
I would prefer if p2 would simply say "nth template argument is equivalent to the nth template parameter" and then in p3 say as the first case: "equivalent if the name of the corresponding template parameter is used".

**Comment by jensmaurer** [comment]
This was rewritten by P1787
