### ISSUE TITLE
Consistency for template parameter names in standard library

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#3642]
In the current standard draft (N4849):

Almost all type template parameter names used for description of the standard library are of PascalCase, except for

- `charT` and `traits` representing character type and its related character/regular expression traits type, used by many components
- `internT`, `externT` and `stateT` used by `std::codecvt` and `std::codecvt_byname`
- `Byte_alloc` and `Wide_alloc` used by `std::wstring_convert` which is deprecated since C++17

Should we make them all PascalCase, i.e. replace them with `CharT`, `Traits`, `InternT`, `ExternT`, `StateT`, `ByteAlloc` and `WideAlloc` respectively for consistency?

Non-type template parameter names used by components in `<random>` and `<semaphore>` are of snake_case (or a single word of all lowercase), while others are of PascalCase (or a single word whose first letter is of uppercase).

Should we also make them all PascalCase? (#3616)

**Comment by jensmaurer** [comment]
Editorial meeting: For charT and traits, it's churn for no real gain. Fix the third bullet.
Leave everything else alone.
