### ISSUE TITLE
Cross reference to temp.over.link is misleading for abbreviated function template wording

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/draft#3657]
The cross reference to temp.over.link in pre-Prague subclause 9.3.3.5 [dcl.fct] paragraph 18 is at odds with intended reading of "equivalent" as not being the temp.over.link definition of "equivalent" as demonstrated by the example that mentions that the cases are functionally equivalent but not equivalent.

Unfortunately, the associated wording paper has a numeric cross-reference that is clearly wrong. The correct cross reference would probably be to [temp.fct].

**Comment by tkoeppe** [comment]
I believe the reference should be to 12.6.6 [temp.fct]. In the original wording that we used, 17.6.5 was the corresponding reference in the Concepts TS (http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4674.pdf).

**Comment by tkoeppe** [comment]
The reference to temp.over.link was editorially inserted in fc60a80689ba6dc79cfda6737252103e44319a42 to repair the erroneous reference 17.6.5.

Fixed by 977961d675f77c0874b10a3f834984e7576cacfb.
