### ISSUE TITLE
consider moving description of Requires: element and [res.on.required]p1 to Annex D

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#3664]
After the final "Mandating" paper is applied, we should consider moving description of the *Requires:* element and [res.on.required]p1 to Annex D (which should then contain all remaining uses of that element).

**Comment by AlisdairM** [comment]
As part of a global review of deprecated features, paper P2139R0 in the post-Prague mailing provides wording to replace all Requires clauses in Annex D, remove the Requires: element from C++23.  Clearly not a good answer for C++20 though, and not yet an approved direction.

**Comment by jensmaurer** [comment]
Confirmed, all remaining \requires are in Annex D.
