### ISSUE TITLE
Produce foreword with list of changes for C++20

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3668]
@tkoeppe to produce a list of changes for C++20.

Then, Richard will produce the foreword.

**Comment by zygoloid** [comment]
General text, received from INCITS:

# Foreword

ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.

The procedures used to develop this document and those intended for its further maintenance are described in the ISO/IEC Directives, Part 1. In particular, the different approval criteria needed for the different types of document should be noted. This document was drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2 (see www.iso.org/directives).

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO and IEC shall not be held responsible for identifying any or all such patent rights. Details of any patent rights identified during the development of the document will be in the Introduction and/or on the ISO list of patent declarations received (see www.iso.org/patents) or the IEC list of patent declarations received (see http://patents.iec.ch).

Any trade name used in this document is information given for the convenience of users and does not constitute an endorsement.

For an explanation of the voluntary nature of standards, the meaning of ISO specific terms and expressions related to conformity assessment, as well as information about ISO's adherence to the World Trade Organization (WTO) principles in the Technical Barriers to Trade (TBT) see www.iso.org/iso/foreword.html.

This document was prepared by Joint Technical Committee ISO/IEC JTC 1, *Information technology*, Subcommittee SC 22,  *Programming languages, their environments and system software interface*.

Any feedback or questions on this document should be directed to the user’s national standards body. A complete listing of these bodies can be found at www.iso.org/members.html.

**Comment by tkoeppe** [comment]
@opensdh: FYI, contributions welcome.

**Comment by zygoloid** [comment]
From #3681: 
> Note that the Forward also indicates the a specific cancels and replaces other documents. This would presumably include TS documents that have been incorporated into the IS.

ISO C11 uses this wording to describe the incorporated technical corrigenda:

> This third edition cancels and replaces the second edition, ISO/IEC 9899:1999, which has been technically revised. It also incorporates the Technical Corrigenda ISO/IEC 9899:1999/Cor 1:2001, ISO/IEC 9899:1999/Cor 2:2004, and ISO/IEC 9899:1999/Cor 3:2007.

We can presumably use similar wording to describe the incorporated technical specifications (we will need a list of those).

**Comment by CaseyCarter** [comment]
The Ranges TS is [ISO/IEC TS 21425:2017](https://www.iso.org/standard/70910.html).

**Comment by johelegp** [comment]
https://wg21.link/N4824 and https://en.cppreference.com/w/cpp/experimental list them.

**Comment by tkoeppe** [comment]
P2131R0 will contain some material to help build the list.

**Comment by zygoloid** [comment]
First pass at this pushed to c++20 branch. Please take a look!
