### ISSUE TITLE
Inconsistent use of \defexposconcept v. \exposconcept v. \placeholder for \expos concepts

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#3680]
Inconsistent use of \defexposconcept v. \exposconcept v. \placeholder for exposition concepts.  Here's some examples from a grep:
```
utilities.tex:    concept @\exposconcept{no-throw-input-iterator}@ = @\seebelow@;    // \expos
support.tex:  concept @\defexposconcept{partially-ordered-with}@ =      // \expos
iterators.tex:  template<class T> concept @\defexposconcept{can-reference}@       // \expos
iterators.tex:    {   *i } -> @\placeholder{can-reference}@;
```

**Comment by jensmaurer** [comment]
\defexposconcept is only applied once per concept, where the actual definition applies. A "see below" mention doesn't count as a definition.
\placeholder uses for \exposconcept are just "not yet changed" situations.

**Comment by jensmaurer** [comment]
Let's wait until #3496 has landed before cleaning up any stragglers.

**Comment by jensmaurer** [comment]
At least the /can-reference/ example is now fixed. Please create a new issue (with specifics) for any remaining issues in this area.
