### ISSUE TITLE
Consider updating "Specification-Style-Guidelines"

### ISSUE THREAD

**Issue by Dani-Hub** [cplusplus/draft#3684]
During the C++20 standardization, some parts of the recommendations should be updated to respect the language features such as the three-way- comparison operator and to reflect some Library convention refinements.

1) "Subclause headings" doesn't currently say anything about three-way comparison operators. Should the specification of <=> declarations go into [*.cmp] when combined with others? (I guess so). But what should be the recommended heading/label name when a single operator<=> is within a subclause? Should it be [\*.rel] then? Or [\*.spaceship]? 

2) The library has now decided (via Marshall's Mandating proposals) to replace in elements that express normative requirements (Mandates, Preconditions, and Constraints) every usage of "shall" by "matter of fact" wording. It would be good, if the guidelines could reflect this change, e.g. in "Writing "Let" in a function description", replace

"Mandates: T shall be CopyConstructible."

by either of

"Mandates: is_convertible_v\<T\> is true."

or

"Mandates: T meets the Cpp17CopyConstructible requirements."

(The second one is based on "Requirements expressed by concepts")

**Comment by jensmaurer** [comment]
Wiki page updated.
