### ISSUE TITLE
Deduction of return type from returned expression is unclear

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#371]
DIS 14882:2014 NB comment JP 07:

In 7.1.6.4p7: In the sentence, “When a variable…type of its specifier”, we think specification for function return type deduction is unclear, because the term "initializer" is not directly related to return statement.

_Proposed change_

Change to: (e.g.)

> the deduced return type is determined from the type of expression specified for the return statement.

**Comment by jensmaurer** [comment]
This is now [dcl.type.auto.deduct] and seems to have been rewritten such that the questionable phrase is gone.
