### ISSUE TITLE
[2020-02 LWG Poll 18] P2091R0 Issues with range access CPOs

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#3720]
resolves GB275, LWG issues 3258, 3299, 3368

**Comment by CaseyCarter** [comment]
Note that the ingress paper didn't correctly react to #3311. It contains two occurrences of _`make-unsigned-like`_ - one in context and one in `\added` wording - which should have been changed to _`to-unsigned-like`_ as in 76e7c18a1255a42c94cb3073de47969dc17549f1.
