### ISSUE TITLE
[dcl.array] Potentially ambiguous specification of array contents

### ISSUE THREAD

**Issue by sdkrystian** [cplusplus/draft#3791]
[[dcl.array] p6](http://eel.is/c++draft/dcl.array#6) states:
> An object of type “array of _N_ `U`” contains a contiguously allocated non-empty set of _N_ subobjects of type `U`, known as the elements of the array, and numbered `0` to `N -1`.

The use of contains here does not seem to be exclusive, and could potentially be interpreted to say that padding is permitted before the first element, allowing for the address of an array and its first element to differ (further, we don't normatively state that an array and it first element have the same address)

**Comment by languagelawyer** [comment]
> further, we don't normatively state that an array and it first element have the same address

#3203
