### ISSUE TITLE
[range.access.begin] P2091R0's change to para 1 is ambiguous

### ISSUE THREAD

**Issue by CaseyCarter** [cplusplus/draft#3802]
Per discussion starting at https://github.com/ericniebler/range-v3/issues/1433#issuecomment-591621950.

P2091R0 adds the phrase "let `t` be an lvalue that denotes the same object as `E` if `E` is a glvalue and otherwise denotes the result of applying the temporary materialization conversion ([conv.rval]) to `E`." several times. This phrase is ambiguous. The intended reading is:

> let `t` be an lvalue that denotes (the same object as `E` if `E` is a glvalue) or (the result of applying the TMC to `E` otherwise).

but it can also be read as:

> let `t` be (an lvalue that denotes the same object as `E` if `E` is a glvalue) or (the result of applying the TMC to `E` otherwise).

which confusingly implies that `t` is an xvalue in the latter case. We could clarify the structure with bullets:

> let `t` be an lvalue that denotes 
> * the same object as `E` if `E` is a glvalue, or 
> * the result of applying the TMC to `E` otherwise.

but the Standard really doesn't need more bullets, and this would add seven such bulleted lists in the introductory matter for seven existing bulleted lists. I'd rather not.

Suggestions?

**Comment by jwakely** [comment]
Maybe add a definition to the start of the parent subclause, [ranges.access], that says something like:

> Within subclause [range.access], the _reified object_ of a subexpression `E` denotes:
> - the same object as `E` if `E` is a glvalue, or
> - the result of applying the temporary materialization conversion ([conv.rval]) to `E` otherwise.

And then say "let `t` be the reified object for `E`."
