### ISSUE TITLE
[expr.call] Incorrect reference to "this parameter"

### ISSUE THREAD

**Issue by sdkrystian** [cplusplus/draft#3811]
[[expr.call] p7](http://eel.is/c++draft/expr.call#7.sentence-3) states:
> [...]  If the function is a non-static member function, the `this` parameter of the function is initialized with a pointer to the object of the call, converted as if by an explicit type conversion.

Seems to be some forgotten wording, the correct term would be "implicit object parameter". 

A potential problem regarding this could be that it would be unclear if the lifetime of the object denoted by the object expression is extended by the reference binding, or if it follows the rules of a normal temporary, however in both these cases the lifetime would end at the completion of the full-expression, so it seems to be a non-issue save for the clarity.

**Comment by jensmaurer** [comment]
While I agree that "this parameter" is bad phrasing, the term "implicit object parameter" is only used during overload resolution as a technical conveyance, and does not seem to exist outside of overload resolution.

**Comment by sdkrystian** [comment]
Maybe we just strike it then? [expr.prim.this] sufficiently describes `this` using "object upon which the call was involed" so we don't need it at all.

**Comment by jensmaurer** [comment]
Editorial meeting: Express the desired offset adjustment semantics by more directly referring to [expr.prim.this] phrasing.

**Comment by frederick-vs-ja** [comment]
#6803 should already have fixed this.
