### ISSUE TITLE
[class.copy.elision] Specification of when implicit move occurs is potentially confusing

### ISSUE THREAD

**Issue by sdkrystian** [cplusplus/draft#3818]
[[class.copy.elision] p3](http://eel.is/c++draft/class.copy.elision) says:
> In the following copy-initialization contexts, a move operation might be used instead of a copy operation

Specifically, "might" makes implicit move sound optional to the implementation, since there is no specification as to what happens after overload resolution is performed.

**Comment by jensmaurer** [comment]
It would be good to say that we actually call the constructor. We sort-of do that in [stmt.return], but {stmt.return.coroutine] is silent on that matter.

**Comment by frederick-vs-ja** [comment]
Probably already resolved. The "might" was removed in 64b5913f6b3cefc42a98f86e68d88e9cef752c82. Furtherly, [P2266R3](https://wg21.link/p2266r3) changed the rules later.
