### ISSUE TITLE
[iterator.cpp17] The iterator "old" concepts (Cpp17Requirements) are not indexed

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#3835]
The classic Cpp17 requirements ("old concepts" per our macros) appear as a block in the main index, but none of the iterator related requirements are listed.  I'm not sure idiomatically which macro should be used and where to ensure each is indexed at least once.

**Comment by johelegp** [comment]
https://github.com/cplusplus/draft/issues/3547 contains some information of Cpp17 requirements in general. I failed to notice that it shouldn't have been closed.

**Comment by jensmaurer** [comment]
Uh, right, those are missing.
