### ISSUE TITLE
[range.split] confuses current and current_

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#3848]
At http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0896r4.pdf#page=121 we can see that the _Effects:_ of `split_view::outer_iterator::operator++` is supposed to use _current_ but in the working draft [range.split.outer] p6 uses `current_` which is not the same thing (see [range.split.outer] p1 and #3847).

The same problem exists in [range.split.outer] p8 (comparison with default sentinel), and [range.split.inner] in the synopsis of _`inner-iterator`_ (definition of `operator*`).

The original application of P0896R4 (e85af9533ab6ab0f0b101ac61fc01ba47c406503) was consistent with P0896R4. Then 7989bb445478b41a9fee3539bebffcaa46ba5270 got rid of _current_ and made _`current_`_ stand in for both `current_` and `parent_->current_`. Then 89abe001f5cba2775ec1f908eadf765572413fd5 (fixing #3562) reintroduced _current_ but didn't restore uses of _current_, leaving them incorrectly referring to _`current_`_.

I think this must be fixed for C++20.

**Comment by jwakely** [comment]
The real problem here is that _`current_`_ and _`current_` are almost indistinguishable now that they both use kebab-case. Even when I knew what I was looking for, verifying that I'd fixed it in diffpdf was hard.

**Comment by jwakely** [comment]
There's also a problem with [range.split.outer] p4 referring to `current_` in a function that can be used when _`Base`_ doesn't satisfy `forward_range`, i.e. when `current_` doesn't exist. That seems like an LWG issue, as it's present in P0896R4.

**Comment by timsong-cpp** [comment]
> The real problem here is that _`current_`_ and _`current`_ are almost indistinguishable now that they both use kebab-case. Even when I knew what I was looking for, verifying that I'd fixed it in diffpdf was hard.

Can we editorially rename one of them to something that looks more different?

**Comment by jwakely** [comment]
I think that would be a good idea. I'll push a second commit to the branch for #3849

**Comment by CaseyCarter** [comment]
> There's also a problem with [range.split.outer] p4 referring to `current_` in a function that can be used when _`Base`_ doesn't satisfy `forward_range`, i.e. when `current_` doesn't exist. That seems like an LWG issue, as it's present in P0896R4.
> 
> I think it should say "Initializes _`parent_­`_ with `i.`_`parent_­`_ and if _`Base`_ models `forward_range`, also initializes _`current_­`_ with `std​::​move(i.`_`current_­`_`)`."

This is subtle: `split_view` only instantiates `outer-iterator<true>` when `forward_range<V>` is `true`, and we don't care if the body of `outer-iterator`'s conversion constructor template is ill-formed when no one should be calling it.
