### ISSUE TITLE
[expr.rel] Unclear how function pointers are compared

### ISSUE THREAD

**Issue by BRevzin** [cplusplus/draft#3850]
The intent of the wording is that result of `p < q` for unequal function pointers is unspecified - but the way we get there is that [expr.rel]/4 defines when pointers to objects compare greater and then [expr.rel]/5 we fall through to "Otherwise, the result of each of the operators is unspecified." 

Can we clean this up by inserting a new paragraph between [expr.rel]/4 and [expr.rel]/5 as follows:

> The result of comparing unequal pointers to functions ~or pointers to member functions~ is unspecified. 

Or something?

**Comment by timsong-cpp** [comment]
We don't allow relational comparisons of pointers to members.

**Comment by jensmaurer** [comment]
In which way is that "not clean"? There are a few more situations where comparing pointers is unspecified, and comparing function pointers is just one special case. Apparently, the right result falls out from the rules, so we're good.

**Comment by BRevzin** [comment]
@jensmaurer The pointer to object case is reasonable - we define right above here what it means to compare those, and specifies a clear partial ordering.

For the pointer to function case, we never even talk about what greater means. So I have to understand that I have to skip over the "Otherwise, if a pointer p compares greater than a pointer q" by way of p can't compare greater than a because we never say what that means. It's like solving a logic puzzle to figure out what the rules are...

**Comment by jensmaurer** [comment]
Editorial meeting: Call out pointers to functions explicitly (as unspecified).
