### ISSUE TITLE
[ranges] has many concepts used without \libconcept

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#3870]
e.g.,
```
  template<input_or_output_iterator I, sentinel_for<I> S, subrange_kind K>
    inline constexpr bool enable_borrowed_range<subrange<I, S, K>> = true;
```

or

```
  template<@\libconcept{input_range}@ V, @\libconcept{indirect_unary_predicate}@<iterator_t<V>> Pred>
    requires view<V> && is_object_v<Pred>
  class filter_view;
```

What's the intended policy for the use of `\libconcept`?

**Comment by johelegp** [comment]
Must be after some "Editorial meeting:". I wonder if there's a compilation of those, like there's the Specification Style Guidelines.

**Comment by CaseyCarter** [comment]
#3494 was closed by application of #3496. I suppose the remaining unannotated concept uses were overlooked?

**Comment by johelegp** [comment]
A more recently merged PR had in context a concept use without `\libconcept`, so I supposed some were introduced since then.

**Comment by jensmaurer** [comment]
Yes, some of these were overlooked. Maybe I should (temporarily) make \libconcept choose a different color so a lack of marking stands out more.
