### ISSUE TITLE
Two index entries for "NTBS" don't use \ntbs

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#3884]
Some index entries for NTBS and NTCTS are not formatted consistently:

![Screenshot_20200317_124719](https://user-images.githubusercontent.com/1254480/76857495-769d1d00-684d-11ea-9be7-ee1927d03764.png)

**Comment by jensmaurer** [comment]
NTCTS is a substantially different beast. For instance, it's defined in [defns.ntcts].

The typography of NTBS is fixed with the linked pull request.
