### ISSUE TITLE
Unclear time zone placeholders

### ISSUE THREAD

**Issue by opensdh** [cplusplus/draft#3892]
[time.zone.db.tzdb]/2 says

> If a `time_zone` `tz` is found &hellip;

(and similarly for `time_zone_link`).  The space between the two `\tcode`s not being visible in the draft, it's hard to see that this is a placeholder.  (The paper uses commas, which are also confusing and were understandably left out of the editing.)  Can we use other placeholders (`Z` and `L` would be an improvement, even though they have to be in code font) or a rephrasing like "(call it `tz`)"?

**Comment by zygoloid** [comment]
There's a larger problem with this wording: found *where*? I think the intent is pretty obvious, but we fail to actually express it. To solve both problems, I'm going with:

> If `zones` contains an element `tz` for which [...]
> otherwise, if `links` contains an element `tz_l` for which `tz_l.name() == tz_name`, then a pointer to the element `tz` of `zones` for which [...]
