### ISSUE TITLE
7.1.5/3 and /4 define 'constraints' that are later referred to as 'requirements'

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#390]
Suggestion from CWG is to change /3 and /4 to define "the requirements for a constexpr function/constructor"

Something like:

"The requirements for a constexpr function are: [...] The program is ill-formed if a constexpr function does not satisfy the requirements of a constexpr function."

**Comment by jensmaurer** [comment]
This is already addressed in the current text. We say "shall satisfy the following requirements".
