### ISSUE TITLE
__STDC_­HOSTED__ deals with freestanding, but does not mention it

### ISSUE THREAD

**Issue by ben-craig** [cplusplus/draft#3914]
It would be nice if searching for the word "freestanding" in the standard would reach the predefined macro that lets users detect whether an implementation is freestanding.  In n4849, the search would miss` __STDC_HOSTED__` in [cpp.predefined].

I recommend editorially changing the text.

Edit cpp.predefined 1.5:

The integer literal 1 if the implementation is a hosted implementation or the integer literal 0 if it is ~not~ <ins>a freestanding implementation</ins>.

**Comment by expnkx** [comment]
I found this fucking issue too. It is annoying for me.
