### ISSUE TITLE
[class.this] has no novel normative wording

### ISSUE THREAD

**Issue by sdkrystian** [cplusplus/draft#3930]
It might be time to remove (or change to point to [expr.prim.this]) [[class.this]](http://eel.is/c++draft/class.this). It only has 3 normative sentences, the first 2 being redundant by [expr.prim.this] and the third by [over.match.funcs].

**Comment by languagelawyer** [comment]
Gonna be fixed by [P1787 Declarations and where to find them](http://wg21.link/p1787)

**Comment by jensmaurer** [comment]
Removed by P1787.
