### ISSUE TITLE
[dcl.init]/14 should probably consider parenthesized initializer for arrays CWG2708

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#3931]
[\[dcl.init\]/14](http://eel.is/c++draft/dcl.init#14):

> If the entity being initialized does not have class type, the *expression-list* in a parenthesized initializer shall be a single expression.

This seems to conflict with [P0960R3: Allow initializing aggregates from a parenthesized list of values](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0960r3.html) (merged in f29e482), which intends to allow `int a[](1, 2, 3);`.

**Comment by jensmaurer** [comment]
This looks like normative CWG territory to me.

**Comment by frederick-vs-ja** [comment]
This is now CWG2708 (resolved by #6328 (https://github.com/cplusplus/draft/commit/f4bb20593b16bcb2a3ff494787fb206d2e9434a6)).
