### ISSUE TITLE
[algorithms.results] Chapter defines class templates not in header <algorithm> synopsis chapter

### ISSUE THREAD

**Issue by amurzeau** [cplusplus/draft#3946]
Each clause contains one or several "Headers <....> synopsis" chapters that define what is defined in the given header.

But for the algorithms library, chapter `25.5 Algorithm result types [algorithms.results]` defines additional classes not in the `25.4 Header <algorithm> synopsis [algorithm.syn]` chapter.

Affected classes are (non exhaustive list, based on latest draft release N4861):
```cpp
namespace std::ranges {
    template<class I, class F> struct in_fun_result;
    template<class I1, class I2> struct in_in_result;
    template<class I, class O> struct in_out_result;
    template<class I1, class I2, class O> struct in_in_out_result;
    template<class I, class O1, class O2> struct in_out_out_result;
    template<class T> struct min_max_result;
    template<class I> struct in_found_result;
}
```

I think that, for coherency with other library headers, these chapters (`[algorithms.results]` and `[algorithm.syn]`) should be somehow merged together.

**Comment by jensmaurer** [comment]
These class templates are mentioned in [algorithm.syn] nowadays, right at the top.
