### ISSUE TITLE
[depr.atomics] Possible header name typo: <atomics> vs <atomic>

### ISSUE THREAD

**Issue by amurzeau** [cplusplus/draft#3947]
The [chapter `D.24 Deprecated atomic operations [depr.atomics]`](https://github.com/cplusplus/draft/blob/aa7a738d66aa3ecb4c609048ebd2db20cc005aec/source/future.tex#L2661) refer to the `<atomics>` header, but the linked chapter `31.2 Header <atomic>synopsis [atomics.syn]` uses the header name `<atomic>` instead (without `s`).

This possible typo was introduced in https://github.com/cplusplus/draft/commit/bbb46260d5dd0bb8b561cc74f929ac9a982629a9.

The chapter `depr.atomics` should probably be fixed to use the header name without `s`: `<atomic>`.

**Comment by jensmaurer** [comment]
Thanks for the hint.
