### ISSUE TITLE
[expr.throw#2] incorrectly dropping cv-qualifiers CWG2699

### ISSUE THREAD

**Issue by JustAnotherHumanBeing** [cplusplus/draft#3959]
This part of the C++ Standard says: **Evaluating a throw-expression with an operand throws an exception; the type of the exception object is determined by removing any top-level cv-qualifiers from the static type of the operand and adjusting the type from “array of T” or function type T to “pointer to T”** .
One might think that this passage implies that if we are dealing with the operand of type **const char[3]** , the const qualifier will be removed from it and then **char[3]** will be adjusted to type **char*** .

**Comment by sdkrystian** [comment]
This will be resolved by #3921

**Comment by JustAnotherHumanBeing** [comment]
According to #3921, "any top-level cv-qualifiers from the type of the (possibly-converted) operand" will be removed. But if they are prvalues, object pointers and function pointers can't have top-level cv-qualifiers.

**Comment by sdkrystian** [comment]
Yes, no cv-qualifiers would be removed in such cases as there are none to remove. Is that problematic?

**Comment by JustAnotherHumanBeing** [comment]
Well, that part of the sentence is ambiguously written because it assumes that a reader knows that such prvalues can't have a top-level const.

**Comment by sdkrystian** [comment]
The end result would still be the same?

**Comment by JustAnotherHumanBeing** [comment]
Okay.

**Comment by jensmaurer** [comment]
CWG2699

**Comment by frederick-vs-ja** [comment]
This should have been fixed by #6328 (https://github.com/cplusplus/draft/pull/6328/commits/3588b7d3fab8e6d655769d61768682b23d493164).
