### ISSUE TITLE
[vector.capacity]p17/18 has two paragraph numbers

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#3982]
[vector.capacity]/17 has two paragraph numbers, that are rendered superimposed on top of each other.

We should fix this for the C++20 IS.

**Comment by jensmaurer** [comment]
@zygoloid , here you are.

**Comment by Eelis** [comment]
Maybe that \pnum is the one that's missing from the Effects clause immediately below. :)

**Comment by jensmaurer** [comment]
Good point. Fixed.
