### ISSUE TITLE
[thread.syn] Should <thread> include <initializer_list>?

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#3988]
[This commit](https://github.com/cplusplus/draft/pull/3748/commits/abaa67fbeba0043aaad6ba22b87a39e8bd92929f) added `#include <initializer_list>` to the synopsis of `<thread>`. However, it seems that [LWG3330](https://cplusplus.github.io/LWG/issue3330) only requires including `<compare>`.

**Comment by jensmaurer** [comment]
Indeed, that appears to be a misapplied motion.

@burblebee , can you shed some light onto this?
@zygoloid , this probably needs to be fixed in the C++20 DIS as well. Attaching the milestone.

**Comment by jwakely** [comment]
Looks like a copy&paste error from one of the other headers where a comment was being added to the `#include <initializer_list>` line.
