### ISSUE TITLE
Editorial: Make names and synopses of unordered_* consistent with other containers

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#400]
- The synopses for `unordered_*` don't contain sections before comments like `// modifiers`, whereas the other container synopses do.
- Unordered containers use `k` for key parameters, ordered associative containers use `x`.
- Unordered containers use `hint` for the hint iterator, other containers use `position`.

We should make this consistent.

Suggestion:
- Use `hint` for hints, `position` for everything else. This requires changing the ordered containers.
- Use `k` for the key, and `obj` for a parameter for the `value_type` or the `mapped_type`. This requires changing the ordered containers.
- Always refer to the section name in comments. This requires changing the unordered containers.

If we agree with these changes, I can create a suitable pull request. Please let me know.

**Comment by zygoloid** [comment]
Diff is visible here: https://github.com/cplusplus/draft/commit/3dd61428d27a091bd16d833598805f0a93bbb319.patch

@jwakely Can I interest you in reviewing this?

**Comment by jwakely** [comment]
The first 18% of the patch looks perfect, but for the purposes of reviewing it, and also for the revision history ("what introduced this change?" "oh, it was that 3000 line patch that fixed loads of unrelated issues") I'd like it to be split into logically separate changes that I can review and merge piecemeal.

**Comment by tkoeppe** [comment]
Offline discussion suggested that these changes better be split into several smaller PRs. Please consider the original diff obsolete, and I will send a number of new PRs.
