### ISSUE TITLE
[concept.swappable] Missing an index entry for ranges::swap

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#4003]
The `ranges::swap` CPO is in the `<concepts>` header, quite removed from the original `swap` function in the `<utility>` header.  It should have its own index entry so that it is easy to find.

**Comment by jensmaurer** [comment]
@AlisdairM , do you have any specific index entry formatting in mind? We already have a cross-reference to ranges::swap under the name "swap".

**Comment by AlisdairM** [comment]
An index entry under 'swap' for ranges::swap is exactly what I was thinking of, but I do not see it in the index - I just triple checked on my current build from 'master'.  Nor do I see it added in the linked PR #4008.  Maybe I mis-understood where to look for the existing reference?

**Comment by jwakely** [comment]
In the index of library names, the first entry for `swap` which goes to page 540, where [concept.swappable] defines `ranges::swap` in p2.
