### ISSUE TITLE
www.open-std.org not reachable over a secure connection (TLS)

### ISSUE THREAD

**Issue by practicalswift** [cplusplus/draft#4006]
First, thanks a lot for all the excellent standardization work that keeps C++ relevant!

Now to my issue: it seems like `www.open-std.org` is not reachable over a secure connection (TLS).

Apologies in advance if this is the incorrect repo to report this - if so, please let me know where to report :)

**Comment by jwakely** [comment]
Contact the webmaster of that site, at the address shown at the bottom of the page. It's nothing to do with this repo.

**Comment by practicalswift** [comment]
Thanks for clarifying! I incorrectly assumed that the site was somehow related to this repo. Sorry!
