### ISSUE TITLE
I have a question. Is this true?

### ISSUE THREAD

**Issue by delata** [cplusplus/draft#4015]
Is this true or made up?
http://harmful.cat-v.org/software/c++/I_did_it_for_you_all

please don't close this issue without giving answer. and don't flag my account

**Comment by jensmaurer** [comment]
This issue tracker is for editorial issues concerning working drafts of the C++ standard. Your question seems profoundly off-topic.

**Comment by delata** [comment]
shut up and answer my question.
c++ is a horrible language. every one knows that.
Linus, RMS, Alan, Brian

**Comment by delata** [comment]
response

**Comment by jwakely** [comment]
It's not true, obviously. Please stop wasting our time.

**Comment by delata** [comment]
can you prove

**Comment by delata** [comment]
ask bjarnee
