### ISSUE TITLE
[class.default.ctor]/4 /5 Constructors do not create objects

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#4019]
/4: A default constructor that is defaulted and not defined as deleted is implicitly defined when it is odr-used ([basic.def.odr]) to **create** an object of its class type

/5: Default constructors are called implicitly to **create** class objects of static, thread, or automatic storage duration ([basic.stc.static], [basic.stc.thread], [basic.stc.auto]) defined without an initializer ([dcl.init]), are called to **create** class objects of dynamic storage duration

**Comment by jensmaurer** [comment]
Any suggestion for improvement?

**Comment by languagelawyer** [comment]
Maybe just `s/create/initialize/`?
