### ISSUE TITLE
[lex.name] Don't talk about upper/lower case letters

### ISSUE THREAD

**Issue by jfbastien** [cplusplus/draft#4024]
From a recent SG16 discussion on [P1949](https://github.com/cplusplus/papers/issues/688), we're going to have this note:

> [ Note: Upper- and lower-case letters are considered different for all identifiers. – end note ]

I said:

> It would be better to say "case-sensitive" instead of differentiating upper and lower-case letters, because there's awkward stuff such as:
> https://en.wikipedia.org/wiki/Capital_%E1%BA%9E

Jens said:

> Yes, but that's a bit out-of-scope of this paper, since the text in question is pre-existing.

I'm filing this bug so we follow up editorially

**Comment by jensmaurer** [comment]
This should be addressed after [P2029R4](https://wg21.link/p2029) Proposed resolution for core issues 411, 1656, and 2333; numeric and universal character escapes in character and string literals #760 was merged (Nov 2020 virtual meeting).

**Comment by jensmaurer** [comment]
This phrase will be removed by [P1949](https://wg21.link/p1949) C++ Identifier Syntax using Unicode Standard Annex 31 #688

**Comment by jensmaurer** [comment]
P1949 was merged 2021-06, but the upper/lowercase phrasing is still present.
