### ISSUE TITLE
inconsistently including or omitting comma between "// x.y.z" and rest of comment in synopses

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#403]
See for instance 20.8.1.2

>  // 20.8.1.2.4, observers
>  // 20.8.1.2.5 modifiers

... but this inconsistency occurs in lots of places. We should pick one style and stick to it.

**Comment by jensmaurer** [comment]
So, which one do you pick?

**Comment by tkoeppe** [comment]
I'd prefer the style

    // 1.2.3, description:

I believe that's a widely used style in the library.

**Comment by jensmaurer** [comment]
Richard?

**Comment by jensmaurer** [comment]
Duplicate of #802.
