### ISSUE TITLE
[string.view.template] Deduction guide specified far from constructors

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#4039]
`array`'s is specified right after the constructors, in the same subclause.
`span`'s are specified on their own subclause after the special member functions'.
`string_view`'s are right before the non-member functions. There's a lot of material between its special member function specifications and the non-members'.

**Comment by jensmaurer** [comment]
We often have a subclause "member functions", but deduction guides are not one of these, so they don't really fit there. On the other hand, they should really go next to the constructors, semantically.

**Comment by JohelEGP** [comment]
Based on https://github.com/cplusplus/draft/issues/5385#issuecomment-1100831004, do you agree with this issue, @jwakely?

**Comment by jwakely** [comment]
That comment was about where we declare the deduction guides, and string view's are consistent: they're declared with the class synopsis.

I wasn't expressing an opinion about where we put the detailed specifications. But I wouldn't object to moving [string.view.deduct] immediately after [string.view.cons]. That makes sense from the "telling you how you can initialise the type" perspective.
