### ISSUE TITLE
[lib] Non-member swap inconsistently specified in class synopsis

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#4041]
| In header synopsis only | In class synopsis |
| ------------------ | ----------------- |
| pair, tuple, optional, variant, any |
| {unique,shared}_ptr | weak_ptr |
| | function |
| array, stack | deque, forward_list, list, vector-not-of-bool, (multi){map,set}, unordered_(multi){map,set}, (priority_)queue |
| valarray |
| | basic_{stringbuf,(i,o)stringstream,filebuf,(i,o)fstream,syncbuf} **(only)** |
| fs::path |
| basic_regex, match_results |
| thread |
| | {unique,shared}_lock |
| | promise, packaged_task

The remaining are friends or depend on the generic `std::swap` via ADL.

**Comment by johelegp** [comment]
Considering https://github.com/cplusplus/draft/pull/4037#issuecomment-738940101 and https://github.com/cplusplus/draft/pull/4035#issuecomment-738941326, does this still need the decision-required tag?

**Comment by jensmaurer** [comment]
Summary of editorial meeting consensus documented in #4035 and #4037: non-member swap should be in the header synopsis, not in the class synopsis.
