### ISSUE TITLE
[dcl.init]/11 and [dcl.init]/(17.4) say the same thing?

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#4047]
[dcl.init]/11: An object whose initializer is an empty set of parentheses, i.e., `()`, shall be value-initialized.

[dcl.init]/17:
> The semantics of initializers are as follows. The destination type is the type of the object or reference being initialized and the source type is the type of the initializer expression. If the initializer is not a single (possibly parenthesized) expression, the source type is not defined.
...
(17.4) — If the initializer is `()`, the object is value-initialized.

**Comment by zygoloid** [comment]
Addressed by #3891.
