### ISSUE TITLE
[special.mem.concepts] Append -for to no-throw-sentinel

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#4050]
I can't find proof to thinking that maybe it was decided not to rename this one.

**Comment by jensmaurer** [comment]
This is an exposition-only name, so we could editorially rename this, but I'd like to have buy-in from LWG before doing so.
@jwakely and @CaseyCarter , what's your viewpoint?

**Comment by CaseyCarter** [comment]
> I can't find proof to thinking that maybe it was decided not to rename this one.

P1754 largely ignored exposition-only concepts since it wasn't crucial to get their naming correct for C++20. I agree that _`no-throw-sentinel-for`_ is an improvement in consistency with the normative concept names.

**Comment by jwakely** [comment]
Works for me. We could also drop the hyphen in *no-throw* for consistency with numerous type traits.

**Comment by CaseyCarter** [comment]
> Works for me. We could also drop the hyphen in _no-throw_ for consistency with numerous type traits.

If you can convince the editor that "nothrow" is one word instead of two, I won't stand in your way ;)

**Comment by johelegp** [comment]
Opened #4101 for the _`no-throw`_ renaming.
