### ISSUE TITLE
[specialized.algorithms] for loop bodies inconsistently a compound-statement

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#4053]
4 *compound-statemet*s vs 14 *expression-statement*s.
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10224-L10228
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10247-L10251
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10264-L10268
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10303-L10307
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10326-L10330
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10343-L10348
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10387-L10391
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10421-L10426
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10444-L10449
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10499-L10504
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10530-L10535
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10560-L10564
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10612-L10616
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10634-L10639
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10652-L10657
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10738-L10741
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10760-L10764
https://github.com/cplusplus/draft/blob/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/algorithms.tex#L10777-L10781

**Comment by jensmaurer** [comment]
It seems not having the braces is the path to consistency incurring the least changes.
