### ISSUE TITLE
[expr.const] "as described above"... where?

### ISSUE THREAD

**Issue by BRevzin** [cplusplus/draft#4077]
In [expr.const], we have [footnote 80](http://eel.is/c++draft/expr.const#footnote-80) which reads:

> Testing this condition may involve a trial evaluation of its initializer as described above.

This footnote is supposed to help us understand what the "or has constant initialization" part means.

Firstly, should "or has constant initialization" read "or is constant-initialized" since that's the term that's defined in [expr.const]/2?

Second, described above _where_? Can the footnote actually point to the section that it's referring to? I don't actually know what it's referring to at the moment.

**Comment by jensmaurer** [comment]
"constant initialization" is defined in [basic.start.static] p2. Note the limitation to variables with static or thread storage duration.

"as described above" refers to the trial evaluation described in [expr.const] p2.2: "when interpreted as a constant-expression". We don't cross-references individual paragraphs of a section, so it's hard to make the pointer more precise.

**Comment by jensmaurer** [comment]
Would it help to add a cross-reference to [basic.start.term] after "constant initialization"?

**Comment by BRevzin** [comment]
Oh yeah, that would help tremendously.
