### ISSUE TITLE
[dcl.type.auto.deduct] Incorrect description of deduction for a variable with copy-initialization?

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#4088]
[[dcl.type.auto.deduct]/2](http://eel.is/c++draft/dcl.type.auto.deduct#2) says:
"""
A type `T` containing a placeholder type, and a corresponding initializer _E_, are determined as follows: 
­— for a variable declared with a type that contains a placeholder type, `T` is the declared type of the variable and _E_ is the initializer. ...
"""

[[dcl.type.auto.deduct]/4](http://eel.is/c++draft/dcl.type.auto.deduct#4) says:
"""
If the _placeholder-type-specifier_ is of the form _type-constraint_<sub>opt</sub> `auto`, the deduced type `T` replacing `T` is determined using the rules for template argument deduction.
Obtain `P` from `T` by replacing the occurrences of _type-constraint_<sub>opt</sub> `auto` either with a new invented type template parameter `U`, or ... [doesn't matter].
Deduce **a value** (!!!) for `U` using the rules of template argument deduction from a function call, where `P` is a function template parameter type and the corresponding argument is _E_.
...
[Example:
```
const auto &i = expr;
```
The type of `i` is the deduced type of the parameter `u` in the call `f(expr)` of the following invented function template:
```
template <class U> void f(const U& u);
```
— end example]
"""

There are several issues here (both in normative wording and the Example): the major one is that for a variable declared as `const auto &i = expr;`, the initializer is `= expr`, not `expr`. And one can't call a function with this initializer as an argument, like `f(= expr)`. ~~Probably, the paragraph should say that the initializer _E_ is the **default** argument of an invented function template (and the type is deduces as if the function is called without argument)?~~ Nah, the grammar for _parameter-declaration_ doesn't allow _initializer_.

Also, is it ok that the Standard calls the deduced type "a **value** of a type parameter" and uses the instructing tone like _Obtain `P` from `T` ..._ _Deduce a value ..._.

**Comment by jensmaurer** [comment]
I think "a value of a type parameter" is fine, and we also employ "obtain P from T" phrasing quite a bit in the template argument deduction area.

Properly removing the "=" from the initializer is an issue, though.

**Comment by xmh0511** [comment]
So, how about this?  `decltype(auto) x2d(i);  // decltype(x2d) is int`？   
> If the placeholder-type-specifier is of the form type-constraint <sub>opt</sub>  decltype(auto), T shall be the placeholder alone. The type deduced for T is determined as described in [dcl.type.decltype], as though E had been the operand of the decltype.  

That means `E` would be `(i)` which is the initializer, hence, `decltype((i))` should be deduced to `int&`.  I think we should preprocess the form of `initializer` in this description.
