### ISSUE TITLE
[special.mem.concepts] Remove hyphen in _no-throw_ for consistency with the type traits

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#4101]
See https://github.com/cplusplus/draft/issues/4050#issuecomment-647085151.

**Comment by jensmaurer** [comment]
While our type traits are named is_nothrow_something, we also have NoThrowForwardIterator (note capital F, indicate a new word).

If we fix this, we should remove the hyphen from "no-throw" (names of exposition-only concepts) and we should rename NoThrowForwardIterator to NothrowForwardIterator for consistency.

**Comment by tkoeppe** [comment]
@jwakely: Thoughts? We're inclined to drop the hyphen and say "nothrow" everywhere.

**Comment by jwakely** [comment]
I think making _`nothrow-sentinel-for`_ consistent with `nothrow_constructible` makes sense. I'm less convinced that _NothrowFoo_ is an improvement on _NoThrowFoo_.

**Comment by tkoeppe** [comment]
Right, I'd also be happy with keeping the camel-case "NoThrow", that seems inoffensive enough. @jensmaurer: could you live with "nothrow-foo" and "NoThrowFoo"?

**Comment by jensmaurer** [comment]
I'm ok with that; it's an incremental improvement which we can iterate on in the future should the pain about NoThrowFoo grow.

**Comment by tkoeppe** [comment]
Great, let's do that then: snake-case `nothrow_foo` without hypen, and camel-case can use `NoThrowFoo` is desired.
