### ISSUE TITLE
`<` characters are also allowed in q-char-sequence's

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#4109]
[\[cpp.include\]/3](http://eel.is/c++draft/cpp#include-3):

> A preprocessing directive of the form
> 
> &nbsp;&nbsp;&nbsp;&nbsp;**# include** " _q-char-sequence_ " _new-line_
> 
> causes the replacement of that directive by the entire contents of the source file identified by the specified
> sequence between the " delimiters. The named source file is searched for in an implementation-defined
> manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read
> 
> &nbsp;&nbsp;&nbsp;&nbsp;**# include** _< h-char-sequence >_ _new-line_
> 
> with the identical contained sequence (including `>` characters, if any) from the original directive.

The `<` character is missing in the last sentence above.

**Comment by jwakely** [comment]
No, I don't think it's missing, it doesn't need to be there. The point is that _h-char-sequence_ doesn't normally allow `>` because it isn't an _h-char_. But `<` is allowed in an _h-char-sequence_ so there's no need to say anything special about it.

**Comment by jensmaurer** [comment]
Agreed.
