### ISSUE TITLE
Do destructors have names?

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#414]
N4296 7.3.3 [namespace.udecl]/4 says `Since destructors do not have names, a using-declaration cannot refer to a destructor for a base class.` But 12.4 [class.dtor]/13 mentions "the destructor name" (in the sentence `In an explicit destructor call, the destructor name appears as a ~ followed by a type-name or decltype-specifier that denotes the destructor’s class type.`)

So, do destructors have names or not?

**Comment by zygoloid** [comment]
We have a precise definition for "name", but we don't stick to it. For instance:

[basic.def.odr]p3: "A variable whose name appears as a potentially-evaluated expression ex is odr-used by ex unless [...]"
This presumably means "A potentially-evaluated id-expression ex that refers to a variable x odr-uses x unless [...]"
But according to the definition of "name", the id-expression need not refer to the variable x; it can refer to another variable in a different declarative region that merely has the same identifier as its name!

Later on in p6, we have the same problem; the ODR doesn't take the declarative region of the entity into account.

And so on. We really need a comprehensive study of where "name" is used and misused.


I've forwarded this to CWG for discussion as to how best to proceed.

**Comment by tkoeppe** [comment]
This is obsolete, the wording has been fixed.

**Comment by cpplearner** [comment]
Fixed by [CWG 2069](http://wg21.link/cwg2069).
