### ISSUE TITLE
Inconsistent description of C++ extensions to header <cstddef>

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#4144]
In addition to importing the contents of <stddef.h> into namespace std, the header <cstddef> also adds the typedef nullptr_t, and type byte, and operations on type byte.  This additions are partially described in two different locations:
[cstddef.syn]p1 notes the addition of byte and its operations, but makes no mention of nullptr_t.
[diff.mods.to.declarations]p3 (in the C compatibility annex) notes the addition of nullptr_t, but says nothing about byte and its operations.

For consistency, we should either consolidate this descriptive material to either one place, or duplicate it completely in both.  Opening and issue, rather than filing an initial PR, as not sure which direction would be preferred.

**Comment by tkoeppe** [comment]
As far as I can tell, [cstddef.syn] does contain `nullptr_t`, https://github.com/cplusplus/draft/blob/aca06a26a0048a4437fafeed573b347ef4209f5e/source/support.tex#L58.

I agree that we should add mention of `nullptr_t` to [depr.c.header.others].

**Comment by tkoeppe** [comment]
As @jwakely noted in my attempted PR, modifying [depr.c.header.others] is a normative change that I'd like to discuss in an issue. I will open one if you don't mind.

PR #4145 contains a proposed change to [diff.mods.to.declarations], could you please take a look?

**Comment by jensmaurer** [comment]
See LWG3484
