### ISSUE TITLE
[basic.life] "Otherwise, such a pointer/glvalue refers to allocated storage" is unclear CWG2551

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#4153]
[basic.life]/6:
"""
Before the lifetime of an object has started but after the storage which the object will occupy has been allocated29 or, after the lifetime of an object has ended and before the storage which the object occupied is reused or released, any pointer that represents the address of the storage location where the object will be or was located may be used but only in limited ways.
For an object under construction or destruction, see [class.cdtor].
Otherwise, such a pointer refers to allocated storage ([basic.stc.dynamic.allocation]) ...
"""

[basic.life]/7:
"""
Similarly, before the lifetime of an object has started but after the storage which the object will occupy has been allocated or, after the lifetime of an object has ended and before the storage which the object occupied is reused or released, any glvalue that refers to the original object may be used but only in limited ways.
For an object under construction or destruction, see [class.cdtor].
Otherwise, such a glvalue refers to allocated storage ([basic.stc.dynamic.allocation]) ...
"""
The meaning of [the beginning of] the last-cited sentences is unclear, especially from the pointer values taxonomy POV.

**Comment by jensmaurer** [comment]
I'm unsure what part of this could be addressed editorially.

**Comment by jensmaurer** [comment]
Created CWG2551
