### ISSUE TITLE
[fs.norm.ref] Dissolve and follow #4175 suit

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#4176]
After #4175, I think [fs.norm.ref] should be dissolved, POSIX removed from the footnote (as it is earlier in the document), and the rest of the footnote moved to the first mention of Windows(r) (after changing "these products" to "this product").

**Comment by zygoloid** [comment]
Merged to master in 2976a219434eed674db28b8ae984a4ee11a7eafe.
