### ISSUE TITLE
Inconsistent spelling of "whitespace"

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#4196]
Looking through the sources, I find at least 3 distinct spelling of "whitespace":
   whitespace
   white-space
   white space

We should choose one canonical spelling, and use it consistently.

**Comment by jensmaurer** [comment]
Statistics:

jmaurer@gavotte:~/C++/draft/source$ grep "white space" *.tex | wc -l
22
jmaurer@gavotte:~/C++/draft/source$ grep "white-space" *.tex | wc -l
15
jmaurer@gavotte:~/C++/draft/source$ grep "whitespace" *.tex | wc -l
12

Wikipedia spells this "whitespace" (single word); we no longer mean "white space" as opposed to "yellow space" (what is that?). Whether the space is actually white, as on paper, is questionable on a computer screen.

**Comment by jensmaurer** [comment]
If we want to go "whitespace", the patch is here: #4211
