### ISSUE TITLE
[c++20] The last item in [cpp.predefined] looks very silly

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#4204]
[cpp.predefined] has a list of predefined macros along with descriptions. We have an unfortunate page break that puts this on a new page, all by itself:

> The names listed in Table 19.
> > The macros defined in Table 19 shall be defined to the corresponding integer literal.
> > [*Note 3*: Future revisions of C++ might replace the values of these macros with greater values. —*end note*]

Adding bullets to this list would help, as would somehow forcing Table 19 to start on the previous page.

**Comment by jensmaurer** [comment]
Shuffling the offending item to the middle, just after the other "year-month" macro we have, fixes the issue.

**Comment by zygoloid** [comment]
Merged to master in bf5a7e48c6c05bc27918e5e149f582d9bcbc5b34.
