### ISSUE TITLE
Statement in the Note in [class.union.anon]/1 should have normative status

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#4210]
[[class.union.anon]/1](http://eel.is/c++draft/class.union.anon#1):

> A union of the form
> &nbsp;&nbsp;&nbsp;&nbsp;`union {` *member-specification* `} ;`
> is called an *anonymous union*; it defines an unnamed type and an unnamed object of that type called an
> *anonymous union object*. Each *member-declaration* in the *member-specification* of an anonymous union shall
> either define a non-static data member or be a *static_assert-declaration*. [**Note: Nested types, anonymous
> unions, and functions cannot be declared within an anonymous union. — end note**] The names of the
> members of an anonymous union shall be distinct from the names of any other entity in the scope in which
> the anonymous union is declared. `...`
> 

Note also that the last statement in the next paragraph is a mere duplication of a similar statement in the Note above.

[[class.union.anon]/2](class.union.anon#2):

> Anonymous unions declared in a named namespace or in the global namespace shall be declared `static`.
> Anonymous unions declared at block scope shall be declared with any storage class allowed for a block-scope
> variable, or with no storage class. A storage class is not allowed in a declaration of an anonymous union in a
> class scope. An anonymous union shall not have private or protected members (11.9). **An anonymous union
> shall not have member functions**.

**Comment by jensmaurer** [comment]
For your first point above, the sentence just in front of the note says

"Each member-declaration in the member-specification of an anonymous union shall
either define a non-static data member or be a static_assert-declaration."

Why do you think the note needs to be normative, since none of the items listed in the note are non-static data members (or static_asserts)?

I agree with your second point.

**Comment by jabelloc** [comment]
I observed in your [pull-request](https://github.com/cplusplus/draft/pull/4212/commits/91b99fdaa514ab1b5c396838d938d86fc09bcc0a) that you have also removed from [[class.union.anon]/2](http://eel.is/c++draft/class.union.anon#2) the following sentence:

> An anonymous union shall not have private or protected members

Was this your intention, or was it inadvertent?

**Comment by jensmaurer** [comment]
That was intentional. See the addition of "public" in p1.

**Comment by jabelloc** [comment]
I remember having read this "public" someplace before, but I can't find it now in [[class.union.anon]/1](http://eel.is/c++draft/class.union.anon#1). Could you give the link again for this addition?

**Comment by jensmaurer** [comment]
See the pull request #4212, the second green blob.

**Comment by jabelloc** [comment]
I have just found that. Thanks.
