### ISSUE TITLE
Process: final page-by-page review

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#4219]
This is a tracking issue to discuss the various steps we should perform duing the final review.

Once we agree on the set of steps, I would like to add them to the editorial wiki.

Let's begin with the context:

One of the last steps before we send the final PDF to ISO is to review the candidate document page-by-page to look for "glaring errors". This shouldn't require close attention to the text, but instead focus on the overall presentation. As such, this should be relatively quick, with only a few seconds spent on each page. If we share the workload, then this is best done along Clause boundaries for vertical reasons.

The goal is to make the document look as nice as possible, and at this stage we can use one-shot changes that do not need to be sustainable and that will not be carried forward into the main branch. The main tool of this nature is adding explicit page breaks.

I will post one comment for each individual step.

**Comment by tkoeppe** [comment]
**Hanging paragraphs.** We no longer tolerate these. If you find any, also notify #4170 so we can update the detection logic.

**Comment by zygoloid** [comment]
Final comments by Dawn in #4275. From me:

[dcl.type.simple]/2: too much vertical whitespace before grammar excerpt
[class.union.anon]/1: too much vertical whitespace before example
[class.derived.general]/5: spurious line break before end of note
[class.mi]/5: weird linebreak in the middle of a note; presumably Figure 5 was expected to appear there?

Review done up to Clause 20.
