### ISSUE TITLE
It seems to an editorial issue for the comment in an operator over example

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4226]
Consider the example in [over.match.oper#7](https://eel.is/c++draft/over.match.oper#7), that is:  
````cpp
struct A {
  operator int();
};
A operator+(const A&, const A&);
void m() {
  A a, b;
  a + b;                        // operator+(a, b) chosen over int(a) + int(b)
}
````
Note the comment in this code, it sounds like the best overload is built-in operator. However, For this example, the candidate functions  are a non-member user-defined function for operator `+` and a built-in operator, according to [over.match.best], convert these operands of type `A` to what the type build-in `+` expects, there are user-defined conversion sequences applied to these original operands, conversely, for user-declared  operator `+`, only identity conversion applied to these operands, which is standard conversion sequences. Obviously, the later is more better. why the comment said `chosen over int(a) + int(b)`?  GCC and Clang all agree that `A operator+(const A&, const A&)` is the best [overload](https://godbolt.org/z/TE9K9r), Is it a typo?

**Comment by jensmaurer** [comment]
I disagree that the comment claims that the best operator is the built-in operator.
It clearly says you choose the (user-defined) operator+ in preference over the built-in operator.
"choose X over Y" means "take X because it's better / you like it more than Y".
