### ISSUE TITLE
Process: page-by-page review tracking

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#4228]
See #4219 for detailed instructions.

Please edit this comment to claim a section of the document.
DP: See comment for questions about the sections I reviewed.

- {TK: good} Front matter + Clauses 1, 2, 3
- {TK: done} 4 General principles[intro]
- {TK: done} 5 Lexical conventions[lex]
- {TK: done} 6 Basics[basic]
- {DP: done} 7 Expressions[expr]
- {DP: done} 8 Statements[stmt.stmt]
- {DP: done} 9 Declarations[dcl.dcl]
- {DP: good} 10 Modules[module]
- {DP: done} 11 Classes[class]
- {DP: done} 12 Overloading[over]
- {DP: done, see note in comment below} 13 Templates[temp]
- {DP: good} 14 Exception handling[except]
- {DP: good} 15 Preprocessing directives[cpp]
- {DP: done} 16 Library introduction[library]
- {DP: done} 17 Language support library[support]
- {DP: done} 18 Concepts library[concepts]
- {DP: good} 19 Diagnostics library[diagnostics]
- {DP: done} 20 General utilities library[utilities]
- {DP: done} 21 Strings library[strings]
- {DP: done} 22 Containers library[containers]
- {TK: done} 23 Iterators library[iterators]
- {TK: done} 24 Ranges library[ranges]
- (JM: done) 25 Algorithms library[algorithms]
- (JM: good) 26 Numerics library[numerics]
- (JM: done; still done after "tailnote") 27 Time library[time]
- (JM: done) 28 Localization library[localization]
- (JM: re-done after #4249) 29 Input/output library[input.output]
- (JM: done) 30 Regular expressions library[re]
- (JM: done) 31 Atomic operations library[atomics]
- {JM: ~done~ ~please revisit~ still done} 32 Thread support library[thread]
- {TK: done} Annex A (informative) Grammar summary[gram]
- {TK: good} Annex B (~informative~ normative) Implementation quantities[implimits]
- {TK: done} Annex C (informative) Compatibility[diff]
- {TK: done} Annex D (normative) Compatibility features
- {TK: done} Back matter

Key:

* "good": Good as is, no changes needed.
* "done": Good after review, but changes need to be applied (and are ready to be merged).
* anything else: still needs attention

**Comment by tkoeppe** [comment]
Please reference this isse (#4228) in pull requests (onto the `c++20` branch) for one-off tweaks, or for pull reqests onto `master` for permanent changes.

**Comment by tkoeppe** [comment]
**Merging notes:** The following changes were made to the main branch and need to be cherrypicked.

* https://github.com/cplusplus/draft/pull/4232

**Comment by burblebee** [comment]
Comments/Questions about the sections I reviewed:

Cases of Notes inside sentences - how to fix?
* [expr.const] p5.2 #147
* [expr.const] p5.7 #147

Cases where a section is near the end of a page - which of these should be fixed?
* [expr.alignof] 7.6.2.6 #129
* [over.match.call]
* Note: [stmt.ambig] Adding page break caused "-end example]" to spill to next page, so not done.

Cases where "[Example" was followed by a page break - which of these should be fixed?
* 7.5.4.2p2 #101
* 7.6.1.3p8 #117
* 7.6.1.8p5 #121
* 7.6.1.9p13 #123
* 7.6.2.8p3 #130
* 9.2.4p1 #168
* 9.2.9.6.1p4 #178
* 9.3.4.4p2 #188
* 9.9p3 #231
* 9.11p7 #238
* 9.12.7p5 #244
* 13.5.3 #376
* 13.8.5.2p2 #414
* 13.9.2p12 #421

Cases where "- end example]" ran over to the next page - which of these should be fixed?
* 9.3.4.7p5 #196
* 10.2p5 #250
* 12.4.4.1p2.7 #341
* 13.7.3p1 #384
* 13.8.3.2p7 #411
* 13.9.3p15 #426
* 13.9.4p16 #430

Someone please review [Clause 8] Expressions to see if I'm catching everything (except for what's listed here) - my changes are in branch c++20_tweaks.

Why do we sometimes start a section with "Preamble" vs. "General"?  I know the "General" sections were added in response to IS, but many seem to contain the same sort of information as the "Preamble"s.

**Comment by jensmaurer** [comment]
"Preamble" was our earlier incomplete attempt at avoiding "hanging paragraphs". I'm sure we'll address some of the recently added "General" paragraphs for C++20 and maybe rename them or dissolve them.

**Comment by tkoeppe** [comment]
@jensmaurer: Could you kindly re-review 32[thread] following https://github.com/cplusplus/draft/commit/1661a8a695a43a03194b4076a20fb879eafe0b88?

**Comment by jensmaurer** [comment]
"Cases of Notes inside sentences changed to footnotes - is the space before the footnote ok?"
Add a % sign on the line before the `\footnote`. This prevents the space. (My new `\footnoteenv` will get rid of the space regardless, but that's for C++23.)

**Comment by jensmaurer** [comment]
"Could you kindly re-review 32[thread] following 1661a8a?"
Done, everything still fine.

**Comment by tkoeppe** [comment]
@burblebee: To fix/force spacing inside codeblocks, you can simply add blank lines to the code.

**Comment by jensmaurer** [comment]
@burblebee: Or insert `@\newpage@` as a separate line.

**Comment by zygoloid** [comment]
All merged.
