### ISSUE TITLE
[class.mem.general] Awkward punctuation around note in list item

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#4236]
![image](https://user-images.githubusercontent.com/22357/94317083-d6574c00-ff85-11ea-9177-da16d427139f.png)

**Comment by tkoeppe** [comment]
Thank you, we'll look at this during the final review. Looks like something we need to rearrange.

**Comment by godbyk** [comment]
I created PR #4241 to address this issue. It makes use of the new `note*` environment in three places (including the one mentioned above).
