### ISSUE TITLE
add an example of conversion-type-id containing a placeholder type

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#424]
The standard contains no examples of `operator auto` or similar; such an example would be helpful, perhaps in [dcl.spec.auto] (maybe in p13, also showing the `foo.operator auto()` syntax for a call) or in [class.conv.fct] (maybe in p7 along with an example showing an ill-formed conversion function template).

**Comment by tkoeppe** [comment]
See the email thread, there's another nice ill-formed example using the trailing return type syntax.

**Comment by jensmaurer** [comment]
Note that the "No return type" phrasing Richard is referring to in his response is no longer there. I've added an example for trailing-return-type.
