### ISSUE TITLE
[range.dangling]p1 is overly long and complex.

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#4247]
Suggested wording (thanks to @jwakely):

> The tag type `dangling` is used together with the template aliases `borrowed_­iterator_­t` and `borrowed_­subrange_­t`. When an algorithm that typically returns an iterator into or subrange of a `range` argument is called with an rvalue `range` argument that does not model `borrowed_range`, the return value could potentially reference a range whose lifetime has ended. In such cases, the tag type `dangling` is returned instead of an iterator or subrange.

**Comment by jwakely** [comment]
@CaseyCarter, @ericniebler, what do you think?

**Comment by tkoeppe** [comment]
Current wording, for comparison:

>  The tag type `dangling` is used together with the template aliases `borrowed_iterator_t` and `borrowed_subrange_t` to indicate that an algorithm that typically returns an iterator into or subrange of a `range` argument does not return an iterator or subrange which could potentially reference a range whose lifetime has ended for a particular rvalue `range` argument which does not model `borrowed_range` (24.4.2).

**Comment by ericniebler** [comment]
LGTM

**Comment by jwakely** [comment]
Thanks.

We should keep the (24.4.2) cross-reference for `borrowed_range` of course, I didn't mean to leave that out in the rewrite.

**Comment by CaseyCarter** [comment]
I note that we _could_ strike the extraneous "rvalue `range`" from the second sentence, leaving only "is called with an argument that does not model `borrowed_range`", but I think the redundancy makes the paragraph more usefully tutorial. So yes, "+1 Tentatively Editorial" from me.

**Comment by jwakely** [comment]
We could also consider adding some commas:

> returns an iterator into, or subrange of, a range argument 

And maybe change "could potentially reference a `range`" to "could potentially refer to a `range`".

**Comment by tkoeppe** [comment]
https://www.iso.org/ISO-house-style.html says:

> A sentence should not contain more than 20 words.

**Comment by CaseyCarter** [comment]
> https://www.iso.org/ISO-house-style.html says:
> 
> > A sentence should not contain more than 20 words.

I feel targeted.

**Comment by tkoeppe** [comment]
Maybe you could feel "standardised" instead?
