### ISSUE TITLE
Class types are not cv-qualified

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#4250]
[[class.derived]/2](http://eel.is/c++draft/class.derived#general-2):

> A _class-or-decltype_ shall denote a (possibly cv-qualified) class type that is not an incompletely defined class ([class.mem]); any cv-qualifiers are ignored. `...`

This should be replaced by:

A _class-or-decltype_ shall denote a <strike>(possibly cv-qualified)</strike> class type that is not an incompletely defined class ([class.mem])<strike>; any cv-qualifiers are ignored</strike>. `...`

**Comment by jensmaurer** [comment]
Uh, why? A cv-qualified class type is still a class type. For example, this works:

```
struct B {};
using CB = const B;
struct D : CB { };
```

**Comment by jabelloc** [comment]
But this doesn't work (at least clang, GCC and VS reject the code), as there is no way for the compiler to parse the `const`  below, given the C++ grammar.

```
struct B{};
struct D : const B {};
```

So, I presume that your snippet compiles because the `CB` in `struct D : CB {}` doesn't carry the `const` anymore. Although I still need to take a look into this in the Standard.

**Comment by jwakely** [comment]
No, it compiles because of [class.derived] p2, and it would stop working with your change.

**Comment by jwakely** [comment]
In other words, "any cv-qualifiers are ignored" in [class.derived] p2 is what causes "doesn't carry the `const` anymore" to be true, so don't try to remove those words!

**Comment by jabelloc** [comment]
@jwakely 

Could you tell me which grammar production would allow the compiler to parse the `const` in `struct D : const B{};` above?

**Comment by jabelloc** [comment]
@jwakely I can see what you mean now.

**Comment by jwakely** [comment]
I meant Jens's snippet when I said "it compiles", because that's the one that compiles. Yours doesn't compile.

In his example, the _class-or-decltype_ `CB` denotes a const-qualified class type. When used as a base class, any cv-qualifiers are ignored, so the base class is `B`. That's what [class.derived] p2 means. Changing [class.derived] p2 would break the example, and so is not only non-editorial, but completely wrong.

What part of this is confusing you?

**Comment by jabelloc** [comment]
As I said before I have already understood your point. But to avoid misunderstandings about this paragraph I would surely insert the Note below, as follows:

 A _class-or-decltype_ shall denote a (possibly cv-qualified) class type that is not an incompletely defined
class (11.4); any cv-qualifiers are ignored. [Note: the code below compiles
 
```
struct B {};
using CB = const B;
struct D : CB { };
```
-end note]  The class denoted by `...`

**Comment by jensmaurer** [comment]
Since "struct D: const B" is syntactically invalid, this is the only remaining choice, with no need for further elaboration. The standard is not a tutorial.
