### ISSUE TITLE
[chrono] Use nested namespace definitions in the library where applicable

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#4256]
For example, in [chrono.syn] we have:

```
inline namespace literals {
inline namespace chrono_literals {
  ...
}
}
```

(Note that `namespace inline literals::inline chrono_literals` is ill-formed: there's no way to collapse two levels of namespace where the outer level is inline.)

I wonder if it would be better to express [chrono.syn] as:

```
namespace std::chrono {
  ...
}
namespace std {
  ...
}
namespace std::chrono {
  ...
}
namespace std::inline literals::inline chrono_literals {
  ...
}
namespace std::chrono {
  using namespace literals::chrono_literals;
}
```

In addition to being more compact, this would mean we never have a (subtle) `}` appearing in the middle of the text switching us between namespaces. (In particular, the switch from `std::chrono` to `std` in the current synopsis is easy to miss, and an incautious reader might think that the inline namespace `literals` is in `std::chrono`, not in `std`.)

More generally, I think we should consider a policy that we never nest namespace definitions in the library clauses: names in namespace definitions should always be relative to the global namespace.

**Comment by tkoeppe** [comment]
I welcome the general policy. I've started to find nested namespaces rather confusing as we've started having deeper nesting. I've even considered whether we should start applying `}  // namespace std`-like close comments (as in some house styles) to aid orientation. The proposed policy alleviates this considerably.

**Comment by jensmaurer** [comment]
In [algorithms], we have a lot of
```
namespace std {
...
namespace ranges {
   ...
}
...
namespace ranges {
   ...
}
}

Closing namespace std in between would tear apart related non-ranges and ranges algorithms more than they deserve.

**Comment by tkoeppe** [comment]
Given the usefulness of the compactness in `<algorithms>`, I'd like to prosose the following:

Richard's proposal is useful where it improves clarity, and in those cases we should feel welcome to use that style. In the algorithms case, the proposal would not improve clarity, and we can retain the status quo.

Ultimately, the goal is not some arbitrary consistency with some useless rule, but to make a clear and understandable document. So above all be consistent with "looks good".

For now, we will only adjust `<chrono>` to use Richard's proposed style. Any further changes would require case-by-case analysis.
