### ISSUE TITLE
[floatfield.manip]/8 has not stood the test of time

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#4258]
This note is explaining why `hexfloat` uses a weird combination of flag values, but it's phrased as if justifying a change to the status quo, not as a historical description. It's not clear that this note is useful, but if we want to retain it, we should rephrase.

**Comment by tkoeppe** [comment]
It seems that having a well-constructed, durable note here would be friendly, since this is indeed an odd design, so some form of "*sic*!" marker would be nice.

**Comment by zygoloid** [comment]
[*Note 1*: If you find this surprising, you were paying attention. Good job! --*end note*]

**Comment by jensmaurer** [comment]
I don't understand the rationale offered here. "floatfield" could never be "hex" in C++2003. Maybe in some implementations, the numeric value of hex conflicted with scientific or fixed?

**Comment by Eelis** [comment]
Well, to make

    str.setf(ios_­base​::hex, ios_­base​::​floatfield);

do anything, `ios_base::hex` must have bits in common with `ios_base::floatfield`. But `ios_base::basefield` is defined as `dec|oct|hex`, so the result would be that `floatfield` and `basefield` would overlap, which seems bad.
