### ISSUE TITLE
CPOs inhibit guaranteed copy elision of arguments, are unimplementable as specified

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/draft#4264]
To take one example, [range.access.begin]/p2.5

> Otherwise, if [...] then `ranges::begin(E)` is _expression-equivalent_ to _`decay-copy`_`(begin(t))`

_Expression-equivalent_ is defined in [defns.expression-equivalent]:

> expressions that all have the same effects, either are all potentially-throwing (14.5) or are all not
> potentially throwing, and either are all constant subexpressions or are all not constant subexpressions.
> 
> [_Example:_ For a value `x` of type `int` and a function `f` that accepts integer arguments, the expressions
> `f(x +2)`, `f(2 + x)`, and `f(1 + x + 1)` are expression-equivalent. —_end example_]

But according to https://en.cppreference.com/w/cpp/language/copy_elision, only PRvalues are subject to guaranteed copy elision. So it is possible that in _`decay-copy`_`(begin(t))`, the elision of the copy of `t` is _required_, but for `ranges::begin(E)` copy elision _may_ happen, but it is not required.

Therefore, they are not _expression-equivalent_ expressions, as that term of power is currently specified.

**Comment by ericniebler** [comment]
attn @CaseyCarter

**Comment by jensmaurer** [comment]
This is the issue tracker for editorial issues around the C++ standard. I'm not seeing anything we could fix as an editorial issue here (i.e.without changing the meaning of the standard). Defects in the definition of "expression-equivalent" should be directed to LWG, it seems.

**Comment by ericniebler** [comment]
So sorry.
