### ISSUE TITLE
normative "Note A", "Note B", ...

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#4267]
A couple of the library tables have entries marked "Note A" etc. The corresponding text is normative, so shouldn't be named a "Note".

Also [container.requirements.general] uses both "(Note A)"  and "(Note B)" and then defines them both to mean the same thing.

**Comment by jensmaurer** [comment]
This will be addressed by #4460.

**Comment by frederick-vs-ja** [comment]
Probably fixed by #7033.

**Comment by tkoeppe** [comment]
Yes, thanks!
