### ISSUE TITLE
[locale.codecvt.virtuals]p2+ is missing a paragraph number

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#4281]
There's a paragraph break in [locale.codecvt.virtuals]p2. Unclear if the right fix is to join the paragraphs or add a new paragraph number. @jwakely, what's your preference?

**Comment by jwakely** [comment]
I agree it's unclear which is right. I think either choice is OK. #4284 adds the `\pnum` just to keep the paragraph break that has been there since C++98.
