### ISSUE TITLE
Paragraphs 2 and 6 of [basic.type.qualifier] appear to be in contradiction (emphases are mine)

### ISSUE THREAD

**Issue by jabelloc** [cplusplus/draft#4297]
[[basic.type.qualifier]/2](http://eel.is/c++draft/basic.type.qualifier#2):

> Except for array types, a compound type ([basic.compound]) is **not** cv-qualified by the cv-qualifiers (if any) of the types from which it is compounded.

[[basic.type.qualifier]/6](http://eel.is/c++draft/basic.type.qualifier#6):

> In this document, the notation _cv_ (or _cv1_, _cv2_, etc.) , used in the description of types, represents an arbitrary set of cv-qualifiers, i.e., one of `{const}`, `{volatile}`, `{const, volatile}`, or the empty set. For a type _cv_ `T`, the _top-level cv-qualifiers_ of that type are those denoted by _cv_.
> 
> [_Example 2:_ The type corresponding to the _type-id_ `const int&` has no top-level cv-qualifiers. **The type corresponding to the _type-id_ `volatile int * const` has the top-level cv-qualifier `const`. For a class type `C`, the type corresponding to the _type-id_ `void (C​::​* volatile)(int) const` has the top-level cv-qualifier `volatile`**. _— end example_]

Note : According to [[basic.compound]/(1.3)](http://eel.is/c++draft/basic.compound#1.3) and [(1.8)](http://eel.is/c++draft/basic.compound#1.8), both _pointers_ and _pointers to member_ are compound types.

**Comment by jwakely** [comment]
There is no contradiction. The first example in p6 is saying that the top-level qualifier on the compound type is `const`, it is not affected by the `volatile` qualifier on the type `volatile int`. The second example is saying that the top-level qualifier on the compound type is `volatile`, it is not affected by the `const` qualifier on the function type `void (int) const`. Both examples perfectly agree with p2.

**Comment by jabelloc** [comment]
Ok I see what you mean. But what does it mean a `volatile` pointer to a member function of type `void(int)`?

**Comment by jensmaurer** [comment]
Exactly that: a pointer-to-member is just some (special) data type, and that type can be volatile-qualified, as-if it were a volatile int.

**Comment by jwakely** [comment]
> But what does it mean a `volatile` pointer to a member function of type `void(int)`?

```cpp
using PMF = void (C::*)() const;
PMF pmf = &C::foo;
volatile PMF vol_pmf = pmf;
```

**Comment by jwakely** [comment]
I really think this kind of thing belongs on StackOverflow. Instead of telling us there's a flaw in the standard, you could ask on StackOverflow why the wording seems contradictory. This could be clarified there, and so could your follow-up question about what the volatile-qualified type means.

**Comment by jabelloc** [comment]
Well if that's what you prefer, definitely I'll stop posting issues here. Thanks for your kind attention. Good luck!

**Comment by jensmaurer** [comment]
"what does it mean"

The same what it means to have a volatile T for any other (scalar) T.
