### ISSUE TITLE
Inconsistent section naming for forward_list

### ISSUE THREAD

**Issue by dangelog** [cplusplus/draft#4302]
The sections that relate to `forward_list` have different spelling, with or without a dot in the name. (I was almost convinced that `forward_list` didn't have uniform container erasure...)

Could it be possible to unify the spelling?

With:
* [forward.list.syn]
* [forward.list.erasure]

Without:
* [forwardlist]
* [forwardlist.overview]
* [forwardlist.cons]
* [forwardlist.iter]
* [forwardlist.access]
* [forwardlist.modifiers]
* [forwardlist.ops]

**Comment by jensmaurer** [comment]
In my view, it would be good to rename everything to [forward.list.something], i.e. add a period.

**Comment by jensmaurer** [comment]
Editorial meeting 2021-04-30: Change everything to forward.list.xxx.

**Comment by dangelog** [comment]
Thank you.
