### ISSUE TITLE
[cpp.subst]/4 Isn't the macro execution example wrong?

### ISSUE THREAD

**Issue by onihusube** [cplusplus/draft#4317]
- [15.6.2 Argument substitution [cpp.subst]/4 - eel.is](http://eel.is/c++draft/cpp#subst-example-3)

Here is an example of H3.

```cpp
#define H3(X, ...) #__VA_OPT__(X##X X##X)
H3(, 0)             // replaced by ""
```

On the other hand, just below that is:
> Each # preprocessing token in the replacement list for a function-like macro shall be followed by a parameter as the next preprocessing token in the replacement list.

This is inconsistent and I think the code example is wrong, but what about?

When I run it, it seems to reject everything except clang.

- [CompilerExplorer](https://godbolt.org/z/P9aEY3)

**Comment by jensmaurer** [comment]
[cpp.subst] p4

> A _va-opt-replacement_ is treated as if it were a parameter...

**Comment by onihusube** [comment]
I overlooked it, thank you...
