### ISSUE TITLE
could and might

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#4319]
ISO wants us to avoid "could" and "might" appearing anywhere in the document. TODO list:

- [x] Front matter + Clauses 1, 2, 3 -- no changes
- [x] 4 General principles[intro] -- no changes
- [x] 5 Lexical conventions[lex] -- jmaurer
- [x] 6 Basics[basic] -- jmaurer
- [x] 7 Expressions[expr] -- jmaurer
- [x] 8 Statements[stmt.stmt] -- jmaurer
- [x] 9 Declarations[dcl.dcl] -- jmaurer
- [x] 10 Modules[module] -- no changes
- [x] 11 Classes[class] -- jmaurer
- [x] 12 Overloading[over] -- jmaurer
- [x] 13 Templates[temp] -- jmaurer
- [x] 14 Exception handling[except] -- jmaurer
- [x] 15 Preprocessing directives[cpp] -- jmaurer
- [x] 16 Library introduction[library] -- jmaurer
- [x] 17 Language support library[support] -- jmaurer
- [x] 18 Concepts library[concepts] -- jmaurer
- [x] 19 Diagnostics library[diagnostics] -- jmaurer
- [x] 20 General utilities library[utilities] -- jmaurer
- [x] 21 Strings library[strings] -- jmaurer
- [x] 22 Containers library[containers] -- jmaurer
- [x] 23 Iterators library[iterators] -- jmaurer
- [x] 24 Ranges library[ranges] -- jmaurer
- [x] 25 Algorithms library[algorithms] -- jmaurer
- [x] 26 Numerics library[numerics] -- jmaurer
- [x] 27 Time library[time] -- jmaurer
- [x] 28 Localization library[localization] -- jmaurer
- [x] 29 Input/output library[input.output] -- jmaurer
- [x] 30 Regular expressions library[re] -- jmaurer
- [x] 31 Atomic operations library[atomics] -- jmaurer
- [x] 32 Thread support library[thread] -- jmaurer
- [x] Annex A (informative) Grammar summary[gram] -- no changes
- [x] Annex B (informative normative) Implementation quantities[implimits] -- no changes
- [x] Annex C (informative) Compatibility[diff] -- jmaurer
- [x] Annex D (normative) Compatibility features -- jmaurer
- [x] Back matter -- no changes

Please add your name next to a section to claim it, and check the box when it's done.

**Comment by johelegp** [comment]
Consider following @jensmaurer approach of using "possible" to replace "might", as shown in #4334, to maintain consistency.

**Comment by jwakely** [comment]
Some of the "it is possible" rephrasing feel awkward when involving a negation. For example, ["It is possible for `f` not to be called at all,"](https://github.com/cplusplus/draft/pull/4349/files#diff-104905fbf448e1727d95ca27b3bc2acf200676a579a9b9d5b819d4365a67c69fR7195).

Similarly "It is possible for line \#1 not to result in concurrency" later in the same pull request.

I don't have better suggestions for those ones right now.

**Comment by tkoeppe** [comment]
Do let us keep those awkward fixes in a separate pile, for C++20 only, and we'll revisit those later.

**Comment by jensmaurer** [comment]
C++20 has shipped.
