### ISSUE TITLE
Consistent (and conventional) spelling of `struct tm`

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#4338]
Conventionally, when C++ declares or defines a struct type, such as `struct timespec;`, it refers to that type by name without the `struct` tag when used.

However, `struct tm` appears to be something of a special case.  As this type is supplied by the C library, and appears in mostly C specified APIs, the `struct` tag (required by C compilers) has been preserved in much of our wording and library synopses.  However, the `<locale>` header is an exception, consistently referring to just `tm*` in the functions it declares.

We should be consistent in how we reference this type in C++ source, and make an active decision to either follow the C++ convention of not repeating the `struct` tag on each use, or whether we prefer to follow the C convention of requiring the `struct` tag in each case.

**Comment by AlisdairM** [comment]
Note that I deliberately used `timespec` as my counterexample, as it comes from the same header and we follow the C++ conventions in this case, although it has distinctly fewer usages to establish a pattern.

**Comment by jensmaurer** [comment]
Note that this approaches "struct stat" territory (although "stat" is POSIX, not C), and we would definitely want the "struct" in front for "stat".

**Comment by jensmaurer** [comment]
Editorial meeting: Drop "struct" in front of "tm" to avoid (the impression of) accidental introduction of the name in the immediately-enclosing namespace.

**Comment by jensmaurer** [comment]
We have declarations of "struct tm" in header synopses `<cwchar>` and `<ctime>`, showing that "struct tm" is a member of namespace `std`. That's probably not exactly great, but also likely a LWG-level larger wording issue.

**Comment by tkoeppe** [comment]
I don't think we spotted this detail when we reviewed P0175. Prior to that, we didn't have the synopses at all and just refered to C, so at this point I would simply consider this something unclear that we never discussed.
