### ISSUE TITLE
Table 9 is missing `decltype(auto)`

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#436]
Table 9 ("_simple-type-specifiers_ and the types they specify") describes how _simple-type-specifiers_ are mapped into types, but it is missing an entry for `decltype(auto)`. Presumably this should say something like "placeholder for the type of the initializer (7.1.6.4)".

We also have a conflict between 7.1.6.2/2 and 7.1.6.4/1. The former says that only `auto` is "a placeholder for a type to be deduced", whereas the latter says that both "are used to designate a placeholder type that will be replaced later by deduction from an initializer". `decltype(auto)` does not perform deduction, so this seems wrong.

One possible, but broader, change:

1) Change 7.1.6.2/4 to define "the _declared type_ of an expression `e`" instead of "the type denoted by `decltype(e)`".
2) Change Table 9 to specify that `decltype(e)` gives "the declared type of `e`".
3) Extend Table 9 to specify that `decltype(auto)` gives "the declared type of the initializer, as described in 7.1.6.4".
4) Fix up 7.1.6.4 to match.

**Comment by jensmaurer** [comment]
We're consistently using "deduced" for decltype(auto), e.g. 7.1.7.4.1p5. All that's really missing is an entry in the table.
