### ISSUE TITLE
Consider using less excessively large source files

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#4369]
utilities.tex is 21K LOC. Source files this large cause some problems on github:
- when you browse to [utilities.tex](https://github.com/cplusplus/draft/blob/6c12819b6a5bd270bfb901726f73d4d147d16a5a/source/utilities.tex), the last 4 thousand lines are silently dropped
- when you make an issue whose description includes a reference to a line near the end of an extremely big source file, github doesn't turn it into a code citation as it normally does.

**Comment by jensmaurer** [comment]
See #3388

**Comment by jensmaurer** [comment]
The restructuring in #3388 has moved > 8k LOC to other files. Recent additions (e.g. std::format) have ballooned utilities.tex to 19k LOC again, but at least there's an improvement.

Closing for now.
