### ISSUE TITLE
Always use \libconcept, even in synopsis and itemdecls

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#4383]
There are several remaining unmarked libconcepts, particularly in ranges.tex. They should be marked so that they can be indexed.  This is a continuation of Jens first pass at this in 4f255cae.

**Comment by jwakely** [comment]
I find it much harder to read the LaTeX with `\libconcept` on every concept, and so harder to review changes like http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2236r0.html#3406

**Comment by jensmaurer** [comment]
Editorial meeting: The consistent policy is "always use \libconcept in synopses and itemdecls". ranges.tex was much improved via #4456.
