### ISSUE TITLE
Footnote marks should appear after punctuation

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#4400]
If a footnote is meant to attach to a word immediately before a punctuation (full stop, comma, etc.), the footnote mark should appear _after_ the punctuation, for visual spacing reasons.

Bad: `foo bar\begin{footnote} ... \end{footnote}.`

Good: `foo bar.\begin{footnote} ... \end{footnote}`

Action items:
* update the wiki
* fix the few cases that violate this (findable with `git grep`)
* [stretch goal] Add a check.

**Comment by jensmaurer** [comment]
I've updated the wiki page, too.
