### ISSUE TITLE
Replace "typedef name" with <grammar>typedef-name</>

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#4401]
On a few occasions, we say "typedef name", which is never defined. Reflector discussion suggests that this is potential holdover from C, which infers English names from grammar names, but we don't do this in C++.

Resolution: replace "typedef name" with _typedef-name_ everywhere.

**Comment by jensmaurer** [comment]
(This has lots of conflicts with Davis' paper, so this needs to wait a little.)

**Comment by jensmaurer** [comment]
@tkoeppe , do you want to similarly replace in "typedef name for linkage purposes", which is a stand-alone defined term?

**Comment by tkoeppe** [comment]
Is "typedef name for linkage purposes" actually defined? I couldn't find the definition, just circular references. (It's also not indexed.)

It looks like "<general> name for linkage purposes" is the defined term, and then "typedef name" is just an application of that -- in which case it suffers form the same problem as reported here. (If instead the whole phrase were a defined term, I'd be happy to keep it and use it.)

**Comment by jensmaurer** [comment]
dcl.typedef p4

> If the typedef declaration defines an unnamed class or enumeration, the first typedef-name declared by the declaration to be that type is used to denote the type for linkage purposes only (6.6).

Is very close to a definition.

**Comment by tkoeppe** [comment]
Hm, that just sounds like a definition that fills in "typedef-name" into "{general} name for linkage purposes", so that would suggest that we should say "_typedef-name_ for linkage purposes" everywhere. Otherwise we should add something to that paragraph like, "which is called the _typedef name for linkage purposes_ [index]" (but that seems uncalled for).

**Comment by jensmaurer** [comment]
I've made a suggestion for a proper definition in the linked pull request.
