### ISSUE TITLE
Example in 3.2/6 (6.6) is obsolete

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/draft#441]
In N4296 subclause 3.2 [basic.def.odr] paragraph 6, the example under 6.6 was rendered obsolete by the resolution to Core Issue 1344.

**Comment by zygoloid** [comment]
Hmm, is the normative rule itself also obsolete?

**Comment by hubert-reinterpretcast** [comment]
I haven't discovered any case where the normative rule itself prevents anything that cannot be interpreted as a violation of the ODR (less the rule in question) or some other "ill-formed, no diagnostic required" rule having to do with templates. I will send a note on the Core reflector.

**Comment by zygoloid** [comment]
This is http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2085

**Comment by jensmaurer** [comment]
This issue is covered by CWG 2085.
