### ISSUE TITLE
Confusing wording in note on [basic.start.dynamic]/1

### ISSUE THREAD

**Issue by RedBeard0531** [cplusplus/draft#4420]
> An explicitly specialized non-inline static data member or variable template specialization has ordered initialization.

Since English lacks a grouping operator it is unclear which adjectives apply to both sides of the "or". I initially read it as `An (explicitly specialized non-inline static data member) or (variable template specialization)`, but I think it is supposed to be closer to `An explicitly specialized non-inline (static data member or variable template specialization)`. Can this be rephrased to make this clear?

**Comment by jwakely** [comment]
Maybe:

> A non-inline static data member or variable template specialization has ordered initialization if it is explicitly specialized.

**Comment by jensmaurer** [comment]
What about:
> An explicit specialization of a non-inline static data member or of a variable template has ordered initialization.

**Comment by jwakely** [comment]
Is it the explicit specialization that has ordered init, or the variable itself? Is there any difference?

Your suggestion says the specialization has ordered init. The original says the variable has ordered init.

**Comment by jensmaurer** [comment]
A template is not a thing that could be initialized (it's not an object or reference; it's a template). Only a specialization of a (certain kind of) template can be initialized.

**Comment by jensmaurer** [comment]
Editorial meeting:
Suggestion: "A non-inline explicit specialization of a templated variable has ordered initialization."
Have CWG review.
