### ISSUE TITLE
[range.split.view] Make require-constant a function

### ISSUE THREAD

**Issue by johelegp** [cplusplus/draft#4423]
This implementation results in a single instantiation per type, rather than one specialization per value (do compilers cache these when the template's not defined?)

```diff
-  template<auto> struct require-constant;       // exposition only
+  consteval void require-constant(auto) {}      // exposition only

   template<class R>
   concept tiny-range =                          // exposition only
     sized_range<R> &&
-    requires { typename require-constant<remove_reference_t<R>::size()>; } &&
+    requires { require-constant(remove_reference_t<R>::size()); } &&
     (remove_reference_t<R>::size() <= 1);
```
or (lambdas are not SCARY, are they?)
```diff
-  template<auto> struct require-constant;       // exposition only
-
   template<class R>
   concept tiny-range =                          // exposition only
     sized_range<R> &&
-    requires { typename require-constant<remove_reference_t<R>::size()>; } &&
+    requires { [](auto) consteval {}(remove_reference_t<R>::size()); } &&
     (remove_reference_t<R>::size() <= 1);
```
See https://godbolt.org/z/svc9Gx.

**Comment by timsong-cpp** [comment]
I don't understand the point in trying to optimize the compile time of the definition of an exposition-only concept like this. The exact definition is not observable; the implementers are free to optimize it already.

In any event, I don't think this is correct. Expressions in a _requires-expression_ are not potentially-evaluated, so the consteval doesn't do anything.

**Comment by johelegp** [comment]
> I don't understand the point in trying to optimize the compile time of the definition of an exposition-only concept like this. The exact definition is not observable; the implementers are free to optimize it already.

Definitely. I thought I'd make this more visible. And also get experts to tell me whether my variation of _`require-constant`_ in my code is actually well-formed. :)

> In any event, I don't think this is correct. Expressions in a _requires-expression_ are not potentially-evaluated, so the consteval doesn't do anything.

Well, maybe I found a bug in these compilers that pass the tests.

**Comment by timsong-cpp** [comment]
That test isn't testing whether `T::size()` is a constant. You are testing whether it is well-formed.

**Comment by johelegp** [comment]
> That test isn't testing whether `T::size()` is a constant. You are testing whether it is well-formed.

This sounds very familiar. I must have repeated this mistake. Thank you, that makes sense.
