### ISSUE TITLE
[range.range] Redundant paragraph about expression variations LWG3915

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#4431]
Expression variations kick in for "an expression that is non-modifying for some constant lvalue operand", but `std::ranges::range`'s is an non-constant lvalue, so [p2](http://eel.is/c++draft/range.range#2) is redundant.

**Comment by johelegp** [comment]
I suppose that the change that clarified the template parameters' cv-qualification for purposes of equality-preservation and requiring additional variations happened concurrently with the change of `std::ranges::range`'s operand from a forwarding reference to a non-constant lvalue reference.

**Comment by jensmaurer** [comment]
@jwakely , do you feel we can editorially remove p2, or should this get LWG review?

**Comment by JohelEGP** [comment]
Requested for an issue to be opened.

**Comment by Dani-Hub** [comment]
@JohelEGP A new library has been created, see [LWG 3915](https://cplusplus.github.io/LWG/issue3915).

**Comment by JohelEGP** [comment]
> Status: [WP](https://cplusplus.github.io/LWG/lwg-active.html#WP)
