### ISSUE TITLE
"conversion operator" denotes functions or operators?

### ISSUE THREAD

**Issue by potswa** [cplusplus/draft#444]
[vector.bool] §23.3.7/4 refers to `std::vector<bool>::reference::operator bool` as a conversion operator, whereas it's a conversion function. The index indicates that "conversion operator" is the same as "conversion, user-defined." However [expr.cast] §5.4/2 uses the term to refer to static_cast, const_cast, dynamic_cast and reinterpret_cast, which seems more appropriate.

**Comment by jensmaurer** [comment]
"conversion operator" should not be a defined term in the standard; the use in 5.4 is assumed to be descriptive English text.
