### ISSUE TITLE
"lvalue reference" vs "lvalue-reference"

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#446]
Marshall pointed out the standard is inconsistent about "lvalue reference" vs "lvalue-reference"

**Comment by cpplearner** [comment]
It seems that in most cases the standard uses "lvalue reference" and "rvalue reference" (with no hyphen). Only [unique.ptr] and [func.require] spell them as "lvalue-reference" and "rvalue-reference" (with a hyphen in the middle).
