### ISSUE TITLE
Add examples to [basic.lookup.unqual]/5

### ISSUE THREAD

**Issue by BRevzin** [cplusplus/draft#4463]
Arthur O'Dwyer posted the following examples to the reflector:

* https://godbolt.org/z/MhvnGn (gcc and icc do one thing, clang and msvc do another)
* https://godbolt.org/z/G5TvWf (all four do something different)

Would be really helpful to add some version of these examples to that clause to make it clear what the rule is.

**Comment by jensmaurer** [comment]
@opensdh , could you please check these examples?

I think for the first example, we look in A first and find T=int.
Same for the second example, we get U=U1 and T=T1.

If you agree, I'll turn this into examples for [basic.lookup.unqual] p5.

**Comment by opensdh** [comment]
> I think for the first example, we look in A first and find T=int.

Yes, and this is true even if `A` is a dependent type.

> Same for the second example, we get U=U1 and T=T1.

Yes, both of those are relevant component names ([basic.lookup.unqual]/5 explicitly names "*type-specifier* or *ptr-operator*").  Note in that example that

```cpp
    operator T1::U() { return {1}; }
    operator T2::U() { return {2}; }
```

are irrelevant.

> If you agree, I'll turn this into examples for [basic.lookup.unqual] p5.

Thanks!
