### ISSUE TITLE
[defns.well.formed] Current definition of "well-formed" might be imprecise

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#4467]
Currently the definition of "well-defined" just covers "the one-definition rule". However, there are many other cases that a program is ill-formed, no diagnostic required without violation of the ODR (e.g. instantiating a template when its associate constraints are satisfied but the corresponding standard concepts are not modeled).
Should we improve the wording?

**Comment by jensmaurer** [comment]
Yes, there seems to be room for improvement.

Maybe just "... and semantic rules where a diagnostic is not required"

**Comment by jensmaurer** [comment]
Editorial meeting:
Suggestion: "C++ program constructed according to the syntax and semantic rules"
Have CWG review it.
