### ISSUE TITLE
Incorrect(?) italics in [class.mfct.non-static]/4

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#447]
Why are only the words _const_ and _volatile_ and _const volatile_ in italics in paragraph 4?

Should it be "_const member function_" rather than "_const_ member function" ?

(Then in the example in that paragraph then talks about a `const` member function in code font.)

**Comment by cpplearner** [comment]
Also note that [class.mfct.non-static]/1 has "*non-static* member function". In addition, there are "*static* member function", "*non-static* member function" and "*inline* member function" in [class.mfct].

**Comment by zygoloid** [comment]
We are defining the entire phrase "const member function", so the entire phrase should be italicized.
