### ISSUE TITLE
[dcl.init.general] p5 wording does not seem to match the intent

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#4478]
[\[dcl.init.general\]/5](http://eel.is/c++draft/dcl.init.general#5):

> A declaration of a block variable with linkage that has an *initializer* is ill-formed.

IIUC the intent is to prohibit

```c++
void f() {
    extern int x = 1;
}
```

But it seems that the variable `x` is not a [block variable](http://eel.is/c++draft/basic.scope.block#def:block_variable), because it does not [belong](http://eel.is/c++draft/basic.scope.scope#def:entity,belong) to the block scope, because the target scope of its declaration is the innermost enclosing namespace scope ([\[dcl.meaning.general\]/(3.5)](http://eel.is/c++draft/dcl.meaning.general#3.5)).

I think this sentence should instead talk about the *immediate scope* of the declaration.

cc @opensdh

**Comment by jensmaurer** [comment]
Maybe:

> A declaration of a variable with linkage that has an /initializer/ shall not inhabit a block scope.

**Comment by opensdh** [comment]
Right; "block-scope variable" &rarr; "block variable" seemed trivially correct when we disentangled block/local variables, but of course the old terminology was imprecise and required interpretation!  Oops.
