### ISSUE TITLE
[temp.expl.spec] Should "declared before" be replaced by "reachable"?

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#4479]
[\[temp.expl.spec\]/7](http://eel.is/c++draft/temp.expl.spec#7.sentence-1), emphasis mine:

> If a template, a member template or a member of a class template is explicitly specialized then that specialization shall be **declared before** the first use of that specialization that would cause an implicit instantiation to take place, in every translation unit in which such a use occurs; no diagnostic is required.

Now that we have modules, this sentence should probably say "... then a declaration of that specialization shall be reachable from ..." instead.

Note that [P1787R6: Declarations and where to find them](https://github.com/cplusplus/draft/commit/c7e8927098ab5074491edb64cbb4e1258c0c2141#diff-993d162d99c97390cfd9b2c9b076a5ef904d9e48366aa8bbbe7663cfc8367588L3195-R3145) updated a similar sentence in [\[temp.spec.partial.general\]](http://eel.is/c++draft/temp.spec.partial.general#1.sentence-3), but neglected this one.

**Comment by jensmaurer** [comment]
@opensdh, any insight here?

**Comment by opensdh** [comment]
I don't have anything to add here: it does appear to be a place I simply missed when trying to audit all uses of words like "declared before".
