### ISSUE TITLE
[basic.def.odr] What does `D` refer to in p14?

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#4498]
[\[basic.def.odr\]/14](http://eel.is/c++draft/basic.def.odr#14):

> If `D` is a template and is defined in more than one translation unit, then the preceding requirements shall apply both to names from the template's enclosing scope used in the template definition, and also to dependent names at the point of instantiation ([temp.dep]). These requirements also apply to corresponding entities defined within each definition of `D` (including the closure types of lambda-expressions, but excluding entities defined within default arguments or default template arguments of either `D` or an entity not defined within `D`). For each such entity and for `D` itself, the behavior is as if there is a single entity with a single definition, including in the application of these requirements to other entities.

It's clear that in the first sentence, `D` must be a template. But do the second and third sentences (starting from "These requirements") apply when `D` is not a template?

**Comment by jensmaurer** [comment]
Yes.

**Comment by languagelawyer** [comment]
Then it is unclear why it [was moved](https://github.com/cplusplus/draft/commit/d9c94bddc06e944baeb17f4b4cd8a0fd4254db67#diff-496151aa14703466fa29b067d1498c86d5bd37c1c9a3f169569974a83cce021bR668-R669) to its own paragraph instead of becoming another list item:

- If D is a class with an implicitly-declared constructor...
- If D is a class with a defaulted three-way comparison operator function...
- If D is a template and is defined in more than one translation unit...

**Comment by jensmaurer** [comment]
The commit you referenced didn't move the "If D is a template" outside of the bullets.

Historically, maybe it was felt that references to "these requirements" (meaning the bulleted list) should be outside of the bulleted list. We're already inconsistent with the use of default arguments, though, so moving at least the "If template" part into the bullets (and maybe some of the other stuff) would clarify.

**Comment by tkoeppe** [comment]
@zygoloid: This is subtle, would you perhaps have a suggestion?

**Comment by tkoeppe** [comment]
Suggestion: merge p15 into the previous paragraph as a bullet, but check with @zygoloid.

**Comment by tkoeppe** [comment]
Proposal from @zygoloid in #6272
