### ISSUE TITLE
[2021-02 LWG Motion 7] P1682R2 std::to_underlying for enumeration

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#4512]
[P1682R2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1682r2.html)

**Comment by jensmaurer** [comment]
Successor: [P1682R3](https://wg21.link/p1682r3)

**Comment by jwakely** [comment]
> Successor: [P1682R3](https://wg21.link/p1682r3)

For the record, the LWG motion _should_ have been for the R3 revision, but I screwed up. But the only differences between R2 and R3 are editorial anyway. The changes merged by #4526 incorporate those editorial fixes.
