### ISSUE TITLE
[unique.ptr.runtime.ctor]/2.2 needs monospace

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#454]
N4296 20.8.1.3.1 [unique.ptr.runtime.ctor]/2.2 should say `element_type*` in monospace.

**Comment by AlisdairM** [comment]
The clause number after Jacksonville extended the library is 20.10.1.3.1, and this issue looks resolved and should be closed?  I compared n4582 with n4527 to confirm.

**Comment by StephanTLavavej** [comment]
Yep, this was fixed by 820981d on Feb 6. Looks like I can close this, as the submitter.
