### ISSUE TITLE
[common.iter.nav] Bad concept index entry

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#4544]
The `\newline{}` on this line:

https://github.com/cplusplus/draft/blob/f8ac034ab30648da8e74427bdf6a8429ff6bf3fc/source/iterators.tex#L5007

results in this bad entry in the concept index:

![image](https://user-images.githubusercontent.com/22357/110586581-bbaf1300-8172-11eb-9b28-d7580ad355a5.png)

**Comment by jwakely** [comment]
Maybe we should use `\libconceptx{constructible_\newline{}from}{constructible_from}` instead.

**Comment by tkoeppe** [comment]
Sounds good. @jwakely: if you have a moment and that works, feel free to push that fix.
