### ISSUE TITLE
[except.ctor] stack unwinding vs. automatic storage duration

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4548]
In section [except.ctor], the rule states: 
>1. As control passes from the point where an exception is thrown to a handler, objects with **automatic storage duration** are destroyed by a process, specified in this subclause, called stack unwinding.    

>3. If the initialization or destruction of an object other than by delegating constructor is terminated by an exception, the destructor is invoked for each of the object's direct subobjects and, for a complete object, virtual base class subobjects, whose initialization has completed ([dcl.init]) and whose destructor has not yet begun execution, except that in the case of destruction, the variant members of a union-like class are not destroyed. [ Note: If such an object has a reference member that extends the lifetime of a temporary object, this ends the lifetime of the reference member, so the lifetime of the temporary object is effectively not extended. — end note ] The subobjects are destroyed in the reverse order of the completion of their construction. Such destruction is sequenced before entering a handler of the function-try-block of the constructor or destructor, if any.  

That means what the third rule says is also a part process of stack unwinding.  

Since the first rule sounds like that the invocation of **stack unwinding** is only for the object with **automatic storage duration**. Doesn't that stack unwinding invoke for the object with dynamic storage duration or others duration? 
````cpp
struct A{
  ~A(){
    
  }
};
struct B{
 B(){
   throw 0;
 }
  A a;
};
int main(){
   try{  
      auto ptr = new B{};
    }catch(int){
   }
}
````
Obviously, the subobject `a` occupies the storage within the complete object of the type `B` which has the **dynamic storage duration**. AFAIK, A's destructor should be invoked since it has been completely constructed in the initialization of B.

**Comment by jensmaurer** [comment]
I think we can just strike "with automatic storage duration"; this is an intro sentence that doesn't really say much normatively. The detailed specification is in the following paragraphs.

**Comment by xmh0511** [comment]
> I think we can just strike "with automatic storage duration"; this is an intro sentence that doesn't really say much normatively. The detailed specification is in the following paragraphs.

Since [CWG 1774](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1774) is approved that destruction of subjects should be considered as **stack unwinding**, the introduction of **stack unwinding** through associating with objects that have automatic storage duration is a bit of contradiction.

**Comment by jensmaurer** [comment]
CWG 1774 wanted to clean up the entire section, but what we have in the working draft right now doesn't look at all like what was approved for CWG 1774.

The "with automatic storage duration" was re-introduced by commit f3a6b2e671efdee5bacb74a5ea01d4bfb1900d3e for [CWG 2256](https://wg21.link/cwg2256).

**Comment by tkoeppe** [comment]
OK, I trust your judgement on this.
