### ISSUE TITLE
Buggy footnote in [type.descriptions.general]

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#455]
Footnote 165 in [type.descriptions.general] says

> 165) Examples from 17.6.3 include: `EqualityComparable`, `LessThanComparable`, `CopyConstructible`. Examples from 24.2 include: `InputIterator`, `ForwardIterator`, `Function`, `Predicate`.

But 24.2 [iterator.requirements] says nothing about `Function` or `Predicate`. The latter is described in 25.1 [algorithms.general]; the former isn't defined at all in the standard.

**Comment by AlisdairM** [comment]
Just stumbled over the same issue researching the specification of 'Predicate'.  Would the best solution be to find a wording that does not make specific cross-references?

**Comment by jensmaurer** [comment]
I'm doing the isolated fix here. This is a footnote giving a list of examples, so there is no need to be exhaustive here.
