### ISSUE TITLE
Clarify the terminology of the non-local variable

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4552]
The phrase "non-local variable" is referred to in many sections, especially in [basic.start.dynamic]. However, the whole standard does not introduce a term definition for such a wording. Presumably, `local entity`  is not used to cover the opposite of non-local.  Should that define it to **the variable which does not belong to a block or function parameter scope**?

**Comment by jensmaurer** [comment]
The latest draft uses "block variable" and, correspondingly, "non-block variable". "non-local" doesn't appear in those contexts anymore.
