### ISSUE TITLE
[alg.is.permutation]/6

### ISSUE THREAD

**Issue by sim9108** [cplusplus/draft#4554]
ranges::equal(first1, last1, pfirst, plast, pred, proj1, proj2)  
=> 
  ranges::equal(first1, last1, first2, last2, pred, proj1, proj2)

**Comment by jwakely** [comment]
No, I don't think that would be correct. The point is that we're not requiring `[first1,last1)` and `[first2,last2)` to compare equal, we're requiring `[first1,last1)` and _some permutation of_ `[first2,last2)` to compare equal. That permutation of `[first2.last2)` is what the range `[pfirst,plast)` denotes.
