### ISSUE TITLE
Several issues about section [except.spec] 

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4561]
### Misusing of the wording "potentially-throwing" in these cases 
> any of the following constructs is **potentially-throwing**
>> a constructor selected by overload resolution in the implicit definition of the constructor for class X to initialize a potentially constructed subobject  

> any of the destructors for any of its potentially constructed subobjects is **potentially-throwing** or the destructor is virtual and the destructor of any virtual base class is **potentially-throwing**.  

> E implicitly invokes a function (...) that is potentially-throwing 

AFAIK, the property "potentially-throwing" ascribes to an expression. That is, we may say an expression is potentially-throwing or not. However, we cannot say a constructor, destructor, or function is potentially-throwing. Maybe, we should say such an entity has the **potentially-throwing exception specification**  

The statement for implicitly-declared assignment operator indicates this point  
>  if the **invocation** of any assignment operator in the implicit definition is potentially-throwing.  

So, for the first three bullets. Should we say that the **invocation** of the destructor, constructor, or function is potentially-throwing? Or, another way, such a constructor, destructor, or function has the potentially-throwing exception specification? That may make sense.  

### The redundant bullet of defining "potentially-throwing"  
> An expression E is potentially-throwing if 
>> - E implicitly invokes a function(...) that is potentially-throwing 
>> - any of the immediate subexpressions of E is potentially-throwing

In this case, Isn't that the last bullet can cover the former, as per   
> The immediate subexpressions of an expression E are 
>> - any function call that E implicitly invokes    

### The exception of a declaration that does not have a  noexcept-specifier   
> unless it is a destructor or a deallocation function or is defaulted on its first declaration, in which cases the exception specification is as specified below 

As specified below, the relevant rules do not only cover the case for `defaulted on its first declaration` but also cover the case for **implicitly-declared**. So, in order to be consistent, I think the introduction in this sentence should add the case for implicitly-declared into its exception cases.

**Comment by jensmaurer** [comment]
> redundant bullet of defining "potentially-throwing"

The problem is that p6.1 talks about the postfix-expression of a function call, but for an implicit invocation of a function, there is no corresponding explicit source code that would match the grammar for postfix-expression.

> implicitly-declared functions

The sentence starts with

> If a declaration of a function does not have a noexcept-specifier ...

An implicitly-declared function does not have a declaration, so this sentence does not apply at all.

**Comment by xmh0511** [comment]
> > redundant bullet of defining "potentially-throwing"
> 
> The problem is that p6.1 talks about the postfix-expression of a function call, but for an implicit invocation of a function, there is no corresponding explicit source code that would match the grammar for postfix-expression.
> 
> > implicitly-declared functions
> 
> The sentence starts with
> 
> > If a declaration of a function does not have a noexcept-specifier ...
> 
> An implicitly-declared function does not have a declaration, so this sentence does not apply at all.

Well. So, the remaining issue is the first issue. function, constructor, or destructor cannot be said that they are potentially-throwing since they're not expressions.
