### ISSUE TITLE
[expr.type.conv] doesn't define T() for T ≠ void

### ISSUE THREAD

**Issue by aaronpuchert** [cplusplus/draft#4566]
Let's go through the second paragraph point by point:

1. "If the initializer is a parenthesized single expression, the type conversion expression is equivalent to the corresponding cast expression." This is defining T(_initializer-clause_) as equivalent to a C-style cast.
2. "Otherwise, if the type is cv `void` and the initializer is `()` or `{}` (after pack expansion, if any), the expression is a prvalue of type void that performs no initialization." That is defining `void()`.
3. "Otherwise, the expression is a prvalue of the specified type whose result object is direct-initialized with the initializer." This seems to define T(_expression-list_) and T _braced-init-list_, so it defines `T{}` but not `T()` because an _expression-list_, unless I'm misreading something, cannot be empty.

What seems to be missing is that `T()` does a value initialization.

**Comment by jwakely** [comment]
Because `T()` for non-void types is not a conversion and is defined elsewhere.

**Comment by aaronpuchert** [comment]
Paragraph 1 seems to include `T()`: "A _simple-type-specifier_ or _typename-specifier_ followed by a parenthesized optional _expression-list_ or by a _braced-init-list_ (the initializer) constructs a value of the specified type given the initializer."

**Comment by johelegp** [comment]
> Paragraph 1 seems to include `T()`: "A _simple-type-specifier_ or _typename-specifier_ followed by a parenthesized optional _expression-list_ or by a _braced-init-list_ (the initializer) constructs a value of the specified type given the initializer."

This has been raised before. Not sure if in another issue, a CWG issue, or perhaps an r/cpp comment.

**Comment by xmh0511** [comment]
> Paragraph 1 seems to include `T()`: "A _simple-type-specifier_ or _typename-specifier_ followed by a parenthesized optional _expression-list_ or by a _braced-init-list_ (the initializer) constructs a value of the specified type given the initializer."

I think it's not true. The grammar of `expression-list` indicates that it shall contain at least one `initializer-clause`, hence `T()` where there's no `expression-list` in the parenthesis is not included by this rule.

**Comment by xmh0511** [comment]
> Paragraph 1 seems to include `T()`: "A _simple-type-specifier_ or _typename-specifier_ followed by a parenthesized optional _expression-list_ or by a _braced-init-list_ (the initializer) constructs a value of the specified type given the initializer."

Isn't that "Otherwise, the expression is a prvalue of the specified type whose result object is direct-initialized with the initializer. If the initializer is a parenthesized optional expression-list, the specified type shall not be an array type." not covers such a case?

**Comment by zygoloid** [comment]
> Isn't that [...] covers such a case?

Yes, I think so. For example, for `int()`, we say the expression is a prvalue of type `int` whose result object is direct-initialized with the initializer `()`. Then [dcl.init.general]/15.4 says that means we perform value-initialization. (Also, [dcl.init.general]/14.4 agrees that this form of initialization is direct-initialization, even though we don't hit the [dcl.init.general]/14.1 case of a parenthesized *expression-list*.)

I don't see a problem here.

**Comment by aaronpuchert** [comment]
> For example, for `int()`, we say the expression is a prvalue of type `int` whose result object is direct-initialized with the initializer `()`. Then [dcl.init.general]/15.4 says that means we perform value-initialization.

Thanks for the hint, [dcl.init.general]/15.4 is what I've been looking for.
