### ISSUE TITLE
The non-normative wording "local variable" should not survive in [basic.stc.static]

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4567]
Since the "non-local variable " has been completely excised after P1787. However, there's still a similar wording survived in the current draft 
> All variables which do not have dynamic storage duration, do not have thread storage duration, and are not **local** have static storage duration.

Should we say 
> All variables which do not have dynamic storage duration, do not have thread storage duration, and do not belong to block and function parameter scope have static storage duration.  

To be consistent with these prior modifications.

**Comment by FrankHB** [comment]
Or better "are not declared in"?

I'm neutral to preserve "local" or not (though "local scope" has been removed away after C++03 someday, it should be still familiar to many users), but "belong" seems somewhat strange to me.

**Comment by xmh0511** [comment]
> Or better "are not declared in"?
> 
> I'm neutral to preserve "local" or not (though "local scope" has been removed away after C++03 someday, it should be still familiar to many users), but "belong" seems somewhat strange to me.

A declaration that inhabits a scope does not mean the associated entity belongs to that scope.
