### ISSUE TITLE
[ranges.syn] Forward declarations of tuple_size and tuple_element are not shown in the synopsis

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#4572]
The forward declarations of these two primary templates (which are not defined) are shown in [[tuple.syn]](https://eel.is/c++draft/tuple.syn), [[utility.syn]](https://eel.is/c++draft/utility.syn), and [[array.syn]](https://eel.is/c++draft/array.syn), but not in [[ranges.syn]](https://eel.is/c++draft/ranges.syn), which is inconsistent.
Perhaps it should be resolved editorially, as the declarations of these two primary templates are effectively required in `<ranges>`.

**Comment by jensmaurer** [comment]
One could argue that the public names need not be made available, even if partial specializations are shown. tuple.helper p6+8 say

> In addition to being available via inclusion of the `<tuple>` header, the template is available when any of the headers `<array>`, `<ranges>`, or `<utility>` are included.

And we do make the primary templates available in `<array>` and `<utility>`, where we also introduce partial specializations. So, this looks like an oversight.

**Comment by jensmaurer** [comment]
@jwakely, would you consider the addition of
```
 template<class T> struct tuple_size;
 template<size_t I, class T> struct tuple_element;
```
to the `<ranges>` synopsis as editorial, i.e. not changing the intended meaning of the standard?

**Comment by jwakely** [comment]
Yes, I think this is editorial.

In general it's true that names user implicitly in a header are not necessarily made available by that header. But for partial specializations I think it's reasonable to expect the primary template to be declared too (I don't see much advantage to introducing compiler magic to make it work). And in this case we do say they're made available by `<ranges>`.
