### ISSUE TITLE
[iterator.cust.swap] Should iter_move be qualified with ranges::?

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#4576]
It is clear that `iter_move` in [[iterator.cust.swap]](https://eel.is/c++draft/iterator.cust.swap) denotes `::std::ranges::iter_move`. However, it seems that [[contents]/3](https://eel.is/c++draft/contents#3) makes unqualified `iter_move` denote the non-existing `::std::iter_move`.

So should we qualify these occurrences of `iter_move` with `ranges::`?

**Comment by jensmaurer** [comment]
A change here is not desirable. This should be addressed by #1913.

**Comment by frederick-vs-ja** [comment]
Fixed by #4695.
