### ISSUE TITLE
[syserr] Should `make_error_code` and `make_error_condition` be found by ADL?

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#4577]
[\[syserr.errcode.constructors\]/4](http://eel.is/c++draft/syserr.errcode.constructors#4) and [\[syserr.errcode.modifiers\]/3](http://eel.is/c++draft/syserr.errcode.modifiers#3) have a postcondition:

> *Postconditions*: `*this == make_error_code(e)`.

Similarly, [\[syserr.errcondition.constructors\]/4](http://eel.is/c++draft/syserr.errcode.constructors#4) and [\[syserr.errcondition.modifiers\]/3](http://eel.is/c++draft/syserr.errcondition.modifiers#3) have a postcondition:

> *Postconditions*: `*this == make_error_condition(e)`.

Per [\[contents\]/3](http://eel.is/c++draft/contents#3) these should be treated as qualified calls. But all implementations (MSVC, libstdc++, libc++, Boost) use unqualified call.

I believe that the intent is to find program-defined `make_error_code` and `make_error_condition`. That is, the specification should clarify that these functions are found by ADL.

**Comment by jensmaurer** [comment]
Yes, I believe `make_error_code()` and `make_error_condition()` were intended as customization points.

@jwakely, this sounds like an LWG issue to me. In particular, any mention of argument-dependent name lookup should probably discuss in which context it appears.

**Comment by jwakely** [comment]
Yes, this needs an LWG issue.
