### ISSUE TITLE
[expr.unary.general] Misaligned grammar productions

### ISSUE THREAD

**Issue by opensdh** [cplusplus/draft#4581]
The grammar in [expr.unary.general] has `++`, `--`, and perhaps `*` indented less than the other productions.  Other uses of `\terminal` at the beginning of productions don't seem to be affected.

**Comment by jensmaurer** [comment]
This is interesting. I haven't found an easy fix for this, unfortunately.

![align](https://user-images.githubusercontent.com/23412755/114238035-3f336e00-9984-11eb-9ac0-3b09a00508a5.png)

**Comment by opensdh** [comment]
Maybe it needs the `\microtypesetup{protrusion=false}` from [expr.prim.fold]?

**Comment by jensmaurer** [comment]
@opensdh, yes that fixed it. See the linked pull request.

**Comment by tkoeppe** [comment]
I feel like I disabled protrusion elsewhere before, but I must have missed this. Thanks!
