### ISSUE TITLE
The wording in [dcl.fct.def.general]/2 doesn't seem to be right.

### ISSUE THREAD

**Issue by AlexanderMace** [cplusplus/draft#4604]
[\[dcl.fct.def.general\]/2](http://eel.is/c++draft/dcl.fct.def#general-2): 

> **In a _function-definition_, either `void` _declarator_ `;` or _declarator_ `;` shall be a well-formed function declaration
> as described in [dcl.fct].** A function shall be defined only in namespace or class scope. The type of a parameter or the return  type for a function definition shall not be a (possibly cv-qualified) class type that is incomplete or abstract within the function body unless the function is deleted ([dcl.fct.def.delete]).

What does the sentence highlighted above has to do with the fact that  a parenthesized declarator should be accepted in a _function-definition_? See [DR2145](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2145) about this.  

See also [my question](https://stackoverflow.com/q/51071198/2337207) in SO and [this comment](https://stackoverflow.com/questions/51071198/i-didnt-understand-the-change-proposed-in-dr-2145-for-dcl-fct-def-general-2#comment89132939_51071198) by T.C..

**Comment by jensmaurer** [comment]
A declarator may be parenthesized as described in [dcl.meaning.general] p8.

Therefore, this sentence ensures that parenthesized declarators are allowed.

**Comment by AlexanderMace** [comment]
"A declarator may be parenthesized as described in [dcl.meaning.general] p8."

[dcl.fct.def.general]/2 is about _declarator_, but [dcl.meaning.general]/8 is about _declarator-id_  **not** _declarator_.

"Therefore, this sentence ensures that parenthesized declarators are allowed."

I simply cannot understand the relationship between the alluded sentence and what you wrote above. Could you elaborate?

**Comment by jensmaurer** [comment]
[dcl.meaning.general] p8 "In a declaration T D where D has the form ..." 

Compare with [dcl.meaning.general] p5, which says that "D" is a declarator. Note that p8 talks about the declarator-id (possibly deep) inside D and assumes the understanding of p5.

**Comment by AlexanderMace** [comment]
"Compare with [dcl.meaning.general] p5, which says that "D" is a declarator. Note that p8 talks about the declarator-id (possibly deep) inside D and assumes the understanding of p5."

Ok, I can accept this. But how does the sentence highlighted in my first post ensure that parenthesized _declarators_ are allowed?

**Comment by jensmaurer** [comment]
Because it says that "T declarator" (with T=void or absent), with the declarator from the constructor grammar, must be a valid function declaration. In order to analyze this, you need to iterate through [dcl.meaning], which (among other things) takes care of "T (declarator)".

**Comment by AlexanderMace** [comment]
> **In a _function-definition_, either `void` _declarator_ `;` or _declarator_ `;` shall be a well-formed function declaration
> as described in [dcl.fct].**

It definitely doesn't tell me anything. I'm giving up !
