### ISSUE TITLE
[range.utility.helpers] not-same-as is confusingly named

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#4606]
```cpp
template<class T, class U>
  concept not-same-as =                         // exposition only
    !same_­as<remove_cvref_t<T>, remove_cvref_t<U>>;
```

It's confusing to have `not-same-as<T, U>` mean something completely different from `not same_as<T, U>`. Can we find a better name for this exposition-only concept?

**Comment by jensmaurer** [comment]
- It's not "completely" different, it's just a bit different.
- Suggestions for a better name are welcome.

**Comment by jwakely** [comment]
_`dissimilar`_ ?

**Comment by timsong-cpp** [comment]
I think we should avoid "similar" since that's a Core term. [P2199](https://wg21.link/P2199/github) wants to propose this exact thing as `different_from` (R0 uses `distinct_from` but a change is expected in the next revision), so maybe we can just call it _`different-from`_?
