### ISSUE TITLE
[cpp.import]/3 What if pp-import is produce by `#include` within private module fragment?

### ISSUE THREAD

**Issue by onihusube** [cplusplus/draft#4618]
In module-file it is forbidden. 

- [15.5 Header unit importation [cpp.import]](http://eel.is/c++draft/cpp#import-3)

However, it is unclear whether *private module fragment* is included in that (module-file), and if it is, then *global module fragment* is included as well.

Looking at [P1857R3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1857r3.html#changes), which introduced this clause, it says:

> 1. Change Log
> - R2
>   - Add wording that rejects #includes from turning into imports in the purview of a module.

Since it says "purview of a module", there seems to be no intention to include *global module fragment*. On the other hand, *private module fragment* seems to be included.

The current clause [cpp.import]/3 seems to either include both fragments or none of them.

At least I think *private module fragment* is included, but what about?

> If a pp-import is produced by source file inclusion (including by the rewrite produced when a #include directive names an importable header) while processing the group of a module-file ***or pp-private-module-fragment***
, the program is ill-formed.

**Comment by jensmaurer** [comment]
We usually use the phrase "named module" if we wish to exclude the global module. I haven't looked in detail whether that would address the concern here.

**Comment by onihusube** [comment]
Is it correct to interpret *group* in this clause as recursively containing two fragments?

It seems to make sense when you consider the purpose of P1857R3.
