### ISSUE TITLE
CWG1531 resolution doesn't appear to have been applied

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#464]
[CWG issue 1531](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1531) was moved to DR at the April 2013 meeting, see [N3622](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3622.pdf), CWG motion 4, but its resolution was not applied to the working draft, and the issue is also missing from [N3692](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3692.html).

**Comment by zygoloid** [comment]
The CWG motion was

"Move we accept as Defect Reports the following issues
from N3539 and apply their proposed resolutions to the C++ working
paper:
903 1213 1358 1531"

N3539 did not have any drafting for core issue 1531.
