### ISSUE TITLE
pick formatting for const object and apply it consistently

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#469]
The definition of the term _const object_ (and friends) does not use teletype font for the "const", and nor do nearby uses of the term. However, other uses of this term in the standard **do** use a teletype font. We should pick one or the other and do it consistently. I'm not sure we **can** use italic teletype, so perhaps that forces us to use the non-teletype font everywhere.

(This same thing happens in a bunch of other places, for instance the terms 'constexpr constructor' and 'return statement'.)

**Comment by cpplearner** [comment]
Actually, italic teletype is already used in [conv]p4, the definition of "contextually converted to `bool`".

**Comment by zygoloid** [comment]
Hmm, it looks like LaTeX used bold italic monospace, not some kind of teletype font, there. Note the shapes of the 'b' and 'l' characters and the generally awful appearance...

**Comment by jensmaurer** [comment]
Editorial meeting consensus: We define the term-of-art "const object" etc, so no \tcode is used. See also #106 and related issues.
