### ISSUE TITLE
Consider spanstream assignment operations

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#4700]
See discussion in #4687: spanstream has a section "Assignment and swap", but only defines swap operations. Should assignment operations be defined, or at least defaulted? This applies to all of `spanstream`, `ospanstream` and `ispanstream`.

**Comment by JohelEGP** [comment]
And `basic_istringstream`, see https://github.com/cplusplus/draft/pull/4687#discussion_r650211541.

**Comment by timsong-cpp** [comment]
The intent is that assignment is entirely specified by [functions.within.classes].

**Comment by jwakely** [comment]
Right, they are defined by front matter. They don't have any special behaviour that needs to be specified explicitly.

**Comment by jensmaurer** [comment]
@tkoeppe: What's the remaining issue here, given [functions.within.classes] ?

**Comment by JohelEGP** [comment]
That'd be making sure the subclause name and stable id mention swap and not assign.

**Comment by tkoeppe** [comment]
@jensmaurer: Yes, what Johel said, we may want to rename the subclause heading.
