### ISSUE TITLE
Inappropriate "Shall" in PostConditions: elements

### ISSUE THREAD

**Issue by Dani-Hub** [cplusplus/draft#4711]
During my recent survey of Postconditions: elements in the N4892 working draft I found two occurrences with inappropriate "shall" usage. A quick confirmation on the LWG reflector indicated that an editorial change would be appreciated:

1) [util.smartptr.shared.const] p23:
```
shared_ptr(shared_ptr&& r) noexcept;
template<class Y> shared_ptr(shared_ptr<Y>&& r) noexcept;
```
[...]
23 Postconditions: `*this` <del>shall</del> contain<ins>s</ins> the old value of `r`. `r` <del>shall be</del><ins>is</ins> empty<del>.</del> <ins>and</ins> `r.get() == nullptr`.

2) Table [tab:container.hash.req]:

 Expression   |  Return type   |  pre-/post-condition
 ------------|---------------|------------------------------------------------------
`b.bucket(k)`|    `size_type`   |  [...]
 | | | Postconditions: The return value <del>shall be</del>
 | | | <ins>is</ins> in the range [0, b.bucket_count()).

**Comment by tkoeppe** [comment]
Great, thanks, could you send a pull request?

**Comment by Dani-Hub** [comment]
Would be great, if you could just change it directly, @tkoeppe - Thanks!

**Comment by tkoeppe** [comment]
Hm, we also say things like ``get()` == nullptr`." a lot instead of "`get() == nullptr` is `true`." But that's pretty pervasive.

**Comment by Dani-Hub** [comment]
Please feel free do make any further adjustments as appropriate, this was just my initial idea of a change suggestion.

**Comment by tkoeppe** [comment]
Yes, I might open a new issue.

Original issue fixed by 6091e264374349c12aa775cd66e5f062d9c7b9e4 and a7ff942fc3d57d35a276ca4aab70f62368466d80. Thanks!

**Comment by jensmaurer** [comment]
Since I'm actively progressing the "dismantle requirements tables" pull request, this change just needlessly introduces conflicts at a rather inopportune time.

**Comment by Dani-Hub** [comment]
So why no deferring it for a better occasion?

**Comment by tkoeppe** [comment]
@jensmaurer: sorry about that! I hope this one small change can be back-ported to your pending PR, and I'll keep away from the tables  henceforth!
