### ISSUE TITLE
"binds to" versus "is bound to"

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#4722]
In most places in the standard, where we talk about a reference being initialized with an expression or a temporary object, we say "the reference binds to the expression" and similar things. However, we also say all of these things:

* the expression binds to the reference (in only about 3 places)
* the reference is bound to the expression
* the expression is bound to the reference

It'd be nice if we were more consistent here. I think the right viewpoint is that references bind to expressions, not the other way around, but if so, is it correct to say that expressions are bound to references or that they are bound to *by* references or something else?

**Comment by languagelawyer** [comment]
> I think the right viewpoint is that references bind to expressions

Not objects/funcions?

**Comment by jensmaurer** [comment]
I think @languagelawyer  is right; reference should bind to objects and/or functions. Of course, an expression may yield an lvalue that designates an object or function to which the reference binds.

**Comment by jensmaurer** [comment]
Editorial meeting 2021-07-16: "reference binds to an expression"
