### ISSUE TITLE
Replace "Working Draft" for non mailing-list ready builds

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#4726]
Following https://github.com/cplusplus/draft/pull/4725#issuecomment-872332594, I think "Working Draft" should be replaced with something more appropiate. The comment following the linked one suggests that just appending "Snapshot" won't do. 

Part of the WD publishing process for the mailing list should be replacing whatever is chosen back to "Working Draft", as it currently is. 

https://github.com/cplusplus/draft/blob/641afd15b04dffd415c152752e9adfcc58f0fe94/source/cover-wd.tex#L25
https://github.com/cplusplus/draft/blob/641afd15b04dffd415c152752e9adfcc58f0fe94/source/std.tex#L34

**Comment by tkoeppe** [comment]
I don't feel terribly inclined to make any changes to a process that isn't broken. This repository exists for the ease of editorial collaboration, and it's not advertised as anything else, or at all. Can we just leave it as is?

**Comment by JohelEGP** [comment]
Definitely. The PDF is one thing, since it _can_ be mistaken as a proper Working Draft.

If no one feels strongly for this, feel free to close this issue. Then I'll open a corresponding issue at https://github.com/Eelis/cxxdraft-htmlgen, which would remain advertised as a "Working Draft".

**Comment by tkoeppe** [comment]
Note also that we do have an index of actual working drafts, as published in the official mailings: https://github.com/cplusplus/draft/blob/main/papers/wd-index.md

It doesn't seem particularly hard for interested parties to get their hands on a recent working draft, and not dirty in the process.

**Comment by tkoeppe** [comment]
Let's leave this as is.
