### ISSUE TITLE
[allocator.uses.construction] LWG3527 incompletely applied

### ISSUE THREAD

**Issue by BoPersson** [cplusplus/draft#4728]
In N4892, paragraph 15 of the section now looks like:

return uses_allocator_construction_args<T>(alloc, piecewise_construct,
                                           forward_as_tuple(get<0>(std::move(pr)),
                                           forward_as_tuple(get<1>(std::move(pr)));

Here the second and third row would each need an additional closing parenthesis to match the code in the issue resolution.

**Comment by JohelEGP** [comment]
Missed at https://github.com/cplusplus/draft/commit/9ffd955ed17b8482c0b491d3590f3d3986650e7c.
