### ISSUE TITLE
[over.match.class.deduct] The obscure structure of the rule for aggregate deduction

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4735]
> In addition, if C is defined and its definition satisfies the conditions for an aggregate class ([dcl.init.aggr]) with the assumption that any dependent base class has no virtual functions and no virtual base classes, and the initializer is a non-empty braced-init-list or parenthesized expression-list, and there are no deduction-guides for C, the set contains an additional function template, called the aggregate deduction candidate, defined as follows.  Let X<sub>1</sub>,...,X<sub>N</sub> be the elements of the initializer-list or designated-initializer-list of the braced-init-list, or of the expression-list. For each X<sub>i</sub>, let e<sub>i</sub> be the corresponding aggregate element of C or **of one of its (possibly recursive) subaggregates that would be initialized by X<sub>i</sub>  if**
>> - [1.5] **brace elision is not considered for any aggregate element that has a dependent non-array type or an array type with a value-dependent bound**, and  
>> - [1.6] each non-trailing aggregate element that is a pack expansion is assumed to correspond to no elements of the initializer list, and  
>> - [1.7] a trailing aggregate element that is a pack expansion is assumed to correspond to all remaining elements of the initializer list (if any).
>
> If there is no such aggregate element e<sub>i</sub> for any X<sub>i</sub>, the aggregate deduction candidate is not added to the set. The aggregate deduction candidate is derived as above from a hypothetical constructor C(T<sub>1</sub>,...,T<sub>n</sub>) 
>> - if e<sub>i</sub> is of array type and x<sub>i</sub> is a braced-init-list or string-literal, T<sub>i</sub> is an rvalue reference to the declared type of e<sub>i</sub>
>> - otherwise, T<sub>i</sub> is the declared type of e<sub>i</sub>

According to the expound in [P2082R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2082r1.pdf) and the following example, the actual intent seems to be that:  
e<sub>i</sub> is the corresponding aggregate element of C if the aggregate element is a dependent non-array type or an array type with a value-dependent bound. Instead, e<sub>i</sub> is the corresponding aggregate element of one of C's subaggregates if the brace elision can be considered(i.e, the inverse cases of what the previous sentence says). However, the current appearance of the structure of "if..." seems to have a reverse meaning.  Specifically, the rule probably can be read as that

> let e<sub>i</sub> be the corresponding aggregate element of C,  
>or the corresponding aggregate element one of its (possibly recursive) subaggregates that would be initialized by X<sub>i</sub>  if 
>> - [1.5]  **brace elision is not considered for any aggregate element that has a dependent non-array type or an array type with a value-dependent bound**
>> [...]

See this example
````cpp
template<typename T>
struct Test{
    T t[2];
};
int main(){
  Test t{{1,2}};
}
````
According to the diagnosis of GCC, the candidate set comprises `template<class T> Test(T, T)-> Test<T>`.  The obscure structure can result in this [issue](https://stackoverflow.com/questions/67280884/why-is-the-braced-init-list-not-supported-in-an-aggregate-deduction-but-brace-el). 

***
Issue 2:     
Notice the bullet [1.6] and [1.7] in the above rule. It appears to me these bullets should be statements(general rules for aggregate CTAD), why are they placed after the `if` condition?

**Comment by xmh0511** [comment]
From the response of the mailing this issue to core language issue, the intent of this rule is saying if the type of the aggregate element is neither a dependent non-array type nor an array type with a value-dependent bound, and the brace elision is considered due to the initializer-list does not begin with a left brace, *ei* is the corresponding aggregate element of the subaggregate, otherwise, it is the aggregate element. But, such meaning is hard to read from the current wording(structure).

**Comment by jensmaurer** [comment]
Closing in favor of cplusplus/CWG#83.
