### ISSUE TITLE
[bit.count] Turn introduction of `N` into a note

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#4747]
`N` is only used in notes. Maybe (also) say "in the following notes" instead. This sentence is also missing a paragraph number.

**Comment by jensmaurer** [comment]
I agree with the missing paragraph number.
It's also correct that "N" is only used in notes, but I'm not sure any of the proposed cures is better than the disease. In short, I think introducing N normatively and then using it only inside notes is not a problem that needs a fix.
