### ISSUE TITLE
[expr.new] doesn't specify the type of a new-expression

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#4752]
[[Note 6: Both `new int` and `new int[10]` have type `int*` and the type of `new int[i][10]` is `int (*)[10]` — end note]](http://eel.is/c++draft/expr.new#note-6)

I couldn't find normative wording in [expr.new] supporting this. Is it somewhere else?

**Comment by xmh0511** [comment]
For single-object new-expression, the relevant rule is defined as that
[expr.new#5]
> When the allocated object is not an array, the result of the new-expression is **a pointer to the object created**.

While the relevant rule for array new-expression is defined as that 
[expr.new#6]
> When the allocated object is an array (that is, the noptr-new-declarator syntax is used or the new-type-id or type-id denotes an array type), the new-expression yields **a pointer to the initial element (if any) of the array**.

**Comment by languagelawyer** [comment]
This specifies the value of a _new-expression_. http://eel.is/c++draft/basic.lval#def:result,prvalue http://eel.is/c++draft/basic.compound#def:pointer_to

**Comment by xmh0511** [comment]
For pointer to object, it is specified in [basic.compound#3], that is
> A pointer to an object of type T is referred to as a “pointer to T”.  
the value that is a pointer to the object of T is certainly has the type "pointer to T"

**Comment by languagelawyer** [comment]
> the value that is a pointer to the object of T certainly has the type "pointer to T"

```c++
int i;
reinterpret_cast<unsigned*>(&i); // value «pointer to an object of type int» has type `unsigned*`
```

**Comment by xmh0511** [comment]
`unsigned int` and `int` are different types as per [basic.types#basic.fundamental-2], hence the result of `reinterpret_cast<unsigned*>(&i);` is equivalent to `static_­cast<unsigned int*>(static_­cast<void*>(i)).` as per [expr.reinterpret.cast#7], where the value of `static_­cast<void*>(i)` still points to the object `i` as per [conv.ptr#2], abbreviate the result of that function as `temp`, then the result of  `static_­cast<unsigned int*>(temp)` remains unchanged as per [expr.static.cast#13], in other words, the pointer still points to the object of type int.
