### ISSUE TITLE
ranges::split_view::iterator::operator* Not rendered properly

### ISSUE THREAD

**Issue by miscco** [cplusplus/draft#4757]
It seems that in https://eel.is/c++draft/ranges#range.split.iterator-3 the `{}` of the subclause constructor are missing.

I cannot really find an error with the code at a glance.

**Comment by jwakely** [comment]
They need to be escaped with backslashes in that context.

**Comment by jwakely** [comment]
This isn't the first time this has happened, we should have an automated check for it if possible.

**Comment by cpplearner** [comment]
It seems that http://eel.is/c++draft/ hasn't picked up https://github.com/cplusplus/draft/commit/628ded4b8e6cd4b7297f9e04a394f200423ab2d7
