### ISSUE TITLE
[basic.types.general] p6 Incorrect comment in example

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4779]
[basic.types#general-example-3]
````cpp
extern int arr[];               // the type of arr is incomplete
typedef int UNKA[];             // UNKA is an incomplete type
UNKA* arrp;                     // arrp is a pointer to an incomplete type
int  arr[10];                   // now the type of arr is complete
void bar() {
  arrp = &arr;                  // error: different types
}
````
The above example is a simplified example of [basic.types#general-example-3], the comment says it's an error. However, it's valid even though their types are different. A **qualification conversion** can be used to convert the type of `&arr` to the cv-unqualified type of `arrp`, which obeys [expr.ass#3]
> If the right operand is an expression, it is implicitly converted to the cv-unqualified type of the left operand.  

The type of `&arr` is `pointer to array of 10 int` whilst the type of `arrp` is `pointer to array of unknown bound of int`, as per [conv.qual#3], the former type can be converted to the later type by a qualification conversion. Hence, the comment should be "ok". [GCC](https://godbolt.org/z/7Eoj99dKz) is in compliance with these rules.

**Comment by jensmaurer** [comment]
I think the assessment here is correct: An pointer to array of known bound can be converted to a pointer to an array of unknown bound.
