### ISSUE TITLE
[basic.def.odr] Validity of duplicate enumerators CWG2530

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4788]
````cpp
enum class A{
    a = 0,
    a = 1
};
````
[basic#pre-5.12] specifies that an enumerator-definition is a declaration. According to [basic.link#8], they declare the same entity. For this example, the major implementations report that `"redefinition of enumerator 'a'".`, however, [basic.def.odr#1] didn't mention enumerators  
> No translation unit shall contain more than one definition of any variable, function, class type, enumeration type, template, default argument for a parameter (for a function in a given scope), or default template argument.  

Does the rule omit such a case? Also, ask the clarification of this case in this [issue](https://stackoverflow.com/questions/68602375/is-there-any-rule-about-why-is-the-redefinition-of-the-enumerator-ill-formed).

**Comment by jensmaurer** [comment]
http://lists.isocpp.org/core/2021/08/11347.php

**Comment by jensmaurer** [comment]
The first case is probably a defect.
The second case is handled by [basic.scope.scope] p4

The name ::x "is bound to two declarations that potentially conflict",
because the declarations for A::x and B::x "cause their shared name to
denote different entities".

**Comment by jensmaurer** [comment]
See CWG2530

**Comment by frederick-vs-ja** [comment]
Should have been closed by #6118 (9859f3b378464ad21bfb640366cf0610a5def9bc).
