### ISSUE TITLE
[dcl.spec.general] p2 prevents the valid type combination

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4796]
````cpp
unsigned  long  long int const volatile a = 0;
````
In this declaration, the complete decl-specifier-seq is `unsigned  long  long int const volatile`. Where *unsigned*, *long*, *long*, *int* are all *simple-type-specifier*s, which in turn are *type-specifier*s, which are also *defining-type-specifier*s; While *const* and *volatile* are both *cv-qualifier*s, which are *type-specifier*s, which are also *defining-type-specifier*s. Hence, in this complete  *decl-specifier-seq*, the defining-type-specifier appears six times. 

However, [dcl.spec.general] p2 says  
> Each decl-specifier **shall** appear at most once in a complete decl-specifier-seq, except that long may appear twice.

Obviously, *defining-type-specifier* appears more than once that are not only *long*.   I think the intent of this rule says each indivisible specifier shall appear at most once except that *long* may appear twice, I would like to name the indivisible specifier as **atomic** specifier(e.g., int, long, short, const, virtual, explicit ...). But It's not formal wording, maybe we can use some terms to precisely phrase such the meaning?

**Comment by jwakely** [comment]
"atomic specifier" is a bad suggestion, because of the confusion with C's atomic type specifier.

**Comment by jwakely** [comment]
>Obviously, _defining-type-specifier_ appears more than once that are not only long.

But they are different specifiers, which is fine, isn't it? It says "each" _decl-specifier_ and that's true. Each of them appears at most once, except `long`. I don't see the issue.

**Comment by xmh0511** [comment]
In the grammar tree of *decl-specifier* [dcl.spec.general] p1, it lists all components that are *decl-specifier*s, "each decl-specifier" sounds like it says each component in that tree.

**Comment by xmh0511** [comment]
Analogy, when we say each *pm-expression* shall appear in... at most once. What does it mean? Should we consider any direct sub-element categories to pm-expression as a unit or anything others? In other words, Does it mean *cast-expression* shall appear at most once or *unary-expression* or *postfix-expression* or each indivisible expression(minimum unit)?

**Comment by jensmaurer** [comment]
So, the issue is whether we need to decompose _decl-specifier_ into its parts, and how far that decomposition goes (e.g. are tokens inside `decltype` also in view?).

**Comment by xmh0511** [comment]
The expression in `decltype` must be a valid expression, IMO, I think we are not necessary to concern the content contained in `decltype` at the perspective of [dcl.spec.general] p2. However, on the top-level, *decltype-specifier* shall only appear once in the complete *decl-specifier-seq*.  

I don't figure out a fine way to phrase them except that the wording **indivisible decl-specifier**, which means the most degree of decomposing **decl-specifier**.

**Comment by jensmaurer** [comment]
That's all fine, but `decltype(static_cast<void f(int,int)>(nullptr))` does contain (deep inside) the _decl-specifiers_ "void" and "int" (twice). The phrasing needs to be such that those are not considered for the general _decl-specifier_ prohibition.

**Comment by xmh0511** [comment]
`void (*)(int,int)` is a type-id where `void` is in the type-specifier-seq, which has a more restricted requirement.  
[dcl.type.general] p2
> As a general rule, ..., at most one type-specifier is allowed in a type-specifier-seq.The only exceptions to this rule are the following: 

the two "int", in my mind, belong to the different complete decl-specifier-seq of two parameter-declarations. So, it's fine here. And [dcl.dcl.dcl.pre] p2 has an addition expound.
> Certain declarations contain one or more scopes ([basic.scope.scope]). Unless otherwise stated, utterances in [dcl.dcl] about components in, of, or contained by a declaration or subcomponent thereof refer only to those components of the declaration that are not nested within scopes nested within the declaration.  

Even though the parameters have abstract-declarators, but they still obey the above rules due to [dcl.dcl#dcl.decl.general-2]
> In all contexts, a declarator is interpreted as given below. Where an abstract-declarator can be used (or omitted) in place of a declarator ([dcl.fct], [except.pre]), it is as if a unique identifier were included in the appropriate place ([dcl.name]).

**Comment by zygoloid** [comment]
If this is worth addressing at all, how about:

> Each <ins>distinct</ins> decl-specifier shall appear at most once in a complete decl-specifier-seq, except that long may appear twice.

It seems clear to me that `int` and `unsigned` are distinct decl-specifiers even though they both use the same immediate production of decl-specifier. (But I also think the wording as-is is clear; if we wanted the other meaning we'd need to say something like "each form of decl-specifier shall appear at most once".)

**Comment by xmh0511** [comment]
Actually, this issue claims that what is the degree of classification when we say "each decl-specifier". Does it refer to these components that are directly subsumed to `decl-specifier`? "distinct decl-specifier" may also have the same problem. "storage-class-specifier" is distinguishable with "defining-type-specifier" but "defining-type-specifier" is not distinguishable with itself when in this **perspective**.

**Comment by jensmaurer** [comment]
It is understood that the specification here does not have utmost precision. 
- The decl-specifiers of the decl-specifier-seq need to be decomposed several levels before we can apply the "at most once" check.
- "shall appear at most once in" has the usual concerns of giving a lexical ("appear") meaning.

While I think the situation is sufficiently clear for type-specifiers and other single-keyword specifiers appearing there, it is less clear for something like:

```
struct S {
  explicit(false) explicit(true) S(int);
};
```
Obviously, `explicit(false)` and `explicit(true)` are different decl-specifiers, but we seem to be lacking words to make this declaration ill-formed.
