### ISSUE TITLE
[basic.start.static] p3 is a bit vague

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4800]
> An implementation is permitted to perform the initialization of a variable with static or thread storage duration as a static initialization even if such initialization is not required to be done statically, provided that
>> - the dynamic version of the initialization does not change the value of any other object of static or thread storage duration prior to its initialization, and
>> - the static version of the initialization produces the same value in the initialized variable as would be produced by the dynamic initialization if all variables not required to be initialized statically were initialized dynamically. 

````cpp
inline double fd() { return 1.0; }
extern double d1;
double d2 = d1;     // unspecified:
                    // either statically initialized to 0.0 or
                    // dynamically initialized to 0.0 if d1 is
                    // dynamically initialized, or 1.0 otherwise
double d1 = fd();   // either initialized statically or dynamically to 1.0
````
The dynamic initialization of d2 can be finely interpreted. However, consider the case, static initialization of d2, when [basic.start.static] p3 applies.

The dynamic initialization of `d2` would be `0` if `d2` and `d1` are all dynamically initialized(since the zero-initialization occurs prior to any dynamic initialization).  However, why could we guarantee that the value of `d2` statically initialized from `d1` is definitely 0? In other words, why is the value of the initializer `d1`  zero when it participates in the static initialization at that point? This implies the static initialization(zero-initialization) of `d1` must happen before the static initialization of `d2`(d2 is statically initialized from `d1`).

**Comment by jensmaurer** [comment]
"static initialization" is defined as zero-initialization or constant-initialization. Which means we have to check whether
`double d2 = x;`
satisfies the conditions given in the quoted text. Which it does for `x == 0` only, I believe, so `double d2 = 0;` is a valid static initialization for the above snippet.

**Comment by xmh0511** [comment]
I think "the static version of the initialization" is saying that `d2` is **statically initialized** from **x**, which should have been a dynamic initialization. 
````cpp
double d1 = fd(); // either initialized statically or dynamically to 1.0
````
Regardless of static or dynamic initialization of `d1`, they all have the value `1.0` that is the result of the initializer `fd()`. Anyhow, the static version of `d2` requires that the static initialization(i.e., zero-initialization) of `x` shall occur prior to its static initialization. The standard indeed does not specify the order of static initialization, hence, it leaves room for this possibility? Is it a correct interpretation of this issue?

**Comment by jensmaurer** [comment]
There is no separate concept "statically initialized"; it just means "static initialization". And "static initialization" can't read other data, but just deal in (compile-time) constants, so an ordering problem does not arise (which is the primary motivation for static initialization).

It's a valid initialization order "d1 zero-init, then d2 dynamically initialized from d1" so the transformation "d2 = 0" is valid (i.e. means zero-initialization of d2).

**Comment by xmh0511** [comment]
*It's a valid initialization order "d1 zero-init, then d2 dynamically initialized from d1, then d1 dynamically initialized from fd()"*
This has implied that the static initialization of `d1` must order prior to static initialization of `d2`(i.e. means zero-initialization of d2), Isn't it?

**Comment by jensmaurer** [comment]
Again, static initialization (which includes constant initialization) does not read the value of d1, so there is no ordering concern here. Any argument that talks about static initialization somehow reading d1 is incorrect.

The idea is: If there is a valid combination of static and dynamic initialization for all variables in view (with possibly some dynamic initialization already transformed to static initialization) resulting in some initial values for the variables and the conditions are satisfied, then a particular dynamic initialization may instead be performed as static initialization if the resulting initial values are the same as for that particular combination.

**Comment by xmh0511** [comment]
According to your clarification, I think if add an additional wording would make the meaning clear
> An implementation is permitted to perform the initialization of a variable with static or thread storage duration as a static initialization even if such initialization is not required to be done statically, provided that
>> - [...]
>> - [...]
>
> Constant initialization from the value will replace the dynamic initialization.  

The concern is basic on what is the static version of the initialization. Does it mean the dynamic initialization would be viewed as a static initialization(which requires reading the value of the initializer) to be performed, or mean a complete new static initialization generated by the implementation if conditions are satisfied(as if the initializer were replaced to a constant value)?

**Comment by jensmaurer** [comment]
An lvalue-to-rvalue conversion on a global non-const variable would violate [expr.const] and thus not be static initialization. Thus, that can't possibly be meant.

**Comment by xmh0511** [comment]
So, I think we should clarify what is the initializer expression in the transformed static version initialization. Since we always have a prvalue to perform the initialization. Maybe, the value consisted with the dynamic initialization could be interpreted as a constant-expression to perform that static initialization.

**Comment by jensmaurer** [comment]
This might be addressed by CWG2821.
