### ISSUE TITLE
[stacktrace.entry.cmp] does not describe operator<=>

### ISSUE THREAD

**Issue by mumbleskates** [cplusplus/draft#4801]
In brief, the line
```
friend constexpr strong_ordering operator<=>(const stacktrace_entry& x,
                                             const stacktrace_entry& y) noexcept;
```
in [stacktrace.entry.overview] is not mentioned in the detailed specification in [stacktrace.empty.cmp], section 20.21.3.5.

**Comment by jwakely** [comment]
[stacktrace.entry.overview] says it models `three_way_comparable<strong_ordering>` which is all we need to say. The actual ordering is unspecified, so there's nothing more to say.

**Comment by mumbleskates** [comment]
This is true! I just put together an implementation status listing for libc++ and went over every operator<=> in the spec; out of about 51 distinct standard library types which have or may have `operator<=>`, and it does stand out a bit that this is the only type with nothing to say; I suppose it's fine though, as pretty much all the rest have sensible commonly observable properties or derive their ordering from the value types.

It wasn't immediately obvious to me that modeling `three_way_comparable<strong_ordering>` is enough to actually guarantee reasonable behavior but this sounds fine, thanks for the reply
