### ISSUE TITLE
[basic.life] Does zero-initialization as a static initialization begin the lifetime of an object? CWG2821

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4802]
````cpp
int i = i;  // #1 static storage duration
````
[basic.life] p1 says
> A variable is said to have vacuous initialization if it is default-initialized and, if it is of class type or a (possibly multi-dimensional) array thereof, that class type has a trivial default constructor. The lifetime of an object of type T begins when:
>> - storage with the proper alignment and size for type T is obtained, and
>> - its **initialization** (if any) is complete (including vacuous initialization) ([dcl.init]),  

The declaration at `#1` will undergo initialization twice. One happens in static initialization(zero-initialization), the other happens in dynamic initialization(whose initializer is itself). 

However, the second bullet only requires that *its **initialization** is complete*, which initialization does it refer to in the intent here? Before the dynamic initialization occurs, `i` has been statically initialized to be `0`, which can still say its initialization is complete. Does it mean the lifetime of `i` at this point has begun?    

I don't know why do we change the original second bullet of the c++17 version to the current wording.  

> if the object has non-vacuous initialization, its initialization is complete,  

I think the older version's intent is clearer to me, which means if the initialization for the object is not non-vacuous, only the specified initialization is complete will the lifetime of the object begin. Except that the possible defect that it didn't say whether the vacuous initialization contributes to this rule.  

Could we just say
>  its **dynamic initialization** (if any) is complete (including vacuous initialization) ([dcl.init])

**Comment by xmh0511** [comment]
Which also causes these two concerns: 
https://stackoverflow.com/questions/67991209/if-a-global-variable-is-initialized-twice-statically-then-dynamically-which

https://stackoverflow.com/questions/67979228/in-c-does-initializing-a-global-variable-with-itself-have-undefined-behaviour

**Comment by jensmaurer** [comment]
We can't access out-of-lifetime variables. However, the example at the bottom of [basic.start.static] p3 makes it clear that the intermediate state of "zero-initialized, but not yet dynamic-initialized" is a perfectly fine state.

In any case, this is not an editorial issue; maybe CWG wishes to somehow remove the double-initialization to make this clear, instead of saying something like "its first initialization" in [basic.life].

**Comment by maggyero** [comment]
> However, the second bullet only requires that its initialization is complete, which initialization does it refer to in the intent here?

@xmh0511 Excellent question.

> maybe CWG wishes to somehow remove the double-initialization to make this clear, instead of saying something like "its first initialization" in [basic.life].

@jensmaurer Interesting.

**Comment by jensmaurer** [comment]
CWG2821
