### ISSUE TITLE
[expr.typeid] glvalue of incomplete type vs typeid

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4826]
````cpp
struct C;
int storage;
C* ptr = (C*)&storage;
typeid(*ptr);  //#1
````
All compilers report `#1` is an error, with the diagnosis `invalid use of incomplete type`. However, there's no relevant rule in the standard that restricts the type of the glvalue operand in [expr.typeid]. Is it an omission?

**Comment by jwakely** [comment]
Since it's unknown whether `S` is a polymorphic type or not, the behaviour here seems undefined. So giving an error is fine.

**Comment by jensmaurer** [comment]
`dynamic_cast` consistently requires complete types for both source and target.

We have "If the type of the _type-id_ is a class type or a reference to a class type, the class shall be completely-defined."

It seems plausible that this rule should also apply to the "expression" case.

**Comment by xmh0511** [comment]
Maybe, we could say that 
> If the static type of the expression is a (possibly cv-qualified) class type, the class shall be completely-defined.

**Comment by xmh0511** [comment]
@jensmaurer  For [expr.typeid] p3
> If the expression is a prvalue, the temporary materialization conversion is applied. The expression is an unevaluated operand. 

How about the following case? 
````cpp
typeid(static_cast<void>(0));
````
The operand is a prvalue of type `void` as per [expr.static.cast] p1 and [expr.static.cast] p6, which means the temporary materialization conversion is not possible to be applied to that operand.
