### ISSUE TITLE
[expr.ass] does not specify the type of the expression (and traditionally misuses "result")

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#4864]

**Comment by jensmaurer** [comment]
I understand the first part ("type is not specified"), but could you please elaborate on the second part?

**Comment by languagelawyer** [comment]
http://eel.is/c++draft/basic.lval#def:result,glvalue, as usual

**Comment by jensmaurer** [comment]
We seem to be not-quite-good with "result" throughout [expr], due to historical reasons.

**Comment by languagelawyer** [comment]
Requests to fix such misuses are no (longer) accepted?

**Comment by jensmaurer** [comment]
Sure. A specific suggestion is appreciated.

**Comment by tkoeppe** [comment]
Is the lack of type specification actually a problem, does it cause ambiguities? I'm not opposed to elaborating that, but I'd like to see a little more motivation.

**Comment by jensmaurer** [comment]
@tkoeppe, every operator used to construct compound expressions should specify what type and value category the resulting compound expression has, and (when evaluated) what the value resulting from the operation is (plus any side effects etc.)

For assignment, we're lacking on the "type" part, which is simply a specification oversight / inconsistency. There's nothing ambiguous here.

**Comment by tkoeppe** [comment]
OK -- "omitted by oversight, inconsistent with other operator specifications" would be sufficient motivation. I'd welcome if that were part of the initial issue report.
