### ISSUE TITLE
[dcl.fct.def.coroutine] p13 A valid reference type is not cv-qualified

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4868]
> When a coroutine is invoked, after initializing its parameters ([expr.call]), a copy is created for each coroutine parameter. For a parameter of type **cv T**, the copy is a variable of type cv T with automatic storage duration that is direct-initialized from an xvalue of type T referring to the parameter.

When the parameter has a reference type, `cv T` is the wrong exposition.  Maybe, we could say

> When a coroutine is invoked, after initializing its parameters ([expr.call]), a copy is created for each coroutine parameter. For a parameter of type **cv T or of type reference to cv T**, the copy is a variable of the **corresponding type** with automatic storage duration that is direct-initialized from an xvalue of type T referring to the parameter.

**Comment by jensmaurer** [comment]
If T is a reference type, then "cv" is simply empty (because references cannot be cv-qualified). I'm not seeing a problem here.

**Comment by xmh0511** [comment]
If `T` is an lvalue reference type, how could an expression be an **xvalue** of an lvalue reference type?

**Comment by jensmaurer** [comment]
That's a valid point, but unrelated to the subject of this issue, which talks about cv-qualification.

**Comment by xmh0511** [comment]
Well, actually this issue has two concerns here. I will post a new issue about the second one. This should be closed.
