### ISSUE TITLE
[format.syn] A wrong exposition for std::format definition

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4877]
The definition for std::format is as the following
````cpp
template<class... Args>
string format(format-string<Args...> fmt, const Args&... args);

template<class... Args>
wstring format(wformat-string<Args...> fmt, const Args&... args);
// .....
````
In this definition, the `format-string` or `wformat-string` is an alias template, defined as the following
````cpp
template<class... Args>
using format-string =   basic-format-string<char, type_identity_t<Args>...>;                      // exposition only
      
template<class... Args>
using wformat-string =  basic-format-string<wchar_t, type_identity_t<Args>...>;                            // exposition only
     
````
where `basic-format-string` is a class template, It arguably says the first parameters of `std::formart` in this two cases are class template specialization. We also gives a simple use of `std::format` in the subsequent clauses, which is 
````cpp
string s0 = format("{} to {}",   "a", "b"); // OK, automatic indexing

````
The first argument has an array type, in template function call deduction, it is decayed to a pointer to participate the deduction, which means  `basic-format-string<char, type_identity_t<Args>...>` will compare with `pointer to const char`, as per [temp.deduct.type#2], the deduction on this pair cannot be done. The deduction will fail.

**Comment by CaseyCarter** [comment]
There is nothing to deduce in `basic-format-string<char, type_identity_t<Args>...>` (ditto for the `wchar_t` case): the `Args` are wrapped in `type_identity_t` specifically so they will be non-deducible. FTAD then only deduces `Args` from the other arguments - as intended - which is enough to fully specify the specialization of `basic-format-string` used for either `format` overload.

**Comment by xmh0511** [comment]
Ah, `type_identity_t` is a non-deduced context.
