### ISSUE TITLE
"Expression" column in tables

### ISSUE THREAD

**Issue by FrankHB** [cplusplus/draft#488]
The title of first column in many tables (about requirements) are named "Expression", which is not consistent with the contents, i.e. many of them are not expressions at all, but declarations or statements. For example, in N4431 Table 19 ([defaultconstructible]), `T t;` is obviously not an expression. The title of column should be renamed to better reflect the intent.

**Comment by jensmaurer** [comment]
Any proposal instead of "Expression"?
Type \newline Expression ?

**Comment by zygoloid** [comment]
This will be fixed by issue#78.
