### ISSUE TITLE
[expr.dynamic.cast] Missing case when `C` is the most derived class in the runtime check

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#4887]
See https://eel.is/c++draft/expr.dynamic.cast#7 and https://eel.is/c++draft/expr.dynamic.cast#8. In the runtime check, `C` is always the type of a base class subobject of the most derived object. The case when `T` is the most derived class is not specified.

**Comment by JohelEGP** [comment]
Only when "v is the same as T (ignoring cv-qualifications)", which might not be the case if `v` is a base class subobject of `C`.

**Comment by xmh0511** [comment]
I think it is covered by [expr.dynamic.cast#8.1], namely `T` is the type of the most derived object while the `v` is a subobject thereof.
> If, in the most derived object pointed (referred) to by v, v points (refers) to a public base class subobject of a C object, and if only one object of type C is derived from the subobject pointed (referred) to by v the result points (refers) to that C object.

C may be the type of the most derived object or the one base class subobject of which the v is a subobject.

**Comment by JohelEGP** [comment]
Thank you, that's right.
