### ISSUE TITLE
[dcl.init.aggr] Example 3 continues list of normative text

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#4891]
See https://eel.is/c++draft/dcl.init.aggr#example-3.
![1631306161](https://user-images.githubusercontent.com/21071787/132915104-d42737e8-4df9-436e-8ba6-f0380b6faad4.png)

**Comment by jensmaurer** [comment]
We could make the example a separate paragraph to avoid the contiguous numbering of distinct bulleted lists.
