### ISSUE TITLE
[dcl.spec.auto.general] Definition of _generic parameter type placeholder_ can be simplified

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#4904]
The paragraph in question, [p2](https://eel.is/c++draft/dcl.spec.auto.general#2), lists two places in the grammar where a _placeholder-type-specifier_ of the form _type-constraint_<sub>opt</sub> `auto` can appear. It leaves one unused and defines a name for the other.

The two are mutually exclusive:
- a decl-specifier of the decl-specifier-seq of a parameter-declaration of a function declaration or lambda-expression (the grammar for parameters), and
- the auto type-specifier introducing a trailing-return-type (the grammar for the return type).

All the paragraph does is define a name for the former. The latter, redundantly excluded, also complicates the surrounding wording which could otherwise read simpler.

Note that this might be concurrently modified, as the paragraph or its subclause seem to have more problems as pointed out at https://bugs.llvm.org/show_bug.cgi?id=51856#c3.

**Comment by xmh0511** [comment]
[dcl.spec.auto.general] p2 is basically discussing the placeholder types of the parameters of a function or lambda. It simply says "auto type-specifier introducing a trailing-return-type" is not considered as a generic parameter type placeholder. I think they are not redundant and it is significant to clarify which placeholder types can be a generic parameter type placeholders.

**Comment by JohelEGP** [comment]
But can the "auto type-specifier introducing a trailing-return-type" be "a decl-specifier of the decl-specifier-seq of a parameter-declaration of a function declaration or lambda-expression"? It reads to me as if "the auto in 'auto f() -> T' appears in the declaration of a parameter". Could it be to account for a case like
```C++
auto f(auto(*)()->int) -> int;
```

**Comment by JohelEGP** [comment]
Thank you. So the intention is to prevent `g` in `auto f(auto(*g)()->int) -> int;` from being a generic parameter type placeholder.
