### ISSUE TITLE
Get rid of Notes: elements in library clauses

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#492]
17.5.1.4 [structure.specifications] defines what a _Notes:_ element means in the detailed specification for a function.

The only correct use of this in the entire standard is 20.12.5.7 [time.duration.cast] (which is missing a paragraph number! it should be paragraph 3).

23.2.1 [container.requirements.general] p4 has a "Notes:" following table 96 but it's not the same thing, because it's not italicized, and isn't a detailed specification where [structure.specifications] applies (so just seems wrong to me, maybe it should be "[Note: the algorithm equal() is defined in Clause 25.]"

Daniel added:

> There exits some incorrectly spelled "Notes:" written as "Note:" such
> as in 20.4.2.4p13, [tuple.elem] p4, [unique.ptr.single.observers] p5
> and maybe elsewhere, but I don't really like this additional flavour
> of notes and would happily replace them all by our usual [Note: - end
> note]

**Comment by jensmaurer** [comment]
With the Parallelism TS merged, we now have a few more Notes: items. I'll prepare a patch to replace all of them with the regular "[ Note: ... -- end note ]" phrasing.
