### ISSUE TITLE
[class.copy.elision] p2 incorrect comment in copy elision example

### ISSUE THREAD

**Issue by RazvanAM** [cplusplus/draft#4926]
Paragraph 2 of [class.copy.elision] (https://eel.is/c++draft/class.copy.elision#2) contains the following example:

```
[...]

constexpr A g() {
  A loc;
  return loc;
}

constexpr A a;          // well-formed, a.p points to a
constexpr A b = g();    // error: b.p would be dangling ([expr.const])

void h() {
  A c = g();            // well-formed, c.p may point to c or to an ephemeral temporary
}
```

I believe the comment "well-formed, c.p may point to c or to an ephemeral temporary" is not entirely correct, because there is no temporary in this scenario.

This comment was originally added with the resolution of [CWG2002](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2022). The example used in that resolution was:
```
[...]

struct A {
    void *p;
    constexpr A(): p(this) {}
  };

  constexpr A a;        // well-formed, a.p points to a
  constexpr A b = A();  // well-formed, b.p points to b

  void g() {
    A c = A();          // well-formed, c.p may point to c or to an ephemeral temporary
  }
```
In this resolution the comment "well-formed, c.p may point to c or to an ephemeral temporary" correctly reflects the code.

After the resolution of [CWG2002](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2022) the code in the example was modified in [95321805a3](https://github.com/cplusplus/draft/commit/95321805a3528aa1006bf8187e39e1f4bab00c1e), but the comment was not changed to reflect this.

**Comment by xmh0511** [comment]
Agree that comment is not correct. Since both [class.copy.elision]p1 and [expr.const] p1 says

> Copy elision **is not permitted** where an expression is evaluated in a context requiring a constant expression ([expr.const]) and in constant initialization ([basic.start.static]).  

Hence, for `A c = g(); `, c.p may point to `loc`, or point to an ephemeral temporary as per [class.temporary] p3, is determined by which initializer expression performs the copy-initialization of `c`.

**Comment by jensmaurer** [comment]
There is no temporary here; the result of `g()` is an rvalue whose target object is c.

**Comment by xmh0511** [comment]
> When an object of class type X is passed to or returned from a function, if X has at least one eligible copy or move constructor ([special]), each such constructor is trivial, and the destructor of X is either trivial or deleted, **implementations are permitted to create a temporary object to hold the function parameter or result object**. The temporary object is constructed from the function argument or return value, respectively, and the function's parameter or return object is initialized as if by using the eligible trivial constructor to copy the temporary (even if that constructor is inaccessible or would not be selected by overload resolution to perform a copy or move of the object).

There can have a temporary here.

**Comment by jensmaurer** [comment]
Good point.
