### ISSUE TITLE
[expr.context] List of back references crossreference the parent subclause

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#4936]
![1632618708](https://user-images.githubusercontent.com/21071787/134789769-dc433748-2cc1-4e55-ac47-35f28c6234df.png)
All but the last two crossreference the parent subclause [expr.prop], with two sibling subclauses in-between.

**Comment by jensmaurer** [comment]
Sorry, I can't parse the sentence "All but the last two crossreference the parent subclause [expr.prop], with two sibling subclauses in-between." Could you try again, please?

**Comment by JohelEGP** [comment]
I'm using crossreference as a verb here. The list of references in the parentheses are uses of the term "unevaluated operand". They are supposed to crossreference [expr.context]. The last two in the list do, but not the rest, which instead crossreference the parent subclause. Those that crossreference the parent subclause of [expr.context], which is a .3 leaf subclause, have an error of two (lengthy) subclauses from the actual reference to the intended reference.

**Comment by jensmaurer** [comment]
Thanks.

**Comment by jensmaurer** [comment]
So, in order to improve the general situation, we need a `\label{term.unevaluated.operand}` at the point where we define it, and then we can just `\iref{term.unevaluated.operand}` where we want to refer to the section number.
