### ISSUE TITLE
[iostream.forward.overview] Notezilla

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#494]
The LWG chair requests that an editorial assistant with library knowledge takes a look at the monster note in 27.3 [iostream.forward], which has been sleeping somewhere deep in the ocean since the '98 standard.

**Comment by tkoeppe** [comment]
Could you clarify which note you have in mind? Is it all of [iostream.forward.overview]? @jensmaurer, does the issue description need to be updated?

**Comment by jwakely** [comment]
Ah yes, there's a new stable name thanks to #1231 

Yes, the note in question is the one that now forms the entirety of [iostream.forward.overview] - title updated.

**Comment by jwakely** [comment]
The problem is that 27.3.2 is nothing but a huge note, so the entire subclause is non-normative.

**Comment by jensmaurer** [comment]
Right, but what's the problem? In other places, we have the intro text as "normative" text without differentiation. Here, we have it in a nice note. We could split the note in two to split off p9, which is a different topic than the intro in p1-p8. Other than killing the note entirely (at least p1-p8), I have no idea where to go here.

**Comment by jwakely** [comment]
I agree that p9 definitely belongs in a note. Arguably the rest could be normative text, even though it doesn't say anything of substance. It would be consistent with other library clauses to have that introductory text as normative (non-note) wording. Would making non-normative wording normative be editorial though? Strictly speaking, probably not.
I don't know how strongly @mclow feels about it, but I opened this issue in response to LWG's bewilderment at finding such a big note.

**Comment by sigfpe** [comment]
Agreed, not a good idea to kill the note.
Making the rest a non-normative change is a change to the standards, so
would required WG21 vote.

**Comment by jensmaurer** [comment]
@jwakely: As long as the effect of the standard's words doesn't change, it's editorial fair game, as far as I understand. So, we could editorially turn the first part into normative text (as long as it's semantically correct).
