### ISSUE TITLE
[class] (9)/7.8 has ambiguous wording

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#496]
> If `X` is a non-union class type, the set `M(X)` is empty if `X` has no (possibly inherited (Clause 10)) non-static data members; otherwise, it consists of the type of the first non-static data member of `X` (where said member may be an anonymous union), `X0`, and the elements of `M(X0)`.

would be clearer as something like:

> If `X` is a non-union class type with no (possibly inherited (Clause 10)) non-static data members, the set `M(X)` is empty.
> If `X` is a non-union class type with first non-static data member `X0` (where said member may be an anonymous union), the set `M(X)` consists of `X0` and the elements of `M(X0)`.

**Comment by tkoeppe** [comment]
@zygoloid: This looks like something for you.
