### ISSUE TITLE
Editorial: "sub-clause" vs "subclause"

### ISSUE THREAD

**Issue by mclow** [cplusplus/draft#497]
The standard uses the term "subclause" 107 times, and "sub-clause" 7 times.
_It also uses "section" 102 times_.

At the very least, the uses of "sub-clause" should be changed to "subclause", but changing the mentions of "section" might be considered as well.

**Comment by payload** [comment]
For the "section" case, there is only `section~\ref`, never `Section~\ref` and once `Sections~\ref`. You can use `grep -hosP '\b(-|\w)+~\\ref' *tex | sort -u` to see the situation.

**Comment by jensmaurer** [comment]
See also #307 and #904.
