### ISSUE TITLE
Do not use “must” as an alternative for “shall”

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#501]
ISO standards use "shall" and not "must" to express requirements. However it seems that the current draft sometimes uses "must" to introduce a requirement.

For example, 14.2[temp.name]p4 says

> When the name of a member template specialization appears after . or -> in a postfix-expression or after a nested-name-specifier in a qualified-id, and the object expression of the postfix-expression is type-dependent or the nested-name-specifier in the qualified-id refers to a dependent type, but the name is not a member of the current instantiation (14.6.2.1), the member template name **must** be prefixed by the keyword template. Otherwise the name is assumed to name a non-template.

If the intent is really to introduce a requirement, the verb "shall", instead of "must", should be used.

**Comment by tvaneerd-rim** [comment]
If the intent is really to introduce a requirement, the verb "shall", instead of "must", <del>should</del><ins>must</ins> be used.

:-)

**Comment by zygoloid** [comment]
I agree that something should change here, but I don't think replacing 'must' with 'shall' is a complete solution. The next sentence says that the program is not ill-formed in the case where the `template` keyword is missing; instead, it is interpreted in a different way. It's possible that we could fix this by changing the 'must' to a 'shall' and deleting the following sentence.

We should come up with a specific proposed change here and check with CWG before applying it.

**Comment by cpplearner** [comment]
[temp.name] is just an example. I noted that it's wording will be changed if [CWG issue 1710](http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2015/n4457.html#1710) is adopted. But there are several other places that uses "must" where the verb "shall" seems more appropriate. As another example, 18.6.1.2 [new.delete.array]p12 says
>Requires: If present, the `std::size_t` `size` argument **must** equal the size argument passed to the
allocation function that returned `ptr`.

**Comment by jensmaurer** [comment]
I would prefer to address the "must"s on a more individual basis, to ease review. We probably don't want to address "must" in notes and example, for instance. Please create individual editorial issues, one for each section with a specific issue you want to have fixed.

As an example, #493 highlights a specific issue.
