### ISSUE TITLE
[over.best.ics] Minor reading improvements

### ISSUE THREAD

**Issue by dangelog** [cplusplus/draft#5023]
The end of https://eel.is/c++draft/over.best.ics#over.ics.list-8 says:

> [...] the implicit conversion sequence is a user-defined conversion sequence with the second standard conversion sequence an identity conversion. 

Could it be possible to rephrase this sentence like this:

> [...] the implicit conversion sequence is a user-defined conversion sequence with the second standard conversion sequence **_being_** an identity conversion.

?

I personally think it would bring more clarity, and be less hostile to be parsed by human beings -- there's no verb apart from "is".  In another related paragraph, an extra verb is actually already there: https://eel.is/c++draft/over.best.ics#over.ics.list-2.sentence-1

> in which case the implicit conversion sequence is a user-defined conversion sequence whose second standard conversion sequence **_is_** an identity conversion.

The same kind of change (adding a second verb such as "being", or using a relative sentence) could also be applied in another couple of places:

https://eel.is/c++draft/over.best.ics#over.ics.ref-1.sentence-2
https://eel.is/c++draft/over.best.ics#over.ics.list-7.2.sentence-1

**Comment by jensmaurer** [comment]
I like "whose second standard conversion sequence is ..." instead of adding "being".

**Comment by dangelog** [comment]
Sure, that sounds fine by me.
