### ISSUE TITLE
[iostreams] Make "sentry" object code font throughout

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#5031]
We have a class called "sentry", so it should be in code font. (It's not just any class that people might claim acts as a sentry in the plain English meaning.)

**Comment by jwakely** [comment]
It's not. Some non-code-font uses are just inconsistent/wrong, e.g. [istream.unformatted] p1 where we're specifically talking about the `sentry` class, so "the sentry constructor" should obviously be code font too. It's the constructor of the `sentry` object introduced earlier in the paragraph.

Other cases just seem like inconsistencies. [istream.extractors] p12 says "After a `sentry` object is constructed" and p14 says "After a sentry object is constructed". There is no difference intended here, they should be consistent. Both are referring to the actions of constructing a `sentry` as specified by [istream.unformatted] p1.

We could introduce wording that says "The object of type `sentry` is referred to as the sentry object" in two places (one of istream and one for ostream) but it seems simpler to just use code font everywhere. I checked every case in Clause 29 [input.output] and they should all be code font.
