### ISSUE TITLE
Wording for how "a contained value is initialized" could be simplified

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#5038]
From P078R8:

This _is_ the wording from the paper, but "whose contained value is direct-non-list-initialized with `invoke(std::forward<F>(f), value())`" would be clearer. LWG made a similar clarification to the `expected` paper recently. Similarly applies to lines 3512-3514.

_Originally posted by @CaseyCarter in https://github.com/cplusplus/draft/pull/5014#r727405883_

If there is a simpler expression, we should apply it to all the `optional` wording.

**Comment by jwakely** [comment]
> If there is a simpler expression, we should apply it to all the `optional` wording.

Yes, that's the plan.
