### ISSUE TITLE
Inconsistent formatting of "cv-qualified"

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#504]
The standard contains uses of "cv-qualified", "_cv_-qualified", and even a few "_cv-qualified_"s.

"_cv-qualified_" should be used only when defining a term. "_cv_-qualified" should probably never be used (except possibly in the case where we're referring to some specific set of cv-qualifiers that we're naming _cv_, per [basic.type.qualifier]/5).

**Comment by jensmaurer** [comment]
Duplicate of #798.
