### ISSUE TITLE
[expos.only.func] Should we move decay-copy to [range.adaptors.general] ?

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#5044]
After adopting P0849R8 and P2321R2 (with some editorial changes), only range adaptor objects `views::all`, `views::take`, and `views::drop` are still specified via _`decay-copy`_. So perhaps it's OK to move _`decay-copy`_ to [[range.adaptors.general]](https://eel.is/c++draft/range.adaptors.general).

**Comment by tkoeppe** [comment]
Oh, that's subtle -- thanks! Does that make a difference in the library?
