### ISSUE TITLE
Nit: "standard layout" vs. "standard-layout"

### ISSUE THREAD

**Issue by mclow** [cplusplus/draft#506]
There are three instances of the first term (all in 29.5), and 50 of the second.

Suggest settling on one or the other - to make my searching easier :-)

**Comment by duckie** [comment]
Even though there is less occurences of it, "standard layout" without the dash makes more sense to me. But maybe there is a reason for the other one to be widely spread in the draft.

**Comment by cpplearner** [comment]
AFAIK, ISO C++ only defines "standard-layout type", "standard-layout class", "standard-layout struct" and "standard-layout union". It doesn't define the meaning of the phrase "have standard layout", but this phrase is used in N4527 §29.5[atomics.types.generic]p5&6 and §29.7[atomics.ﬂag]p3. 

I think it's safe to replace "have standard layout" with "be standard-layout structs". According to [N2427](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2427.html), this matches the original intent.

Incidentally, the sentense "They shall each support aggregate initialization syntax." in §29.5 is also problematic: `std::atomic<T>` doesn't seem to be a aggregate, as it has a user-provided constructor `constexpr atomic(T) noexcept`. This might need to be a non-editorial issue....

**Comment by jensmaurer** [comment]
"Incidentally, the sentense "They shall each support aggregate initialization syntax." in §29.5 is also problematic: std::atomic<T> doesn't seem to be a aggregate, as it has a user-provided constructor constexpr atomic(T) noexcept."

With list-initialization, we already support "aggregate initialization syntax" here, even when the class has a constructor. That said, the requirement seems to be totally vacuous given the synopsis.

**Comment by tkoeppe** [comment]
See also [LWG 2715](http://wg21.link/lwg2715) for discussion on the (meaningless) phrase "aggregate initialization syntax".

@mclow: If the LWG issue was resolved as editorial, can you please either update and reopen this issue or create a new issue on GitHub? I will merge PR #1021 for now.
