### ISSUE TITLE
Mix of "see" and page numbers in the same index entry

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#5061]
![image](https://user-images.githubusercontent.com/10905931/138369106-43f1058c-601d-4940-a9b5-664a3dfa6e46.png)

These look really odd, not the least because the "see" happens in the middle of a long list of page numbers.

It looks like the "multiple encaps" warnings in `std-generalindex.ilg` can be used to detect these. (But that same warning is benign in other indices where we intentionally format one of the page numbers in bold.)

**Comment by tkoeppe** [comment]
Can we try making `\keyword{foo}` emit an index entry "`foo` (keyword)"?

**Comment by tkoeppe** [comment]
Or alternatively:

     char32_t:
         see type, char32_t
         (as keyword): 12, 23, 34, 56
