### ISSUE TITLE
[basic.indet][bit.cast] Why "unsigned ordinary character"?

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#5070]
As `char` is not considered as an unsigned integer type even if `std::is_unsigned_v<char>` is `true`, can we replace all uses of "unsigned ordinary character" with `unsigned char`?

**Comment by jensmaurer** [comment]
http://lists.isocpp.org/core/2021/11/11656.php

**Comment by Eisenwave** [comment]
> http://lists.isocpp.org/core/2021/11/11656.php

@jensmaurer is there a publicly accessible link to that issue?

**Comment by Eisenwave** [comment]
Related: https://github.com/cplusplus/CWG/issues/403

**Comment by tkoeppe** [comment]
@Eisenwave I think that email is just a restatement of the problem, presumably with the intention of creating a CWG issue (@jensmaurer?). So let's close this.
