### ISSUE TITLE
[basic.link]/10 definition of "attached to module" is redunant and circular

### ISSUE THREAD

**Issue by RedBeard0531** [cplusplus/draft#5082]
https://eel.is/c++draft/basic.link#10
> If two declarations of an entity are attached to different modules, the program is ill-formed; no diagnostic is required if neither is reachable from the other. [...] As a consequence of these rules, all declarations of an entity are attached to the same module; the entity is said to be _attached_ to that module.

That basically seems to be saying that an entity is said to be attached to a module if it is attached to that module...

We have another definition of attachment at https://eel.is/c++draft/module.unit#7, so maybe it would be best to remove the part of [basic.link]/10 after the semicolon. If the definition in [basic.link] is trying to expand the concept from a declaration to an entity, and we think that distinction is important, it seems clearer to me to expand the wording in [module.unit] to say something like an entity is attached to whichever module the declaration that declares it is attached to.

**Comment by jensmaurer** [comment]
@RedBeard0531 , we have "declaration attached to a module" in [module.unit] p7 and we have "entity attached to a module" in [basic.link] p10. Those are different things, nothing circular here.
