### ISSUE TITLE
[dcl.fct.def.coroutine] mention of `*this` does not make sense after P0847R7 CWG2754

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#5085]
[\[dcl.fct.def.coroutine\]/4](http://eel.is/c++draft/dcl.fct.def.coroutine#4.sentence-2):

> For a non-static member function, q<sub>1</sub> is an lvalue that denotes `*this`; any other q<sub>i</sub> is an lvalue that denotes the parameter copy corresponding to p<sub>i</sub>, as described below.

P0847R7 (69392bf28731ada3dbaebe600401b6ccc9f5fa58) adds explicit object member functions, which are non-static member functions but don't have `this`. The definition of q<sub>1</sub> does not make sense in this case.

The proposed wording in P0847R7 does not contain this sentence, probably because the sentence was added by CWG2465 (8a70399af20bf0b289196d10967590b3a036d2c0), which is fairly recent.

**Comment by jensmaurer** [comment]
This should read "implicit object member function", I think.

**Comment by frederick-vs-ja** [comment]
This is now CWG2754.
