### ISSUE TITLE
Nit: value of some object <ins>of</ins> type T

### ISSUE THREAD

**Issue by tvaneerd-rim** [cplusplus/draft#509]
24.2.1 In general
    All input iterators i support the expression *i, resulting in a value of some object type T, called the value type of the iterator.

I think you need an 'of' there

    All input iterators i support the expression *i, resulting in a value of some object <ins>of</ins> type T, called the value type of the iterator.

**Comment by zygoloid** [comment]
The existing text is correct; see the definition of "object type" in 3.9/8.

**Comment by tvaneerd-rim** [comment]
agreed
