### ISSUE TITLE
[except.throw] doesn't specify the type of the lvalue denoting the exception object

### ISSUE THREAD

**Issue by languagelawyer** [cplusplus/draft#5091]
[except.throw]/3:
> Throwing an exception copy-initializes a temporary object, called the _exception object_.
> An lvalue denoting the temporary is used to initialize the variable declared in the matching handler  ([except.handle]).

Is there any wording defining the type of this lvalue? Also, https://timsong-cpp.github.io/cppwp/except.handle#14 is worded in terms of initialization from object, not expression. Does it need a separate issue?

**Comment by jensmaurer** [comment]
At least [expr.throw] clearly says what the type of the exception object is. Can you find other situations where we fail to say what the type of the exception object is?
