### ISSUE TITLE
[intro.refs] 3 ISO/IEC 9945:2003

### ISSUE THREAD

**Issue by kynowoo** [cplusplus/draft#5098]
I find an inconsistency that the year of the standard "ISO/IEC 9945:2003" in the term intro.refs[3] is not the same with those  "ISO/IEC 9945:2009"s in the term intro.refs[1.4][1.5][1.6]. 
Is it intended or maybe an overlook?

**Comment by jwakely** [comment]
That's my fault, it should have been changed by https://wg21.link/p2227 which was applied to the draft as #4321
