### ISSUE TITLE
value-initialized and value initializing

### ISSUE THREAD

**Issue by tvaneerd** [cplusplus/draft#510]
Almost everywhere we use a hyphen for
- value-initialization
- value-initialized
- value-initializes
  (etc?)

But in a few places, we drop the hyphen
Locations:
- 20.4.2.1.5  tuple() constructor
- 23.2.1.8 container requirements note about allocators 
- 24,2,5,2 Forward iterators
- 24.5.1.3.1 reverse_iterator()
- 24.5.3.3.1 move_iterator()

**Comment by tkoeppe** [comment]
Make a pull request! :-)
