### ISSUE TITLE
[dcl.typedef] p2 Unexplained lookup "error" in example

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#5107]
```
using cell = pair<void*, cell*>;    // error
```

Two issues: `pair` is undefined here (is it `std::pair`?) and the error is unexplained.
The explanation for the error is in [basic.scope.pdecl] p4:

> The locus of a _using-declarator_ that does not name a constructor is immediately after the _using-declarator_ (9.9).

Source: Vladimir Grigoriev on std-discussion 2021-11-13

**Comment by xmh0511** [comment]
It seems there is nothing related to `using-declarator` since the declaration is not a `using-declaration`; it's just an alias-declaration.

**Comment by jensmaurer** [comment]
Oh, right, seems I was confused.
