### ISSUE TITLE
[version.syn] Use a digit separator to split the year and the month

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#5109]
A naive attempt doesn't work in LaTeX:
![1636995164](https://user-images.githubusercontent.com/21071787/141821777-e2d38975-caae-42cd-8579-67dcfb1f48d0.png)
Even then, I find the dates look better:
Before:
![a](https://user-images.githubusercontent.com/21071787/141823061-e28601ec-5656-4a38-a188-452ef98fac5a.png)
After:
![b](https://user-images.githubusercontent.com/21071787/141823065-8cf0fe98-68c1-4eb0-a943-5b9b3520bd48.png)

**Comment by jensmaurer** [comment]
@tkoeppe , this looks like an improvement to me (modulo `codeblock` magic that we need to prevent, of course)

**Comment by tkoeppe** [comment]
Yes, I agree. This looks good. We'll work out how to implement it properly.

**Comment by jensmaurer** [comment]
We should tell the "codeblock" environment not to consider `'` a character literal introducer.

**Comment by tkoeppe** [comment]
Or we can at least make a specialized environment that has this property, if necessary.

**Comment by jensmaurer** [comment]
Not editorial, as shown in #5117.
