### ISSUE TITLE
[temp.deduct.general]/p7 should exclude exception specifications CWG2618

### ISSUE THREAD

**Issue by cmeerw** [cplusplus/draft#5129]
[[temp.deduct.general]/p7](http://eel.is/c++draft/temp#deduct.general-7) currently says

> The substitution occurs in all types and expressions that are used in the function type and in template parameter declarations.

This should exclude exceptions specifications (since C++17) as we have a note saying:

> The equivalent substitution in exception specifications is done only when the noexcept-specifier is instantiated, at which point a program is ill-formed if the substitution results in an invalid type or expression.

Should p7 also mention the "explicit-specifier" as p8 then does?

> Only invalid types and expressions in the immediate context of the function type, its template parameter types, and its explicit-specifier can result in a deduction failure.

**Comment by jensmaurer** [comment]
CWG2618
