### ISSUE TITLE
[ranges] Considering adding ExecutionPolicy parameters into std::ranges::for_each

### ISSUE THREAD

**Issue by Jimmy-Hu** [cplusplus/draft#5132]
Hi,

I've checked there is a function overloading with ExecutionPolicy parameters in `std::for_each`:

```C++
template< class ExecutionPolicy, class ForwardIt, class UnaryFunction2 >
void for_each( ExecutionPolicy&& policy, ForwardIt first, ForwardIt last, UnaryFunction2 f );
```

I think that the execution policy parameters can also be added into std::ranges::for_each function and the
following overloading structure can be considered.

```C++
template< class ExecutionPolicy, std::input_iterator I,
std::sentinel_for<I> S, class Proj = std::identity,
std::indirectly_unary_invocable<std::projected<I, Proj>> Fun >
requires (std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>)
constexpr for_each_result<I, Fun>
          for_each( ExecutionPolicy&& policy, I first, S last, Fun f, Proj proj = {} );

template< class ExecutionPolicy, ranges::input_range R, class Proj =std::identity,
std::indirectly_unary_invocable<std::projected<ranges::iterator_t<R>,
Proj>> Fun >
requires (std::is_execution_policy_v<std::remove_cvref_t<ExecutionPolicy>>)
constexpr for_each_result<ranges::borrowed_iterator_t<R>, Fun>
          for_each( ExecutionPolicy&& policy, R&& r, Fun f, Proj proj = {} ); 
```

An advantage of this design is to integrate parallel algorithm into ranges::for_each function.

**Comment by JohelEGP** [comment]
The issue sounds like a proposal. Adding new overloads to `ranges::for_each` is not an editorial issue. I suggest you read the first section of the README for more information on what that might mean.

**Comment by Jimmy-Hu** [comment]
@JohelEGP Thank you for the prompt reply. I've checked the [How to submit a new issue/defect report](https://isocpp.org/std/submit-issue) and [an initial message to std-discussion](https://lists.isocpp.org/std-discussion/2021/11/1521.php). So the next step is to follow the instruction in ["How to submit a core language or standard library issue" section](https://isocpp.org/std/submit-issue)? It's my first time to propose new proposal. Please let me know if there is any misunderstanding. Thank you so much.

**Comment by JohelEGP** [comment]
A linked webpage also has this: https://isocpp.org/std/submit-a-proposal.

**Comment by jwakely** [comment]
You need to submit a proposal. The issue process is for fixing defects. This is not a defect. The lack of parallel overloads for the ranges algo is intentional, not a mistake.

Closing as this is not editorial.
