### ISSUE TITLE
[associative.reqmts.general] introduces `r` with two different meanings

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#5134]
[N4901](https://isocpp.org/files/papers/N4901.pdf) [associative.reqmts.general]/8.13:

> — `r` denotes a valid dereferenceable iterator to `a`,

But then /8.19 through /8.22 introduce `r` with a totally different meaning:

> — `kl` is a value such that `a` is partitioned (25.8) with respect to `c(r, kl)`, with `r` the key value of `e` and `e` in `a`;
> — `ku` is a value such that `a` is partitioned with respect to `!c(ku, r)`;
> — `ke` is a value such that `a` is partitioned with respect to `c(r, ke)` and `!c(ke, r)`, with `c(r, ke)` implying `!c(ke, r)`;
> — `kx` is a value such that
> — `a` is partitioned with respect to `c(r, rx)` and `!c(kx, r)`, with `c(r, kx)` implying `!c(kx, r)`, and
> — `kx` is not convertible to either `iterator` or `const_iterator`; and

This is confusing; a different name should be introduced.

**Comment by jensmaurer** [comment]
Are you saying that all mentions of "r" in p8.19 through p8.22 mean "r" as in "r the key value of e and e in a"?
If so, it's seriously confusing that we introduce "r" only in p8.19 and not with a larger scope.
However, it's obvious that "r" can't have the "iterator" meaning here, because it needs to be of the key_type.

**Comment by StephanTLavavej** [comment]
Yep! It is indeed seriously confusing.

**Comment by jwakely** [comment]
The first `r` in (8.13) was introduced by f03534f6366ef229e67ffa4f3622a11b0d73564 for [LWG 2059](https://wg21.link/lwg2059). It should have been a different name.

It would be a smaller change to rename _that_ one, and the single use of it in the table, `a.erase(r)`.
