### ISSUE TITLE
[fs.class.path.general]Where is section 4.12？

### ISSUE THREAD

**Issue by SainoNamkho** [cplusplus/draft#5137]
Section 4.12 is referred as
> [Example 1: POSIX specifies the mechanism in section 4.12, Pathname resolution. — end example]

[fs.class.path.general](https://eel.is/c++draft/filesystems#fs.class.path.general-6)
but there's no such section 4.12 in the document.
Then what is the section?

**Comment by jwakely** [comment]
Section 4.12 of the POSIX spec referenced in [intro.refs] i.e. ISO/IEC 9945:2009.

**Comment by jwakely** [comment]
Not 4.12 in the C++ standard.

**Comment by SainoNamkho** [comment]
> Section 4.12 of the POSIX spec referenced in [intro.refs] i.e. ISO/IEC 9945:2009.

Thanks a lot!

**Comment by JohelEGP** [comment]
POSIX is the OS described in ISO/IEC 9945:2009. My guess is that 4.12 refers to the section of the document POSIX is described in, namely ISO/IEC 9945:2009. So it's still wrong, although fair enough for a note. But not the fact that the reference is split apart (doesn't follow the convention of "document, section"), which is consufing.

Perhaps other such names introduced in [intro.refs] for things described in a document are similarly wrongly used to refer to its document. If that's done normatively, it requires a revision.
