### ISSUE TITLE
Requirement in [class.union]/2 probably should use "shall"

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/draft#514]
In N4527 subclause 9.5 [class.union] paragraph 2:
A union can have member functions (including constructors and destructors), but not virtual functions.

it may be more appropriate for the "but not" to be changed to:
"but it shall not have".

**Comment by burblebee** [comment]
Fixed in commit 90352854d99ee3e3b2f935bba47c6749365d52d8.

**Comment by hubert-reinterpretcast** [comment]
Looks good. Thanks.
