### ISSUE TITLE
Inconsistent cross-references for array of unknown bound

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#5146]
[range.prim.size] p2 (2.1) says:

> If T is an array of unknown bound ([dcl.array]), ranges​::​size(E) is ill-formed.

But [range.prim.empty] p2 (2.1) says:

> If T is an array of unknown bound ([basic.compound]), ranges​::​empty(E) is ill-formed.

The xref should be the same.

**Comment by CaseyCarter** [comment]
I think both should be cross-referencing [dcl.array].

**Comment by JohelEGP** [comment]
Or a label for "array of unknown bound".

**Comment by jwakely** [comment]
Other adjacent subclauses have references for array types. `ranges::end` has no reference for array of unknown bound.
