### ISSUE TITLE
c plus plus application openSUSE 15.2 cannot find -lmysqlclient_

### ISSUE THREAD

**Issue by sepideh4330** [cplusplus/draft#5161]
my c++ application was working perfectly fine in openSUSE 13.2 but since I updated my operating system to openSUSE 15.2 I have encountered an error during the compilation time which is "cannot find -lmysqlclient_r"

**Comment by jensmaurer** [comment]
This issue tracker is for editorial issues in the ISO C++ standard.

It is not a general C++ help desk; please consult stackoverflow.com or similar venues.

**Comment by sepideh4330** [comment]
ok thanks
