### ISSUE TITLE
[temp.res.general]/1 What does "is or is reachable" mean?

### ISSUE THREAD

**Issue by CaseyCarter** [cplusplus/draft#5189]
The first sentence of the cited paragraph (which was merged verbatim from P1787R6 "Declarations and where to find them") is:

> A name that appears in a declaration $D$ of a template $T$ is looked up from where it appears in an unspecified declaration of $T$ that is or is reachable from $D$ and from which no other declaration of $T$ that contains the usage of the name is reachable.

Is "A declaration of $T$ that is" an incredibly awkard way to say "any declaration of $T$"? Or should "is or" be struck from this sentence?

**Comment by CaseyCarter** [comment]
@opensdh, any thoughts (or prayers)?

**Comment by opensdh** [comment]
It means "that is _D_ or is reachable from _D_".

**Comment by xmh0511** [comment]
@CaseyCarter @opensdh  At the first glance of this sentence, it's hard to read. Fortunately, [temp.over.link.example] p3 has great help to understand the meaning. 
````cpp
template <class T> decltype(g(T())) h();
int g(int);
template <class T> decltype(g(T())) h()         // redeclaration of h() uses the earlier lookup…
  { return g(T()); }                            // … although the lookup here does find g(int)
int i = h<int>();                               // template argument substitution fails; g(int)
                                                // not considered at the first declaration of h()
````

**Comment by CaseyCarter** [comment]
Would anyone object to changing this sentence to:
```diff
 A name that appears in a declaration $D$ of a template $T$ is looked up from where it appears in an unspecified
 declaration of $T$ that is
+either $D$ itself
 or is reachable from $D$ and from which no other declaration of $T$ that contains the usage
 of the name is reachable.
```
which I think preserves the intended meaning but would have been easier for me to decode?

**Comment by opensdh** [comment]
> Give a man a clarification and he reads for a day.  Teach a man to parse arbitrary grammatical English sentences and he reads for a lifetime.

(Other than that, no.)

**Comment by jensmaurer** [comment]
> Give a man a clarification and he reads for a day. Teach a man to parse arbitrary grammatical English sentences and he reads for a lifetime.

What about women?

**Comment by opensdh** [comment]
The [received wisdom](https://en.wiktionary.org/wiki/give_a_man_a_fish_and_you_feed_him_for_a_day;_teach_a_man_to_fish_and_you_feed_him_for_a_lifetime) addresses only the adult male case.  I suspect women are also capable of eating and catching fish, but since I was stretching the saying already by applying it to reading, I didn't want to press my luck by assuming.
