### ISSUE TITLE
erroneous sentence in [dcl.decl] p5

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#519]
[dcl.decl] p5 says

> The _type-id_ in a _trailing-return-type_ includes the longest possible sequence of _abstract-declarator_s.

However, the grammar of _trailing-return-type_ (which is " **->** _trailing-type-speciﬁer-seq_ _abstract-declarator_<sub>opt</sub>") does not contain a _type-id_.

Moreover, I cannot find any ambiguity in the accompanying example. Perhaps this disambiguation rule is no longer necessary after the adoption of [CWG 681](http://www.open-std.org/JTC1/SC22/WG21/docs/cwg_defects.html).

**Comment by zygoloid** [comment]
I agree that both the normative text and the example are wrong. It does look like the disambiguation rule is no longer needed, but removing a normative rule (even one that we believe has no effect) is non-editorial. I'll forward this to CWG.

**Comment by cpplearner** [comment]
Fixed by [CWG 2040](http://wg21.link/cwg2040).
