### ISSUE TITLE
Inconsistent null values throughout the draft

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#52]
From an email to cxxeditor@ (and pointed out by various people in the past):

I noticed following inconsistent usage of null and NULL in the current C++ standard (checked against N3337)

20.7.2.2.1/16 Uses NULL when i think it should be null to be consistent.
20.8.11.2.1/8 Same issue.

20.8.11.2.1/15 & 22 Uses NULL to compare where in other places in the std 0 and nullptr are used.

For example
    20.7.1.2.5 compares against nullptr
    20.7.2.2.1/22 compares against 0 (there are many more such)

There are many other NULL uses in the standard that are not clear that they should be NULL.

**Comment by tkoeppe** [comment]
Does that fix this issue? Can it be closed?
