### ISSUE TITLE
[editoral] the ambiguity in [stmt.return] p4

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#5215]
[stmt.return] p4 says: 
> Otherwise, flowing off the end of a function other than main or a coroutine results in undefined behavior.

It seems the sentence can be read as two meanings, which are: 
> - flowing off the end of a function other than **(main or a coroutine)** results in undefined behavior.
> - flowing off the end of a function other than main or flowing off the end of a coroutine results in undefined behavior. 

we can infer that the second one is a wrong interpretation but this is based on that we get the clue after reading [dcl.fct.def.coroutine] p11.

**Comment by jwakely** [comment]
They mean the same thing. A coroutine is a function, so it doesn't matter if you group "a coroutine" with "a function" or not.

**Comment by jwakely** [comment]
I think it doesn't matter which way you parse it, it means the same thing.

**Comment by xmh0511** [comment]
> I think it doesn't matter which way you parse it, it means the same thing.

Uh, Do you think 
> flowing off the end of a function that is neither `main` nor a coroutine results in UB

has the same meaning with

> flowing off the end of a function that is not `main`, or flowing off the end of a coroutine, results in UB

?  The latter obviously conflicts with [dcl.fct.def.coroutine] p11

> The coroutine state is destroyed when control flows off the end of the coroutine

**Comment by jwakely** [comment]
Doh, I implicitly negated the coroutine part, sorry. I need to learn to read.

I think your rephrasing as "a function that is neither main nor a coroutine" would be an improvement.
