### ISSUE TITLE
P2416 Inconsistent wording in the requirements for expressions

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#5233]
As LWG has approved P2416, I think some issues may be reported here.

----
Currently there are two inconsistent styles used in "_Result_:" when presenting requirements for expressions:
- an lvalue of type `T`/a prvalue of type `T`, and
- `T&`/`T`,

where `T` is an object type in either case.
IMO we should only use one style to present the requirements for expressions, because a simple `T` might be ambiguous. Persumably a simple `T` is requiring that the expression is a prvalue of `T`.

----
Some requirements are specified by the undefined element "_Return type_:" (see also [LWG2819](https://cplusplus.github.io/LWG/issue2819)) in P2416R1. I think they should be specified by "_Result_:".

**Comment by jensmaurer** [comment]
Both have been noticed by LWG and are fixed in the latest revision.
[d2416r2.pdf](https://github.com/cplusplus/draft/files/7923756/d2416r2.pdf)

**Comment by frederick-vs-ja** [comment]
Oh... currently the undefined element "_Value_:" is used in the latest revision. Perhaps it should be replaced with "_Returns_:".
