### ISSUE TITLE
[range.req.general]/2 still says view requires constant time destruction

### ISSUE THREAD

**Issue by RedBeard0531** [cplusplus/draft#5234]
[[range.req.general]/2](http://eel.is/c++draft/range.req.general#2.sentence-3) says:
> The `view` concept specifies requirements on a `range` type with constant-time destruction and move operations.

That is no longer true. [[range.view]/2.3](http://eel.is/c++draft/range.view#2.3) says:
> if _N_ copies and/or moves are made from an object of type `T` that contained _M_ elements, then those _N_ objects have _O(N+M)_ destruction

I'm not sure what we want to say exactly instead there. That is vaguely like amortized constant-time, but only if you consider a finite _M_ and an infinite _N_.  Maybe it is best to just have the intro not mention destruction at all?

(I'm assuming that [range.req.general] is considered a non-normative "introduction" so any changes here are editorial. If not, please make this an LWG issue.)

**Comment by CaseyCarter** [comment]
I think we're overprecise here, resulting in normative duplication which unsurprisingly became out-of-date as the design changed. How about something more generically descriptive like "The `view` concept specifies requirements for object types that model `range` and provide operations with predictable complexity."?

**Comment by RedBeard0531** [comment]
That seems fine with me. I'm ok with an imprecise introduction, as long as it isn't inaccurate.
