### ISSUE TITLE
Some unclear wording in [except] CWG2775

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#5238]
### [except.throw] p3
> Throwing an exception copy-initializes ([dcl.init], [class.copy.ctor]) a temporary object, called the exception object.

The sentence does not specify the source of the copy-initialization. A possible improvement maybe that
> Throwing an exception copy-initializes ([dcl.init], [class.copy.ctor]) a temporary object, called the exception object, **from the operand of the throw-expression**.  

### [except.throw] p2
> When an exception is thrown, control is transferred to the nearest handler with a matching type ([except.handle]); “nearest” means the handler for which the compound-statement or ctor-initializer following the try keyword was most recently entered by the thread of control and not yet exited.

Is the following an improvement to the definition of "nearest handler"? 
> “nearest” means the **handler of a try-block or function-try-block** whose compound-statement or ctor-initializer was most recently entered by the thread of control and not yet exited.

The improvement seems to be simpler to read.

[except.throw] p5
> When the **thrown object** is a class object, the constructor selected for the copy-initialization as well as the constructor selected for a copy-initialization considering the **thrown object** as an lvalue shall be non-deleted and accessible, even if the copy/move operation is elided ([class.copy.elision]). The destructor is potentially invoked ([class.dtor]).

"thrown object" seems not to be a formal wording. Because we have defined *exception object*. Isn't that better to be used instead of "thrown object"?

**Comment by frederick-vs-ja** [comment]
I think the thrown object means the operand of the throw-expression. As the exception object is the target of initialization, it's meaningless whether it's considered as an lvalue.

**Comment by xmh0511** [comment]
> I think the thrown object means the operand of the throw-expression. As the exception object is the target of initialization, it's meaningless whether it's considered as an lvalue.

The operand of the throw-expression is not necessary to be an object, it can be a prvalue of a certain type, which is not an object.  The sentence 
> the constructor selected for the copy-initialization as well as the constructor selected for a copy-initialization considering the thrown object as an lvalue

should be rephrased to two parts
> the constructor selected for the copy-initialization of the exception object
> the constructor selected for a copy-initialization of **the variable declared by the exception-declaration** considering the ~thrown object~  exception object as an lvalue

The latter is consistent with [except.handle] p14. The lvalue relaxes the requirement when copy-initializing from "a temporary object" that would have been an xvalue.

**Comment by frederick-vs-ja** [comment]
The first occurrence of "thrown object" in [except.throw] has been present since C++98, and the second occurrence is introduced by [CWG1863](https://wg21.link/cwg1863) (adopted at Oct. 2015). Both occurrences are older than the adoption of [P0135R1](https://wg21.link/p0135r1) (at Jun. 2016) which makes prvalues of classes and arrays not objects.

What I meant is the first occurrence of "thrown object" might correctly mean the operand until C++17/P0135R1, but is incorrect now. It seems that the second occurrence of "thrown object" is wrong at first, because it is the exception object, whose type is never cv-qualified, that is needed to be copied, while the type of the operand of a throw-expression may be cv-qualified.

Since C++20/[P0848R3](https://wg21.link/p0848r3), a copy/move constructor may be constrained, so there may be no such constructor "selected for the copy-initialization", in which case the program is presumably ill-formed. But it seems that the current wording does not cover such cases.

I want to use the following wording:
> Let `t` be the operand of the _throw-expression_, `VT` be the type of the exception object. The variable definitions `VT e = t;` and `VT ec = e;` shall be well-formed for invented variables `e` and `ec`, ...

**Comment by xmh0511** [comment]
what do `e` and `ec` denote respectively, in your wording? 

> It seems that the current usage of "accessible" is also problematic, as the initialization and the copy of the exception object may happen in contexts with different access.  

"accessible" is checked in the context of the first matched handler, except that the exception is rethrown, "accessible" will continue to be checked for the context of the first matched handler with which the rethrown exception matches, and so on.

**Comment by frederick-vs-ja** [comment]
`e` and `ec` are not things. They are not created, and are only needed to check the validity of copy-initialization.

"Accessible" in [except.throw] p5 may refer to different contexts, and possibly two different constructors.
- The context where the throw-expression appears. The first constructor is checked.
- The context of the first matched handler. The second constructor is checked.
- The context inside `std::current_exception`. The second constructor is checked.
  - However, even though a `std::current_exception` call may only copy the exception object when it's nested within some matched handler, the `std::current_exception` function itself has no access to private constructors.

**Comment by xmh0511** [comment]
In general, the two constructors that need to be checked refer to them: 
> - the constructor selected for constructing the *exception object* from the operand, which is the first one you refer to.
> - the constructor selected for copying the *exception object*, which is the second one you refer to. 

It seems that `rethrow_exception ` and `make_exception_ptr` are also contexts where needs to check the corresponding constructor.

**Comment by xmh0511** [comment]
### the confusion use of exceptions and exception objects.
[propagation] p1 states
> The type exception_­ptr can be used to **refer to an exception object**. 

The same meaning is also appeared in [propagation] p10, [except.throw] p4.2. However, [propagation] p8 instead states
> An exception_­ptr object that refers to the **currently handled exception** or a copy of the **currently handled exception** 

The currently handled exception is an exception rather than an exception object. We should clarify the relationship between exception and exception object.

**Comment by frederick-vs-ja** [comment]
> **However, this proposal would ignore a case that the target object of the initialization has a base class type `B` of `T` and the copy/move constructor of `B` is inaccessible at that point**.

You're right. There can be three different constructors involved.

Given CWG2711 has made some clarification, the first two cases are addressed, and there's arguably no accessibility issue - it might be implied that accessibility check is made in the context of the throw-expression or the handler (which is also clang's current behavior).

The case for `std::current_exception` is still problematic. Currently, no mainstream implementation performs the necessary check, and it's even unclear whether the source of copy-initialization needed for `std::current_exception` is a cv-unqualified lvalue.

**Comment by jensmaurer** [comment]
We need to "capture" the (or a) copy constructor at the point of the "throw" (which may or may not be a throw-expression), because `current_exception` and similar functions operate on type-erased exceptions, thus we can't perform any overload resolution or accessibility checks at that point.

It seems to make sense to use a "const lvalue" for the source of the copy.

**Comment by frederick-vs-ja** [comment]
Should be already fixed by #6906 (c37fc847b953d3df41266537c6ef9b88ebf80a99).
