### ISSUE TITLE
[iterator.concept.winc] Duplicate paragraph

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#5251]
[\[iterator.concept.winc\]/12](http://eel.is/c++draft/iterator.concept.winc#12):

> For any two integer-like types `I1` and `I2`, at least one of which is an integer-class type, `common_­type_­t<I1, I2>` denotes an integer-class type whose width is not less than that of `I1` or `I2`. If both `I1` and `I2` are signed-integer-like types, then `common_­type_­t<I1, I2>` is also a signed-integer-like type.

[\[iterator.concept.winc\]/13](http://eel.is/c++draft/iterator.concept.winc#13):

> For any two integer-like types `I1` and `I2`, at least one of which is an integer-class type, `common_­type_­t<I1, I2>` denotes an integer-like type whose width is not less than that of `I1` or `I2`. If both `I1` and `I2` are signed-integer-like types, then `common_­type_­t<I1, I2>` is also a signed-integer-like type.

These are nearly identical, except that /12 says "`common_­type_­t<I1, I2>` denotes an integer-**class** type" while /13 says "`common_­type_­t<I1, I2>` denotes an integer-**like** type". Note that "integer-like type" is defined as "integral or integer-class type" in this section.

I believe that /13 is not needed, as it only specifies a weaker form of the previous paragraph.

/12 was added by [P2393R1 Cleaning up integer-class types](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2393r1.html). /13 was added by [P2321R2 zip](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2321r2.html).

cc @timsong-cpp

**Comment by timsong-cpp** [comment]
P2393 is pretty clear that its wording supersedes P2321’s.

**Comment by frederick-vs-ja** [comment]
I believe p12 and p13 are equivalent now as the common type can only be an integer-class type, and p13 should be removed as p12 is clearer.

**Comment by jensmaurer** [comment]
Fixed by the linked pull request.
