### ISSUE TITLE
Example in [class.protected] needs to be updated

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#527]
After [CWG 1873](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1873), derived class friends have no access to base class protected members.  The example in [class.protected], however, still labels such accesses as OK:

    class B {
    protected:
      int i;
      static int j;
    };
    class D1 : public B {
    };
    class D2 : public B {
      friend void fr(B*,D1*,D2*);
      void mem(B*,D1*);
    };
    void fr(B* pb, D1* p1, D2* p2) {
      // snip
      B::j = 5; // OK (because refers to static member) 
      D2::j = 6; // OK (because refers to static member)
    }

The line `B::j = 5;` should be marked ill-formed instead.

**Comment by hubert-reinterpretcast** [comment]
It seems
```
p2->B::i = 4;
```
is suspect too.
