### ISSUE TITLE
Remarks: vs. Remark: and Postconditions: vs. Postcondition: in library

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#529]
[structure.specifications] defines only _Remarks:_ and _Postconditions:_ elements, but the singular form _Remark:_ and _Postcondition:_ are also used throughout the library. (_Effect:_, OTOH, is only used in two lines in Table 28, the allocator requirements table.) This should be cleaned up.

**Comment by jensmaurer** [comment]
Duplicate of #282.
