### ISSUE TITLE
[lex.name] prohibits uses of predefined macro names and feature-test macros CWG 2818

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#5296]
This seems to prohibit uses of [predefined macro names](https://eel.is/c++draft/cpp.predefined) and library feature-test macros.
> [3](https://eel.is/c++draft/lex.name#3)[#](http://github.com/Eelis/draft/tree/dd187fdd1eb0bd31df208223997ff766dff5fee4/source/lex.tex#L794) In addition, some identifiers are reserved for use by C++ implementations and shall not be used otherwise; no diagnostic is required[.](https://eel.is/c++draft/lex.name#3.sentence-1)
[(3.1)](https://eel.is/c++draft/lex.name#3.1) Each identifier that contains a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use[.](https://eel.is/c++draft/lex.name#3.1.sentence-1)
[(3.2)](https://eel.is/c++draft/lex.name#3.2) Each identifier that begins with an underscore is reserved to the implementation for use as a name in the global namespace[.](https://eel.is/c++draft/lex.name#3.2.sentence-1)

More formally, according to [intro.compliance.general],
> [(2.3)](https://eel.is/c++draft/intro.compliance.general#2.3)
If a program contains a violation of a rule for which no diagnostic is required, this document places no requirement on implementations with respect to that program[.](https://eel.is/c++draft/intro.compliance.general#2.3.sentence-1)

Permission to use [predefined macro names](https://eel.is/c++draft/cpp.predefined) and library feature-test macros needs to be added to [cpp.predefined] and [version.syn], respectively. For full effect, amend [lex.name]p3's "otherwise" to "unless otherwise specified".

**Comment by JohelEGP** [comment]
I think the permission added to [version.syn] will also need something like [cpp.predefined]'s p4, that is, that a library feature-test macro is not subject of `#define` and `#undef`. But that is not relevant to the issue at hand.

**Comment by frederick-vs-ja** [comment]
IIUC this issue touches the same area as #5187.
In addition to the standard, implementations generally provide their own feature test macros. I think we should (conditionally) allow usage of these macros.

**Comment by JohelEGP** [comment]
> IIUC this issue touches the same area as #5187.

Indeed.

> In addition to the standard, implementations generally provide their own feature test macros. I think we should (conditionally) allow usage of these macros.

I considered this. But my conclusion was that implementations can define that so as not to fall under the standard's NDR. They probably already do that with `__is_same` and family.

**Comment by frederick-vs-ja** [comment]
The original issue should be already resolved by #7099 (ba8ff838ef25600001485912bc44b8e42640ef12). The concerns seem fully addressed in CWG2818.

However, it doesn't seem allowed to detect "future" standard feature-test macros yet. Not sure whether this is intended.
