### ISSUE TITLE
Inconsistent spacing between "template" and "<"

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#53]
From an email to cxxeditor@:

```
template<typename T>
```

or

```
template <typename T>
```

The standard as-is has 1494 instances of 'template<' that I can find trivially, and 2053 instances of 'template <'.

**Comment by AlisdairM** [comment]
Can we confirm the preference is:

template<class T, template class<U>>
and not
template <typename T,template class <typename U> >

(space and keyword choice)

I will perform a sweep of all library clauses after the Oulu papers land, and apply the preferred rule.
Understood that this may miss the CD, but should be easily landed before ballot resolutions arrive.

My preference would be template <typename T, template typename<typename U>> so it is a good job that I don't get to pick ;)

**Comment by tkoeppe** [comment]
@AlisdairM: My understanding is that "space after comma" and "closing `>>`" are uncontroversial. On the other hand, both openings `template<` and `template <` appear in roughly equal numbers and should not be changed at this point.

It's probably best to wait until all the motions have been merged unless you're happy to rebase.

**Comment by AlisdairM** [comment]
I want to do whatever is required to close the issue - the legwork seems easy, but repetitive :)
Yes, I definitely plan to wait till all the motions have landed, so that I am looking at the full text.

I would prefer guidance to resolve one way or the other on the 'template <' vs. 'template<', but if the conclusion is that both are acceptable, I will look for local consistency in each clause, and leave it at that.

**Comment by FrankHB** [comment]
I don't like the idea to choose a style merely according to the amount of instances, _unless there are no other reasons_.

Personally I prefer `template<` as we usually don't have any whitespace between identifier and lparen of function parameter list in a function declaration. This results a simpler rule: just avoid any space before the first token of "parameter list". The current style fits to my flavor:)

BTW, I've ever searched for some tools to format code in this style, but failed. Notably,[ `clang-format` had implemented the needed functionality, but eventually rejected](http://reviews.llvm.org/D10807). The reviewer also mentioned the style in the standard. Perhaps they should reconsider it this time.
See also http://stackoverflow.com/questions/34423615/cpp-template-spacing-using-clang-format-3-6-not-working-as-expected.

**Comment by jwakely** [comment]
I have a weak preference for `template<` without a space, just because it's slightly more compact and so gives us one more character spare. That way we *might* be able to fit something on one line that needed breaking (or ran into the margin) otherwise.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Don't apply for C++17.

**Comment by burblebee** [comment]
I'm reopening this because I ran into this while reviewing PR #2719, applied from P1458R1.  I would like to see a consistent form for this, with guidance added to our Specification-Style-Guidelines.

**Comment by CaseyCarter** [comment]
FWIW, we use `template<` in the specification of the Library, but allow `template <` in some examples (IIRC) as a nod to the validity of both styles. I suspect it would simplify the editorial teams job if you instituted a blanket ban on `template <` so the CI could validate it.

**Comment by tkoeppe** [comment]
@burblebee: Thanks for finding this. The guidance is clear (see above); I have finally updated the wiki to reflect this. Please apply the intended (no-space) formatting to this and all future wording changes.
