### ISSUE TITLE
Unable to find label {term.odr.use}

### ISSUE THREAD

**Issue by ChuanqiXu9** [cplusplus/draft#5303]
For example, when I click the link in http://eel.is/c++draft/basic.start.dynamic#4, I got a 404 not found page. And it looks like we couldn't find any page for any reference to `term.odr.use`. (I don't find any section named `term.odr.use` too)

**Comment by jensmaurer** [comment]
This tracker is not about bugs in the HTML rendering made available at http://eel.is/c++draft/

**Comment by jwakely** [comment]
Maybe we should just leave one of these bogus issues open so people can find it by searching open issues, and they stop reporting it here.

**Comment by jensmaurer** [comment]
> Maybe we should just leave one of these bogus issues open until Eelis has a fix. That will mean people can find it by searching open issues, and they might stop reporting it here.

You forgot to make "might" bold and super-size in the above.
