### ISSUE TITLE
How to space ref qualifiers

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#5308]
Should we have a convention for how to use whitespace in ref qualifiers in the library?

```
void f() const &;
void f() const&;
void f() const &&;
void f() const&&;
```

These qualifiers are still relatively rare, so we don't really have a weight of precedence here. I'm inclined to have no space between the cv and the ref qualifier (`const&`). If we want to fix a style, we should record it in the wiki.

**Comment by JohelEGP** [comment]
> I'm inclined to have no space between the cv and the ref qualifier (`const&`).

This seems prevalent, so I've been suggesting removing spaces whenever I notice them.

**Comment by jensmaurer** [comment]
I'm mildly in favor of having a space there. `const&` runs together too much for me. Yes, we do `const T&` elsewhere, but that feels somehow different.

**Comment by tkoeppe** [comment]
Yeah, I see what you mean. I don't feel strongly either way, but do you at least think we should fix a style at all?

**Comment by jensmaurer** [comment]
Yes, there should be consistent style enforced with check-source.sh (if that is technically feasible).

**Comment by tkoeppe** [comment]
OK, great! I leave the choice to you -- I think I can see the point of cv and ref being different, separate things here, esp. since we also have a space before a `&` that has no const -- so it's not like `T&` and `T const&`, but more like `f() &` and `f() const &`.

@zygoloid, @opensdh: any other core perspectives here?

**Comment by opensdh** [comment]
I generally agree: I don't tend to think of those qualifiers as actually being *decl-specifier*s and declarator operators, perhaps because *ref-qualifier*s don't influence the type of `*this` (even though they do affect the implicit object parameter).  Moreover, in the West Const (aka Best Const) style used by the standard, one doesn't see a *cv-qualifier* followed immediately by a *ptr-operator*.

**Comment by tkoeppe** [comment]
Jens: wants space, "to close together without space"

OpenSDH: wants space, becausethe qualifiers aren't *decl-specifiers*

Richard: wants space, because it's "const [T]&" where the T s omitted.


=> Let's go with the space then!

**Comment by jensmaurer** [comment]
spacey!
