### ISSUE TITLE
[diff.cpp20.library] is missing

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#5314]
Look at [diff.cpp17.library], [diff.cpp14.library], [diff.cpp03.library] 

We need a similar section [diff.cpp20.library] to announce new headers and removed headers.
Do we have a list somewhere?

@tkoeppe , @jwakely FYI

**Comment by frederick-vs-ja** [comment]
New headers: `<expected>`, `<spanstream>`, and `<stacktrace>`.
Removed headers: none.

(I wish `<strstream>` were removed.)

**Comment by jwakely** [comment]
And `<stdatomic.h>`.
