### ISSUE TITLE
[class.prop] ambiguous conditions in definition of implicit-lifetime class

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#5318]
> A class `S` is an *implicit-lifetime class* if it is an aggregate or has at least one trivial eligible constructor and a trivial, non-deleted destructor.

It's ambiguous whether this means (A || (B && C)) or ((A || B) && C).

How about:

> A class `S` is an *implicit-lifetime class* if it has a trivial, non-deleted destructor and either it is an aggregate or it has at least one trivial eligible constructor.

**Comment by jensmaurer** [comment]
The problem is that the omission of words in the English phrasing "or has X and Y" leads me to believe that "and" binds more tightly here than the "or". I'm wary of introducing a silent semantic change.

**Comment by jensmaurer** [comment]
@zygoloid , what did you intend here?

**Comment by jwakely** [comment]
I don't think an aggregate with a non-trivial destructor can be an implicit-lifetime type, can it?

**Comment by opensdh** [comment]
> I don't think an aggregate with a non-trivial destructor can be an implicit-lifetime type, can it?

It probably [_shouldn't_ be](https://github.com/cplusplus/CWG/issues/70), but there was actually only one way to parse the sentence in question (because "a trivial, non-deleted destructor" is merely a noun phrase).
