### ISSUE TITLE
Move the restrictions regarding macros away from [library] (or add links to them)

### ISSUE THREAD

**Issue by dangelog** [cplusplus/draft#5321]
[[macro.names]](https://eel.is/c++draft/macro.names) says

> A translation unit shall not #define or #undef names lexically identical to keywords, to the identifiers listed in Table [4](https://eel.is/c++draft/lex.name#tab:lex.name.special), or to the [attribute-token](https://eel.is/c++draft/dcl.attr.grammar#nt:attribute-token)s described in [[dcl.attr]](https://eel.is/c++draft/dcl.attr), except that the names likely and unlikely may be defined as function-like macros ([[cpp.replace]](https://eel.is/c++draft/cpp.replace))[.](https://eel.is/c++draft/macro.names#2.sentence-1)

Nothing in there "depends" on the library, this restriction is purely a language matter. It would be nice to move that clause (or restate it, link to it, etc.) into [cpp] and/or [lex].

**Comment by JohelEGP** [comment]
> [1](https://eel.is/c++draft/constraints#overview-1) Subclause [[constraints]](https://eel.is/c++draft/constraints#) describes restrictions on C++ programs that use the facilities of the C++ standard library[.](https://eel.is/c++draft/constraints#overview-1.sentence-1)
The following subclauses specify constraints on the program's use of [namespaces](https://eel.is/c++draft/constraints#namespace.std), its use of various reserved names, [...]

> [2](https://eel.is/c++draft/constraints#reserved.names.general-2) If a program declares or defines a name in a context where it is reserved, other than as explicitly allowed by [[library]](https://eel.is/c++draft/library), its behavior is undefined[.](https://eel.is/c++draft/constraints#reserved.names.general-2.sentence-1)

This is specifying library UB.

**Comment by dangelog** [comment]
Sorry, could you please elaborate? My point is: why is defining a macro that is e.g. equal to a language keyword a matter for the library, rather than for the language?

**Comment by JohelEGP** [comment]
You can change the meaning of including a C++ standard library header.

**Comment by dangelog** [comment]
But the rule is broader than that. A TU that consists entirely of

```
#define new old
```

is illegal according to that clause, isn't it? So why can't the rule be moved elsewhere?

(For clarity: I'm not saying to REMOVE that paragraph; I'm asking to move it to a language-specific part, or at leats to leave links from the language-specific parts.)

**Comment by JohelEGP** [comment]
> But the rule is broader than that. A TU that consists entirely of
> 
> ```
> #define new old
> ```
> 
> is illegal according to that clause, isn't it?

A TU is not enough. It's "C++ programs that use the facilities of the C++ standard library".

**Comment by jensmaurer** [comment]
[[constraints.overview]](https://eel.is/c++draft/constraints.overview) says:

> Subclause [[constraints]](https://eel.is/c++draft/constraints) describes restrictions on C++ programs that use the facilities of the C++ standard library.

If you don't use the standard library, you can #define keywords to your heart's content (and live with the consequences).

**Comment by dangelog** [comment]
Got it, thank you.

Just wondering: is there a formal definition of "using the standard library" somewhere?

**Comment by JohelEGP** [comment]
I don't think so.

**Comment by dangelog** [comment]
Got it, thank you.

Just wondering: is there a formal definition of "using the standard library" somewhere?
