### ISSUE TITLE
[range.utility.conv.general] Should `reservable-container` and `container-insertable` be concepts?

### ISSUE THREAD

**Issue by hewillk** [cplusplus/draft#5328]
In [[range.utility.conv.general]](https://timsong-cpp.github.io/cppwp/ranges#range.utility.conv.general), _`reservable-container`_ and _`container-insertable`_ are defined as

```
template<class Container>
constexpr bool reservable-container =          // exposition only
  sized_­range<Container> &&
  requires(Container& c, range_size_t<Container> n) {
    c.reserve(n);
    { c.capacity() } -> same_­as<decltype(n)>;
    { c.max_size() } -> same_­as<decltype(n)>;
  };
```

```
template<class Container, class Ref>
constexpr bool container-insertable =          // exposition only
  requires(Container& c, Ref&& ref) {
    requires (requires { c.push_back(std::forward<Ref>(ref)); } ||
              requires { c.insert(c.end(), std::forward<Ref>(ref)); });
  };
```

I don't understand why they lack `inline`, and it seems to me that defining them as concept is more consistent with the name, since the `inline constexpr bool` variables usually start with `is_`.

**Comment by JohelEGP** [comment]
I agree that prepending `is-` results in a better name, unless they're made `concept`s. These don't need to be `inline` since their address is not leaked, and thus the difference is not observable.

**Comment by hewillk** [comment]
I know, but _exposition only_ `constexpr bool` in `<ranges>` all are `inline`. Should we be consistent with them?

**Comment by JohelEGP** [comment]
That makes sense.

**Comment by hewillk** [comment]
In the original paper [p1206r7](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1206r7.pdf), the description of _`reservable-container`_ is

> **reservable-container concept**
> The exposition only reservable-container concepts checks for
> • reserve
> • max_size
> • capacity
> which is consistent with ranges-v3. This serves multiple purposes:
> • Avoid calling reserve on unordered containers and others entities that have a reserve
> method with different semantics
> • Allow implementations to check that we are not trying to reserve more than max size

So I suspect it should be a concept in nature, and the opinion of the author of the paper may be required.

**Comment by jwakely** [comment]
No, they should not be `inline`. They don't actually exist, so we don't need to add noise to the declaration to avoid linker errors for things that aren't really there.

No, we don't want them to be concepts. They were concepts in an earlier revision of the paper and it was changed intentionally by LWG review. The reason it's a variable template not a concept is because we don't want the semantic requirements of the constraints to result in UB if violated. It's a purely syntactic check.

**Comment by jwakely** [comment]
> I know, but _exposition only_ `constexpr bool` in `<ranges>` all are `inline`. Should we be consistent with them?

Maybe we should remove it from them too.

**Comment by jensmaurer** [comment]
No, they should not be `inline`, because variable templates are implicitly inline.

**Comment by JohelEGP** [comment]
Indeed, see #4625.

**Comment by hewillk** [comment]
Do we need to rename `container-insertable` to `insertable-container` to make it consistent with the naming of `reserve-container`? It seems a bit odd to me that two similar concepts have different name styles.

**Comment by jensmaurer** [comment]
No. `reservable-container` is a property of a container (regardless of element type etc), but `container-insertable` is about some `Ref` that wants to be inserted in some container, so it talks about something in relationship to a container. Different naming styles are fine.

**Comment by jensmaurer** [comment]
I'm not seeing any more open issues here. Closing.
