### ISSUE TITLE
[util.smartptr.shared] misuses italics

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#533]
Throughout [util.smartptr.shared] terms are italicised on each use, not only when defined, e.g. [util.smartptr.shared.const]/1 uses _empty_ which is defined [util.smartptr.shared]/1

> _Effects:_ Constructs an _empty_ shared_ptr object.

**Comment by jensmaurer** [comment]
@jwakely, are you actively working on this?

**Comment by tkoeppe** [comment]
To repeat @zygoloid's suggestion here for reference:

We can change "Foo is *bar* if quz" to "Foo is said to bar if quz", so that it's clear that a term is being defined ("is said to") without the need to distinguish the defined term typographically.
