### ISSUE TITLE
[container.rev.reqmts] p16+ are not "reversible container requirements"

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#5334]
See https://eel.is/c++draft/container.rev.reqmts#16.

**Comment by jensmaurer** [comment]
True. Maybe move those to [container.requirements.pre].

**Comment by hubert-reinterpretcast** [comment]
Also, the cross-reference for "contiguous container" (which is defined in the misplaced text that is the subject of this Issue) from [array.overview] paragraph 1 points to [container.requirements.general].

**Comment by JohelEGP** [comment]
Resolved by #6192 and #6199.
