### ISSUE TITLE
Inconsistent class-key in class template declarations

### ISSUE THREAD

**Issue by Arcoth** [cplusplus/draft#534]
Declarations such as e.g.

```c++
// 20.3.4, tuple-like access to pair:
template <class T> class tuple_size;
template <size_t I, class T> class tuple_element;

template <class T1, class T2> struct tuple_size<pair<T1, T2> >;
template <class T1, class T2> struct tuple_element<0, pair<T1, T2> >;
template <class T1, class T2> struct tuple_element<1, pair<T1, T2> >;
```
Use `struct` and `class` interchangeably. While this is not a defective thing per se (see §7.1.6.3/3), compilers do warn about inconsistent usage of both and it should be tidied up.

**Comment by jwakely** [comment]
Compilers don't compile declarations in the standard.

**Comment by Arcoth** [comment]
My point is that the aforementioned usage can be irritating. Also, yes they do, as the declarations are put into headers that themselves are compiled when including them - unless I'm mistaken?

**Comment by jwakely** [comment]
Compilers do not compile the standard, they compile headers that come with their implementation. The implementation headers can use whatever class-keys they want to, they don't have to match the standard, and changing the standard doesn't mean implementation will change.
I see nothing worth fixing here.

**Comment by oblitum** [comment]
Nor do I, I use `class` and `struct` interchangeably (I don't like `class` with `struct`-like layout for example, no `private` members, etc). If any compiler where to warn about that I would just use a flag to silent such warning.

**Comment by sigfpe** [comment]
Users who tolerate those bogus warnings should find something more productive to do.



-------- Original message --------

**Comment by zygoloid** [comment]
Closing; while consistency in presentation is generally important, in this case I don't think the comprehensibility or style of the standard is affected.

**Comment by oblitum** [comment]
I've captured the original intent of the issue re-reading it now... Well in that case it seems understandable, but it's bogus nonetheless. Personally I use `class` and `struct` interchangeably with a purpose as I said. In this case deviation from the original template in the instantiations doesn't look purposeful but there's no rule one can really form about that, such warnings woudn't apply for me for example, since any instantiation may happen to be more `class`-like or `struct`-like, and I use the proper keyword in each case, regardless of the keyword used for the original template.

**Comment by oblitum** [comment]
s/instantiation/specialization/

**Comment by Arcoth** [comment]
@zygoloid It might be sensible to uncouple`-Wmismatched-tags` from `-Wall` then, for Clang.

**Comment by jwakely** [comment]
@Arcoth, I still don't understand why you think the use of `struct` or `class` here in the standard has anything to do with warnings from your compiler. How we present this information in the standard does not dictate how vendors implement those specializations. If you get warnings complain to your std::lib vendor, but this is not the right venue.

**Comment by Arcoth** [comment]
> I still don't understand why you think the use of struct or class here in the standard has anything to do with warnings from your compiler.

I don't. 

> If you get warnings complain to your std::lib vendor, but this is not the right venue.

I was talking about Clang's nonsensical warning that annoyed me, which was the original incentive for opening this issue. I asked a Clang dev above - apparently you're not welcoming OT. I'll ask somewhere else then.

**Comment by sigfpe** [comment]
You do realize this is not the place to ask your vendor to do something very specific to your compiler. 



-------- Original message --------
