### ISSUE TITLE
[temp.arg.explicit] p5 Explicitly specified template arguments can enforce to use the template

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#5341]
[temp.arg.explicit] p5 just states:
> [Note 2: An empty template argument list can be used to indicate that a given use refers to a specialization of a function template even when a non-template function ([dcl.fct]) is visible that would otherwise be used. For example:
````cpp
// template <class T> int f(T);    // #1
int f(int);                     // #2
// int k = f(1);                   // uses #2
int l = f<>(1);                 // uses #1
````
> — end note]

However, we lack the rule to interpret the reason. First, `f<>` is **syntactically ok** as per grammar. [basic.lookup] has no special treatment to the name `f` when have determined that the `<` is interpreted as the delimiter of a template-argument-list according to [temp.names] p3: discards the name that denotes a non-template function.  

The only relevant reason may be [temp.deduct.general] p2: 
> When an explicit template argument list is specified, if the given template-id is not valid ([temp.names]), type deduction fails.

However, [temp.names] p7 is not friendly to interpret whether a template-id is valid when its component name does not denote a template.  

[temp.names] p7 should first admit that a `template-id` is not valid if its component name does not denote a template, it would be a simple/direct way to interpret the aforementioned case. I think it is also reasonable as the initial condition. [temp.names] p7 may be changed to:
> A template-id is valid if
>> -  the component name of it shall be introduced by a template-declaration 
>> - [...]
>
> A template-id shall be valid unless it is a simple-template-id that names a function template specialization ([[temp.deduct]](http://eel.is/c++draft/temp.deduct))[.](http://eel.is/c++draft/temp.names#7.sentence-2)

After applying this modification, `f<>` is not valid if the name `f` denotes `#2`, which results in type deduction fails as per [temp.deduct.general] p2. In the current draft, [temp.over] is drafted in terms of the function templates, 
> If, for a given **function template**, **argument deduction fails** or the synthesized function template specialization would be ill-formed, no such function is added to the set of candidate functions for that template[.](http://eel.is/c++draft/temp.over#1.sentence-3)  

[temp.over] should also admit that `#2` **won't be added to the candidate set** if it is referenced by an invalid `template-id`(`f<>` results in deduction fails).  This will interpret why an empty template argument list can be used to enforce to use of the template.

**Comment by jensmaurer** [comment]
@opensdh, I thought `f<>` should remove non-template overloads from the overload set. Do you know where that restriction is?

**Comment by jensmaurer** [comment]
Great. So, what is the remaining issue, exactly?

**Comment by xmh0511** [comment]
No hazy anymore.

**Comment by opensdh** [comment]
The non-*simple-template-id* possibilities can _only_ name function template specializations, so the latter part of the suggested change does nothing.

**Comment by xmh0511** [comment]
@jensmaurer @opensdh Whether a name is interpreted as a `template-name` depends on whether the symbol `<` is interpreted as a delimiter of a template-argument-list, this is implied by [temp.names] p3 and explicitly specified by [temp.names.note] p1
> If the name is an [identifier](https://eel.is/c++draft/lex.name#nt:identifier), it is then interpreted as a [template-name](https://eel.is/c++draft/temp.names#nt:template-name)[.](https://eel.is/c++draft/temp.names#3.sentence-2)

There is no rule that specifies that a `template-name` must be introduced by a template declaration, even though it's indeed a template declaration:
````cpp
template<class T>
class X{};
````
which is grammatically equivalent to *template-head declaration* where the *declaration* is a *class-specifier* whose class-name is an **identifier** that is not a `template-name` on this grammar chain.   

Consider this example:
````cpp
struct C{
   struct X{};
};
template<class T>
T::X<int> fun(){//... };

fun<C>();
````
According to [temp.names] p3 and [temp.res.general] p4, the symbol `<` is interpreted as a delimiter
>A < is interpreted as the delimiter of a template-argument-list if it follows a name that is not a conversion-function-id and
>> - [...]
>> - that is a terminal name in a using-declarator ([namespace.udecl]), in a declarator-id ([dcl.meaning]), or in a **type-only context** other than a nested-name-specifier ([temp.res]).

Thus, `X<int>` is interpreted as a **simple-template-id**, this is the initial syntax analysis in the first phase.  Any further checking will be done when the template is instantiated. So, we should ensure that we have the rule to specify whether `X<int>` is a valid template-id or not when the template is instantiated.

**Comment by jensmaurer** [comment]
The temp.names p3 rules help to determine at parse time whether some &lt; is an operator or the start of a _template-argument-list_. The interpretation whether something is a _template-name_ or not is locked in at parse time (with the help of the &lt; disambiguation rules), not at instantiation time. The "is valid" checks need to be performed at instantiation time, though, which is too late.

**Comment by xmh0511** [comment]
> The interpretation whether something is a template-name or not is locked in at parse time (with the help of the < disambiguation rules)

So, for `T::X<int>` this stuff, the delimiter is interpreted as a start of a template-argument-list and the terminal name of this type-specifier is `X` that is an identifier, It can be considered as a template-name **at parse time** and such a result is locked. This is the issue here, for which we have no special rule to restrict what `T::X<int>` will be when it's instantiated. Since `X<int>` is locked to be considered to be a template-id at parse time, it should be consistent at any time, hence, I think the valid definition for a template-id should work on it to check whether it is valid. This is the motivation of the modification.

**Comment by jensmaurer** [comment]
We say that a _class-name_ is introduced by a class declaration, and lookup essentially returns a _class-name_ when it finds a name declared as a class.

We have something similar for _template-name_in temp.param p3 (a template template parameter introduces a _template-name_); we seem to be lacking wording that a template declaration introduces its declarator-id as a _template-name_.

Once we have that, the &lt; would cause a _template-name_ to be required at the point of use, but the lookup result doesn't fit, and it's ill-formed.  Similar to `X::Y` requiring X to be a class-name or namespace-name.

**Comment by xmh0511** [comment]
> We say that a _class-name_ is introduced by a class declaration, and lookup essentially returns a _class-name_ when it finds a name declared as a class.
> 
> We have something similar for _template-name_in temp.param p3 (a template template parameter introduces a _template-name_); we seem to be lacking wording that a template declaration introduces its declarator-id as a _template-name_.
> 
> Once we have that, the < would cause a _template-name_ to be required at the point of use, but the lookup result doesn't fit, and it's ill-formed. Similar to `X::Y` requiring X to be a class-name or namespace-name.

It seems it is exact https://github.com/cplusplus/draft/issues/5345

**Comment by xmh0511** [comment]
> lookup essentially returns a class-name when it finds a name declared as a class.

It seems that this is not explicitly espoused with a formal rule. lookup only concerns **name** and declarations, where **name** is defined as:
[basic.pre] p4
> A name is an identifier ([lex.name]), operator-function-id ([over.oper]), literal-operator-id ([over.literal]), or conversion-function-id ([class.conv.fct]).
