### ISSUE TITLE
[spanstream.syn] doesn't mention `swap()` overloads

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#5362]
As of N4910, "Header `<spanstream>` synopsis" [spanstream.syn] doesn't mention the `swap()` overloads for `basic_spanbuf`, `basic_ispanstream`, `basic_ospanstream`, and `basic_spanstream`. Instead they're declared in [spanbuf.general], [ispanstream.general], [ospanstream.general], and [spanstream.general].

I believe this should follow the usual convention of having the header synopsis declare such overloads. (Noticed while scanning each header synopsis to implement Standard Library Modules.)

**Comment by JohelEGP** [comment]
Yes, that's the consensus documented in https://github.com/cplusplus/draft/issues/4041#issuecomment-739146311.
