### ISSUE TITLE
[diff.cpp03] etc introduction incorrect

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#537]
These introductory sentences say e.g.: "This subclause lists the differences between C++ and ISO C++ 2003 (ISO/IEC 14882:2003, Programming Languages — C++), by the chapters of this document."

But that's wrong: for instance, C.4.1 is a difference against C++03 and C++11, not just C++14.

We should fix these intro sentences to say which other subclauses are also in scope.

**Comment by jensmaurer** [comment]
@zygoloid: Why don't we simply say "This subclause lists the differences between ISO C++ 2011 (paren) and ISO C++ 2003 (paren)"?

If we ever revert a change, it's unlikely we retroactively amend old annex C entries, so simply saying this is the diffs of C++03 vs. C++11 is actually closer to the truth (and probably staying that way). If you want to find out what has changed between C++17 and C++03, it's somewhat obvious you need to read through several C.x subclauses.

**Comment by zygoloid** [comment]
Approach: reverse the order of the subclauses, and change all but the first to say:

"This subclause lists the differences between ISO C++ and ISO C++ abcd (in addition to those listed above), by the chapters of this document."

**Comment by jensmaurer** [comment]
Is "reverse the order of subclauses" a large enough section shuffling that it's C++23 material? See also #2252.

**Comment by jensmaurer** [comment]
Editorial meeting: Reversing the order means every revision of the standard will shift the numbering.
Just do it.
