### ISSUE TITLE
[containers.requirements.general] missing reference to table

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#54]
From an email to cxxeditor@:

I would like to report a simple Editorial issue. It appears not only
in the official standard but in also in which I believe is latest
draft: N3485.

Paragraph 23.2.1/4 says:

"In Tables 96 and 97 [...] a and b denote values of type X [...]"

whereas it meant

"In Tables 96, 97 and 98 [...] a and b denote values of type X [...]"

Indeed, Table 98 uses a and b and no other paragraph between 23.2.1/4
and Table 98 defines a and b. Alternatively, the paragraph immediately
preceding Table 98, which is 23.2.1/12, could redefine a and b by
replicating the definition given in 23.2.1/4.

**Comment by tkoeppe** [comment]
This appears to be fixed now. Close?
