### ISSUE TITLE
[expr.call] The result type of a function call and the value category relying on it

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#5415]
[expr.call] p14 says
> A function call is an lvalue if the **result type** is an lvalue reference type or an rvalue reference to function type, an xvalue if the **result type** is an rvalue reference to object type, and a prvalue otherwise.

So, the type of the result of a function call is significant to determine the value category of the function call. However, it's unclear the type of the result in a normal function call. [expr.call] p9 just says 

> The result of a function call is the result of the possibly-converted operand of the return statement ([stmt.return]) that transferred control out of the called function (if any), except in a virtual function call if the return type of the final overrider is different from the return type of the statically chosen function, the value returned from the final overrider is converted to the return type of the statically chosen function.  

It does specify the destination type for the case that the return types of the final overrider and the statically chosen function are different. However, for the conversion in the first step, it is vague to the destination type of the conversion(if any).  

> The result of a function call is the result of the possibly-converted operand of the return statement ([stmt.return]) that transferred control out of the called function (if any)

When we build up a conversion, we usually use the utterance: convert the expression `E` to type `T`. For the above case, we lack to specify the destination type `T`(in the first conversion). The improvement might be:   

> The result of a function call is:
>> - if no conversion is necessary, the operand of the return statement. 
>> - Otherwise, the **result of the conversion** that implicitly converts the operand of the return statement to the return type of the called function.
>
> where the return statement transferred control out of the called function (if any), except in a virtual function call if the return type of the final overrider is different from the return type of the statically chosen function, the **result of the final overrider** is converted to the return type of the statically chosen function.

Moreover, [conv.general] p6 defines what the result of a conversion is. 
> using the temporary variable as the result of the conversion. 

The modified rule together with  [conv.general] p6 are clear to clarify the value category that relies on the result type of the function call. 
````cpp
struct A{
   A(int);
};
A fun(){
  return 0;
}
````
The result of the conversion is defined as
````cpp
A t = 0;
````
The result of the call (`t`) is a prvalue of class `A`, thus the function call is a prvalue.

**Comment by xmh0511** [comment]
> It seems a bit clearer to use return type instead of result type

Yes, It was my original thought before proposing the suggestion. However, it still does not clarify the result of the function call, as pointed out in this issue, we lack to specify the destination type of the conversion. So, instead of replacing `result type` with `return type` for [expr.call] p14,  It might be better to directly clarify the result of the function call.

**Comment by xmh0511** [comment]
Change [expr.call] p9  to
> The result of a function call where the return type of the function is `T` is:
>> - if `T` is `cv void`, the function call has no result. 
>> - Otherwise, if the operand of the return statement ([stmt.return]) that transferred control out of the called function (if any) is `E`, for an invented declaration `T t = E;`
>>> - If no conversion is required and `E` is an expression, the result of `E`; the function call has the same category as `E`.
>>> - Otherwise, the result of the unqualified-id `t`.  `t` is an lvalue if T is an lvalue reference type or an rvalue reference to function type ([dcl.ref]), an xvalue if T is an rvalue reference to object type, and a prvalue otherwise. The function call has the same category as `t`.
>> [note: `E` may be a *braced-init-list*. --end note]

**Comment by jensmaurer** [comment]
I don't think this is correct.  For example,

```
int f()
{
  int x;
  return x;
}
```

I think this qualifies as "no conversion is required". The operand of the return statement is an lvalue, yet the function call `f()` obviously yields a prvalue.

**Comment by xmh0511** [comment]
Why wouldn't an lvalue-to-rvalue conversion apply to the operand `x` in that example? As said in [basic.lval] p5
> The **[result](https://eel.is/c++draft/basic.lval#def:result,prvalue) of a prvalue** is the value that the expression stores into its context; a prvalue that has type cv void has no result[.](https://eel.is/c++draft/basic.lval#5.sentence-2)  

Since the function call `f()` is a prvalue, its result should be the value stored in `x`. [conv.lval] p3.4 explicitly says
> Otherwise, the object indicated by the glvalue is read ([defns.access]), and the **value contained in the object** is the **prvalue result**.  


I think the proposed suggestion is not good for class type, consider this example
````cpp
struct B{};
B fun1(B& b){
    return b;
}
````
We have said that converting an argument of a class type to the same type is an identity conversion, which means no conversion is required. So, I think the proposed suggestion might be simplified to
> Otherwise, if the operand of the return statement ([stmt.return]) that transferred control out of the called function (if any) is E, for an invented declaration `T t = E;`, the unqualified-id `t`; `t` is an lvalue if `T` is an lvalue reference type or an rvalue reference to function type ([dcl.ref]), an xvalue if `T` is an rvalue reference to object type, and a prvalue otherwise.  The program is ill-formed If the declaration would be ill-formed.  

Without considering what the original operand is.  I think the declaration modeling a copy-initialization is consistent with [dcl.init.general] p14.

**Comment by jensmaurer** [comment]
See also #4847 and #4723.

The wording should be clear that the type and value category of a function call only depend on the return type written in the function declaration. I think it would be helpful to separate that  from the determination of the result (i.e. the value that is returned). I'm wondering whether we could simply say that the operand of the evaluated `return` copy-initializes the result, which works for both lvalues and prvalues, I think, and does the conversions we want.

**Comment by xmh0511** [comment]
> I'm wondering whether we could simply say that the operand of the evaluated return copy-initializes the result

As I said above, the function call is not necessarily used to initialize something. Consider this snippet
````cpp
fun() + 1;
````
There is no stuff to be initialized, we just need to read the value for computation. So, the current rule for the `return` statement obviously cannot cover this usage.  

Indeed that using "return type" to directly determine the value category of a function call is clearer. Nonetheless, The result of a function call is also needed to be clarified.

**Comment by xmh0511** [comment]
The example in https://github.com/cplusplus/draft/issues/4847 actually wants to say we should consider any conversions required to match the operand of the return statement to the return type as part of the initialization of the invented declaration, in order to avoid the ambiguity when we say certain conversions are not considered when initializing **the actual result object**.   

With the help of the suggestion, it is easy to interpret the example in #4847 and the corresponding rule will be well. 
````cpp
struct B{
  B(int){}
};
struct A{
  operator B(){   
     return 0;
  }
};
A a;
B const& rf = a;  //#1
````
the function call to `A::operator B` is a prvalue defined as
````cpp
 B t = 0;
````
`t` is the result of `A::operator B();` and it is a prvalue, which means the result object will be initialized by the constructor `B::B(int)` with the argument `0` wherever the result is used to initialize an object. According to [dcl.init.ref] p5.4.1, the effect at `#1` is the same like:
````cpp
B const& rf = t;
````
which obeys [dcl.init.ref] p5.3, no user-defined conversion is required in this initialization.

**Comment by xmh0511** [comment]
What the result of a function call is may be clarified by https://github.com/cplusplus/CWG/issues/186, and therefore what the type of the result is. Or, we may just need to use the return type in the rule.
