### ISSUE TITLE
Where to get the C++98 and C++03 drafts?

### ISSUE THREAD

**Issue by ltimaginea** [cplusplus/draft#5417]
Hi! I want to get the C++98 and C++03 drafts for my C++98/03 study reference information. This cplusplus/draft repo doesn't have them. And at here [http://www.open-std.org/JTC1/SC22/WG21/docs/standards](http://www.open-std.org/JTC1/SC22/WG21/docs/standards) , the C++03 draft link requires Authentication, so I can't get the C++98 and C++03 drafts. 

Where to get the C++98 and C++03 drafts? Can to add the C++98 and C++03 drafts to this cplusplus/draft repo?

Thanks!

**Comment by ltimaginea** [comment]
> The commit history in this repo only goes back to C++11, and the C++98 and C++03 standards are copyrighted by ISO.

OK! However, the C++98/03 **drafts** should not be copyrighted by ISO. I mean, I don't want the ISO official C++98 and C++03 standard documentations, I want the C++98 and C++03 **drafts**. Where to get the C++98 and C++03 drafts?

Thanks!

**Comment by jwakely** [comment]
If we had them, they'd be on open-std.org already.

**Comment by jwakely** [comment]
And if they're present there but password-protected, that's for a reason (such as being copyright ISO).

**Comment by frederick-vs-ja** [comment]
The C++98 final draft (N1146) can be found [here](http://open-std.org/jtc1/sc22/wg21/docs/wp/pdf/nov97-2/).

C++03 draft (N1316) seems non-public for some reason.

**Comment by jensmaurer** [comment]
This issue apparently does not name an editorial defect in the Working Draft. Please address your national standardization body if you wish to obtain copies of the standard. Closing.
