### ISSUE TITLE
confused collection of synopses for <cstdlib>

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#542]
We do not present a single unified view of the <cstdlib> header anywhere. Instead, we have six (!) separate tables with the title "Header <cstdlib> synopsis" distributed across 5 library clauses, and none of them describes the complete contents of the header. In some places we say that the table describes some of the contents of the header. In some places we incorrectly say it describes the complete contents.

Ideally, we should have a single place where we say what is actually in this header.

**Comment by zygoloid** [comment]
Similarly, [c.malloc] claims to provide a synopsis for <cstring> but misses most of the contents. The complete contents in this case are listed in [c.strings]

**Comment by tkoeppe** [comment]
What do you mean by "describe what is in this header"? If the following wording says that something from the header is replaced by something else (e.g. `strchr`), should the synopsis show the C original or a synthetic version with the C++ changes applied?

**Comment by timsong-cpp** [comment]
...and none of the six tables contains `NULL`, which is supposed to be defined by `<cstdlib>`.

**Comment by tkoeppe** [comment]
Those were dark days. The draft looks much different now.
