### ISSUE TITLE
std::thread termination

### ISSUE THREAD

**Issue by Flak88** [cplusplus/draft#545]
In some cases thread just can hang. Would not we should have more control on this kind of situation? Like .terminate(), .kill(), etc.
Yeah, i know pitfalls. Possible unreleased memory and other stuff. But it still better, then waiting forever to stop thread(which can never stopped).

**Comment by jwakely** [comment]
You seem to be requesting a design change, not an editorial issue, and this is the wrong place to do that.

Thread cancellation was discussed at length during the C++0x process and was not deemed suitable for standardisation. If you want to propose a change to the language please see https://isocpp.org/std/submit-a-proposal

**Comment by jwakely** [comment]
https://github.com/cplusplus/draft/wiki/How-to-tell-if-an-issue-is-editorial
