### ISSUE TITLE
Reference collapsing

### ISSUE THREAD

**Issue by FrankHB** [cplusplus/draft#546]
I searched N4527 and found "reference collapsing" is in the index. It points to the right place, i.e. [dcl.ref]/6. However, in [dcl.ref], there is no such wording in the normative and/or informative text at all. The only other occurrence of "reference collapsing" is in Table 53. This might confuse readers (and actually recently happened around me). Can it be clearer?

**Comment by MrMormon** [comment]
Any update?

**Comment by FrankHB** [comment]
Still applicable for N4567.
