### ISSUE TITLE
[mem.poly.allocator.class.general] Specializations of `polymorphic_allocator` may need clarification

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#5468]
`std::pmr::polymorphic_allocator<void>` seems allowed currently, but it can't meet the _Cpp17Allocator_ requirements. Should we say "A specialization of class template `pmr​::​polymorphic_allocator` meets the _Cpp17Allocator_ requirements ([allocator.requirements.general]) **if its template argument is a _cv_-unqualified object type**."?

I'm not sure whether an LWG issue is needed as no practical change would be made.

**Comment by jensmaurer** [comment]
@jwakely, any opinion here?

**Comment by jwakely** [comment]
I like the suggestion. In the Networking TS, `std::pmr::polymorphic_allocator<void>` is a *proto-allocator* but we don't have that term in the IS. The suggestion seems like a good alternative fix.

**Comment by jwakely** [comment]
And I agree this is just a clarification of the status quo, so editorial.
