### ISSUE TITLE
[allocator.requirements.general] Consider changing Example 2

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#5479]
The example seemly contains some "legacy" styles:
- `typedef`: now `using` is preferred;
- `operator!=`: as of C++20, rewritten candidates are generally preferred;
- globally visible equality operators: hidden friends seem preferred.

Should we change the example as following to encourage preferred styles?
```C++
template<class Tp>
struct SimpleAllocator {
  using value_type = Tp;
  SimpleAllocator(ctor args);

  template<class T> SimpleAllocator(const SimpleAllocator<T>& other);

  [[nodiscard]] Tp* allocate(std::size_t n);
  void deallocate(Tp* p, std::size_t n);

  template<class T>
  friend bool operator==(const SimpleAllocator&, const SimpleAllocator<T>&);
};
```

**Comment by jensmaurer** [comment]
@jwakely , what do you think?

**Comment by jwakely** [comment]
I think a normal member instead of hidden friend would be simpler for the equality op. It can even be a non-template, and rely on the converting constructor.

    bool operator==(const SimpleAllocator&) const;

**Comment by jwakely** [comment]
While we're here, should we use different template parameter names? `Tp` and `T` are unnecessarily similar. Maybe `T` and `U`.

**Comment by jwakely** [comment]
So:

```c++
template<class T>
struct SimpleAllocator {
  using value_type = T;
  SimpleAllocator(ctor args);

  template<class U> SimpleAllocator(const SimpleAllocator<U>& other);

  [[nodiscard]] T* allocate(std::size_t n);
  void deallocate(T* p, std::size_t n);

  bool operator==(const SimpleAllocator&) const;
};
```

**Comment by frederick-vs-ja** [comment]
> So:
> 
> ```c++
> template<class T>
> struct SimpleAllocator {
>   using value_type = T;
>   SimpleAllocator(ctor args);
> 
>   template<class U> SimpleAllocator(const SimpleAllocator<U>& other);
> 
>   [[nodiscard]] T* allocate(std::size_t n);
>   void deallocate(T* p, std::size_t n);
> 
>   bool operator==(const SimpleAllocator&) const;
> };
> ```

Oops, the example suffers from the same problem as [this bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115939) ([Godbolt link](https://godbolt.org/z/3rb4sMxE8)).

The template friend approach seems to work ([Godbolt link](https://godbolt.org/z/7GPeoGKe8)).
