### ISSUE TITLE
[basic.def.odr] p5 "appears as" is not defined and "named by" is a better choice

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#5533]
[basic.def.odr] p5 says
> A variable is named by an expression if the expression is an id-expression that denotes it. A variable x **whose name appears as** a potentially-evaluated expression E is odr-used by E unless 

The intent of what `E` is here refers to the `id-expression` naming the entity. "appear as" is not a defined meaning. It is better that we just say: 
> A variable **is named by an expression** if **the expression is an id-expression** that denotes it. A variable x **named by a potentially-evaluated expression E** is odr-used by E unless  

It is more clear.

**Comment by jensmaurer** [comment]
No, because it raises the question whether an unevaluated subexpression (e.g. sizeof) of a potentially-evaluated expression also fits "named by". (It clearly doesn't fit "appears as".)

**Comment by xmh0511** [comment]
> No, because it raises the question whether an unevaluated subexpression (e.g. sizeof) of a potentially-evaluated expression also fits "named by". (It clearly doesn't fit "appears as".)

Why? Did you mean such as this example?
````cpp
auto c = sizeof(T::x); 
````

The variable `T:x` is not **named by** the expression `sizeof(T::x)`, it is just named by `T::x` that is an *id-expression* denotes it.  `T::x` is not potentially evaluated since it is the operand of `sizeof`. Could you please give a counterexample?

**Comment by jensmaurer** [comment]
Agreed.

**Comment by xmh0511** [comment]
https://github.com/cplusplus/draft/pull/5534

**Comment by tkoeppe** [comment]
@jensmaurer Could you take a look at #5534 then?
