### ISSUE TITLE
Resolution of CWG 2017 "Flowing off end is not equivalent to no-expression return"

### ISSUE THREAD

**Issue by petrochenkov** [cplusplus/draft#561]
The text in http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0167r0.html#2017 says:

```
Change 6.6.3 [stmt.return] paragraph 2 as follows:

...Flowing off the end of a function with a void return type is equivalent to a return with no value; this results in undefined behavior in a value-returning function operand. Otherwise, flowing off the end of a function other than main (3.6.1 [basic.start.main] results in undefined behavior.
```

Should it be `... a function with a *cv* void return type is equivalent to ...`?

**Comment by Arcoth** [comment]
It appears that if the indefinite article or plural form is used, the set of types `{void, volatile void, const void, const volatile void}` is being referred to. This is consistent with the formatting - fixed width is only employed when talking of `void`, not "the void types" or "a void type". E.g. [basic.types]/5:

> Incompletely-defined object types and the void types are incomplete types (3.9.1).

**Comment by timsong-cpp** [comment]
That particular phrasing has just been cleaned up by [CWG 2006](http://wg21.link/CWG2006).

**Comment by petrochenkov** [comment]
Oh, and I think constructors are not covered by this resolution, since they have no return types?

**Comment by petrochenkov** [comment]
Fixed in N4582
