### ISSUE TITLE
20.12.6.7 [time.point.cast] is missing parens

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#562]
The newly-added `floor()`, `ceil()`, `round()` in N4567 20.12.6.7 [time.point.cast]/4, /6, /8 are missing parentheses:

*Returns:* `time_point<Clock, ToDuration>floor<ToDuration>(tp.time_since_epoch())`.

*Returns:* `time_point<Clock, ToDuration>ceil<ToDuration>(tp.time_since_epoch())`.

*Returns:* `time_point<Clock, ToDuration>round<ToDuration>(tp.time_since_epoch())`.

**Comment by jwakely** [comment]
The problem is that they use braces for init, but braces are special in LaTeX. Fix coming ...
