### ISSUE TITLE
20.7.2 [memory.syn] should mention owner_less's default template arg

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#563]
N4567 20.7.2 [memory.syn] declares:

`template<class T> class owner_less;`

But 20.8.2.4 [util.smartptr.ownerless] now says:

`template<class T = void> struct owner_less;`

The synopsis should be updated, to be consistent with `plus<>` etc.  Also, the `class` vs. `struct` disagreement should be fixed.

**Comment by jwakely** [comment]
Fixed at faf6ce008124ccaeaf8f77d31f3fb72bd2fcafdd
