### ISSUE TITLE
inconsistent periods in compatibility annex

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#564]
In [diff.iso] and [diff.cpp03] the `\change` elements do not end with a period.

In [diff.cpp11] and [diff.cpp14] the `\change` elements all end with a period except for [diff.cpp11.basic].

Is there any reason not to add periods consistently? There isn't some ISO convention we need to follow here?

**Comment by tkoeppe** [comment]
This seems to have been fixed by 64978c8d.
