### ISSUE TITLE
License of the draft

### ISSUE THREAD

**Issue by SabrinaJewson** [cplusplus/draft#5704]
Would it be possible to assign a specific license to this draft so that the legality of copying the contents of it is more precisely specified? Already there exist sites that rehost it like [eel.is](https://eel.is/c++draft/) but without a license they may not technically be legal.

My particular use case is that I want to extract and edit the sections on multithreading and memory orderings to include in the Rust Nomicon, and I’m not sure if that’s allowed.

**Comment by jensmaurer** [comment]
We're not in a position to give legal advice here, sorry.
