### ISSUE TITLE
[expected.object.assign] Missing Returns element

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#5712]
The first 2 operators at [expected.object.assign](https://eel.is/c++draft/expected.object.assign) are missing _Returns:_ `*this`.

**Comment by frederick-vs-ja** [comment]
Almost all assignment operators in the standard library return `*this`. Is it worthwhile to specify this once instead of repeating everywhere?

**Comment by jwakely** [comment]
> Almost all assignment operators in the standard library return `*this`. Is it worthwhile to specify this once instead of repeating everywhere?

Yes, we've suggested this in LWG. I'll open a new issue and assign it to myself.
