### ISSUE TITLE
Subclause [stdfloat.syn] is oddly disconnected

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#5714]
We should either start a new subsection "Floating-point types" with additional wording, perhaps relating to C, or otherwise perhaps we can rename "Integer types" to "Numeric types" (or "Arithmetic types") and have both `<cstdint>` and `<stdfloat>` in it.

**Comment by tkoeppe** [comment]
@AaronBallman Do you expect us to gain more wording in C++ regarding floating point types once we rebase on C23? Would it be better to have two distinct sections for integer and floating-point types, or can we combine them into a single section?

**Comment by JohelEGP** [comment]
The originating comment: https://github.com/cplusplus/draft/pull/5670#discussion_r937779198.

**Comment by AaronBallman** [comment]
> @AaronBallman Do you expect us to gain more wording in C++ regarding floating point types once we rebase on C23?

Yes, C23 adds new floating-point types to the core language (decimal floating-point types) and a pile of new C library functions for the new types.

> Would it be better to have two distinct sections for integer and floating-point types, or can we combine them into a single section?

My intuition is that two sections is going to be more workable in the long run. C23 also added checked integer math in its own header, as an example.
