### ISSUE TITLE
Syntax highlighted code for drafts

### ISSUE THREAD

**Issue by shivshankardayal** [cplusplus/draft#572]
I would like to see syntax highlighted code in draft. Thus, I propose to make changes in draft which I can do. I know that it may not be acceptable for some reasons but with git we can have a branch which contains that version of draft.

**Comment by sigfpe** [comment]
What purpose would this serve?-------- Original message --------From: Shiv Shankar Dayal <notifications@github.com> Date: 11/27/2015  9:00 PM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Subject: [draft] Syntax highlighted code for drafts (#572) 
I would like to see syntax highlighted code in draft. Thus, I propose to make changes in draft which I can do. I know that it may not be acceptable for some reasons but with git we can have a branch which contains that version of draft.

**Comment by shivshankardayal** [comment]
For many people who read drafts on screen it is just pleasing to have it. There is no useful technical value. To keep it separate we can keep it in a separate branch.

**Comment by sigfpe** [comment]
And many find it a distraction from both the normative spec and the main points sample codes are meant to convey :-)
Given that highlighting taste differs among people, and this is additional work, who is going to maintain this separate branch?-------- Original message --------From: Shiv Shankar Dayal <notifications@github.com> Date: 11/27/2015  10:35 PM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Cc: sigfpe <sig.fpe@axiomatics.org> Subject: Re: [draft] Syntax highlighted code for drafts (#572) 
For many people who read drafts on screen it is just pleasing to have it. There is no useful technical value. To keep it separate we can keep it in a separate branch.

**Comment by shivshankardayal** [comment]
There is not much of maintenance work. An automated script can do it and we can have a git hook to automatically update branch and generate the pdfs once master is updated. I can maintain this separate branch although I doubt that manual work will be needed frequently.

**Comment by sigfpe** [comment]
So it can be done in a separate fork?-------- Original message --------From: Shiv Shankar Dayal <notifications@github.com> Date: 11/27/2015  11:25 PM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Cc: sigfpe <sig.fpe@axiomatics.org> Subject: Re: [draft] Syntax highlighted code for drafts (#572) 
There is not much of maintenance work. An automated script can do it and we can have a git hook to automatically update branch and generate the pdfs once master is updated. I can maintain this separate branch although I doubt that manual work will be needed frequently.

**Comment by shivshankardayal** [comment]
Yes, it can be done in a separate fork.

**Comment by sigfpe** [comment]
In that case, is it necessary to create an issue against the draft?-------- Original message --------From: Shiv Shankar Dayal <notifications@github.com> Date: 11/27/2015  11:28 PM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Cc: sigfpe <sig.fpe@axiomatics.org> Subject: Re: [draft] Syntax highlighted code for drafts (#572) 
Yes, it can be done in a separate fork.

**Comment by shivshankardayal** [comment]
I was wondering if that branch could be part of this repository that is why I created this issue. I cannot label it else I would have labeled it tiny or cosmetic.

**Comment by jwakely** [comment]
I am firmly opposed to having ongoing branches or forks of the draft in the official repo, I think it can only lead to confusion. Short-lived branches for making changes that get merged back is fine, but branches for "the draft with syntax highlighting" or "the draft with extra examples" or anything like that would be counter-productive. Such things don't belong in this repo.

**Comment by shivshankardayal** [comment]
That is fine. I understand your point. I can create a fork and keep it in my respository where stray users will find it. :)

**Comment by zygoloid** [comment]
It's likely that this is possible just by changing the configuration of the listings package.
