### ISSUE TITLE
Fix up table of library headers after all new library headers have been added

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#5722]
See comment in https://github.com/cplusplus/draft/pull/5626#discussion_r928230007_

**Comment by tkoeppe** [comment]
I have a commit for this ready.

**Comment by jensmaurer** [comment]
@tkoeppe, so please go ahead with that.

**Comment by tkoeppe** [comment]
This has landed already, thanks!

**Comment by tkoeppe** [comment]
Thanks -- I thought I had pressed "close with commment", must have misclicked something.
