### ISSUE TITLE
[mdspan.mdspan] Remaining uses of `pointer`

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#5727]
These uses of `pointer` should be replaced by `data_handle_type`, as proposed in [P2604R0](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2604r0.html), but it appears that the changes were lost due to merge conflict.

https://github.com/cplusplus/draft/blob/1bc895c21e5e3907bf0fefa963629f5a33074878/source/containers.tex#L18761-L18770
https://github.com/cplusplus/draft/blob/1bc895c21e5e3907bf0fefa963629f5a33074878/source/containers.tex#L18931-L18932
https://github.com/cplusplus/draft/blob/1bc895c21e5e3907bf0fefa963629f5a33074878/source/containers.tex#L18976-L18981

**Comment by tkoeppe** [comment]
Thanks, I'll fix that!

**Comment by tkoeppe** [comment]
Fixed by e24445344d26e3d9a3ad92b939b8c034daa47eb4.
