### ISSUE TITLE
[diff.library] (C.5) is woefully out of date

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#573]
It looks like [diff.library] was not updated for the resync to the C99 standard library; many or all of the macros and functions added by that change are missing. It's also not really clear what value we gain by duplicating the information on the contents of the <c*> headers as tables 149-153.

**Comment by tkoeppe** [comment]
I think I did something about that in response to [LWG 2201](http://wg21.link/lwg2201).
