### ISSUE TITLE
views::stride in [ranges.syn] should not be marked freestanding

### ISSUE THREAD

**Issue by ben-craig** [cplusplus/draft#5733]
P1642 (freestanding stuff) has a merge conflict / editing race condition with P1899 (stride_view).  Both were added in the same plenary, and both wanted to modify ranges.syn.  The drafting note in P1642 did not explicitly call out stride_view though, so views::stride probably shouldn't get the `// freestanding` comment.  Note that only views::stride got an erroneous freestanding mark.  `stride_view` and the accompanying `enable_borrowed_range` didn't get such a mark (which is the correct editorial decision).

From a design standpoint stride_view and friends are totally fine in freestanding, but we'll need a paper / NB comment to fix that at this point.

**Comment by tkoeppe** [comment]
Could you perhaps send a pull request to remove erroneous annotations?

I had understood the wording of P1642 to mean that LWG had implicitly approved the pending changes:

"""
The following papers are all in the LWG queue as of 2022-04-09:
...
[P1899 views::stride](http://wg21.link/P1899)
...
The above papers add facilities to <ranges>, <utility>, and <functional>. The wording in this revision will include those facilities implicitly
"""

Was that not right?

**Comment by frederick-vs-ja** [comment]
I guess we can keep the current working draft as-is even if it's contradictory, as the working draft used to have long-standing `noexcept` mismatch that was eventually fixed via LWG issues.
IMO an LWG issue should be filed soon to make `stride_view` and its friends freestanding.

**Comment by tkoeppe** [comment]
@ben-craig Could you please confirm that the sentence I quoted, "The wording in this revision will include those facilities implicitly", does _not_ mean that those new features from the LWG queue have been approved to be freestanding?

**Comment by ben-craig** [comment]
The merge conflicts that LWG approved are the ones mentioned in the drafting notes.  The freestanding paper was reviewed and approved by LWG on July 2, and stride was approved on July 8.  When reviewing freestanding, we only verified and explicitly approved of the things that were already LWG approved.

**Comment by tkoeppe** [comment]
@ben-craig: thanks -- I think it was a misunderstanding on my part then. I thought that LWG had approved the wording "The wording in this revision will include those facilities implicitly" with the interpretation that those implicit inclusions are also approved.

**Comment by tkoeppe** [comment]
Oh, I think we already fixed this as part of b77c526dda683307f1c0048efa0d922eb5dd02e0.
