### ISSUE TITLE
[range.cartesian.view] Fix _`cartesian-product-is-common`_

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#5735]
What is `Const`? Why is `Vs...` unused? The refined concept only takes 1 argument.

Presumably, `Const` came from a copy-pasted _`maybe-const`_`<Const, First>`. That'd explain the extra closing `>`.

Considering the name of the concept and how it's used, this should be:
```suggestion
    (@\exposconcept{cartesian-product-common-arg}@<First> && ... &&
     @\exposconcept{cartesian-product-common-arg}@<Vs>);
```

_Originally posted by @JohelEGP in https://github.com/cplusplus/draft/pull/5647#discussion_r929081572_

**Comment by tkoeppe** [comment]
I think you're right, will send a PR.

**Comment by hewillk** [comment]
Is this really correct? From the [original paper](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2374r4.html#common-range):

> `cartesian_product_view` can be a common range if the first range either is common, or is sized and random access. This paper reflects this.

In my opinion this should be
```cpp
template <class First, class... Vs>
  concept cartesian-product-is-common = // exposition only
    cartesian-product-common-arg<First>;
```

@tkoeppe @JohelEGP

**Comment by JohelEGP** [comment]
Then I'd also question why the `end()` overloads are constrained with `@\exposconcept{cartesian-product-is-common}@<First, Vs...>` rather than `cartesian-product-common-arg<First>` directly.

**Comment by hewillk** [comment]
`cartesian-product-common-arg` might not be a good constraint name for `end`, `cartesian-product-is-common` seems to be additionally defined for consistency with `cartesian-product-is-sized`.
