### ISSUE TITLE
[ranges.syn] Fix `// freestanding` comments of under [range.as.rvalue]

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#5738]
https://github.com/cplusplus/draft/pull/5708#discussion_r944520506 was not applied and its surrounding `// freestanding` comments are not aligned with the rest. See the discussion starting at https://github.com/cplusplus/draft/pull/5698#discussion_r944515423 as for why the linked suggestion makes sense, besides having been what the paper requested.

**Comment by tkoeppe** [comment]
I've got this already, thanks.

**Comment by tkoeppe** [comment]
Splitting the alignment and the missing comment and sending a PR for the latter.
