### ISSUE TITLE
[cpp.cond] Missing `__has_cpp_attribute(assume)` CWG2615

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#5740]
[P1774R8](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1774r8.pdf) adds the assumption attribute `assume`, but does not modify Table 22 "`__has_cpp_attribute` values" to handle `__has_cpp_attribute(assume)`.

This appears to be an obvious mistake. Can it be fixed editorially?

**Comment by tkoeppe** [comment]
@jensmaurer Has the feature test macro been discussed?

**Comment by jensmaurer** [comment]
The change  history of the paper says

> R5, 2021-12-09: Updated wording (removed feature-test macro, allowed duplicate attributes, added clarifications). Updated and restructured text, expanding semantics section to reflect discussion in EWG and on the WG21 reflectors. Added Peter Dimov’s refcounted smart pointer code example.

I don't remember any discussion about a feature-test macro in CWG, and the CWG minutes don't show any discussion either. I presume everybody assumed `__cpp_has_attribute` would just magically work.

**Comment by tkoeppe** [comment]
Thanks -- I don't have a problem adding it, but there has been pushback on other missing macros being "normative changes that should go through the regular issue process". Maybe we can make this a CWG issue then?

**Comment by tkoeppe** [comment]
(Please relabel/reassign as you see fit!)

**Comment by jensmaurer** [comment]
CWG2615

**Comment by frederick-vs-ja** [comment]
Should have been fixed by #5988 (https://github.com/cplusplus/draft/pull/5988/commits/82c4158bd006ddc831e54a5a2f50e2b62c516384).
