### ISSUE TITLE
update Annex F introductory text

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#575]
The introductory text of Annex F is almost certainly no longer up to date, and it only lists differences against C++2003. If this text is considered to be valuable, we should update it to also list differences from C++11 and C++14 (for instance, the inheriting constructors subclause has been moved and renamed). Otherwise, we should excise it.

**Comment by AlisdairM** [comment]
Annex F is now built as an index, and the troublesome text has been removed.  This issue can be closed.
