### ISSUE TITLE
[vector.capacity] p14 The precondition use "and" but should use "or"

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#5776]
[vector.capacity] p14 says 
> constexpr void resize(size_type sz);
>> Preconditions: T is Cpp17MoveInsertable **and** Cpp17DefaultInsertable into *this.

Cpp17MoveInsertable is defined in [containers.container.alloc.reqmts] p2.3
> T is Cpp17MoveInsertable into X means that the following expression is well-formed:
>> - allocator_traits<A>::construct(m, p, RV)

[containers.container.alloc.reqmts] p2 says
> given an lvalue m of type A, a pointer p of type T*, an expression v of type (possibly const) T, and an **rvalue rv of type T**,

Consider this example:
````cpp
struct A{
   A() = default;
   A(A const&) = default;
   A(A&&) = delete;
};
int main(){
   std::vector<A> vec{};
   vec.resize(10); // ok
}
````
However, `A` is not Cpp17MoveInsertable since `allocator_traits<A>::construct(m, p, RV)` is ill-formed for `A`.

**Comment by JohelEGP** [comment]
I think it's "and" because when `sz > capacity()`, the first `size()` elements use Cpp17MoveInsertable and the rest Cpp17DefaultInsertable.

**Comment by xmh0511** [comment]
> 

But, in other words, when `sz < capacity()`, the invocation of `resize()` indeed does not requires the requirement `Cpp17MoveInsertable` for `A`, as shown in the example.

**Comment by xmh0511** [comment]
Moreover, consider this example
````cpp
  std::vector<A> vec{};
  vec.reserve(2);
  std::cout<< vec.capacity()<<std::endl;  // #1
  vec.resize(10);  // #2
````
`#1` prints `2` and `#2` still be ok.

**Comment by xmh0511** [comment]
From the comment of the implementation of `vector<T>::resize`, it says it will default construct the element when `sz > the first size()`, see https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/stl_vector.h#L1004

**Comment by JohelEGP** [comment]
When you _do_ run out of capacity, you need the former set of requirements. Maybe what you want is to make the precondition of that set conditional. But I don't think that's editorial.

**Comment by xmh0511** [comment]
See my last comment above. I'm not sure whether the implementation didn't obey the requirement, or whether there are some inconsistencies in the standard. At least, according to your opinion, the requirement `Cpp17MoveInsertable` for  `void resize(size_type sz);` should be conditional.

**Comment by frederick-vs-ja** [comment]
> From the comment of the implementation of `vector<T>::resize`, it says it will default construct the element when `sz > the first size()`, see https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/stl_vector.h#L1004

The comment doesn't follow the standard terminology, but IIUC the actual implementation is right here. In that case, the libstdc++ implementation is actually default-inserting new elements (with `__uninitialized_default_n_a`) and moving or copying old ones (with `__uninitialized_move_if_noexcept_a`).

We can't simply make _Cpp17MoveInsertable_ or _Cpp17DefaultInsertable_ conditional, because "_Mandates_" is missing here, and the well-formedness requirements, in my opinion, inappropriately appear in "_Preconditions_".

I think there are several possible defects.
- [vector.capacity]/16 suggests that old elements are copy-inserted under some conditions, but _Cpp17CopyInsertable_ (which has semantic requirements) is not mentioned in _Preconditions_.
- Many named requirements in [container.alloc.reqmts]/2 (e.g. _Cpp17DefaultInsertable_) are merely requirements for well-formedness, and it's suspicious for them to appear in _Preconditions_ instead of _Mandates_.
  - _Cpp17MoveInsertable_ and _Cpp17CopyInsertable_ have additional semantic requirements, should they be split?
- There is implementation divergence on `resize`: libstdc++ and msvc stl accept the non-move-insertable `A`, while libc++ rejects it. Currently all of them are conforming IIUC because _Cpp17MoveInsertable_ only appears in _Preconditions_. If diagnosable parts of _Preconditions_ are moved to _Mandates_, then the implementation divergence matters. It's not clear to me whether such divergence is intentionally allowed.

Anyway, I don't think this is editorial either. LWG issues seem needed.

**Comment by jwakely** [comment]
> But, in other words, when `sz < capacity()`, the invocation of `resize()` indeed does not requires the requirement `Cpp17MoveInsertable` for `A`, as shown in the example.

Yes, but simply changing the preconditions from "and" to "or" would not help that problem and would be totally wrong. That would imply that resizing when capacity is exceeded has to work for an object that can only be default constructed, but not copied or moved. That's nonsense.

When shrinking the vector, neither Cpp17MoveInsertable nor Cpp17DefaultInsertable is required. When growing within the current capacity, only Cpp17DefaultInsertable is required. When exceeding the capacity, both are required. So the current wording is correct. In general, for an arbitrary call to `resize`, both are required.

So there is no editorial issue here, and any change to those requirements would be very non-editorial.

**Comment by jwakely** [comment]
> * _Cpp17MoveInsertable_ and _Cpp17CopyInsertable_ have additional semantic requirements, should they be split?

At the time, there was a deliberate decision to not alter those requirements in [Mandating the Standard Library:
Clause 21 - Containers library](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1463r1.pdf). That could be revisited now, but I don't know how much support there would be for doing that. It seems out of scope for an LWG issue, a paper would be needed.

**Comment by xmh0511** [comment]
> So the current wording is correct.

The wording "and" requires both conditions are true, I think. However, the condition `Cpp17MoveInsertable` for `A` is false. This is the issue here.

**Comment by JohelEGP** [comment]
That just means it's UB.
> [(3.3)](https://eel.is/c++draft/library#structure.specifications-3.3)
Preconditions: the conditions that the function assumes to hold whenever it is called; violation of any preconditions results in undefined behavior[.](https://eel.is/c++draft/library#structure.specifications-3.3.sentence-1)

**Comment by frederick-vs-ja** [comment]
> However, the condition `Cpp17MoveInsertable` for `A` is false. This is the issue here.

This is not an issue of standard wording or implementations (at this moment). Using such non-_Cpp17MoveInsertable_ `A` with `resize` results in UB, and thus implementations may support it as a conforming extension, or reject it.

**Comment by xmh0511** [comment]
> i.e. the wording is correct. There is no editorial issue here.

My original option is 
>  I'm not sure whether the implementation **didn't obey the requirement**, or whether there **are some inconsistencies in the standard**.

AFAIK, the implementations of GCC and MSVC regarding `resize` all support the case when `T` is not `Cpp17MoveInsertable`, not sure whether Clang supports this behavior or not since I didn't dig further in Clang's standard library source code, Clang may be similar to GCC here. According to the wording, the behavior would be UB if `T` is not `Cpp17MoveInsertable`, however, all major implementations have consistent behavior. Agree that this issue touches the domain that is non-editorial

**Comment by frederick-vs-ja** [comment]
> I'm not sure whether the implementation **didn't obey the requirement**, or whether there **are some inconsistencies in the standard**.

Implementations are conforming here IIUC, as currently they are **not** required to reject non-_Cpp17MoveInsertable_ types.

The standard wording seemly has defects - copy insertion is suggested by the standard and conditionally used by all mainstream implementations (when the move construction is potentially throwing and copy construction is available), but the "_Preconditions_:" is only mentioning _Cpp17MoveInsertable_.

This is not limited to `vector`'s `resize`. Perhaps almost all element-relocating operations of `vector` and `deque` are affected. I've tried to submit an LWG issue for this.

> Clang may be similar to GCC here

Yes. But libc++ [rejects non-(formally-)_Cpp17MoveInsertable_ types](https://github.com/llvm/llvm-project/blob/e624f8a3bb88075493dec521408993ea0ef7bde0/libcxx/include/__memory/uninitialized_algorithms.h#L588-L589) when conditional move-or-copy-insertion is used. (Note that Clang can be used together with libc++, libstdc++, and MSVC STL.)

**Comment by jwakely** [comment]
> According to the wording, the behavior would be UB if `T` is not `Cpp17MoveInsertable`, however, all major implementations have consistent behavior.

Which is one possible outcome of UB.

I'm closing this, there is no editorial issue here.

**Comment by xmh0511** [comment]
> Implementations are conforming here IIUC

From certain perspectives, you're right to say implementations are conforming here. Since the violation of precondition results in UB, which means the document imposes no requirement. Implementations are free to do anything here.  Since the behaviors of all mainstream implementations are similar, so I think we might expel the behavior from UB.

**Comment by jwakely** [comment]
No, that type is _Cpp17MoveInsertable_ into `vec`. There's no requirement to use a move constructor, just that construction from an rvalue passed to `allocator_traits::construct` works. You can pass an rvalue to that copy constructor.

**Comment by jwakely** [comment]
This issues list is not the right place to learn how vector works.

**Comment by jwakely** [comment]
> Since the behaviors of all mainstream implementations are similar, so I think we might expel the behavior from UB.

As stated above, libc++ has a static assert. So not the same.

**Comment by xmh0511** [comment]
The modified example is my original thought when wrote the comment. I'm not learning how to use vector, I just want to say the use of T that causes UB is widely used in actually code.

**Comment by jwakely** [comment]
No, because you can't use that type at all with `vector`. Your example doesn't even compile.

**Comment by jwakely** [comment]
> T that causes UB is widely used in actually code

I don't think this is true at all.

Type with `T(T&)` copy constructors and `T(T&&) = delete;` move constructors are unusual, and perverse, and generally not usable with the standard library containers.

**Comment by xmh0511** [comment]
> Your example doesn't even compile.

You're right, this is my oversight. However, the first example is indeed usable in actual code. Such as deep copy an object instead of using shallow copy.

**Comment by jwakely** [comment]
Deleting a move constructor is perverse. If you don't want it to be efficiently movable, just don't define a move constructor. Then you get deep copies of rvalues.

Getting undefined behaviour for such types is fine, they're irregular and unnecessary.
