### ISSUE TITLE
[basic.life]/8 Add a note about pointer to uninitialized memory

### ISSUE THREAD

**Issue by blackteahamburger** [cplusplus/draft#5782]
Transparently replaceable only applies to objects, so creating an object on uninitialized memory does not automatically make a pointer to the original uninitialized memory point to the newly created object.

Nothing in the standard mentions the above fact. It is recommended to add a note to provide clarity.

**Comment by languagelawyer** [comment]
What is
> a pointer to ... uninitialized memory

**Comment by blackteahamburger** [comment]
"uninitialized memory" refers to memory that does not have any objects on it.

**Comment by languagelawyer** [comment]
I think we do not have such things because we implicitly create objects. Also, my  question was about pointer, not about memory.

**Comment by jensmaurer** [comment]
@blackteahamburger , please give a code example.

**Comment by blackteahamburger** [comment]
> I think we do not have such things because we implicitly create objects.

Just call a function that doesn't do IOC:

```
void* p = __builtin_malloc(1);
new (p) char;
 __builtin_free(p);
```

**Comment by jensmaurer** [comment]
@blackteahamburger , this is not a conforming C++ program; its behavior is not specified by the standard. Do you have an example of a conforming program?

**Comment by languagelawyer** [comment]
> Just call a function that doesn't do IOC

IOC functions are not limited to those specified in the standard. Well, ofc, an implementation should define them as IOC, but implementations often ignore the requirement to specify implementation-defined things. I'd say you can treat `__builtin_malloc` as IOC.

**Comment by blackteahamburger** [comment]
I forgot that IOC do not start the lifetimes of subobjects of such objects that are not themselves of implicit-lifetime types... Just use `std::string`:

```
void* p = operator new(sizeof(std::string));    // does not implicitly create a std::string object
std::string* pstr = new (p) std::string;
*static_cast<std::string*>(p) = "str1";    // undefined behavior
*pstr = "str2";    // OK
```

**Comment by languagelawyer** [comment]
@blackteahamburger your concern is [basic.life]/8's
> after the lifetime of an object has ended

condition, and that the lifetime of the first element of the implicitly-created `std::string[1]` has never started?

**Comment by languagelawyer** [comment]
I think the
>  after the lifetime of an object has ended

condition is slightly misspelled. It does not mean that there necessarily shall be lifetime end, but that if there is lifetime end, it shall be properly synchronized (new object creation shall happen-after the lifetime end).

**Comment by tkoeppe** [comment]
I'm not sure if there's an editorial issue here. Please reopen if you have a clear improvement in mind.
