### ISSUE TITLE
[flat.map.defn,flat.multimap.defn] Deduction guide needs to default `Allocator` to be useful LWG3786

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#5800]
Is this right? What does it mean that the previous template parameter `Compare` is defaulted, but `Allocator` isn't, even though both corresponding function parameters are defaulted? Seems like you can't get this to work without defaulting this `Allocator`: https://godbolt.org/z/fYesrsbMz.

```suggestion
           class Allocator = allocator<ranges::range_value_t<R>>>
```
```suggestion
           class Allocator = allocator<@\exposid{range-mapped-type}@<R>>>
```

I think both suggestions fulfill the corresponding _Constraints_ element.

```suggestion
           class Allocator = allocator<void>>
```

_Originally posted by @JohelEGP in https://github.com/cplusplus/draft/pull/5626#discussion_r922744940_

See also https://github.com/cplusplus/draft/pull/5626/files#r922820452.

**Comment by cpplearner** [comment]
The affected deduction guides are

https://github.com/cplusplus/draft/blob/bc6d64c6745821c8e28d097aa381493e316fe4e0/source/containers.tex#L14934-L14937
https://github.com/cplusplus/draft/blob/bc6d64c6745821c8e28d097aa381493e316fe4e0/source/containers.tex#L16039-L16042

In these deduction guides, there's no `Allocator` on the right of `->`, which means the `Allocator` does not affect the result of deduction. So IIUC it doesn't matter what the default is, as long as there is a default.

**Comment by jensmaurer** [comment]
Something is strange here, but the fix doesn't seem to be editorially-obvious. Maybe we want to pass the Allocator parameter to the `vector` containers that are inside the `flat_map`?

@jwakely , this looks like a library issue to me.

**Comment by jwakely** [comment]
> @jwakely , this looks like a library issue to me.

Yes, I agree. Please submit one, @JohelEGP

**Comment by JohelEGP** [comment]
See https://cplusplus.github.io/LWG/issue3786.

**Comment by jwakely** [comment]
Thanks!

**Comment by JohelEGP** [comment]
Status: WP.
