### ISSUE TITLE
Add blanket wording for operator++(int) on iterators

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#5808]
We have several standard library iterators that define `operator++(int)` exactly the same way:

```
auto tmp = *this;
++*this;
return tmp;
```

We should add blanket wording saying that unless otherwise specified, an `operator++(int)` is defined that way, and similarly for `operator--(int)`.

**Comment by JohelEGP** [comment]
Duplicate of https://github.com/cplusplus/draft/issues/4690.

**Comment by jwakely** [comment]
Oops, forgot I already opened an issue for this, thanks.
