### ISSUE TITLE
replace `typedef` declarations with *alias-declaration*s in the library

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#581]
In library synopses, it would be better to use *alias-declaration*s rather than `typedef` declarations as our "house style".

(As discussed with various parties elsewhere.)

**Comment by sigfpe** [comment]
Amen.-------- Original message --------From: Richard Smith <notifications@github.com> Date: 12/8/2015  2:54 PM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Subject: [draft] replace `typedef` declarations with *alias-declaration*s in
  the library (#581) 
In library synopses, it would be better to use alias-declarations rather than typedef declarations as our "house style".

(As discussed with various parties elsewhere.)

**Comment by AlisdairM** [comment]
Is this something we want to do for C++17?  It is something I am, personally, keen to see happen, and if we believe this is entirely editorial, I am prepared to do the work of submitting many pull requests between now and Oulu.  The main question, once we confirm that we want to proceed, is what granularity should I exercise for a single pull request?

I would want to go fine-grained enough that a single pull request is (relatively) easy to review, but not so fine-grained that it swamps the queue.  The obvious granularity would be one clause at a time, as that is one file/request - but I fear that may be a little too big a bite to get right.

There is also the question of whether we should run it past LWG, or whether your previous discussion with various parties gives you confidence to proceed already?

**Comment by sigfpe** [comment]
Go for it! :-)-------- Original message --------From: Alisdair Meredith <notifications@github.com> Date: 4/11/2016  4:56 PM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Cc: sigfpe <sig.fpe@axiomatics.org> Subject: Re: [cplusplus/draft] replace `typedef` declarations with
  *alias-declaration*s in the library (#581) 
Is this something we want to do for C++17?  It is something I am, personally, keen to see happen, and if we believe this is entirely editorial, I am prepared to do the work of submitting many pull requests between now and Oulu.  The main question, once we confirm that we want to proceed, is what granularity should I exercise for a single pull request?

I would want to go fine-grained enough that a single pull request is (relatively) easy to review, but not so fine-grained that it swamps the queue.  The obvious granularity would be one clause at a time, as that is one file/request - but I fear that may be a little too big a bite to get right.

There is also the question of whether we should run it past LWG, or whether your previous discussion with various parties gives you confidence to proceed already?

**Comment by keryell** [comment]
Yes, it looks odd to have all these typedef everywhere...

**Comment by tkoeppe** [comment]
This should probably not be a "series of pull requests", but rather a single incantation of zygoloid's "carefully crafted regex"...

**Comment by AlisdairM** [comment]
I  have not looked into large-scale changes before, but still recommend a granularity of a pull request/file, to avoid getting into a state of every parallel commit possibly creating conflicts to resolve.  Also, I have no "carefully crafted regex" but would be happy to review the output of such, and manually highlight/fix any issues that need attention.

**Comment by zygoloid** [comment]
I've asked mclow and jyasskin for confirmation they're happy with this, but in principle I think this is a positive change and falls within the bounds of editorial discretion.

**Comment by jyasskin** [comment]
I believe it's editorial (there's no behavioral change, right?) and a good idea.

**Comment by mclow** [comment]
I have no objection, either.

**Comment by AlisdairM** [comment]
Confirm for Jeffrey that there is no behavioral change, it is a purely change of 'coding convention' for how we render our classes, in favor of something I think we all believe should be more readable.

**Comment by jwakely** [comment]
Fixed at c8f1863b67ce555c7576faddb50bd8707bfe0bee
