### ISSUE TITLE
[expr.unary.op] p10 The operand should be the promoted operand

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#5815]
[expr.unary.op] p10 says
> The operand of ~ shall have integral or unscoped enumeration type; the result is the ones' complement of **its operand**. Integral promotions are performed. The type of the result is the type of the promoted operand.

What is the operand refers to? It is more clear if we say
> The operand of ~ shall have integral or unscoped enumeration type. Integral promotions are performed on the operand. The result is the ones' complement of the (possible promoted) operand. The type of the result is the type of the promoted operand.

**Comment by frederick-vs-ja** [comment]
Should have been fixed by #5984 (68653fc432d180b713e5554df50a62e650fff751).
