### ISSUE TITLE
[expr.prim.lambda.capture]/8 Add a note explaining when capture is required

### ISSUE THREAD

**Issue by blackteahamburger** [cplusplus/draft#5824]
> If a lambda-expression or an instantiation of the function call operator template of a generic lambda odr-uses (6.2) this or a variable with automatic storage duration from its reaching scope, that entity shall be captured by the lambda-expression.

in [expr.prim.lambda.capture]/8 has been moved to [basic.def.odr]/9 because of [P0588R1](https://wg21.link/P0588R1). So now there is no relevant description in [expr.prim.lambda.capture]/8, which can be confusing.

**Comment by jensmaurer** [comment]
We can add a cross-reference to basic.def.odr after "odr-usable", which is the first appearance of the term here, if that clarifies things.

Otherwise, I'm not seeing a problem here.

**Comment by blackteahamburger** [comment]
I think it would be useful to explain it, since it is about lambda expressions after all.

**Comment by jensmaurer** [comment]
The standard is not a tutorial. If we have complicated rules, we shouldn't try to paraphrase them (likely incorrectly) in notes; we should add a cross-reference and that's it.
