### ISSUE TITLE
[over.best.ics.general] p6 is long

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#5825]
p6 is a bit unwieldy ... should we split it up into bullets?

It was always a big wall of text with two notes and an example in the middle, but our new way of putting those on a new line makes it look like it should really be separate paragraphs, or at least bulleted, or something.

Also, the new sentence added by [P1169R4 static operator()](https://wg21.link/p1169r4) seems like it's not really part of that paragraph, should it be split into a separate paragraph? With the current formatting it looks like it's only applicable to the last "sub-paragraph" of p6, about derived-to-base conversions, but it's not.

**Comment by tkoeppe** [comment]
See https://eel.is/c++draft/over.best.ics.general#6 for the current state.
