### ISSUE TITLE
placeholders::_2 is not indexed

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#5828]
It appears in the [functional.syn] synopsis, and in [func.bind.isplace] and [func.bind.place].

placeholders::_1 is indexed, but only once, not for the appearance in [func.bind.isplace].

**Comment by jensmaurer** [comment]
... and how many of those placeholder type names should we index?  Just _1 and _2, or up to _10, because that's the minimum specified in [implimits]?

**Comment by jwakely** [comment]
Yeah, I don't know what's right, but it certainly seems weird that we explicitly mention _2 in two places and don't index it at all (and only index one occurrence of _1).

**Comment by tkoeppe** [comment]
How about the 0, 1, many principle? Either we index nothing, or just `_1`, or everything, and the last option is not feasible?

**Comment by jensmaurer** [comment]
Users will see _1, _2, ..._10 in code (not more, because more is not portable), so I think we should index these in case someone seeks help in the standard to find out what this funny stuff is / does. It's just 3 places in total, so 10 x 3 items won't kill the indexer.

**Comment by tkoeppe** [comment]
OK, sure!

**Comment by jensmaurer** [comment]
We don't index appearances in the synopsis separately; we only index the definition.
