### ISSUE TITLE
Some exposition-only types are not formatted as such in the index

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#5832]
See `chunk_view`'s _inner-iterator_ and _outer-iterator_ and _sentinel_:

![image](https://user-images.githubusercontent.com/1254480/190143741-5749ef75-ba80-444f-a3d0-36793195b3cb.png)

And adjacent_transform_view and adjacent_view's _iterator_ and _sentinel_:

![image](https://user-images.githubusercontent.com/1254480/190144255-a7438b68-aa96-44ad-976a-77a517a73214.png)

And the index entries for their `base()` member of various iterator and sentinel types:

![image](https://user-images.githubusercontent.com/1254480/190144958-ad4db8b1-4912-47b5-9ee3-1e58084454d3.png)
![image](https://user-images.githubusercontent.com/1254480/190145086-c9bd1021-e8ea-4d55-bf2e-e9d6e75fdb72.png)

And so on ...

![image](https://user-images.githubusercontent.com/1254480/190145309-6733a38f-f59d-4d62-99f1-110fc87863b5.png)

![image](https://user-images.githubusercontent.com/1254480/190145377-a5273d87-fe11-438e-8098-d973c38e49ae.png)

![image](https://user-images.githubusercontent.com/1254480/190145450-35359d88-1e4d-47c0-bd48-60fad71c27f3.png)

![image](https://user-images.githubusercontent.com/1254480/190145521-c906e663-4949-4494-9944-a6186d5f1353.png)

![image](https://user-images.githubusercontent.com/1254480/190145566-b48e2c04-119e-4d59-836e-c1ab55e01339.png)

**Comment by jensmaurer** [comment]
We don't want to index exposition-only names at all, I think, because those are not names that could appear in user programs.

So, exposition-only member functions should not be indexed.

For exposition-only classes, we do want to index them, if/when they contain user-visible member functions (e.g. operators in case of views).

**Comment by tkoeppe** [comment]
@jensmaurer What about exposition-only members such as `move_only_function::is-callable-from`?

**Comment by jensmaurer** [comment]
All kebab-case names should be in exposition-italics. If you notice any that aren't, we should fix them.  But those exposition-only names cannot ever be called by users, so they shouldn't appear in the index of library names.

**Comment by W-E-Brown** [comment]
> On Sep 24, 2022, at 2:07 PM, Jens Maurer ***@***.***> wrote:
> All kebab-case names should be in exposition-italics. If you notice any that aren't, we should fix them. But those exposition-only names cannot ever be called by users, so they shouldn't appear in the index of library names.
> 
I respectfully disagree with this latter opinion, as the library index is the first place I would seek to find such names.  I wouldn't mind having these names in the general index as well, but it seems to me that a library-only artifact that, in fact, could be implemented as specified, ought be findable via a library-only index.

On further reflection, I would not object to such names' inclusion in a more general index, as well, but that wouldn't be the first place I'd look.  Whether an entity is callable seems not the best criterion, in my opinion, on which to base an indexing decision.

I briefly contemplated the notion of a separate index of exposition-only names, but I find myself lukewarm as to that idea.  Nonetheless, I would find that an acceptable compromise although it wouldn't be my first choice.

**Comment by jensmaurer** [comment]
@tkoeppe, we need a new issue here that we can mark "decision-required". I do agree the exposition-only names should be in some index (or several?); the question is which one. I'm not strongly opposed to the library names index if we add some intro paragraph explaining the typeface.

**Comment by tkoeppe** [comment]
We can open such an issue, but for now we have four straggling exposition-only names that remain in the library index, in the wrong place (namely right at the start), which doesn't seem all that useful, either.

Maybe we could put all the exposition-only names into the existing library index, but into a separate section?

**Comment by jensmaurer** [comment]
We should sort them in the proper alphabetical order; anything else amounts to a special index that nobody wants.

**Comment by tkoeppe** [comment]
The library index also serves as a list of reserved names (e.g. for the purpose of defining macros) so maybe there's some value in not "polluting" that list with names that don't affect actual programs, but only exist for the purpose of specification?
