### ISSUE TITLE
this_thread::get_id() is not related to psychoanalysis

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#5833]
> No other thread of execution has this id and this thread of execution always has this id.

Shouldn't "id" be "`id` value", or "identity", or something?

**Comment by jensmaurer** [comment]
The preceding text has "uniquely identifies the current thread of execution", so the first part "no other thread" is redundant anyway.

**Comment by tkoeppe** [comment]
Is there any concern about whether past or future threads might reuse IDs? Did the original "no other thread" wording imply anyhing stronger than just "uniquely identifies"?

**Comment by jensmaurer** [comment]
In practice, we can't prevent thread-id overflow anyway.
