### ISSUE TITLE
[ranges.syn] std::[ranges::]get([const ]subrange<I, S, K>&) is not marked freestanding

### ISSUE THREAD

**Issue by ArsenArsen** [cplusplus/draft#5837]
P1642 does not omit `get()` nor `subrange` from freestanding, so, presumably, this was an error.

**Comment by jwakely** [comment]
Those overloads were added to the synopsis by f400d80927fd580f99f5f2d94c3d07eaa47373d0 and P1642 said to make them freestanding, but maybe #5713 was based on an old revision?

**Comment by jwakely** [comment]
Ah f400d80927fd580f99f5f2d94c3d07eaa47373d0 was authored in April but not committed until after #5713 was merged.
