### ISSUE TITLE
[ranges.syn] `repeat_view`, `stride_view`, `cartesian_product_view` are not marked as freestanding

### ISSUE THREAD

**Issue by hewillk** [cplusplus/draft#5858]
I'm curious why they weren't added, please let me know if I'm missing something.

**Comment by tkoeppe** [comment]
Which paper proposed such a marking?

**Comment by JohelEGP** [comment]
See https://github.com/cplusplus/draft/issues/5733.

**Comment by jwakely** [comment]
> I'm curious why they weren't added, please let me know if I'm missing something.

They were not part of the working draft when P1642R11 was approved by LWG. The instruction to add *freestanding* to most of `<ranges>` does not mean "and also to anything that gets added in future".
