### ISSUE TITLE
[diff.library] NULL <cstdio> missing in Table 149

### ISSUE THREAD

**Issue by cubbimew** [cplusplus/draft#586]
`Table 133 — Header <cstdio> synopsis` mentions `NULL <cstdio>`
`C.5.2.4[diff.null]` mentions "The macro `NULL`, defined in .. `<cstdio>` .."
however
`Table 149 — Standard macros` lists only six NULLs. `NULL <cstdio>` is missing in this table.

**Comment by jwakely** [comment]
Fixed by merging the pull request - thanks.
