### ISSUE TITLE
[expected.expected] Missing explicit specification for unexpected-converting constructor

### ISSUE THREAD

**Issue by HunterKohler** [cplusplus/draft#5864]
Though shown in the individual constructor descriptions, the explicit specification of the unexpected-converting constructors `expected(const unexpected<G> &)`, and `expected(unexpected<G> &&)` are not shown in the class overview of `expected`. See the following descrepency:

https://github.com/cplusplus/draft/blob/14a10ef0948f4709cd1114c489b8e4b919ba7cbc/source/utilities.tex#L7239-L7242

https://github.com/cplusplus/draft/blob/14a10ef0948f4709cd1114c489b8e4b919ba7cbc/source/utilities.tex#L7562-L7565

I'll open a PR for the small change.

**Comment by jwakely** [comment]
This is [LWG 3754](https://cplusplus.github.io/LWG/issue3754).
