### ISSUE TITLE
[expr.const] Disjunction disqualifies `construct_at` of non-active member

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#5876]
> [6](https://eel.is/c++draft/expr.const#6)
[#](http://github.com/Eelis/draft/tree/b8cf1c46fd8fe0b5d509afc8944f2a2b3d29a515/source/expressions.tex#L7562)
[[...]](https://eel.is/c++draft/expr.const#6.sentence-1)
Similarly, the evaluation of a call to std​::​construct_­at or std​::​ranges​::​construct_­at ([[specialized.construct]](https://eel.is/c++draft/specialized.construct)) does not disqualify E from being a core constant expression unless the first argument, of type T*, does not point to storage allocated with std​::​allocator<T> or to an object whose lifetime began within the evaluation of E, or the evaluation of the underlying constructor call disqualifies E from being a core constant expression[.](https://eel.is/c++draft/expr.const#6.sentence-2)

According to the wording, this code should be ill-formed, but implementations accept it: https://compiler-explorer.com/z/f8Tjx8EK5.

```C++
#include <memory>
union num {
  int i;
  constexpr num() {
    std::construct_at(&i); // the first argument does not point
    // to storage allocated with std​::​allocator<T> or
    // to an object whose lifetime began within the evaluation of E
  }
};
static_assert(num{}.i == 0);
```

**Comment by frederick-vs-ja** [comment]
Perhaps this issue should be reported in the [CWG repo](https://github.com/cplusplus/CWG/issues). I think `expected` (probably alongwith `optional` and `variant` after [P2231R1](https://wg21.link/p2231r1)) can't work without such allowance.

**Comment by JohelEGP** [comment]
I'd prefer a [transfer](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository).

**Comment by JohelEGP** [comment]
Opened https://github.com/cplusplus/CWG/issues/155.
