### ISSUE TITLE
[ratio.ratio] What is `sign`?

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#5879]
> [(2.1)](https://eel.is/c++draft/ratio.ratio#2.1)
num shall have the value sign(N) * sign(D) * abs(N) / gcd[.](https://eel.is/c++draft/ratio.ratio#2.1.sentence-1)

**Comment by jwakely** [comment]
Signum: https://en.m.wikipedia.org/wiki/Sign_function

**Comment by JohelEGP** [comment]
Is it supposed to be defined by a normative reference? It's not defined by the WD.

**Comment by JohelEGP** [comment]
Based on https://eel.is/c++draft/intro.defs p1-p2, searching the databases does not show `sign` being defined by ISO/IEC 2382 nor ISO 80000-2:2009.

**Comment by jwakely** [comment]
It might be in ISO/IEC 10967, Language independent arithmetic (LIA) but I think we only refer to that in footnotes.

**Comment by JohelEGP** [comment]
I see that ISO 80000-2:2019 does define sgn (with verbal equivalent signum, Table 6, item no. 2-10.13).
