### ISSUE TITLE
Index of library names has exposition-only names under "Symbols"

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#5894]
These names (is-callable-from, is-vector-bool-reference and range-default-formatter) do not start with underscores (or any other symbol):

![image](https://user-images.githubusercontent.com/1254480/194526402-de57028c-45bd-478a-aa38-22c52596c39e.png)

**Comment by tkoeppe** [comment]
Yes, I've noticed this before, but wasn't able to fix it. We somehow need to modify the indexer macro to use a plain version of the text for collation, while retaining the fully marked up version for presentation. We already do this successfully for the impldef index, but I wasn't able to make it work for the library index.

**Comment by jensmaurer** [comment]
Before we do this, we should decide whether we actually want those exposition-only names in the library names index.
