### ISSUE TITLE
[range.repeat] The template parameter name `W` is confusing

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#5902]
Perhaps that name is copied from the specification of `iota_view`, where `W` is the initial of `weakly_incrementable`. However, the first template parameter of `repeat_view` is entirely unrelated to `weakly_incrementable`.

I think we should avoid superfluous mirroring of `iota_view`, and just call the template parameter `T`.

**Comment by CaseyCarter** [comment]
FWIW, I agree that this seems like false consistency and we should change it.

**Comment by jensmaurer** [comment]
Lots of agreement here. Patch welcome.
