### ISSUE TITLE
Use of "value" in [expr.const]/5

### ISSUE THREAD

**Issue by Arcoth** [cplusplus/draft#594]
> A _constant expression_ is either a glvalue core constant expression **whose value refers to an entity** that is a permitted result of a constant expression […]

The use of "value" in that context is confusing. Can this be improved?

**Comment by tkoeppe** [comment]
While you're here, could you take a look at https://github.com/cplusplus/draft/pull/541 please?

**Comment by jensmaurer** [comment]
"whose value" -> "that"?
