### ISSUE TITLE
Inconsistent Latex source for "const" in "(possibly const)"

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#5952]
We use all of the following in the spec:
* `(possibly \keyword{const})`,
* `(possibly \tcode{const})`, and
* `(possibly const)`

We should be consistent.

**Comment by JohelEGP** [comment]
See also https://github.com/cplusplus/draft/issues/117 and https://github.com/cplusplus/draft/issues/1497.

**Comment by burblebee** [comment]
Closing as a duplicate of #117.
