### ISSUE TITLE
[c.files] table 134 lists SCNX* macros, which do not exist

### ISSUE THREAD

**Issue by cubbimew** [cplusplus/draft#596]
[c.files] Table 134 - Header `<cinttypes>` synopsis mentions
`SCN{d i o u x X}[FAST LEAST]{8 16 32 64}`
`SCN{d i o u x X}{MAX PTR}`
but there are no SCNX* macros in C's `inttypes.h`, only SCNx*.

This contradicts [c.files]/4 "The contents of header `<cinttypes>` are the same as the Standard C Library header `<inttypes.h>`", and looks like a copy-paste error from the PRI* macros just above, which do come in both PRIx and PRIX variants.

**Comment by timsong-cpp** [comment]
I actually sent an email to lwgchair@ yesterday, since I wasn't sure if this counts as editorial. But if it can be handled editorially, all the better :)

**Comment by jwakely** [comment]
Resolved by merging #597
