### ISSUE TITLE
Lines run over the right margin

### ISSUE THREAD

**Issue by K-ballo** [cplusplus/draft#598]
Some lines run over the right margin, for example [tuple.cnstr]/5 and /9.

**Comment by tkoeppe** [comment]
Suggested solution: `is_default_construct\-ible<$T_i$>::value`, `std::for\-ward`.

**Comment by jensmaurer** [comment]
This is a special case of #693.

**Comment by jensmaurer** [comment]
Seems to have been fixed a while ago.
