### ISSUE TITLE
[time.clock.req] Fix punctuation of list p4

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#5980]
Item 4.2 https://eel.is/c++draft/time.clock.req#4.2 does not end in a comma, unlike other non-final items.

**Comment by tkoeppe** [comment]
OK, I can fix that after motions. Leave it with me.

**Comment by tkoeppe** [comment]
(Fixed by 9e41a1c27de2f676badacbe0c1aac783063b7cd6,)
