### ISSUE TITLE
[range.split] The example does not work after P2499R0

### ISSUE THREAD

**Issue by dangelog** [cplusplus/draft#6017]
https://eel.is/c++draft/range.split.overview#3 has this example:

```cpp
string str{"the quick brown fox"};
for (string_view word : views::split(str, ' ')) {
  cout << word << '*';
}
// The above prints the*quick*brown*fox*
```

This implicitly constructs a `std::string_view` out of each subrange obtained by `split`. This does not compile any more because the corresponding constructor has been made `explicit` by P2499R0, and `split` doesn't seem to have the same shortcuts that other views have (e.g. `take` out of `string_view` yields another `string_view`).

Possible solution: make the construction explicit:

```cpp
string str{"the quick brown fox"};
for (const auto& word : views::split(str, ' ')) {
  cout << string_view(word) << '*';
}
// The above prints the*quick*brown*fox*
```

**Comment by jwakely** [comment]
> Possible solution: make the construction explicit:

Yeah, this looks good to me.
