### ISSUE TITLE
[range.adjacent.transform.iterator, range.adjacent.transform.sentinel] unfriendly horizontal scroll bar

### ISSUE THREAD

**Issue by hewillk** [cplusplus/draft#6044]
The spaces of [[range.adjacent.transform.iterator]](https://eel.is/c++draft/range.adjacent.transform.iterator) and [[range.adjacent.transform.sentinel]](https://eel.is/c++draft/range.adjacent.transform.sentinel) have been compressed by nearly half, making it necessary to use the horizontal scroll bar below for full browsing. 

![image](https://user-images.githubusercontent.com/67143766/210304241-00827263-5880-4da5-8e86-045ec5aa38fb.png)

**Comment by cpplearner** [comment]
Is this a problem of https://github.com/Eelis/cxxdraft-htmlgen ?

cc @Eelis

**Comment by Eelis** [comment]
Thanks, should be fixed now.

**Comment by jensmaurer** [comment]
The PDF does not have horizontal scroll bars by definition, so this appears to be reporting an issue for something other than the rendered PDF. Please direct your concerns to the appropriate forum.
