### ISSUE TITLE
(primary-expression && ...) in a requires-clause

### ISSUE THREAD

**Issue by notbob-at-tessellation-com** [cplusplus/draft#6051]
Hello,

Today I am making my first posts to this group. Please forgive me if I make mistakes. Thank you.

Here is the context:

Header `<iterator>`:

```
template<class F, class... Is>
requires (indirectly_readable<Is> && ...) && invocable<F, iter_reference_t<Is>...>
using indirect_result_t = invoke_result_t<F, iter_reference_t<Is>...>;
```

Header `<variant>`:

```
template<class... Types> requires (three_way_comparable<Types> && ...)
constexpr common_comparison_category_t<compare_three_way_result_t<Types>...>
operator<=>(const variant<Types...>&, const variant<Types...>&);
```

A requires-clause has the following grammar:

requires-clause:
    requires constraint-logical-or-expression
constraint-logical-or-expression:
    constraint-logical-and-expression
    constraint-logical-or-expression || constraint-logical-and-expression
constraint-logical-and-expression:
    primary-expression
    constraint-logical-and-expression && primary-expression

In `<iterator>`, "`(indirectly_readable<Is> && ...)`", I understand "`indirectly_readable<Is>`" is a primary-expression, but "..." is not.
In `<variant>`, "`(three_way_comparable<Types> && ...)`", I understand "`three_way_comparable<Types>`" is a primary-expression, but "..." is not.

Am I misunderstanding something, or is this an error?

Thank you,

Robert Schwartz

**Comment by jwakely** [comment]
N.B. I've edited your original post to add markdown formatting, so it's rendered correctly, without &lt;iterator&gt; being treated as HTML markup.

**Comment by notbob-at-tessellation-com** [comment]
Will do, and thank you.

Robert

On Jan 18, 2023, at 9:36 AM, Jonathan Wakely ***@***.***> wrote:



This is not an editorial question, please use the std-discussion forum instead:
https://lists.isocpp.org/mailman/listinfo.cgi/std-proposals

**Comment by jwakely** [comment]
> Am I misunderstanding something, or is this an error?

To save you the time of going to std-discussion, you're misunderstanding. Those are both a _fold-expression_ in the grammar, see [expr.prim.fold]. You need to consider the whole expression, it's not ( _primary-expression_ && `...` ) it's all just a _fold-expression_.

**Comment by notbob-at-tessellation-com** [comment]
I didn't realize that. Thank you!

Robert

On Jan 18, 2023, at 9:39 AM, Jonathan Wakely ***@***.***> wrote:



N.B. I've edited your original post to add markdown formatting, so it's rendered correctly, without <iterator> being treated as HTML markup.

**Comment by notbob-at-tessellation-com** [comment]
Aha! Now I see. Thank you so much for explaining that!

Warm regards,

Robert

On Jan 18, 2023, at 9:42 AM, Jonathan Wakely ***@***.***> wrote:



Am I misunderstanding something, or is this an error?

To save you the time of going to std-discussion, you're misunderstanding. Those are both a fold-expression in the grammar, see [expr.prim.fold]. You need to consider the whole expression, it's not ( primary-expression && ... ) it's all just a fold-expression.
