### ISSUE TITLE
friend [[nodiscard]]

### ISSUE THREAD

**Issue by notbob-at-tessellation-com** [cplusplus/draft#6052]
Hello,

Today I am making my first posts to this group. Please forgive me if I make mistakes. Thank you.

Here is the context:

Header <stop_token>:

[[nodiscard]] friend bool operator==(const stop_token& lhs, const stop_token& rhs) noexcept;

I would have thought that this should be:

friend [[nodiscard]] bool operator==(const stop_token& lhs, const stop_token& rhs) noexcept;

i.e. the attribute pertains to the function, not to the friend declaration,
but I was told that an attribute cannot appear in this position,
hence it must be as it is in <stop_token>.

Perhaps the grammar should be amended to allow an attribute in this position?

What do you think?

Thank you,

Robert Schwartz

**Comment by jwakely** [comment]
Not editorial, please see https://github.com/cplusplus/draft/wiki/How-to-tell-if-an-issue-is-editorial

**Comment by notbob-at-tessellation-com** [comment]
I see. Where should I submit this?

Thanks,

Robert

On Jan 18, 2023, at 9:43 AM, Jonathan Wakely ***@***.***> wrote:



Not editorial, please see https://github.com/cplusplus/draft/wiki/How-to-tell-if-an-issue-is-editorial

**Comment by jwakely** [comment]
std-discussion makes sense, I think.

**Comment by notbob-at-tessellation-com** [comment]
Thank you!

Robert

On Jan 18, 2023, at 9:46 AM, Jonathan Wakely ***@***.***> wrote:



std-discussion makes sense, I think.

**Comment by jensmaurer** [comment]
Please read https://isocpp.org/std/submit-a-proposal
and be prepared to offer rationale why we need another round of complication of the "stuff before the declarator-id" in a declaration.
