### ISSUE TITLE
Attributes on hidden friends

### ISSUE THREAD

**Issue by dangelog** [cplusplus/draft#6054]
From this thread on the std-proposals ML: https://lists.isocpp.org/std-proposals/2023/01/5452.php

---

https://eel.is/c++draft/stoptoken.general declares the friend function

```
    [[nodiscard]] friend bool operator==(const stop_token& lhs, const stop_token& rhs) noexcept;
```

This declaration is to be taken as a hidden friend as per https://eel.is/c++draft/hidden.friends . As such, an implementation will have no choice but to immediately _define_ that function rather than just declare it.

However it's "mildly interesting" that the declaration above in the class synposis is actually ill-formed, per https://eel.is/c++draft/dcl.attr#grammar-5.sentence-3 :

> If an [attribute-specifier-seq](https://eel.is/c++draft/dcl.attr#nt:attribute-specifier-seq) appertains to a friend declaration ([[class.friend]](https://eel.is/c++draft/class.friend)), that declaration shall be a definition[.](https://eel.is/c++draft/dcl.attr#grammar-5.sentence-3)

AFAICS, [stoptoken.general] is the only place in the Standard Library where an attribute is used on a friend declaration.

I'm not sure if it should be fixed editorially somehow, for instance by adding another note to [hidden.friends] that says that such declarations may have attributes which are meant to be interpreted as attributes appearing on the definition, or something along those lines. Are there any other places where the Standard Library shows actual code (no "exposition only" / "see below" / etc.) that actually is ill-formed?

**Comment by jensmaurer** [comment]
We show (otherwise ill-formed) repeated default arguments in the various synopses, for example.

**Comment by dangelog** [comment]
Ok, so nothing to do, and one should "read between the lines" to interpret the synopsys code correctly?

**Comment by jwakely** [comment]
Yes, it tells you the API, it's not meant to be a conforming implementation.

**Comment by jensmaurer** [comment]
In particular, [intro.compliance.general] p4 says

> For functions, function templates, objects, and values, the library Clauses specify declarations. Implementations shall supply definitions consistent with the descriptions in the library Clauses.

So, this explicitly says the implementation must plug in a definition. Nothing to see here, I guess.
