### ISSUE TITLE
expression in requirement-seq no longer IFNDR due to DR2392

### ISSUE THREAD

**Issue by sunmy2019** [cplusplus/draft#6055]
https://eel.is/c++draft/expr.prim.req.general#5 has this example

```cpp
template<typename T> concept C =
requires {
  new int[-(int)sizeof(T)];     // ill-formed, no diagnostic required
};
```

This is previously IFNDR.

But with DR2392 accepted in Nov. 2022, for every `T`, this expression is well-formed whenever it is in an unevaluated context. We can even write `new int[-1]` in the requirement-seq, the program is well-formed.

https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2392
https://cplusplus.github.io/CWG/issues/2392.html

**Comment by sunmy2019** [comment]
I got another question.

In the standard, the following %1 and %2 are unevaluated operands
```cpp
template <typename T>
concept C = /* %1 */ true;

template <typename T>
concept CC = requires {
    requires /* %2 */ C<T>;
};
```
%1 is defined here: https://eel.is/c++draft/temp.concept#6
%2 is defined here: https://eel.is/c++draft/expr.prim.req#general-2

But clearly, they are evaluated and must evaluate to be true at compile time.

IMO, an unevaluated expression should be something we did not check its value, something like
```cpp
  // DR 2392
  template<class T = void> constexpr int f() { T t; return 1; }
  using _ = decltype(new int[f()]);
```
But we cannot write
```cpp
template <typename T>
concept C = foo();
```

So what's wrong here? Do I misinterpret anything?

**Comment by JohelEGP** [comment]
> But clearly, they are evaluated and must evaluate to be true at compile time.

They are evaluated when the naming a concept specialization outside unevaluated operands, and need not to evaluate to `true`.

**Comment by frederick-vs-ja** [comment]
I think the example is not definitely correct even before CWG2392 - since some implementation may allow large object types of size equal to `UINT_MAX + size_t(1)`, in which case `-(int)sizeof(T)` is `0` if `T` is such a type.
