### ISSUE TITLE
Petition to stop with versioning C++

### ISSUE THREAD

**Issue by elemanhillary** [cplusplus/draft#6057]
IMO, we should stop releasing new versions of C++ standards, let's borrow a leaf from C.
We are over stuffing the language with modules and libraries which will make us turn out like Javascript with a big library field that makes the language not a good first-to-go to language to learn as there's literally a library to do anything which i strongly believe its not C++ direction. Lets remain with the tradition of doing things like in the first versions of C++.

**Comment by tkoeppe** [comment]
This does not seem like an editorial issue. Please see https://isocpp.org/std for information on the standardization process.
