### ISSUE TITLE
Words in italics

### ISSUE THREAD

**Issue by FrankHB** [cplusplus/draft#606]
Italic words are only specified to be the terms or syntactic categories. What about other kind of usage, i.e. to emphasize?

For example, in [associative.reqmts]/4:

> The phrase “equivalence of keys” means the equivalence relation imposed by the comparison and _not_ the `operator==` on keys.

Here the word "not" is italicized. Is this intended?

BTW, for this particular half of the sentence, is it better to be a note or a footnote? Note that the `operator==` can mean equivalence relation on keys occasionally.

**Comment by jensmaurer** [comment]
I believe there is very little room in the C++ standard document for emphasis of words such as "not".

Regarding the normative status of that half-sentence: We could change that to a note, right.

**Comment by zygoloid** [comment]
[ Note: This is not necessarily the same as the result of the `operator==` on keys. ]
