### ISSUE TITLE
Why does `__cpp_lib_constexpr_bitset` have value 202202L instead of 202207L?

### ISSUE THREAD

**Issue by cpplearner** [cplusplus/draft#6065]
P2417R2 (A more constexpr bitset) was adopted in 2022-07 (#5679), but the feature-test macro got the value 202202L.

https://github.com/cplusplus/draft/blob/a009995257307b1ed8894718b70c917f4c25094b/source/support.tex#L595

What is the reason for that? Is that a mistake?

**Comment by jensmaurer** [comment]
My bug: https://github.com/cplusplus/draft/issues/6065
