### ISSUE TITLE
<print> header is missing in Table 118 

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#6072]
For C++23 we added a new `<print>` header but it's not shown in Table 118 [tab:iostreams.summary] . I would expect it to be shown with the other headers described in subclause 31.7.

**Comment by alexriegler** [comment]
This seems relatively easy to fix. I can give it a try. However, I don't think I can assign the issue to myself.

**Comment by jwakely** [comment]
Assigned, but we don't really use that field much - please feel free to submit a PR for anything without having it assigned to you :smiley:
