### ISSUE TITLE
[temp.over.link] Comment cut off in example 1

### ISSUE THREAD

**Issue by 8ightfold** [cplusplus/draft#6074]
In example 1 (https://eel.is/c++draft/temp.over.link#example-1), the comment for ``f(p)`` is cut off, displaying as ``// calls f<int>(int*``

**Comment by tkoeppe** [comment]
This repository of the draft standard sources has nothing to do with the website you mention; please report issues to the relevant maintainer of the website.

**Comment by 8ightfold** [comment]
Whoops. Will do.
