### ISSUE TITLE
[support.c.headers.other] Ambiguity in the requirements for includes

### ISSUE THREAD

**Issue by 8ightfold** [cplusplus/draft#6075]
In [support.c.headers.other], it states that the *<name.h>* headers behave "as if each name placed in the standard library namespace by the corresponding *<cname>* header is placed within the global namespace scope". There are exceptions for several different parts of the *<cname>* headers, but it's left unclear as to whether or not including them in their corresponding *<name.h>* is optional.

Is it optional to for things such as ``std::byte`` to be included in the corresponding .h, or are they required but not put in the global namespace? The note makes it seem as if it's the former, but it's still currently ambiguous.

**Comment by tkoeppe** [comment]
I'm not sure I understand the question, but whether `<stddef.h>` defined `std::byte` is unspecified, whereas it is guaranteed that `::byte` is _not_ defined by that header.

**Comment by 8ightfold** [comment]
That's what we wanted clarification on. As of now, it's not obvious that this is the case.

**Comment by 8ightfold** [comment]
I also just found out this isn't the place to submit issues like this. Thanks for your response.
