### ISSUE TITLE
Missing capture default in example 5.1.2.4

### ISSUE THREAD

**Issue by t-lutz** [cplusplus/draft#609]
The last two lines of the example read:

```
int j;
auto x3 = []()->auto&& { return j; }; // OK: return type is int&
```

However `j` is not captured and the lambda doesn't have a default capture. 

The correct code should be:

```
int j;
auto x3 = [&]()->auto&& { return j; }; // OK: return type is int&
           ^
```

**Comment by cpplearner** [comment]
I think `j` should be interpreted as having namespace scope, so it needn't (and can't) be captured.

**Comment by t-lutz** [comment]
My bad., I wrongly reproduced the example with `j` in a local scope.
