### ISSUE TITLE
[specialized.algorithms.general] The note seems incorrect

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#6143]
[[specialized.algorithms.general]/3](https://eel.is/c++draft/specialized.algorithms.general#3) says that:

> [_Note 1_: When invoked on ranges of potentially-overlapping subobjects ([intro.object]), the algorithms specified in [specialized.algorithms] result in undefined behavior. — _end note_]

However, this is a non-normative note, and maybe sometimes incorrect.

In this example
```C++
#include <memory>

int main()
{
    struct B {};
    struct D : B {};
    D d;
    std::construct_at(static_cast<B*>(&d));
    // or use an uninitialized_* algorithm to create a new B object
    // ... other operations
    std::construct_at(&d);
}
```
the newly created `B` object doesn't transparently replace the original base class subobject, and hence the lifetime of `d` is ended by the operation. But the program may still have well-defined behavior, as long as the pointer or reference to `d` or its base class subobject is carefully used.

**Comment by CaseyCarter** [comment]
Yes, we should just strike this note. I was trying to make a point that complete-object initialization "on top of" a subobject can zero tail padding bits where some other object lives, but this isn't a issue in the abstract machine were storage reuse ends the lifetime of "other object" anyway, and the note isn't clear enough to communicate anything but FUD in any case. We could change it to "can result in undefined behavior" to make it correct, but without any clarification I think it's still useless.

I no longer think it's worth our effort to try to warn people about that these footguns are even more footgunnish than the average C++ footgun. I think we should just strike the note.

**Comment by jwakely** [comment]
I'm confused by the removal of this note.

Previously, we had a somewhat inaccurate note pointing out that the uninitialized algos could result in problems when used with potentially overlapping subobjects. That warned me to be careful, even if it didn't tell me exactly what the problem was.

Now there's nothing. So are these algos no longer allowed to overwrite tail padding? Or they still are, we just expect users (and implementers) to figure that out? Because I can't figure it out. I would have preferred to add "can" to the note as Jens suggested on the PR.

**Comment by jwakely** [comment]
We could even do better than just adding "can", e.g.,

[Note: New objects created by the algorithms specified in [specialized.algorithms] can reuse storage occupied by other objects, including potentially-overlapping subobjects ([intro.object]), ending the lifetime of those other objects ([basic.life]).]

**Comment by jwakely** [comment]
Or we could say it conditionally, if...then...

[Note: If new objects created by the algorithms specified in [specialized.algorithms] reuse storage occupied by other objects, then the lifetimes of those other objects ([basic.life]) will end. This can include potentially-overlapping subobjects ([intro.object]) in the reused storage.]

**Comment by frederick-vs-ja** [comment]
I'll try to revive the note with the suggested wording...

**Comment by tkoeppe** [comment]
> Or we could say it conditionally, if...then...
> 
> [Note: If new objects created by the algorithms specified in [specialized.algorithms] reuse storage occupied by other objects, then the lifetimes of those other objects ([basic.life]) will end. This can include potentially-overlapping subobjects ([intro.object]) in the reused storage.]

But that would leave the reader to wonder, "but does this ever happen"? If this really _can_ happen, then it'd probably be worth saying that, and then you can follow up with consequences. "It can happen that [storage is reused], and in that case [lifetimes are ended]", etc.

**Comment by jwakely** [comment]
How about:

> When new objects are created by the algorithms specified in [specialized.algorithms], the lifetime ends for any existing objects (including potentially-overlapping subobjects ([intro.object])) in storage that is reused ([basic.life]).

**Comment by tkoeppe** [comment]
Very nice! Avoid all modal verbs. Facts don't care about your uninitialized_fillings.
