### ISSUE TITLE
LWG3906 [atomics.types.pointer], [atomics.ref.pointer] "Undefined address" is undefined

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#6185]
The term "undefined address" used in [atomics.types.pointer] and [atomics.ref.pointer] is probably related to undefined behavior mentioned in [expr.add], but the relation is not clear since the term itself seems undefined.

**Comment by jensmaurer** [comment]
This is not an editorial concern; please submit an LWG issue.

(I suspect we want "invalid pointer value" here, but I'm not sure.)

**Comment by frederick-vs-ja** [comment]
This is now LWG3906. Closing.
