### ISSUE TITLE
[intro.execution] p10 Ambiguous meaning with the "and"

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#6191]
[intro.execution] p10 says
> Except where noted, evaluations of operands of individual operators and of subexpressions of individual expressions are unsequenced.

We use "sequence" to describe the relationship between two evaluations. Say `o1` and `o2` are evaluations of operands of an individual operator, `s1` and `s2` are evaluations of an individual expression.

What does the sentence mean?
> 1. any of `o1` and `o2` is unsequenced with any of `s1` and `s2`
>2. `o1` is unsequenced with `o2`, `s1` is unsequenced with `s2`

The "and" in the sentence arises ambiguity. The improvement might be:

> Except where noted, the evaluations in the following are unsequenced: 
>> - evaluations of operands of individual operators
>> - evaluations of subexpressions of individual expressions

**Comment by xmh0511** [comment]
So, the constructive way is clearer here, I think.

**Comment by jensmaurer** [comment]
I disagree. You're using "in", which is ambiguous to whether it applies to the first level only, or all the way down.

**Comment by xmh0511** [comment]
> I disagree. You're using "in", which is ambiguous to whether it applies to the first level only, or all the way down.

> Except where noted, the evaluations of expressions are defined as:
>> - evaluations of operands of individual operators are unsequenced, or
>> - evaluations of subexpressions of individual expressions are unsequenced

That is, for `a + b`, we can use both the two bullets defined in the list to interpret the case.
