### ISSUE TITLE
No \idxhdr index entry for <chrono>

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#622]
There is an index entry for `chrono` (the namespace, presumably) but not for `<chrono>`

**Comment by AlisdairM** [comment]
This is addressed as a part of https://github.com/cplusplus/draft/pull/855 which also catches <any>, <ratio>, and <type_traits>.

**Comment by AlisdairM** [comment]
The fix for this was merged with https://github.com/cplusplus/draft/pull/861

**Comment by jwakely** [comment]
I see an entry for `<chrono>` in the library name index, but not the main one.

**Comment by jwakely** [comment]
There are loads missing from the main one, we only seem to have index entries for the C library headers and some freestanding ones such as `<exception>`, `<initializer_list>` and `<new>`.

**Comment by jwakely** [comment]
I've opened #940 for that, this original issue is fixed now.
