### ISSUE TITLE
[container.adapters] The `flat_*` container adapters need to index their members

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#6221]
A bulk of the specification for the `flat_*` container adapters is in the container requirements clauses, as they are both containers and adapters.  However, they are not listed for indexing in the clauses for containers, reversible containers, or associative containers.

I quickly hacked up a patch to do exactly that, but there were too many double-references where some members DO have "otherwise" documentation, so filing an issue as I do not have time to clean up properly right now.

**Comment by Quuxplusone** [comment]
I'd be willing to take this on as part of [P2767](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2767r0.html), since it'll merge-conflict heavily no matter what.

**Comment by jensmaurer** [comment]
Since indexing usually doesn't show up in any papers, I'd prefer to keep the indexing fixes as an editorial pull request.  I don't think there will be much conflict.

**Comment by AlisdairM** [comment]
This issue was addressed by #7288
