### ISSUE TITLE
[class.static.data] IFNDR case is not distinguished

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#6226]
[[class.static.data]/4](https://eel.is/c++draft/class.static.data#4) currently says:
> The member shall still be defined in a namespace scope if it is odr-used ([basic.def.odr]) in the program and the namespace scope definition shall not contain an _initializer_.

If I understand correctly, no diagnostic is required for the former case (covered by [[basic.def.odr]/11](https://eel.is/c++draft/basic.def.odr#11)), but diagnostic is required for the latter. Should we specify them more differently?

**Comment by jensmaurer** [comment]
I'm not seeing an imminent need. The presence of an initializer for a namespace-scope definition is clearly and easily checkable; the ODR violation already has a cross-reference into IFNDR territory.

**Comment by frederick-vs-ja** [comment]
> I'm not seeing an imminent need. The presence of an initializer for a namespace-scope definition is clearly and easily checkable; the ODR violation already has a cross-reference into IFNDR territory.

Agree. Closing since cross-reference is sufficient.
