### ISSUE TITLE
Why does the size of the PDF fluctuate between 5 MB and 11 MB?

### ISSUE THREAD

**Issue by HighCommander4** [cplusplus/draft#623]
The PDFs for N3690, N3797, N3936, and N4527 (as downloaded from http://www.open-std.org/jtc1/sc22/wg21) are a little over 5 MB in size.

For N4140, N4296, N4433, and N4567, they are a little over 11 MB.

Why is the size of the generated PDF fluctuating in this way?

**Comment by zygoloid** [comment]
The cause is that different versions of `pdflatex` have different defaults for PDF compression :( We should see if there's some way to control this from within the .tex file.

**Comment by jensmaurer** [comment]
Change 0ba033839ace7cbad8bb2122f4f5a8d2b18b2c46 added

> \pdfminorversion=5
> \pdfcompresslevel=9
> \pdfobjcompresslevel=2

to std.tex.
