### ISSUE TITLE
[defns.iostream.templates] This section doesn't seem helpful and may be misleading

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#6236]
It seems that [defns.iostream.templates] is not referenced elsewhere in the standard. And perhaps it's wrong to exclude `basic_stringbuf` and `basic_syncbuf` (and their friends).

Should we just remove this section?

**Comment by jwakely** [comment]
See [defns.character.container]. In C++98 and C++03 that said "It is used for one of the template parameters of the
string and iostream class templates." In C++11 it was changed to a note talking about "the string, iostream, and regular expression class templates".

So it's still used, but as "the string [class templates], iostream [class templates], and regular expression class templates". I don't think anybody will actually make the connection between that note and the definition though.

I think it would be OK to remove it, but maybe we should improve the note in [defns.character.container] to be more clear about what "string, iostream, and regular expression class templates" refers to. Maybe change it to:

>  It is used for the template parameter of `std::char_traits` and the class templates that use that, such as the string, iostream, and regular expression class templates.

**Comment by tkoeppe** [comment]
@jwakely Can you send a PR with that change?

**Comment by jwakely** [comment]
> @jwakely Can you send a PR with that change?

as-you-wish.gif
