### ISSUE TITLE
[dcl.attr.grammar] Braces of _balanced-token_ are unaligned

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#6239]
![1682699200](https://user-images.githubusercontent.com/21071787/235203159-3491ef27-fc3c-4f62-afbd-3d7b3b31066c.png)

Could this happen because the braces are escaped in the source?
```LaTeX
\nontermdef{balanced-token}\br
    \terminal{(} \opt{balanced-token-seq} \terminal{)}\br
    \terminal{[} \opt{balanced-token-seq} \terminal{]}\br
    \terminal{\{} \opt{balanced-token-seq} \terminal{\}}\br
    \textnormal{any \grammarterm{token} other than a parenthesis, a bracket, or a brace}
```

**Comment by jensmaurer** [comment]
Hm... Interesting.  Maybe "\{" expands to something that kills the alignment.

**Comment by tkoeppe** [comment]
Very odd, I can't figure out what's going on, either. @godbyk, might you have an idea?

**Comment by tkoeppe** [comment]
Ah, got it, microtype is causing this.

**Comment by tkoeppe** [comment]
E.g. see https://github.com/cplusplus/draft/blob/f52423c2a4d60d0ad653a3c8e2895037df016db0/source/lex.tex#L1034-L1035
