### ISSUE TITLE
[expr.static.cast] Paragraph 8 ends in a colon

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#6261]
See <https://eel.is/c++draft/expr.static.cast#8>.

**Comment by tkoeppe** [comment]
What is the problem with a paragraph ending in a colon?

**Comment by JohelEGP** [comment]
I'm not too sure if it's correct in English.
It seems to be used pervasively to introduce a list of items.
In this case, it seems to be doing that for the paragraphs that follow it.
When done for paragraphs, other wording uses "below" or something else instead of the style in [expr.static.cast]p8.

**Comment by tkoeppe** [comment]
I'm not convinced there's any problem here. The elaborating material is not just _somewhere_ below, but follows immediately. I don't see a pressing reason to change this.
