### ISSUE TITLE
[expr.add] Pointer subtraction when P-Q is out of range of ptrdiff_t is unclear

### ISSUE THREAD

**Issue by vasama** [cplusplus/draft#6268]
> Otherwise, if P and Q point to, respectively, array elements *i* and *j* of the same array object x, the expression P - Q has the value *i - j*.

When *i - j* is not in range of `ptrdiff_t`, this seems to be undefined behaviour due to [expr.pre]. The note on 5.3 should probably be moved here, and a reference to [expr.pre] added.

**Comment by jensmaurer** [comment]
Sounds good. Care to submit a pull request?
