### ISSUE TITLE
[meta.trans.other] Table 57 uses the layout for type predicates (Tables 47-49,51) instead of type transformations/queries (Tables 50,52-56)

### ISSUE THREAD

**Issue by cubbimew** [cplusplus/draft#629]
Table 57 "Other transformations" in 20.10.7.6[meta.trans.other] has three columns named "Template", "Condition", "Comments", which is how predicate tables (Table 47,48,49,51) are laid out. However, the traits listed in Table 57 are not predicates and do not test any condition. These are transformation traits, and the rest of those traits use two-column layout "Template", "Comments" (Tables 50,52,53,54,55,56)
The contents of the column named "Condition" in Table 57 where not empty appear to be the requirements on the template type parameters, which means they should move into Comments after the word "Requires:" as done for other transformation traits, namely in Tables 50 and 54

**Comment by jwakely** [comment]
Fixed by #747
