### ISSUE TITLE
[mdspan.submdspan] `full_extent_t` doesn't exist LWG3970

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#6353]
This subclause is added by #6338.
It uses `full_extent_t` and `full_extent`, which don't exist.

**Comment by tkoeppe** [comment]
@CaseyCarter, @jwakely: did you come across this during review by any chance? Do you recall if `full_extent` was discussed?

**Comment by JohelEGP** [comment]
Someone opened LWG3970.

**Comment by JohelEGP** [comment]
> Status: [WP](https://cplusplus.github.io/LWG/lwg-active.html#WP)
