### ISSUE TITLE
[func.wrap.ref.class, func.wrap.ref.deduct] Inconsistent parameter

### ISSUE THREAD

**Issue by JohelEGP** [cplusplus/draft#6362]
In the class synopsis:
```C++
  template<auto f>
    function_ref(nontype_t<f>, auto) -> function_ref<see below>;
```
> The detailed specifications uses a forwarding parameter.
> That's consistent with the actual constructors,
> as it doesn't require copy on the caller side when deducing.
> ```suggestion
>     function_ref(nontype_t<f>, auto&&) -> function_ref<@\seebelow@>;
> ```

In the deduction guide's detailed specifications:
```C++
template<auto f, class T>
  function_ref(nontype_t<f>, T&&) -> function_ref<see below>;
```
> The second parameter in the class synopsis is actually `auto`.
> That requires a copy, as opposed to `T&&`.
> So I can't solve this editorially _here_,
> but it can be done in the class synopsis.

> To be consistent with my suggestion on the class synopsis:
> ```suggestion
> template<auto f>
>   function_ref(nontype_t<f>, auto&&) -> function_ref<@\seebelow@>;
> ```

Originally: <https://github.com/cplusplus/draft/pull/6357#discussion_r1243901827>, <https://github.com/cplusplus/draft/pull/6357#discussion_r1243895084>.

**Comment by frederick-vs-ja** [comment]
Presumably `auto` shouldn't be used here, see CWG2697.

**Comment by JohelEGP** [comment]
Thank you.
For now, I suggested <https://github.com/cplusplus/draft/pull/6357#discussion_r1246605635>.
If that's not editorially accepted, an LWG issue might be needed.

**Comment by tkoeppe** [comment]
Could you please make a separate PR for this, after the motions?

**Comment by JohelEGP** [comment]
Yes.

**Comment by JohelEGP** [comment]
Opened #6398.
