### ISSUE TITLE
[basic.fundamental] Wording implies existence of unique maximum value of floating-point types

### ISSUE THREAD

**Issue by ilazaric** [cplusplus/draft#6370]
https://github.com/cplusplus/draft/blob/384d36a0d30e6a8050e23f7193db40fb56ff4f06/source/basic.tex#L5065-L5067

To me this implies existence of a **unique** maximum representable value of `float`
`float` values are not totally ordered, `NaN` is not comparable with anything
In terms of partial orders both `+inf` and all `NaN` values would be considered [maximal elements](https://en.wikipedia.org/wiki/Maximal_and_minimal_elements)

Same thought is applicable to other floating-point types, and to minimum instead of maximum

I feel that a person that is not familiar with IEEE-754 could come to wrong conclusions regarding floating-point types

I don't think a deep elaboration is needed or necessary
A simple `finite` word addition could be sufficient, would match `max()` behaviour of `std::numeric_limits`

**Comment by jensmaurer** [comment]
This is a note, and the mentioned facilities do allow to query for NaNs as well as infinities and finite min/max values, so I'm not seeing anything wrong here. We don't mention a `max`  facility in particular.

**Comment by jwakely** [comment]
And adding "finite" wouldn't make sense for the integral types. I don't think anything needs to change here.

**Comment by jwakely** [comment]
Specifically, I don't think anybody is drawing conclusions about floating point types from this piece of wording.
