### ISSUE TITLE
Cherrypicks for the C++23 IS

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#6415]
Please list any commits since N4950 that should be cherrypicked into the C++23 IS. This should only happen for fixes of technical faults and important clarifications.

**Comment by tkoeppe** [comment]
https://github.com/cplusplus/draft/commit/f61a2c8a847e846ba1167c876b0fc1532ab433d7

**Comment by jwakely** [comment]
ae3f6e8260aede8b5f9ec42347af58e29631f3dd the xrefs to [container.requirements.general] are baffling nonsense, because that subclause doesn't define any of the things that the cross-references are trying to refer to.

Similarly, 708cacb4bbe60c13985b8a8e025557f74bbfa405 (not merged yet, see #6255) and maybe edcde07a059e95a71de6ab1315a6ed1ca5d19ef8 (also not merged yet, same PR).

**Comment by tkoeppe** [comment]
Is 4fac9f97a2c25d39a01f75cf198d0783bfa8deda the linked version of the first change you mention?

**Comment by tkoeppe** [comment]
We'll also need to reverse-backport the xrefdelta then, so that there will now no longer a diff with C++23.

**Comment by tkoeppe** [comment]
https://github.com/cplusplus/draft/pull/6531 for Unicode examples

**Comment by tkoeppe** [comment]
Making a manual change similar to 9369ba13509cd5d2c9e862b7ad02f109c204a585.

**Comment by tkoeppe** [comment]
https://github.com/cplusplus/draft-private/commits/c++23-is for ISO/CS-03

**Comment by tkoeppe** [comment]
7ed9cbfef44d15b798af83223f5d3b62927652a5 for ISO/CS-04

**Comment by tkoeppe** [comment]
a9e7d80d46b43127bfaccd3202d3ea16d282943e for ISO/CS-29

**Comment by tkoeppe** [comment]
f21cca505c99a4b1d6ba881d17beeaf2cf740d00 for ISO/CS-30

**Comment by tkoeppe** [comment]
f52c4dccfeafc6e385323e9d8cebf6213a4f49ce for ISO/CS-18

**Comment by tkoeppe** [comment]
722bd4f167badc5bb5dddde9b0d00f91c2ef1644 for JP-25

**Comment by tkoeppe** [comment]
f58dd250cf8ac51609e98b5e96ebe62cd0e2a029 for JP-24

**Comment by tkoeppe** [comment]
400521547f60196f6dfa7857bdcc907698991df8 for JP-23

**Comment by tkoeppe** [comment]
bd7f9a9e640bfcd204cabecf1cc4953b7138554e for ISO/CS-34

**Comment by tkoeppe** [comment]
https://github.com/cplusplus/draft/pull/6611 for ISO/CS-39

**Comment by tkoeppe** [comment]
d29b1fc1c22018b1a83cee910ebdbb4520d2c960 e128de19470877fbf8f0335b8c0e2a1700f2e320 for ISO/CS-08

**Comment by tkoeppe** [comment]
4d603c640dd47c71f84bbce55416302efab8b298 for ISO/CS-09

**Comment by tkoeppe** [comment]
8f79c15da5892775a63d0587eba53165cc8390dc for ISO/CS-11 and -16.

**Comment by tkoeppe** [comment]
4c76193e3d310ea5a18679ab86a54074fe1635e9 for ISO/CS-15.

**Comment by tkoeppe** [comment]
f672ecf38d2aec6ccf184d1a36bc4e83809afab0 for ISO/CS-035.

**Comment by tkoeppe** [comment]
2d6182932954732f71a28d90ec1f1b23838ccc67 partially towards ISO/CS-02.

**Comment by tkoeppe** [comment]
4676f765f696774807688c3adfdc2eb03905a827 for ISO/CS-01

**Comment by tkoeppe** [comment]
For removed terms, we need to add the relevant "deleted xrefs" entries in the IS. (The C++2c WD is not affected.)

**Comment by tkoeppe** [comment]
4a6f2e3f4791c44b8c8f32a75d0bebac4a7b6a9e for ISO/CS-02

**Comment by tkoeppe** [comment]
eb7f0bcbff2af109643089ef36dfe67040a27f4a for ISO/CS-17. That should be the last one.

**Comment by jwakely** [comment]
What about #6695, maybe not important enough?

**Comment by tkoeppe** [comment]
I did add that, too, but didn't make a note here :-S
