### ISSUE TITLE
References to tables in Clause 28 should use "Table" not "table"

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#647]
e.g. 28.5.1 [re.synop] says "has the effects listed in table 155" but elsewhere references to tables use an uppercase T.

**Comment by burblebee** [comment]
This is a general problem elsewhere in the spec for which I was about to open a github issue for.  OK to just tackle them all in this issue?  If not, please open an issue for the general case.

**Comment by jwakely** [comment]
I agree it makes sense to do it all under this issue.

**Comment by jensmaurer** [comment]
This seems to be fixed as of now.
