### ISSUE TITLE
[format.string.std]/4: sC example doesn't have enough clowns

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#6474]
https://github.com/cplusplus/draft/blob/a272b7cd04dc0be488250a0c6aaead160e778774/source/utilities.tex#L15920

The string being formatted should have three clowns, not one.

**Comment by tkoeppe** [comment]
@tahonermann Could you have a look and verify this bug?

**Comment by tkoeppe** [comment]
Seems like there was indeed not enough clownery :-(

**Comment by tahonermann** [comment]
Good catch, @timsong-cpp . @tkoeppe had asked me to verify that the DIS looked right quite some time ago and I confirmed it did. Alas, I was apparently so excited to see clowns at all that I neglected to count them :(

It looks like there are some FIXME comments that can probably be removed when correcting this:
- https://github.com/cplusplus/draft/blob/main/source/utilities.tex#L15904-L15905.
- https://github.com/cplusplus/draft/blob/main/source/utilities.tex#L17142-L17144
