### ISSUE TITLE
[enum.copy_options] refers to "Filesystem library"

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#649]
> Calling a Filesystem library function with more than a single constant for an option group results in undefined behavior.

It's not clear what counts as "a Filesystem library function" now that the content has moved from the TS to the IS.

**Comment by zygoloid** [comment]
I fixed this editorially by dropping the "Filesystem". Only functions within [filesystems] take these types, which seems to properly scope this rule to the relevant functions.

**Comment by jwakely** [comment]
I thought about that, but wondered whether someone would misread it to suggest that passing one of those options to a function template such as `make_pair` would be undefined if conflicting bits are set.
