### ISSUE TITLE
Broken or unsightly iref links after line breaks after #5151

### ISSUE THREAD

**Issue by ecatmur** [cplusplus/draft#6504]
After #5151, some iref links are broken or unsightly where the iref parameter list extends across a line break; for example, https://github.com/cplusplus/draft/blob/1c22d62180901069128b21daa2773d40566bd983/source/basic.tex#L600-L601 renders as:

> an expression is converted (either implicitly or explicitly) to type T ([[conv]](https://eel.is/c++draft/conv), [[expr.type.conv]](https://eel.is/c++draft/expr.type.conv), [[ expr.dynamic.cast]](https://eel.is/c++draft/expr.dynamic.cast), [[expr.static.cast]](https://eel.is/c++draft/expr.static.cast), [[expr.cast]](https://eel.is/c++draft/expr.cast)), or

and https://github.com/cplusplus/draft/blob/1c22d62180901069128b21daa2773d40566bd983/source/basic.tex#L3725-L3726 as:

> the operand of a cast or conversion ([[conv.integral]](https://eel.is/c++draft/conv.integral), [[ expr.type.conv]](https://eel.is/c++draft/%20%20%20%20expr.type.conv), [[expr.static.cast]](https://eel.is/c++draft/expr.static.cast), [[expr.cast]](https://eel.is/c++draft/expr.cast)) to an unsigned ordinary character type or std​::​byte type ([[cstddef.syn]](https://eel.is/c++draft/cstddef.syn)), or

In the first case, the iref to expr.dynamic.cast has unsightly extra space but the link works, but in the second case the link to expr.type.conv is itself broken, having extra spaces within the link target, probably because the second case is indented.

**Comment by JohelEGP** [comment]
Sounds like an issue for <https://github.com/Eelis/cxxdraft-htmlgen>, not this repository.

**Comment by ecatmur** [comment]
Thanks!
