### ISSUE TITLE
Section headings should use \hypertarget

### ISSUE THREAD

**Issue by t3nsor** [cplusplus/draft#6510]
It would be very useful if we could directly link to a particular section in a PDF version of the standard, e.g., `https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/n4958.pdf#dcl.init.general` should open the PDF at page 211.

This could be accomplished by inserting a `\hypertarget` command, perhaps in the definition of the `\Sec` macros, or in the definition of `\addxref`.

**Comment by Eelis** [comment]
That would be awesome! (Even though it would put cxxdraft-htmlgen out of business... ;-))

**Comment by tkoeppe** [comment]
Can you prototype this and check that this would actually work?

**Comment by JohelEGP** [comment]
> (Even though it would put cxxdraft-htmlgen out of business... ;-))

Hardly.
This may be a big use case,
but there's so much more you can do with HTML
that a PDF can't AFAIK.

**Comment by t3nsor** [comment]
I'll prototype it soon when I get the chance.

The main motivation for this is for the links to be stable. If I have a paper in the mailing that links to a particular section of the standard, it should be a link that will always be to the particular working draft that was the most recent one at the time the paper was written. But I imagine people will still use eel.is most of the time when such stability isn't required.

**Comment by t3nsor** [comment]
Please see the above PR. I've built it locally and confirmed that it works. I haven't uploaded the PDF, as I wouldn't want to be accused of violating ISO policy somehow, but please see more details on the PR.

**Comment by leni536** [comment]
FTR https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/n4958.pdf#subsection.9.4.1 works for me on the current PDF. You can get the link by right clicking the outline element in Firefox, but AFAIK the link should work in other browsers too.

But I do like the better fragment identifiers introduced here.

**Comment by JohelEGP** [comment]
> but AFAIK the link should work in other browsers too.

I remember it being the other way around.

**Comment by leni536** [comment]
> > but AFAIK the link should work in other browsers too.
> 
> I remember it being the other way around.

I know two kinds of fragment id links that get resolved in some browsers:

1. Fragment id that refers to an outline element by outline name:
  * https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/n4958.pdf#9.4.1%20General
  * This works in Chrome, doesn't work in Firefox
2. Fragment id that refers to a PDF "bookmark"
  * https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/n4958.pdf#subsection.9.4.1
  * Works in both Firefox and Chrome
  * The link can be obtained by right clicking on the outline element in Firefox.

I meddled with this part of the PDF spec a bit at my previous workplace.

**Comment by t3nsor** [comment]
Bump. Anything needed from me? I'd be really happy if this could get merged before the next working draft.

**Comment by t3nsor** [comment]
Bump
