### ISSUE TITLE
[dcl.attr.assume] Contradictory wording around contextual conversion

### ISSUE THREAD

**Issue by Eisenwave** [cplusplus/draft#6512]
[[dcl.attr.assume]](https://eel.is/c++draft/dcl.attr.assume) says:
> The expression is contextually converted to `bool`. The expression is not evaluated. If the converted expression would evaluate to true at the point where the assumption appears, the assumption has no effect.
Otherwise, the behavior is undefined.

This wording is mildly contradictory because the first sentence says that contextual conversion takes place. This might even invoke user-defined conversion operators, so the reader should assume that something is being evaluated here.

However, this is then contradicted by saying that the expression is not evaluated. If it's not evaluated, then obviously contextual conversion can't take place.

I think it would be much clearer to write:
```diff
-The expression is contextually converted to bool.
+The expression shall be contextually convertible to bool.
 The expression is not evaluated.
 If the converted expression would evaluate to true at the point where the assumption appears,
 the assumption has no effect.
 Otherwise, the behavior is undefined.
```
I am not sure if this issue is so severe that it's non-editorial.

**Comment by Eisenwave** [comment]
Hmm, I think it might really be non-editorial, because the wording only says that the expression is not evaluated, but it does not say that the contextual conversion is not evaluated.

This is obviously unimplementable, because an implementation can't contextually convert the result of an expression that doesn't exist, because the expression has never been evaluated.

**Comment by Eisenwave** [comment]
Or maybe I'm misunderstanding things. https://eel.is/c++draft/conv#def:contextually_implicitly_converted The away that contextual conversion is worded, it doesn't imply evaluation in itself.

**Comment by jensmaurer** [comment]
The talk about conversions here is just about creating the syntax tree (with some implicit nodes). Whether that syntax tree is evaluated, is a second consideration.
