### ISSUE TITLE
[rand.device] Weird text style in comment

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#6513]
https://github.com/cplusplus/draft/blob/3d62863c44813e8b8442a1c32231ea7a13cfe192/source/numerics.tex#L3634

This produces:

![image](https://github.com/cplusplus/draft/assets/22357/0c020762-9395-4210-9d9d-25eda401c953)

I'm not sure if the odd style had some intended purpose.

**Comment by tkoeppe** [comment]
There's a weird stray `\textit` there. Feel free to send a PR to remove it!

**Comment by tkoeppe** [comment]
(It's also an overall weirdly colloquial comment.)

**Comment by jwakely** [comment]
We should just remove the comment and move the declaration next to the other constructors.

**Comment by tkoeppe** [comment]
I suppose this comes from a time when deleted members were new and everyone was excited to put them to use?

**Comment by jwakely** [comment]
And explain them!

**Comment by JohelEGP** [comment]
The synopsis generally doesn't follow <https://eel.is/c++draft/structure.specifications#2>.
