### ISSUE TITLE
"ith" should be consistently formatted

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#653]
Sometimes we use "ith", sometimes we use "$i^{th}$", etc.

**Comment by tkoeppe** [comment]
If you're going with the maths notation, then it should be `$i^\text{th}$`.

**Comment by tkoeppe** [comment]
Following 48efdfe014549e6d116ce12ca427f7df0e0f8c70, there's still work left to be done in the later parts of  [tuple.tuple].

**Comment by tkoeppe** [comment]
(I've been following my recommended style on and off when I happen across relevant text, though I haven't actively sought them out.)

**Comment by godbyk** [comment]
@tkoeppe Would it be better to create an `\ith` macro to help ensure consistency?

**Comment by tkoeppe** [comment]
@godbyk: I'd be strongly against that. Text and maths is the bread and butter of LaTeX, and `$i^\text{th}$` is perfectly readable. Every new macro carries a heavy mental cost and needs to be carefully justified: readers need to know what it means, writers need to remember to use it, and the more trivial the subject the more arbitrary the macros become. We also don't define macros for `the behavior is undefined`, say, even though that's a much more common phrase. Macros shouldn't just zlib-compress the text, they should factor out conceptual units.

**Comment by godbyk** [comment]
@tkoeppe  My proposed macro isn't about compression or saving a few keystrokes; it's about ensuring consistency.

I propose that it's easier for an author less accustomed to LaTeX and the finer points of typesetting to remember `\ith` than `$i^\text{th}$`.  After all, if everyone naturally typed `$i^\text{th}$`, this bug report wouldn't exist.

Macros also offer more flexibility when it comes to changing styles. If you later decide that `$i\text{th}$` is better than `$i^\text{th}$`, for instance, you must only change it in one place.

A better counter-argument would be, “What about `$j^\text{th}$` and `10000^\text{th}` and `$\tcode{I}^\text{th}$`?”  And for that I'd still recommend a macro that appends <sup>th</sup>. For example:

```latex
\let\thorn\th% stealing \th for our own purposes
\def\th{\ensuremath{{}^\text{th}}}

$i\th$  \qquad  \tcode{N}\th  \qquad  7\th
```
