### ISSUE TITLE
Add a `ranges::to_container(T container)` which accepts a reusable container

### ISSUE THREAD

**Issue by dongweigogo** [cplusplus/draft#6548]
According to C++23 draft, there will be a ranges::to() to be implemented.

> Constructing containers and strings from ranges with [ranges::to()](https://en.cppreference.com/w/cpp/ranges/to), tagged constructors, insert and assign member functions.  
[P1206R7](https://wg21.link/P1206R7)

I tested ranges::to() in develop version of clang because current gcc does not support. It works but I found that it has a rather poor performance.

`
vector<int> v
auto vec  = views::iota(-10, 10) | views::filter([](int i) {return i>0;}) | ranges::to<vector<int>>();`

I think that the main reason is that a new container has to be created every time the view runs. Thus it is reasonable if we could supply a variant ranges::to() which accept a reusable container as a parameter. like ranges::to_container(T container).

There are at least two benefits based on the above thought:
1. The reusable container can avoid unnecessary reallocating ;
2. We can collect different views into a same container;

Since ranges::to() is somehow similar to collect() in rust lang, I found a couterpart of ranges::to_container(T container) there:

`a.iter().collect_into(&mut vec);`

The collect_into() is what I would like to propose.

**Comment by jwakely** [comment]
This repository is just for the text of the standard, not for proposed changes or additions to the standard. Please see https://isocpp.org/std/submit-a-proposal instead.

**Comment by frederick-vs-ja** [comment]
Such a stuff is almost same as `c.assign_range(expr)` except that it returns a reference to `c`.

If you don't need to immediately refer to the container in the same expression, you can just use `assign_range`.
