### ISSUE TITLE
[basic.start.main] Clarify what it means to "use" `main` CWG2811

### ISSUE THREAD

**Issue by Eisenwave** [cplusplus/draft#6563]
The current wording in [[basic.start.main] p3](https://eel.is/c++draft/basic.start.main#3) is:
> The function main shall not be used within a program.

There is no forward reference for what "use" refers to and the word doesn't seem to be defined anywhere, so I'm pretty sure this is meant to mean *odr-use*:

> A function is odr-used if it is named by a potentially-evaluated expression or conversion.

\- [[basic.def.odr] p8](https://eel.is/c++draft/basic.def.odr#8)

1. Can we just replace "use" with "odr-use"?
2. Is CWG intent clear enough for this to be non-editorial or is there more to it?

### C++98 Wording

> The function main shall not be used (3.2 [basic.def.odr]) within a program.

\- [[basic.start.main] p3](https://open-std.org/JTC1/SC22/WG21/docs/wp/pdf/nov97-2/body.pdf)

> An object or non-overloaded function is *used* if its name appears in a potentially-evaluated expression.

\- [[basic.def.odr] p2](https://open-std.org/JTC1/SC22/WG21/docs/wp/pdf/nov97-2/body.pdf)

**Comment by Eisenwave** [comment]
Alternatively this could adopt the wording for deleted functions in [[dcl.fct.def.delete] p2](https://eel.is/c++draft/dcl.fct.def.delete#2):

> A program that refers to a deleted function implicitly or explicitly, other than to declare it, is ill-formed.

**Comment by Eisenwave** [comment]
@jensmaurer [your paper](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3214.htm) replaced "use ([basic.def.odr])" with "use".

Why is odr-use not the right interpretation here, and what is?

**Comment by t3nsor** [comment]
Frustratingly, I can't find anything in the meeting minutes about why this change was made between N3154 and N3214. See https://stackoverflow.com/a/25298934/481267

I don't think it's editorial. I think CWG should try to come to an agreement about what it's supposed to mean.

**Comment by Eisenwave** [comment]
@t3nsor I was initially confused too, but look at the C++98 wording I've edited into the answer. In C++98, the paragraph for `main` literally references *use* (subsequently renamed to odr-use).

It looks like a purely editorial issue where someone forgot to replace "use" with "odr-use" when the term was renamed.

**Comment by t3nsor** [comment]
No, look at the difference between N3154 and N3214. It appears to be intentional.

**Comment by Eisenwave** [comment]
You're probably right, but then what does "use" even mean? It used to have a definition but now it's pretty meaningless. There should at least be a note which clarifies what constitutes "use" of `main`.

**Comment by t3nsor** [comment]
That's the problem: I don't think anyone knows for sure what it means, so this should go to CWG. Especially since the language has evolved so much that there may be new questions to consider that may not have existed in C++11.

**Comment by jensmaurer** [comment]
I'm pretty sure CWG left "use" in there because it wasn't clearly "odr-use" that was intended here, but the paper to introduce "odr-use" was important enough not to get hung up over it.

We need answers for `decltype(::main)` as well as `sizeof(&::main)`, for example. It's plausible that forming even an unevaluated pointer-to-main is hard to support on some platforms (because it might have a type that is not representable in C++).

**Comment by frederick-vs-ja** [comment]
Is this resolved together with CWG2811?
