### ISSUE TITLE
[tab:headers.cpp] `<hazard_pointer>` is hazardously missing

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#6585]
[N4958](https://isocpp.org/files/papers/N4958.pdf) contains `<hazard_pointer>` but forgot to mention it in The Table:

https://github.com/cplusplus/draft/blob/34cf81ebc821377eb3969002e4669bf5e08f479f/source/lib-intro.tex#L1105-L1108

**Comment by jensmaurer** [comment]
Oh no, a disaster.
