### ISSUE TITLE
[thread.lock.guard] Does not take into account storage reuse

### ISSUE THREAD

**Issue by jeremy-rifkin** [cplusplus/draft#6588]
[[thread.lock.guard] p1](http://eel.is/c++draft/thread.lock.guard#1.sentence-2) reads
> A lock_guard object maintains ownership of a lockable object throughout the lock_guard object's [lifetime](http://eel.is/c++draft/basic.life#def:lifetime)[.](http://eel.is/c++draft/thread.lock.guard#1.sentence-2)

Yet in the following (ostensibly) valid program ownership is not maintained throughout the lock_guard object's lifetime:

```cpp
std::lock_guard<std::mutex> lock(mutex);
new (&lock) char[sizeof lock]; // http://eel.is/c++draft/basic.life#1.5
std::mutex dummy_mutex;
new (&lock) std::lock_guard<std::mutex>(dummy_mutex);
```

**Comment by CaseyCarter** [comment]
I don't understand. Are you suggesting that `lock` somehow relinquishes ownership of `mutex` before `new (&lock) char[sizeof lock]` ends its lifetime by reusing its storage?

**Comment by jeremy-rifkin** [comment]
Thank you for your quick response, I'm happy to clarify

> Are you suggesting that `lock` somehow relinquishes ownership of `mutex` before `new (&lock) char[sizeof lock]` ends its lifetime by reusing its storage to hold an array of characters?

No, that'd be impossible.

Let me preface this by saying it's entirely possible I'm misreading / misunderstanding but to me [[thread.lock.guard] p1](http://eel.is/c++draft/thread.lock.guard#1.sentence-2) implies that it should release the mutex when its lifetime ends. But in this case the `mutex` is not unlocked.

**Comment by CaseyCarter** [comment]
"I check my email frequently while I am at work" implies nothing about my email-checking frequency when I'm at home. I might not check at all, or check rarely, or check frequently. None of those would contradict the fact that I check frequently while I am at work.

Similarly, "A lock_guard object maintains ownership of a lockable object throughout the lock_guard object's lifetime" says nothing about what a `lock_guard` object may or may not do outside its lifetime. A zombie `lock_guard` continuing to own a lockable object may not be ideal, but it still doesn't contradict a statement about the behavior of living `lock_guard` objects.
