### ISSUE TITLE
[stmt.return] p5 "which" is ambiguous in the sentence

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#6616]
[stmt.return] p5 says:
> The copy-initialization of the result of the call is sequenced before the destruction of temporaries at the end of the full-expression established by the operand of the return statement, **which**, in turn, is sequenced before the destruction of local variables ([stmt.jump]) of the block enclosing the return statement.

What does the `which` in the sentence refer to?  It can be read as
> 1. "which" refers to "The copy-initialization of the result of the call"
> 2. "which" refers to "the destruction of temporaries"

According to this example:
````cpp
#include <iostream>
struct Drop{
    Drop(int id):id_(id){

    }
    int id_;
    ~Drop(){
        std::cout<<"drop "<< id_<<std::endl;
    }
};
int g(){
    Drop x{0};
    {
        Drop y{1};
        return ((Drop&&)Drop{2},0);
    }
    return 1;
}
int main(){ 
   auto c = g();
   std::cout<<"main\n";
}
````
The outputs are consistent in major implementations, which is
```
drop 2
drop 1
drop 0
main
```
It seems that `which` wants to refer to "the destruction of temporaries"

### Suggested Resolution
> The copy-initialization of the result of the call is sequenced before the destruction of temporaries at the end of the full-expression established by the operand of the return statement, and the destruction of the temporaries is sequenced before the destruction of local variables ([stmt.jump]) of the block enclosing the return statement.

**Comment by t3nsor** [comment]
It's not ambiguous at all. "A x B, which in turn x C" **always** means "A x B and B x C", not "A x B and A x C".
