### ISSUE TITLE
[streambuf.general] `std::basic_streambuf` is not an abstract class

### ISSUE THREAD

**Issue by PJBoy** [cplusplus/draft#6629]
[p1](http://eel.is/c++draft/streambuf.general#1) says "The class template `basic_streambuf` serves as an abstract base class for deriving various stream buffers". Base class I agree with, but an abstract class [has a pure virtual function](http://eel.is/c++draft/class.abstract#def:class,abstract), and `basic_streambuf` has not

**Comment by timsong-cpp** [comment]
This is [LWG2504](https://cplusplus.github.io/LWG/issue2504).

**Comment by jensmaurer** [comment]
I think this is sufficiently obvious that we can handle this editorially.

I'd suggest to simply strike "abstract" here; this is an intro sentence that doesn't need to show the full picture.

Pull request welcome.
