### ISSUE TITLE
[func.require] Unclear use of "shall"

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#6640]
[func.require]/4 reads:
> [...] This forwarding step delivers a state entity of type `T` as _cv_ `T&` when the call is performed on an lvalue of the call wrapper type and as _cv_ `T&&` otherwise, where _cv_ represents the cv-qualifiers of the call wrapper and where _cv_ shall be neither `volatile` nor `const volatile`.

It seems that the "shall be" used here is imposing some additional requirements, and thus shouldn't be interpreted as plain "is". But the additional requirements don't seem clear.
- Is the implementation required to ensure that when a `volatile` value of the wrapper is called, the invocation is ill-formed, or
- is the user code required to ensure that a `volatile` value of the wrapper is not called, otherwise, the behavior is undefined, or
- is the use of  "shall" unintended, and thus a plain "is" should be used, which implicitly makes the invocation on such a `volatile` value unspecified?

**Comment by jensmaurer** [comment]
We customarily use "shall" for constraints on the user-written program.  Thus, it's the first item.

**Comment by jwakely** [comment]
For the library use of "shall" it's the second, i.e. UB. This means the impl is allowed to accept it as an extension (for backwards compatibility), instead of being required to reject it as ill-formed.

**Comment by jensmaurer** [comment]
Ah, thanks for the info.

**Comment by jwakely** [comment]
In the interests of removing unnecessary UB, maybe we should consider making this conditionally supported, or explicitly unspecified (which would still allow it to be supported as an extension, but wouldn't open the door to nasal demons and unbounded UB).

**Comment by frederick-vs-ja** [comment]
I failed to express that the current wording seemingly mixes requirements for implementations and user codes in a strange way (at least to me).

Should we editorially clarify the status quo by divorcing the requirements, or open an LWG issue to change it?

**Comment by jwakely** [comment]
Please request an LWG issue, because I'd like to revisit the implied UB.
