### ISSUE TITLE
[diff] Annex C missing some header additions

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#6647]
C++23:
- `<mdspan>`
- `<stdfloat>`

C++26:
- `<rcu>`
- `<hazard_pointer>`
- `<text_encoding>`

**Comment by AlisdairM** [comment]
Addressed by #6648

I confirmed that there are no other missing headers for earlier standards

**Comment by AlisdairM** [comment]
The PR has been merged but is not linked to this issue.  Should this issue be closed now?
