### ISSUE TITLE
[diff.cpp03.library] Two entries for <typeinfo> in the index of library headers

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#6649]
The hyphenation of the <typeindex> header causes it to appear twice in the index of library headers, with an erroneous appearance sorted out of order, as-if it were a header named type:

\libheaderref{tuple},
\libheaderrefx{type\-index}{type.index.synopsis},
\libheaderrefx{type_traits}{meta.type.synop},

->

\<tuple>, 516–520, 689, 699, 710, 1968, 1993, 1994
\<typeindex>, 1968
\<type_traits>, 516–520, 657, 1968, 1992
\<typeindex>, 803
\<typeinfo>, 517, 538

**Comment by frederick-vs-ja** [comment]
This is fixed in https://eel.is/c++draft/headerindex. I think we can cherry-pick @Eelis's changes.
