### ISSUE TITLE
[2023-11 LWG Motion 3] Freestanding Library: Partial Classes

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6661]
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2407r5.html

**Comment by tkoeppe** [comment]
Some wording from this paper is allegedly superseded by https://cplusplus.github.io/LWG/lwg-active.html#3973 .

**Comment by burblebee** [comment]
@tkoeppe how should we proceed with this one?
