### ISSUE TITLE
[2023-11 LWG Motion 19] A free function linear algebra interface based on the BLAS

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6677]
https://wiki.edg.com/pub/Wg21kona2023/StrawPolls/P1673R13.html

**Comment by burblebee** [comment]
This paper is huge - any chance we can get the source? Emailed Mark Hoemmen to ask...

**Comment by jensmaurer** [comment]
@burblebee , please don't start with this one until @tkoeppe and you and me have agreed on an approach. It's likely we want to create some scripts. Please send the paper source to us once you got it.

**Comment by tkoeppe** [comment]
Yes, please hold on, we're discussing this with the authors. @burblebee, feel free to leave this one to me. We can also send a working draft without this motion and add it in a future draft. Or we can have some "in progress" markers in the draft, if that were to help.

**Comment by tkoeppe** [comment]
Daisy pointed me to https://github.com/ORNL/cpp-proposals-pub/pull/436, which is supposedly the markdown source of the approved paper (I haven't confirmed that).

**Comment by burblebee** [comment]
Great timing, just cc'ed you and Jens on the email reply with links to the source :)

**Comment by tkoeppe** [comment]
Thanks a lot! Let me get through all your ready PRs first, and I'll have a look at this paper afterwards.

**Comment by jensmaurer** [comment]
Paper is done; feel free to review.
