### ISSUE TITLE
[error.reporting] references in [filesystems] should be to [fs.err.report] instead

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#669]
[filesystems] contains numerous references to [error.reporting]; they should be to [fs.err.report].

**Comment by jwakely** [comment]
We might need to check all the cross-references. In [fs.conform.9945] we have:

> Some behavior is specified by reference to POSIX (27.10.2.1).

But 27.10.2.1 is [fs.conform.9945]. The href in the HTML is correct, pointing to [fs.norm.ref], so the LaTeX is correct.

However, later in [fs.conform.9945] we have:

> the implementation shall report an error as specified in § 27.10.7.

Which is the correct number, but this time the HTML href points to [fs.norm.ref] when it should be [fs.err.report].

**Comment by jwakely** [comment]
[path.construct]/4 refers to 27.10.8.2.1 but the exact same requirement in [path.assign]/5 refers to 27.10.8.2.2 but with the text 27.10.8.2.1

I assume both should be to 27.10.8.2.1 but I'm not sure.

**Comment by jwakely** [comment]
There are some inline cross-references too, which were lost in the conversion to LaTeX, such as "native pathname format" in [path.native.obs]p1 and "resolve" in [path.non-member]p10. The former is easy to fix but I'm not sure what the latter is referencing.

Also "file system races" in [fs.op.funcs]p1, "absolute path" in [fs.op.absolute]p1, both easy to fix.

**Comment by jwakely** [comment]
The original issue is fixed by a330bd6e771e2b5389dbf6d12f041d96eeda1c53

The flip-flopping references for format and encoding conversion are fixed by a643e53dbe23523d20e097f8175e8811d1b5ec70

The inline html links have been re-inserted by 3a6968c5e533767e650320518c571ae66099d284, 830eb75fd1502603c170b6d48189c87379b64d4e, and d78a2dffebc092e2779ca80a5873d737d6d9c456

The "resolve" link is still absent.

**Comment by jwakely** [comment]
Oops, I only pushed those commits to my own fork.

**Comment by jwakely** [comment]
Fixed now, the updated commit IDs are:

6513551 [path.op.absolute] Add cross-reference to [fs.def.absolute.path].
e3c65c8 [path.op.funcs] Add cross-reference to [fs.def.race].
4ecda29 [path.native.obs] Add cross-reference to [fs.def.native].
5d086be [path.construct], [path.assign], [path.append], [path.concat] Change references to [path.cvt].
afae63c [filesystems] Fix references to [fs.err.report].
