### ISSUE TITLE
Consider changing title of [fs.err.report]

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#671]
Both 27.5.6.5 [error.reporting] and 27.10.7 [fs.err.report] have the title "Error reporting". Maybe not a problem if the context is always clear, or references to Error reporting always include a cross-reference to the correct subclause.

**Comment by burblebee** [comment]
I don't like the word "report" itself.  Errors aren't being "reported", but "handled".  But yes, having 2 sections with the same name is confusing, even with xrefs.

**Comment by jensmaurer** [comment]
Depending on the outcome of #1242, it seems we might have lots more subheadings with the same title, only differentiated by their parent headings.

Put differently, when employing "short" subheadings, it's probably unavoidable to get duplicates in different parts of the heading tree.

I suggest NAD here (and those who wish to change "reporting" to something else should open a new issue; it seems to me this is really about reporting errors to the application).

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Do not try to identify sections by heading; use labels instead.
