### ISSUE TITLE
Why do we name `fail` in [iostate.flags]?

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#674]
> Otherwise, the function throws an object `fail` of class `basic_ios::failure` (27.5.3.1.1), constructed with implementation-defined argument values.

Why do we name it at all, and why do we give it the same name as a member function of the current class?

**Comment by AlisdairM** [comment]
It looks suspect to me too.

**Comment by jwakely** [comment]
Fixed by 24ad0836274dbb494f7d391d917aaf1e4f3844fa
