### ISSUE TITLE
cerrno, system_error and charconv

### ISSUE THREAD

**Issue by trcrsired** [cplusplus/draft#6763]
The errno.h is not in freestanding C. If we define our own errno numbers, it can create issues that flags -ffreestanding will not use the right to_chars due to the return type has a std::errc. Purely header reimplementation of charconv is too costly and encourages C++ standard libraries implementations not to support freestanding at all.

I suggest removing charconv completely from freestanding. or making errno and system_error not freestanding too.

**Comment by trcrsired** [comment]
@ben-craig

**Comment by jwakely** [comment]
This repo is for maintaining the draft and submitting editorial changes, not technical discussion.
