### ISSUE TITLE
[depr.c.macros] Missing description of `__alignof_is_defined` LWG4036

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#6765]
`__alignas_is_defined` and `__alignof_is_defined` are introduced in C11 ([WG14 N1507](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1507.htm), [WG14 N1558](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1558.pdf)) and removed in C23 ([WG14 N2934](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2934.pdf)).

However, C++ (11~23) has never mentioned `__alignof_is_defined` even though it's specified that "contents of the C++ header `<stdalign.h>` are the same as the C standard library header `<stdalign.h>`" (the wording was slightly different before C++20). There doesn't seem any C++ paper or issue for this.

Is it intended that `__alignof_is_defined` is not a C++ feature or is there a missing specification? In the latter case, we may still need to change Annex C for C++26.

**Comment by jwakely** [comment]
This was mentioned during the discussion of [LWG 3827](https://cplusplus.github.io/LWG/issue3827) but looks like it didn't make it into the issue. 

It was mentioned in https://github.com/cplusplus/nbballot/issues/502

It doesn't really matter now, because if it was supposed to be present in older standards, it's gone now anyway. I don't think we want a compatibility note saying that something which was never in the standard is gone now.

**Comment by jwakely** [comment]
Oh wait, they're not gone, we only deprecated them for now. Sigh.

I suppose we could add `__alignof_is_defined` to Annex D. I find it hard to care. Nobody should ever try to use that macro in C++.

**Comment by jensmaurer** [comment]
What's unclear about this specification in [stdalign.h.syn] ?

> The contents of the C++ header <stdalign.h> are the same as the C standard library header <stdalign.h>, with the following changes: The header <stdalign.h> does not define a macro named alignas.
> See also: ISO/IEC 9899:2018, 7.15

Our normative reference is to C17, so if this has a macro in `<stdalign.h>`, then C++23 has this macro as well.

What exactly is the problem?  Do you want index entries for the macros?

**Comment by jwakely** [comment]
We explicitly deprecated `__alignas_is_defined` in C++23, it would be silly to leave `__alignof_is_defined` there, un-deprecated. It would conflict with the clear direction of an NB comment.

**Comment by jensmaurer** [comment]
Ah, ok, we're simply missing an entry for `__alignof_is_defined` in [depr.c.macros].

**Comment by jwakely** [comment]
Yeah I think we should probably do it as an LWG issue. I don't know why it was never listed in the contents of `<cstdalign>`, if it _had_ been there, we'd have deprecated it as part of LWG 3827.

**Comment by frederick-vs-ja** [comment]
Hmm... I'm tried to submit an LWG issue but not sure whether it is wanted (it's possibly too late). Since C++26 will probably refer to C23 and thus should get `__alignas_is_defined`/`__alignof_is_defined` removed.

**Comment by frederick-vs-ja** [comment]
Should be fixed by #6915.
