### ISSUE TITLE
[headers] has incorrect name for subclause xref

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#6789]
[headers] p9 says:

> 17.14, C standard library headers, describes the effects of using the name.h (C header) form in a C++
program.

Where 17.14 is a cross-ref to [support.c.headers], but that subclause's title is "C headers", not "C standard library headers" as shown in [headers] p9.

Should we just strike "C standard library headers" from p9? Maybe change it to:

> Subclause 17.14 describes the effects of using the name.h (C header) form in a C++ program.

**Comment by jensmaurer** [comment]
Sounds good to me.
