### ISSUE TITLE
12.5  [over.built] 11, 12

### ISSUE THREAD

**Issue by sim9108** [cplusplus/draft#6798]
11: For every integral type T   --->  For promoted integral type T,

12: 
For every pair of floating-point types L and R , there exists a candidate operator function of the form
std::partial_ordering operator<=>(L , R )

 --->

For every pair of floating-point types T, there exists a candidate operator function of the form
std::partial_ordering operator<=>(T , T )

**Comment by jensmaurer** [comment]
p11: Why would this change be editorial? It appears to make a normative difference.

p12: The existing wording says that there are heterogenous comparisons, e.g. between float and double.  The suggested change would mean there are only homogenous comparisons.

The difference might be detectable with user-defined conversions from class types, I think.

**Comment by AlisdairM** [comment]
Jens gave good reasons why this suggested issue is non-editorial, and might not even be correct.

Are we ready to close the issue?

**Comment by tkoeppe** [comment]
Yes, thanks!
