### ISSUE TITLE
Need Annex C entry for hexfloat 

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#680]
The change to the *pp-number* production necessitated by the introduction of hexadecimal floating point literals can break valid C++14 code:

```
long double operator""_p(long double);
auto x = 0e1_p+0; // parsed as 0e1_p + 0 in C++14
                  // parsed as a single pp-number instead in C++17 (and so ill-formed)
```

**Comment by zygoloid** [comment]
There's an incompatibility with C++98 too:

  #define X(a) b##a
  int b0p = X(0p+0); // OK in C++98, ill-formed in C++17

**Comment by tkoeppe** [comment]
@zygoloid: Do you want me to draft the change?

**Comment by zygoloid** [comment]
@tkoeppe That'd be great, yes please!

**Comment by tkoeppe** [comment]
@zygoloid: PHAL

**Comment by tkoeppe** [comment]
This is completed and can be closed.
