### ISSUE TITLE
C++ Increment and Decrement Operators

### ISSUE THREAD

**Issue by JankieQwQ** [cplusplus/draft#6805]
In some Chinese C++ textbooks (For example: _Tan Haoqiang C programming_), there are often exercises like the following:
```C++
#include <iostream>

int main(){
    int i = 1;
    std::cout << (i++)+(++i) << endl;
}
```
The textbook provides the answer as ```6```, but when compiled with G++, the output is ```4``` or ```5``` or ```6```(Depends on level of optimization).  

I want to have some specification for this operation, such as:In the same row, if the variable has been increment more than once, the value before the first increment of the variable is used as the reference value.

Thanks.

**Comment by jwakely** [comment]
This repository is for editorial work on the C++ draft, not for questions about C++ or the content of the draft.

https://github.com/cplusplus/draft/wiki/How-to-submit-an-editorial-issue

I suggest you ask this somewhere like stackoverflow.com instead.
