### ISSUE TITLE
[format.syn] Bad index entry for format_args_t

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#6821]
https://github.com/cplusplus/draft/blob/8c8e05d7ff6cda6329ca898e7a270547a85675d7/source/utilities.tex#L15568

`format_args_t` is not mentioned in [format], but is mentioned in https://eel.is/c++draft/diff.cpp20.utilities#1.sentence-2

**Comment by cpplearner** [comment]
#6813 removes this index entry.

**Comment by Eelis** [comment]
Ah perfect!
