### ISSUE TITLE
[meta.trans.other] Normative paragraph starting with "Note A:"

### ISSUE THREAD

**Issue by Eisenwave** [cplusplus/draft#6842]
What's up with the style in paragraphs such as [[meta.trans.other] p4](https://eel.is/c++draft/meta.trans.other#4)?

It seems a bit unconventional; I wasn't able to find anything about it in https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines.

Should we keep it is this supposed to be reworded? If so, into what?

**Comment by jensmaurer** [comment]
These "notes" are normative; we refer to them in the table above the notes.

**Comment by AlisdairM** [comment]
See also: #4267

**Comment by frederick-vs-ja** [comment]
Probably fixed by #7033.
