### ISSUE TITLE
[lex.phases] Clarify the state of forming logical-lines when partially composing a comment

### ISSUE THREAD

**Issue by ContingencyOfTautologicalContradictions** [cplusplus/draft#6854]
```cpp
int meow/\
/ a single-line comment
;

```

Clang says that this is ok, GCC doesn't.

I think Clang here is right because the standard doesn't mention that you can't form a new logical-line while the comment is partially composed. In fact, forming logical lines (phase 2) should happen before processing comments (phase 3). So the comment should be in a single.line when the compiler "see" it at the phase 3.

I think clarifying whether this is allowed or not, preferably at the phase 3, would be a nice addon.

**Comment by jensmaurer** [comment]
I think [lex.phases] is very clear here: Line splicing happens in phase 2, before recognizing comments in phase 3. I don't know what needs to be clarified in addition to that

Please post a bug report to gcc.

**Comment by jwakely** [comment]
> Clang says that this is ok, GCC doesn't.

GCC compiles the code.

**Comment by ContingencyOfTautologicalContradictions** [comment]
> > Clang says that this is ok, GCC doesn't.
> 
> GCC compiles the code.

Not when -Werror=comment, see https://godbolt.org/z/fjrfn8sqc

**Comment by jwakely** [comment]
That's just a warning telling you the comment is split across two lines, it doesn't mean GCC thinks the code is invalid. If you ask for warnings to be turned into errors, that's what you get. It doesn't mean GCC doesn't accept the code. It certainly doesn't mean there's anything wrong with the standard.

If you don't want an error there, don't use `-Werror=comment`, it's quite simple.

**Comment by jensmaurer** [comment]
And I think gcc is right to give you the warning, because writing such line-spliced comments might, in fact, be a source of confusion.
