### ISSUE TITLE
coroutine_traits is not in the index

### ISSUE THREAD

**Issue by t3nsor** [cplusplus/draft#6856]
In the index of library names, `coroutine_handle` is follwed by `cos`, with no entry for `coroutine_traits`.

**Comment by jensmaurer** [comment]
A pull request to fix this is welcome.

**Comment by frederick-vs-ja** [comment]
Would it be better to show the synopsis for `coroutine_traits` and reword [[coroutine.traits.primary]/1](https://eel.is/c++draft/coroutine.traits.primary#1) like this?

```C++
namespace std {
  template<class R, class... ArgTypes>
  struct coroutine_traits {
    using promise_type = R::promise_type; // not always present
  };
}
```

> For the primary template, the member _typedef-name_ `promise_type` is declared if and only if the _qualified-id_ `R::promise_type` is valid and denotes a type ([temp.deduct]).
