### ISSUE TITLE
Containers refer to exploded tables as though they still exist

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#6858]
e.g. [vector.overview] p2

> Descriptions are provided here only for operations on `vector` that are not described in one of these tables or for operations where there is additional semantic information.

It's not clear what "these tables" refers to, because they were replaced in 93ff092d1cd2b335f372b9546365b3d495caf2d8.

**Comment by timsong-cpp** [comment]
dup of https://github.com/cplusplus/draft/issues/6762?

**Comment by jwakely** [comment]
Yes indeed, thanks.
