### ISSUE TITLE
implementation-defined vs. implementation defined vs. impldef

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#687]
The spec is inconsistent in the text for implementation-defined wording. Some use the impldef reference, some use implementation-defined, and some use implementation defined. It is also inconsistent in whether or not an index accompanies the implementation-defined text.

**Comment by zygoloid** [comment]
The missing index entries are covered by issue #98.

**Comment by AlisdairM** [comment]
I believe this is mostly resolved by https://github.com/cplusplus/draft/pull/899?
