### ISSUE TITLE
[2024-03 LWG Motion 2] Undeprecate polymorphic_allocator::destroy for C++26

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6873]
https://wiki.edg.com/pub/Wg21tokyo2024/StrawPolls/P2875R4.pdf

**Comment by AlisdairM** [comment]
Could this issue be assigned to me?  I don't see the UI to assign issues.

**Comment by AlisdairM** [comment]
This PR has been consolidated into #6921 that resolves merge conflicts among the 4 deprecation removal papers.
