### ISSUE TITLE
[2024-03 LWG Motion 3] Remove Deprecated strstreams From C++26

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6874]
https://wiki.edg.com/pub/Wg21tokyo2024/StrawPolls/P2867R2.html

**Comment by AlisdairM** [comment]
Could this issue be assigned to me?  I don't see the UI to assign issues.

**Comment by AlisdairM** [comment]
This PR has been consolidated into #6921 that resolves merge conflicts among the 4 deprecation removal papers.
