### ISSUE TITLE
[2024-03 LWG Motion 4] Remove Deprecated shared_ptr Atomic Access APIs from C++26

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6875]
https://wiki.edg.com/pub/Wg21tokyo2024/StrawPolls/P2869R4.pdf

**Comment by AlisdairM** [comment]
Could this issue be assigned to me?  I don't see the UI to assign issues.

**Comment by AlisdairM** [comment]
This PR has been consolidated into #6921 that resolves merge conflicts among the 4 deprecation removal papers.
