### ISSUE TITLE
Formatting of "Type/Name(s)" Tables is confusing

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#688]
Table 151 "Header synopsis" in [c.files] and others like it throughout the spec have header "Type Name(s)", but the contents don't line up with the headers. It ends up looking like the entries in the far left column are "Type"s and all other entries are "Name(s)". It would be clearer if the "Macros:"/"Functions:"/etc. appeared under "Type", and name entries appeared under "Name(s)".

**Comment by jensmaurer** [comment]
We now have proper synopses showing declarations instead of funny tables.
