### ISSUE TITLE
index: formatting issues

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#69]
Via cxxeditor@:

Finally, I noted a very minor typographical issue: There seems to be
a space missing after "see" in the index entry for
"conditionally-supported behavior".  I also suspect there shouldn't be a
page entry here, given that it's a cross-reference to another entry.
(Besides, the page number is wrong.)  [Hmmm; I now see this entry is
generated via an \indexdefn macro call; perhaps it should be an
\indextext call instead?]

**Comment by tkoeppe** [comment]
This seems to have been fixed; we've had a bunch of index fix commits recently.

**Comment by cpplearner** [comment]
Appears to be fixed by e525c60ebaf2e54d19642614372cdc7ce768e606.
