### ISSUE TITLE
[time.zone.db.access] Definition of std::chrono::current_zone() unclear

### ISSUE THREAD

**Issue by hvenev** [cplusplus/draft#6922]
The current definition of `current_zone()` is the following:

> A pointer to the time zone which the computer has set as its local time zone.

This leaves quite a lot of things open, most notably whether the returned time zone needs to be the same as the one used by the C library functions that deal with local time. In particular, it is unclear whether the `TZ` environment variable needs to be respected on POSIX systems (it is respected by the C library, but the words "the computer" as opposed to "the process" imply that it may need to be ignored).

**Comment by jwakely** [comment]
This repository is for editorial work on the draft, not for reporting issues in the standard. Please see https://cplusplus.github.io/LWG/lwg-active.html#submit_issue and use the email address at the top of that document, thanks.
