### ISSUE TITLE
What is "it" in [memory.resource.prot]/7?

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#695]
In the note:
        "For a derived class \tcode{D}, a typical implementation of this function will compute \tcode{dynamic_cast<const D*>(\&other)} and go no further (i.e., return \tcode{false}) if it returns \tcode{nullptr}."
 what is "it"?

e-mail from Richard:
> I'm guessing "it" means the dynamic_cast expression. But in that case the wording is wrong, as it's not a function call and thus cannot return a value. Seems like this is something we can handle editorially, as this is non-normative; please either file an editorial issue or a pull request.

**Comment by jwakely** [comment]
Yes, it seems clear to me that "it" is the dynamic_cast expression, although the uses of "compute" and "returns" and "go no further" all make me uneasy.

How about:

> `For a derived class \tcode{D}, a typical implementation of this function will immediately return \tcode{false} if \tcode{dynamic_cast<const D*>(&other) == nullptr}.`

Also, earlier in the note, should "match the type of this" be "match the type of \tcode{*this}" ?
