### ISSUE TITLE
cross-references needed to library types and their requirements

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#696]
What are the requirements of the referred-to library types mentioned in [alg.random.sample]/1 and elsewhere?  For example, what are the requirements of an InputIterator type mentioned in Bullet 1.1:
  "... shall meet the requirements of an InputIterator type"?
A reference would be very useful for all such types.
Grep in Latex for "shall meet the .*requirements of" to see list of all occurrences (some do have references).

Also, I could find nothing in the index for the types themselves (like InputIterator).   Cross-references for each should be added.

e-mail from Richard:

> This seems editorial. We should add cross-references here and make sure that the library concept names end up in the index.

**Comment by timsong-cpp** [comment]
`MeowIterator`s are not concepts proper, so these should probably use the wording in [algorithms.general]/5 ("shall satisfy the requirements of a meow iterator") with a cross link to [meow.iterators].

**Comment by jwakely** [comment]
> Also, I could find nothing in the index for the types themselves (like InputIterator).

Because they aren't types. Tim Song's suggestion is the correct way to say it.

**Comment by burblebee** [comment]
Thanks for clarifying.  Tim Song, would you mind taking this one please?

**Comment by jensmaurer** [comment]
We say both "shall satisfy the requirements..." (55 times) and "shall meet the requirements..." (24 times). [Both counts are the results of a simple "grep".]

**Comment by jensmaurer** [comment]
I've split off the phrasing questions for \tcode concepts (e.g. CopyConstructible) into #1263. This issue now exclusively deals with iterator requirements.
