### ISSUE TITLE
[ISO/CS C++2023] Remove hanging paragraphs

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6975]
- [x] 7.5 Primary expressions This is a hanging paragraph as per the ISO/IEC Directives Part 2, 22.3.2. Hanging paragraphs" shall be avoided since reference to them is ambiguous.  Please move this text to 7.5 or add another subclause 7.5.1, and renumber the existing subclause levels and cross-references.
- [x] 17.12.5.2 Class coroutine_handle<noop_coroutine_promise> This is a hanging paragraph as per the ISO/IEC Directives, Clause 22.3.3. Please move the text in 17.12.5.2 to 17.12.5.2.1. Otherwise, create another subclause "17.12.5.2.1 General" and relabel the existing ones. 
- [ ] 22.4.4 Class template tuple This is a hanging paragraph as per the ISO/IEC Directives, Clause 22.3.3. Please move the text in 22.4.4 to 22.4.4.1. Otherwise, create another subclause "22.4.4.1 General" and relabel the existing ones. 
- [x] 25.5.2.2 Class template back_insert_iterator this is a hanging paragraph. Either move the content in  25.5.2.2 to 25.2.2.1, or create another subclause directly under 25.5.2.2  "25.2.2.1 General". If a new subclause is added, the existing subclause numbers and cross-references would therefore have to be updated.
- [x] 25.5.2.3 Class template front_insert_iterator this is a hanging paragraph. Either move the content in  25.5.2.3 to 25.2.3.1, or create another subclause directly under 25.5.2.3  "25.2.3.1 General". If a new subclause is added, the existing subclause numbers and cross-references would therefore have to be updated.
- [x] 25.5.2.4 Class template insert_iterator this is a hanging paragraph. Either move the content in  25.5.2.4 to 25.2.4.1, or create another subclause directly under 25.5.2.4  "25.2.4.1 General". If a new subclause is added, the existing subclause numbers and cross-references would therefore have to be updated.
- [x] 30.4.6.4 Class template time_put This is another hanging paragraph - please move the content to 30.4.6.4.1, or add a new subclause directly under it "30.4.6.4.1 General" and rename the existing subclauses
- [x] 30.4.7.2 Class template money_get This is another hanging paragraph - please move the content to 30.4.7.2.1, or add a new subclause directly under it "30.4.7.2.1 General" and relabel the existing subclauses
- [x] 30.4.7.3 Class template money_put this is another hanging paragraph - see the comment above
- [x] 31.5.3 Class template fpos This is another hanging paragraph - please move the content to 31.5.3.1, or add a new subclause directly under it "31.5.3.1 General" and relabel the existing subclauses

**Comment by jensmaurer** [comment]
For 22.4.4, please cherry-pick first hunk (only) of 9620e6d2ff6dcc1ee355bfaff664efd82774af03 .

**Comment by tkoeppe** [comment]
> For 22.4.4, please cherry-pick the first hunk (only) of [9620e6d](https://github.com/cplusplus/draft/commit/9620e6d2ff6dcc1ee355bfaff664efd82774af03) .

Thanks!
