### ISSUE TITLE
[ISO/CS C++2023] Remove the word "subclause"

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6976]
- [ ] 13.5.1 General remove the word "subclause". Use the subclause number only to cross-reference a subclause.
- [ ] 19.5.1 General remove the word "subclause"
- [ ] 19.6.1 General remove word "subclause"
- [ ] 24.2.2.1 Introduction remove the word "subclause"
- [ ] 24.5.5.1 Overview Please remove the word "subclause" - the subclause number sufficies as a cross-reference. Update accordingly throughout the document.
- [ ] 29.12 Formatting please remove the word "subclause"
- [ ] 33.5.1 General remove the word "subclause"
- [ ] 33.6.1 General please remove the word "subclause"
- [ ] 33.9.1 General remove "subclause"
- [ ] C.7.4 Modifications to declarations Remove "subclause"

**Comment by tkoeppe** [comment]
I've asked ISO whether it's OK to retain "Subclause 1.2.3 describes feature X" to start a sentence, since otherwise we'd come up against the natural language style rule to not start a sentence with a symbol. Please hold off on changing that.

Interior changes like "see ~subclause~ 1.2.3" are fine.

**Comment by tkoeppe** [comment]
I think we've done what we can here.
