### ISSUE TITLE
[ISO/CS C++2023] Re-paginate to avoid lone "Example" or "Note" introducers

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6978]
- [ ] 6.4.1 General move "EXAMPLE 4" on next page 
- [ ] 6.5.4 Argument-dependent name lookup Please move "Example 1" to the next page
- [ ] 6.7.7 Temporary objects move "EXAMPLE 2" to the next page
- [ ] 7.6.1.1 General should this be an "EXAMPLE"? Please consider adding this in the sentence above "Postfix expressions group left-to-right, as shown below."
- [ ] 9.4.2 Aggregates move "EXAMPLE 3" to the next page
- [ ] 9.12.1 Attribute syntax and semantics Move "Example 1" to the next page.
- [ ] 11.8.5 Protected member access move EXAMPLE to the next page
- [ ] 11.10.2 Equality operator Move "example" to next page.
- [ ] 12.2.2.9 Class template argument deduction move "example 2" to the next page.
- [ ] 13.7.4 Variadic templates move "EXAMPLE 7" to the next page. Also please check the size of the font is uniform.
- [ ] 13.9.2 Implicit instantiation move "EXAMPLE 11" to the next page and ensure the font is the same size
- [ ] 13.9.3 Explicit instantiation move "EXAMPLE 2" to the next page and ensure the font is the same size
- [ ] 13.10.2 Explicit template argument specification move "example 3" to the next page
- [ ] 13.10.3.1 General move "example 5" to the next page
- [ ] 13.10.3.6 Deducing template arguments from a type Move "Example 13" to the next page
- [ ] 26.7.7.1 Overview move "example" to the next page 
- [ ] 29.8.11.1 Overview move "example" to the next page.
- [ ] 31.12.6.5.11 Generation move "example 1" to the next page.

**Comment by tkoeppe** [comment]
(Leave with me for final vertical review.)

**Comment by jensmaurer** [comment]
Pull request #6989 fixes the majority of occurrences by adjusting vertical break penalties.
(On the current draft, there is only one occurrence that remains.)

**Comment by jensmaurer** [comment]
Fixed by #7274
