### ISSUE TITLE
[ISO/CS C++2023] Replace forbidden words in notes and examples

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6980]
- [ ] 9.4.5 List-initialization "are not allowed" = "negative permission" - this is not permitted in a note. Please change to a negative possibility (" are not possible") or remove the "note". 
- [ ] 11.4.4 Special member functions "may" not permitted in a NOTE. Please change to "can".
- [ ] 13.3 Names of template specializations replace "might" with "can" in NOTE 1
- [ ] 13.8.1 General replace "might" with "can" in Note 1.
- [ ] 13.9.3 Explicit instantiation "needs to" suggests a requirement, which is not permitted in  a NOTE. Please change to "is expected to"
- [ ] 17.14.7 Other C headers replace "may" with "can" in this example, as permissions "may" are not allowed in notes.
- [ ] 20.3.2.4 Class template owner_less "Note that" is an imperative verbal form which is a requirement as per the ISO/IEC Directives Part 2. Please remove "note that" and use full sentences, removing the bullet points. Otherwise, replace "note that" with "it is worth noting that".
- [ ] 21.3.8.7 Other transformations What is "Note A"? And likewise for the text below, what is "Note B?" If these are meant to be "notes" according to the ISO/IEC Directives Part 2, then please change them to "NOTE x" as appropriate
- [ ] 22.4.6 Calling a function with a tuple of arguments In this context "it is necessary for" appears to be a requirement, i.e. it could be replaced with "shall" i.e. "it shall be supplied as...." Since requirements are not permitted in notes, please make this normal text, or change "it is necessary for " to "it is expected ..."
- [ ] 28.3.1 Header <cfenv> synopsis Please remove all caps. Change to "See also..." or make this NOTE 2, if it is necessary to use capital letters for this information.
- [ ] 33.5.4 Order and consistency please remove "prefer" as it is an imperative verbal form which is not permitted in a note. Please change to "x is preferred/can be preferred"
- [ ] 33.5.7.2 Operations Please change "could" to "can" in this note so that it is clearly expressing a possibility.
- [ ] 33.5.8.2 Operations on atomic types please change "might" to "can" in NOTE 8 so that it is clear that this is expressing a possibility.

**Comment by AlisdairM** [comment]
Now that C++23 is published, are we in a position to close this issue?
Should we preemptively open one for [ISO/CS C++2026] if we did not complete the task?

**Comment by tkoeppe** [comment]
We have other places for tracking similar things. We haven't applied all the changes from the IS back to the WD, because they don't all make for improvements, so it would still be good to revise the WD, but I'd first like to write a guidance document, and then we other pull requests where we can continue this work.
