### ISSUE TITLE
[ISO/CS C++2023] Specification unclarity around "ISO weeks"

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6984]
- [x] 29.12 Formatting What does the "ISO week-based week number" refer to? How does the user know what this means? Please make the text clearer.
- [x] 29.13 Parsing see comment above - What does the "ISO week-based week number" refer to? How does the user know what this means? Please make the text clearer. 
- [x] 29.13 Parsing see comment above - what does the "ISO weekday" mean?

**Comment by jwakely** [comment]
https://en.wikipedia.org/wiki/ISO_week_date
https://en.wikipedia.org/wiki/ISO_8601#Week_dates
