### ISSUE TITLE
Reference comments missing from [memory.polymorphic.allocator.class] synopsis

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#699]
Methods in synopsis are missing comments and references to definitions.
Comments should precede each method group with:
`    // <ref>, descrition:`

Also, is "Specializations for pair using piecewise construction" the right description for the methods that follow it?

**Comment by jwakely** [comment]
> Also, is "Specializations for pair using piecewise construction" the right description for the methods that follow it?

They're overloads not specializations, so maybe "Overloads for piecewise construction of pairs." (The term is defined in [pairs.pair]p14).

**Comment by burblebee** [comment]
Or should "`Specializations for pair using piecewise construction`" be reworded as a note in the details of method "`void construct(pair<T1,T2>* p, piecewise_construct_t, ...)`"?  That's how we resolved the other incorrect  comment "`Return a default-constructed allocator (no allocator propagation)`" before "`select_on_container_copy_construction()`".  Thoughts on how to word the note?
