### ISSUE TITLE
[ISO/CS C++2023] Adjust presentation of bibliography

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6993]
- [x] Bibliography Please number each item in the bibliography starting with [1]. See an example in the ISO model standard https://www.iso.org/files/live/sites/isoorg/files/developing_standards/docs/en/model_document-rice_model.pdf
- [x] Bibliography Please remove this sentence from the bibliography. This can be moved to the relevant part in the document where ISO/IEC 10967-1:2012 is cited.

**Comment by jensmaurer** [comment]
@tkoeppe , please cherry-pick  aa595cbf112a9bbca288620da122eeb1f500c02d  for the first item.

**Comment by tkoeppe** [comment]
Done, thank you!
