### ISSUE TITLE
[ISO/CS C++2023] Colons before bulleted lists

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#6999]
ISO/CS believes that a colon should precede a bulleted list.

We believe that bulleted lists are typographical whitespace that aids in conveying the structure of a sentence, but does not alter punctuation rules for the sentence.  That means a colon in front of a bulleted list is only acceptable if each bullet contains a complete sentence.

We should come to a decision and document it on the "style guidelines" wiki page.

**Comment by tkoeppe** [comment]
This is in fact an optional non-rule: It's not in the Drafting Directives, only in the House Style at https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-p-lists, and it says "preferably ends with a colon". ISO have clarified that we can retain the current practice as long as we're consistent.
