### ISSUE TITLE
[ISO/CS C++2023] Change 'through' to 'to'

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#7001]
- [x] 3 Terms and definitions edit "....in Clause 4 through to Clause 15..."
- [x] 4.1.1 General edit "....in Clause 4 to Clause 15..." This appears several times throughout the document - for clarity, please correct using "to" instead of "through". 
- [x] 16.3.3.4 Functions within classes See comments above - please change to "Clause 17 to Clause 33". Modify throughout the text.

**Comment by tkoeppe** [comment]
I agree with Walter's point that this is losing something. The request doesn't even seem to be based on any particular ISO rule, so I've asked whether we can retain the status quo. Thanks a lot for making this PR, but let's put this on hold unless they insist.

**Comment by tkoeppe** [comment]
Not actually needed.
