### ISSUE TITLE
[unique.ptr.create] `std::make_unique<int&>` may not be rejected properly

### ISSUE THREAD

**Issue by Eisenwave** [cplusplus/draft#7009]
`std::make_unique<int&>` is not rejected by a *Constraints* or *Mandates* specification. Instead, it is said to return
```cpp
unique_ptr<T>(new T(std​::​forward<Args>(args)...))
```
... and this would be ill-formed when `T` is a reference type, function type, etc. `std::unique_ptr<T>` is also allowed for basically any `T` (including incomplete types such as `void`); you just need the right deleter to make it work.

I believe this could be solved editorially be using an *Equivalent to* specification instead of a *Returns* specification. Any opinions?

**Comment by Eisenwave** [comment]
While we're at it, I believe that `std::make_unique` is similarly under-constrained, but I'm not sure if we wold want to solve it in the same way.

**Comment by frederick-vs-ja** [comment]
I guess it's unnecessary to redundantly specify them like this:
> - _Mandates_: _`expr`_ is well-formed.
> - _Returns_: _`expr`_.

"Equilvalent to" propagates _Constraints_, which would be a bit problematic when arbitrary `T` is involved. See LWG3628.

**Comment by Eisenwave** [comment]
Makes sense. There is also the alternative of copying over the "mandates" for `new`-expressions to be used: https://eel.is/c++draft/expr.new#1.sentence-3

If it was as simple as
> *Mandates:* `T` is a complete object type.

... I would have seen it as a slight net positive, but the rules aren't as simple, and this is just more wording that needs to be kept in sync. I think it should be left as is; I don't see a way to improve it for `std::make_unique` at least.
