### ISSUE TITLE
grammar terms aren't \grammarterm'd

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#701]
Many references to grammar terms defined in [lex](such as digit) are formatted in roman rather than italics.  This issue is cloned from #296 for the other grammar terms mentioned in that issue.

Note that we have separate issues for:
- universal-character-name #296
- literal #322

**Comment by tkoeppe** [comment]
How much of this is still a problem?

**Comment by jensmaurer** [comment]
> `grep -- - *.tex | fgrep -w '\term' `

still shows a few (very few) occurrences that need fixing (assuming that grammarterms often have a hyphen in their spelling).
