### ISSUE TITLE
[variant.visit] `as-variant` are not a `constexpr` unction templates

### ISSUE THREAD

**Issue by hewillk** [cplusplus/draft#7038]
Although `std::visit` is a `constexpr` function, _`as-variant`_ in [[variant.visit]](https://eel.is/c++draft/variant.visit) is not a `constexpr` function. Adding `constexpr` to them seems to improve consistency.
Is such `constexpr`-able editorial or is it unnecessary?

**Comment by frederick-vs-ja** [comment]
It seems better to add `constexpr` as _`as-variant`_ seems as-if evaluated per [variant.visit]/6 and /7.
