### ISSUE TITLE
[dcl.array] Subscript for arrays no longer performs array-to-pointer conversion

### ISSUE THREAD

**Issue by Eisenwave** [cplusplus/draft#7052]
[[dcl.array] p9](https://eel.is/c++draft/dcl.array#9.sentence-5) incorrectly says in a note:

> The expression `x3d[i]` is equivalent to `*(x3d + i);` in that expression, `x3d` is subject to the array-to-pointer conversion ([[conv.array]](https://eel.is/c++draft/conv.array)) and is first converted to a pointer to a 2-dimensional array with rank 5 ×7 that points to the first element of `x3d`.

This used to be the case prior to CWG1213. Because the operand was required to be a pointer, an array-to-pointer conversion was required. However, this is no longer the case. See [[expr.sub] p2](https://eel.is/c++draft/expr.sub#2.sentence-2):

> One of the expressions shall be a glvalue of type “array of `T`” or a prvalue of type “pointer to `T`” and the other shall be a prvalue of unscoped enumeration or integral type.

**Comment by frederick-vs-ja** [comment]
There's nothing wrong to me as `x3d` is an lvalue expression.

**Comment by Eisenwave** [comment]
I'll close this for now; the term "identical (by definition)" is still very unconventional and https://github.com/cplusplus/CWG/issues/549 deals with that.
