### ISSUE TITLE
[meta.unary.prop] is_nothrow_* traits should be explicitly allowed to have strengthened results

### ISSUE THREAD

**Issue by FrankHB** [cplusplus/draft#7070]
Although not explicitly specified as [[res.on.exception.handling]/5](https://eel.is/c++draft/res.on.exception.handling#5), the wording "is known not to throw any exceptions" in the condition column in [[tab:meta.unary.prop]](https://eel.is/c++draft/tab:meta.unary.prop) for tratis `is_nothrow_constructible` and `is_nothrow_assignable` permits to have different results from the status of the fact no functions with non-throwing exception specification will be called in the operations; that is, operations with _Throws:_ in the semantics but no non-throwing exception specification can also be assumed non-throwing. However, the following "([[expr.unary.noexcept]](https://eel.is/c++draft/expr.unary.noexcept))" is quite confusing by suggesting this is all about the case of `noexcept-specification`. Such internal consistency should be resolved edtiorially, e.g. converting the link to a note.

I believe this should be clarified editorially for various reasons (including some reasioning not so editiorial, though):

* The current wording besides the link (which is not explicitly against it) is clear.
	* This somehow follows the spirit of the NAD treatment of [LWG 2116](https://cplusplus.github.io/LWG/issue2116) in [P2842](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2842r0.pdf).
* The suggested resolution (to change the potentionally misleading link) is clear.
	* No conformance rule will be changed to be more restrictive in this direction, and absolutely no current conforming implementations will be break.
* The opposite direction (to disallow the strenghened results) is problematic.
	* The names containing `nothrow` instead of `noexcept`, so they should better avoid to tightly couple with `noexcept-specification`.
	* As mentioned in P2842, these traits predate `noexcept`. The history of renaming also indicates they are not coupled with `noexcept`.
	* There are risks of breaking some implementation already having the strenghened results in this context (although I have no instance).

Moreover, I've encountered some real problems when such traits are strictly bound to `noexcept` results. Specifically, to eliminate [-Wnoexcept] warnings from G++, the missing of explicit (conditional) `noexcept-specification` on the constructors of standard library types like `std::pair` instances makes the work much harder, because the precise location for pragmas to ignore the warning is often difficult to identify when the cause is `std` types. To work around this, additional exception specification can be added in *every* suspicious call sites, like:

```
namespace my
{
template<typename T, typename... A>
struct is_nothrow_constructible : std::is_nothrow_constructible<T, A...>
{};
// cv-qualified specializations here
template<typename T1, typename T2, typename A1, typename A2>
struct is_nothrow_constructible<std::pair<T1, T2>, A1, A2> : std::bool_constant<std::is_nothrow_constructible<T1, A1>::value && std::is_nothrow_constructible<T2, A2>::value>
{};
}
// more specializations can be added

using my::is_nothrow_constructible;;

template<typename T, typename... A>
void foo(...) noexcept(is_nothrow_constructible<T, A...>()) // exception specification added
{}
```

Then `my::is_nothrow_constructible` is a drop-in replacement of `std::is_nothrow_constructible` in almost any practical case in user programs. (Actually this is a user-provided fix of the potential defect of the constructor of `std::pair`, since the missing `noexcept` is not for intentional use, esp. allowing reporting the failure of violation of narrow contracts.) However, before it is clarified that strenghened results are allowed in `std` trait, it will also be confusing in `namespace my`.  I can hardly come up with a better name in that case, plus replacing `is_nothrow_constructible` anywhere is far more horrible to just replacing `using std::is_nothrow_constructible;` by `using my::is_nothrow_constructible;`. (And surely I can't specialize `std::is_nothow_constructible` for `std::pair<long, long>`, as it is undefined behavior.)

**Comment by jwakely** [comment]
It's unclear whether you're just suggesting to remove the "([expr.unary.noexcept])" cross-reference, or requesting a policy change/clarification which would certainly not be editorial.

If gcc's -Wnoexcept causes something like a false positive (or a true positive that the user can't do anything about) then that's entirely QoI and not an issue with the standard.

**Comment by FrankHB** [comment]
OK, let me clarify:

I suggest to replace "([expr.unary.noexcept])" to a note like:

"[Note X: Knowing not to throw any exceptions is implied by the fact that no functions having potentially-throwing exception specification ([except.spec]) are called. It can also be implied by the restrictions on implementations ([res.on.exception.handling]) or other cases when the implementation can ensure that no evluation can exit via exception.]"

(Editorial note: the note should be resued for different traits. Not sure it is directly fit in the table.)

The wording above is tweaked so cases besides _Throws_ in [res.on.exception.handling] (like C functions) and implementation-specific cases are also honored.

Refreshed reasons are presented below.

I think this should be fixed, because:

* The traits, by the names and meaning, in historical and current interests, should not depend on `noexcept` directly (as "([expr.unary.noexcept])" suggested), which is misleading.
* It should be safe to decouple from `noexcept` to ease mental work of maintaince, esp. the complicated library policies of `noexcept` [WIP](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p3085r2.html), which focuses on essentially different things.

I think this editorial fix is way better to treating it a defect, for:

* It does not need to concern changes on the normative text, and no current implementations are required to change.
* It embodies a legimate implementation option previously easily neglected. I believe this is an appropriate use case of a note.

Plus I'm reluctant to present an LWG issue with proposed NAD/NAD editorial resolution in the first turn. This GitHub issue is exactly the first turn to gather differing opinions. If WG21 think it necessary to have a policy clarification effective on the normative rules (e.g. to emphasize the differences of mandatory status between `noexcept` and other conditions within an explicit style like [res.on.exception.handling], or to require these optional conditions as implementation-defined), then it is proper to convert this issue to an LWG issue. The original title of this issue can be used.

The remained problems on -Wnoexcept is the background, not the problems composing the suggested editorial issue. Yes, they are not about the standard; they are about QoI on libstdc++ (not having strengthened `noexcept-specification` like libc++ and Microsoft STL), and/or on the g++ frontend (bug: failing to respect `#pragma GCC system_header` to suppress the warning; enhancement: compiler intrinsic to make improvement of QoI of `std::is_nothrow_*` even `noexcept` is totally missing). However, the treatment of this issue may have effect on the judgement about these GCC QoI issues, in particular, the enhancement part of the frontend.

**Comment by jensmaurer** [comment]
Hm...

- Suppose an implementation strengthens exception specifications in the standard library and uses "noexcept" to implement "is known...". All is well, before and after the change.

- Suppose an implementation does not strengthen exception specifications, but still uses "noexcept" to implement "is known...".  Does the new note mean that "is known" is clarified such that an implementation is supposed to (is required to?) special-case all situations where the standard says "Throws: nothing" and give the "noexcept(true)" answer for the query?

I think the current cross-reference makes it clear that using the "noexcept" operator is sufficient to implement "is known", and there is no expectation to do additional heroics. (Additional heroics are allowed, though.) (And, independently, implementations are still allowed to strengthen exception specifications if they so feel.  Yes, that makes the outcome of the "is known" queries vary between implementations, but that's par for the course.)

So, it seems to me the cross-reference is very much semantics-bearing here. We should not touch it editorially.

If you want to require strengthening exception specifications, that would mean replacing some "Throws: nothing" with "noexcept", and that feels like a paper to LEWG, not an editorial issue.

Oh, and "Knowing not to throw any exceptions is implied by the fact that no functions having potentially-throwing exception specification ([except.spec]) are called." is also an incorrect statement, because some core language facilities such as `typeid` or `dynamic_cast` can throw exceptions, with no function calls involved.

**Comment by jwakely** [comment]
I don't see why an implementation would want to strengthen the result of the traits, but *not* do so by adding `noexcept` where appropriate.

This seems to be an attempt to workaround "missing" noexcept in places where it's not required but could be strengthened. But the workaround would require changes to the implementation, so if the impl has to change anyway, it could just add the noexcept. Then the traits give the desired result. 

I just don't see any advantage to "clarifying" the traits. I think it would just make things more confusing.

**Comment by frederick-vs-ja** [comment]
The issue seems to request allowing `is_nothrow_*` traits to be _more strengthened_ than the exception specifications used for the corresponding constructors, right?

LWG3967 touches this although it only concerns about defaulted functions.

> I think the current cross-reference makes it clear that using the "noexcept" operator is sufficient to implement "is known", and there is no expectation to do additional heroics.

I guess it's still unclear whether these traits behave as-if `noexcept` is used for and only for immediate contexts of involved operations. Can we say that some expression or the full-expression of the variable definition "is non-throwing" (or verbosely, "is not potentially-throwing") instead?

**Comment by FrankHB** [comment]
> * Suppose an implementation does not strengthen exception specifications, but still uses "noexcept" to implement "is known...".  Does the new note mean that "is known" is clarified such that an implementation is supposed to (is required to?) special-case all situations where the standard says "Throws: nothing" and give the "noexcept(true)" answer for the query?
> 
> I think the current cross-reference makes it clear that using the "noexcept" operator is sufficient to implement "is known", and there is no expectation to do additional heroics. (Additional heroics are allowed, though.) (And, independently, implementations are still allowed to strengthen exception specifications if they so feel. Yes, that makes the outcome of the "is known" queries vary between implementations, but that's par for the course.)
> 
> So, it seems to me the cross-reference is very much semantics-bearing here. We should not touch it editorially.

Ah... if there is doubt that "is known..." is not clarified (enough) to cover all `noexcept(true)` cases, this is not editorial.

Even if nobody is against the expectation to implement "is known..." by `noexcept` (with or without other ways), is it really guaranteed? (I missed this.)

A note is insufficient to establish a requirement which is missing from the normative text at current. Nor does the cross-reference, I think.

> If you want to require strengthening exception specifications, that would mean replacing some "Throws: nothing" with "noexcept", and that feels like a paper to LEWG, not an editorial issue.

_Throws: nothing_ is about how to settle excpetion specifications down by design in general. For SD-9/LEWG such policy is a must, because almost any evolution in library will be affected.

This is not the case here. It does not affect arbitrary new features proposed in future.

It's more like [res.on.exception.handling]. Besides the requirement, the extent of the conditions of "is known..." is eventually up to the implementation.

> Oh, and "Knowing not to throw any exceptions is implied by the fact that no functions having potentially-throwing exception specification ([except.spec]) are called." is also an incorrect statement, because some core language facilities such as `typeid` or `dynamic_cast` can throw exceptions, with no function calls involved.

It is technically imprecise and insufficient, but still (logically) true, hence correct as a statement of a note. I agree other cases should be addressed, though.

> I don't see why an implementation would want to strengthen the result of the traits, but not do so by adding noexcept where appropriate.

For an ordinary implementation, probably. However, what if I decide to patch an existing implementation I have no control (say, libstdc++)? Patching `std::is_nothrow_*` with additional specializations is obviously easier than patching dozens of constructors like `std::pair`'s.

> This seems to be an attempt to workaround "missing" noexcept in places where it's not required but could be strengthened. But the workaround would require changes to the implementation, so if the impl has to change anyway, it could just add the noexcept. Then the traits give the desired result.

Actually the code illustrated in the background section is the non-intrusive version of such patching (not requiring to the changes in the implementation), at the cost that `std::` must be removed before `is_nothrow_*`. There is no such non-intrusive equivalent about adding `noexcept` on the constructors unless the whole `std::pair` stuff is replaced totally. So, the clarification (whether editorial or not) will be a real improvement for this case.

> LWG3967 touches this although it only concerns about defaulted functions.

This shares the same root cause that "is known..." is underspecified and there can be misinterpretions.

**Comment by jwakely** [comment]
> Actually the code illustrated in the background section is the non-intrusive version of such patching (not requiring to the changes in the implementation), at the cost that `std::` must be removed before `is_nothrow_*`.

No, that's adding a completely different template. The standard talks about the traits which are part of the implementation, not others that happen to have the same name.

**Comment by FrankHB** [comment]
> No, that's adding a completely different template. The standard talks about the traits which are part of the implementation, not others that happen to have the same name.

I'm fully aware of the fact that such "workaround" case is unrelated to the standard for conformance or any implementation of C++ standard library.

However, it *does affect* users hosting projects based on the standard. Instead of direct implementing the rules for conformance, the specification in a standard can be used as a source as a base design. Derivations can extend the standard's specification instead of reinventing wheels. Instances include derived programming languages (like C++/CLI), library solutions (like boost), and more (like POSIX). (In fact, ISO C++ also uses the "C subset" of the standard library via normative reference to ISO/IEC 9899:1999 instead of copying the text.) If there is already a specification (even if optional, informative, or having no implementations available), it may still ease the work of derivation *a lot*, particularly in cases the downstream projects cannot make the guarantees practically feasible.

With the suggested change here, I (close to the position of authors of Boost.TypeTraits) can make quite strong guarantees (asserting `is_nothrow_*` may have *unspecified* ways to improve without the knowledge of concrete C++ implementations, even when the entities being operated are in a standard library implementation not supporting the strengthened results - for instance, constructors of `std::pair` in libstdc++) for my users by a statement of "see ISO C++ [...]" in the document instead of a setup of an additional support matrix (compiler+std library) of supported configurations, simply because "the standard has said so". My users have only a cost no more than the introduction of declarations like `using my::is_nothrow_*;` in their source code once `std::` before `is_nothrow_*` are removed, perhaps easier than a typical setup of a build script to introduce a new library. Otherwise, to achieve the similar effect, I have to take a survey routinely, to cover every configurations for potability - because suspicions on bugs around compiler (say, -Wnoexcept in my case) may kick in and I can't determine whether the bugs are of mine or the language implementation before some case by case analyses; and even with that, I can't say any new conforming implementation will naturally work with my solution - of course compiler vendors will not comply with my requirements by default, even if I can provide the "patched" standard as the combined specification. Virtually, *only the standard is the right place* to provide such assumptions, even when they are not yet implemented (so alternative non-intrusive implementations outside `std` are just workarounds compared to `std` ones). (Or there can be technical specifications; but I don't think they are fit for amendment of features already in the standard.) And since C++ standard library implementations are often distributed by system vendors, to avoid the mess of dependencies (about both deployment and runtime binary compatibility), update of the `std` implementations can't replace the workarounds totally.

So, it is still an issue about the standard to make it more useful in practice. It is naturally an enhancement in this turn.

**Comment by FrankHB** [comment]
> Anyway, [N3050](https://wg21.link/n3050), which introduced `noexcept`, expressed that `noexcept` should be used for these traits.

Yes, allowing these traits implementable by pure library manner was one of the reason (benefit) to introduce of `noexcept`. But that was an implementation detail, and it was less convincing due to [LWG 2116](https://cplusplus.github.io/LWG/issue2116). Besides this, the traits were renamed in [N3142](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3142.html), for the reason about being more focusing on the user sites. This is consistent with my point. In the sense of interface, being `noexcept` and having `true` results from the traits are already not the same since the first published standard containing them. There is no reason to take a step back.

> Is -Wnoexcept off-topic here? Even if is_throw_* traits are more strengthened in some library implementation, nothing seems helpful for -Wnoexcept to me.

To users, -Wnoexcept is a quite useful tool to check against the unexpectedly missing `noexcept-specification`s (not only non-throwing ones, but also conditional ones like the one missed by `std::pair`'s constructors). It is more relavant due to lacking of other way to detect "is known not to throw any exceptions" property, exactly. If alternative implementation-specific ways are presented, there will be less need for -Wnoexcept at the very beginning. That is just not the reality.

There can be more (un)interesting subtleties about `noexcept(noexcept(T(arg)))` vs. `noexcept(is_nothrow_constructible<T, decltype(arg)>())`. I'm at the position of WA to make them have absolutely same semantics. That said, `noexcept(auto)` should be far better than any of them in many cases. This is likely more off-topic, but... see below.

> If we talk about strengthening `is_trivially_*` traits instead, things seem different. I can see how can such strengthening be useful.

There is a more direct relation from the view of implementation: inferring the missing `noexcept-specification` (used by the underlying logic of -Wnoexcept) is exactly a promising technique to implement the enhancement of the traits. To enhance the traits, basically it just requires some new intrinsics. It is sensitive to the visibility of function bodies, and quite different to the existing way of detecting via the `noexcept` operator. But probably `noexcept(auto)` can also share the logic and it should come first.

**Comment by jensmaurer** [comment]
> It is technically imprecise and insufficient, but still (logically) true, hence correct as a statement of a note.

No, you said "is implied by the fact", which means "no noexcept(false) function calls implies knowing not to throw any exceptions".  I can trivially create an example where all function calls are noexcept(true), yet an exception will be thrown by "typeid" or "dynamic_cast".  If you meant the implication the other way around, that's fine, but doesn't help much here.

> Moreover, I've encountered some real problems when such traits are strictly bound to noexcept results. 

An editorial change that seeks to somehow change or affect existing implementations is not editorial. Your "real problems" will not go away.

Given the length of the discussion here and the unclear benefits of the proposed change (the standard does not exist for the benefit of derived standards that may or may not exist), I don't think there is anything that can be done editorially here.
