### ISSUE TITLE
[meta.rel] New 'is_callable' entries overflow the middle cell of table

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#709]
The pack-expansion ellipsis is overflowing the 'Condition' column of table 54 - Type Relation Predicates in [meta.rel] for the two new traits added in Jacksonville, is_callable, and is_nothrow_callable.  I don't see any obvious way to improve matters either, so filing an issue rather than a pull request.

**Comment by K-ballo** [comment]
Using a shorter name for `ArgTypes` perhaps?

**Comment by jwakely** [comment]
Fixed by 535ff921a4c61da91716c9e18d42ffb26cc53c24
