### ISSUE TITLE
[2024-06 LWG Motion 7] P0843R14 inplace_vector

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#7090]
https://wiki.edg.com/pub/Wg21stlouis2024/StrawPolls/P0843%20inplace_vector.html

**Comment by burblebee** [comment]
This paper includes the following under the wording for [containers.sequences.inplace.vector.overview]:
>> LWG Review TODO: We need to review this last clause about constexpr. [...]
Has that happened?

**Comment by frederick-vs-ja** [comment]
The `operator<=>` seems to suffer the same problem as that in LWG4071. Is this already discussed or fixed?

**Comment by jwakely** [comment]
No, I don't think that was discussed.

**Comment by jwakely** [comment]
The reference implementation was incomplete :angry: 

```c++
    constexpr friend int /*synth-three-way-result<T>*/
    operator<=>(const inplace_vector& __x, const inplace_vector& __y)
```
