### ISSUE TITLE
[2024-06 LWG Motion 12] P2300R10 std::execution

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#7095]
https://wiki.edg.com/pub/Wg21stlouis2024/StrawPolls/P2300R10.html

**Comment by burblebee** [comment]
This is big. Can we get the source for the new sections added by this paper please?

**Comment by jensmaurer** [comment]
@burblebee , what do you mean? The source is HTML.

**Comment by burblebee** [comment]
> @burblebee , what do you mean? The source is HTML.

Oh! Yes, I see the `html` extension now that you mention it! :) Hard to believe it was originally written in html tho. Moot now that you grabbed this one.
