### ISSUE TITLE
[optional.observe] Duplicate constexpr function description?

### ISSUE THREAD

**Issue by hewillk** [cplusplus/draft#7101]
[[optional.observe]](https://eel.is/c++draft/optional.observe) specifies:

> _Remarks_: These functions are **constexpr functions**.

However, the function signature already has `constexpr`, is this redundant?

Same goes for [[optional.relops]](https://eel.is/c++draft/optional.relops):

> _Remarks_: Specializations of this function template for which `*x == *y` is a core constant expression are **constexpr functions**.

As these relational operators are all marked as `constexpr`.

Are these _Remarks_ unnecessary, or am I missing something?

**Comment by frederick-vs-ja** [comment]
Already tracked by LWG2829 and LWG2833.

**Comment by jwakely** [comment]
Not an editorial issue, as noted above.
