### ISSUE TITLE
class.copy rules for overloading as rvalue

### ISSUE THREAD

**Issue by BRevzin** [cplusplus/draft#712]
The rule for potentially selecting the the constructor as if the object were an rvalue currently reads as:

> When the criteria for elision of a copy/move operation are met, but not for an _exception-declaration_, and the object to be copied is designated by an lvalue, or when the _expression_ in a `return` statement is a (possibly parenthesized) _id-expression_ that names an object with automatic storage duration declared in the body or _parameter-declaration-clause_ of the innermost enclosing function or _lambda-expression_, overload resolution to select the constructor for the copy is first performed as if the object were designated by an rvalue.

This is a very long sentence with lots of internal boolean operators, and every three months I come across this sentence and mis-parse it. It would be great to come with with a rewording of this such that it's obvious what the two cases are. Something to the effect of:

> Overload resolution to select the constructor for the copy is first performed as if the object were designated by an rvalue if either:
> - the criteria for elision of a copy/move operation are met, but not for an _exception-declaration_, and the object to be copied is designated by an lvalue, or  
> - the _expression_ in a `return` statement is a (possibly parenthesized) _id-expression_ that names an object with automatic storage duration declared in the body or _parameter-declaration-clause_ of the innermost enclosing function or _lambda-expression_

Or really any other kind of editorial wizardry to clearly separate the two conditions that lead to the rvalue overload being considered.

**Comment by zygoloid** [comment]
I'd prefer to not make any changes here until P0135 lands, because it's going to change this wording.

**Comment by jensmaurer** [comment]
P0135 has landed.

**Comment by nullptr-cpp** [comment]
Does anyone know which proposal this change corresponds to?

**Comment by tkoeppe** [comment]
Could you try git-blame until you find the motion application commit?

**Comment by nullptr-cpp** [comment]
@tkoeppe  
https://github.com/cplusplus/draft/commit/32026a5b490a8f0b310530425108247694968def

 [class.copy] Rephrase rule preferring a move constructor

in a throw-expression or a return statement.

Fixes #712.


I got here through this commit :)

**Comment by tkoeppe** [comment]
Yes yes, right, now continue git-blaming from before that commit, look where the previous content came from, etc.

**Comment by jensmaurer** [comment]
I believe these rules are entirely misplaced in a "copy elision" section. After all, elision is optional, but moving is mandatory. I'm trying to fix this in #3998.

**Comment by nullptr-cpp** [comment]
@tkoeppe 
I have done this before, and what I want to know now is which proposal this commit corresponds to? 
I want to know the corresponding proposal number, I can't find it in commit history :sweat_smile:

**Comment by tkoeppe** [comment]
@nullptr-cpp: I don't know and would just do the same thing I advised. If you get all the way to commit 1, then this wording has been there since before C++11 and we'd need to look much harder.

**Comment by tkoeppe** [comment]
@nullptr-cpp: Yes, the original wording "When the criteria for elision" was already present in the first commit on GitHub.
