### ISSUE TITLE
[bibliography] Footer suggests the bibliography is in a section it isn't in

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#7147]
![image](https://github.com/user-attachments/assets/d8d8ab8d-08ef-4be5-8ced-f9e03932b885)

**Comment by tkoeppe** [comment]
Ah yes, this may have come from the recent header/footer change. We need to disable the page mark when the Bibliography starts.

**Comment by tkoeppe** [comment]
Fixed by 96c58e53ed950dbb237b3638f7e2c968e89f2468
