### ISSUE TITLE
Incorrect section references in filesystems subclause

### ISSUE THREAD

**Issue by geoffromer** [cplusplus/draft#715]
Subclause [filesystems] contains a large number of references to [error.reporting]. From context, it is clear that every one of these references is wrong, and should be a reference to [fs.err.report].

Most of these references are of the form "Throws: As specified in Error reporting (27.5.6.5).", but section 27.5.6.5 (aka [error.reporting]) says nothing about how a filesystem function throws. The place where the throwing behavior of filesystem functions is specified is [fs.err.report]. Both sections are titled "Error reporting", which is presumably how the confusion arose.

**Comment by jwakely** [comment]
See #669
