### ISSUE TITLE
[expr.ass] CWG 2399: What's "the expression"?

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#720]
[expr.ass]/2,3,6 contains several references to "the expression":

> -2- In simple assignment (=), the value of the expression replaces that of the object referred to by the left operand.
> 
> -3- If the left operand is not of class type, the expression is implicitly converted (Clause [conv]) to the cv-unqualified type of the left operand.
> 
> -6- When the left operand of an assignment operator is a bit-field that cannot represent the value of the expression, the resulting value of the bit-field is implementation-defined.

Clearly it's meant to refer to the right operand, i.e., the _initializer-clause_, but that's not necessarily an expression, and in any event the reference is unclear just reading the text.

**Comment by tkoeppe** [comment]
Are you sure? Doesn't it refer to the assignment expression as a whole? The expression `f() = 5` has value `5`, and that value replaces the value of the left operand.

**Comment by timsong-cpp** [comment]
The assignment expression as a whole is an lvalue referring to the left operand.

**Comment by burblebee** [comment]
This sounds like a core issue.  How does one turn an edit issue into a core issue?

**Comment by tkoeppe** [comment]
@burblebee: I think you wait until a friendly person (hello @zygoloid) emails the issue to the Core chair... :-)

**Comment by tkoeppe** [comment]
From a discussion with @zygoloid:

1. change p2 to say
 > In a simple assignment (=) <ins>whose right operand is an assignment-expression<ins>, the value of <del>the</del> <ins>that</ins> expression [...]"
2. then p9 would define what happens in the other case in terms of the p2 or p4 wording
3. maybe moving the assignment-expression / braced-init-list dispatch up front might be cleaner
4. also, talking about what happens for class types here is unnecessary; none of the other overloadable operators bother with that

**Comment by jensmaurer** [comment]
Posted to the core reflector so that we get a core issue: http://lists.isocpp.org/core/2016/12/1382.php

**Comment by jensmaurer** [comment]
See also [CWG 1542](http://wg21.link/cwg1542).

**Comment by jensmaurer** [comment]
Handled by [CWG 2399](https://wg21.link/cwg2399).

**Comment by jensmaurer** [comment]
Fixed by 9700b1357df79e5a95f75db9fc46e2aa1f7d689c (Nov 2019).
