### ISSUE TITLE
Is LWG chair's gmail account not actively used?

### ISSUE THREAD

**Issue by yaito3014** [cplusplus/draft#7305]
A week ago, I have sent an email about potential LWG issue to the chair's gmail address. I think this was the correct procedure according to this page, <https://cplusplus.github.io/LWG/lwg-active.html#submit_issue>. Since then, I haven't received a reply.

@jwakely, could you please take a look into the inbox, including the spam folder?

If there is more proper way to report an issue, please let me know.

Thanks!

**Comment by jwakely** [comment]
We received the email, just haven't acted on it yet. You followed the correct process, so thank you for the submission.
