### ISSUE TITLE
[class.path]: literal missing backslash-escape

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/draft#731]
In [class.path] paragraph 4:
> [ ... ] is the backslash character (`L’\’`).

**Comment by tkoeppe** [comment]
Make a PR?

**Comment by hubert-reinterpretcast** [comment]
The text appears in an example; so I believe it is an editorial issue.

**Comment by tkoeppe** [comment]
Right, so could you just create a pull request for the editor?

**Comment by timsong-cpp** [comment]
It's missing an extra backslash, not a single quote.

**Comment by hubert-reinterpretcast** [comment]
Ah; yes.
