### ISSUE TITLE
[exec.queryable.general] Can we use `std::as_const` here?

### ISSUE THREAD

**Issue by Eisenwave** [cplusplus/draft#7350]
I find the phrasing in [[exec.queryable.general] p2](https://eel.is/c++draft/exec.queryable.general#2) unusually complex for what it's doing:

> Let `q` be a query object, let `args` be a (possibly empty) pack of subexpressions, let `env` be a subexpression that refers to a queryable object *o* of type `O`, and let `cenv` be a subexpression referring to o such that `decltype((cenv))` is `const O&`.
The expression `q(env, args...)` is equal to ([concepts.equality]) the expression `q(cenv, args...)`.

Could we do the following?

```diff
 [...]
-, and let cenv be a subexpression referring to o such that decltype((cenv)) is const O&.
The expression q(env, args...) is equal to ([concepts.equality])
-the expression q(cenv, args...).
+q(as_const(env), args...).
```
On a side note, I'm a little surprised that the standard uses `as_const` without `std::` in a variety of places. One would think that this is bad because it allows ADL to find versions of `as_const` that do something else entirely.

Why do we write `std::move` everywhere but not `std::as_const`?

**Comment by jwakely** [comment]
> One would think that this is bad because it allows ADL to find versions of `as_const` that do something else entirely.

No it doesn't, see [contents].

> Why do we write `std::move` everywhere but not `std::as_const`?

The library convention is to qualify `move` and `forward` consistently, for reasons.

**Comment by jwakely** [comment]
And no, we can't use `as_const` here because it doesn't work with rvalues.
