### ISSUE TITLE
23.2.5[unord.req]p12 refers to key_equal as a function

### ISSUE THREAD

**Issue by cubbimew** [cplusplus/draft#736]
`23.2.5[unord.req]p12` says

> ... to the predicate returned by `key_equal()`

presumably the intent was to say "returned by `key_eq()`" (`key_equal` is the name of the type of the predicate returned by `key_eq()`)

The use of `key_equal()` in Table 110 seems correct (...constructs an empty container with ... key_equal() as the key equality predicate"

**Comment by jwakely** [comment]
Fixed at 13b57f74b8b9aac71e4cabe186b16c60670c2c71
