### ISSUE TITLE
[reverse.iter.cons] Seemingly redundant wording

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/draft#7369]
[[reverse.iter.cons]/1](https://eel.is/c++draft/reverse.iter.cons#1) currently says:
> _Effects_: Value-initializes `current`. Iterator operations applied to the resulting iterator have defined behavior if and only if the corresponding operations are defined on a value-initialized iterator of type `Iterator`.

The second sentence seems to be completely redundant. I guess it can be removed editorially, but the similarly redundant wording for  `move_iterator` was removed by LWG3435.

**Comment by jensmaurer** [comment]
@jwakely , I'd be ok with removing the fluff editorially.  What do you think?
