### ISSUE TITLE
[linalg.reqs.val] is missing an 's' in "linear algebra value type"

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#7373]
> Throughout 29.9, the following types are _linear algebra value type_:

The incoming paper ([P1673R13](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p1673r13.html#linear-algebra-value-types-linalg.reqs.val)) said "linear algebra value types" here, plural. The 's' has been lost as a consequence of the `defnadjx` macro:

```
\pnum
Throughout \ref{linalg},
the following types are
\defnadjx{linear algebra}{value type}{linear algebra value types}:
```

I'm not sure how to fix that without altering the index entries ... although they seem kinda messed up anyway:

![image](https://github.com/user-attachments/assets/e1b24ce4-3347-49ad-bedb-55daf36ef47b)

@jensmaurer what was the intention here?

**Comment by jwakely** [comment]
Should it be: `\defnadjx{linear algebra}{value types}:{value type}`?

**Comment by jensmaurer** [comment]
We want the singular index entry and the plural display in the running text.  Looks like I messed up the use of the macro.

**Comment by tkoeppe** [comment]
Feel free to just push the change!

**Comment by jwakely** [comment]
#7374
