### ISSUE TITLE
flat maps could use \exposid for private members

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#7380]
`c` and `compare` aren't in _kebab-case_

`flat_set` and `flat_multiset` does use `kebab-case` so we're inconsistent.

**Comment by jwakely** [comment]
Not using kebab-case for `c` is especially misleading because the classic container adaptors `queue`, `stack` etc. also have a data member called `c`, but it's not exposition-only for those adaptors. It's a protected member and part of the API.

**Comment by frederick-vs-ja** [comment]
I think my PR #6404 is fixing this.

**Comment by jwakely** [comment]
> I think my PR #6404 is fixing this.

Ah thanks!
