### ISSUE TITLE
[2024-11 LWG Motion 17] P3019R11 indirect and polymorphic: Vocabulary Types for Composite Class Design

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#7429]
[P3019R11](https://wiki.edg.com/pub/Wg21wroclaw2024/StrawPolls/P3019R11.pdf) (indirect and polymorphic: Vocabulary Types for Composite Class Design

**Comment by tkoeppe** [comment]
After some discussion and investigation several of us, including the authors, editors, and the LWG chair, agreed that the paper is sufficiently unclear in its present form that it'd be better to have LWG make a new revision and have that proposed again at the next plenary; for this meeting, we're not applying this paper.
