### ISSUE TITLE
Odd indexing for bitset::set

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#743]
In the index of library names `bitset::set` is grouped under `set` along with members of `std::set` so looks like it's actually a member function, `std::set::bitset`

**Comment by AlisdairM** [comment]
There is a similar problem with any/bitset::any

**Comment by jensmaurer** [comment]
Well, \indexlibrarymember{a}{b} adds "b under a" and "a under b" index entries, so the above is a natural fallout of this design. But I agree it's confusing in this particular case.

**Comment by tkoeppe** [comment]
This seems somewhat ad-hoc to me. The general problem is that a single top-level index entry with subentries is used with multiple different meanings that differ across the subentries. Are there more such cases? Is the right answer to randomly select one meaning as the desired one and discard the others? Or should we maybe disambiguate the meaning and keep both entries, such as "set (*m*)" for the member and "set (*t*)" for the type or template?

**Comment by jensmaurer** [comment]
Good point: Maybe we should just say "set (member)" for the bitset members to disambiguate (and assume a class / template) otherwise).

**Comment by tkoeppe** [comment]
Maybe `\indexlibrarymember` should *always* replace `a (\textit{member})`. That may be generally useful information.

**Comment by jensmaurer** [comment]
... at least for the first-level entry.

**Comment by tkoeppe** [comment]
Your commit looks sensible, it's a nice local solution that's adequate for the problem.
