### ISSUE TITLE
Wrong range in [alg.search]

### ISSUE THREAD

**Issue by slotosch** [cplusplus/draft#7474]
During the qualification of the C++ STL Validas has pointed me to the following issue:
The specification of [alg.search] has a wrong range.
Currently the range is "[first1, last1 - (last2 - first2))" (**exclusive**) but should be "[first1, last1 - (last2 - first2)]" (**inclusive**).
So please correct the closing ")" to "]". Otherwise the last occurence will not be found.
We observed the issue in C++14 and C++17 and cppreference.com
The implementations do the right thing and work correctly and find even the last occurence.

For example in the list {1, 2, 3, 4, 5} the pattern {4,5} should be found (obviously).
In the case the last element is not included it will not be found.
The attached programm shows that the implementation is working and find the pattern.
[rangebug.cpp.txt](https://github.com/user-attachments/files/18024619/rangebug.cpp.txt)

**Comment by tkoeppe** [comment]
This does not sound editorial to me: https://github.com/cplusplus/draft/wiki/How-to-tell-if-an-issue-is-editorial

Do you think it is?

**Comment by slotosch** [comment]
> This does not sound editorial to me: https://github.com/cplusplus/draft/wiki/How-to-tell-if-an-issue-is-editorial
> 
> Do you think it is?

Indeed this is semantic issue. Sorry if I have misclassified it

**Comment by jwakely** [comment]
Please see https://cplusplus.github.io/LWG/lwg-active.html#submit_issue instead

**Comment by jwakely** [comment]
Got it, thanks

**Comment by slotosch** [comment]
Happy to hear Jonathan,
If there is anything we can do to support you feel free to ask.
Here is the link to the issue we file in the standard:
https://github.com/cplusplus/draft/issues/7474

Kind regards & a nice weekend,
               Oscar

***@***.***?anonymous&ep=bwmEmailSignature>
Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>

**Comment by Dani-Hub** [comment]
The library issue exists now, see [LWG 4179](https://cplusplus.github.io/LWG/issue4179).
