### ISSUE TITLE
[linalg.helpers] too many T

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#7494]
> a subexpression E whose type is `T` is expression-equivalent to ... includes the declaration `template<class T> T abs(T) = delete;`

These are not the same `T` so we should pick a different letter, we have plenty to choose from.

[linalg.helpers.abs]
[linalg.helpers.conj]
[linalg.helpers.real]
[linalg.helpers.imag]

**Comment by jwakely** [comment]
Reopening, this is about reusing `T` for different things in wording that was already in the draft, not about the issue in the just-merged [linalg.conj.conjugated] changes.

**Comment by tkoeppe** [comment]
Oh, sorry! I thought the just-merged changes got rid of the troublesome `T`s, but there's more.

**Comment by jwakely** [comment]
Why does the poison pill for `abs` use a by-value param and the others use a reference?

```
template<class T> T abs(T) = delete;
template<class U> U conj(const U&) = delete;
template<class U> U real(const U&) = delete;
template<class U> U imag(const U&) = delete;
```

I don't think it makes much difference, but if that's the case then there's no reason for them to differ.

**Comment by frederick-vs-ja** [comment]
> I don't think it makes much difference, but if that's the case then there's no reason for them to differ.

Hmm... possibly they catch different combinations of cv-qualification and value category.
However, are they necessary at all (see also [P2602R2](https://wg21.link/p2602r2))? If not, perhaps we can create an LWG issue to remove these poison pills.

**Comment by jwakely** [comment]
> Hmm... possibly they catch different combinations of cv-qualification and value category.

Do they though? I don't think so. All that matters is that the poison pill is found by unqualified lookup, we don't care whether the arguments can be matched to make it viable or not.

**Comment by jwakely** [comment]
And the types involved here have to be linear algebra value types, which are semiregular. So they can't be move-only, such that `abs(U)` wouldn't be viable for lvalues.

@mhoemmen is there any rationale for `abs(T)` vs `abs(const T&)` in the [linalg.helpers.abs] poison pill?

**Comment by mhoemmen** [comment]
Thanks for catching this issue!

@jwakely wrote:
> is there any rationale for `abs(T)` vs `abs(const T&)` in the [linalg.helpers.abs] poison pill?

There is no rationale for the `abs` poison pill to use `T` vs. `const T&`.  As you pointed out, linear algebra value types have to be semiregular, so there's no intended difference between those two things.  This was likely an oversight.
