### ISSUE TITLE
\opt vs. \opt{}

### ISSUE THREAD

**Issue by burblebee** [cplusplus/draft#761]
I see both \opt and \opt{} used in the grammars in Latex.  Can these all be changed to be just \opt?

**Comment by tkoeppe** [comment]
We had a PR to fix those just recently - the `{}` is needed to produce space. `\opt` doesn't use anything fancy like `\xspace`.

**Comment by zygoloid** [comment]
We should use `\opt{}` everywhere to avoid the possibility of problems / missing whitespace.

**Comment by burblebee** [comment]
Should we instead add \xspace to \opt so that it acts like \opt{}?

**Comment by tkoeppe** [comment]
I'm really worried about xspace because I don't really understand how it interacts with other punctuators. I'd be perfectly happy to use `\opt{}` when necessary.

**Comment by zygoloid** [comment]
On 23 Jun 2016 12:03 a.m., "burblebee" <notifications@github.com> wrote:
>
> Should we instead add \xspace to \opt so that it acts like \opt{}?

I'd like to move away from xspace. It's too unpredictable.

**Comment by burblebee** [comment]
OK.  Shall I turn all \opts into \opt{}s then?  Or leave as is and close this issue as "NAD"?

**Comment by tkoeppe** [comment]
Well, is the spacing actually wrong? I'd say we should have the `{}` if and only if it's needed.

**Comment by burblebee** [comment]
Great - let's close this as a non-issue then.
