### ISSUE TITLE
remove counts of headers etc from [headers] and [depr.c.headers]

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#766]
We don't need to give an explicit count of the number of items in a table, and doing so creates a maintenance burden and possibility of errors. We should remove these (an LWG informal poll has agreed to this).

**Comment by jensmaurer** [comment]
This is a direct outflow from chaos theory, it seems.

[headers] lists the C headers in a table, and then [depr.c.headers] lists those exact same headers again.
[depr.c.headers] tells us that "The use of any of the C ++ headers <ccomplex>, <cstdalign>, <cstdbool>, or <ctgmath> is deprecated." but [diff.mods.to.headers] says "For compatibility with the C standard library, the C ++ standard library provides the C headers enumerated in D.4, but their use is deprecated in C ++ ."

Can someone tell me which ones of the C headers are deprecated and which ones aren't?

**Comment by tkoeppe** [comment]
@jensmaurer: I'm not sure that's true. [headers] lists `<cstddef>`, which is not deprecated. [depr.c.headers] lists `<stddef.h>`, which *is* deprecated, as stated by [diffs.mods.to.headers].

Moreover we are apparently also deprecating `<ccomplex>` etc; I have an issue open about that (a pull request, in fact).

**Comment by jensmaurer** [comment]
@tkoeppe: Ah, you're right. Those lists subtly differ in their .h suffix. :-/

**Comment by jensmaurer** [comment]
Why does D.4p2 talk about C++ headers, then? [depr.c.headers] is supposed to be about .h -style headers.

Why does C.5.1p4 talk about C++ headers in a section entitled "C standard library", showing incompatibilities vs. C11? Surely, C11 doesn't have those C++ headers.

**Comment by tkoeppe** [comment]
I think D.4p2 is just because Clark couldn't find a better place for that in P0063.

C.5.1p4 is a note, but I was told that all of Annex C is a note, so it's not marked up.

**Comment by tkoeppe** [comment]
I filed an LWG issue about all this a while ago. I think it would make sense in general to say that "X is deprecated" in the main text, and then describe X in Annex D, but we need to think how that affects things like `<cstdalign>`.

**Comment by jensmaurer** [comment]
See also #1054.
