### ISSUE TITLE
[associative.reqmts] Terribly formatted table

### ISSUE THREAD

**Issue by sdutoit** [cplusplus/draft#78]
The table "Associative container requirements" has awful formatting.

**Comment by tkoeppe** [comment]
Are there any requirement tables that *don't* have awful formatting? :-)

I have an attempt [here](https://github.com/tkoeppe/draft/tree/table_to_paragraph) to re-layout the tables into paragraphs. I'm waiting for @zygoloid's response.

**Comment by zygoloid** [comment]
Our preference is to move away from tables for requirements for C++20.

**Comment by tkoeppe** [comment]
Here is an example of a different way to present requirements. The example replaces Table 86 in [container.requirements.general]:

![image](https://user-images.githubusercontent.com/6378233/32478826-baeee0f4-c37e-11e7-969a-bcf028963228.png)

The code lives in https://github.com/tkoeppe/draft/tree/table_to_paragraph

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Present Thomas' bulleted rewrite to LWG for comment.

**Comment by mclow** [comment]
Sent to -lib reflector for feedback.

**Comment by tkoeppe** [comment]
I really hope we can make some progress with this for C++20. There's good guidance from @geoffromer on the reflector, @tkoeppe needs to do some work here.

**Comment by geoffromer** [comment]
For reference, the reflector thread is http://lists.isocpp.org/lib/2018/01/5041.php

**Comment by cpplearner** [comment]
any update?

**Comment by zygoloid** [comment]
Not happening for C++20. Retargeting.

**Comment by tkoeppe** [comment]
Resumed by Jens's effort in #4460.

**Comment by tkoeppe** [comment]
@jensmaurer: I take it we can close this now? :-)

**Comment by jensmaurer** [comment]
Yes. I've also added a link to the pull request.
