### ISSUE TITLE
Sections 18.3.2.1 and 18.3.2.3 have the same name

### ISSUE THREAD

**Issue by Eelis** [cplusplus/draft#785]
Both are named "Class template numeric_limits".
Maybe one of them should say "synopsis"?

**Comment by Eelis** [comment]
Hm no, maybe one of them should say "overview"? Or maybe they should be merged. I don't know, I really can't tell what the intended structure is here. :)

**Comment by tkoeppe** [comment]
Deleting a stable name? What has the world come to :-)
