### ISSUE TITLE
"punctuator" grammar rule not defined

### ISSUE THREAD

**Issue by ShimmerFairy** [cplusplus/draft#787]
The _punctuator_ rule is specified as a choice in the _token_ rule, however _punctuator_ is not defined. See [issue 198 here](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#189).

**Comment by jwakely** [comment]
That's a technical issue, not an editorial one, and is already being tracked by CWG 189.

https://github.com/cplusplus/draft/wiki/How-to-tell-if-an-issue-is-editorial
