### ISSUE TITLE
"pre:" and "post:" in container requirements tables

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#792]
The container requirements tables introduce preconditions and postconditions with "pre:" and "post:", or sometimes "Pre:" and "Post:".  Those are not italicized like _Effects:_ etc. (and are not using LaTeX commands, just plain text, so are harder to see in the source).

We should format them consistently.

A better solution might fall out of @tkoeppe's suggestion on Issue #78 if we get rid of the tables, as we could use real _Requires:_ and _Postconditions:_ elements once we aren't constrained by the column width in those tables.

**Comment by jensmaurer** [comment]
In [unord.req], we use "pre:" as well as "_Requires:_". Can someone clue me in what the (supposed) difference is?

**Comment by jwakely** [comment]
No idea, I think it's just historical baggage, from a time when we were less formal about such things.

It would be good to clean it up before (or as part of) [P0411 Separating Library Requirements and Preconditions](https://wg21.link/p0411r0)

**Comment by jensmaurer** [comment]
@jwakely: Ok, so replacing pre/post with \Requires and \Postcondition right now would put us on a good starting point for further P0411 massaging, right?

**Comment by jwakely** [comment]
Yes, I think so. My guess is that pre/post were used just to avoid wasting space in those table cells, for layout reasons.
