### ISSUE TITLE
Inconsistent wording in [new.delete.single] and [new.delete.array]

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#793]
[new.delete.single]/12:

> _Requires:_ _ptr_ shall be a null pointer or its value shall be a value returned by an earlier call to the (possibly replaced) `operator new(std::size_t)` or `operator new(std::size_t,const std::nothrow_t&)` which has not been invalidated by an intervening call to `operator delete(void*)` or `operator
> delete(void*, std::size_t)`.

[new.delete.array]/11:

> _Requires:_ _ptr_ shall be a null pointer or its value shall be the value returned by an earlier call to
> `operator new[](std::size_t)` or `operator new[](std::size_t,const std::nothrow_t&)` which
> has not been invalidated by an intervening call to `operator delete[](void*)` or `operator delete[](
> void*, std::size_t)`.

Firstly, _ptr_ should be using \tcode not \textit.

Secondly, why is one "its value shall be a value" and the other "its value shall be the value"?

Thirdly, why does the first state "possibly-replaced" but not the second?

**Comment by jwakely** [comment]
And why doesn't [new.delete.array] have a _Requires_ about safely-derived pointers?

**Comment by jwakely** [comment]
(some of these problems were already fixed at e51a2152599bce93d72b371590d03960f99f85e3 by the P0035R4 changes)

**Comment by jensmaurer** [comment]
Current state:

[new.delete.single] p12
Requires: `ptr` shall be a null pointer or its value shall represent the address of a block of memory
allocated by an earlier call to a (possibly replaced) `operator new(std::size_t)` or `operator new(std ::size_t, std::align_val_t)` which has not been invalidated by an intervening call to `operator delete`.

[new.delete.array] p11
Requires: `ptr` shall be a null pointer or its value shall represent the address of a block of memory
allocated by an earlier call to a (possibly replaced) `operator new[](std::size_t)` or `operator new[](std::size_t, std::align_val_t)` which has not been invalidated by an intervening call to
`operator delete[]`.

**Comment by jensmaurer** [comment]
Looks like it's fixed.
