### ISSUE TITLE
Stable names in 20.11 are too long

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#794]
[memory.polymorphic.allocator.class]
[memory.resource.monotonic.buffer.ctor]

Surely we can abbreviate these.

**Comment by tkoeppe** [comment]
Best to fix that before we commit to the stable names!

**Comment by tkoeppe** [comment]
`[mem.poly.alloc.class]`
`[mem.res.mono.buf.ctor]`

**Comment by AlisdairM** [comment]
looking at Annex F for long names, these are far from the only culprits.  Seems to be an issue with many stable names from the TS.  Compare: fun.wrap.badcall  vs. optional.bad_optional_access - we have forgotten how to abbreviate.

Also, underscores seem to make the names look much longer in Annex F - see the Boyer Moore searchers.

**Comment by jwakely** [comment]
Yes, underscores are sometimes replaced with dots instead, e.g. unique.ptr, which looks much better.

[optional.bad.access] or [optional.badaccess] seem better than [optional.bad_optional_access].

I'm also not sure we really need to keep the word "object" in [optional.object.*] ... I think it was there to reserve place for [optional.ref.*] but we don't have `optional<T&>` and even if we did we could still use [optional.ref.*] once we add it.

**Comment by cpplearner** [comment]
The longest one seems to be [func.searchers.boyer_moore_horspool.creation] in 20.14.13.3.1, and it formats badly in the new xrefs.

**Comment by tkoeppe** [comment]
@jwakely, @AlisdairM, @zygoloid: We should fix this before we ship the IS!

**Comment by jwakely** [comment]
GB 52 covers this.

**Comment by jensmaurer** [comment]
Those long names are also the cause for overfull/underfull hbox complaints from LaTeX; see #693.
