### ISSUE TITLE
[list.ops] p12 has Effects in the Requires paragraph

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#796]
> _Requires:_ `[first, last)` is a valid range in `x`. The result is undefined if `position` is an iterator in the range `[first, last)`. Pointers and references to the moved elements of `x` now refer to those same elements but as members of `*this`. Iterators referring to the moved elements will continue to refer to their elements, but they now behave as iterators into `*this`, not into `x`.

What are the third and fourth sentences doing in a _Requires_ paragraph?

**Comment by burblebee** [comment]
Unless this was incorrectly applied by the editor from the original paper (was it?), I'd say this is an LWG issue.

I've asked this question before - how does one turn an edit issue into an LWG/CWG issue?  Is there a process for that?

**Comment by tkoeppe** [comment]
There's probably no safer way than to email lwgchair with a paste of the issue. The github issues are too transient to be referenced; they can be edited or deleted on a whim.

**Comment by burblebee** [comment]
Ok.  Thanks.

email sent to lwgchair - closing this as an edit issue.

**Comment by jwakely** [comment]
> Unless this was incorrectly applied by the editor from the original paper (was it?), I'd say this is an LWG issue.

Hard to tell, that wording appeared some time between C++03 and C++11, but I haven't tracked down when exactly. The original text just said that it invalidates iterators referring to the spliced elements, so I'd guess that was expanded to the new wording, but not moved to a more suitable paragraph.

I'm not sure it needs to be a defect report, the meaning of the words is entirely clear, moving them to a different paragraph will have no normative effect.
