### ISSUE TITLE
[alg.random.sample] has period in middle of sentence

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#797]
>  `SampleIterator` shall satisfy the additional requirements of a random access iterator (24.2.7).
unless `PopulationIterator` satisfies the additional requirements of a forward iterator (24.2.5).

I assume that's meant to be a comma.

**Comment by timsong-cpp** [comment]
[That was my fault](https://github.com/cplusplus/draft/commit/0560bab1b1fc2eb55fb5fa8f447fc6b1445b6f0c) :( 

It should be nothing, actually, but a comma works too.

**Comment by jwakely** [comment]
Aha! thanks, I'll fix it once the Oulu motions land.
