### ISSUE TITLE
Inconsistent formatting of cv-qualified

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#798]
The core and library clauses oscillate between cv-qualified, _cv_-qualified and (in one case) _cv-qualified_.

The library is also inconsistent about parenthesising "possibly cv-qualified".

**Comment by AlisdairM** [comment]
I got some guidance from @zygoloid regarding this on a recent pull request #684 :
"cv should not be italicized except when referencing a metavariable representing a set of cv-qualifiers. That is: "_cv_-qualified" means "qualified with the set of qualifiers named _cv_", whereas "cv-qualified" means "qualified with some unspecified cv-qualifiers". See [basic.type.qualifier]/5."
