### ISSUE TITLE
[LaTeX] Simplify index entries for class members

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#799]
It is very common to create an index entry for a class member like so:

    \indexlibrary{\idxcode{class}!\idxcode{member}}%
    \indexlibrary{\idxcode{member}!\idxcode{class}}%

It would be nice to be able to create both entries from a single line, such as:

    \indexlibrarymember{\idxcode{class}!\idxcode{member}}%

This would then allow us to simplify a lot of declarations, and improve consistency. It would help towards fixing the modest number of cases where one, but not both, of the lines above is present.

**Comment by jwakely** [comment]
I do that in the Networking TS, see https://github.com/cplusplus/networking-ts/commit/18a1cc18184b4698b9a7f7b2aa55475a00f5c801#diff-a647f9a1c14f8900030991b8b9fec2d8R69

    % Add two names to the library index as both #1!#2 and #2!#1
    \newcommand{\indexlibrarytwo}[2]{%
    \indexlibrary{\idxcode{#1}!\idxcode{#2}}%
    \indexlibrary{\idxcode{#2}!\idxcode{#1}}%
    }

Your name is better though :)

**Comment by AlisdairM** [comment]
Macro and initial application up for review:
  https://github.com/cplusplus/draft/pull/835

**Comment by AlisdairM** [comment]
This has been satisfactorily resolved by https://github.com/cplusplus/draft/pull/837 (although some follow-up patches may still apply).
