### ISSUE TITLE
Missing index entries for operator!=

### ISSUE THREAD

**Issue by jwakely** [cplusplus/draft#800]
Overloads of `operator!=` need to be indexed as `operator"!=` and this is currently not done for string_view, optional and PMRs.

I'll fix this once the Oulu motions are merged.

**Comment by burblebee** [comment]
What's special about `operator!=` ?  What other chars should be treated specially?

**Comment by godbyk** [comment]
The `!` symbol has a special meaning for the indexer. It indicates that the rhs is a subentry.

The following characters have special meaning within the `\index` commands:

    !  "  @  |

**Comment by burblebee** [comment]
Thanks!  noted :)   so you'd do "" for "?

**Comment by jwakely** [comment]
Fixed at 16f3af8a65762aab840e878315a71d17f1dac736

**Comment by godbyk** [comment]
@burblebee That's correct.
