### ISSUE TITLE
[lib] How to format sectioning comments in synopsis

### ISSUE THREAD

**Issue by tkoeppe** [cplusplus/draft#802]
Comments in a synopsis that refer to sections come in a variety of styles at the moment:

```
// 34.8, Capital letters
```

<p>

```
// 34.8, lowercase like this
```

<p>

```
// 34.8, lowercase with colon:
```

<p>

```
// See 34.8, something something
```

We should probably agree on a style. I think the third one is the most prevalent (lowercase with colon), though the second one is also widely used, and @zygoloid doesn't think the colon is helping any.

**Comment by burblebee** [comment]
I've been using the 3rd one (lowercase with colon), because as you noted, it is the most prevalent.

**Comment by zygoloid** [comment]
I think we should be choosing between the second and third options. My preference is the second form, because the colon seems like noise to me (and I like the contents of the line after the comma to match the section name), but if consensus among editors is that the third is better, that's fine with me.

**Comment by burblebee** [comment]
On Sun, Jul 10, 2016 at 05:18:50PM -0700, Richard Smith wrote:
> I think we should be choosing between the second and third options. My preference is the second form, because the colon seems like noise to me (and I like the contents of the line after the comma to match the section name), but if consensus among editors is that the third is better, that's fine with me.

I've been using the 3rd option because that's the most common one.
It would be good to be consistant in any case.

**Comment by burblebee** [comment]
On Fri, Nov 18, 2016 at 11:17:02AM -0800, dawn@burble.org wrote:
> On Sun, Jul 10, 2016 at 05:18:50PM -0700, Richard Smith wrote:
> > I think we should be choosing between the second and third options. My preference is the second form, because the colon seems like noise to me (and I like the contents of the line after the comma to match the section name), but if consensus among editors is that the third is better, that's fine with me.
> 
> I've been using the 3rd option because that's the most common one.
> It would be good to be consistent in any case.

I should add, that I really don't have a preference between 2 and 3, as
long as we're consistent.

**Comment by tkoeppe** [comment]
> I should add, that I really don't have a preference between 2 and 3, as
long as we're consistent.

Same here. Option 3 seems like the most prevalent one, so simplicity suggests we stick with that, but I'm also just as happy with 2 as with 3 in principle.

**Comment by jensmaurer** [comment]
I second @zygoloid here, the colon is adding nothing.

**Comment by jwakely** [comment]
I find the colon unnecessary too.
