### ISSUE TITLE
make_any

### ISSUE THREAD

**Issue by timsong-cpp** [cplusplus/draft#813]
[The order of template parameters](https://github.com/cplusplus/draft/blob/master/source/utilities.tex#L4829) in

    template <class U, class T, class ...Args>
    any make_any(initializer_list<U>, Args&& ...args);

seems clearly broken. Can this be handled editorially, or should I send this to LWG?

**Comment by jwakely** [comment]
I think that can be fixed editorially, because the proposal contradicts itself. The synopsis has the wrong parameter order but the spec for that function has it right. That fits the following criterion from https://github.com/cplusplus/draft/wiki/How-to-tell-if-an-issue-is-editorial

> Internal inconsistencies (e.g. two different declarations for the same function overload, when it is clear which is the correct declaration)
