### ISSUE TITLE
consistently render, or omit, labels for tables

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#824]
We currently render the labels for concept tables, but for no other tables:

  Table 21 — MoveConstructible requirements **[moveconstructible]**

If this is useful, we should do it for all tables. If not, we should remove it from the concept tables.

We will also need to make sure that there are no name collisions between table labels and section labels if we choose to show them, to avoid confusion. Perhaps we could render the 'tab:' prefix.

**Comment by AlisdairM** [comment]
Table numbers are not consistent, as new tables get inserted (or removed) so having some kind of name associated with each table is helpful when filing issues.

**Comment by tkoeppe** [comment]
The table stable name doesn't *have* to be the same as the label, though for the sake of editing the text, stable table labels would be nice. And yes, we can rename them until we start displaying them.

**Comment by jensmaurer** [comment]
It seems to me we don't really have to render labels for tables. Usually, a table is associated with a single paragraph that we can reference. The labels shown for the "concept tables" look actually somewhat disgusting to me.

**Comment by jensmaurer** [comment]
Editorial meeting consensus: There are no other mentions of the labels in the document. The labels for the tables are not used in the standard. Remove the table labels.
