### ISSUE TITLE
Incorrect underline character in the title of [util.smartptr.getdeleter]

### ISSUE THREAD

**Issue by LYP951018** [cplusplus/draft#844]

**Comment by tkoeppe** [comment]
What exactly is the problem here? Looks like WAI/NAD to me.

**Comment by jwakely** [comment]
There's nothing wrong with the underscore, but it should be in code font.

**Comment by tkoeppe** [comment]
Ah yes, that's an actual issue. Fix coming up.

**Comment by tkoeppe** [comment]
Fixed by 6b82a23fc4433c704e0837d34ebe880c6408a09c.
