### ISSUE TITLE
Remaining reference to <cstring> in 20.10.1 [memory.general]

### ISSUE THREAD

**Issue by BoPersson** [cplusplus/draft#862]
The subclause says:

20.10.1 In general [memory.general]
1 This subclause describes the contents of the header \<memory\> (20.10.2) and some of the contents of the C headers \<cstdlib\> and \<cstring\> (20.10.11).

However, \<cstring\> was just removed from 20.10.11

**Comment by tkoeppe** [comment]
Thank you, fixed by https://github.com/cplusplus/draft/commit/277eb59b0b92a4431f1217f50e96b196a0c967f1.
