### ISSUE TITLE
What is the meaning of 'section' in the standard?

### ISSUE THREAD

**Issue by AlisdairM** [cplusplus/draft#904]
I have not quite fathomed the meaning of ‘section’ to determine if we use it correctly or consistently.

For example, 3.8p11 [basic.life] provides a meaning for "before" and "after" that apply to the rest of the section.  As the next paragraph is the first of 3.9, that suggests 'section' is the top level clause number?

29.8 [atomic.fences] starts p1 with "This section introduces synchronization primitives called fences."  This clearly is intended to apply to 29.8 specifically, and not the whole of 29.

I believe that ISO define this term precisely as a term of its own vocabulary - are we consistent with any such definition?

**Comment by timsong-cpp** [comment]
3.8p11 doesn't say "the rest of"; I think it's meant to refer to the preceding paragraphs in 3.8.

**Comment by zygoloid** [comment]
I believe the term the ISO Directives recommend here is "subclause".

**Comment by jensmaurer** [comment]
See also #307.

**Comment by tkoeppe** [comment]
Closing, we don't need multiple issues for the same topic. Post any future information in #307 please.
