### ISSUE TITLE
Small typo in [any.modifiers]/2

### ISSUE THREAD

**Issue by StephanTLavavej** [cplusplus/draft#913]
N4606 20.8.3.3 [any.modifiers]/2 says "*Effects:* Calls `this.reset()`." It should say `this->reset()` or eliminate `this` entirely (e.g. /10 just refers to `has_value()` by itself).

**Comment by tkoeppe** [comment]
Thanks - could you send a PR please?

**Comment by StephanTLavavej** [comment]
I'm on Windows and I've never built the Standard from its sources here (I tried once in a Linux VM). Which is why I submit issues instead of PRs when I find typos. I know I should figure out the build process someday.

**Comment by tkoeppe** [comment]
I believe you can make edits directly in the GitHub web interface nowadays. No need to actually build anything, we have Travis for that :-) For small changes like this, I'm perfectly happy to just review the source changes.

**Comment by timsong-cpp** [comment]
Already fixed by #884.
