### ISSUE TITLE
[time.duration.nonmember] is missing formatting

### ISSUE THREAD

**Issue by zygoloid** [cplusplus/draft#916]
More than half of the _Returns:_ clauses in this subclause are in Roman rather than Teletype.

We also have inconsistency between this subclause and the next one: in [time.duration.comparisons](and in [time.point.nonmember]), we use italic teletype for the placeholder _`CT`_, but in this subclause (and in [time.duration.cast]) we use non-italic teletype for the placeholders `CD` and `CR`.

**Comment by tkoeppe** [comment]
To clarify the complaint: Some itemdescrs are using `\effects Returns` rather than `\returns`, right? So the `\effects` should go away, too.

**Comment by zygoloid** [comment]
I'm not seeing any `\effects` in this section. Can you point to a paragraph where you see that issue? So far I'm only concerned by the issues I pointed out in the first comment.

**Comment by tkoeppe** [comment]
Never mind, I misunderstood!

**Comment by tkoeppe** [comment]
I'm unsure on how to proceed regarding placeholders. I am currently of the opinion that none of the use cases in utilities.tex should use placeholders, and the only legitimate placeholders I can think of are the `F` in `do_F` in locales and the `key` in `fetch_key` in atomics, where the placeholder actually stands for part of an identifier. By contrast, all the uses in utilities.tex are merely type aliases, usually introduced by something like "Let `T` be the type of...".

**Comment by jensmaurer** [comment]
Editorial meeting consensus: Do not italicize "CD" or "CT", these are actual types, not meta-placeholders.

**Comment by tkoeppe** [comment]
As a further example of what makes a placeholder, there is now the `X` in `XTypes` in [tuple.creation].

**Comment by jensmaurer** [comment]
I agree that CD represents a specific type (and thus should not be \placeholder), but CR(A,B) is a type meta-function that isn't actually C++, yet we use \tcode. Maybe we want to \placeholder CR here?

**Comment by zygoloid** [comment]
Expand the CR macro in its four uses.
