### ISSUE TITLE
[basic.def.odr] brittle and broken count of bullets in normative text

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/draft#944]
In N4604 subclause 3.2 [basic.def.odr] paragraph 6, bullet 6.5:

> [ ... ] that is, the default argument is subject to the three requirements described above [ ... ]

the "three requirements" presumably refer to bullets 6.1 through 6.4.

**Comment by zygoloid** [comment]
It's worse than that:

> the default argument is subject to the three requirements described above (and, if the default argument has sub-expressions with default arguments, this requirement applies recursively).

So it's actually referring to bullets 6.1 through 6.5!
