### ISSUE TITLE
[basic.def.odr] dangling reference to 7.1.2 for "inline"

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/draft#945]
In N4604 subclause 3.2 [basic.def.odr] paragraph 6, the cross-reference to 7.1.2 should refer instead to 7.1.6 [dcl.inline].

**Comment by tkoeppe** [comment]
Thanks, fixed by c6552f06c8e35020718d5bd211f7cbeef96ea1f3.
