### ISSUE TITLE
generated pdf doesn't contain hyperlinks for grammer terms.

### ISSUE THREAD

**Issue by introom** [cplusplus/draft#946]
For example, on ee.is, I can click the term `lambda-expression` and it will jump to `http://eel.is/c++draft/expr.prim.lambda#nt:lambda-expression`.

In the generated pdf, the terms such as `lambda-expression` are plain text.

**Comment by tkoeppe** [comment]
Can you please clarify? Where do you click, and where does it take you? The grammar definitions appear multiple times.

**Comment by introom** [comment]
for example, at `http://eel.is/c++draft/expr.prim.lambda#3`, click the following `lambda-expression` .  But in the pdf, there is no corresponding hyperlink.

Readers may be confused what `lambda-expression` is, and they have to resort to other means to find the definition of that term.

**Comment by jwakely** [comment]
> Readers may be confused what lambda-expression is, and they have to resort to other means to find the definition of that term.

Such as searching for it, or looking in the index of grammar terms, which works perfectly well.

eel.is is nothing to do with the C++ committee or the official drafts and uses a completely different pipeline to generate HTML pages. We certainly don't want to add a reference like "(5.1.5)" after every occurrence of a grammar-term.

**Comment by introom** [comment]
@jwakely I wasn't adding reference. I was saying hyper-link, as the way eel.is does.  Of course `add a reference like "(5.1.5)"` is a sure way to distract the readers.

**Comment by jwakely** [comment]
Yes, I know, but the draft doesn't inline hyperlinks like that, and IMHO there's no reason to change that.

**Comment by jensmaurer** [comment]
Not a bug.
