### ISSUE TITLE
Subhead with no [stable.tag]

### ISSUE THREAD

**Issue by W-E-Brown** [cplusplus/draft#952]
Looking at N4604,  clause `[utility]` (20.2), there's a subheading "Header `<utility>` synopsis" that has no [stable.tag].
- Should it?
- If so, a tag such as [utility.syn] seems consistent with similar synopsis subclauses.

**Comment by jwakely** [comment]
That style of header is created by the `\synopsis` command and I think the lack of tag is intentional (it doesn't start a new section). See also the `<functional>` synopsis in [function.objects], the `<tuple>` synopsis in [tuple.general], the `<variant>` synopsis in `[variant.general]` etc. etc.

**Comment by jwakely** [comment]
[optional.syn] is inconsistent and doesn't use the `\synopsis` command:

    \rSec2[optional.syn]{Header \tcode{<optional>} synopsis}

Also [memory.syn]

    \rSec2[memory.syn]{Header \tcode{<memory>} synopsis}

And [meta.type.synop]:

    \rSec2[meta.type.synop]{Header \tcode{<type_traits>} synopsis}

**Comment by tkoeppe** [comment]
Use of `\synopsis` is optional. Lots of times we use real, numbered headings, exactly because getting a referenceable section name is useful. For the new C library synopses we tried sticking to a pattern by which the stable name for the synopsis of `<cfoo>` is `[cfoo.syn]`.

**Comment by tkoeppe** [comment]
See also Issue #566.

**Comment by jensmaurer** [comment]
The original issue was fixed with #1213.
