### ISSUE TITLE
Inconsistency in [expr.ass] and [intro.execution]

### ISSUE THREAD

**Issue by akemimadoka** [cplusplus/draft#953]
[expr.ass]/1:

> In all cases, the assignment is sequenced after the value
> computation of the right and left operands, and before the value computation of the assignment expression.
> The right operand is sequenced before the left operand

[intro.execution]/15:

> i = v[i++]; // the behavior is undefined
> i = 7, i++, i++; // i becomes 9
> i = i++ + 1; // the behavior is undefined
> i = i + 1; // the value of i is incremented

With the assignment being sequenced after the value
computation of the right and left operands, why is i = v[i++] and i = i++ + 1 undefined behavior?

**Comment by jensmaurer** [comment]
It seems we've overlooked this example when we applied Gaby's order-of-initialization paper.

**Comment by Kingwl** [comment]
it's very helpful to me!

**Comment by ly0** [comment]
it's very helpful to me!

**Comment by AngryPowman** [comment]
it's very helpful to me!
