### ISSUE TITLE
Behaviour of `std::pmr::memory_resource::do_allocate()` is ambiguous

### ISSUE THREAD

**Issue by iolojz** [cplusplus/draft#966]
essentially a copy of this [StackOverflow](http://stackoverflow.com/questions/40386696/behaviour-of-stdpmrmemory-resourceallocate-on-large-alignments) question.

To quote N4606:  
>`virtual void* do_allocate(size_t bytes, size_t alignment) = 0;`

>Requires: Alignment shall be a power of two.

>Returns: A derived class shall implement this function to return a pointer to allocated storage (3.7.4.2) with a size of at least __bytes__. The returned storage is aligned to the specified alignment, if such alignment is supported; otherwise it is aligned to __max_align__.

>Throws: A derived class implementation shall throw an appropriate exception if it is unable to allocate memory with the requested size and alignment.

This is ambiguous: What happens if the alignment is a power of two but unsupported (e.g larger than __max_align__)? Is the returned storage aligned to __max_align__ or is an exception thrown?

**Comment by jensmaurer** [comment]
I've asked for an LWG issue.

**Comment by jensmaurer** [comment]
[LWG 2843](https://cplusplus.github.io/LWG/lwg-active.html#2843)
