### ISSUE TITLE
Unify the wording style of saying "T in Types"

### ISSUE THREAD

**Issue by lichray** [cplusplus/draft#974]
In some places we say "`T` in _Types_", some places say "`T` in _Types_...", and sometimes followed by a 4th dot (period).  We should switch all of these to use the first form.

**Comment by W-E-Brown** [comment]
> On Nov 9, 2016, at 9:36 AM, Zhihao Yuan <notifications@github.com> wrote:
> 
> In some places we say "T in Types", some places say "T in Types...", and sometimes followed by a 4th dot (period). We should switch all of these to use the first form.

While I don't at all mind a unified presentation style, this specific resolution would be not my first choice.

Instead, I recommend "for all T_i constituting Ts" (or, in some cases, "for each of the T_i constituting Ts").

If/when LWG discusses my pending common_type paper, I will lobby for such wording in at least that context.  (The published draft uses the word "comprise", but in this specific context, that's the wrong word.  If we want to invert the sentence ["Ts is comprised of"], we can keep "comprise", but that seems not universally applicable.)

-- WEB

**Comment by lichray** [comment]
On Nov 9, 2016 11:30 AM, "W-E-Brown" <notifications@github.com> wrote:
>
> Instead, I recommend "for all T_i constituting Ts" (or, in some cases,
"for each of the T_i constituting Ts").
>

I'm happy with this suggestion.

--
Zhihao

**Comment by jensmaurer** [comment]
Editorial meeting consensus: [tuple.elem] p3+4 is fine as-is, add "If a *type* T". p5 drop ellipsis after Types. Generally, we want to say "a type T in Types" if we want to talk about an element of the pack "Types".
